{100}{}{Вы видите мужчину. Он пристально смотрит вам в глаза и отворачивается.}
{101}{}{Вы видите Грега.}
{102}{}{Что? Зачем ты говоришь со мной? Они услышат и поймут, что ты ЗНАЕШЬ.}
{103}{}{Снова ты? Привет. Говори тише, за нами следят.}
{104}{}{Кончай орать, иначе они заметут и тебя, и меня.}
{105}{}{Кто ты?}
{106}{}{Ты чего такой нервный?}
{107}{}{Тебе не помешало бы подлечиться, друг.}
{108}{}{Ничего.}
{109}{}{Я Грег... Только никто об этом не должен знать, иначе они придут за мной.}
{110}{}{Нервный? Никакой я не нервный. Просто осторожный. Говорят, я параноик, но никто, кроме меня, не знает, что скоро они придут за нами.}
{111}{}{Они? Кто это - "они"?}
{112}{}{Очевидно, что ты параноик. Поговорим позже.}
{113}{}{Well, they are... You know, don't you? The disease was just the start. Now they're going to come and take us all. But you are just like all the rest. You won't believe me, and you'll be doomed. You mark my words: I'LL STILL BE HERE, and ALL OF THIS, INCLUDING YOU, WILL BE TAKEN. TAKEN! (He grasps his head and curls up, into a ball, squealing and thrashing about)}
{114}{}{Medication... Oh, so you're one of them, trying to get me to take my medication again... Well, you won't get me to. I WON'T TAKE IT! NO, I WON'T. THE VOICES. NO, I WON'T! YOU CAN'T MAKE ME. (He closes his eyes shut and clutches his head frantically, talking with the voices that only he can hear)}
{115}{}{Я ВАМ НЕ ПОДЧИНЮСЬ!}
{116}{}{ВАС НИЧТО НЕ СПАСЕТ!}
{117}{}{ВСЕ КОНЧЕНО!}
{118}{}{ОНИ ИДУТ, ВАМ ИХ НЕ ОСТАНОВИТЬ!}
{119}{}{ОНИ ДОБЕРУТСЯ ДО ВАС!}
