{100}{}{You see a scared, angry peasant.}
{101}{}{Вы видите Фила.}
{102}{}{Это не моя собака!}
{103}{}{Damn right, kill that beast!}
{104}{}{I wouldn't trust that monster, if I were you. That thing is a genuine killer.}
{105}{}{Мистер,}
{106}{}{Мэм,}
{107}{}{ я был бы счастлив, если бы вы мне помогли избавиться от этой проклятой собаки.}
{108}{}{Почему?}
{109}{}{Нет уж, я занимаюсь куда более важными делами.}
{110}{}{Откуда она взялась?}
{111}{}{Hnnng.}
{112}{}{Oh geez. Maybe you can talk it to death?}
{113}{}{Она не пускает нас домой, вот почему!}
{114}{}{Got it, thanks.}
{115}{}{Разве это не твоя собака?}
{116}{}{It was the "pet" of a traveler. When the traveler died, this stupid dog just plopped its furry ass down on my doorstep and wouldn't leave. It's been there for days.}
{117}{}{Oh. Thanks!}
{118}{}{А кто был этот путешественник?}
{119}{}{А как выглядел этот путешественник?}
{120}{}{Не знаю. Какой-то парень. Он сказал, что пришел с востока. Что-то мне не верится, что он прошел через мертвые земли на востоке. В общем, он попытался вмешаться в дела Гизмо.}
{121}{}{Так что парни Гизмо его избили и сбросили с крыши казино. Путешественник сломал шею и умер. А собака расстроилась.}
{122}{}{А как выглядел этот путешественник?}
{123}{}{Oh, the guy was tall, dark-haired with a little graying around the edges. He was dressed all in black leather, like that's a good idea in the desert; and carried a shotgun.}
{124}{}{He had some funny accent. The dog was his constant companion; followed him everywhere.}
{125}{}{Appreciate the info!}
{126}{}{I really hate this stupid dog.}
{127}{}{Thanks for your help, stranger.}
{128}{}{Wow, okay. See you around I guess. Asshole.}
