{100}{}{Вы видите Шута.}
{101}{}{Вы видите члена банды.}
{102}{}{Они называют нас Шутами, но вы просто глупы, чтобы появляться здесь.}
{103}{}{Ты собираешься что-то начать вместе с нами?}
{104}{}{Это не твое место.}
{105}{}{Don't think you can come walking in here and start something.}
{106}{}{Watch out, or you can end up in a crypt, Crypt.}
{107}{}{Да, мы займёмся этими Склепами.}
{108}{}{Scrapheap ain't gonna be the same without those Crypts. It's gonna be ours!}
{109}{}{Ха-ха-ха! Ха-ха-ха-ха!}
{110}{}{Шуты! Шуты! Шуты! Да!}
{111}{}{Didja hear the one about the chicken and the foxhole?}
{112}{}{Будет круто.}
{113}{}{He who laughs last, laughs last.}
{114}{}{Жизнь - это шутка, тьфу, черт возьми.}
{115}{}{If it wasn't for them Crypts, we would rule this town. Or at least kick Lenny in the crotch.}
{116}{}{Будь дураком.}
{117}{}{You think that puny leather will save you from Baka?}
{118}{}{What happened? Your mom drop you on your head at birth?}
{119}{}{Если бы я был таким уродом, я бы убил себя.}
{120}{}{You Crypts look like you just came out of one.}
{121}{}{Only a fool would try something that stupid. Oh, wait, I am a Fool.}
