{100}{}{You see a power generator. This must be what supplies electricity to the doors, elevators and lights in this complex.}
{101}{}{Генератор включен.}
{102}{}{Генератор выключен. Интересно, сможете ли вы включить его.}
{103}{}{Генератор уже включен.}
{104}{}{Вы запускаете генератор, и все системы включаются.}
{105}{}{Вам не удалось запустить генератор.}
{106}{}{Ваших навыков недостаточно, чтобы отремонтировать эту систему.}
{107}{}{You hear a constant mechanical humming on this level, which reminds you of something that you can't quite put your finger on...}
