{100}{}{Вы видите Склепа Райзе.}
{101}{}{Ну ты и Шут, что приперся сюда.}
{102}{}{Зачем ты меня беспокоишь?}
{103}{}{Меня послал Рок.}
{104}{}{Ничего, просто мимо прохожу.}
{105}{}{Расскажи мне про Шутов.}
{106}{}{Расскажи про генератор.}
{107}{}{А, ну да. Почему это?}
{108}{}{He said I could get a cold glass of water.}
{109}{}{Rock said the Crypts were looking for members.}
{110}{}{Хаха! Отличная попытка. Оставь меня в покое.}
{111}{}{Could be. It looks like you got some talent. You think you could be a Crypt?}
{112}{}{Да.}
{113}{}{Нет.}
{114}{}{Well, then. Let's try you out. We're gonna send you on a little mission. Go scout out the Fools to the north, and report back to me.}
{115}{}{Хорошо.}
{116}{}{Нет.}
{117}{}{Then little boys should leave before they get a spanking.}
{118}{}{We don't like strangers in our town. If you want to stay, you join us. If you don't, you might regret staying in Scrapheap.}
{119}{}{Как я могу присоединиться?}
{120}{}{I ask and you say yes. You swear an oath when you sign on. If you break that oath, I send some of my boys to break you.}
{121}{}{Ладно, я с вами.}
{122}{}{Что-то я не хочу играть.}
{123}{}{Мы не хотим тебя здесь видеть. Уходи, пока цел.}
{124}{}{Are the Fools ready for our attack?}
{125}{}{Да.}
{126}{}{Нет.}
{127}{}{Мне нужно еще поисследовать.}
{128}{}{It doesn't matter. Nothing will stop them from feeling the cold of death! They die now!}
{129}{}{Excellent. We will catch them unprepared. They die now!}
{130}{}{Hurry. I wish for the blood of Fools.}
{131}{}{They are my enemies. They will die. Now why do you bother me?}
{132}{}{Меня послал Рок.}
{133}{}{Ничего, просто мимо прохожу.}
{134}{}{Расскажи про генератор.}
{135}{}{You should not ask questions about things you don't know about. The generator is ours, and it will remain ours. As long as we have it, we are in control. You ask too many questions.}
{136}{}{[Готово]}
{137}{}{[дальше]}
{138}{}{Ха-ха! Убивайте побольше этих глупцов!!}
{139}{}{Одно наверняка точно, вы Шуты, будете править надгробной плитой.}
{140}{}{Помет Брамина пахнет лучше чем ты.}
{141}{}{Даже Ленни стреляет лучше.}
{142}{}{You should not have lied to me. I know better. Go, scout the Fools and return. Do not tempt me.}
{143}{}{You cannot be trusted. That is a shame. You will die. This is a pleasure.}
{144}{}{Теперь мы управляем этим городом!}
{145}{}{Сейчас не время для вопросов. Сейчас время сражаться!}
