{100}{}{Вы видите одинокого Паладина. Похоже, он испуган и зол.}
{101}{}{Остановись, незнакомец! Назови себя!}
{102}{}{Моя }
{103}{}{.}
{104}{}{Я }
{105}{}{. Что здесь произошло?}
{106}{}{Мое имя не имеет значения.}
{107}{}{Береги себя, }
{108}{}{, you may hurt yourself. An army of bad mutants came to this place and made a big boom. See?}
{109}{}{Ух-ха.}
{110}{}{See. So, you better find anoter place to go. It isn't safe here.}
{111}{}{И-ду.}
{112}{}{Mutants. It was a really big army. They came, killed everyone, took everything they could and blew this place up.}
{113}{}{Как же ты выжил?}
{114}{}{I was returning from a long range patrol. When I came the battle was already over. I couldn't do anything. So I hid and watched them.}
{115}{}{Хочешь сказать, ты был слишком напуган, чтобы что-то сделать?}
{116}{}{No one else survived this invasion?}
{117}{}{Look, I may not be the bravest man in Brotherhood, but I'm also not an idiot. There was really nothing, I could possibly do.}
{118}{}{Coward. Now stay and guard a bunch of ruins. I better go and kill some of those mutants of yours.}
{119}{}{Sorry. Did anyone else survived this massacre?}
{120}{}{Several scouting parties, some paladins on patrol... too little to do anything. Brotherhood of Steel is practically dead. I'll stay here for the time being, try to gather as many survivors as I can and tell them what happened here. Then... I actually don't know what's then. Never had a chance to even think about it.}
{121}{}{I understand. Keep up a good work, Paladin, I need to go.}
{122}{}{Прощай, }
{123}{}{. If you'll run into some Brotherhood survivors in your travels, tell them what's happened here.}
{124}{}{Стой где стоишь... Ох, это ты, }
{125}{}{.}
{126}{}{Ух-ха.}
{127}{}{Да, это я. Что здесь произошло?}
{130}{}{Прощай, }
{131}{}{. If you'll run into some of our fellow Brothers, tell them what's happened here.}
{132}{}{Конечно. Мне правда надо идти.}
{133}{}{Тогда иди. Мне нечего тебе сказать.}
{150}{}{The Paladin ignores you. It seems he's deep in his thoughts.}
