{100}{}{Вы видите Скиппи.}
{101}{}{Вы видите гуля-бандита.}
{102}{}{Он подбрасывает то, что в воздухе похоже на экзотический нож.}
{103}{}{[дальше]}
{104}{}{[Готово]}
{105}{}{[Tossing a set of blades near your face] Watch out, you clod. You might get hurt, and then I would have to laugh.}
{106}{}{Вы всматриваетесь, эти вещи выглядят острыми.}
{107}{}{Дай мне эти вещи, прежде чем причинить кому-то боль!}
{108}{}{Ни и чего ты мечешься?}
{109}{}{Они острые, безусловно они острее, чем твое остроумие.}
{110}{}{Ты бросаешь мне вызов?}
{111}{}{Ой, но я полагаю, что я заслужил это.}
{112}{}{Me? Challenge you? Oh, the very thought makes me chuckle. No, we Fools do not partake in the code duello. It is not our style. Let us show you how we treat outsiders.}
{113}{}{Действительно. Чем могу помочь?}
{114}{}{Что это за вещи?}
{115}{}{What they are is mine, what they will not be is yours. Beyond that, these cutters are a heirloom from my poor departed father. You might say he got a little caught up in them before he died! [Skippy laughs.]}
{116}{}{Ты дурочка. Могу я одолжить их?}
{117}{}{Well, since you asked nicely - okay. [He hands you the cutters.] Now, begone, for I must seek a new toy to pass the time.}
{118}{}{I think not, at least not handle-first. You shall weep blood, or at least cry with laughter and pain when I am done with you.}
{119}{}{Нам тут такие, как ты, не нужны. Уходи, или доиграешься.}
{120}{}{Well, if it isn't the latest Fool. A good sense of humor, at the very least. Perhaps some fine motor skills. We'll see. Play nice.}
{121}{}{You are a lucky fellow, my friend. This day is the day I will let you live. Unless, of course, you annoy me too much. Then I will have to use my best corpse jokes.}
{122}{}{Никогда не кради у Шутов, глупышка.}
{123}{}{Ты уже получила резаки от Скиппи. Прекрати, пока еще не поздно.}
{124}{}{Вам удалось украсть кусачки, пока он не смотрит.}
{125}{}{Вы оскорбляете нас и честь нашей Королевы. Некоторые оскорбления могут быть смыты только кровью.}
{126}{}{Ты умрешь, скотина!}
{127}{}{Is that your face, or did your neck throw up?}
{128}{}{You mother had to tie a steak around you to the dog would play with you}
{129}{}{Глупее тебя только Райзе.}
{130}{}{Я думаю, что после родов можно жить какое-то время.}
