{100}{}{Вы видите Кайла.}
{101}{}{What's up man, how are you doing? Still travellin' afoot... Aren't you tired? Maybe it's a time to think about cool wheels for your journeys? Are you ready to spend some money?}
{102}{}{Как я? Никогда не чувствовала себя лучше! И у вас действительно есть такой комплект колес для меня? Деньги не проблема.}
{103}{}{Если я тебя немного порежу, может быть, ты дашь мне его бесплатно?}
{104}{}{Это хороший вопрос. Кажется, мне нужно обратиться к тебе позже.}
{105}{}{Хм ... Ну, я не знаю. От более богатого покупателя может быть больше пользы. Послушай, почему бы тебе не вернуться позже, когда у тебя будет больше крышек?}
{106}{}{Believe me, a friend of mine has a REAL business. It seems, he is the only person in the wasteland who could sell you a car. The place is not so far away from here. It should take about one day to get there. Dude uses his own house as a parking garage... 400 caps would be enough for me to show you the way.}
{107}{}{Заметано. Покажи мне своего друга, а об остальном я позабочусь.}
{108}{}{Извини, Кайл. У меня есть более важные дела.}
{109}{}{Хорошо, я отведу тебя туда. Все что угодно для привлекательного клиента! Следуй за мной. [берёт 400 крышек]}
{110}{}{I knew you'd chicken out. Everyone is afraid of travel having so much money. However my raider friends will help you with that! [You come to understand that something went wrong, but suddenly a strong kick in the head knocks you down unconscious. Last thing you feel is that you are being dragged somewhere...]}
{111}{}{Слушай, отморозь. Свали. Твои угрозы пустые.}
{112}{}{Мне надо искать более удобного клиента.}
