{100}{}{Вы используете входной компьютер. Компьютер не признает ваш код доступа.}
{101}{}{Вы используете входной компьютер. Громкоговоритель потрескивает и возвращается к жизни.}
{102}{}{Прости, но мы не можем тебя сейчас снова впустить. Ну, технические трудности. Приходи снова попозже.}
{103}{}{Вы видите входной компьютер Убежища 13.}
{104}{}{Мы благодарны тебе за наше спасение, но я не могу впустить тебя.}
{105}{}{We're sorry, but you can't come back. We wish you the best.}
{106}{}{Смотритель сказал свое слово, вы должны уйти.}
{107}{}{Look, many of us are outraged with the Overseer's decision, but we must comply with his wishes.}
{108}{}{You must make your life in the outside world from now on. Good luck, friend.}
{109}{}{You are a danger to the future of this vault; leave at once.}
{110}{}{Мы не хотим тебя здесь видеть. Уходи.}
{111}{}{Мы не пускаем убийц в Убежище. Уходи!}
{112}{}{We are afraid of what you have become and what you may do to us. Leave.}
{113}{}{After what you did to the Overseer, you think we'll let you back?}
{114}{}{Как можно было совершить такое предательство?!}
{115}{}{Уходи, маньяк.}
{116}{}{The computer explodes in a spectacular shower of sparks and wiring, short-circuiting the entire configuration.}
{117}{}{Вы видите обломки входного компьютера Убежища 13.}
{118}{}{It's a total mess and completely beyond repair.}
{119}{}{ Эта дверь больше никогда не закроется.}
{120}{}{ Эта дверь больше никогда не откроется.}
{121}{}{Прямое попадание!}
{122}{}{Uh-oh! }
{123}{}{Компьютер в нерабочем состоянии.}
{124}{}{With the door forever sealed shut and no replacement Water Chip, the inhabitants of Vault 13 will soon discover that their Vault has become a tomb.}
