{100}{}{Вы используете входной компьютер. Компьютер не признает ваш код доступа.}
{101}{}{Вы используете входной компьютер. Громкоговоритель потрескивает и возвращается к жизни.}
{102}{}{Прости, но мы не можем тебя сейчас снова впустить. Ну, технические трудности. Приходи снова попозже.}
{103}{}{Вы видите входной компьютер Убежища 13.}
{104}{}{Мы благодарны тебе за наше спасение, но я не могу впустить тебя.}
{105}{}{Извини, но ты не можешь вернуться. Мы желаем тебе всего наилучшего.}
{106}{}{Смотритель сказал свое слово, ты должна уйти.}
{107}{}{Послушай, многие из нас возмущены решением Смотрителя, но мы должны выполнять его пожелания.}
{108}{}{С этого момента ты должна начать жить во внешнем мире. Удачи подруга.}
{109}{}{Ты представляешь опасность для будущего этого Убежища; немедленно уходи.}
{110}{}{Мы не хотим тебя здесь видеть. Уходи.}
{111}{}{Мы не пускаем убийц в Убежище. Уходи!}
{112}{}{Мы боимся того, кем ты стала и что ты можешь с нами сделать. Уходи.}
{113}{}{После того, что ты сделала со Смотрителем, ты думаешь мы тебя отпустим?}
{114}{}{Как можно было совершить такое предательство?!}
{115}{}{Уходи, маньяк.}
{116}{}{Компьютер взрывается впечатляющим градом из искр и проводов, вызывая короткое замыкание во всей системе.}
{117}{}{Вы видите обломки входного компьютера Убежища 13.}
{118}{}{Здесь полный беспорядок и полностью отсутствует ремонт.}
{119}{}{ Эта дверь больше никогда не закроется.}
{120}{}{ Эта дверь больше никогда не откроется.}
{121}{}{Мое лицо! Что ты сделал?!}
{122}{}{Мое лицо! Что ты сделал?!}
{123}{}{Компьютер в нерабочем состоянии.}
{124}{}{Когда дверь будет навсегда заперта и не будет замены водяного чипа, жители Убежища 13 быстро обнаружат, что их Убежище стало их гробницей.}
{125}{}{> Команда?}
{126}{}{Вы видите медика Убежища 13.}
{127}{}{Вы видите медика Убежища 13.}
{128}{}{Modify configuration parameters.}
{129}{}{Ничего страшного.}
{130}{}{Welcome to your SimTek 5000 interactive customization! Vault-Tec is committed to providing a pleasant integration into the outside world. Remember, incorrect settings may cause unstable anomalies! (Warranty void after 2077)}
{131}{}{Vault 13 door entry computer can't be accessed during combat.}
{132}{}{I understand.  [Execute "SPOILERS.EXE"]}
{133}{}{Opens!}
{134}{}{Do shut.}
{135}{}{Певец}
{136}{}{Пока.}
{137}{}{Boosh.  [Execute "SPOILERS.EXE"]}
{138}{}{Recalibrate Vault 13 water-level monitoring systems.}
{139}{}{View or modify simulation-terminating parameters.}
{140}{}{Супермутанты}
{141}{}{Classify situational combat options.}
{142}{}{Recalculate cross-wasteland encounter statistics.}
{143}{}{[Items, Inventory, Bartering]}
{144}{}{Нада шмотки.}
{145}{}{[Social sexy times]}
{146}{}{Hmm... Actually, let's go back.}
{147}{}{МНЕ ХОЧЕТСЯ!}
{148}{}{Thanks, I'm all set.  [Exit system]}
{149}{}{[выйти из системы]}
{150}{}{Okay, I'm done here.  [Go to main menu]}
{151}{}{Replay historical data feed.}
{152}{}{Calculating... System monitors indicate that Vault 13 water reserves are currently dropping at a steady rate. Estimated days left until total depletion: }
{153}{}{.  Enter new value to recalibrate system.  (Default database value: 150)}
{154}{}{> Команда?}
{155}{}{[30]}
{156}{}{[60]}
{157}{}{[90]}
{158}{}{[120]}
{159}{}{[150]}
{160}{}{[ЕЩЕ]}
{161}{}{[НАЗАД]}
{162}{}{[180]}
{163}{}{[210]}
{164}{}{[240]}
{165}{}{[270]}
{166}{}{[300]}
{167}{}{[330]}
{168}{}{[365]}
{169}{}{[730]}
{170}{}{[вернуться к главному меню]}
{171}{}{[125]}
{172}{}{[135]}
{173}{}{[140]}
{174}{}{[145]}
{175}{}{Align calibration with Overseer's estimates. [120 - 150]}
{176}{}{Or-seer nums! [120 - 150]}
{177}{}{[999]}
{178}{}{[64000]}
{179}{}{[130]}
{180}{}{Priority of Vault 13 waterchip-replacement subroutines.}
{181}{}{How to stop mutant invasions}
{182}{}{Reevaluate relative priority of Vault 13 survival vectors.}
{183}{}{[Endgame Condition: Can play after being dipped?]}
{184}{}{If the Wasteland will be as rough as it sounds, maybe I should take a moment to reflect on any personal neuroses that may affect my survival out there.}
{185}{}{Me strong is many smart. Maybe has crazies. Want big challenge! [Optional gameplay restrictions]}
{186}{}{If all other threats to the Vault are eliminated, our emergency wastewater redistribution protocol can negate the need for a Water Chip.  Protocol is currently: }
{187}{}{. Toggle protocol status?  (Default status: Enabled)}
{188}{}{DISABLED}
{189}{}{ENABLED}
{190}{}{Looks good; let's back up.  [Go to previous menu]}
{191}{}{Создатель}
{192}{}{Цистерны}
{193}{}{Вы видите Создателя супермутантов.}
{194}{}{Вы видите Создателя супермутантов.}
{195}{}{To stop invasions of towns, you currently need to eliminate: }
{196}{}{ Change requirement for cessation?  (Default requirement: The Master)}
{197}{}{Checking... By default, this simulation will terminate if sensors indicate Vault 13 Survivability has dropped to zero. Current setting: }
{198}{}{Объявить тревогу по базе.}
{199}{}{Нет.}
{200}{}{Me done! Where other?  [Go to previous menu]}
{201}{}{Да.}
{202}{}{!}
{203}{}{Пайки}
{204}{}{Навыки}
{205}{}{Party members}
{206}{}{[Custom playstyles]}
{207}{}{[Misc]}
{208}{}{Thank you for trusting Vault-Tec and SimTek 5000 with your customization needs! Please state a command.}
{209}{}{Simulation terminates when Survivability reaches zero.}
{210}{}{Simulation can continue if the source was foreign.}
{211}{}{Simulation can continue if the source was organic.}
{212}{}{Simulation continues regardless of Survivability rating.}
{213}{}{Can the player keep playing after/if they've become a Super Mutant? Current seting: }
{214}{}{ (Default: No.)}
{215}{}{[SPECIAL]}
{216}{}{Святилище}
{217}{}{Некрополь.}
{218}{}{Хаб}
{219}{}{Не-а.}
{220}{}{Братство Стали.}
{221}{}{Джанктаун.}
{222}{}{Из Шэйди Сэндс.}
{223}{}{Из Убежища 13.}
{224}{}{Итак, назовите характеристику, и я расскажу вам об операции.}
{225}{}{You are viewing number of days until invasion of }
{226}{}{У вас сейчас $ }
{227}{}{. Select new value below to modify.  (Default value: }
{228}{}{)}
{229}{}{Instant (0 days)}
{230}{}{1/4 of default.}
{231}{}{1/2 of default.}
{232}{}{Элитный воин Убежища.}
{233}{}{Виноват!}
{234}{}{Виноват!}
{235}{}{Виноват!}
{236}{}{Disabled. (this location will not be invaded)}
{237}{}{Вы упали на землю.}
{238}{}{Does player receive dadiation-on-hit from critters?}
{239}{}{Specifics of Childkiller status}
{240}{}{Ambient light and Flares}
{241}{}{}
{242}{}{}
{243}{}{}
{244}{}{}
{245}{}{}
{246}{}{}
{247}{}{Hardcore: No loading saves. Must complete in 1 session.}
{248}{}{Codependent Loser: If a hireling leaves or dies, game over.}
{249}{}{Lone Wolf: If you get party members, game over}
{250}{}{Pacifist: If player lands any hit in combat, game over.}
{251}{}{Killswitch: If combat mode is ever activated, game over.}
{252}{}{I Like It Hard: difficulty_level of Hard only.}
{253}{}{I Like It Rough: combat_difficulty of Rough only.}
{254}{}{Specify if any of the following characteristics apply to you, and sensors will adapt accordingly.}
{255}{}{I'm Special: If your stats are ever raised, game over.}
{256}{}{ This playstyle is currently: }
{257}{}{. Toggle status?}
{258}{}{Weapon Drop Mod is currently: }
{259}{}{hexes from corpse. Your command?}
{260}{}{уронил оружие}
{261}{}{Приступай!}
{262}{}{1    Да, отключить его.}
{263}{}{Enable it, with a drop distance of 0 hexes from corpse.}
{264}{}{Enable it, with a drop distance of 0-1 hexes from corpse.}
{265}{}{Enable it, with a drop distance of 0-2 hexes from corpse.}
{266}{}{Enable it, with a drop distance of 1 hex from corpse.}
{267}{}{Enable it, with a drop distance of 1-2 hexes from corpse.}
{268}{}{Enable it, with a drop distance of 2 hexes from corpse.}
{269}{}{No creatures will irradiate the player upon landing an attack. Which type do you wish to toggle?}
{270}{}{Интеллект}
{271}{}{, }
{272}{}{will have a chance to irradiate the player when landing hits, based on Combat Difficulty and player's stats. Which type do you wish to toggle?}
{273}{}{Облученная крыса}
{274}{}{Летуны}
{275}{}{Кентавры:}
{276}{}{Вы видите светящегося гуля.}
{277}{}{Вы видите светящегося гуля.}
{278}{}{Glowing Ghouls and Irradiated Rats only, with a max of 1 rad per hit (2077 field manual defaults)}
{279}{}{Only glowing ghouls and irradiated rats will have a chance to irradiate the player when landing hits, with 1/6 chance of 1 rad per hit. Which type do you wish to toggle?}
{280}{}{Number of times can upgrade Plasma Rifle and Power Armor?}
{281}{}{Items received at start of game}
{282}{}{Миссис Стэплтон}
{283}{}{Киллиан}
{284}{}{Разрывная ракета}
{285}{}{Броня}
{286}{}{Голодиск}
{287}{}{Swap knockback/no-knockback on Sledgehammers}
{288}{}{Settings for specific traders/merchants}
{289}{}{Military Base red forcefields - who do they damage?}
{290}{}{6  Шейди Сэндс,  Военная База}
{291}{}{Can hired NPCs level up at all?}
{292}{}{How many player levels per NPC levelup?}
{293}{}{Is levelup tracking relative or absolute?}
{294}{}{After joining the player's team, can Ian/Tycho/Katja gain levels? (Currently they }
{295}{}{Я могу.}
{296}{}{cannot.)}
{297}{}{ Vanilla default: hired NPCs did not gain levels.}
{298}{}{[1]}
{299}{}{[2]}
{300}{}{[3]}
{301}{}{[4]}
{302}{}{[5]}
{303}{}{[6]}
{304}{}{[7]}
{305}{}{[8]}
{306}{}{How many player levels does it take to trigger a hireling levelup?. (Currently it takes }
{307}{}{ player level for an NPC to gain one level.)  NPC Mod default: 4.}
{308}{}{ player levels for an NPC to gain one level.)  NPC Mod default: 4.}
{309}{}{When hirelings join your team, should they immediately levelup to be what they would if you'd gotten them at level 1?  (Currently they }
{310}{}{do.)  NPC Mod default: Do not.}
{311}{}{do not.)  NPC Mod default: Do not.}
{312}{}{}
{313}{}{}
{314}{}{}
{315}{}{}
{316}{}{}
{317}{}{}
{318}{}{Number of Turbo Plasma Rifle upgrades allowed?}
{319}{}{Number of Power Armor upgrades allowed?}
{320}{}{Player will be able to upgrade this many Plasma Rifles: }
{321}{}{Player will be able to upgrade this many Power Armors: }
{322}{}{. Select a new value if desired.  (Vanilla default: 1)}
{323}{}{To switch between standard and no-knockback version of sledgehammer items, choose an option below.}
{324}{}{Remove knockback from all Super Sledges in player's inventory.}
{325}{}{Remove knockback from all regular Sledgehammers in player's inventory.}
{326}{}{Add knockback to all Super Sledges in player's inventory.}
{327}{}{Add knockback to all regular Sledgehammers in player's inventory.}
{328}{}{Система очистки воздуха}
{329}{}{}
{330}{}{}
{331}{}{}
{332}{}{}
{333}{}{}
{334}{}{}
{335}{}{}
{336}{}{}
{337}{}{}
{338}{}{}
{339}{}{}
{340}{}{}
{341}{}{}
{342}{}{}
{343}{}{}
{344}{}{}
{345}{}{}
{346}{}{}
{347}{}{}
{348}{}{}
{349}{}{}
{350}{}{}
{351}{}{}
{352}{}{}
{353}{}{}
{354}{}{}
{355}{}{}
{356}{}{}
{357}{}{}
{358}{}{}
{359}{}{}
{360}{}{}
{361}{}{}
{362}{}{}
{363}{}{}
{364}{}{}
{365}{}{}
{366}{}{}
{367}{}{}
{368}{}{}
{369}{}{}
{370}{}{}
{371}{}{}
{372}{}{}
{373}{}{}
{374}{}{}
{375}{}{}
{376}{}{}
{377}{}{}
{378}{}{}
{379}{}{}
{380}{}{}
{381}{}{}
{382}{}{}
{383}{}{}
{384}{}{}
{385}{}{}
{386}{}{}
{387}{}{}
{388}{}{}
{389}{}{}
{390}{}{}
{391}{}{}
{392}{}{}
{393}{}{}
{394}{}{}
{395}{}{}
{396}{}{}
{397}{}{}
{398}{}{}
{399}{}{}
{400}{}{}
{401}{}{}
{402}{}{}
{403}{}{}
{404}{}{}
{405}{}{}
{1000}{}{Вы взломали компьютер.}
{1001}{}{Хмм... интересно, что изменяет эта настройка?}
