{0}{}{DESERT1.MAP}
{1}{}{DESERT2.MAP}
{2}{}{DESERT3.MAP}
{3}{}{HALLDED.MAP}
{4}{}{HOTEL.MAP}
{5}{}{WATRSHD.MAP}
{6}{}{VAULT13.MAP}
{7}{}{VAULTENT.MAP}
{8}{}{VAULTBUR.MAP}
{9}{}{VAULTNEC.MAP}
{10}{}{JUNKENT.MAP}
{11}{}{JUNKCSNO.MAP}
{12}{}{JUNKKILL.MAP}
{13}{}{BROHDENT.MAP}
{14}{}{BROHD12.MAP}
{15}{}{BROHD34.MAP}
{16}{}{CAVES.MAP}
{17}{}{CHILDRN1.MAP}
{18}{}{CHILDRN2.MAP}
{19}{}{CITY1.MAP}
{20}{}{COAST1.MAP}
{21}{}{COAST2.MAP}
{22}{}{COLATRUK.MAP}
{23}{}{FSAUSER.MAP}
{24}{}{RAIDERS.MAP}
{25}{}{SHADYE.MAP}
{26}{}{SHADYW.MAP}
{27}{}{GLOWENT.MAP}
{28}{}{LAADYTUM.MAP}
{29}{}{LAFOLLWR.MAP}
{30}{}{MBENT.MAP}
{31}{}{MBSTRG12.MAP}
{32}{}{MBVATS12.MAP}
{33}{}{MSTRLR12.MAP}
{34}{}{MSTRLR34.MAP}
{35}{}{V13ENT.MAP}
{36}{}{HUBENT.MAP}
{37}{}{DETHCLAW.MAP}
{38}{}{HUBDWNTN.MAP}
{39}{}{HUBHEIGT.MAP}
{40}{}{HUBOLDTN.MAP}
{41}{}{HUBWATER.MAP}
{42}{}{GLOW1.MAP}
{43}{}{GLOW2.MAP}
{44}{}{LABLADES.MAP}
{45}{}{LARIPPER.MAP}
{46}{}{LAGUNRUN.MAP}
{47}{}{CHILDEAD.MAP}
{48}{}{MBDEAD.MAP}
{49}{}{MOUNTN1.MAP}
{50}{}{MOUNTN2.MAP}
{51}{}{FOOT.MAP}
{52}{}{TARDIS.MAP}
{53}{}{TALKCOW.MAP}
{54}{}{USEDCAR.MAP}
{55}{}{BRODEAD.MAP}
{56}{}{DESCRVN1.MAP}
{57}{}{DESCRVN2.MAP}
{58}{}{MNTCRVN1.MAP}
{59}{}{MNTCRVN2.MAP}
{60}{}{VIPERS.MAP}
{61}{}{DESCRVN3.MAP}
{62}{}{MNTCRVN3.MAP}
{63}{}{DESCRVN4.MAP}
{64}{}{MNTCRVN4.MAP}
{65}{}{HUBMIS0.MAP}
{66}{}{HUBMIS1.MAP}
{100}{}{Desert}
{101}{}{Desert}
{102}{}{Desert}
{103}{}{Nécropolis}
{104}{}{Nécropolis}
{105}{}{Nécropolis}
{106}{}{Vault 13}
{107}{}{Vault 15}
{108}{}{Vault 15}
{109}{}{Vault 12}
{110}{}{Dépôtville}
{111}{}{Dépôtville}
{112}{}{Dépôtville}
{113}{}{Confrérie de l'Acier}
{114}{}{Confrérie de l'Acier}
{115}{}{Confrérie de l'Acier}
{116}{}{Sables Ombragés}
{117}{}{Cathedral}
{118}{}{Cathedral}
{119}{}{City}
{120}{}{Coast}
{121}{}{Coast}
{122}{}{Desert}
{123}{}{Desert}
{124}{}{The Khans}
{125}{}{Sables Ombragés}
{126}{}{Sables Ombragés}
{127}{}{The Glow}
{128}{}{L.A. Boneyard}
{129}{}{L.A. Boneyard}
{130}{}{Military Base}
{131}{}{Military Base}
{132}{}{Military Base}
{133}{}{UNUSED}
{134}{}{UNUSED}
{135}{}{Vault 13}
{136}{}{The Hub}
{137}{}{The Hub}
{138}{}{The Hub}
{139}{}{The Hub}
{140}{}{The Hub}
{141}{}{The Hub}
{142}{}{The Glow}
{143}{}{The Glow}
{144}{}{L.A. Boneyard}
{145}{}{L.A. Boneyard}
{146}{}{L.A. Boneyard}
{147}{}{Ruins}
{148}{}{Military Base}
{149}{}{Mountains}
{150}{}{Mountains}
{151}{}{Desert}
{152}{}{Desert}
{153}{}{Desert}
{154}{}{Desert}
{155}{}{Confrérie de l'Acier}
{156}{}{Desert}
{157}{}{Desert}
{158}{}{Mountains}
{159}{}{Mountains}
{160}{}{Viper Camp}
{161}{}{Desert}
{162}{}{Mountains}
{163}{}{Desert}
{164}{}{Mountains}
{165}{}{The Hub}
{166}{}{The Hub}
{200}{}{Wasteland}
{201}{}{Wasteland}
{202}{}{Wasteland}
{203}{}{Wasteland}
{204}{}{Wasteland}
{205}{}{Wasteland}
{206}{}{Wasteland}
{207}{}{Wasteland}
{208}{}{Wasteland}
{209}{}{Sewers under Hall}
{210}{}{Hall of the Dead}
{211}{}{Sewers under Hall}
{212}{}{Sewers under Hotel}
{213}{}{Hotel of Doom}
{214}{}{Sewers under Hotel}
{215}{}{Sewers under Watershed}
{216}{}{The Watershed}
{217}{}{Sewers under Watershed}
{218}{}{Entrance, Medical}
{219}{}{Living Quarters}
{220}{}{Library, Supplies, Command}
{221}{}{Old Shack}
{222}{}{Cavern Entrance}
{223}{}{Cavern Entrance}
{224}{}{Living Quarters}
{225}{}{Library, Supplies, Command}
{226}{}{Library, Supplies, Command}
{227}{}{Level 1 (Sewer Entrance)}
{228}{}{Level 2 (Living Quarters)}
{229}{}{Level 3 (Command Center)}
{230}{}{Entrance, Hospital}
{231}{}{Doc Morbid's Lab}
{232}{}{Doc Morbid's Lab}
{233}{}{Casino, Bar}
{234}{}{Casino, Bar}
{235}{}{Casino, Bar}
{236}{}{General Store, Hotel}
{237}{}{General Store, Hotel}
{238}{}{General Store, Hotel}
{239}{}{Entrance}
{240}{}{Entrance}
{241}{}{Entrance}
{242}{}{Level 1}
{243}{}{Level 2}
{244}{}{Level 2}
{245}{}{Level 3}
{246}{}{Level 4}
{247}{}{Level 4}
{248}{}{Radscorpion Cave}
{249}{}{Radscorpion Cave}
{250}{}{Radscorpion Cave}
{251}{}{Entrance}
{252}{}{Tower Level 1}
{253}{}{}
{254}{}{Tower Level 2}
{255}{}{Tower Level 3}
{256}{}{Tower Level 4}
{257}{}{Ruins}
{258}{}{Ruins}
{259}{}{Ruins}
{260}{}{Shoreline}
{261}{}{Shoreline}
{262}{}{Shoreline}
{263}{}{Shoreline}
{264}{}{Shoreline}
{265}{}{Shoreline}
{266}{}{Overturned Truck}
{267}{}{Overturned Truck}
{268}{}{Overturned Truck}
{269}{}{Spacecraft}
{270}{}{Spacecraft}
{271}{}{Spacecraft}
{272}{}{Base Camp}
{273}{}{Base Camp}
{274}{}{Base Camp}
{275}{}{Garden, Brahma Pen}
{276}{}{Garden, Brahma Pen}
{277}{}{Garden, Brahma Pen}
{278}{}{Entrance, Town Hall}
{279}{}{Entrance, Town Hall}
{280}{}{Entrance, Town Hall}
{281}{}{Entrance}
{282}{}{Entrance}
{283}{}{Entrance}
{284}{}{Adytum}
{285}{}{Underground}
{286}{}{}
{287}{}{Library}
{288}{}{Underground}
{289}{}{}
{290}{}{Entrance}
{291}{}{Entrance}
{292}{}{Entrance}
{293}{}{Stronghold Level 1}
{294}{}{Stronghold Level 2}
{295}{}{}
{296}{}{Vats Level 1}
{297}{}{Vats Level 2}
{298}{}{}
{299}{}{Lair Level 1}
{300}{}{Lair Level 2}
{301}{}{}
{302}{}{Lair Level 3}
{303}{}{Lair Level 4}
{304}{}{}
{305}{}{Cavern, Vault Door}
{306}{}{Cavern, Vault Door}
{307}{}{Cavern, Vault Door}
{308}{}{Entrance, Caravaners}
{309}{}{Entrance, Caravaners}
{310}{}{Entrance, Caravaners}
{311}{}{Deathclaw Lair}
{312}{}{Deathclaw Lair}
{313}{}{Deathclaw Lair}
{314}{}{Downtown, Market, Casino}
{315}{}{Decker's Hideout}
{316}{}{Decker's Hideout}
{317}{}{Heights, Hightower}
{318}{}{Heights, Hightower}
{319}{}{Heights, Hightower}
{320}{}{Old Town}
{321}{}{Thieves' Circle}
{322}{}{Thieves' Circle}
{323}{}{Water Merchants, Church}
{324}{}{Water Merchants, Church}
{325}{}{Water Merchants, Church}
{326}{}{Level 1}
{327}{}{Level 2}
{328}{}{Level 3}
{329}{}{Level 4}
{330}{}{Level 5}
{331}{}{Level 6}
{332}{}{Downtown}
{333}{}{Downtown}
{334}{}{Downtown}
{335}{}{Warehouse}
{336}{}{Underground}
{337}{}{}
{338}{}{Forteresse}
{339}{}{Forteresse}
{340}{}{Forteresse}
{341}{}{Crater}
{342}{}{Crater}
{343}{}{Crater}
{344}{}{Ruins}
{345}{}{Ruins}
{346}{}{Ruins}
{347}{}{Pass}
{348}{}{Pass}
{349}{}{Pass}
{350}{}{Pass}
{351}{}{Pass}
{352}{}{Pass}
{353}{}{Footprint}
{354}{}{Footprint}
{355}{}{Footprint}
{356}{}{Police Box}
{357}{}{Police Box}
{358}{}{Police Box}
{359}{}{Talking Cows}
{360}{}{Talking Cows}
{361}{}{Talking Cows}
{362}{}{Pre-Owned Cars}
{363}{}{Pre-Owned Cars}
{364}{}{Pre-Owned Cars}
{365}{}{Ruins}
{366}{}{Ruins}
{367}{}{Ruins}
{368}{}{Caravan Encounter}
{369}{}{Caravan Encounter}
{370}{}{Caravan Encounter}
{371}{}{Caravan Encounter}
{372}{}{Caravan Encounter}
{373}{}{Caravan Encounter}
{374}{}{Caravan Encounter}
{375}{}{Caravan Encounter}
{376}{}{Caravan Encounter}
{377}{}{Caravan Encounter}
{378}{}{Caravan Encounter}
{379}{}{Caravan Encounter}
{380}{}{Vipers' Camp}
{381}{}{Vipers' Camp}
{382}{}{Vipers' Camp}
{383}{}{Caravan Encounter}
{384}{}{Caravan Encounter}
{385}{}{Caravan Encounter}
{386}{}{Caravan Encounter}
{387}{}{Caravan Encounter}
{388}{}{Caravan Encounter}
{389}{}{Caravan Encounter}
{390}{}{Caravan Encounter}
{391}{}{Caravan Encounter}
{392}{}{Caravan Encounter}
{393}{}{Caravan Encounter}
{394}{}{Caravan Encounter}
{395}{}{Irwin's Farm}
{396}{}{Irwin's Farm}
{397}{}{Irwin's Farm}
{398}{}{Irwin's Farm}
{399}{}{Irwin's Farm}
{400}{}{Irwin's Farm}
{500}{}{Vault 13}
{501}{}{Vault 15}
{502}{}{Sables Ombragés}
{503}{}{Dépôtville}
{504}{}{The Khans}
{505}{}{Nécropolis}
{506}{}{The Hub}
{507}{}{Confrérie de l'Acier}
{508}{}{Mariposa Military Base}
{509}{}{The Glow}
{510}{}{L.A. Boneyard}
{511}{}{Children's Cathedral}
{1000}{}{ERROR: Not enough disk space to save map!}
