{100}{}{Strength}
{101}{}{Perception}
{102}{}{Endurance}
{103}{}{Charisma}
{104}{}{Intelligence}
{105}{}{Agility}
{106}{}{Luck}
{107}{}{Maximum Hit Points}
{108}{}{Maximum Action Points}
{109}{}{Armor Class}
{110}{}{Unarmed Damage}
{111}{}{Nahkampf-Sch.}
{112}{}{Carry Weight}
{113}{}{Sequence}
{114}{}{Healing Rate}
{115}{}{Critical Chance}
{116}{}{Better Criticals}
{117}{}{Damage Threshold}
{118}{}{Damage Threshold Laser}
{119}{}{Damage Threshold Fire}
{120}{}{Damage Threshold Plasma}
{121}{}{Damage Threshold Electrical}
{122}{}{Damage Threshold EMP}
{123}{}{Damage Threshold Explosion}
{124}{}{Damage Resistance}
{125}{}{Damage Resistance Laser}
{126}{}{Damage Resistance Fire}
{127}{}{Damage Resistance Plasma}
{128}{}{Damage Resistance Electrical}
{129}{}{Damage Resistance EMP}
{130}{}{Damage Resistance Explosion}
{131}{}{Radiation Resistance}
{132}{}{Poison Resistance}
{133}{}{Age}
{134}{}{Gender}
{135}{}{Current Hit Points}
{136}{}{Current Poison Level}
{137}{}{Current Radiation Level}
{200}{}{Raw physical strength. A high Strength is good for combat-based characters and packrats. Modifies: Hit Points, Melee Damage, and Carry Weight.}
{201}{}{Fähigkeit, ungewöhnliche Dinge zu sehen, zu hören, zu schmecken und wahrzunehmen. Eine gute Wahrnehmung ist z.B. für Scharfschützen wichtig. Beeinflusst: Reaktions- und Distanzkampffaktoren.}
{202}{}{Kondition und Belastbarkeit. Eine Figur mit hoher Ausdauer überlebt, wo andere längst sterben. Beeinflusst: Trefferpunkte, Resistenz gegen Gift u. Strahlung, Heilung, Zusatztrefferpunkte pro Level.}
{203}{}{Kombination aus äußerer Erscheinung und Charme. Ein ausgeprägtes Charisma ist für Figuren wichtig, die Menschen mit Worten beeinflussen wollen. Beeinflusst: Reaktionen von inaktiven Figuren und Preise beim Handeln.}
{204}{}{Wissen, Weisheit und schnelles Denkvermögen. Eine hohe Intelligenz ist für jede Figur wichtig. Beeinflusst: Anzahl der neuen Fähigkeitspunkte pro Level, Dialogoptionen und viele Fähigkeiten.}
{205}{}{Coordination and the ability to move well. A high Agility is important for any active character. Modifies: Action Points, Armor Class, Sequence, and many skills.}
{206}{}{Fate. Karma. An extremely high or low Luck will affect the character - somehow. Events and situations will be changed by how lucky (or unlucky) your character is.}
{207}{}{How much damage your character can take before dying. If you reach 0 hit points or less, you are dead.}
{208}{}{Represents the number of actions that your character can take during one combat turn. Different types of actions require different amounts of Action Points to perform.}
{209}{}{Modifies the chance to successfully hit your character during ranged or melee combat. Higher is better.}
{210}{}{The amount of bonus damage your character does in hand-to-hand combat.}
{211}{}{The amount of bonus damage your character does in hand-to-hand combat.}
{212}{}{The maximum amount of equipment your character can carry, in pounds.}
{213}{}{Determines how soon in combat your character can take their turn. Higher is better. With a high enough Sequence, you can effectively "ambush" your opponents, getting two turns in a row.}
{214}{}{When you rest, you heal this amount of hit points every four hours.}
{215}{}{The chance to cause a critical hit in combat is equal to this amount. Critical hits always cause more damage, and can also blind, cripple, knock out or instantly kill an opponent. Ouch.}
{216}{}{Better Criticals}
{217}{}{Damage Threshold}
{218}{}{Damage Threshold Laser}
{219}{}{Damage Threshold Fire}
{220}{}{Damage Threshold Plasma}
{221}{}{Damage Threshold Electrical}
{222}{}{Damage Threshold EMP}
{223}{}{Damage Threshold Explosion}
{224}{}{Any damage taken is reduced by this amount. Damage Resistance can be increased by wearing armor.}
{225}{}{Damage Resistance Laser}
{226}{}{Damage Resistance Fire}
{227}{}{Damage Resistance Plasma}
{228}{}{Damage Resistance Electrical}
{229}{}{Damage Resistance EMP}
{230}{}{Damage Resistance Explosion}
{231}{}{When exposed to radiation, the amount you absorb is reduced by this percentage. Radiation Resistance can be modified by the type of armor worn, and anti-radiation drugs.}
{232}{}{Reduces the poison damage you receive by this percentage.}
{233}{}{Age}
{234}{}{Gender}
{235}{}{Current Hit Points}
{236}{}{Current Poison Level}
{237}{}{Current Radiation Level}
{301}{}{V. Bad}
{302}{}{Bad}
{303}{}{Poor}
{304}{}{Fair}
{305}{}{Average}
{306}{}{Good}
{307}{}{V. Good}
{308}{}{Great}
{309}{}{Excellent}
{310}{}{Heroic}
{400}{}{Unspent Skill Points}
{401}{}{Level}
{402}{}{Experience}
{403}{}{Reputation}
{404}{}{Karma}
{500}{}{Points earned by going up a Level. Can be used to increase a skill by 1%, or a tag skill by 2%, per point spent.}
{501}{}{The general competency of the player character. A measure of your experience and abilities.}
{502}{}{A reward for completing specific tasks, or defeating enemies in combat. More experience is required to attain higher Levels.}
{503}{}{Was die Welt von deinen Handlungen und Taten weiß. Beeinflusst die Reaktionen von inaktiven Figuren.}
{504}{}{The effects of actions that you have taken. Important information will be displayed.}
{600}{}{You have gained a level!}
