{0}{}{SAVE GAME}
{1}{}{LOAD GAME}
{2}{}{PREFERENCES}
{3}{}{EXIT GAME}
{4}{}{DONE}
{100}{}{GAME PREFERENCES}
{101}{}{GAME DIFFICULTY}
{102}{}{COMBAT DIFFICULTY}
{103}{}{VIOLENCE LEVEL}
{104}{}{TARGET HIGHLIGHT}
{105}{}{UNUSED}
{106}{}{COMBAT MESSAGES}
{107}{}{COMBAT FLOATS}
{108}{}{LANGUAGE FILTER}
{109}{}{PLAYER RUNNING}
{110}{}{SUBTITLES}
{111}{}{ITEM HIGHLIGHT}
{112}{}{COMBAT SPEED}
{113}{}{FLOAT MESSAGES LIFESPAN}
{114}{}{MASTER AUDIO VOLUME}
{115}{}{MUSIC AND MOVIE VOLUME}
{116}{}{SOUND EFFECTS VOLUME}
{117}{}{SPEECH VOLUME}
{118}{}{BRIGHTNESS / CONTRAST}
{119}{}{MOUSE SENSITIVITY}
{120}{}{DEFAULT}
{121}{}{CANCEL}
{122}{}{Affect player speed?}
{123}{}{UNUSED}
{201}{}{On}
{202}{}{Off}
{203}{}{Easy}
{204}{}{Normal}
{205}{}{Hard}
{206}{}{Wimpy}
{207}{}{Normal}
{208}{}{Rough}
{209}{}{Normal}
{210}{}{Fastest}
{211}{}{Verbose}
{212}{}{Brief}
{213}{}{Targeting Only}
{214}{}{None}
{215}{}{Minimal}
{216}{}{Maximum Blood}
{217}{}{8 seconds}
{218}{}{Fast}
{219}{}{Always}
{220}{}{Lots}
{221}{}{Quiet}
{222}{}{Loud}
{223}{}{Brighter}
{224}{}{Wide}
{300}{}{UNPAUSE}
{301}{}{PAUSED}
{1000}{}{UNUSED}
{1001}{}{UNUSED}
