{10}{}{<None>}
{100}{}{Glass}
{101}{}{Metal}
{102}{}{Plastic}
{103}{}{Wood}
{104}{}{Dirt}
{105}{}{Stone}
{106}{}{Cement}
{107}{}{Leather}
{150}{}{Armor}
{151}{}{Container}
{152}{}{Drug}
{153}{}{Weapon}
{154}{}{Ammo}
{155}{}{Misc Item}
{156}{}{Key}
{200}{}{Portal}
{201}{}{Stairs}
{202}{}{Elevator}
{203}{}{Ladder Bottom}
{204}{}{Ladder Top}
{205}{}{Generic Scenery}
{250}{}{normal_dam}
{251}{}{laser}
{252}{}{fire}
{253}{}{plasma}
{254}{}{electrical}
{255}{}{emp}
{256}{}{explosion}
{300}{}{None}
{301}{}{Rocket}
{302}{}{Flamer Fuel}
{303}{}{C Energy Cell}
{304}{}{D Energy Cell}
{305}{}{.223}
{306}{}{5mm}
{307}{}{.40 cal}
{308}{}{10mm}
{309}{}{.44 cal}
{310}{}{14mm}
{311}{}{12-gauge}
{312}{}{9mm}
{313}{}{BB}
{314}{}{RESERVED}
{315}{}{RESERVED}
{316}{}{RESERVED}
{317}{}{RESERVED}
{318}{}{RESERVED}
{350}{}{Caucasian}
{351}{}{African}
{400}{}{Biped}
{401}{}{Quadruped}
{402}{}{Robotic}
{450}{}{Men:}
{451}{}{Women:}
{452}{}{Children:}
{453}{}{Super Mutants:}
{454}{}{Ghouls:}
{455}{}{Brahmin:}
{456}{}{Radscorpions:}
{457}{}{Rats:}
{458}{}{Floaters:}
{459}{}{Centaurs:}
{460}{}{Robots:}
{461}{}{Dogs:}
{462}{}{Manti:}
{463}{}{Deathclaws:}
{464}{}{The Master:}
{465}{}{This is the number of adult human males that you have permanently and forcefully removed from the gene pool.}
{466}{}{This is the number of adult human females that you have brutally snuffed out during the course of your adventures.}
{467}{}{This is how many bright futures of innocent defenseless human children you have shattered with your murderous ways. You cad.}
{468}{}{This is the total number of big scary Super Mutants that you have skillfully massacred throughout the wastes.}
{469}{}{This is how many irradiated zombie-like creatures you have laid to rest. Includes both males and females. (Not that they look any different to you anyway.)}
{470}{}{This is the tally of how many brahmin (mutant two-headed cows) you have chopped up and butchered during your travels.}
{471}{}{This is the number of huge mutated scorpions that you have exterminated as you strode the land.}
{472}{}{This is the number of cute furry rats that you have eliminated from the food chain. Includes all members of the rat family.}
{473}{}{This is the total number of strange mutated floating creatures that you have happily put to death.}
{474}{}{This is the tally of how many freakish multi-headed many-legged Centaurs you have had the pleasure of executing.}
{475}{}{The total number of robots that you have terminated with extreme prejudice, turned into spare parts, or otherwise disabled.}
{476}{}{This line shows how many nice friendly doggies you have sent to the great kennel in the sky, you heartless jerk.}
{477}{}{This is the total number of manti (oversized mutated preying mantis-like insects) that you have squashed so far.}
{478}{}{This line indicates that you have slain the legendary Deathclaw, and/or any of her many ferocious spawn. Well done.}
{479}{}{This indicates you have killed the Master. Master! Master.}
{480}{}{You see: %s.}
{485}{}{You search the %s.}
{486}{}{You close the %s.}
{487}{}{It is locked.}
{490}{}{You see: %s.}
{491}{}{You see a dead: %s.}
{492}{}{You see the remains of: %s.}
{493}{}{You see nothing out of the ordinary.}
{500}{}{Dead}
{501}{}{Almost Dead}
{502}{}{Severely Wounded}
{503}{}{Wounded}
{504}{}{Unhurt}
{510}{}{AC Mod: %d}
{511}{}{RV-Mod: %d}
{512}{}{Dmg Mod: %d/%d}
{518}{}{You look: %s }
{519}{}{%s %s }
{520}{}{You look: %s.}
{521}{}{%s %s.}
{522}{}{He looks: %s }
{523}{}{She looks: %s }
{524}{}{It looks: %s }
{525}{}{%s has %d/%d hit points.}
{526}{}{It has %d/%d shots of %s.}
{530}{}{and has crippled limbs.}
{531}{}{but has crippled limbs.}
{532}{}{and have crippled limbs.}
{533}{}{but have crippled limbs.}
{535}{}{He has %d/%d hit points}
{536}{}{She has %d/%d hit points}
{537}{}{It has %d/%d hit points}
{540}{}{It weighs %d pounds.}
{541}{}{It weighs %d pound.}
{544}{}{, }
{545}{}{.}
{546}{}{ and is wielding a %s.}
{547}{}{ and is wielding a %s with %d/%d shots of %s.}
{550}{}{\nError: lookup_val out of range!}
{551}{}{\nError: obj_examine: proto_ptr failed!}
{580}{}{You use the %s.}
{581}{}{You use the %s on %s.}
{582}{}{That does nothing of interest.}
{583}{}{To your dismay, you realize that it is already dead.}
{584}{}{As you reach down, you realize that it is already dead.}
{585}{}{Alas, you are too late.}
{586}{}{That won't work on the dead.}
{587}{}{You light the flare.}
{588}{}{The flare is already lit.}
{589}{}{You set the timer.}
{590}{}{The timer is already ticking!}
{620}{}{You earn %d experience for killing: %s.}
{621}{}{%s you earn %d experience.}
{622}{}{Für den Sieg über deine Feinde}
{623}{}{Für das Erledigen deiner Gegner}
{624}{}{You are victorious in combat;}
{625}{}{Für die Vernichtung deiner Gegner}
{626}{}{Für die Vernichtung deiner Gegner, ohne einen Kratzer abzubekommen,}
{650}{}{[Done]}
{651}{}{[More]}
{652}{}{[More]}
{653}{}{[Back]}
{654}{}{[Back]}
{655}{}{[Continue]}
{656}{}{Err...}
{660}{}{You can't see there.}
{661}{}{Too far away.}
{670}{}{Okay.}
{671}{}{Sure.}
{672}{}{As you wish.}
{673}{}{Whatever you say.}
{674}{}{I'll try.}
{675}{}{I can't do that.}
{676}{}{I don't think I can do that.}
{677}{}{Arf!}
{678}{}{Woof!}
{700}{}{You do not have enough Action Points to do that.}
{800}{}{You read the book.}
{801}{}{You learn nothing new.}
{802}{}{You learn about the practical application of science and technology.}
{803}{}{You learn about mechanical and electronic repair procedures.}
{804}{}{You learn better ways to heal injuries in the field.}
{805}{}{You learn how to handle and maintain your guns better.}
{806}{}{You learn a lot about wilderness survival techniques.}
{900}{}{The supplies in the Doctor's Bag run out.}
{901}{}{The supplies in the First Aid Kit run out.}
{902}{}{You cannot do that during combat.}
{903}{}{This person will not barter with you.}
{904}{}{This person has nothing to tell you about.}
{905}{}{You cannot pick that up. You are at your maximum weight capacity.}
{913}{}{This critter can't carry anything.}
