{100}{}{Voici Abel.}
{101}{}{Un imposant mutant.}
{102}{}{Tu n'as rien à faire ici.}
{103}{}{Grr.}
{104}{}{Bien sûr que non. Je viens ici pour te tuer !}
{105}{}{Pourquoi dis-tu ça ?}
{106}{}{Ah, ouais ? Cause toujours !}
{107}{}{Pik!}
{108}{}{J'vais t'donner une bonne raclée si tu continues !}
{109}{}{Pik ! Pik !}
{110}{}{Oh, cette fois, tu l'auras pas volée !}
{111}{}{Toi humain. Moi mutant. Mutant tuer humain.}
{112}{}{Mais comment ? Qu'est-ce que tu fais du champ de force ?}
{113}{}{Abel s'en occupe. Après, Abel donner bonne raclée !}
{114}{}{Les Enfants ne sont pas admis ici. Ici endroit pour mutants. Va donc.}
{115}{}{Grr !}
{116}{}{Il faut que je traverse le champ de force. S'il te plaît, laisse-moi passer.}
{117}{}{Non.}
{118}{}{Toi encore ! Abel donner bonne raclée !}
{970}{}{Me Abel.}
{971}{}{Me Abel.}
{972}{}{Me Abel.}
{973}{}{Me Abel.}
{974}{}{Me Abel.}
{975}{}{Me Abel.}
{976}{}{Me Abel.}
{977}{}{Me Abel.}
{978}{}{Me Abel.}
{979}{}{Me Abel.}
{980}{}{Grr.}
{981}{}{Pourquoi dis-tu cela ?}
{982}{}{Pik!}
{983}{}{Ung... wuh?}
{984}{}{Hmm?}
{985}{}{Que dis-tu ?}
{986}{}{What, hmm?}
{987}{}{Uh... me not know.}
{988}{}{Me not know.}
{989}{}{What that?}
{990}{}{}
{991}{}{}
{992}{}{}
{993}{}{}
{994}{}{}
{995}{}{}
{996}{}{}
{997}{}{}
{998}{}{}
{999}{}{}
