{100}{}{Tu vois un genre de disque étrange.}
{101}{}{Message du Pip-Boy : fichier déjà présent sur le système. Abandon du chargement.}
{102}{}{Message du Pip-Boy : chargement des données sur le disque. Terminé.}
{103}{}{Ce disque porte un signe étrange dessus. Tu penses que cela pourrait bien être ce que la Confrérie de l'Acier t'a demandé de récupérer.}
{104}{}{Tu vois : Disque Antique de la Confrérie.}
{125}{}{Tu vois un étrange disque provenant de la Base Militaire.}
{126}{}{You see: Vault Locations Holodisk.}
{127}{}{Cet holodisque est en parfait état. Une étiquette brillante indique: "Emplacement des Abris v34.129".}
