{100}{}{Tu as mis Barry en colère !}
{101}{}{Voici Barry.}
{102}{}{Eh ! Y'a que les Goules qu'ont droit à une ration d'eau.}
{103}{}{T'aurais pas dû me réveiller. Tu vas passer un sale quart d'heure !}
{104}{}{Le mutant t'ignore.}
{1000}{}{Puce d'eau|Puce eau|Puce|Eau|Controleur}
{1001}{}{Nécropolis}
{1002}{}{Set}
{1003}{}{Watershed}
{1004}{}{Hall}
{1005}{}{Lou}
{1006}{}{Goules}
{1007}{}{Normaux}
{1100}{}{Je ne sais pas.}
{1101}{}{Tu y es.}
{1102}{}{C'est qu'une tapette. Faut se débarrasser de lui et de ses Goules.}
{1103}{}{C'est ici.}
{1104}{}{Je ne sais pas.}
{1105}{}{Lui, le chef de Harry.}
{1106}{}{Des poules mouillées.}
{1107}{}{Encore plus poules mouillées que les Goules.}
