{100}{}{Tu vois Zack Barstow, un initié des Enfants de la cathédrale.}
{101}{}{Bienvenue chez les Enfants de la Cathédrale. Comment puis-je faire pour t'aider ?}
{102}{}{Urrrooo ?}
{103}{}{Quel est le sens de l'univers ?}
{104}{}{Je suis gravement blessé. Tu penses pouvoir m'aider ?}
{105}{}{Comment réparer une pompe à eau ?}
{106}{}{Peux-tu me dire quelque chose sur cet endroit ?}
{107}{}{Je ne suis pas fait pour ça. Peut-être que si tu parles à Laura, elle sera prête à te donner les informations dont tu as besoin.}
{108}{}{Oh, réparer des pompes à eau, c'est facile. C'est une formalité.}
{109}{}{Je n'ai pas les outils pour t'aider avec ce problème. Va t'adresser à l'un de mes supérieurs.}
{110}{}{Oh, ça. C'est une formalité.}
{111}{}{Va consulter Laura. Je t'ai dit tout ce que je savais.}
