{100}{}{Tu vois Jade.}
{101}{}{Tu vois Beca.}
{102}{}{}
{103}{}{}
{104}{}{Tu vois un membre des Ecorcheurs.}
{105}{}{Tu vois un membre des Ecorcheurs.}
{106}{}{Tu penses que c'est Books.}
{107}{}{Tu penses que c'est Scars.}
{108}{}{Tu penses que c'est Gunner.}
{109}{}{Tu penses que c'est Twitch.}
{110}{}{Tu penses que c'est Hammer.}
{111}{}{Tu penses que c'est Razor.}
{112}{}{Voici les dortoirs. Maintenant sors d'ici avant que je te botte le cul.}
{113}{}{Sois mon invité.}
{114}{}{Désolé pour ça. Salut.}
{115}{}{Je peux m'incruster ici ?}
{116}{}{Non. Ils sont pour les vrais membres des Ecorcheurs, pas pour de quelconques lavettes.}
{117}{}{Hé l'ami ! Comment ça va ? Installe-toi ici si tu as besoin d'un endroit sûr.}
{118}{}{Ainsi tu t'es porté volontaire pour nous aider. C'est mieux que rien, je l'admets. Merci. Je vais faire passer le mot.}
{119}{}{Ouais. Je vais y aller et voir ce que je peux faire.}
{120}{}{Hé te revoilà. J'ai entendu que tu nous avais vraiment aidé. Tu es plus que digne de notre respect en effet. Nous sommes libres maintenant. [Tu es dorénavant un membre du gang des Ecorcheurs.]}
{121}{}{Je ne peux pas t'aider. Va parler à Razor.}
