{100}{}{Tu vois : Bob.}
{101}{}{Je ne te laisserai pas me voler aveuglément !}
{102}{}{Hé, je ne veux pas d'ennuis !}
{103}{}{Donne-moi une brochette d'iguane.}
{104}{}{Peux tu me dire quelque chose à propos d'une puce d'eau ?}
{105}{}{Qu'est-ce que tu peux me dire sur Decker ?}
{106}{}{Je pense que nous devons parler de Doc Morbid et de certains de tes ingrédients secrets.}
{107}{}{Sais-tu quelque chose sur les caravanes disparues ?}
{108}{}{Quoi, j'ai des problèmes ? Qu'est-ce qui te donne cette impression ?}
{109}{}{Me hungry ! Grrrr !}
{110}{}{Bonjour. Bienvenue à l'Iguane Rôti, le restaurant familial. Puis-je prendre ta commande ?}
{111}{}{Donne-moi une brochette d'iguane.}
{112}{}{Peux tu me dire quelque chose à propos d'une puce d'eau ?}
{113}{}{Qu'est-ce que tu peux me dire sur Decker ?}
{114}{}{Je pense que nous devons parler de Doc Morbid et de certains de tes ingrédients secrets.}
{115}{}{Sais-tu quelque chose sur les caravanes disparues ?}
{116}{}{Il se passe des trucs intéressants au Centre ?}
{117}{}{Me hungry ! Grrrr !}
{118}{}{Désolé, on n'a plus d'iguane.}
{119}{}{Nous n'avons que des brochettes d'iguane. Vingt capsules chacune.}
{120}{}{Nous n'avons que de la viande de premier choix. Mais c'est très bon. Huit capsules chacun.}
{121}{}{Bien sûr. On a des brochettes d'iguane pour 20 capsules, et nos morceaux de choix pour 8 capsules.}
{122}{}{Je vais prendre un iguane.}
{123}{}{Je vais prendre ton morceau de choix.}
{124}{}{Tu sais, j'ai entendu dire que ton morceau de choix a le goût de poulet.}
{125}{}{Pas de portions de mauviettes ! Moi vouloir tous les iguanes ! Ugh !}
{126}{}{Hmm, ça sent bon ! La première coupe rend le ventre heureux !}
{127}{}{On ne sert pas ça ici. Autre chose ?}
{128}{}{Donne-moi une brochette d'iguane.}
{129}{}{Qu'est-ce que tu peux me dire sur Decker ?}
{130}{}{Je pense que nous devons parler de Doc Morbid et de certains de tes ingrédients secrets.}
{131}{}{Sais-tu quelque chose sur les caravanes disparues ?}
{132}{}{Il se passe des trucs intéressants au Centre ?}
{133}{}{Me hungry ! Grrrr !}
{134}{}{Mr. Decker is a distinguished businessman in a less than distinguished business. Anything else ?}
{135}{}{I want information on Doc Morbid.}
{136}{}{Donne-moi une brochette d'iguane.}
{137}{}{Rien.}
{138}{}{He was a mean son of a bitch and anyone who isn't glad he's dead is a damned liar. Can I take your order ?}
{139}{}{Donne-moi une brochette d'iguane.}
{140}{}{Tell me a little about the Water Merchants.}
{141}{}{Je pense que nous devons parler de Doc Morbid et de certains de tes ingrédients secrets.}
{142}{}{Sais-tu quelque chose sur les caravanes disparues ?}
{143}{}{Il se passe des trucs intéressants au Centre ?}
{144}{}{Me hungry ! Grrrr !}
{145}{}{I don't know what you're talking about. Ok. I'll pay you one hundred bucks if you keep your mouth shut. Take it and get out.}
{146}{}{I want two hundred.}
{147}{}{I'll take the hundred.}
{148}{}{I'm going to the police.}
{149}{}{Stop selling them. Now.}
{150}{}{Terrible business. Those poor people. Oh, those poor people. Losing their lives in such a ghastly way ! Is there anything else I can do for you ? Like feed you, perhaps ?}
{151}{}{Donne-moi une brochette d'iguane.}
{152}{}{Peux tu me dire quelque chose à propos d'une puce d'eau ?}
{153}{}{Qu'est-ce que tu peux me dire sur Decker ?}
{154}{}{Je pense que nous devons parler de Doc Morbid et de certains de tes ingrédients secrets.}
{155}{}{Il se passe des trucs intéressants au Centre ?}
{156}{}{Nothing. Sorry to bring it up. I just hear stories. Now is there anything else I can do for you ?}
{157}{}{Donne-moi une brochette d'iguane.}
{158}{}{Peux tu me dire quelque chose à propos d'une puce d'eau ?}
{159}{}{Qu'est-ce que tu peux me dire sur Decker ?}
{160}{}{Je pense que nous devons parler de Doc Morbid et de certains de tes ingrédients secrets.}
{161}{}{Sais-tu quelque chose sur les caravanes disparues ?}
{162}{}{Il se passe des trucs intéressants au Centre ?}
{163}{}{Someone killed Decker. We're in mourning, at least until the Hub runs out of booze.}
{164}{}{Someone shot Sheriff Greene. Don't know about the deputy though.}
{165}{}{Daren Hightower was murdered. And all that money couldn't save him. Ironic, ain't it ?}
{166}{}{Someone has really pissed off someone important, because I hear that there's a big hit out on some poor sod.}
{167}{}{Someone stole a necklace from the Hightowers. Man, did they ever make a big mistake. They're dead for sure.}
{168}{}{Someone killed Jain over at the Cathedral. I hear she was a real bitch !}
{169}{}{Well, the only new thing is that the Children of the Cathedral have taken over the hospital. It's pretty boring around here lately. Mind you, they're a strange crowd.}
{170}{}{Et avec ça ?}
{171}{}{Donne-moi une brochette d'iguane.}
{172}{}{Peux tu me dire quelque chose à propos d'une puce d'eau ?}
{173}{}{Qu'est-ce que tu peux me dire sur Decker ?}
{174}{}{Je pense que nous devons parler de Doc Morbid et de certains de tes ingrédients secrets.}
{175}{}{Sais-tu quelque chose sur les caravanes disparues ?}
{176}{}{Sorry, you can't afford one.}
{177}{}{One whole iguana, coming up ! Anything else ?}
{178}{}{Gimme another iguana on a stick.}
{179}{}{Peux tu me dire quelque chose à propos d'une puce d'eau ?}
{180}{}{Qu'est-ce que tu peux me dire sur Decker ?}
{181}{}{Sais-tu quelque chose sur les caravanes disparues ?}
{182}{}{Il se passe des trucs intéressants au Centre ?}
{183}{}{Me want another iguana !}
{184}{}{Me stuffed ! URRRP !}
{185}{}{Sorry, you can't afford one.}
{186}{}{One iguana prime cut select, coming up ! Anything else ?}
{187}{}{Gimme another iguana on a stick.}
{188}{}{Peux tu me dire quelque chose à propos d'une puce d'eau ?}
{189}{}{Qu'est-ce que tu peux me dire sur Decker ?}
{190}{}{Sais-tu quelque chose sur les caravanes disparues ?}
{191}{}{Il se passe des trucs intéressants au Centre ?}
{192}{}{Me want another iguana !}
{193}{}{Me stuffed ! URRRP !}
{194}{}{Thank you. Come again !}
{195}{}{You must be new in town if you're asking me about the Water Merchants. Water is life. And you don't get much more powerful than life and death.}
{196}{}{Donne-moi une brochette d'iguane.}
{197}{}{Je pense que nous devons parler de Doc Morbid et de certains de tes ingrédients secrets.}
{198}{}{Sais-tu quelque chose sur les caravanes disparues ?}
{199}{}{Il se passe des trucs intéressants au Centre ?}
{200}{}{Me hungry ! Grrrr !}
{201}{}{You greedy son of a bitch !}
{202}{}{You greedy whore !}
{203}{}{All right, you win. Here's your money. Take it and don't come back !}
{204}{}{I'd change your mind if I were you, friend. People have died for less in the Hub. Now get out and don't come back !}
{205}{}{Maybe I've been using some questionable portions, but it's not like I'm committing murder. Like Morbid's stuff is already dead, ain't it ?}
{206}{}{I'm sure it is, Bob. And I'm sure the police will agree.}
{207}{}{Cannibalism is a crime against humanity, Bob. I'm going to see that you pay for your it.}
{208}{}{Maybe it is. Maybe it isn't. I don't care. It's immoral. Stop it.}
{209}{}{No way ! I ain't letting you screw me ! Eat this !}
{210}{}{I ain't going broke because of your scruples, but you're gonna die from them ! Eat this !}
