{100}{}{Ils n'ont jamais ce que je veux.}
{101}{}{J'ai l'impression que le choix se restreint de plus en plus.}
{102}{}{Ces prix sont inabordables.}
{103}{}{Je ne trouve jamais ce que je veux.}
{104}{}{Je préfère le choix de la Caravane Ecarlate.}
{105}{}{Ils n'ont jamais ce que je veux.}
{106}{}{J'ai l'impression que le choix se restreint de plus en plus.}
{107}{}{Ces prix sont inabordables.}
{108}{}{Désolé, je ne suis pas censé parler aux étrangers.}
{109}{}{Tu devrais t'adresser à Cabbot ou Darrell si tu as des questions.}
{110}{}{J'dois y aller.}
{111}{}{J'te parlrai pas.}
{112}{}{Je n'aime pas les peaudouces.}
{113}{}{Arrrr !}
{114}{}{Grrrrr !}
{115}{}{Ils n'ont jamais ce que je veux.}
{116}{}{J'ai l'impression que le choix se restreint de plus en plus.}
{117}{}{Ces prix sont inabordables.}
{118}{}{Je ne trouve jamais ce que je veux.}
{119}{}{Je préfère le choix de la Caravane Ecarlate.}
{1100}{}{Tu vois un client de la caravane.}
{1103}{}{Désolé, je ne suis pas censé parler aux étrangers.}
{1105}{}{Si tu vois des Redaleks, fais-le moi savoir.}
{1107}{}{Heureusement que ces Marchands d'Eau ne viennent plus par ici.}
{1109}{}{Cabbot est chargé de l'accueil. Tu devrais aller lui parler ou à Darrell.}
{1110}{}{Je préfère le choix de la Caravane Ecarlate.}
{1111}{}{Les Marchands du Lointain sont des gens agréables, n'est-ce pas ?}
{1112}{}{La Caravane Ecarlate est trop banal pour moi.}
