{100}{}{Drôle de machine à sous. Il faut 10 caps pour y jouer.}
{101}{}{Tu mets 10 caps dans la machine à sous et tu tires sur la poignée.}
{102}{}{DING ! DING ! DING !}
{103}{}{Tu as trois grenades. Excellent ! Les }
{104}{}{ caps tombent dans le plateau et tu les prends.}
{105}{}{Ding ! Ding ! Ding !}
{106}{}{Tu as trois balles. Bravo ! 15 caps tombent dans le plateau et sont à toi.}
{107}{}{Ahh des cosses ! Tu as perdu.}
{108}{}{Tu n'as pas assez d'argent pour jouer.}
