{100}{}{Tu vois un enfant, il est plutôt petit.}
{101}{}{Salut !}
{102}{}{Bonjour.}
{103}{}{Où sont tes parents ?}
{104}{}{Erf.}
{105}{}{Ché pas. Quelque part par là.}
{106}{}{Tu es drôle !}
{107}{}{Hé, tu vas tuer quelqu'un ?}
{108}{}{Oui.}
{109}{}{Non !}
{110}{}{Erf.}
{111}{}{J'vais l'dire à ma maman !}
{112}{}{Alors tu devrais pas porter ton arme comme ça}
{200}{}{Sorry, mister.}
{201}{}{Sorry, ma'am.}
{300}{}{Papa est juste là ! Tu le vois pas ?}
{301}{}{Maman est juste là ! Tu la vois pas ?}
{980}{}{Hein ?}
{981}{}{Ché pas. Demande à ma maman.}
{982}{}{Demande à mon papa.}
{1000}{}{Deathclaw}
{1001}{}{Pillards|Pillards|Khans|Khan}
{1002}{}{Dépôtville}
{1003}{}{Brahmine}
{1004}{}{Puce d'eau|Puce eau|Puce|Eau|Controleur}
{1005}{}{Marchands|Marchand}
{1006}{}{Khans}
{1007}{}{Garl}
{1008}{}{Sables Ombragés}
{1009}{}{Centre}
{1010}{}{Tandi}
{1011}{}{Aradesh}
{1012}{}{Seth}
{1013}{}{Razlo}
{1014}{}{Police}
{1015}{}{Caravanes}
{1016}{}{Marchands}
{1017}{}{Enfants}
{1018}{}{Nécropolis}
{1019}{}{Rouge}
{1020}{}{Confrérie de l'Acier|Confrérie|Confrerie|Acier}
{1021}{}{Cimetière de L.A.}
{1022}{}{Towers}
{1023}{}{Ville}
{1024}{}{Downtown}
{1025}{}{Hauteurs}
{1026}{}{Cimetière|Le Cimetière|Cimetière de L.A.|Los Angeles}
{1027}{}{L.A. Boneyard}
{1100}{}{Ouah ! Un monstre cauchemardesque !}
{1101}{}{Méchants !}
{1102}{}{Je ne sais pas.}
{1103}{}{Des gros trucs qui puent.}
{1104}{}{Demande à ma maman.}
{1105}{}{Drôles de chants de marins.}
{1106}{}{Méchants !}
{1107}{}{Sale type.}
{1108}{}{J'te l'dirai pas.}
{1109}{}{Grande ville.}
{1110}{}{J'te l'dirai pas.}
{1111}{}{Non, j' te dirai rien.}
{1112}{}{Ma maman veut pas que je parle de lui.}
{1113}{}{Mon papa trouve qu'il est bizarre.}
{1114}{}{Big peoples.}
{1115}{}{They have those stinkies that pull them.}
{1116}{}{Nice people. They give me candy.}
{1117}{}{They don't like to play hide and seek.}
{1118}{}{Scary place.}
{1119}{}{Yucky place.}
{1120}{}{Scary place.}
{1121}{}{Scary place.}
{1122}{}{Mommy won't let us play there.}
{1123}{}{Daddy keeps telling us to play there.}
{1124}{}{Big people area.}
{1125}{}{Big people area.}
{1126}{}{Scary place.}
{1127}{}{Scary place.}
