{100}{}{On retourne au Centre.}
{101}{}{Vas-tu repartir avec nous ?}
{102}{}{Je suis prêt à partir.}
{103}{}{J'espère avoir assez de cartouches...}
{104}{}{J'adore ce boulot !}
{105}{}{Let's go!}
{106}{}{En route !}
{107}{}{Nous les avons tous tué !}
{108}{}{C'était facile !}
{109}{}{On ne parle plus et on bouge son cul !}
{110}{}{Prêt à partir ?}
{111}{}{Je suis pas payé pour parler.}
{112}{}{Foutu endroit de merde !}
{113}{}{Je suis pas payé pour parler.}
{114}{}{Occupe toi de ton cul !}
{115}{}{Occupe toi de ton cul !}
{200}{}{Let's do this!}
{201}{}{Hope I have enough bullets...}
{202}{}{Aim for the eyes!}
{203}{}{Protège la caravane !}
{204}{}{Stay sharp, everyone.}
