{100}{}{C'est une sorte de disquette bizarre. Peut-être qu'il peut être lu dans ton Pip-Boy 2000.}
{101}{}{Message du Pip-Boy : fichier déjà présent sur le système. Abandon du chargement.}
{102}{}{Message du Pip-Boy : chargement des données sur le disque. Terminé.}
{103}{}{Tu remarques une étiquette fanée par le temps sur le disque. Il y est écrit: "Notes sur les expériences Delta".}
{104}{}{Tu vois: Disque sur les expériences Delta.}
{105}{}{L'armée a jugé nécessaire que nous approfondissions nos recherches sur l'effet de la technologie des ondes sur les organismes vivants. La lumière et le son sont les bases de nos études. En manipulant les longueurs d'ondes et en amplifiant les fréquences, nous avons été capable de créer des rayons lasers capables de pénétrer dans plusieurs mètres d'acier. Malheureusement, les capacités d'un tel engin n'ont pas été complètement développées. Nous avons actuellement d'autres scientifiques qui se penchent sur le sujet.}
{106}{}{**BEGIN-DISK**}
{107}{}{**END-DISK**}
{108}{}{[Continue]}
