{100}{}{Voici un marchand ambulant d'origine asiatique.}
{101}{}{Voici Duc, le marchand ambulant.}
{102}{}{Salut, nomade. Je m'appelle Duc, je m'en vais faire du commerce aux Sables Ombragés. J'ai peut-être des marchandises qui t'intéressent ?}
{103}{}{Qu'est-ce que t'as à vendre ?}
{104}{}{Tu vas souvent aux Sables Ombragés ?}
{105}{}{Arf !}
{106}{}{Je vais te montrer.}
{107}{}{Oui, les Sables Ombragés font partie de ma tournée. Tu seras en sécurité si tu voyages avec nous.}
{108}{}{Ouais, ça m'a l'air intéressant.}
{109}{}{Non, merci.}
{110}{}{Hmm, encore un crétin. Va voir ailleurs si j'y suis ok ?}
{111}{}{Ca devrait prendre qu'un jour ou deux. Allons-y !}
{112}{}{SHADYW.MAP}
{113}{}{Y'a pas grand monde qui s'aventure seul dans le désert. Qui es-tu ?}
{114}{}{None of your business.}
{115}{}{Je m'appelle }
{116}{}{.}
{117}{}{Moi }
{118}{}{Rebonjour ! Que puis-je pour toi ?}
{119}{}{Je peux vous accompagner jusqu'aux Sables Ombragés ?}
{120}{}{Qu'est-ce que t'as à vendre ?}
{121}{}{Rien, merci.}
{122}{}{Qu'est-ce que tu veux ?}
{123}{}{Rien, excuse-moi.}
{124}{}{Qu'est-ce que t'as à vendre ?}
{125}{}{Ah ?}
{126}{}{Méfie-toi si tu voyages en solitaire. Récemment, y'a eu des disparitions aux Sables Ombragés.}
{127}{}{Hé, j'ai entendu dire comment t'avais sauvé cette femme des Sables Ombragés. Du beau boulot !}
{128}{}{Oh, pardon. Je savais pas que t'étais aussi stupide.}
{129}{}{Merci, à la prochaine !}
{130}{}{Rumph !}
{131}{}{Arf !}
{132}{}{!}
