{100}{}{Tu vois un policier du Centre.}
{101}{}{Si seulement mon poste était plus près de chez moi.}
{102}{}{Je me demande ce qui est arrivé à ces caravanes.}
{103}{}{Avance.}
{104}{}{Je te conseille de pas sortir tes armes, étranger.}
{105}{}{Pas de conneries, hein ?}
{106}{}{Des marchandises à déclarer ?}
{107}{}{Me balance pas ton arme sous le nez.}
{108}{}{Range ça si tu veux pas faire un tour en taule.}
{109}{}{C'est moi que tu vises ?}
{110}{}{J'ai entendu parler de toi. Fais gaffe.}
{111}{}{On t'aura à l'oeil.}
{112}{}{Pas de castagne dans notre ville, gros dur !}
{113}{}{On n'aime pas les tueurs d'enfants !}
{114}{}{Si tu poses la main sur un enfant, je te descends.}
{115}{}{J'ai horreur des gens de ton espèce.}
{116}{}{Appelle pas à l'aide si t'es dans le pétrin.}
{117}{}{Eh, merci de faire le boulot à notre place.}
{118}{}{Pas de meurtre ici, même s'il est justifié !}
{119}{}{Si c'est toi qu'as tué le Griffemort... merci.}
{120}{}{Tiens-toi à carreau dans notre ville.}
{121}{}{J'éviterais Decker si j'étais toi.}
{122}{}{Bon séjour !}
{123}{}{Bienvenue au Centre !}
{124}{}{Bonjour.}
{125}{}{Si tu veux te rafraîchir, va au Faucon Maltais.}
{126}{}{Si tu cherches le marché, suis la grand-route.}
{127}{}{Avance.}
{128}{}{Avance. Avance.}
{129}{}{On est là pour faire régner l'ordre.}
{130}{}{Joue pas avec ton arme dans notre ville.}
{131}{}{Qu'on te prenne pas dans une bagarre avec ça.}
{132}{}{Je te conseille de ranger ton arme.}
{133}{}{Range ça... ton arme, je veux dire.}
{134}{}{Bienvenue Paladin. Ca faisait longtemps !}
{135}{}{Alors, c'est toi qui joues les gros bras ! Finit la bagarre, compris ?}
{136}{}{Je te conseille de plus chercher la bagarre !}
{137}{}{C'est toi... je te conseille de maîtriser tes nerfs.}
{138}{}{Les Marchands du Lointain ont été anéantis. Je peux pas y croire.}
{139}{}{Les Marchands d'Eau sont partis. Quel soulagement.}
{140}{}{La Caravane Ecarlate a été détruite.}
{141}{}{T'as entendu ? L'Underground a enfin été anéanti !}
{142}{}{Decker est Mort !}
{143}{}{Le problème Decker est enfin résolu.}
{144}{}{Fais attention... L'endroit n'est pas sûr.}
{145}{}{Surveille tes caps, mon gars.}
{146}{}{Surveille tes caps, ma fille.}
{147}{}{Harold l'Ancien adore raconter des histoires.}
{148}{}{Traîne pas par ici, c'est pas sûr.}
{149}{}{La Vieille Ville n'est vraiment plus qu'un tas de ruines.}
{150}{}{Ca pue ici.}
{151}{}{On devrait tout raser.}
{152}{}{Je sais que ce maudit Cercle des Voleurs rôde dans le coin.}
{153}{}{Pauvre Harold... Il a pas eu la vie facile.}
{154}{}{Pas de conneries, hein ?}
{155}{}{Eh. J'te connais. Finit la castagne, compris ?}
{156}{}{A ta place, je songerais à ne plus chercher la bagarre !}
{157}{}{La prochaine fois qu'on te surprend en train de te bagarrer ce sera la taule !}
{158}{}{T'as entendu ? Les Marchands du Lointain ont été anéantis.}
{159}{}{Les Marchants d'Eau, c'est plus que de l'histoire ancienne. Quelle chance !}
{160}{}{Quelqu'un a décimé la Caravane Ecarlate.}
{161}{}{T'as entendu ? L'Underground a enfin été anéanti !}
{162}{}{Decker est Mort !}
{163}{}{Cette ville serait sans doute plus sûre sans Decker.}
