{100}{}{Qu'est-ce que tu veux ?}
{101}{}{Laisse-moi tranquille !}
{102}{}{Quoi ?}
{103}{}{Ne fous pas le bordel dans mes affaires.}
{104}{}{Salut.}
{105}{}{Arrrr !}
{106}{}{Grrrrr !}
{107}{}{Uungh.}
{108}{}{Euh.}
{109}{}{Hé, as-tu entendu que Set est mort ?}
{110}{}{Set est mort. Set est mort. Set est mort...}
{111}{}{Il y a assez d'eau pour tout le monde. Set s'en assure.}
{112}{}{J'ai entendu dire que les mutants ont fuis la ville.}
{113}{}{Depuis que les mutants sont partis, tout s'arrange.}
{114}{}{Bonjour.}
{200}{}{Vous examinez la chose pitoyable, mais ne comprenez pas ce qui pourrait l'avoir rendu comme ça.}
{201}{}{Il semble avoir été autrefois humain, ou avoir des origines humaines. Vous supposez que la détérioration de l'organisme est probablement dûe à de l'acide ou aux radiations.}
{202}{}{L'organisme de l'humanoïde paraît fortement irradié, mais toujours en fonctionnement. Jadis il était un homme, il semble avoir maintenant trouvé un style de vie plus animal.}
{203}{}{L'organisme de l'humanoïde paraît fortement irradié, et une grande partie des muscles et de la matière cérébrale semblent s'être détériorés. Cependant, des indicateurs génétiques vous poussent à croire qu'il est descendant, comme vous, de ceux qui sont entrés dans les Abris.}
{204}{}{Non je te remercie.}
{205}{}{Non, merci.}
{206}{}{Bien sûr.}
{207}{}{Oui.}
{208}{}{Non.}
{209}{}{D'accord.}
{300}{}{Euh...}
{301}{}{Warf.}
{302}{}{Ouga.}
{303}{}{Argh.}
{350}{}{[FIN]}
{351}{}{[Salut]}
{352}{}{[MORE]}
{353}{}{[Continuer]}
{354}{}{[Combattre]}
{355}{}{[Donner l'argent]}
{375}{}{Salut.}
{376}{}{Au revoir.}
{450}{}{L'horizon est dégagé, on bouge !}
{900}{}{La vieille porte usée devrait facilement être détruite avec un explosif.}
{905}{}{Wouaf ! Wouaf !}
{910}{}{Tu reçois une décharge du sol électrifié.}
{911}{}{ est électrocuté par le sol électrifié.}
{912}{}{Le niveau de puissance tombe à zéro, puis remonte à 50% lorsque les générateurs de secours se mettent en marche.}
{913}{}{Un léger bourdonnement se fait entendre alors que le flux d'électricité passe de nouveau dans la base.}
{930}{}{Hooooowl !}
{950}{}{Tu prends du temps pour t'entraîner. Ta compétence Corps-à-corps augmente de 5%.}
{951}{}{Le rataupe combattant succombe à un coup fatal.}
{952}{}{Le match est terminé.}
{953}{}{Tu prends du temps pour t'entraîner.}
{954}{}{Tu mets tes lunettes à vision nocturne.}
{955}{}{Tu enlèves tes lunettes à vision nocturne.}
{956}{}{You learn nothing new.}
{957}{}{Tu apprends beaucoup sur le maniement des armes lourdes.}
{958}{}{Tu apprends beaucoup sur le maniement des armes à énergie.}
{959}{}{Tu apprends beaucoup sur les techniques médicales.}
{960}{}{Tu apprends beaucoup sur le crochetage.}
{961}{}{Tu apprends beaucoup sur les sciences et la technologie.}
{962}{}{Tu apprends beaucoup sur les pièges et les explosifs.}
{963}{}{Tu augmentes tes compétences relationnelles.}
{964}{}{Tu apprends beaucoup sur le troc.}
{965}{}{Tu n'as pas l'intelligence nécessaire pour comprendre cet ouvrage.}
{966}{}{Cet ouvrage est trop avancé pour tes connaissances sur le sujet.}
{967}{}{Tu gagnes de nouveaux talents par l'apprentissage continu.}
{968}{}{Ton vocabulaire s'enrichit.}
{969}{}{Ton éloquence s'améliore.}
{970}{}{Tu apprends beaucoup sur les techniques de survie.}
{971}{}{Tu apprends beaucoup sur les technologies avancées.}
{1003}{}{Tu désactives le champ de force.}
{1004}{}{Tu pirates l'ordinateur.}
{1012}{}{ALERTE ! FUSION COMPLETE DU REACTEUR !}
{1013}{}{ALERTE ! Toxines rejetées dans les conduits d'aération !}
{1050}{}{Tu fabriques un antidote à partir de la toxine prélevée sur le radscorpion.}
{2000}{}{zéro}
{2001}{}{un}
{2002}{}{deux}
{2003}{}{trois}
{2004}{}{quatre}
{2005}{}{cinq}
{2006}{}{six}
{2007}{}{sept}
{2008}{}{huit}
{2009}{}{neuf}
{2010}{}{dix}
{2011}{}{onze}
{2012}{}{douze}
{2013}{}{treize}
{2014}{}{quatorze}
{2015}{}{quinze}
{2016}{}{seize}
{2017}{}{dix-sept}
{2018}{}{dix-huit}
{2019}{}{dix-neuf}
{2021}{}{vingt-et-un}
{2022}{}{vingt-deux}
{2023}{}{vingt-trois}
{2024}{}{vingt-quatre}
{2025}{}{vingt-cinq}
{2026}{}{vingt-six}
{2027}{}{vingt-sept}
{2028}{}{vingt-huit}
{2029}{}{vingt-neuf}
{2030}{}{trente}
{2031}{}{trente-et-un}
{2032}{}{trente-deux}
{2033}{}{trente-trois}
{2034}{}{trente-quatre}
{2035}{}{trente-cinq}
{2036}{}{trente-six}
{2037}{}{trente-sept}
{2038}{}{trente-huit}
{2039}{}{trente-neuf}
{2040}{}{quarante}
{2041}{}{quarante-et-un}
{2042}{}{quarante-deux}
{2043}{}{quarante-trois}
{2044}{}{quarante-quatre}
{2045}{}{quarante-cinq}
{2046}{}{quarante-six}
{2047}{}{quarante-sept}
{2048}{}{quarante-huit}
{2049}{}{quarante-neuf}
{2050}{}{cinquante}
{2051}{}{cinquante-et-un}
{2052}{}{cinquante-deux}
{2053}{}{cinquante-trois}
{2054}{}{cinquante-quatre}
{2055}{}{cinquante-cinq}
{2056}{}{cinquante-six}
{2057}{}{cinquante-sept}
{2058}{}{cinquante-huit}
{2059}{}{cinquante-neuf}
{2060}{}{soixante}
{2061}{}{soixante-et-un}
{2062}{}{soixante-deux}
{2063}{}{soixante-trois}
{2064}{}{soixante-quatre}
{2065}{}{soixante-cinq}
{2066}{}{soixante-six}
{2067}{}{soixante-sept}
{2068}{}{soixante-huit}
{2069}{}{soixante-neuf}
{2070}{}{soixante-dix}
{2071}{}{soixante-et-onze}
{2072}{}{soixante-douze}
{2073}{}{soixante-treize}
{2074}{}{soixante-quatorze}
{2075}{}{soixante-quinze}
{2076}{}{soixante-seize}
{2077}{}{soixante-dix-sept}
{2078}{}{soixante-dix-huit}
{2079}{}{soixante-dix-neuf}
{2080}{}{quatre-vingt}
{2081}{}{quatre-vingt-un}
{2082}{}{quatre-vingt-deux}
{2083}{}{quatre-vingt-trois}
{2084}{}{quatre-vingt-quatre}
{2085}{}{quatre-vingt-cinq}
{2086}{}{quatre-vingt-six}
{2087}{}{quatre-vingt-sept}
{2088}{}{quatre-vingt-huit}
{2089}{}{quatre-vingt-neuf}
{2090}{}{quatre-vingt-dix}
{2091}{}{quatre-vingt-onze}
{2092}{}{quatre-vingt-douze}
{2093}{}{quatre-vingt-treize}
{2094}{}{quatre-vingt-quatorze}
{2095}{}{quatre-vingt-quinze}
{2096}{}{quatre-vingt-seize}
{2097}{}{quatre-vingt-dix-sept}
{2098}{}{quatre-vingt-dix-huit}
{2099}{}{quatre-vingt-dix-neuf}
{2100}{}{cent}
{3000}{}{}
{3025}{}{}
{3050}{}{Si tu recommences ça, je te tue.}
{3051}{}{Y'a rien à voler, abruti.}
{3052}{}{Je crois pas qu'on se connaisse "suffisament" bien.}
{3053}{}{Touche ça encore une fois et tu vas le payer.}
{3054}{}{Me touche pas !}
{3055}{}{Fais encore ça et je te coupe la tête.}
{3056}{}{Bas les pattes !}
{3057}{}{Tu cherches les ennuis ?}
{3058}{}{Touche moi encore et t'es mort.}
{3059}{}{Seuls les ennuis sont gratuits.}
{3060}{}{Dégage !}
{3061}{}{Attention !}
{3062}{}{Tu cherches à mourir ?}
{3063}{}{T'essaie encore ça et je t'éclate la tête !}
{3064}{}{C'est à moi : bas les pattes !}
{3075}{}{}
{3100}{}{ a rejoins le groupe }
{3101}{}{ a quitté le groupe }
{3300}{}{}
{3325}{}{Pourquoi tu remettrais pas tout ça où tu l'as pris ?}
{3326}{}{C'est pas bien de prendre ce qui t'appartiens pas !}
{3327}{}{Tire-toi de là, minable !}
{3328}{}{Et viens pas me dire que "tu cherches tes clés". Barre-toi !}
{3329}{}{Quoique tu cherches, c'est pas ici. Compris ?}
{3350}{}{}
{3375}{}{}
{3400}{}{Cpt. Corpse's Cheating Tool.}
{3401}{}{Add to party: Adds target object to your party.  Valid targets: critters and items. (don't use on player)}
{3402}{}{Remove from party: Removes target object from party. (don't use on player)}
{3403}{}{Give armor and wield: Create a suit of Adv Power Armor MkII on target and wear. (Player and NPCs only)}
{3404}{}{Remove armor: Removes targets armor from armor slot}
{3405}{}{Set Max HP to 250 (does not work)}
{3406}{}{Create Resistance Booster Drugs (Needs Add-On Patch to work)}
{3407}{}{ to wield this item?}
{3408}{}{Remove Weapon: Causes an NPC to put away his/her weapon}
{3409}{}{Change NPCs appearance}
{3410}{}{Destroy Scenery or Wall: Good for clearing paths}
{3411}{}{Give Experience}
{3412}{}{Push target NPC}
{3413}{}{Give Money}
{3414}{}{Create Item: Creates an specific item on target}
{3415}{}{Heal Player or NPC: Also heals crippled limbs}
{3416}{}{Change NPC Stats}
{3417}{}{Select Category}
{3418}{}{Basic Stats}
{3419}{}{Strength}
{3420}{}{Perception}
{3421}{}{Endurance}
{3422}{}{Charisma}
{3423}{}{Intelligence}
{3424}{}{Agility}
{3425}{}{Luck}
{3426}{}{Hit Points}
{3427}{}{Action Points}
{3428}{}{Melee Damage}
{3429}{}{Carry Amount}
{3430}{}{Sequence}
{3431}{}{Healing Rate}
{3432}{}{Critical Chance}
{3433}{}{Better Criticals}
{3434}{}{Age}
{3435}{}{Gender}
{3436}{}{PC Stats}
{3437}{}{Skill Points}
{3438}{}{Reputation}
{3439}{}{Karma}
{3499}{}{Team Number Set}
{3500}{}{Team Number: }
{3501}{}{Quantity}
{3502}{}{+1}
{3503}{}{+10}
{3504}{}{+100}
{3505}{}{-1}
{3506}{}{-10}
{3507}{}{-100}
{3508}{}{+1000}
{3509}{}{+10000}
{3510}{}{+100000}
{3511}{}{Boxes (2)}
{3512}{}{Boxes (1)}
{3513}{}{Fridge}
{3514}{}{Ice Chest}
{3515}{}{Ammo Crate (Big)}
{3516}{}{Order }
{3517}{}{Wagon(Red)}
{3518}{}{Wagon(White)}
{3519}{}{Floor Safe}
{3520}{}{Chest}
{3521}{}{Give Item}
{3600}{}{}
{3625}{}{Hé, toi ! Qu'est-ce que tu farfouilles comme ça ?}
{3626}{}{Si t'as pas une clé dans ta main, tu ferais mieux de partir d'ici.}
{3627}{}{C'est pas fermé par hasard, minable !}
{3628}{}{Referme ça avant de t'attirer des problèmes !}
{3650}{}{}
{3675}{}{}
{3700}{}{Changer le FRM de la cible}
{3701}{}{Power Armor}
{3702}{}{Robes violettes}
{3703}{}{Armure de combat [F]}
{3704}{}{Tenue de l'Abri 13 [F]}
{3705}{}{Armure en cuir [F]}
{3706}{}{Mad Max [F]}
{3707}{}{Armure de métal [F]}
{3708}{}{Tenue de l'Abri 13 [MB]}
{3709}{}{Armure de métal [MB]}
{3710}{}{Armure de combat [M]}
{3711}{}{Tenue de l'Abri 13 [M]}
{3712}{}{Armure en cuir [M]}
{3713}{}{Mad Max [M]}
{3714}{}{Armure de métal [M]}
{3715}{}{Brahmine}
{3716}{}{Dog}
{3717}{}{M. Handy}
{3718}{}{Lt Lou}
{3719}{}{Rataupe}
{3720}{}{Cuir noir [SM]}
{3721}{}{Mutant vert}
{3722}{}{Radscorpion géant}
{3723}{}{Floater}
{3724}{}{Rat}
{3725}{}{Centaure}
{3726}{}{Robe bleue}
{3727}{}{Enfant}
{3728}{}{Goule vert}
{3729}{}{Glowing One}
{3730}{}{SuperArmure [sans casque]}
{3731}{}{Moine}
{3732}{}{Blonde}
{3733}{}{Punk}
{3734}{}{Armure de métal [F pantalons jaunes]}
{3735}{}{Tandi}
{3736}{}{Salope}
{3737}{}{Tenue de l'Abri 13 [F cheveux rouge]}
{3738}{}{Paysan noir [T-shirt rouge]}
{3739}{}{Paysan [T-shirt jaune]}
{3740}{}{Paysan chauve [T-shirt vert]}
{3741}{}{Nain aux cheveux rouge}
{3742}{}{Loser}
{3743}{}{Armure de cuir [M chauve]}
{3744}{}{Veste en cuir [voyou aux cheveux long]}
{3745}{}{Paysan [casquette bleue]}
{3746}{}{Griffemort adulte}
{3747}{}{Mantis}
{3748}{}{Robobrain}
{3749}{}{Floating Eye}
{3750}{}{Pig Rat}
{3751}{}{Robes marrons}
{3752}{}{Docteur chauve}
{3753}{}{Egg}
{3754}{}{Petit radscorpion}
{3755}{}{Jeune Griffemort}
{3761}{}{Sentry Robot}
{3764}{}{Citoyen homme}
{3769}{}{Citoyen femme}
{3774}{}{Goule neutre}
{3778}{}{Combinaison de l'Abri [F noire]}
{3779}{}{Robes noires}
{3782}{}{Policier}
{3784}{}{Technician}
{3798}{}{[FIN]}
{3799}{}{}
{3800}{}{[BACK]}
{3801}{}{[MENU PRINCIPAL]}
{3802}{}{[EXIT]}
{3803}{}{Entrer le PID de l'objet [format : 0000] }
{3804}{}{Premier nombre [1000]}
{3805}{}{Deuxième nombre [100]}
{3806}{}{Troisième nombre [10] }
{3807}{}{Quatrième nombre [1] }
{3808}{}{PID: }
{3809}{}{Nom de l'objet : }
{3810}{}{Objet invalide}
{3900}{}{}
{3925}{}{Hé toi ! Que fais tu là ?}
{3926}{}{T'es pas censé être ici !}
{3927}{}{Si tu penses pouvoir venir vers moi comme ça, tu te trompes !}
{3928}{}{Tu ferais mieux de pas être en train de faire ce que je crois que tu fais, étranger.}
{3929}{}{Et tu pensais que je te remarquerais pas ? Fous le camp !}
{3950}{}{}
{3975}{}{}
{4000}{}{Vérifier les seuils et résistances aux dégâts.}
{4001}{}{%}
{4002}{}{ a été soigné.}
{4003}{}{La jambe gauche estropiée a été soigné.}
{4004}{}{La jambe droite estropiée a été soigné.}
{4005}{}{Le bras gauche estropié a été soigné.}
{4006}{}{Le bras droit estropié a été soigné.}
{4007}{}{L’œil mutilé a été soigné}
{4008}{}{ n'est pas blessé.}
{4010}{}{SEUILS ET RESISTANCES}
{4011}{}{/}
{4012}{}{--}
{4100}{}{Normal : }
{4101}{}{Laser : }
{4102}{}{Feu : }
{4103}{}{Plasma : }
{4104}{}{Electricité : }
{4105}{}{EMP : }
{4106}{}{Explosion : }
{4107}{}{Radiation : }
{4108}{}{Poison : }
{4109}{}{ semble en bonne santé.}
{4200}{}{}
{4225}{}{}
{4250}{}{}
{4275}{}{}
{4300}{}{Oui, Maitre ?}
{4301}{}{}
{4500}{}{}
{4525}{}{}
{4550}{}{}
{4575}{}{}
{4600}{}{}
{4800}{}{}
{4825}{}{}
{4850}{}{}
{4875}{}{}
{4900}{}{}
{5100}{}{}
{5125}{}{}
{5150}{}{}
{5175}{}{}
{5201}{}{Do you wish to continue playing Fallout Fixt with this character?}
{5202}{}{No.  (END GAME: Play final movie sequence & credits, then exit to main menu.)}
{5203}{}{Yes.  (CONTINUE PLAYING: This dialog window will close and you'll stay on this map. Play continues normally.)}
{5400}{}{Reste loin de là.}
{9000}{}{Réparation terminée.}
{9001}{}{Réarmement terminé.}
{9002}{}{Réparation des dégâts en cours.}
{9003}{}{Aucun dégât détecté.}
{9004}{}{Fonction de réparation.}
{9005}{}{Entrer commande.}
{9006}{}{Surveille cet endroit.}
{9007}{}{Initialiser fonction de sentinelle.}
{9008}{}{Equiper armement.}
{9009}{}{Tu n'en a pas dans ton inventaire.}
{9010}{}{Fusil plasma.}
{9011}{}{Fusil laser.}
{9012}{}{Minigun.}
{9013}{}{Gatling laser}
{9014}{}{Armes.}
{9015}{}{Munition.}
{9016}{}{5 mm JHP}
{9017}{}{5mm AP}
{9018}{}{Cellule énergétique.}
{9019}{}{M. Handy est programmé au maniement des armes lourdes et à énergie.}
{10000}{}{Dis-moi quelque chose.}
{10001}{}{Tu devrais te soigner maintenant.}
{10002}{}{J'ai besoin que tu attendes jusqu'à mon retour.}
{10003}{}{Lâche ton arme.}
{10004}{}{Reste près de moi.}
{10005}{}{Ne pars pas trop loin de moi.}
{10006}{}{On devrait s'écarter un peu.}
{10007}{}{C'est tout pour l'instant.}
{10008}{}{Il faut modifier la distance entre nous.}
{10009}{}{Il faut que je te parle de ton équipement.}
{10010}{}{En fait, je pense que la distance est bonne.}
{10011}{}{J'ai rien besoin de savoir à propos de ton équipement.}
{10012}{}{Enlève l'armure que tu portes.}
{10013}{}{J'ai besoin de savoir quel type d'arme tu sais manier.}
{10100}{}{Allons-y.}
{21020}{}{vingt}
