{100}{}{Voici un garde Paladin.}
{101}{}{Désolé, j'peux pas discuter.}
{102}{}{Bonne journée.}
{103}{}{Tu savais qu'on peut survivre des semaines sans eau dans une SuperArmure ?}
{104}{}{T'as rien contre une bonne vieille bagarre ?}
{105}{}{J'aime vraiment les nouveaux fusils laser mais je préfère quand même les anciens pistolets laser.}
{106}{}{Les patrouilles de nuit sont très dangereuses. A ta place, je ne m'aventurerais pas trop loin la nuit.}
{107}{}{Attention, c'est un monde mortel là-bas.}
{108}{}{Je crois que mon armure a une tache !}
{109}{}{La Confrérie, c'est super. Je connais rien d'autre, mais ça peut pas être mieux.}
{110}{}{Salut, Initié.}
{111}{}{Si tu as besoin de quelque chose, adresse-toi à Vree.}
{112}{}{Vree est juste là-bas si tu veux parler à quelqu'un.}
{113}{}{Faut que je trouve du temps entre les patrouilles et l'entraînement pour étudier. Je commence un peu à me rouiller.}
{114}{}{Ton esprit et ton corps doivent toujours être au top, Initié.}
{115}{}{Etre Paladin, c'est pas simplement combattre, mon gars.}
{116}{}{Ma fille, être Paladin, c'est pas simplement combattre.}
