{100}{}{Voici un Scribe.}
{101}{}{Vree est mon idole.}
{102}{}{Vree est tellement mignonne.}
{103}{}{Sophia est très jolie.}
{104}{}{Derek est sympa.}
{105}{}{L'univers va-t-il continuer son expansion ou finalement se rétracter ?}
{106}{}{J'aime ces vieux livres et ces vieux magazines, mais ils sont si durs à trouver.}
{107}{}{La connaissance, c'est le pouvoir.}
{108}{}{La plume est plus puissante que l'épée.}
{109}{}{La technologie doit être préservée.}
{110}{}{La science est si amusante.}
{111}{}{J'ai déjà vu un vaisseau extraterrestre.}
{112}{}{Tu savais que le soleil est en fait une énorme réaction nucléaire ?}
{113}{}{Tu savais qu'un trou noir est en fait une ouverture vers un autre univers ?}
{114}{}{Sais-tu qu'un atome d'hydrogène est composé de 99,9843425% de vide ?}
{115}{}{Un jour, nous pourrons voyager dans le temps et peut-être empêcher le désastre qui a détruit notre monde par le passé.}
{116}{}{La recherche est une des mes activités préférées. J'ai l'impression de tenter de résoudre un mystère.}
{117}{}{Etre scribe, c'est ce qu'il y a de mieux. Tu étudies toutes les technologies anciennes et tu essaies d'en créer de nouvelles.}
{118}{}{On pourrait améliorer ces terminaux. Peut-être placer l'écran ici.}
{119}{}{Pardon, je suis en plein milieu d'une éventuelle découverte. Je ne peux pas te parler.}
{120}{}{Hé Initié. Tu pourrais devenir Scribe, si tu n'as pas encore fait ton choix.}
{121}{}{Nous, les Scribes, nous concevons du matériel, des armes et des fournitures. C'est passionnant.}
{122}{}{S'il te plaît, ne me dérange pas, j'essaie de terminer ma recherche.}
{123}{}{Voilà Vree ; elle est aussi Scribe.}
