{100}{}{Tu vois Heather, une éclaireuse des Disciples.}
{101}{}{Que fais-tu ici ?}
{102}{}{Ca !}
{103}{}{Allez salut.}
{104}{}{Oh, simple curiosité...}
{105}{}{Je suis là pour te tuer !}
{106}{}{Juste curieux de ce qui se passe dans les parages.}
{107}{}{Vraiment ? Et que pourrais-tu bien chercher ?}
{108}{}{Je pense que je l'ai déjà trouvée.}
{109}{}{Je recherche un espion.}
{110}{}{Rien du tout. Je me promène.}
{111}{}{Seulement des informations.}
{112}{}{Merci, mais j'ai déjà rendez-vous avec quelqu'un d'autre. Je crois qu'il est temps pour toi d'aller ailleurs.}
{113}{}{Oui, l'espion. J'ai entendu parler de cette peste inquiétante. Je souhaite vraiment qu'on l'attrape.}
{114}{}{J'ai toujours entendu que c'était une espionne.}
{115}{}{As-tu entendu quelque chose au sujet de cet espion ?}
{116}{}{Tu es l'espionne !}
{117}{}{Bonne chance. Désolé de t'avoir dérangé.}
{118}{}{Je parie que c'est ce fanfaron de Neil qui raconte tout ça. J'aurai à m'entretenir avec lui plus tard.}
{119}{}{Tu penses que Neil est l'espion ?}
{120}{}{Alors qui est l'espion selon toi ?}
{121}{}{Tu sembles un peu sur la défensive. Des explications ?}
{122}{}{Je suis presque sûr de ça. J'ai seulement besoin de preuves.}
{123}{}{Je vais te donner ta preuve.}
{124}{}{Il semble être quelqu'un de bien. Je ne sais pas.}
{125}{}{Pourquoi penses-tu que c'est lui ?}
{126}{}{Merci. Tu ne sais pas à quel point ce que cela signifie pour moi. Dès que tu as ta preuve, tue le.}
{127}{}{Qu'est-ce qu'il y a à savoir ? Il a accès aux Enfants de la Cathédrale. Il travaille pendant la nuit quand tout le monde se repose. Ca ne peut être que lui.}
{128}{}{Ok, je vais enquêter dans ce sens.}
{129}{}{Oublie ça. Je pense que tu essaies de me mettre sur une fausse piste !}
{130}{}{Je suis vraiment triste que tu penses de cette manière. Je ne peux pas côtoyer quelqu'un pensant que je suis un espion. Je vais avoir à te tuer maintenant.}
{131}{}{Il va chez les Enfants pendant la nuit. Personne ne le voit en mission. Ca doit être lui.}
{132}{}{Ok, je vais enquêter dans ce sens.}
{133}{}{Oublie ça. Je pense que tu essaies de me mettre sur une fausse piste !}
{134}{}{Je ne suis pas certaine de son identité. Je pense que ça peut être soit un garde soit une étudiante. Ils continuent à se faufiler dans la Cathédrale des Enfants durant la nuit.}
{135}{}{Penses-tu à d'autres pistes à suivre ?}
{136}{}{Mais j'ai entendu dire que seulement les éclaireurs font des raids jusque chez les Enfants.}
{137}{}{Ok. Merci pour ton aide.}
{138}{}{Pas vraiment. C'est juste que je pense que c'est un homme et probablement un étudiant ou un garde.}
{139}{}{Ok. Merci pour ton aide.}
{140}{}{Vrai. Nous les éclaireurs faisons de nombreux raids jusque chez les Enfants, et avec trop de pertes ces derniers temps. Cet espion nous coûte cher.}
{141}{}{Tu sembles très affolée. Je vais rechercher cet espion et le tuer.}
{142}{}{L'espion pourrait-il être un éclaireur ?}
{143}{}{Merci pour ton aide.}
{144}{}{Pourquoi l'un des éclaireurs ferait ça ?}
{145}{}{Si tu arrêtes les éclaireurs, alors tu arrêtes les raids.}
{146}{}{Je ne sais pas. Pourquoi feriez-vous ça ?}
{147}{}{Je ne sais pas. Je me pose la question.}
{148}{}{C'est plutôt une bonne idée. J'ai remarqué que Peter n'était jamais beaucoup attaqué pendant les raids. Je pense que c'est lui.}
{149}{}{Ok, je vais enquêter dans ce sens.}
{150}{}{Oublie ça. Je pense que tu essaies de me mettre sur une fausse piste !}
{151}{}{Tu penses que c'est moi ?}
{152}{}{Je suis désolé. Je suis un peu stressé.}
{153}{}{Oui ! Maintenant tu vas mourir !}
{154}{}{Alors inquiète toi pour d'autres choses. Je dois retourner au travail.}
{155}{}{Je pense qu'il pense que je suis l'espionne. Mais ce n'est pas moi.}
{156}{}{Peut-être qu'il a raison.}
{157}{}{Pourquoi penserait-il ça ?}
{158}{}{Parce que je suis le nouvel éclaireur. Je suis ici depuis seulement un an environ et les problèmes ont commencé il y a 5 mois à peu près.}
{159}{}{Je pense que Neil pourrait avoir raison.}
{160}{}{Je pense que Neil doit être l'espion. Je vais enquêter dans cette direction.}
{161}{}{Alors va voir ailleurs. Il n'y a pas de place pour toi.}
{162}{}{Si tu as besoin d'informations, va voir Nicole. Elle pense qu'elle sait tout.}
{163}{}{Je peux être persuadée de te raconter quelque chose sur ce qu'il se passe. Pour une certaine somme.}
{164}{}{Combien ?}
{165}{}{Tu vendrais des secrets ?}
{166}{}{Oublie ça. Je n'ai pas d'argent.}
{167}{}{300 caps et l'information est à toi.}
{168}{}{Bien sûr.}
{169}{}{Pas question.}
{170}{}{Il va y avoir un raid du côté Sud de la forteresse des Enfants. Maintenant va t'en.}
{171}{}{Tu essaies de m'arnaquer ? Tu vas voir comment ça se passe !}
{172}{}{Je regrette que tu aies ces impressions. Mais bonne journée à toi.}
{173}{}{J'ai besoin de m'en sortir en quelque sorte. Maintenant, veux-tu cette information ou non ?}
{174}{}{Bien sûr.}
{175}{}{Pas question.}
{176}{}{Rien. Maintenant laisse-moi.}
{177}{}{Laisse-moi. J'essaie de me reposer actuellement.}
