{100}{}{Voici le Shérif Justin Greene.}
{101}{}{Bon sang mais c'est le tueur d'innocents. J'ai entendu parler de toi et tu as de la chance que mon insigne m'interdise de te descendre sur place. Je te conseille de quitter notre ville. Sur-le-champ.}
{102}{}{Bonjour m'sieur ! Je suis Justin Greene. Je suis le shérif de cette bonne ville. Y'a-t-il quelque chose que je puisse faire pour vous ?}
{103}{}{Bonjour m'dame ! Je suis Justin Greene. Je suis le shérif de cette bonne ville. Y'a-t-il quelque chose qui je puisse faire pour vous ?}
{104}{}{Allez, crache le morceau !}
{105}{}{Decker vient de m'engager pour tuer un certain marchand et sa femme.}
{106}{}{Decker a essayé de m'engager pour tuer une dénommée Jain.}
{107}{}{Rien, excuse-moi.}
{108}{}{Je ne peux rien te dire, ou je suis un homme mort. Désolé.}
{109}{}{Merci. Nous faisons de notre mieux. C'est vraiment difficile dans une ville de cette taille, mais nous faisons notre possible avec les moyens que l'on a. Et c'est pas facile avec ces bandits qui possèdent de meilleures armes que nous.}
{110}{}{Merci encore.}
{111}{}{Il est temps que tu partes. Tueur d'enfants !}
{112}{}{Je comprends et je veux éviter ça. Mais, si tu changes d'avis, fais-le moi savoir. C' est dangereux et quelqu'un doit veiller au respect de la loi.}
{113}{}{Excellent ! Tu me confirmes ce que d'autres sources m'ont appris sur ses projets. C'était ce que j'attendais pour prendre des mesures contre lui. Ca va chauffer et j'ai besoin de toutes les bonnes volontés. Je peux te payer 1000 caps. 200 maintenant et le reste quand nous aurons terminé. Qu'est-ce que tu en dis ?}
{114}{}{Tu arrives trop tard... Sacré nom de nom ! Je savais que c'était lui le responsable. Si seulement j'avais pu l'arrêter à temps ! En tout cas, tu es le dernier témoin dont j'avais besoin. Nous devrons le "neutraliser". Ca va chauffer et j'ai besoin de toutes les bonnes volontés. Je peux te payer 1000 caps. 200 maintenant et le reste quand nous aurons terminé. Qu'est-ce que tu en dis ?}
{115}{}{Tu arrives trop tard... Qu'est-ce qui me dit que ce n'est pas toi qui es derrière tout ça ? Decker n'est pas homme à parler de sa vie et de ses plans au premier venu.}
{116}{}{Je viens d'apprendre qu'elle est déjà morte...attends une minute. Qu'est-ce qui me dit que ce n'est pas toi qui es responsable ? Decker n'est pas homme à parler de sa vie et de ses plans au premier venu et le laisser en vie.}
{117}{}{Ce sera avec plaisir.}
{118}{}{Je veux tout et tout de suite.}
{119}{}{Pas question. Débrouille-toi sans moi.}
{120}{}{Pas question. Tu me sembles digne de confiance mais il n'est pas dit que tu ne nous fausseras pas compagnie dès que ça chauffera un peu trop. Considère ça comme une sorte d'assurance risque.}
{121}{}{Ca roule.}
{122}{}{Débrouille-toi tout seul, Shérif.}
{123}{}{Super ! On peut y aller dès que tu es prêt.}
{124}{}{On peut y aller quand vous voulez.}
{125}{}{Bien. Au revoir.}
{126}{}{Ca me désole d'entendre ça. Si tu changes d'avis, fais-le-moi savoir mais sache que je n'attendrai pas très longtemps.}
{127}{}{C'est bon. Ca marche pour moi. Laisse-moi juste le temps d'aller chercher du matériel.}
{128}{}{C'est de la folie.}
{129}{}{Salut.}
{130}{}{Super ! Fais-moi savoir quand tu seras prêt mais ne mets pas trop longtemps.}
{131}{}{Quoi ? Tu crois que je vais le laisser tuer tout le monde sans broncher. J'ai une responsabilité vis-à-vis de cette ville. Ce sont des choses que tu ne peux pas comprendre.}
{132}{}{Tu as raison. A toi de jouer.}
{133}{}{Comment oses-tu m'accuser !}
{134}{}{Je me fiche de ce tu penses.}
{135}{}{Bon, je n'ai rien essayé de faire.}
{136}{}{On était au Faucon et il y avait pas mal de gens}
{137}{}{Ne m'en veux pas. Decker nous a montés les uns contre les autres pendant des années. Maintenant, je ne fais confiance à personne. Mais je pourrais avoir besoin de ton aide. Je te payerai 1000 caps. 200 maintenant et 800 quand nous en aurons terminé.}
{138}{}{On ne me la fait pas ! Tu as de la chance que je n'ai pas de preuve. Mais un bon conseil : quitte la ville avant que j'en trouve une.}
{139}{}{Voilà qui est étrange. Je n'ai jamais entendu dire qu'il arrivait à Decker de quitter son bureau. Il devient courageux. Cette saloperie d'assassin... merde ! Je finirai bien par l'avoir ! Si tu nous donnes un coup de main, je te payerai 1000 caps - 200 maintenant et 800 quand nous aurons terminé. Qu'est-ce que tu en dis ?}
{140}{}{C'est la plus grosse connerie que j'aie jamais entendue. Decker n'abandonne jamais son bureau. Je savais bien qu'il y avait quelque chose qui ne tournait pas rond chez toi. Tu as de la chance que je n'ai aucune preuve. Mais un bon conseil : quitte la ville avant que j'en trouve une !}
{141}{}{Ok, allons-y...}
{142}{}{Alors, tu viens te rendre ? Ca m'épate.}
{143}{}{Oui, je regrette.}
{144}{}{Me rendre ? Laisse-moi rire.}
{145}{}{Attrapez-le !}
{146}{}{Attrapez-la !}
{147}{}{C'est en cellule que tu vas te retrouver.}
{148}{}{Reste tranquille. Tu n'iras nulle part.}
{149}{}{Un fugitif ! Attrapez-le !}
{150}{}{Une fugitive ! Attrapez-la !}
{151}{}{On peut y aller ?}
{152}{}{Oui.}
{153}{}{Non.}
{154}{}{Euh...}
{155}{}{Je ne peux pas croire que Decker soit enfin mort. Je pensais ne jamais vivre assez longtemps pour voir ce jour.}
{156}{}{Est-ce que tu as changé d'avis ? Tu peux encore nous aider à nous débarrasser de cette gangrène dont nous avons parlé.}
{157}{}{C'est d'accord.}
{158}{}{Non.}
{159}{}{Bah ?}
{160}{}{Nous te surveillons.}
{161}{}{J'ai été témoin d'un crime !}
{162}{}{Tu fais du bon boulot.}
{163}{}{Je ne fais que passer. Salut.}
{164}{}{Oula.}
{165}{}{Bonjour, monsieur. A quoi puis-je vous être utile ?}
{166}{}{Bonjour, m'dame. A quoi puis-je vous être utile ?}
{167}{}{Bonjour. A quoi puis-je vous être utile ?}
{168}{}{Ah oui ?}
{169}{}{Va cuver ton vin, ok ?}
