{100}{}{Voici un officier de police.}
{101}{}{Bonjour ! Tu devrais faire attention... euh, je veux dire... [l'officier regarde d'un drôle d'air les autres officiers et leur fait signe de la tête en te montrant.]}
{102}{}{Salut étranger... Attends ! Je te reconnais ! Tu fais l'objet d'un avis de recherche pour vol ! Pas un geste !}
{103}{}{C'est bon, je me rends.}
{104}{}{Je vais te descendre !}
{105}{}{Karr Rok !}
{106}{}{[Rends-toi.]}
{107}{}{Fais gaffe, le coin n'est pas très sûr.}
{108}{}{Fais gaffe à tes scripts, }
{109}{}{mec.}
{110}{}{poulette.}
{111}{}{Tu ne devrais pas être ici. L'endroit n'est pas sûr.}
{112}{}{La Vieille Ville n'est vraiment plus qu'un tas de ruines.}
{113}{}{Ca pue ici.}
{114}{}{On devrait tout raser.}
{115}{}{Je sais que ce foutu Cercle des Voleurs se trouve ici, quelque part.}
{116}{}{Pauvre Harold, il n'a pas rigolé tous les jours.}
{117}{}{Pas de conneries, hein ?}
{118}{}{Hé. Je te connais. Plus de bagarre, d'accord ?}
{119}{}{Ne t'avise pas de recommencer à te battre !}
{120}{}{La prochaine fois qu'on te surprend en train de te bagarrer ce sera la taule !}
{121}{}{T'as entendu ? Les Marchands du Lointain se sont fait balayés.}
{122}{}{Les Marchants d'Eau, c'est plus que de l'histoire ancienne. Quelle chance !}
{123}{}{Quelqu'un a décimé la Caravane Ecarlate.}
{124}{}{T'as entendu ! L'Underground a finalement été anéanti !}
{125}{}{Decker est Mort !}
{126}{}{Débarrassée de Decker, cette ville serait plus sûre.}
