{100}{}{Voici un chasseur de primes très costaud avec une pancarte où l'on peut lire, "Je suis Christopher et tu es mon bifteck".}
{101}{}{Qu'est-ce que tu veux ?}
{102}{}{Un beignet.}
{103}{}{Que fais-tu ici ?}
{104}{}{Je jetais un coup d'œil.}
{105}{}{Rien.}
{106}{}{Ici, on n'aime pas trop ceux qui se la jouent. Décampe.}
{107}{}{Cette blague n'était déjà pas marrante la première fois. Tu es sur le point de découvrir pourquoi je suis l'un des chasseurs de primes les plus craints du désert. Et je me ferai même pas payer pour ça !}
{108}{}{None of your business.}
{109}{}{Bon, va voir ailleurs si j'y suis.}
{110}{}{Tu savais que ta tête a été mise à prix pour }
{111}{}{[Christopher te regarde avec attention, envisageant quelque chose... on dirait qu'il vient de prendre une décision] Dis-moi, à quel rythme rends-tu visite au Centre ou à Dépotville ?}
{112}{}{Assez souvent, pourquoi cette question ?}
{113}{}{Et bien, tu vois... Le travail m'occupe presque à plein temps et je n'ai aucune opportunité pour me rendre là-bas. Et en tant que fumeur invétéré, un bon vieux briquet Zippo me manque terriblement. On dit que de nombreux objets d'avant-guerre peuvent se trouver dans les magasins là-bas. Si tu me rapportes un Zippo, je partagerai avec toi des informations au sujet des bases voisines. Je pense que cela pourrait t'être utile !}
{114}{}{Quel dommage. On dirait que je me suis trompé sur ton compte. Dégage de là.}
{115}{}{Pourquoi pas, je t'en trouverai un.}
{116}{}{D'accord.}
{117}{}{Hé, j'en ai justement un ici. J'en ai pas vraiment besoin et je peux te le donner en échange d'informations.}
{118}{}{Merci ! [Il prend le briquet] Donc, qu'as-tu besoin de savoir, exactement ?}
{119}{}{Voici ton briquet. Il est temps de me donner des informations.}
{120}{}{Pas d'autres questions, merci.}
{121}{}{[Plus]}
{122}{}{Que veux-tu savoir d'autre ?}
{123}{}{Je cherche des informations.}
{124}{}{beuuh.. que ?}
{125}{}{T'es sérieux ? Hors de ma vue !}
{126}{}{Je vais rendre service au monde en te logeant une balle dans le crâne !}
{200}{}{ caps, pour avoir assassiné des enfants ? C'est le moment de rafler la mise !}
