{100}{}{Tu vois un jeune homme aux traits fins.}
{101}{}{Tu vois : Jason Zimmerman.}
{102}{}{Hé, tu viens de très loin ? As-tu vécu beaucoup d'aventures ?}
{103}{}{Oui, je viens d'un saut loin au nord.}
{104}{}{En fait, je viens de Mars. Tu veux voir ma lance de feu ?}
{105}{}{J'ai vécu quelques aventures.}
{106}{}{Je n'ai pas fait grand-chose, vraiment.}
{107}{}{Euh, loin. D'un Abri.}
{108}{}{Oh. Je pensais que quelqu'un qui avait traversé les déchets à l'extérieur serait, eh bien, plus intelligent. Pas grave.}
{109}{}{Miles dit que maintenant que tu as ces pièces, il peut faire fonctionner les fermes, pour qu'on n'ait pas à vendre des balles au Centre. Je n'y ai jamais vraiment pensé jusqu'à ce que Smitty fasse remarquer que les balles qu'il fabriquait étaient }
{110}{}{vendus au Hub, qui les vendait aux gangs. Je suppose que tu as trouvé une bonne solution.}
{111}{}{Je n'ai jamais pensé que nous serions capables d'arrêter de combattre les gangs. Mon père m'a raconté comment tu leur as fait promettre de nous laisser tranquilles. Tu sais, je pensais que j'ai toujours voulu partir à l'aventure, mais je crois que j'aime... eh bien, la }
{112}{}{sentiment de sécurité ici maintenant. Plus besoin de s'inquiéter des attaques soudaines des gangs et de se demander qui va être tué.}
{113}{}{Lorraine dit qu'il y avait un Abri au sud d'ici, où beaucoup de mes grands-parents vivaient. C'est comment de vivre dans un Abri ?}
{114}{}{C'est plutôt ennuyeux, en fait.}
{115}{}{C'est très excitant. Nous avons toutes sortes de technologies, tu ne le croirais pas !}
{116}{}{Oh. Eh bien, tu as dû vivre quelques aventures après être parti, non ?}
{117}{}{Pas vraiment.}
{118}{}{Oui, il y a pas mal de danger dehors.}
{119}{}{Comme quelqu'un l'a écrit un jour, "l'aventure, c'est quelqu'un d'autre, très loin, qui passe un moment très désagréable".}
{120}{}{Euh. Les marchands du Centre parlent de radscorpions et autres.}
{121}{}{En fait, c'est surtout le désert.}
{122}{}{Eh bien, en fait, il y a toutes sortes de monstres là dehors.}
{123}{}{Vraiment ? Quels types de monstres as-tu combattus ?}
{124}{}{Pas grand chose, juste quelques rats et autres.}
{125}{}{Ouais, les gardes du Centre ont dit qu'il y a beaucoup de choses mutantes radioactives qui vivent dans le désert. La chasse aux monstres doit être une vraie orgie !}
{126}{}{Oui, c'est vraiment le pied !}
{127}{}{Non, c'est plus une douleur. Venin, morsures, radiations... c'est mortel.}
{128}{}{J'aimerais pouvoir partir à l'aventure un jour.}
{129}{}{Je n'ai jamais pensé à ça. J'aime plutôt avoir de l'eau propre et un endroit où rester.}
{130}{}{Je pensais que vivre dans le désert serait... tu sais... rude, et dangereux, et tout. Mais je suppose qu'on a de quoi s'occuper ici, avec les gangs et tout.}
{131}{}{Quoi, t'es une sorte de cinglé ou quoi ? Caleb n'aurait jamais dû te laisser passer les portes !}
{132}{}{C'est cool. Tout ce qu'on a ici, c'est ce stupide puits et ces fermes souterraines que Miles essaie de faire fonctionner.}
{133}{}{Oui, j'ai remarqué que tu n'as pas de sac de couchage ou autre. Ça doit être plutôt sale et inconfortable là-dehors.}
{134}{}{Rebonjour. Tu as des histoires intéressantes à raconter ?}
{135}{}{Que veux-tu savoir ?}
{136}{}{Pas vraiment.}
{137}{}{Eh bien, si tu fais quelque chose d'intéressant, raconte-moi tout !}
{138}{}{Laisse-moi tranquille !}
{139}{}{Dieu merci, tu es là ! S'il te plaît, aide-moi à sortir d'ici !}
{140}{}{Ayuh.}
{141}{}{Ne t'inquiète pas, je vais nous sortir de là.}
{142}{}{Désolé gamin, tu te débrouilles tout seul !}
{143}{}{Que fais-tu ici ?}
{144}{}{Merci !}
{145}{}{S'il te plaît, ne me quitte pas !}
{146}{}{Je pensais qu'il serait amusant de quitter Le Sanctuaire et d'explorer le monde. Mais les Ecorcheurs m'ont attrapé et m'ont retenu ici. S'il te plaît, aide-moi !}
{147}{}{Très bien, sortons d'ici !}
{148}{}{Pas question. Tu t'es mis dans ce pétrin, tu t'en sors.}
{149}{}{J'espère que nous sortirons bientôt d'ici !}
