{100}{}{Tu pense que ce cuir va te sauver de Baka ?}
{101}{}{Tu fais pas le poids contre nous !}
{102}{}{Si j'étais aussi moche, je me serais tué.}
{103}{}{Les Crypts, vous n'avez aucune chance.}
{104}{}{Tu sens la douleur ?}
{105}{}{Je vais adorer ça.}
{106}{}{Tu vas mourir minable !}
{107}{}{L'heure de la revanche a sonnée.}
{108}{}{Es-tu prêt à avoir mal ?}
{109}{}{Y a que Rayze qui peut être aussi stupide que toi.}
{110}{}{J'imagine que la petite pute peut vivre encore un moment...}
{111}{}{Sales Crypts ! On va vous enterrer !}
{112}{}{Meurt connard !}
{113}{}{Qui t'a dit que tu pouvais quitter ton cercueil ? Returne-y !}
{114}{}{On va eradiquer les gars de ton espèce !}
{115}{}{Seuls les Fools ont la sagesse nécessaire pour contrôler Scrapheap.}
{116}{}{Disparait, bave de poulet à trois pattes !}
{117}{}{Qu'est-ce qui t'est arrivé ? Ta mère t'a bercé contre un mur ?}
{118}{}{}
{119}{}{}
{120}{}{}
{200}{}{Courrez, Fools, tant que vous avez encore une chance de survivre.}
{201}{}{Hey, Rayze ! La chasse est ouverte ! Et les Fools sont en tête de liste des animaux stupides.}
{202}{}{Hey les gars ! Laissez-moi un Fool à tuer.}
{203}{}{Les Crypts vont t'envoyer dans ta tombe!}
{204}{}{Les idiots n'ont pas le droit de vivre.}
{205}{}{L'idiotie va disparaître.}
{206}{}{Regarde qui vient de se prendre un joli coup de bâton !}
{207}{}{Tu vas te faire enterrer, Fool !}
{208}{}{Je vais enfin pouvoir botter des culs ! J'attendais que ca !}
{209}{}{Les Crypts reignent ! Et les Fools craignent !}
{210}{}{On est les missionnaires de la faucheuse !}
{211}{}{T'inquiète ! Ca sera rapide et douloureux !}
{212}{}{DES BABOUINS VIOLETS !}
{213}{}{Les Brahmines ont plus de jugement qu'un Fool.}
{214}{}{Les Fools sont tellement faibles que même Lex peut tous les battre à lui tout seul.}
{215}{}{Haha! Ca nous fait plus de fools à tuer!!}
{216}{}{La seule chose que les Fools vont contrôler est un putain de sarcophage.}
{217}{}{Il était temps. J'attendais que ça.}
{218}{}{Même Lenny vise mieux que toi.}
{219}{}{Mangez du métal, Fools.}
{220}{}{Je planterais ta tête sur un pieux.}
{300}{}{Hey! Le générateur est brisé. Quittons ce taudis.}
{400}{}{Maintenant que le generateur est brise, les gangs n'ont plus aucune raison de se battre pour Scrapheap. ton boulot ici est termine, mais ta mission de retrouver la puce d'eau continue.}
{402}{}{Maintenant que les gangs sont elimines, Scrapheap est de nouveau un havre de paix.}
