{100}{}{Tu as mis Larry hors de lui.}
{101}{}{Voici Larry.}
{102}{}{Si tu déranges le chef, il n'hésitera pas à te frapper.}
{103}{}{Les humains ne sont pas autorisés à entrer dans Nécropolis. Tu vas venir avec moi.}
{104}{}{Mais...}
{105}{}{Jamais !}
{106}{}{Eh !}
{107}{}{Crève, humain !}
{108}{}{Le mutant t'ignore.}
{1000}{}{Eau}
{1001}{}{Nécropolis}
{1002}{}{Set}
{1003}{}{Watershed}
{1004}{}{Hall}
{1005}{}{Lou}
{1006}{}{Goules}
{1007}{}{Normaux}
{1100}{}{Je ne sais pas.}
{1101}{}{Tu y es.}
{1102}{}{C'est un dégonflé. On devrait les éliminer lui et ses Goules.}
{1103}{}{C'est ici.}
{1104}{}{Je ne sais pas.}
{1105}{}{Lui, le chef de Harry.}
{1106}{}{Des poules mouillées.}
{1107}{}{Encore plus poules mouillées que les Goules.}
