{100}{}{Voici un Chevalier.}
{101}{}{Bonjour Initié. Je m'appelle Larry. Que puis-je pour toi ?}
{102}{}{Vree m'a dit que tu pourrais me montrer un pistolet laser.}
{103}{}{Vree m'a dit que tu pourrais me donner un pistolet laser.}
{104}{}{Euh...}
{105}{}{Euh, d'accord...}
{106}{}{Euh, oui. C'est une arme très efficace. Sa portée est de... enfin, très longue. [Larry continue à parler pendant un temps qui te semble interminable mais tu as l'air d'apprendre quelques astuces sur l'utilisation des armes à énergie.]}
{107}{}{Hein ? Pourtant elle sait qu'ils ne sont pas encore prêts... Oh, elle doit vouloir que je te les montre. Oui, je peux te les montrer. Tu vois, ça fonctionne avec des cellules énergétiques faites à partir de... [Larry continue sur sa lancée pendant un temps qui te semble interminable mais tu as l'air d'apprendre quelques astuces sur l'utilisation des armes à énergie.]}
{108}{}{Ouais, c'est ça, bien sûr. 'vaudrait mieux que tu partes.}
{109}{}{Je n'aime pas les menteurs, va-t'en.}
{200}{}{Ca ne va pas du tout.}
{201}{}{Allons-y.}
{202}{}{Le mécanisme de mise à feu n'arrête pas de se bloquer.}
{203}{}{C'est beaucoup mieux.}
{204}{}{Presque.}
{205}{}{Ca va prendre un certain temps.}
{206}{}{Voilà d'où vient le problème !}
{207}{}{John, je crois que j'ai trouvé d'où vient le problème.}
{208}{}{Damn!}
{209}{}{Merde !}
{210}{}{C'est de ma faute !}
{211}{}{Je vais bien.}
{212}{}{Ca fait mal.}
{213}{}{C'est ce que je voulais.}
{214}{}{Mais pourquoi ça se produit tout le temps ?}
{215}{}{My eyes!}
{216}{}{Tu n'es pas un chevalier.}
{217}{}{Je dois parler à un chevalier.}
{218}{}{Je ne comprends pas, les cellules n'arrêtent pas de se décharger.}
{219}{}{Tu ferais mieux de reculer. Ca pourrait être dangereux.}
{220}{}{Ne me dérange pas, s'il te plaît.}
{221}{}{Regarde où tu mets les pieds.}
{222}{}{Tu cherches ton chemin ?}
{223}{}{Excuse-moi, je ne peux pas parler pour l'instant.}
{300}{}{Les armes à énergie augmentent de 5%.}
