{101}{}{Une nuée de rats fonce sur toi !}
{102}{}{Soudain, une nuée de mantes mutantes t'attaque !}
{103}{}{Soudain, une nuée de mantes mutantes t'attaque !}
{104}{}{Un horrible cadavre partiellement dévoré se trouve non loin d'ici.}
{105}{}{Tu trébuches dans un sorte de flaque d'eau.}
{106}{}{Assoiffé, tu bois de l'eau... Elle a mauvais goût.}
{107}{}{L'eau semble hautement radioactive et infecte.}
{200}{}{You stumble upon some water pools.}
{201}{}{Out of dire thirst, you drink some water... It doesn't taste so good.}
{202}{}{The water looks highly radioactive and foul.}
{203}{}{Ahhh...}
{204}{}{Arrgg...}
{205}{}{Yuck!}
{1000}{}{Tu gagnes }
{1001}{}{ points d'expérience pour avoir utilisé avec succès ta compétence Vie en plein air.}
{1002}{}{Encounter: "}
{1003}{}{"}
{1004}{}{. Do you wish to engage?}
{1005}{}{Oui.}
{1006}{}{Non.}
{1007}{}{}
{1008}{}{}
{1009}{}{}
{1010}{}{You are ambushed by a blood-thirsty bounty hunter and his goon squad!}
