{100}{}{Voici Tandi.}
{101}{}{Qu'est-ce qu'il y a d'autre dans les parages ?}
{102}{}{Que se passe-t-il ici ?}
{103}{}{T'as entendu des histoires sur le Sud ?}
{104}{}{Ca te plaît ici ?}
{105}{}{Eh bien, c'est à peu près tout. Merci de ta patience.}
{106}{TAND_1}{Salut ! J'ai entendu dire qu'il y avait un voyageur en ville, mais je voulais pas l'croire sans l'voir. Je m'appelle Tandi, et toi ?}
{107}{}{Je m'appelle }
{108}{}{.}
{109}{}{Mon nom c'est }
{110}{}{. Ne l'oublie pas.}
{111}{}{Hein ?}
{112}{TAND_2}{Alors... Elle te plaît not' p'tite ville ? T'as déjà l'bourdon ?}
{113}{}{Pas mal dans le genre. Mais, est-ce que je peux te poser quelques questions ?}
{114}{}{Bof. Y'a rien à faire ici à part regarder les brahmimes copuler.}
{115}{}{Ouais...}
{116}{}{Euh, oui. Pas très folichon.}
{117}{TAND_3}{Oui, bien sûr. J'suis jamais sortie d'ici, alors j'sais pas à quoi j'peux t'être utile. Bon, qu'est-ce que tu veux savoir ?}
{118}{TAND_4}{Ouais. Oh, ça s'voit qu et'habites pas là. Y'a rien d'intéressant, et j'te dis pas, jouer à embêter les brahmines, ça lasse vite.}
{119}{}{Si tu t'ennuies tellement, pourquoi tu fous pas le camp ?}
{120}{}{Oh, j'suis sûr que t'exagères.}
{121}{}{Ca semble mignon et tranquille ici.}
{122}{TAND_5}{Moi, partir ? Si seulement ! Mais j'saurais pas m'débrouiller toute seule et personne veut s'en aller. En plus, mon père dit qu'il f'rait une crise cardiaque si quelque chose m'arrivait !}
{123}{}{Dur tout ça. Est-ce que je peux te poser quelques questions ?}
{124}{}{Heu, faut que j'y aille. Bonne chance.}
{125}{TAND_6}{Euh... Je dois rester ici.}
{126}{TAND_12}{Reste habiter ici toute ta vie et tu verras si ça t'plaît ! Autre chose que tu veux savoir ?}
{127}{TAND_13}{Oh ça, pour être tranquille... et tellement chiant que j'ai l'impression qu'mon cerveau se ramollit tous les jours un peu plus.}
{128}{}{Pourquoi tu pars pas ?}
{129}{}{Je compatis mais malheureusement j'ai pas beaucoup de temps... Je peux te poser quelques questions ?}
{130}{TAND_14}{Enfin quelqu'un d'lucide ! Bien sûr, t'as sans doute voyagé, alors pour toi ici, ça doit être un vrai trou !}
{131}{}{Si tu t'ennuies tellement, pourquoi tu fous pas le camp ?}
{132}{}{Oh, j'suis sûr que t'exagères.}
{133}{}{Ca semble mignon et tranquille ici.}
{134}{TAND_15}{Dépôtville est au Sud-Ouest, mais je sais pas à quelle distance. Et puis, y'a cet endroit bizarre, la Cité de la Mort. Ah, et puis l'autre... Oh, zut, j'ai son nom sur le bout de langue... Ah ouais, le Centre.}
{135}{TAND_15a}{Y'a quelques villes vers le Sud. Mais un grand voyageur comme toi, t'as déjà dû les visiter.}
{136}{}{Merci.}
{137}{TAND_16}{Pas de problème. Autre chose ?}
{138}{TAND_20}{On a les radscorpions ! Enfin, c'est pas une bonne chose, mais y'a personne qu'est mort d'leurs piqûres. Et c'est c'qu'on a d'plus passionnant ici !}
{139}{TAND_21}{Pas grand-chose, surtout depuis qu't'as rossé ces radscorpions. Waouh, j'aurais bien voulu voir ça !}
{140}{TAND_22}{Same as always. Bo-ring.}
{141}{TAND_23g}{L'histoire la plus bizarre que j'ai entendue, c'est sur le Griffemort.}
{142}{TAND_23b}{Just stuff.}
{143}{}{Merci.}
{144}{}{Le Griffemort ?}
{145}{TAND_24}{Ca peut aller. Enfin, c'est chez nous, tout ça... mais je m'ennuie à mourir ! Tu sais, j'aimerais voir du pays.}
{146}{}{Si tu t'ennuies tellement, pourquoi tu fous pas le camp ?}
{147}{}{Oh, j'suis sûr que tu noircis le tableau !}
{148}{}{Ca semble mignon et tranquille ici.}
{149}{TAND_27m}{J'suis pas celle que tu crois. Adresse-toi à une brahmime ou à j'sais pas quoi.}
{150}{TAND_27f}{Ecoute...euh...Je, euh... J'aime les mecs, ok ? Euh, excuse-moi, j'ai du lait sur le feu.}
{151}{TAND_28}{Eh bien, merci pour la causette. Y'a pas souvent d'étrangers ici, alors ça fait toujours plaisir d'parler à quelqu'un qu'est pas du coin. Allez, a plus !}
{152}{}{Salut.}
{153}{TAND_29}{Euh, écoute. Faut que j'm'occupe des brahmines. C'était, euh, cool... de t'parler.}
{154}{TAND_30a}{Salut, te revoilà ! Qu'est-ce que j'peux faire pour toi cette fois ?}
{155}{}{Je peux encore te poser quelques questions ?}
{156}{}{Rien. Salut.}
{157}{TAND_35}{Euh... merci. A plus tard.}
{158}{TAND_36}{Salut ! J'avais peur qu't'aies mis les voiles et d'pas pouvoir te r'mercier de m'avoir sauvée. Ah ! C'était super ! De l'action, de l'aventure... Et si j'peux faire quelque chose pour toi, te gêne pas.}
{159}{}{Eh bien, quelques questions ?}
{160}{}{Et si toi et moi... eh bien, tu sais... nous deux... ensemble.}
{161}{}{Non, c'est bon, merci.}
{162}{}{Ben, euh !!}
{163}{TAND_37}{Qui t'es ? Qu'est-ce tu veux ?}
{164}{}{Je m'appelle }
{165}{}{, et ton père m'envoie.}
{166}{}{Je suis ta bonne fée. Alors, qu'est-ce que t'en dis ?}
{167}{}{Euh, ben...}
{168}{TAND_38}{Mon père t'envoie !? T'es là pour m'faire sortir ?}
{169}{}{Oui, alors bouge pas. Je vais te faire sortir.}
{170}{}{Non, il m'envoie juste te regarder.}
{171}{TAND_39}{Alors, c'est quoi ton plan ?}
{172}{}{T'attends juste que les portes s'ouvrent. Et là, tu cours !}
{173}{}{Je vais combattre le chef des Khans en échange de ta liberté.}
{174}{TAND_40}{C'est ça, ton plan ? Hmm, ok. Mais fais vite. J'les ai entendus parler et j'aime pas ce qu'ils mijotent.}
{175}{TAND_41}{Toi ? L'combattre ? Tu t'fous de moi ! [Soupir] Ecoute, si t'as une autre idée, tu m'fais signe, ok ?}
{176}{TAND_42}{Oh, j'vois qu'on a de l'humour, hein ? Tu m'fais sortir d'ici ou quoi !?}
{177}{}{Ouais. Tu bouges pas, et dès que tu vois la porte ouverte, tu cours.}
{178}{}{Je vais combattre le chef des Khans en échange de ta liberté.}
{179}{TAND_43}{Oh, c'est encore toi ! Alors, tu vas m'faire sortir ?}
{180}{}{Oui, alors bouge pas. Je vais te faire sortir.}
{181}{}{Non, je passe juste te dire au revoir.}
{182}{}{Euh, ben...}
{183}{TAND_43a}{Bonjour, y'a quelqu'un à l'étage ? Tu peux m'faire sortir d'ici ? Peux-tu ME - FAIRE - SORTIR ?!}
{184}{TAND_43b}{Pas le temps d'bavarder, il faut qu'on sorte d'ici.}
{185}{TAND_44}{Aradesh c'est mon père. Il est pas trop pénible pour un paternel.}
{186}{TAND_45}{C'est moi. Qui d'autre tu croyais ?}
{187}{TAND_46}{Razlo, c'est l'vieux type à l'Est de la ville. C'est un bon toubib, même si c'est un fossile.}
{188}{TAND_47}{Seth c'est l'capitaine des gardes. Mon père a essayé de nous brancher, mais c'est pas mon type.}
{189}{TAND_48}{Agathe est la doyenne. On l'adore, surtout pour ses histoires. Va la voir si tu veux en entendre une.}
{190}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{191}{TAND_50}{C'est là qu'on a toute notre eau. Ca existe depuis avant ma naissance.}
{192}{TAND_51}{I've actually seen one, even if it was from far away. They're nasty creatures, with claws and a big stinger. And their poison can be deadly if it isn't treated. You should talk to my dad, Aradesh, he knows more about them.}
{193}{TAND_52}{I heard a tale from a traveler up from the south. He said the Deathclaw was a creature that killed people at night. He said no one can catch it, because it can disappear like smoke. Not that I believe it, of course.}
{194}{TAND_53}{Junktown's a small city to the southwest. It's supposed to have pretty good trading, but my father won't even look into it. He says we need to stay 'protected'. Yeah, right. Caged is more like it.}
{195}{TAND_54}{Agatha est la doyenne. On l'adore, surtout pour ses histoires. Va la voir si tu veux en entendre une.}
{196}{TAND_55}{I don't know, but the guy who told me about it was really scared of it. He said that the undead walked the streets!}
{197}{TAND_62}{I don't know. You might want to ask Seth or my father about it, though.}
{198}{TAND_63}{Hmm... Ca m'dit rien.}
{199}{TAND_64}{Hmm... non. Jamais entendu parler.}
{200}{TAND_65}{Ehh ! Où tu t'crois ? Remets ça en place !}
{201}{TAND_66}{Bon ! Je vais le dire à mon père !}
{202}{TAND_67}{J'hallucine, qu'est-ce que tu fous ? Arrête !}
{203}{TAND_68}{Qu'est-ce que tu fous ici ? Tu ferais mieux de partir avant que mon père s'réveille.}
{204}{TAND_69}{Like I said...}
{205}{TAND_70}{Ecoute, je t'ai déjà dit...}
{206}{TAND_71}{Encore ? Eh, oh ? Combien de fois faut j'te dise ? T'as de la cire dans les oreilles ou quoi ?}
{207}{TAND_72}{Oh ouais, j'en ai entendu parler, mais adresse-toi plutôt à Agathe. Elle en saura plus long qu'moi.}
{208}{}{Partons d'ici.}
{209}{}{Duh!}
{300}{}{Waouh ! Ca n'a rien à voir avec les Sables Ombragés !}
{301}{}{Dis, c'est quoi, là-bas ?}
{302}{}{J'ai hâte de raconter de quoi a l'air le monde extérieur aux gens des Sables Ombragés !}
{303}{}{Il y a d'autres radscorpions ?}
{304}{}{Où allons-nous maintenant ?}
{305}{}{Quand est-ce qu'on arrive ?}
{350}{TAND_16a}{Yeah, whatever.}
{399}{}{[Continue]}
{400}{TAND_3}{Bien sûr, d'accord. J'suis jamais sortie d'ici, donc je n'sais pas en quoi j'peux t'aider. De quoi t'as besoin ?}
{402}{TAND_28}{Bien, merci pour ce... "partage". [elle sourit et te fait un clin d'oeil] On n'a pas beaucoup d'étrangers ici, alors c'est toujours agréable de "partager" avec de nouvelles personnes. Bon, à plus !}
{404}{}{C'est quelque chose que je n'veux pas que les autres entendent. Allons dans un endroit plus discret, et j'te dirais...}
{405}{}{Tu as l'air plutôt... inexpérimenté. J'aimerais t'enseigner tout c'que j'connais. On devrait s'y mettre tout de suite, il y a beaucoup à faire. [clin d'oeil]}
{406}{}{*Soupir* Plus que tu peux fournir, mais je m'en contenterai.}
{407}{}{[Continue]}
{410}{TAND_14}{Enfin quelqu'un d'lucide ! Bien sûr, t'as sans doute voyagé, alors pour toi ici, ça doit être un vrai trou ! [Elle hausse les épaules et te mène dans sa chambre]}
{412}{}{[Elle sourit et t'emmène dans sa chambre]}
{415}{}{J'aimerais avoir un peu plus de fun, quand t'as l'temps.}
{500}{}{Can you answer a few questions first?}
{501}{}{Nope! That was it. Thanks, Tandi.}
{502}{}{On second thought, never mind. Let's go!}
{503}{}{Just wanted to say hi. You're great.}
{504}{}{Me like prity gurl.}
{505}{}{Elp?}
{506}{}{Me tell.}
{507}{}{Oof.}
{508}{}{Make boom-boom?}
{509}{}{}
{510}{}{Let's discuss our tactics and formation.}
{511}{}{Utilise ta meilleure arme.}
{512}{}{Change ton armure.}
{980}{TAND_62}{I don't know. You might want to ask Seth or my father about it, though.}
{981}{TAND_63}{Hmm... Ca m'dit rien.}
{982}{TAND_64}{Hmm... non. Jamais entendu parler.}
{1000}{}{Aradesh}
{1001}{}{Tandi}
{1002}{}{Seth}
{1003}{}{Pillards|Pillards|Khans|Khan}
{1004}{}{Well}
{1005}{}{Radscorpions}
{1006}{}{Griffemort|Griffes|Griffe|Griffemorts}
{1007}{}{Dépôtville}
{1008}{}{Centre}
{1009}{}{City}
{1010}{}{Razlo|Medic|Doc|Docteur|Médecin|Medecin|Aide|Guérison|Guerison|Blessure|Blessé|Blesse|Fracture}
{1011}{}{Khans}
{1012}{}{Razlo}
{1013}{}{Sables Ombragés}
{1014}{}{The Hub}
{1015}{}{Water Chip}
{1016}{}{Abri}
{1017}{}{Alya}
{1018}{}{Diana}
{1019}{}{Gwen}
{1020}{}{Petrox}
{1021}{}{Tolya}
{1022}{}{Raider}
{1023}{}{Khan}
{1024}{}{Deathclaws}
{1025}{}{Garl}
{1026}{}{Sables}
{1027}{}{Ombragés}
{1028}{}{Radscorpion}
{1029}{}{Radscorpions}
{1030}{}{Rad}
{1031}{}{Booze}
{1032}{}{stimulants}
{1033}{}{The Vault}
{1034}{}{Eau}
{1035}{}{Puce d'eau|Puce eau|Puce|Eau|Controleur}
{1037}{}{Dead}
{1038}{}{Nécropolis}
{1039}{}{Junk}
{1040}{}{Deathclaw}
{1041}{}{Death}
{1042}{}{Camp}
{1100}{TAND_44}{Aradesh c'est mon père. Il est pas trop pénible pour un paternel.}
{1101}{TAND_45}{C'est moi. Qui d'autre tu croyais ?}
{1102}{TAND_47}{Seth c'est l'capitaine des gardes. Mon père a essayé de nous brancher, mais c'est pas mon type.}
{1103}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{1104}{TAND_50}{C'est là qu'on a toute notre eau. Ca existe depuis avant ma naissance.}
{1105}{TAND_51}{I've actually seen one, even if it was from far away. They're nasty creatures, with claws and a big stinger. And their poison can be deadly if it isn't treated. You should talk to my dad, Aradesh, he knows more about them.}
{1106}{TAND_52}{I heard a tale from a traveler up from the south. He said the Deathclaw was a creature that killed people at night. He said no one can catch it, because it can disappear like smoke. Not that I believe it, of course.}
{1107}{TAND_53}{Junktown's a small city to the southwest. It's supposed to have pretty good trading, but my father won't even look into it. He says we need to stay 'protected'. Yeah, right. Caged is more like it.}
{1108}{TAND_54}{Agatha est la doyenne. On l'adore, surtout pour ses histoires. Va la voir si tu veux en entendre une.}
{1109}{TAND_55}{I don't know, but the guy who told me about it was really scared of it. He said that the undead walked the streets!}
{1110}{TAND_51}{I've actually seen one, even if it was from far away. They're nasty creatures, with claws and a big stinger. And their poison can be deadly if it isn't treated. You should talk to my dad, Aradesh, he knows more about them.}
{1111}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{1112}{TAND_46}{Razlo, c'est l'vieux type à l'Est de la ville. C'est un bon toubib, même si c'est un fossile.}
{1113}{TAND_22}{Same as always. Bo-ring.}
{1114}{TAND_54}{Agatha est la doyenne. On l'adore, surtout pour ses histoires. Va la voir si tu veux en entendre une.}
{1115}{TAND_62}{I don't know. You might want to ask Seth or my father about it, though.}
{1116}{TAND_62}{I don't know. You might want to ask Seth or my father about it, though.}
{1117}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{1118}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{1119}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{1120}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{1121}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{1122}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{1123}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{1124}{TAND_52}{I heard a tale from a traveler up from the south. He said the Deathclaw was a creature that killed people at night. He said no one can catch it, because it can disappear like smoke. Not that I believe it, of course.}
{1125}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
{1126}{TAND_22}{Same as always. Bo-ring.}
{1127}{TAND_22}{Same as always. Bo-ring.}
{1128}{TAND_51}{I've actually seen one, even if it was from far away. They're nasty creatures, with claws and a big stinger. And their poison can be deadly if it isn't treated. You should talk to my dad, Aradesh, he knows more about them.}
{1129}{TAND_51}{I've actually seen one, even if it was from far away. They're nasty creatures, with claws and a big stinger. And their poison can be deadly if it isn't treated. You should talk to my dad, Aradesh, he knows more about them.}
{1130}{TAND_51}{I've actually seen one, even if it was from far away. They're nasty creatures, with claws and a big stinger. And their poison can be deadly if it isn't treated. You should talk to my dad, Aradesh, he knows more about them.}
{1131}{TAND_23b}{Just stuff.}
{1132}{TAND_23b}{Just stuff.}
{1133}{TAND_62}{I don't know. You might want to ask Seth or my father about it, though.}
{1134}{TAND_62}{I don't know. You might want to ask Seth or my father about it, though.}
{1135}{TAND_62}{I don't know. You might want to ask Seth or my father about it, though.}
{1137}{TAND_55}{I don't know, but the guy who told me about it was really scared of it. He said that the undead walked the streets!}
{1138}{TAND_55}{I don't know, but the guy who told me about it was really scared of it. He said that the undead walked the streets!}
{1139}{TAND_53}{Junktown's a small city to the southwest. It's supposed to have pretty good trading, but my father won't even look into it. He says we need to stay 'protected'. Yeah, right. Caged is more like it.}
{1140}{TAND_52}{I heard a tale from a traveler up from the south. He said the Deathclaw was a creature that killed people at night. He said no one can catch it, because it can disappear like smoke. Not that I believe it, of course.}
{1141}{TAND_52}{I heard a tale from a traveler up from the south. He said the Deathclaw was a creature that killed people at night. He said no one can catch it, because it can disappear like smoke. Not that I believe it, of course.}
{1142}{TAND_49}{Pretty bad bunch or so I've heard. My father knows more about them. He never tells me much about the outside world.}
