{100}{}{Voici un ordinateur très perfectionné de la Confrérie.}
{101}{}{Tu n'as pas accès à ce terminal.}
{102}{}{La leçon se termine dans six heures. La fatigue te tiraille.}
{103}{}{Tu as déjà ingurgité tout ce que tu pouvais.}
{200}{}{Voici un ordinateur. Il semble pourvu de pièces en chair humaine.}
{201}{}{Tu joues un moment avec l'ordinateur mais tu ne parviens pas à contourner le système de sécurité.}
{202}{}{Cet ordinateur fonctionne parfaitement.}
{203}{}{Tu gagnes }
{204}{}{ experience for hacking into the computer!}
{205}{}{points d'expérience pour avoir piraté cet ordinateur.}
{206}{}{Tu gagnes }
{207}{}{ experience for hacking into the computer!}
{208}{}{Tu gagnes }
{209}{}{ experience for your detective work}
{210}{}{, but ultimately you don't find any new intel while searching this terminal.}
{211}{}{You've learned all you can from the system.}
{300}{}{This computer is functioning perfectly.}
