{100}{}{Ves: al Ayudante del Sheriff Fry.}
{101}{}{Hola, amiga. Ayudante Tony Fry a tu servicio.}
{102}{}{¿Qué lugar es éste?}
{103}{}{Quítate de mi camino o tendré que mandarte a tomar viento.}
{104}{}{Yo no lo hice.}
{105}{}{Me ha encantado conocerte. Adiós.}
{106}{}{Wug.}
{107}{}{¡Ack!}
{108}{}{Oh, ¡una recién llegada! ¡Bienvenido al Eje! Pensé que eras de las caravanas. ¿Viniste con ellos?}
{109}{}{Sí.}
{110}{}{No.}
{111}{}{No me sorprende. La mayoría de los nuevos miembros de nuestra ciudad vienen con las caravanas, a pesar de las caravanas desaparecidas. Es una bonita ciudad, pero ten cuidado con tus amistades. La gente como Decker y sus seguidores puede traerte problemas.}
{112}{}{¿Quién es Decker?}
{113}{}{¿Caravanas desaparecidas?}
{114}{}{Vale, gracias.}
{115}{}{Estoy sorprendido. Las cosas están chungas ahí, especialmente por lo de las caravanas desaparecidas. Pero ahora estás a salvo. Limítate a apartarte del Halcón Maltés. Son una panda de camorristas. Decker y su panda.}
{116}{}{¿Quién es Decker?}
{117}{}{¿Caravanas desaparecidas?}
{118}{}{Sí, bueno, estoy bastante nervioso.}
{119}{}{Creo que sí. Bueno, ¿no tenías otra pregunta?}
{120}{}{¿Quién es Decker?}
{121}{}{¿Qué es eso de que han desaparecido caravanas?}
{122}{}{Eso es todo, gracias.}
