{100}{}{Paladín}
{101}{}{No deberías estar aquí, Iniciada.}
{102}{}{¿Qué estás haciendo aquí?}
{103}{}{La Sala de Guardias es para los guardias. Tú no eres un guardia. Estás en la Sala de Guardias. Así que FUERA.}
{104}{}{Por favor, vete. No deberías estar aquí.}
{105}{}{Ey, no Iniciados.}
{106}{}{Esta no es la biblioteca, chico. Si quieres investigar, por favor, ve a la biblioteca.}
{107}{}{Esta no es la biblioteca, chica. Si quieres investigar, por favor, ve a la biblioteca.}
