{100}{}{Paladín}
{101}{}{¡Mantente firme, Iniciada!}
{102}{}{Parece que va bien. Continúas haciendo un buen trabajo.}
{103}{}{Hola, Iniciada, todo está seguro.}
{104}{}{Hola, Hermano }
{105}{}{.}
{106}{}{Lo siento, no puedo hablar con nadie. Ya sabes como es.}
{107}{}{Si tienes preguntas, deberías hablar con Talus o con Maxson.}
{108}{}{Vree está en la biblioteca durante el día si tienes alguna cuestión técnica.}
{109}{}{Rhombus es mi ídolo.}
{110}{}{Ojalá estuviera entrenando ahora. Los deberes de un guardia son una pérdida de tiempo.}
{111}{}{Vree es mi ídolo.}
{112}{}{¡Marco!}
{113}{}{¡Polo!}
