{100}{}{Estás viendo a un guardia Paladín.}
{101}{}{Pssst, ¿hay algo bueno por aquí?}
{102}{}{Lo siento, estoy de guardia. No puedo hablar ahora.}
{103}{}{Hace un día precioso. Espero que hoy no nos ataquen.}
{104}{}{Algunos de los comerciantes de las caravanas son un poco raros.}
{105}{}{Buenos días.}
{106}{}{Hola, tienes buen aspecto.}
{107}{}{Saludos, Iniciada.}
{108}{}{Si tienes alguna pregunta sobre nuestra orden, debes hablar con Cabbot, ahí junto a la puerta.}
{109}{}{Cabbot es la persona con la que quieres hablar; es ese joven que está junto a la puerta.}
{110}{}{Pssst, ¿hay algo bueno por aquí?}
{111}{}{Si estás aquí para negociar, estás hablando con la persona menos indicada.}
{112}{}{¿Qué?}
{113}{}{No me molestes, gusano.}
{114}{}{¿Acaso parece que me interesa lo que puedas ofrecerme?}
{115}{}{Uuf. Vaya carácter.}
{116}{}{Iniciada, deberías saber que no se nos puede molestar cuando estamos de guardia.}
{117}{}{Si tienes alguna pregunta acerca de la Orden, debes hablar con Cabbot, junto a la puerta.}
{118}{}{Iniciada, ¿no deberías hacer algo útil?}
{119}{}{Creo que no deberías estar aquí, forastera.}
