{0}{}{FU}
{1}{}{PE}
{2}{}{RE}
{3}{}{CA}
{4}{}{IN}
{5}{}{AG}
{6}{}{SU}
{7}{}{Puntos de Salud}
{8}{}{Clase de Armadura}
{9}{}{  Normal}
{10}{}{  Láser}
{11}{}{  Fuego}
{12}{}{  Plasma}
{13}{}{  Explosión}
{14}{}{[no item]}
{15}{}{Daño:}
{16}{}{Rng:}
{17}{}{}
{18}{}{(not worn)}
{19}{}{Need more Action Points to access your inventory.}
{20}{}{Peso:}
{21}{}{MOVER OBJETOS}
{22}{}{TODO}
{23}{}{FIJAR TEMPORIZADOR}
{24}{}{Daño desarmado:}
{25}{}{No puedes recoger eso. Llevas el máximo peso soportado.}
{26}{}{No hay espacio para ese objeto.}
{27}{}{Vale, es un buen trato.}
{28}{}{No, tu oferta no es lo suficientemente buena.}
{29}{}{You earn %d experience for successful use of your Steal skill!}
{30}{}{Peso:}
