{0}{}{DESERT1.MAP}
{1}{}{DESERT2.MAP}
{2}{}{DESERT3.MAP}
{3}{}{HALLDED.MAP}
{4}{}{HOTEL.MAP}
{5}{}{WATRSHD.MAP}
{6}{}{VAULT13.MAP}
{7}{}{VAULTENT.MAP}
{8}{}{VAULTBUR.MAP}
{9}{}{VAULTNEC.MAP}
{10}{}{JUNKENT.MAP}
{11}{}{JUNKCSNO.MAP}
{12}{}{JUNKKILL.MAP}
{13}{}{BROHDENT.MAP}
{14}{}{BROHD12.MAP}
{15}{}{BROHD34.MAP}
{16}{}{CAVES.MAP}
{17}{}{CHILDRN1.MAP}
{18}{}{CHILDRN2.MAP}
{19}{}{CITY1.MAP}
{20}{}{COAST1.MAP}
{21}{}{COAST2.MAP}
{22}{}{COLATRUK.MAP}
{23}{}{FSAUSER.MAP}
{24}{}{RAIDERS.MAP}
{25}{}{SHADYE.MAP}
{26}{}{SHADYW.MAP}
{27}{}{GLOWENT.MAP}
{28}{}{LAADYTUM.MAP}
{29}{}{LAFOLLWR.MAP}
{30}{}{MBENT.MAP}
{31}{}{MBSTRG12.MAP}
{32}{}{MBVATS12.MAP}
{33}{}{MSTRLR12.MAP}
{34}{}{MSTRLR34.MAP}
{35}{}{V13ENT.MAP}
{36}{}{HUBENT.MAP}
{37}{}{DETHCLAW.MAP}
{38}{}{HUBDWNTN.MAP}
{39}{}{HUBHEIGT.MAP}
{40}{}{HUBOLDTN.MAP}
{41}{}{HUBWATER.MAP}
{42}{}{GLOW1.MAP}
{43}{}{GLOW2.MAP}
{44}{}{LABLADES.MAP}
{45}{}{LARIPPER.MAP}
{46}{}{LAGUNRUN.MAP}
{47}{}{CHILDEAD.MAP}
{48}{}{MBDEAD.MAP}
{49}{}{MOUNTN1.MAP}
{50}{}{MOUNTN2.MAP}
{51}{}{FOOT.MAP}
{52}{}{TARDIS.MAP}
{53}{}{TALKCOW.MAP}
{54}{}{USEDCAR.MAP}
{55}{}{BRODEAD.MAP}
{56}{}{DESCRVN1.MAP}
{57}{}{DESCRVN2.MAP}
{58}{}{MNTCRVN1.MAP}
{59}{}{MNTCRVN2.MAP}
{60}{}{VIPERS.MAP}
{61}{}{DESCRVN3.MAP}
{62}{}{MNTCRVN3.MAP}
{63}{}{DESCRVN4.MAP}
{64}{}{MNTCRVN4.MAP}
{65}{}{HUBMIS0.MAP}
{66}{}{HUBMIS1.MAP}
{100}{}{Desierto}
{101}{}{Desierto}
{102}{}{Desierto}
{103}{}{Necrópolis}
{104}{}{Necrópolis}
{105}{}{Necrópolis}
{106}{}{Refugio 13}
{107}{}{Refugio 15}
{108}{}{Refugio 15}
{109}{}{Refugio 12}
{110}{}{Ciudad Vertedero}
{111}{}{Ciudad Vertedero}
{112}{}{Ciudad Vertedero}
{113}{}{Hermandad del Acero}
{114}{}{Hermandad del Acero}
{115}{}{Hermandad del Acero}
{116}{}{Arenas Sombrías}
{117}{}{Catedral}
{118}{}{Catedral}
{119}{}{Ciudad}
{120}{}{Costa}
{121}{}{Costa}
{122}{}{Desierto}
{123}{}{Desierto}
{124}{}{Los Khans}
{125}{}{Arenas Sombrías}
{126}{}{Arenas Sombrías}
{127}{}{Ardor}
{128}{}{Cementerio de LA}
{129}{}{Cementerio de LA}
{130}{}{Base Militar}
{131}{}{Base Militar}
{132}{}{Base Militar}
{133}{}{SIN USAR}
{134}{}{SIN USAR}
{135}{}{Refugio 13}
{136}{}{Eje}
{137}{}{Eje}
{138}{}{Eje}
{139}{}{Eje}
{140}{}{Eje}
{141}{}{Eje}
{142}{}{Ardor}
{143}{}{Ardor}
{144}{}{Cementerio de LA}
{145}{}{Cementerio de LA}
{146}{}{Cementerio de LA}
{147}{}{Ruinas}
{148}{}{Base Militar}
{149}{}{Montañas}
{150}{}{Montañas}
{151}{}{Desierto}
{152}{}{Desierto}
{153}{}{Desierto}
{154}{}{Desierto}
{155}{}{Hermandad del Acero}
{156}{}{Desierto}
{157}{}{Desierto}
{158}{}{Montañas}
{159}{}{Montañas}
{160}{}{Campamento Víbora}
{161}{}{Desierto}
{162}{}{Montañas}
{163}{}{Desierto}
{164}{}{Montañas}
{165}{}{Eje}
{166}{}{Eje}
{200}{}{Wasteland}
{201}{}{Wasteland}
{202}{}{Wasteland}
{203}{}{Wasteland}
{204}{}{Wasteland}
{205}{}{Wasteland}
{206}{}{Wasteland}
{207}{}{Wasteland}
{208}{}{Wasteland}
{209}{}{Alcantarillas bajo Hall}
{210}{}{Sala de los Difuntos}
{211}{}{Alcantarillas bajo Hall}
{212}{}{Sewers under Hotel}
{213}{}{Hotel de la perdición}
{214}{}{Sewers under Hotel}
{215}{}{Sewers under Watershed}
{216}{}{El almacén de agua}
{217}{}{Sewers under Watershed}
{218}{}{Entrance, Medical}
{219}{}{Aposentos}
{220}{}{Biblioteca, Suministros, Comando}
{221}{}{Old Shack}
{222}{}{Cavern Entrance}
{223}{}{Cavern Entrance}
{224}{}{Aposentos}
{225}{}{Biblioteca, Suministros, Comando}
{226}{}{Biblioteca, Suministros, Comando}
{227}{}{Level 1 (Sewer Entrance)}
{228}{}{Level 2 (Living Quarters)}
{229}{}{Level 3 (Command Center)}
{230}{}{Entrance, Hospital}
{231}{}{Doc Morbid's Lab}
{232}{}{Doc Morbid's Lab}
{233}{}{Casino, Bar}
{234}{}{Casino, Bar}
{235}{}{Casino, Bar}
{236}{}{General Store, Hotel}
{237}{}{General Store, Hotel}
{238}{}{General Store, Hotel}
{239}{}{Entrada}
{240}{}{Entrada}
{241}{}{Entrada}
{242}{}{Nivel 1}
{243}{}{Nivel 2}
{244}{}{Nivel 2}
{245}{}{Nivel 3}
{246}{}{Nivel 4}
{247}{}{Nivel 4}
{248}{}{Radscorpion Cave}
{249}{}{Radscorpion Cave}
{250}{}{Radscorpion Cave}
{251}{}{Entrada}
{252}{}{Torre Nivel 1}
{253}{}{}
{254}{}{Torre Nivel 2}
{255}{}{Torre Nivel 3}
{256}{}{Torre Nivel 4}
{257}{}{Ruinas}
{258}{}{Ruinas}
{259}{}{Ruinas}
{260}{}{Shoreline}
{261}{}{Shoreline}
{262}{}{Shoreline}
{263}{}{Shoreline}
{264}{}{Shoreline}
{265}{}{Shoreline}
{266}{}{Camión volcado}
{267}{}{Camión volcado}
{268}{}{Camión volcado}
{269}{}{Nave espacial}
{270}{}{Nave espacial}
{271}{}{Nave espacial}
{272}{}{Campo base}
{273}{}{Campo base}
{274}{}{Campo base}
{275}{}{Garden, Brahma Pen}
{276}{}{Garden, Brahma Pen}
{277}{}{Garden, Brahma Pen}
{278}{}{Entrance, Town Hall}
{279}{}{Entrance, Town Hall}
{280}{}{Entrance, Town Hall}
{281}{}{Entrada}
{282}{}{Entrada}
{283}{}{Entrada}
{284}{}{Adytum}
{285}{}{Subterráneo}
{286}{}{}
{287}{}{Biblioteca}
{288}{}{Subterráneo}
{289}{}{}
{290}{}{Entrada}
{291}{}{Entrada}
{292}{}{Entrada}
{293}{}{Fortaleza Nivel 1}
{294}{}{Fortaleza Nivel 2}
{295}{}{}
{296}{}{Tanques Nivel 1}
{297}{}{Tanques Nivel 2}
{298}{}{}
{299}{}{Guarida Nivel 1}
{300}{}{Guarida Nivel 2}
{301}{}{}
{302}{}{Guarida Nivel 3}
{303}{}{Guarida Nivel 4}
{304}{}{}
{305}{}{Caverna, Puerta del Refugio}
{306}{}{Caverna, Puerta del Refugio}
{307}{}{Caverna, Puerta del Refugio}
{308}{}{Entrance, Caravaners}
{309}{}{Entrance, Caravaners}
{310}{}{Entrance, Caravaners}
{311}{}{Deathclaw Lair}
{312}{}{Deathclaw Lair}
{313}{}{Deathclaw Lair}
{314}{}{Downtown, Market, Casino}
{315}{}{Escondrijo de Decker}
{316}{}{Escondrijo de Decker}
{317}{}{Heights, Hightower}
{318}{}{Heights, Hightower}
{319}{}{Heights, Hightower}
{320}{}{Ciudad Antigua}
{321}{}{Gremio de Ladrones}
{322}{}{Gremio de Ladrones}
{323}{}{Water Merchants, Church}
{324}{}{Water Merchants, Church}
{325}{}{Water Merchants, Church}
{326}{}{Nivel 1}
{327}{}{Nivel 2}
{328}{}{Nivel 3}
{329}{}{Nivel 4}
{330}{}{Nivel 5}
{331}{}{Nivel 6}
{332}{}{Centro de la ciudad}
{333}{}{Centro de la ciudad}
{334}{}{Centro de la ciudad}
{335}{}{Almacén}
{336}{}{Subterráneo}
{337}{}{}
{338}{}{Fortaleza}
{339}{}{Fortaleza}
{340}{}{Fortaleza}
{341}{}{Cráter}
{342}{}{Cráter}
{343}{}{Cráter}
{344}{}{Ruinas}
{345}{}{Ruinas}
{346}{}{Ruinas}
{347}{}{Pass}
{348}{}{Pass}
{349}{}{Pass}
{350}{}{Pass}
{351}{}{Pass}
{352}{}{Pass}
{353}{}{Huella}
{354}{}{Huella}
{355}{}{Huella}
{356}{}{Cabina de policía}
{357}{}{Cabina de policía}
{358}{}{Cabina de policía}
{359}{}{Vacas parlantes}
{360}{}{Vacas parlantes}
{361}{}{Vacas parlantes}
{362}{}{Venta de coches usados}
{363}{}{Venta de coches usados}
{364}{}{Venta de coches usados}
{365}{}{Ruinas}
{366}{}{Ruinas}
{367}{}{Ruinas}
{368}{}{Caravan Encounter}
{369}{}{Caravan Encounter}
{370}{}{Caravan Encounter}
{371}{}{Caravan Encounter}
{372}{}{Caravan Encounter}
{373}{}{Caravan Encounter}
{374}{}{Caravan Encounter}
{375}{}{Caravan Encounter}
{376}{}{Caravan Encounter}
{377}{}{Caravan Encounter}
{378}{}{Caravan Encounter}
{379}{}{Caravan Encounter}
{380}{}{Campamento de los Víboras}
{381}{}{Campamento de los Víboras}
{382}{}{Campamento de los Víboras}
{383}{}{Caravan Encounter}
{384}{}{Caravan Encounter}
{385}{}{Caravan Encounter}
{386}{}{Caravan Encounter}
{387}{}{Caravan Encounter}
{388}{}{Caravan Encounter}
{389}{}{Caravan Encounter}
{390}{}{Caravan Encounter}
{391}{}{Caravan Encounter}
{392}{}{Caravan Encounter}
{393}{}{Caravan Encounter}
{394}{}{Caravan Encounter}
{395}{}{Granja de Irwin}
{396}{}{Granja de Irwin}
{397}{}{Granja de Irwin}
{398}{}{Granja de Irwin}
{399}{}{Granja de Irwin}
{400}{}{Granja de Irwin}
{500}{}{Refugio 13}
{501}{}{Refugio 15}
{502}{}{Arenas Sombrías}
{503}{}{Ciudad Vertedero}
{504}{}{Los Khans}
{505}{}{Necrópolis}
{506}{}{Eje}
{507}{}{Hermandad del Acero}
{508}{}{Base Militar Mariposa}
{509}{}{Ardor}
{510}{}{Cementerio de LA}
{511}{}{Niños de la Catedral}
{1000}{}{ERROR: ¡No hay suficiente espacio para guardar el mapa!}
