{100}{}{Barril metálico con fuego}
{101}{}{El barril contiene papel y otra basura ardiendo.}
{200}{}{Puerta de madera}
{201}{}{Una puerta, hecha de madera.}
{300}{}{Mesa de madera}
{301}{}{Una mesa, hecha de madera.}
{400}{}{Mesa de madera}
{401}{}{Una mesa, hecha de madera.}
{500}{}{Barril metálico}
{501}{}{Un viejo barril, hecho de acero.}
{600}{}{Barril metálico}
{601}{}{Un viejo barril, hecho de acero.}
{700}{}{una pila de neumáticos}
{701}{}{Un montón de viejas llantas de caucho. Están vulcanizadas y endurecidas, probablemente por el calor.}
{800}{}{Puerta de seguridad}
{801}{}{Esta puerta parece muy segura. Proporciona protección contra elementos del mundo exterior y criaturas peligrosas.}
{900}{}{Computadora}
{901}{}{Un terminal de ordenador del Refugio, conectado al ordenador principal del Refugio.}
{1000}{}{Columna}
{1001}{}{Una columna de soporte, proporciona alivio estructural a todo el complejo.}
{1100}{}{Computadora}
{1101}{}{Un terminal de ordenador del Refugio, conectado al ordenador principal del Refugio.}
{1200}{}{Computadora}
{1201}{}{Un terminal de ordenador del Refugio, conectado al ordenador principal del Refugio.}
{1300}{}{Monitor}
{1301}{}{Un monitor de pantalla verde mostrando diversos bits de datos. Algunos bytes aparecen de vez en cuando.}
{1400}{}{Monitor}
{1401}{}{Un monitor de pantalla verde mostrando diversos bits de datos.}
{1500}{}{Holo-generador}
{1501}{}{Un reproductor de cintas THT de entretenimiento a gran escala. No se ha rodado ninguna película nueva en 80 años.}
{1600}{}{Pantallas}
{1601}{}{Una serie de tres monitores, mostrando diversos bits de datos.}
{1700}{}{Pantallas}
{1701}{}{Un conjunto de tres monitores, mostrando diversos bits de datos sobre los alrededores del Refugio.}
{1800}{}{Puerta}
{1801}{}{Después de un examen riguroso, sigue siendo una puerta.}
{1900}{}{Puerta}
{1901}{}{Después de un examen riguroso, sigue siendo una puerta.}
{2000}{}{Ventilación}
{2001}{}{Una válvula de aire que abastece en aire procesado y purificado al complejo del Refugio.}
{2100}{}{Ventilación}
{2101}{}{Una válvula de aire que abastece en aire procesado y purificado al complejo del Refugio.}
{2200}{}{Puerta del Refugio 13}
{2201}{}{Una puerta pesada, construida para sobrevivir a todo tipo de daño y traumas.}
{2300}{}{Puerta del Refugio 13}
{2301}{}{Una puerta pesada, construida para sobrevivir a todo tipo de daño y traumas.}
{2400}{}{Pedestal}
{2401}{}{Estructura hidráulica, diseñada para proporcionar líneas de apoyo, energía y comunicación a la plataforma del Supervisor.}
{2500}{}{Monitor}
{2501}{}{Cuando has visto un monitor, los has visto a todos.}
{2600}{}{Monitor}
{2601}{}{Un monitor de computadora, mostrando diversos bits de datos.}
{2700}{}{Enrejado}
{2701}{}{Una reja de tecnología estándar que actúa como base del pedestal del Supervisor.}
{2800}{}{Tuberías}
{2801}{}{Algunas tuberías. Después de un examen más detenido, siguen siendo tuberías.}
{2900}{}{Ventilación}
{2901}{}{Un sistema de ventilación estándar Vault-Tec.}
{3000}{}{Columna}
{3001}{}{Un sistema de columnas de soporte estándar Vault-Tec.}
{3100}{}{Columna}
{3101}{}{Un sistema de columnas de soporte estándar Vault-Tec.}
{3200}{}{Ventilación}
{3201}{}{Un sistema de ventilación estándar Vault-Tec.}
{3300}{}{Ventilación}
{3301}{}{Un sistema de ventilación estándar Vault-Tec.}
{3400}{}{Cama}
{3401}{}{Una cama, parece muy cómoda si la comparas con los lugares donde has dormido últimamente.}
{3500}{}{Cama}
{3501}{}{Una cama común. Parece cómoda.}
{3600}{}{Cama}
{3601}{}{Una cama común. Parece cómoda.}
{3700}{}{Cama}
{3701}{}{Una cama común. Parece cómoda.}
{3800}{}{el ascensor del Refugio}
{3801}{}{Es un ascensor. Sube y baja niveles en la estructura del Refugio.}
{3900}{}{Silla}
{3901}{}{Es una silla. Por desgracia no tienes tiempo para sentarte y relajarte.}
{4000}{}{Silla}
{4001}{}{Es una silla. Por desgracia no tienes tiempo para sentarte y relajarte.}
{4100}{}{Silla}
{4101}{}{Es una silla. Por desgracia no tienes tiempo para sentarte y relajarte.}
{4200}{}{Silla}
{4201}{}{Es una silla. Por desgracia no tienes tiempo para sentarte y relajarte.}
{4300}{}{Monitor}
{4301}{}{Un monitor de computadora, mostrando diversos bits de datos.}
{4400}{}{Monitor}
{4401}{}{Un monitor de computadora, mostrando diversos bits de datos.}
{4500}{}{Monitor}
{4501}{}{Un monitor de computadora, mostrando diversos bits de datos.}
{4600}{}{Monitor}
{4601}{}{Un monitor de computadora, mostrando diversos bits de datos.}
{4700}{}{Monitor}
{4701}{}{Un monitor de computadora, mostrando diversos bits de datos.}
{4800}{}{Monitor}
{4801}{}{Un monitor de computadora, mostrando diversos bits de datos.}
{4900}{}{Marcador de zona de salida del mapa}
{4901}{}{Marcador de zona de salida del mapa}
{5000}{}{Unidad de Tratamiento de Aire}
{5001}{}{Una UPA limpia el aire contaminado y lo convierte en aire utilizable para la estructura. Ésta en concreto está rota.}
{5100}{}{Silla}
{5101}{}{Es una silla. Por desgracia no tienes tiempo para sentarte y relajarte.}
{5200}{}{Silla}
{5201}{}{Es una silla. Por desgracia no tienes tiempo para sentarte y relajarte.}
{5300}{}{Silla}
{5301}{}{Es una silla. Por desgracia no tienes tiempo para sentarte y relajarte.}
{5400}{}{Silla}
{5401}{}{Es una silla. Por desgracia no tienes tiempo para sentarte y relajarte.}
{5500}{}{Videopantalla}
{5501}{}{Esta unidad de videopantalla tiene diversos monitores de computadora y otras pantallas. Parece estar ejecutando muchas, muchas tareas.}
{5600}{}{Videopantalla}
{5601}{}{Esta unidad de videopantalla tiene diversos monitores de computadora y otras pantallas. Parece estar ejecutando muchas, muchas tareas.}
{5700}{}{Silla}
{5701}{}{Es una silla. Parece muy cómoda.}
{5800}{}{Silla}
{5801}{}{Es una silla. Parece muy cómoda.}
{5900}{}{Silla}
{5901}{}{Es una silla. Parece muy cómoda.}
{6000}{}{Silla}
{6001}{}{Es una silla. Parece muy cómoda.}
{6100}{}{una mesa}
{6101}{}{Es una mesa. Antes de que las mesas existieran, la gente tenía que poner sus cosas en el suelo.}
{6200}{}{una mesa}
{6201}{}{Definitivamente es una mesa.}
{6300}{}{Planta rodadora}
{6301}{}{Es una planta rodadora. Por supuesto, nunca has visto una planta rodadora en vivo antes. Deberías echarle un buen vistazo.}
{6400}{}{Cactus}
{6401}{}{No ves nada especial en este cactus.}
{6500}{}{Cactus}
{6501}{}{No ves nada importante en este cactus.}
{6600}{}{Árbol}
{6601}{}{Un árbol muerto. Nada crece bien aquí.}
{6700}{}{Un Hexágono Secreto de Bloqueo.}
{6701}{}{Si estás viendo esto, maldice al diseñador técnico.}
{6800}{}{las escaleras del Refugio}
{6801}{}{Una serie de escaleras.}
{6900}{}{Estalagmita}
{6901}{}{Una extensión natural del suelo rocoso.}
{7000}{}{Estalagmita}
{7001}{}{Una extensión natural del suelo rocoso.}
{7100}{}{Mancha de sangre}
{7101}{}{No hay nada fuera de lo común en esta mancha de sangre. Excepto, por supuesto, que alguien o algo murió aquí.}
{7200}{}{Pilar de roca}
{7201}{}{Este grueso pilar de roca se extiende del suelo al techo.}
{7300}{}{Pilar de roca}
{7301}{}{Este grueso pilar de roca se extiende del suelo al techo.}
{7400}{}{Rocas}
{7401}{}{Estudias las rocas por un momento, pero no se mueven.}
{7500}{}{Rocas}
{7501}{}{Mantienes un ojo sobre estas rocas, por si acaso se mueven y te atacan.}
{7600}{}{el suelo de un coche}
{7601}{}{ELIMINADO}
{7700}{}{el techo de un coche}
{7701}{}{ELIMINADO}
{7800}{}{Rocas}
{7801}{}{Una gran montón de rocas. Parecen autóctonas de esta región.}
{7900}{}{Rocas}
{7901}{}{Un pequeño montón de rocas.}
{8000}{}{Rocas}
{8001}{}{Un pequeño montón de rocas.}
{8100}{}{Rocas}
{8101}{}{Un gran montón de rocas.}
{8200}{}{unos huesos}
{8201}{}{Un gran montón de huesos descolorados de animal. Al menos, crees que son huesos de animal...}
{8300}{}{unos huesos}
{8301}{}{Un gran montón de huesos descolorados de animal. Al menos, crees que son huesos de animal...}
{8400}{}{unos huesos}
{8401}{}{Una gran pila de huesos descolorados de animal. No puedes determinar la especie del animal muerto.}
{8500}{}{unos huesos}
{8501}{}{Crees que pueden ser huesos de un Canguro Cornudo, pero no puedes estar seguro. Están muy deteriorados como para una inspección definitiva.}
{8600}{}{unos huesos}
{8601}{}{Ves los huesos de una gran vaca de dos cabezas.}
{8700}{}{Puerta}
{8701}{}{Una entrada de madera. Se abre, y se cierra, y se abre, se cierra, y...}
{8800}{}{un cofre de hielo metalizado}
{8801}{}{ELIMINADO}
{8900}{}{un cofre de hielo metalizado}
{8901}{}{ELIMINADO}
{9000}{}{Rocas}
{9001}{}{Un gran montón de rocas. Parece peligroso sentarse ahí.}
{9100}{}{Rocas}
{9101}{}{Un gran montón de rocas. Si miras más de cerca, puedes ver las caras de pequeños ancianos en los laterales de las piedras.}
{9200}{}{Rocas}
{9201}{}{¡Rocas, rocas, rocas! ¡Mires donde mires, rocas!}
{9300}{}{Rocas}
{9301}{}{Un pequeño montón de rocas.}
{9400}{}{Barra}
{9401}{}{Esta versión moderna de alambique podría llamarse microdestilería.}
{9500}{}{Silla}
{9501}{}{Un viejo sillón podrido fabricado a partir de un antiguo asiento de coche.}
{9600}{}{Silla}
{9601}{}{Una vieja silla maloliente que era el asiento de un coche. Los muelles han perdido su elasticidad.}
{9700}{}{Silla}
{9701}{}{Un podrido y apestoso sillón viejo posado sobre ladrillos para sostenerlo. Parece muy incómodo.}
{9800}{}{Sofá}
{9801}{}{Un podrido y apestoso sillón viejo posado sobre ladrillos para sostenerlo. Parece muy incómodo.}
{9900}{}{Sofá}
{9901}{}{Un artefacto para sentarse muy incómodo que solía ser un sofá.}
{10000}{}{Sofá}
{10001}{}{Un artefacto para sentarse muy incómodo que solía ser un sofá.}
{10100}{}{Neumático}
{10101}{}{Unas viejas llantas de caucho apoyadas en medio de unas hierbas.}
{10200}{}{Arbusto}
{10201}{}{Algún tipo de hierba del desierto.}
{10300}{}{Arbusto}
{10301}{}{Algún tipo de hierba del desierto.}
{10400}{}{Arbusto}
{10401}{}{Algún tipo de hierba del desierto.}
{10500}{}{Arbusto}
{10501}{}{Algún tipo de hierba del desierto.}
{10600}{}{Vertedero}
{10601}{}{Una oxidada puerta de coche recostada sobre un barril de metal. Una gran cantidad de óxido se está produciendo.}
{10700}{}{Vertedero}
{10701}{}{Un inodoro roto, medio sepultado en la arena. La vida es orinar, luego morir.}
{10800}{}{Hierbas}
{10801}{}{Algún tipo de maleza del desierto. Si estuvo creciendo en el pasado reciente, ya no lo hace.}
{10900}{}{Vertedero}
{10901}{}{Un neumático de coche, sepultado en la arena. Hay algunos trozos de madera amontonados alrededor.}
{11000}{}{Rocas}
{11001}{}{En una inspección más cercana, te parece que en realidad pueden ser trozos de madera petrificada.}
{11100}{}{Basura}
{11101}{}{Un pequeño montón de basura, con hierba muerta adherida a él.}
{11200}{}{Basura}
{11201}{}{Un pequeño montón de basura.}
{11300}{}{Basura}
{11301}{}{Un pequeño montón de basura.}
{11400}{}{Basura}
{11401}{}{Un pequeño montón de basura.}
{11500}{}{Hierbas}
{11501}{}{Un pequeño montón de basura, con hierba seca adherida a él.}
{11600}{}{Vertedero}
{11601}{}{Una pieza retorcida de metal oxidado.}
{11700}{}{Vertedero}
{11701}{}{Algunos trozos rotos de madera.}
{11800}{}{Vertedero}
{11801}{}{Un pequeño montón de chatarra variada.}
{11900}{}{Basura}
{11901}{}{Un pequeño montón de basura.}
{12000}{}{Basura}
{12001}{}{Un pequeño montón de basura.}
{12100}{}{Basura}
{12101}{}{Un pequeño montón de basura.}
{12200}{}{Basura}
{12201}{}{Un pequeño montón de basura.}
{12300}{}{Basura}
{12301}{}{Un pequeño montón de basura.}
{12400}{}{Basura}
{12401}{}{Un pequeño montón de basura.}
{12500}{}{Hierbas}
{12501}{}{Maleza común del desierto.}
{12600}{}{Hierbas}
{12601}{}{Maleza común del desierto.}
{12700}{}{Hierbas}
{12701}{}{Maleza común del desierto.}
{12800}{}{}
{12900}{}{Muro}
{12901}{}{El hedor de moho emana de las húmedas paredes del alcantarillado.}
{13000}{}{Muro}
{13001}{}{El hedor de moho emana de las húmedas paredes del alcantarillado.}
{13100}{}{Muro}
{13101}{}{El hedor de moho emana de las húmedas paredes del alcantarillado.}
{13200}{}{Muro}
{13201}{}{El hedor de moho emana de las húmedas paredes del alcantarillado.}
{13300}{}{Muro}
{13301}{}{El hedor de moho emana de las húmedas paredes del alcantarillado.}
{13400}{}{Muro}
{13401}{}{El hedor de moho emana de las húmedas paredes del alcantarillado.}
{13500}{}{Alcantarilla}
{13501}{}{Alguna clase de fétido y repugnante olor procede de esta alcantarilla. Pasado un rato, ya no huele tan mal.}
{13600}{}{Alcantarilla}
{13601}{}{Apenas puedes distinguir algún movimiento tras la rejilla que cubre esta alcantarilla. Puedes ver ojos rojos mirándote. Ojos de rata.}
{13700}{}{Alcantarilla}
{13701}{}{Se escucha el gorgoteo del agua en esta alcantarilla. Por eso apesta tanto.}
{13800}{}{Alcantarilla}
{13801}{}{Se escucha el gorgoteo del agua más allá de esta alcantarilla. Por eso apesta tanto.}
{13900}{}{Escalera}
{13901}{}{Es una vieja escalera destartalada. Parece que apenas soportará tu peso.}
{14000}{}{Entrada de alcantarilla}
{14001}{}{Parece un acceso al sistema de alcantarillas.}
{14100}{}{Fuente de luz}
{14200}{}{Puerta}
{14201}{}{Parece una puerta de Refugio normal que ha sido averiada, quizás quemada. De todos modos aún funciona.}
{14300}{}{Puerta}
{14301}{}{Parece una puerta de Refugio normal que ha sido averiada, quizás quemada. De todos modos aún funciona.}
{14400}{}{una tapa}
{14401}{}{Una tapa de alcantarilla pesada. Parece estar en buen estado y se ha movido recientemente.}
{14500}{}{Agujero}
{14501}{}{Se ha abierto un gran agujero a través de esta puerta con una explosión.}
{14600}{}{Agujero}
{14601}{}{Se ha abierto un gran agujero a través de esta puerta con una explosión.}
{14700}{}{Cristal blindado}
{14701}{}{Cristal completamente irrompible. Ni siquiera lo intentes.}
{14800}{}{Cristal blindado}
{14801}{}{Cristal completamente irrompible. Ni siquiera lo intentes.}
{14900}{}{Cristal blindado}
{14901}{}{Cristal completamente irrompible. Ni siquiera lo intentes.}
{15000}{}{Cristal blindado}
{15001}{}{Cristal completamente irrompible. Ni siquiera lo intentes.}
{15100}{}{Puerta}
{15101}{}{Esta puerta es una pieza de construcción de alta tecnología. Se abre por dilatación a medida que rotan las tres piezas que la forman.}
{15200}{}{Puerta}
{15201}{}{Esta puerta es una pieza de construcción de alta tecnología. Se abre por dilatación a medida que rotan las tres piezas que la forman.}
{15300}{}{Puerta}
{15301}{}{Esta puerta está adornada con el símbolo de la Hermandad del Acero.}
{15400}{}{Puerta}
{15401}{}{Esta puerta está adornada con el símbolo de la Hermandad del Acero.}
{15500}{}{Ascensor}
{15501}{}{Este es el interior del elevador de la Hermandad. ¡Está absolutamente limpio!}
{15600}{}{Ascensor}
{15601}{}{Este es el interior del elevador de la Hermandad. ¡Está absolutamente limpio!}
{15700}{}{Marca}
{15701}{}{Este es el símbolo de la Hermandad del Acero. Esta marca le dice al Yermo que es su territorio, y que hay que marcharse inmediatamente.}
{15800}{}{Monitor}
{15801}{}{Estás viendo un monitor de ordenador. Está fabricado con tecnología de la Hermandad.}
{15900}{}{Monitor}
{15901}{}{Estás viendo un monitor de ordenador. Está fabricado con tecnología de la Hermandad.}
{16000}{}{Computadora}
{16001}{}{Se trata de un banco de datos de memoria del ordenador. Obviamente tiene tecnología de la Hermandad.}
{16100}{}{Computadora}
{16101}{}{Se trata de un banco de datos de memoria del ordenador. Obviamente tiene tecnología de la Hermandad.}
{16200}{}{Computadora}
{16201}{}{Una computadora de alta tecnología. Usa un moderno dispositivo de almacenamiento de bobina magnética en lugar del anticuado sistema de tarjetas perforadas.}
{16300}{}{Computadora}
{16301}{}{Una computadora de alta tecnología. Usa un moderno dispositivo de almacenamiento de bobina magnética en lugar del anticuado sistema de tarjetas perforadas.}
{16400}{}{Monitor}
{16401}{}{Estás viendo un monitor de ordenador. Está fabricado con tecnología de la Hermandad.}
{16500}{}{Monitor}
{16501}{}{Estás viendo un monitor de ordenador. Está fabricado con tecnología de la Hermandad.}
{16600}{}{Cable}
{16601}{}{Algún tipo de cableado de computadora.}
{16700}{}{Cable}
{16701}{}{Algún tipo de cableado de computadora.}
{16800}{}{Cable}
{16801}{}{Algún tipo de cableado de computadora.}
{16900}{}{Columna}
{16901}{}{Una columna de soporte.}
{17000}{}{Columna}
{17001}{}{Una columna de soporte.}
{17100}{}{Computadora de acceso}
{17101}{}{This computer controls the large Vault blast door. You have to enter a specific access code for the computer to work.}
{17200}{}{Cartel de Casino}
{17201}{}{Parece publicidad del Casino de Gizmo.}
{17300}{}{Vault 13 Blast Door}
{17301}{}{Esta gran puerta es la conexión entre el Refugio y el mundo exterior. Es demasiado grande para abrirse manualmente. Utiliza el terminal de entrada.}
{17400}{}{Vault 13 Blast Door}
{17401}{}{Esta gran puerta es la conexión entre el Refugio y el mundo exterior.}
{17500}{}{Cartel de Casino}
{17501}{}{Esta parte del cartel contiene un motor eléctrico que hace girar lentamente la sección del neón.}
{17600}{}{Flecha abajo}
{17601}{}{Tus agudas aptitudes para la percepción y la deducción concluyen que este ascensor está bajando.}
{17700}{}{Flecha arriba}
{17701}{}{Tus agudas aptitudes para la percepción y la deducción concluyen que este ascensor está subiendo.}
{17800}{}{un cajón}
{17801}{}{Un contenedor de almacenaje y transporte de aspecto caro, probablemente hecho a partir de un compuesto de alta tecnología, con el emblema de la Hermandad del Acero estampado en él.}
{17900}{}{un cajón}
{17901}{}{Un contenedor de almacenaje y transporte de aspecto caro, probablemente hecho a partir de un compuesto de alta tecnología, con el emblema de la Hermandad del Acero estampado en él.}
{18000}{}{un cajón}
{18001}{}{Un contenedor de almacenaje y transporte de aspecto caro, probablemente hecho a partir de un compuesto de alta tecnología, con el emblema de la Hermandad del Acero estampado en él.}
{18100}{}{Parte superior de elevador}
{18101}{}{Estás viendo una parte de un elevador.}
{18200}{}{Consola de Computadora}
{18201}{}{Es un terminal mudo, conectado a un gran ordenador mediante un cable. Es tecnología de la Hermandad.}
{18300}{}{Consola de Computadora}
{18301}{}{Es un terminal mudo, conectado a un gran ordenador mediante un cable. Es tecnología de la Hermandad.}
{18400}{}{Emblema}
{18401}{}{El símbolo de la Hermandad. La rueda representa su conocimiento en ingeniería, la espada es su voluntad de defenderse a sí mismos, y las alas son la esperanza de fortalecimiento.}
{18500}{}{Emblema}
{18501}{}{El símbolo de la Hermandad. La rueda representa su conocimiento en ingeniería, la espada es su voluntad de defenderse a sí mismos, y las alas son la esperanza de fortalecimiento.}
{18600}{}{Cartel de nivel 'uno'}
{18601}{}{Crees que esto puede significar que estás en el primer nivel de la Hermandad.}
{18700}{}{Cartel de nivel 'dos'}
{18701}{}{Estás en el segundo nivel de la Hermandad.}
{18800}{}{Cartel de nivel 'tres'}
{18801}{}{Esto debe significar que estás en el tercer nivel de la Hermandad.}
{18900}{}{Cartel de nivel 'cuatro'}
{18901}{}{Debes de estar en el nivel cuatro de la Hermandad.}
{19000}{}{Litera}
{19001}{}{Una litera de estilo militar. Debe de ser muy incómoda. Las sábanas están tan tensas que podrías hacer rebotar una moneda sobre ellas.}
{19100}{}{Litera}
{19101}{}{Una litera de estilo militar. Debe de ser muy incómoda. Las sábanas están tan tensas que podrías hacer rebotar una moneda sobre ellas.}
{19200}{}{Litera}
{19201}{}{Una litera de estilo militar. Debe de ser muy incómoda. Las sábanas están tan tensas que podrías hacer rebotar una moneda sobre ellas.}
{19300}{}{un cajón}
{19301}{}{Un contenedor de almacenaje y transporte de aspecto caro, probablemente hecho a partir de un compuesto de alta tecnología, con el emblema de la Hermandad del Acero estampado en él.}
{19400}{}{Máquina de Nuka-Cola}
{19401}{}{Está rota. Qué decepción.}
{19500}{}{Muro}
{19600}{}{un escotillón}
{19601}{}{Parece un buen escotillón.}
{19700}{}{Alcantarilla}
{19701}{}{La escalera de esta alcantarilla conduce a la oscuridad de abajo. Ohhh, espeluznante.}
{19800}{}{Altar}
{19801}{}{Esto es un altar.}
{19900}{}{Plataforma del predicador}
{19901}{}{Uno se coloca detrás de esto para hablar. Parece un lugar pequeño como para dar un discurso preparado.}
{20000}{}{Banco de iglesia}
{20001}{}{Se ve exactamente como lo esperarías. No hay nada especial en este banco.}
{20100}{}{Letrero}
{20101}{}{El letrero de este poste parece un poco oxidado.}
{20200}{}{Letrero}
{20201}{}{El letrero de este poste parece un poco oxidado.}
{20300}{}{Letrero}
{20301}{}{El letrero de este poste parece un poco oxidado.}
{20400}{}{Letrero}
{20401}{}{El letrero de este poste parece un poco oxidado.}
{20500}{}{Letrero}
{20501}{}{El letrero de este poste parece un poco oxidado.}
{20600}{}{Colchón viejo}
{20601}{}{Un viejo colchón maltratado. Te parece ver algún tipo de insecto que lo infesta.}
{20700}{}{Colchón viejo}
{20701}{}{Incluso si durmieras solo en esta cosa, no estarías durmiendo solo.}
{20800}{}{Cama}
{20801}{}{Una improvisada cama. El material fue recolectado de alguna otra fuente.}
{20900}{}{Cama}
{20901}{}{Una improvisada cama. El material fue recolectado de alguna otra fuente.}
{21000}{}{Cama}
{21001}{}{Esta cama ha visto mejores días (y probablemente noches, también).}
{21100}{}{Cama}
{21101}{}{Inspeccionándola más de cerca, te das cuenta que las sábanas no han sido cambiadas desde hace mucho, mucho tiempo.}
{21200}{}{Cama}
{21201}{}{Hay un par de manchas de extraña procedencia en esta cama destartalada.}
{21300}{}{Cama}
{21301}{}{Esta cama ha tenido mucho uso y desgaste. Algo debió de meterse entre los colchones y murió, también.}
{21400}{}{una estantería}
{21500}{}{una estantería}
{21600}{}{una estantería}
{21700}{}{una estantería}
{21800}{}{una estantería}
{21900}{}{una estantería}
{22000}{}{Cajas}
{22001}{}{Estas cajas de madera se están deteriorando por las condiciones ambientales.}
{22100}{}{Cajas}
{22101}{}{No ves ningún detalle especial en estas cajas de madera.}
{22200}{}{Cajas}
{22201}{}{Te sobra el tiempo para observar de cerca esta basura podrida.}
{22300}{}{Cajas}
{22301}{}{Estas cajas de madera se están deteriorando por las condiciones ambientales.}
{22400}{}{Coche}
{22401}{}{Este automóvil tiene una pinta terrible. No crees que haya forma de repararlo.}
{22500}{}{Coche}
{22501}{}{Esta pieza oxidada de metal no puede repararse.}
{22600}{}{Coche}
{22601}{}{Concluyes que este vehículo no volverá a poder conducirse. Ni de broma.}
{22700}{}{Coche}
{22701}{}{No hay forma de que esta chatarra pueda volver a poder conducirse de nuevo.}
{22800}{}{Coche}
{22801}{}{Si el Mecánico del Año apareciera a tu lado, ninguno de los dos podría reparar esta chatarra oxidada.}
{22900}{}{Silla}
{22901}{}{Una silla cómoda.}
{23000}{}{Silla}
{23001}{}{Parece que esta silla ha vivido mejores momentos.}
{23100}{}{Silla}
{23101}{}{Esta silla está mohosa y asquerosa. Como puedes adivinar, también apesta.}
{23200}{}{Silla}
{23201}{}{Esta silla se está cayendo a pedazos. Rápidamente.}
{23300}{}{Silla}
{23301}{}{Si alguien te pagara un montón de chapas y pudieras usar refuerzos de acero, te plantearías sentarte en esta silla.}
{23400}{}{Silla}
{23401}{}{Parece una vieja silla de oficina que se conserva bien pese al paso del tiempo.}
{23500}{}{Silla}
{23501}{}{Es una silla de oficina. Podría soportar el peso de una persona.}
{23600}{}{Silla}
{23601}{}{Esta silla de oficina parece que tuvo días mejores. Ahora es básicamente basura.}
{23700}{}{Silla}
{23701}{}{Parece una silla que verías en la oficina de una funeraria: muerta.}
{23800}{}{una mesa}
{23900}{}{una mesa}
{24000}{}{una cómoda}
{24100}{}{una cómoda}
{24200}{}{una cómoda}
{24300}{}{Boca de incendios}
{24301}{}{Esta es una boca de incendios. Sin rociadores de techo como los del Refugio, podría hacerte falta una para apagar un fuego.}
{24400}{}{Poste de luz}
{24401}{}{Esta farola parece que sigue en condiciones de funcionar. Imagina, por aquí hay algo que funciona.}
{24500}{}{Poste de luz}
{24501}{}{Esta farola nunca volverá a funcionar.}
{24600}{}{Poste de luz}
{24601}{}{Esta es una farola funcional. Por la noche, proyecta una luz pálida y suave que te recuerda absolutamente nada.}
{24700}{}{Poste de luz}
{24701}{}{Esta farola está rota. No se puede reparar.}
{24800}{}{Poste de luz}
{24801}{}{Esta farola funciona.}
{24900}{}{Poste de luz}
{24901}{}{La bombilla de este poste de luz está destrozada, sin posibilidad de reparación.}
{25000}{}{Poste de luz}
{25001}{}{Esta es una farola funcional.}
{25100}{}{Puerta}
{25101}{}{La cerradura de esta puerta se ha atascado y las barras tienen un aspecto muy robusto.}
{25200}{}{Vertedero}
{25201}{}{Definitivamente, chatarra sin valor, sin duda.}
{25300}{}{Vertedero}
{25301}{}{Definitivamente, chatarra sin valor, sin duda.}
{25400}{}{Vertedero}
{25401}{}{Definitivamente, chatarra sin valor, sin duda.}
{25500}{}{Vertedero}
{25501}{}{Definitivamente, chatarra sin valor, sin duda.}
{25600}{}{Vertedero}
{25601}{}{Definitivamente, chatarra sin valor, sin duda.}
{25700}{}{Buzón de correos}
{25701}{}{Este buzón de correos está vacío. Tienes la impresión de que lleva así mucho tiempo.}
{25800}{}{Puerta}
{25801}{}{Una puerta de madera bien elaborada, en buenas condiciones.}
{25900}{}{Puerta}
{25901}{}{Una puerta de madera bien elaborada, en buenas condiciones.}
{26000}{}{Puerta}
{26001}{}{Una puerta de madera bien elaborada, en buenas condiciones.}
{26100}{}{Puerta}
{26101}{}{Una puerta de madera bien elaborada, en buenas condiciones.}
{26200}{}{Banco de iglesia}
{26201}{}{Este banco de madera esta deteriorándose lentamente.}
{26300}{}{Banco de iglesia}
{26301}{}{Este banco ha sido abandonado, y muestra signos de desuso.}
{26400}{}{Banco de iglesia}
{26401}{}{Un banco de madera que ha sucumbido a los efectos del tiempo y el maltrato.}
{26500}{}{Expendedora de periódicos}
{26501}{}{Esta expendedora de periódicos está vacía.}
{26600}{}{Expendedora de periódicos}
{26601}{}{Esta expendedora de periódicos está vacía.}
{26700}{}{Expendedora de periódicos}
{26701}{}{Esta expendedora de periódicos está vacía.}
{26800}{}{Expendedora de periódicos}
{26801}{}{Esta expendedora de periódicos está vacía.}
{26900}{}{Expendedora de periódicos}
{26901}{}{Esta expendedora de periódicos está vacía.}
{27000}{}{Expendedora de periódicos}
{27001}{}{Esta expendedora de periódicos está vacía. Parece que en su momento debió contener revistas para adultos.}
{27100}{}{Vertedero}
{27101}{}{Un colchón en pésimas condiciones. Ni siquiera las ratas dormirían en él.}
{27200}{}{Vertedero}
{27201}{}{Una cama de matrimonio que ha tenido días mejores que este.}
{27300}{}{Vertedero}
{27301}{}{Una pila de madera podrida y desgastada. No vale su peso en, bueno, en nada.}
{27400}{}{Vertedero}
{27401}{}{Un montón de madera, con algunos inútiles clavos oxidados clavados profundamente.}
{27500}{}{Cajas}
{27501}{}{Un montón de cajas viejas. No te explicas cómo han podido durar tanto tiempo.}
{27600}{}{Cajas}
{27601}{}{Un montón de cajas viejas.}
{27700}{}{Vertedero}
{27701}{}{Algunos desperdicios que crees que han podido ser un colchón antes de ser destruidos por el ambiente.}
{27800}{}{Rocas}
{27801}{}{Tras un examen más minucioso, estas siguen siendo piedras.}
{27900}{}{Rocas}
{27901}{}{Sep, son piedras.}
{28000}{}{Rocas}
{28001}{}{Concluyes que son piedras.}
{28100}{}{unos escombros}
{28101}{}{Un montoncito de escombros y piedras. ¡Cuidado!}
{28200}{}{un fregadero}
{28201}{}{Un fregadero de porcelana que dejó de funcionar hace tiempo.}
{28300}{}{un fregadero}
{28301}{}{Un fregadero de porcelana roto. Hay restos de agua sucia en el fondo y una rata muerta que flota.}
{28400}{}{un fregadero}
{28401}{}{Este fregadero no funciona. Puedes deducirlo por el gran agujero del centro.}
{28500}{}{un fregadero}
{28501}{}{Un fregadero de porcelana roto. Hay restos de agua sucia en el fondo y una rata muerta que flota.}
{28600}{}{una señal de ALTO}
{28601}{}{Una señal roja con la palabra STOP escrita en grandes letras.}
{28700}{}{una señal de ALTO}
{28701}{}{Una señal roja con la palabra STOP escrita en grandes letras. El agujero de bala que presenta no viene de fábrica.}
{28800}{}{un semáforo}
{28801}{}{Es un dispositivo del control de tráfico.}
{28900}{}{un semáforo}
{28901}{}{Es un dispositivo del control de tráfico.}
{29000}{}{un semáforo}
{29001}{}{Es un dispositivo del control de tráfico.}
{29100}{}{una farola}
{29101}{}{Esta farola ilumina las calles cuando anochece o cuando no hay demasiada luz.}
{29200}{}{una farola}
{29201}{}{Esta farola ilumina las calles cuando anochece o cuando no hay demasiada luz.}
{29300}{}{una farola}
{29301}{}{Esta farola ilumina las calles cuando anochece o cuando no hay demasiada luz.}
{29400}{}{una farola}
{29401}{}{Esta farola ilumina las calles cuando anochece o cuando no hay demasiada luz.}
{29500}{}{una farola}
{29501}{}{Esta farola ofrece iluminación al caer la noche, si no estuviera rota.}
{29600}{}{una farola}
{29601}{}{Esta farola ofrece iluminación al caer la noche, si no estuviera rota.}
{29700}{}{una farola}
{29701}{}{Esta farola ofrece iluminación al caer la noche, si no estuviera rota.}
{29800}{}{Letrero}
{29801}{}{Esta señal podría indicar el nombre de la calle, pero las letras no se ven.}
{29900}{}{Letrero}
{29901}{}{Esta señal podría indicar el nombre de la calle, pero las letras no se ven.}
{30000}{}{una mesa}
{30001}{}{Una mesa de madera que no está en muy buenas condiciones.}
{30100}{}{una mesa}
{30101}{}{Una mesa de madera que no está en muy buenas condiciones.}
{30200}{}{una mesa}
{30201}{}{Una mesa de madera que no está en muy buenas condiciones.}
{30300}{}{una mesa}
{30301}{}{Una mesa de madera, con una superficie plástica que ha sido rota hace poco.}
{30400}{}{una mesa}
{30401}{}{Una mesa de madera de color verde que necesita un arreglo.}
{30500}{}{una mesa}
{30501}{}{Parece una vieja mesa de café cuyas dimensiones se ajustan a la estatura de esos pequeños mutantes.}
{30600}{}{una mesa}
{30601}{}{Parece una vieja mesa de café cuyas dimensiones se ajustan a la estatura de esos pequeños mutantes.}
{30700}{}{el váter}
{30701}{}{Por la forma del asiento no es el lugar más indicado para sentarse.}
{30800}{}{el váter}
{30801}{}{Este váter está roto.}
{30900}{}{el váter}
{30901}{}{¡Puaj! ¡El último que lo usó no tiró de la cadena!}
{31000}{}{el váter}
{31001}{}{Este váter está roto y no puedes utilizarlo si eres una mujer.}
{31100}{}{Desperdicios}
{31101}{}{Algunas tuberías semiescondidas entre la basura. No hay nada importante. Sigue.}
{31200}{}{Desperdicios}
{31201}{}{Algunas esquirlas de cristal y otros desperdicios.}
{31300}{}{Desperdicios}
{31301}{}{Algunas esquirlas de cristal y otros desperdicios.}
{31400}{}{Desperdicios}
{31401}{}{Una tubería que ha sido partida por la mitad. Parece que se ha roto por su propio peso.}
{31500}{}{un cubo de basura}
{31501}{}{Un cubo de basura. Apenas puedes leer el letrero: ¡Mantenga limpia su ciudad!}
{31600}{}{Árbol}
{31601}{}{Es un árbol muerto.}
{31700}{}{Árbol}
{31701}{}{Un tocón. Nada digno de mención. De hecho, esto podría ser la cosa menos interesante que has visto en tu vida.}
{31800}{}{Árbol}
{31801}{}{Es un árbol muerto.}
{31900}{}{Árbol}
{31901}{}{Es un árbol muerto.}
{32000}{}{Árbol}
{32001}{}{Es un árbol muerto.}
{32100}{}{Árbol}
{32101}{}{Es un árbol muerto.}
{32200}{}{un camión}
{32201}{}{Este camión ha tenido mejores días. Parece que los saqueadores no lo han tocado, pero aun así...}
{32300}{}{un camión}
{32301}{}{Los restos de un camión cisterna. Este amasijo de metal no volverá a moverse.}
{32400}{}{un camión}
{32401}{}{Este camión cisterna necesita ayuda. Irremediablemente.}
{32500}{}{una bañera}
{32501}{}{Esta bañera está rota y desconchada.}
{32600}{}{una bañera}
{32601}{}{Tras un examen riguroso, concluyes que no te bañarás ahí.}
{32700}{}{el urinario}
{32701}{}{Es solo un urinario.}
{32800}{}{el urinario}
{32801}{}{Es solo un urinario.}
{32900}{}{el urinario}
{32901}{}{Es solo un urinario. Nada digno de mención.}
{33000}{}{el urinario}
{33001}{}{Es solo un urinario. Nada digno de mención.}
{33100}{}{un depósito de agua}
{33101}{}{Un gran tanque con líquido. En este caso, crees que se diseñó para almacenar agua.}
{33200}{}{Puerta}
{33201}{}{Una puerta de madera. Nada especial que destacar.}
{33300}{}{Puerta}
{33301}{}{Una puerta de madera. Es la entrada y la salida de este edificio.}
{33400}{}{una lámpara de pared}
{33401}{}{Esta lámpara parece estar en buenas condiciones.}
{33500}{}{una lámpara de pared}
{33501}{}{Una lámpara rota. Es normal que no funcione.}
{33600}{}{una lámpara de pared}
{33601}{}{Esta lámpara parece estar en buenas condiciones.}
{33700}{}{una lámpara de pared}
{33701}{}{Una lámpara rota. Es normal que no funcione.}
{33800}{}{una lámpara de pared}
{33801}{}{Esta lámpara parece estar en buenas condiciones.}
{33900}{}{una lámpara de pared}
{33901}{}{Una lámpara rota. Es normal que no funcione.}
{34000}{}{una lámpara de pared}
{34001}{}{Esta lámpara parece estar en buenas condiciones.}
{34100}{}{una lámpara de pared}
{34101}{}{Una lámpara rota. Es normal que no funcione.}
{34200}{}{una señal de atención}
{34201}{}{Era una señal para controlar el flujo de tráfico.}
{34300}{}{una señal de atención}
{34301}{}{The sign is faded, but you can make out the word "YIELD".}
{34400}{}{Inviso Automático de Bloqueo de Hexágonos}
{34401}{}{Si estás viendo esto, maldice al diseñador técnico.}
{34500}{}{el suelo}
{34600}{}{Puerta}
{34601}{}{Una puerta de madera decorada. Obviamente fue diseñada por un diestro artesano.}
{34700}{}{Banco de iglesia}
{34701}{}{Este asiento se apoya en grandes ladrillos. Nada del otro mundo, pero tú quisiste mirarlo.}
{34800}{}{una escalera}
{34801}{}{Esta escalera conduce hacia arriba.}
{34900}{}{una escalera}
{34901}{}{Esta escalera conduce hacia arriba.}
{35000}{}{una escalera}
{35001}{}{Esta escalera conduce hacia arriba.}
{35100}{}{una escalera}
{35101}{}{Esta escalera conduce hacia arriba.}
{35200}{}{una escalera}
{35201}{}{Esta escalera conduce hacia arriba.}
{35300}{}{una escalera}
{35301}{}{Esta escalera conduce hacia arriba.}
{35400}{}{una escalera}
{35401}{}{Esta escalera conduce hacia arriba.}
{35500}{}{una escalera}
{35501}{}{Esta escalera conduce hacia arriba.}
{35600}{}{una escalera}
{35601}{}{Esta escalera conduce hacia abajo.}
{35700}{}{Muro}
{35701}{}{Estás mirando el exterior de la Catedral.}
{35800}{}{Muro}
{35801}{}{Estás mirando el exterior de la Catedral.}
{35900}{}{Muro}
{35901}{}{Estás mirando el exterior de la Catedral.}
{36000}{}{Muro}
{36001}{}{Estás mirando el exterior de la Catedral.}
{36100}{}{una cortina}
{36101}{}{Esta cortina parece haber sido creada con medios primitivos, pero resulta muy funcional.}
{36200}{}{una cortina}
{36201}{}{Esta cortina parece haber sido creada con medios primitivos, pero resulta muy funcional.}
{36300}{}{un cuenco}
{36301}{}{Un cuenco de madera elegantemente tallado. Parece servir para triturar y separar granos.}
{36400}{}{un cuenco}
{36401}{}{Un cuenco de madera elegantemente tallado.}
{36500}{}{Olla}
{36501}{}{Una vasija muy bien hecha.}
{36600}{}{una planta}
{36601}{}{Crees que se trata de una col mutante. Parece florecer a temperaturas cálidas.}
{36700}{}{una planta}
{36701}{}{Crees que se trata de una col mutante. Parece florecer a temperaturas cálidas.}
{36800}{}{una carretilla}
{36801}{}{Una carretilla de campo austera pero efectiva.}
{36900}{}{una planta}
{36901}{}{Una caña de maíz mutante. Parece florecer bajo estas condiciones.}
{37000}{}{una planta}
{37001}{}{Una caña de maíz mutante. Parece florecer bajo estas condiciones.}
{37100}{}{una planta}
{37101}{}{Una caña de maíz mutante. Parece florecer bajo estas condiciones.}
{37200}{}{Olla}
{37201}{}{Una olla artesanal.}
{37300}{}{un rastrillo}
{37301}{}{Este rastrillo es propiedad de sus dueños. No puedes imaginar para qué sirve.}
{37400}{}{un rastrillo}
{37401}{}{Este rastrillo es propiedad de sus dueños. No puedes imaginar para qué sirve.}
{37500}{}{un rastrillo}
{37501}{}{Este rastrillo es propiedad de sus dueños. No puedes imaginar para qué sirve.}
{37600}{}{una esterilla}
{37601}{}{Una simple esterilla. Esta claro que el tejedor tenía talento.}
{37700}{}{una esterilla}
{37701}{}{Una simple esterilla. Esta claro que el tejedor tenía talento.}
{37800}{}{una esterilla}
{37801}{}{Una simple esterilla. Esta claro que el tejedor tenía talento.}
{37900}{}{Pala}
{37901}{}{Esta pala es propiedad de sus dueños. No puedes imaginar para qué sirve.}
{38000}{}{Pala}
{38001}{}{Esta pala es propiedad de sus dueños. No puedes imaginar para qué sirve.}
{38100}{}{Pala}
{38101}{}{Esta pala es propiedad de sus dueños. No puedes imaginar para qué sirve.}
{38200}{}{un jarrón}
{38201}{}{Un jarrón de barro muy bonito.}
{38300}{}{Pozo}
{38301}{}{Por mucho que lo intentas, no se te ocurre la forma de llevar este pozo a tu Refugio.}
{38400}{}{un palo}
{38401}{}{Este palo ayuda a sostener la tienda.}
{38500}{}{un palo}
{38501}{}{Este palo ayuda a sostener la tienda.}
{38600}{}{un palo}
{38601}{}{Este palo ayuda a sostener la tienda.}
{38700}{}{un palo}
{38701}{}{Este palo ayuda a sostener la tienda.}
{38800}{}{un palo}
{38801}{}{Este palo ayuda a sostener la tienda.}
{38900}{}{un palo}
{38901}{}{Este palo ayuda a sostener la tienda.}
{39000}{}{Vault Blast Door}
{39001}{}{This Vault blast door is now just a large piece of heavy scrap metal.}
{39100}{}{Vault Entrance}
{39101}{}{The mechanisms and computer used to open or close the heavy Vault blast door have been damaged beyond repair.}
{39200}{}{el refuerzo}
{39201}{}{Este refuerzo ayuda a sostener el muro defensivo.}
{39300}{}{el refuerzo}
{39301}{}{Este refuerzo ayuda a sostener el muro defensivo.}
{39400}{}{el refuerzo}
{39401}{}{Este refuerzo ayuda a sostener el muro defensivo.}
{39500}{}{el refuerzo}
{39501}{}{Este refuerzo ayuda a sostener el muro defensivo.}
{39600}{}{Barril metálico}
{39601}{}{Un barril de metal oxidado. Está vacío.}
{39700}{}{Barril metálico}
{39701}{}{Por su sonido hueco, parece que este barril está vacío.}
{39800}{}{un barril de metal}
{39801}{}{Por su sonido hueco, parece que estos barriles están vacíos.}
{39900}{}{un barril de metal}
{39901}{}{Por su sonido hueco, parece que estos barriles están vacíos.}
{40000}{}{una cúpula}
{40001}{}{Encuentras una pequeña etiqueta que pone: "Propiedad de la Zona-51. Si lo encuentra, por favor, devuélvalo".}
{40100}{}{un cajón}
{40101}{}{Un cajón de madera. No parece estar en mal estado.}
{40200}{}{un cajón}
{40201}{}{Un simple cajón de madera en buenas condiciones.}
{40300}{}{un cajón}
{40301}{}{Este simple cajón de madera ha cedido por su propio peso.}
{40400}{}{una mesa}
{40401}{}{Este es un escritorio desvencijado con un ordenador viejo y polvoriento colocado encima de él.}
{40500}{}{una mesa}
{40501}{}{Este es un escritorio desvencijado con un ordenador viejo y polvoriento colocado encima de él.}
{40600}{}{Puerta}
{40601}{}{Una puerta de madera en buen estado.}
{40700}{}{la entrada a la cueva}
{40701}{}{Una gran cantidad de piedras, muchas más de las que se pueden mover con facilidad.}
{40800}{}{Coche}
{40801}{}{Este coche sumergido no puede repararse.}
{40900}{}{Coche}
{40901}{}{Este coche está algo húmedo y no puede repararse.}
{41000}{}{Coche}
{41001}{}{Este coche ha sido mal aparcado. Por desgracia, necesita una reparación.}
{41100}{}{Vertedero}
{41101}{}{Esta chatarra ha sido destrozada por agua de mar contaminada.}
{41200}{}{Vertedero}
{41201}{}{Esta basura casi ha desaparecido.}
{41300}{}{Vertedero}
{41301}{}{Una selecta gama de basura inservible.}
{41400}{}{Tuberías}
{41401}{}{Estas tuberías solían transportar combustible desde un depósito subterráneo hasta el garaje. No se utilizan desde hace mucho tiempo.}
{41500}{}{Tubería}
{41501}{}{Estas tuberías solían transportar combustible desde un depósito subterráneo hasta el garaje. No se utilizan desde hace mucho tiempo.}
{41600}{}{Tuberías}
{41601}{}{Estas tuberías solían transportar combustible desde un depósito subterráneo hasta el garaje. No se utilizan desde hace mucho tiempo.}
{41700}{}{el hueco del ascensor}
{41701}{}{Parte del sistema de un ascensor.}
{41800}{}{el hueco del ascensor}
{41801}{}{Un hueco del ascensor que se pierde en las profundidades. Ha sido dañado.}
{41900}{}{Ascensor}
{41901}{}{Un ascensor. Úsalo para subir y bajar niveles.}
{42000}{}{el hueco del ascensor}
{42001}{}{Un hueco del ascensor que se pierde en las profundidades. Ha sido dañado.}
{42100}{}{una puerta de ascensor}
{42101}{}{Esta puerta conduce a la caja del ascensor. Si quieres usar el ascensor, primero has de abrir esta puerta.}
{42200}{}{Tubería}
{42201}{}{Una tubería de metal. No merece mencionar más detalles.}
{42300}{}{Basura}
{42400}{}{una caja}
{42401}{}{Un contenedor de almacenaje y transporte de aspecto caro, probablemente hecho a partir de un compuesto de alta tecnología, con el emblema de la Hermandad del Acero estampado en él.}
{42500}{}{una caja}
{42501}{}{Un contenedor de almacenaje y transporte de aspecto caro, probablemente hecho a partir de un compuesto de alta tecnología, con el emblema de la Hermandad del Acero estampado en él.}
{42600}{}{una caja}
{42601}{}{Un contenedor de almacenaje y transporte de aspecto caro, probablemente hecho a partir de un compuesto de alta tecnología, con el emblema de la Hermandad del Acero estampado en él.}
{42700}{}{una caja}
{42701}{}{Un contenedor de almacenaje y transporte de aspecto caro, probablemente hecho a partir de un compuesto de alta tecnología, con el emblema de la Hermandad del Acero estampado en él.}
{42800}{}{Rocas}
{42801}{}{Un montoncito de piedras. No es muy interesante.}
{42900}{}{Rocas}
{42901}{}{Un montoncito de piedras. No es muy interesante.}
{43000}{}{Rocas}
{43001}{}{Un montoncito de piedras. No tiene demasiado interés para ti.}
{43100}{}{Rocas}
{43101}{}{Un montoncito de piedras.}
{43200}{}{Rocas}
{43201}{}{Un montoncito de piedras.}
{43300}{}{Rocas}
{43301}{}{Un montoncito de piedras.}
{43400}{}{Rocas}
{43401}{}{Un montoncito de piedras.}
{43500}{}{Rocas}
{43501}{}{Un montoncito de piedras.}
{43600}{}{Vault Blast Door}
{43601}{}{This Vault blast door is very similar to the one at Vault 13. The door mechanism has been disabled.}
{43700}{}{Puerta}
{43701}{}{Una puerta de madera, reforzada con laterales metálicos con un diseño casi hipnótico.}
{43800}{}{Puerta}
{43801}{}{Una puerta de madera, reforzada con laterales metálicos con un diseño casi hipnótico.}
{43900}{}{Tanques}
{43901}{}{Una especie de estructura. No estás seguro, pero te parece ver grandes tanques de mezcla verde que no parece demasiado importante.}
{44000}{}{Tanques}
{44001}{}{Una especie de estructura. No estás seguro, pero te parece ver grandes tanques de mezcla verde que no parece demasiado importante.}
{44100}{}{Tanques}
{44101}{}{Una especie de estructura. No estás seguro, pero te parece ver grandes tanques de mezcla verde que no parece demasiado importante.}
{44200}{}{Tanques}
{44201}{}{Una especie de estructura. No estás seguro, pero te parece ver grandes tanques de mezcla verde que no parece demasiado importante.}
{44300}{}{Tanques}
{44301}{}{Una especie de estructura. No estás seguro, pero te parece ver grandes tanques de mezcla verde que no parece demasiado importante.}
{44400}{}{Tanques}
{44401}{}{Una especie de estructura. No estás seguro, pero te parece ver grandes tanques de mezcla verde que no parece demasiado importante.}
{44500}{}{Tanques}
{44501}{}{Una especie de estructura. No estás seguro, pero te parece ver grandes tanques de mezcla verde que no parece demasiado importante.}
{44600}{}{Tanques}
{44601}{}{Una especie de estructura. No estás seguro, pero te parece ver grandes tanques de mezcla verde que no parece demasiado importante.}
{44700}{}{Muro}
{44701}{}{Un muro de ladrillos con un bonito patrón de mugre sobre él.}
{44800}{}{Puerta}
{44801}{}{Una puerta de seguridad. Parece fuertemente blindada.}
{44900}{}{una cabeza nuclear}
{45000}{}{Pozo}
{45001}{}{Por mucho que lo intentas, no se te ocurre la forma de llevar este pozo a tu Refugio.}
{45100}{}{una mesa de dados}
{45101}{}{Una mesa de juego.}
{45200}{}{una mesa de dados}
{45201}{}{Una mesa de juego.}
{45300}{}{una mesa de dados}
{45301}{}{Una mesa de juego.}
{45400}{}{una mesa de dados}
{45401}{}{Una mesa de juego.}
{45500}{}{una mesa de dados}
{45501}{}{Una mesa de juego.}
{45600}{}{una mesa de dados}
{45601}{}{Una mesa de juego.}
{45700}{}{una mesa de dados}
{45701}{}{Una mesa de juego.}
{45800}{}{una mesa de dados}
{45801}{}{Una mesa de juego.}
{45900}{}{una mesa de dados}
{45901}{}{Una mesa de juego.}
{46000}{}{una mesa de dados}
{46001}{}{Una mesa de juego.}
{46100}{}{una piedra}
{46101}{}{Una pequeña piedra que carece de interés en el contexto de esta historia.}
{46200}{}{una piedra}
{46201}{}{Una pequeña piedra que carece de interés en el contexto de esta historia.}
{46300}{}{una piedra}
{46301}{}{Una pequeña piedra que carece de interés en el contexto de esta historia.}
{46400}{}{una piedra}
{46401}{}{Una pequeña piedra que carece de interés en el contexto de esta historia.}
{46500}{}{una máquina tragaperras}
{46501}{}{Esta es una máquina de juego.}
{46600}{}{una máquina tragaperras}
{46601}{}{Esta es una máquina de juego.}
{46700}{}{el portal}
{46800}{}{Ascensor}
{46900}{}{Ascensor}
{47000}{}{una puerta de ascensor}
{47100}{}{una ventana}
{47101}{}{Esta ventana está hecha con papel de cera y no con cristal.}
{47200}{}{una ventana}
{47201}{}{Esta ventana está hecha con papel de cera y no con cristal.}
{47300}{}{una ventana}
{47301}{}{Esta ventana está hecha con papel de cera y no con cristal.}
{47400}{}{una ventana}
{47401}{}{Esta ventana está hecha con papel de cera y no con cristal.}
{47500}{}{Puerta}
{47501}{}{Esta gran puerta giratoria se ha atascado desde el interior.}
{47600}{}{Puerta}
{47601}{}{Esta gran puerta giratoria se ha atascado desde el interior.}
{47700}{}{Puerta}
{47701}{}{Esta gran puerta giratoria se ha atascado desde el interior. Pone: SÓLO CARGA.}
{47800}{}{Puerta}
{47801}{}{Esta gran puerta giratoria se ha atascado desde el interior.}
{47900}{}{Puerta}
{47901}{}{Esta gran puerta giratoria se ha atascado desde el interior.}
{48000}{}{Puerta}
{48001}{}{Esta gran puerta giratoria se ha atascado desde el interior. Pone: SÓLO CARGA.}
{48100}{}{Puerta}
{48101}{}{Esta puerta podría ser la de un almacén.}
{48200}{}{Puerta}
{48201}{}{Esta puerta podría ser la de un almacén.}
{48300}{}{una sonda meteorológica}
{48301}{}{Esta simple sonda meteorológica le permite a la gente de Arenas Sombrías estudiar el tiempo.}
{48400}{}{Altar}
{48401}{}{Un simple altar hecho con madera pintada.}
{48500}{}{un podio}
{48501}{}{Este podio es normal, excepto por el símbolo de los Niños de la Catedral grabado en él.}
{48600}{}{Altar}
{48700}{}{Monitor}
{48701}{}{Un gran monitor en blanco y negro. La recepción es bastante buena para estar en un lugar cerrado sin antena.}
{48800}{}{Monitor}
{48801}{}{Un gran monitor en blanco y negro. La figura con túnica está recitando un dogma religioso de modo muy fervoroso.}
{48900}{}{un campo de fuerza}
{48901}{}{Un potente campo de energía que previene el paso de cualquier cosa, viviente o no.}
{49000}{}{un campo de fuerza}
{49001}{}{Un potente campo de energía que previene el paso de cualquier cosa, viviente o no.}
{49100}{}{un campo de fuerza}
{49101}{}{Un potente campo de energía que crepita amenazadoramente. Te das cuenta de que el campo está dañado lo suficiente como para caminar a través de él.}
{49200}{}{un campo de fuerza}
{49201}{}{Un potente campo de energía que crepita amenazadoramente. Te das cuenta de que el campo está dañado lo suficiente como para caminar a través de él.}
{49300}{}{una mesa}
{49301}{}{Una mesa de madera normal y corriente.}
{49400}{}{una mesa}
{49401}{}{Una mesa de madera normal y corriente.}
{49500}{}{una mesa}
{49501}{}{Una mesa de madera normal y corriente.}
{49600}{}{una mesa}
{49601}{}{Una mesa de madera normal y corriente.}
{49700}{}{una mesa}
{49701}{}{Una mesa de madera normal y corriente.}
{49800}{}{una mesa}
{49801}{}{Una mesa de madera normal y corriente.}
{49900}{}{Estante}
{50000}{}{Estante}
{50100}{}{Estante}
{50200}{}{Estante}
{50300}{}{Estante}
{50400}{}{Estante}
{50500}{}{Altar}
{50501}{}{Un simple altar hecho con madera pintada.}
{50600}{}{Altar}
{50601}{}{Un simple altar hecho con madera pintada.}
{50700}{}{Altar}
{50701}{}{Un simple altar hecho con madera pintada.}
{50800}{}{Altar}
{50801}{}{Un simple altar hecho con madera pintada.}
{50900}{}{unos escombros}
{50901}{}{Una parte destruida del tejado ha formado este montón de escombros. La cuerda te conduce de nuevo a la superficie.}
{51000}{}{una estantería}
{51100}{}{una estantería}
{51200}{}{una estantería}
{51300}{}{una estantería}
{51400}{}{una estantería}
{51500}{}{una estantería}
{51600}{}{una mesa}
{51601}{}{Esta mesa grande parece importante. Puede que tengan reuniones aquí.}
{51700}{}{una mesa}
{51701}{}{Esta mesa grande parece importante. Puede que tengan reuniones aquí.}
{51800}{}{una mesa}
{51801}{}{Esta mesa grande parece importante. Puede que tengan reuniones aquí.}
{51900}{}{una mesa}
{51901}{}{Esta mesa grande parece importante. Puede que tengan reuniones aquí.}
{52000}{}{una mesa}
{52001}{}{Esta mesa grande parece importante. Puede que tengan reuniones aquí.}
{52100}{}{una mesa}
{52101}{}{Esta mesa grande parece importante. Puede que tengan reuniones aquí.}
{52200}{}{Altar}
{52201}{}{Un altar diseñado y utilizado por la Hermandad del Acero. Su símbolo es muy aparente.}
{52300}{}{Altar}
{52301}{}{Un altar diseñado y utilizado por la Hermandad del Acero. Su símbolo es muy aparente.}
{52400}{}{Altar}
{52401}{}{Un altar diseñado y utilizado por la Hermandad del Acero. Su símbolo es muy aparente.}
{52500}{}{Banco de iglesia}
{52501}{}{Un banco bonito pero incómodo.}
{52600}{}{un podio}
{52601}{}{Un podio de madera bonito. Hay una pantalla delante que muestra al orador.}
{52700}{}{Carro}
{52701}{}{Un carro de mercancías convertido a partir de restos destrozados de un antiguo automóvil.}
{52800}{}{Carro}
{52801}{}{Un carro de mercancías convertido a partir de restos destrozados de un antiguo automóvil.}
{52900}{}{Carro}
{52901}{}{Un carro de mercancías convertido a partir de restos destrozados de un antiguo automóvil.}
{53000}{}{Carro}
{53001}{}{Un carro de mercancías convertido a partir de restos destrozados de un antiguo automóvil.}
{53100}{}{Carro}
{53101}{}{Un carro de mercancías convertido a partir de restos destrozados de un antiguo automóvil.}
{53200}{}{Carro}
{53201}{}{Un carro de mercancías convertido a partir de restos destrozados de un antiguo automóvil.}
{53300}{}{una colchoneta}
{53301}{}{Una colchoneta de ejercicios.}
{53400}{}{una colchoneta}
{53401}{}{Una colchoneta de ejercicios.}
{53500}{}{una colchoneta}
{53501}{}{Una colchoneta de ejercicios.}
{53600}{}{una colchoneta}
{53601}{}{Una colchoneta de ejercicios.}
{53700}{}{un saco de boxeo}
{53701}{}{Es un saco de boxeo de la marca StrongMan(tm).}
{53800}{}{una escalera de ejercicios}
{53801}{}{Una máquina de ejercicios.}
{53900}{}{una escalera de ejercicios}
{53901}{}{Una máquina de ejercicios.}
{54000}{}{una cinta móvil}
{54001}{}{Una máquina de ejercicios.}
{54100}{}{una cinta móvil}
{54101}{}{Una máquina de ejercicios.}
{54200}{}{un banco de pressing}
{54201}{}{Decides que no es el momento de hacer pesas.}
{54300}{}{un banco de pressing}
{54301}{}{Decides que no es el momento de hacer pesas.}
{54400}{}{Puente}
{54401}{}{Un puente de madera precario permite el acceso a través de la sustancia viscosa.}
{54500}{}{Puente}
{54501}{}{Un puente de madera precario permite el acceso a través de la sustancia viscosa.}
{54600}{}{una mesa de ruleta}
{54601}{}{Una mesa de juego.}
{54700}{}{una mesa de ruleta}
{54701}{}{Una mesa de juego.}
{54800}{}{una mesa de ruleta}
{54801}{}{Una mesa de juego.}
{54900}{}{una mesa de ruleta}
{54901}{}{Una mesa de juego.}
{55000}{}{una mesa de ruleta}
{55001}{}{Una mesa de juego.}
{55100}{}{un barril}
{55101}{}{Este barril de metal vacío tiene el símbolo del trébol nuclear pintado en un lado con pintura amarilla brillante.}
{55200}{}{un barril}
{55201}{}{Este barril contiene una especie de sustancia viscosa que reluce. El símbolo del trébol nuclear da una pista sobre lo que puede ser esta sustancia viscosa.}
{55300}{}{Computadora}
{55301}{}{Un ordenador de apariencia muy moderna.}
{55400}{}{Computadora}
{55401}{}{Un ordenador de apariencia muy moderna.}
{55500}{}{un tanque de suspensión}
{55501}{}{Una especie de aparato médico o experimental. Parece tener capacidad para contener un cuerpo humano o el de una criatura grande.}
{55600}{}{un tanque de suspensión roto}
{55601}{}{Una pieza de equipo rota. Necesita una reparación.}
{55700}{}{el ordenador principal}
{55701}{}{Un súper ordenador. Probablemente el ordenador más rápido que has visto en tu vida.}
{55800}{}{Plataforma de Soporte}
{55801}{}{Esta plataforma soporta el gran ordenador sobre las cámaras frigoríficas.}
{55900}{}{NO USAR}
{56000}{}{NO USAR}
{56100}{}{Cama}
{56101}{}{Una litera de estilo militar. Debe de ser muy incómoda. Las sábanas están tan tensas que podrías hacer rebotar una moneda sobre ellas.}
{56200}{}{Cama}
{56201}{}{Una litera de estilo militar. Debe de ser muy incómoda. Las sábanas están tan tensas que podrías hacer rebotar una moneda sobre ellas.}
{56300}{}{Cama}
{56301}{}{Una litera de estilo militar. Debe de ser muy incómoda. Las sábanas están tan tensas que podrías hacer rebotar una moneda sobre ellas.}
{56400}{}{Cable}
{56401}{}{Parece una especie de cable en serie.}
{56500}{}{Cable}
{56501}{}{Parece una especie de cable en serie.}
{56600}{}{una señal}
{56601}{}{En la señal pone BAR. Parece muy evidente.}
{56700}{}{una viga}
{56701}{}{Esta viga sólida está encima del agujero del cráter.}
{56800}{}{una viga}
{56801}{}{Hay una cuerda fuertemente atada a la viga. Parece que ahora puedes bajar al cráter.}
{56900}{}{unas repisas}
{56901}{}{Ves unas repisas metálicas vacías.}
{57000}{}{unas repisas}
{57001}{}{Ves unas repisas metálicas vacías.}
{57100}{}{unas repisas}
{57101}{}{Ves unas repisas metálicas vacías.}
{57200}{}{unas repisas}
{57201}{}{Ves unas repisas metálicas vacías.}
{57300}{}{un arbusto}
{57301}{}{Unos hierbajos salvajes. No son relevantes para esta historia.}
{57400}{}{un arbusto}
{57401}{}{Unos hierbajos salvajes.}
{57500}{}{un arbusto}
{57501}{}{Unos hierbajos salvajes.}
{57600}{}{el suelo}
{57601}{}{Una buena vista de Adytum y el Cementerio de LA desde este nivel de la torre. Puedes sentir lo cerca que estás del cielo.}
{57700}{}{el suelo}
{57701}{}{Una buena vista de Adytum y el Cementerio de LA desde este nivel de la torre.}
{57800}{}{Muro}
{57801}{}{Una buena vista de las afueras de la Catedral.}
{57900}{}{Muro}
{57901}{}{Una buena vista de las afueras de la Catedral.}
{58000}{}{Muro}
{58001}{}{Una buena vista de las afueras de la Catedral.}
{58100}{}{Puerta}
{58101}{}{Una puerta que parece ir a la perfección en una celda.}
{58200}{}{una señal}
{58201}{}{Según esta señal este es el Almacén de Darkwater.}
{58300}{}{Escalera}
{58301}{}{Esta escalera conduce a las oscuridades subterráneas.}
{58400}{}{Escalera}
{58401}{}{Esta escalera conduce a las oscuridades subterráneas.}
{58500}{}{la maquinaria}
{58501}{}{Parece una vieja prensa de impresión o un trasto de fábrica.}
{58600}{}{la maquinaria}
{58601}{}{Parece una vieja prensa de impresión o un trasto de fábrica.}
{58700}{}{la maquinaria}
{58701}{}{Parece una vieja prensa de impresión o un trasto de fábrica.}
{58800}{}{la maquinaria}
{58801}{}{Parece una vieja prensa de impresión o un trasto de fábrica.}
{58900}{}{la maquinaria}
{58901}{}{Parece una vieja prensa de impresión o un trasto de fábrica.}
{59000}{}{la maquinaria}
{59001}{}{Parece una vieja prensa de impresión o un trasto de fábrica.}
{59100}{}{una mesa}
{59101}{}{Esta mesa de metal parece estar en buenas condiciones. Hay un sumidero en su centro.}
{59200}{}{una mesa}
{59201}{}{Esta mesa de metal parece estar en buenas condiciones. Hay un sumidero en su centro.}
{59300}{}{una mesa}
{59301}{}{La mesa de metal está cubierta por una especie de biomasa.}
{59400}{}{una mesa}
{59401}{}{La mesa de metal está cubierta por una especie de biomasa.}
{59500}{}{una mesa}
{59501}{}{La mesa de metal está cubierta por una especie de biomasa.}
{59600}{}{un tablón de anuncios}
{59601}{}{Hay noticias de empleo colgadas en el tablón. Parece resultar de gran utilidad.}
{59700}{}{Garita de Guardia}
{59701}{}{Esta garita de guardia tiene cien años de antigüedad, pero está en excelente condición.}
{59800}{}{una señal}
{59801}{}{En esta señal pone: Grandes Almacenes.}
{59900}{}{una señal}
{59901}{}{En esta señal pone: Grandes Almacenes.}
{60000}{}{una señal}
{60001}{}{En esta señal pone: Mercado}
{60100}{}{una piscina de lodo}
{60101}{}{Parece muy poco saludable. Deberías ponerte un traje de baño blindado antes de sumergirte en ella.}
{60200}{}{una piscina de lodo}
{60201}{}{Parece muy poco saludable. Deberías ponerte un traje de baño blindado antes de sumergirte en ella.}
{60300}{}{una piscina de lodo}
{60301}{}{Parece muy poco saludable. Deberías ponerte un traje de baño blindado antes de sumergirte en ella.}
{60400}{}{una mesa}
{60401}{}{Una mesa de metal muy bonita.}
{60500}{}{una mesa}
{60501}{}{Una mesa de metal muy bonita.}
{60600}{}{una mesa}
{60601}{}{Una mesa de metal muy bonita.}
{60700}{}{una mesa}
{60701}{}{Una mesa de metal muy bonita.}
{60800}{}{una mesa}
{60801}{}{Esta mesa de metal no ha sido bien tratada. La oxidación es evidente.}
{60900}{}{una mesa}
{60901}{}{Una mesa de metal de buen aspecto, excepto por el óxido.}
{61000}{}{una mesa}
{61001}{}{Una mesa de metal de buen aspecto, excepto por el óxido.}
{61100}{}{una mesa}
{61101}{}{Una mesa de metal de buen aspecto, excepto por el óxido.}
{61200}{}{una hoguera}
{61201}{}{El fuego está encendido.}
{61300}{}{un espejo}
{61301}{}{Por un momento ves tu imagen reflejada.}
{61400}{}{un espejo}
{61401}{}{Por un momento ves tu imagen reflejada.}
{61500}{}{un fregadero}
{61501}{}{Un fregadero en perfecto estado de funcionamiento. Bonito y limpio.}
{61600}{}{el váter}
{61601}{}{Este váter está muy limpio y encima funciona.}
{61700}{}{el urinario}
{61701}{}{Este urinario funciona.}
{61800}{}{el váter}
{61801}{}{Si tuvieras un fetiche por los váteres, este sería uno bueno para usar. O para "usar".}
{61900}{}{un fregadero}
{61901}{}{Este fregadero está en perfectas condiciones.}
{62000}{}{el urinario}
{62001}{}{Este urinario está en perfectas condiciones.}
{62100}{}{una ducha}
{62101}{}{Una ducha de estilo militar. No es para gente humilde.}
{62200}{}{una ducha}
{62201}{}{Una ducha de estilo militar. No es para gente humilde.}
{62300}{}{una ducha}
{62301}{}{Una ducha de estilo militar. No es para gente humilde.}
{62400}{}{una ducha}
{62401}{}{Una ducha de estilo militar. No es para gente humilde.}
{62500}{}{una ducha}
{62501}{}{Una ducha de estilo militar. No es para gente humilde.}
{62600}{}{una ducha}
{62601}{}{Una ducha de estilo militar. No es para gente humilde.}
{62700}{}{Cama}
{62701}{}{Una litera de estructura reforzada.}
{62800}{}{Cama}
{62801}{}{Una litera de estructura reforzada.}
{62900}{}{Cama}
{62901}{}{Una litera de estructura reforzada.}
{63000}{}{Cama}
{63001}{}{Una litera de estructura reforzada.}
{63100}{}{Cama}
{63101}{}{Una litera de estructura reforzada.}
{63200}{}{un terminal}
{63201}{}{Una muy agradable estación.}
{63300}{}{un terminal}
{63301}{}{Una muy agradable estación.}
{63400}{}{una bandera}
{63401}{}{Esta bandera es el símbolo de los Niños de la Catedral.}
{63500}{}{una bandera}
{63501}{}{Esta bandera es el símbolo de los Niños de la Catedral.}
{63600}{}{una bandera}
{63601}{}{Esta bandera es el símbolo de los Niños de la Catedral.}
{63700}{}{Computadora}
{63701}{}{Un gran ordenador.}
{63800}{}{Computadora}
{63801}{}{Un gran ordenador.}
{63900}{}{Computadora}
{63901}{}{Un gran ordenador.}
{64000}{}{un terminal}
{64001}{}{El terminal de un gran ordenador.}
{64100}{}{el cadáver}
{64101}{}{Parece que esta persona ha tenido una muerte horrible.}
{64200}{}{el cadáver}
{64201}{}{Parece que esta persona ha tenido una muerte horrible.}
{64300}{}{el cadáver}
{64301}{}{Parece que esta persona ha tenido una muerte horrible.}
{64400}{}{el cadáver}
{64401}{}{Parece que esta persona ha tenido una muerte horrible.}
{64500}{}{Puerta}
{64501}{}{Esta puerta de barrotes es muy útil como puerta de celda.}
{64600}{}{Terminal de Acceso}
{64601}{}{Un dispositivo para manejar equipos de alta tecnología, tales como emisores de campos de fuerza.}
{64700}{}{Terminal de Acceso}
{64701}{}{Un dispositivo para manejar equipos de alta tecnología, tales como emisores de campos de fuerza.}
{64800}{}{una carretilla elevadora}
{64801}{}{La carretilla elevadora no funciona.}
{64900}{}{una carretilla elevadora}
{64901}{}{La carretilla elevadora no funciona.}
{65000}{}{el equipo}
{65001}{}{Algún tipo de equipo de alta tecnología.}
{65100}{}{una mesa de operaciones}
{65101}{}{Esta mesa está muy deteriorada. El sumidero en el centro de la mesa está obstruido.}
{65200}{}{una mesa de operaciones}
{65201}{}{Esta mesa está muy deteriorada.}
{65300}{}{Puerta}
{65301}{}{Esta valla tiene una barra que sube y baja.}
{65400}{}{Tubería}
{65401}{}{Estas grandes y oxidadas tuberías se usan para mover grandes cantidades de agua u otros líquidos.}
{65500}{}{Tubería}
{65501}{}{Estas grandes y oxidadas tuberías se usan para mover grandes cantidades de agua u otros líquidos.}
{65600}{}{un generador de energía}
{65601}{}{Un generador de energía eléctrica. Un modelo estándar de los de antes de la guerra.}
{65700}{}{Tanque}
{65701}{}{Un gran depósito de agua. Parece bien conservado, lo que es una ventaja.}
{65800}{}{Cabina de policía}
{65801}{}{Una cabina de policía del Reino Unido, de los años 60.}
{65900}{}{una mesa}
{65901}{}{Una mesa bonita. Hecha a mano y mucho más bonita que las que has visto antes.}
{66000}{}{una mesa}
{66001}{}{Una mesa bonita. Hecha a mano y mucho más bonita que las que has visto antes.}
{66100}{}{una mesa}
{66101}{}{Una mesa bonita. Hecha a mano y mucho más bonita que las que has visto antes.}
{66200}{}{Silla}
{66201}{}{Una silla bonita.}
{66300}{}{Silla}
{66301}{}{Una silla bonita.}
{66400}{}{Silla}
{66401}{}{Una silla bonita.}
{66500}{}{Silla}
{66501}{}{Una silla bonita.}
{66600}{}{Silla}
{66601}{}{Una silla bonita.}
{66700}{}{Silla}
{66701}{}{Una silla bonita.}
{66800}{}{Silla}
{66801}{}{Una silla bonita.}
{66900}{}{Silla}
{66901}{}{Una silla bonita.}
{67000}{}{Silla}
{67001}{}{Una silla bonita.}
{67100}{}{Silla}
{67101}{}{Una silla bonita.}
{67200}{}{Silla}
{67201}{}{Una silla bonita.}
{67300}{}{Silla}
{67301}{}{Una silla bonita.}
{67400}{}{Silla}
{67401}{}{Una silla bonita.}
{67500}{}{Silla}
{67501}{}{Una silla bonita.}
{67600}{}{Silla}
{67601}{}{Una silla bonita.}
{67700}{}{Silla}
{67701}{}{Una silla bonita.}
{67800}{}{Cama}
{67801}{}{Una cama bonita.}
{67900}{}{Cama}
{67901}{}{Una cama bonita.}
{68000}{}{Cama}
{68001}{}{Una cama bonita.}
{68100}{}{Cama}
{68101}{}{Una cama bonita.}
{68200}{}{una estufa}
{68201}{}{Una estufa de leña funcional.}
{68300}{}{una estufa}
{68301}{}{Una estufa de leña funcional.}
{68400}{}{una estufa}
{68401}{}{Una estufa de leña funcional.}
{68500}{}{una estufa}
{68501}{}{Una estufa de leña funcional.}
{68600}{}{un poste roto}
{68601}{}{La Hermandad del Acero ha caído.}
{68700}{}{una entrada destruida}
{68701}{}{Esta fue la entrada de la poderosa Hermandad del Acero - ahora solo otro edificio del yermo.}
{68800}{}{Rocas}
{68801}{}{Un montón grande de piedras. No se debe a una causa natural.}
{68900}{}{Rocas}
{68901}{}{Un montón grande de piedras. No se debe a una causa natural.}
{69000}{}{el váter}
{69001}{}{Un váter sucio pero muy útil. Se han colocado algunas hojas en el agujero para mitigar el olor.}
{69100}{}{Montaña}
{69101}{}{Las vertientes de esta montaña parecen bastante inaccesibles.}
{69200}{}{Montaña}
{69201}{}{Las vertientes de esta montaña parecen bastante inaccesibles.}
{69300}{}{Montaña}
{69301}{}{Las vertientes de esta montaña parecen bastante inaccesibles.}
{69400}{}{Montaña}
{69401}{}{Las vertientes de esta montaña parecen bastante inaccesibles.}
{69500}{}{Montaña}
{69501}{}{Las vertientes de esta montaña parecen bastante inaccesibles.}
{69600}{}{Montaña}
{69601}{}{Las vertientes de esta montaña parecen bastante inaccesibles.}
{69700}{}{una mezcla}
{69701}{}{Ves una sustancia viscosa, extraña y nociva.}
{69800}{}{una mezcla}
{69801}{}{Ves una sustancia viscosa, extraña y nociva.}
{69900}{}{una mezcla}
{69901}{}{Ves una sustancia viscosa, extraña y nociva.}
{70000}{}{una mezcla}
{70001}{}{Ves una sustancia viscosa, extraña y nociva.}
{70100}{}{una mezcla}
{70101}{}{Ves una sustancia viscosa, extraña y nociva.}
{70200}{}{una mezcla}
{70201}{}{Ves una sustancia viscosa, extraña y nociva.}
{70300}{}{una mezcla}
{70301}{}{Ves una sustancia viscosa, extraña y nociva.}
{70400}{}{una mezcla}
{70401}{}{Ves una sustancia viscosa, extraña y nociva.}
{70500}{}{una mezcla}
{70501}{}{Ves una sustancia viscosa, extraña y nociva.}
{70600}{}{una mezcla}
{70601}{}{Ves una sustancia viscosa, extraña y nociva.}
{70700}{}{una mezcla}
{70701}{}{Ves una sustancia viscosa, extraña y nociva.}
{70800}{}{una mezcla}
{70801}{}{Ves una sustancia viscosa, extraña y nociva.}
{70900}{}{una mezcla}
{70901}{}{Ves una sustancia viscosa, extraña y nociva.}
{71000}{}{una mezcla}
{71001}{}{Ves una sustancia viscosa, extraña y nociva.}
{71100}{}{una mezcla}
{71101}{}{Ves una sustancia viscosa, extraña y nociva.}
{71200}{}{una mezcla}
{71201}{}{Ves una sustancia viscosa, extraña y nociva.}
{71300}{}{una mezcla}
{71301}{}{Ves una sustancia viscosa, extraña y nociva.}
{71400}{}{una mezcla}
{71401}{}{Ves una sustancia viscosa, extraña y nociva.}
{71500}{}{una mezcla}
{71501}{}{Ves una sustancia viscosa, extraña y nociva.}
{71600}{}{una mezcla}
{71601}{}{Ves una sustancia viscosa, extraña y nociva.}
{71700}{}{una mezcla}
{71701}{}{Ves una sustancia viscosa, extraña y nociva.}
{71800}{}{una mezcla}
{71801}{}{Ves una sustancia viscosa, extraña y nociva.}
{71900}{}{una mezcla}
{71901}{}{Ves una sustancia viscosa, extraña y nociva.}
{72000}{}{una mezcla}
{72001}{}{Ves una sustancia viscosa, extraña y nociva.}
{72100}{}{una mezcla}
{72101}{}{Ves una sustancia viscosa, extraña y nociva.}
{72200}{}{una mezcla}
{72201}{}{Ves una sustancia viscosa, extraña y nociva.}
{72300}{}{una mezcla}
{72301}{}{Ves una sustancia viscosa, extraña y nociva.}
{72400}{}{una mezcla}
{72401}{}{Ves una sustancia viscosa, extraña y nociva.}
{72500}{}{una mezcla}
{72501}{}{Ves una sustancia viscosa, extraña y nociva.}
{72600}{}{una mezcla}
{72601}{}{Ves una sustancia viscosa, extraña y nociva.}
{72700}{}{una mezcla}
{72701}{}{Ves una sustancia viscosa, extraña y nociva.}
{72800}{}{una mezcla}
{72801}{}{Ves una sustancia viscosa, extraña y nociva.}
{72900}{}{una mezcla}
{72901}{}{Ves una sustancia viscosa, extraña y nociva.}
{73000}{}{una mezcla}
{73001}{}{Ves una sustancia viscosa, extraña y nociva.}
{73100}{}{una mezcla}
{73101}{}{Ves una sustancia viscosa, extraña y nociva.}
{73200}{}{una mezcla}
{73201}{}{Ves una sustancia viscosa, extraña y nociva.}
{73300}{}{una mezcla}
{73301}{}{Ves una sustancia viscosa, extraña y nociva.}
{73400}{}{una mezcla}
{73401}{}{Ves una sustancia viscosa, extraña y nociva.}
{73500}{}{una mezcla}
{73501}{}{Ves una sustancia viscosa, extraña y nociva.}
{73600}{}{una mezcla}
{73601}{}{Ves una sustancia viscosa, extraña y nociva.}
{73700}{}{una mezcla}
{73701}{}{Ves una sustancia viscosa, extraña y nociva.}
{73800}{}{una mezcla}
{73801}{}{Ves una sustancia viscosa, extraña y nociva.}
{73900}{}{una mezcla}
{73901}{}{Ves una sustancia viscosa, extraña y nociva.}
{74000}{}{una mezcla}
{74001}{}{Ves una sustancia viscosa, extraña y nociva.}
{74100}{}{una mezcla}
{74101}{}{Ves una sustancia viscosa, extraña y nociva.}
{74200}{}{una mezcla}
{74201}{}{Ves una sustancia viscosa, extraña y nociva.}
{74300}{}{una mezcla}
{74301}{}{Ves una sustancia viscosa, extraña y nociva.}
{74400}{}{una mezcla}
{74401}{}{Ves una sustancia viscosa, extraña y nociva.}
{74500}{}{una mezcla}
{74501}{}{Ves una sustancia viscosa, extraña y nociva.}
{74600}{}{una mezcla}
{74601}{}{Ves una sustancia viscosa, extraña y nociva.}
{74700}{}{una mezcla}
{74701}{}{Ves una sustancia viscosa, extraña y nociva.}
{74800}{}{una mezcla}
{74801}{}{Ves una sustancia viscosa, extraña y nociva.}
{74900}{}{Computadora}
{74901}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{75000}{}{Computadora}
{75001}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{75100}{}{Computadora}
{75101}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{75200}{}{Computadora}
{75201}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{75300}{}{Computadora}
{75301}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{75400}{}{Computadora}
{75401}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{75500}{}{Computadora}
{75501}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{75600}{}{Computadora}
{75601}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{75700}{}{Computadora}
{75701}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{75800}{}{Computadora}
{75801}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{75900}{}{Computadora}
{75901}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{76000}{}{Computadora}
{76001}{}{La cantidad de sustancia viscosa en este ordenador hace muy difícil el acceso.}
{76100}{}{unos monitores}
{76101}{}{No puedes leer nada en el monitor debido a la cantidad de sustancia viscosa que hay sobre las pantallas.}
{76200}{}{unos monitores}
{76201}{}{No puedes leer nada en el monitor debido a la cantidad de sustancia viscosa que hay sobre las pantallas.}
{76300}{}{unos monitores}
{76301}{}{No puedes leer nada en el monitor debido a la cantidad de sustancia viscosa que hay sobre las pantallas.}
{76400}{}{unos monitores}
{76401}{}{No puedes leer nada en el monitor debido a la cantidad de sustancia viscosa que hay sobre las pantallas.}
{76500}{}{el suelo}
{76501}{}{Jurarías que hay algo que se mueve en el suelo.}
{76600}{}{Pedestal}
{76601}{}{Parece que el pedestal está respirando lentamente.}
{76700}{}{el suelo}
{76800}{}{una bomba nuclear}
{76801}{}{Se trata de una bomba nuclear. Parece bastante peligroso sentarse ahí.}
{76900}{}{una base de apoyo}
{76901}{}{Esta base sirve de apoyo a la bomba nuclear situada encima de la misma.}
{77000}{}{Consola de Computadora}
{77001}{}{Este es un ordenador de acceso nuclear. El ordenador parece muy seguro. Hay una ranura para una llave de forma rara.}
{77100}{}{unos cables}
{77101}{}{Estos cables conectan la bomba al ordenador.}
{77200}{}{Silla}
{77201}{}{No hay nada raro en esta silla.}
{77300}{}{Silla}
{77301}{}{No hay nada raro en esta silla.}
{77400}{}{Silla}
{77401}{}{No hay nada raro en esta silla.}
{77500}{}{Silla}
{77501}{}{No hay nada raro en esta silla.}
{77600}{}{Silla}
{77601}{}{No hay nada raro en esta silla.}
{77700}{}{Silla}
{77701}{}{No hay nada raro en esta silla.}
{77800}{}{Silla}
{77801}{}{No hay nada raro en esta silla.}
{77900}{}{Silla}
{77901}{}{No hay nada raro en esta silla.}
{78000}{}{el pilar}
{78001}{}{Un pilar de soporte.}
{78100}{}{el pilar}
{78101}{}{Un pilar de soporte.}
{78200}{}{el pilar}
{78201}{}{Un pilar de soporte.}
{78300}{}{el pilar}
{78301}{}{Un pilar de soporte.}
{78400}{}{Cama}
{78401}{}{Esta cama está en muy malas condiciones.}
{78500}{}{Cama}
{78501}{}{Esta cama está en muy malas condiciones.}
{78600}{}{Cama}
{78601}{}{Esta cama está en muy malas condiciones.}
{78700}{}{Cama}
{78701}{}{Esta cama está en muy malas condiciones.}
{78800}{}{unos monitores}
{78801}{}{Estos monitores están rotos y no funcionan.}
{78900}{}{unos monitores}
{78901}{}{Estos monitores están rotos y no funcionan.}
{79000}{}{unos monitores}
{79001}{}{Estos monitores están rotos y no funcionan.}
{79100}{}{unos monitores}
{79101}{}{Estos monitores están rotos y no funcionan.}
{79200}{}{Ventilación}
{79201}{}{Sale muy poco aire fresco de este respiradero.}
{79300}{}{Ventilación}
{79301}{}{Casi no sale aire fresco de este respiradero.}
{79400}{}{Ventilación}
{79401}{}{No sale aire fresco de este respiradero.}
{79500}{}{Ventilación}
{79501}{}{Solo sale una pequeña bocanada de aire fresco de este respiradero.}
{79600}{}{una mesa}
{79601}{}{No hay nada extraño en esta mesa, excepto que está casi destruida.}
{79700}{}{una mesa}
{79701}{}{Esta mesa ha sido seriamente dañada.}
{79800}{}{una mesa}
{79801}{}{Esta mesa está en muy malas condiciones.}
{79900}{}{una mesa}
{79901}{}{No hay motivo para examinar esta mesa.}
{80000}{}{unos monitores}
{80001}{}{Las pantallas en este grupo de monitores han sido destruidas.}
{80100}{}{unos monitores}
{80101}{}{Las pantallas en este grupo de monitores han sido dañadas y hay que arreglarlas.}
{80200}{}{Monitor}
{80201}{}{La pantalla del monitor ha sido golpeada y destruida.}
{80300}{}{Monitor}
{80301}{}{Este monitor no sirve para nada con la pantalla rota.}
{80400}{}{Computadora}
{80401}{}{Este ordenador está roto.}
{80500}{}{Computadora}
{80501}{}{Este ordenador está roto.}
{80600}{}{Computadora}
{80601}{}{Este ordenador está roto.}
{80700}{}{Silla}
{80701}{}{Esta silla está desvencijada.}
{80800}{}{Silla}
{80801}{}{Esta silla está desvencijada.}
{80900}{}{Silla}
{80901}{}{Esta silla está desvencijada.}
{81000}{}{Silla}
{81001}{}{Esta silla está desvencijada.}
{81100}{}{Ventilación}
{81101}{}{Este respiradero ha sido dañado y necesita una reparación.}
{81200}{}{Ventilación}
{81201}{}{Este respiradero está muy dañado y no puede ser reparado.}
{81300}{}{Ventilación}
{81301}{}{Este respiradero no funciona.}
{81400}{}{Computadora}
{81401}{}{Parece que este ordenador funciona mal.}
{81500}{}{Computadora}
{81501}{}{Parece que este ordenador funciona mal.}
{81600}{}{Monitor}
{81601}{}{El monitor apenas funciona.}
{81700}{}{Monitor}
{81701}{}{El monitor apenas funciona.}
{81800}{}{Computadora}
{81801}{}{El ordenador no funciona.}
{81900}{}{Computadora}
{81901}{}{El ordenador no funciona.}
{82000}{}{Monitor}
{82001}{}{El monitor no funciona.}
{82100}{}{Monitor}
{82101}{}{El monitor no funciona.}
{82200}{}{el portal}
{82201}{}{Parece un portal muy bonito. Sostiene muy bien la puerta.}
{82300}{}{unos monitores}
{82301}{}{Los monitores están en buen estado.}
{82400}{}{unos monitores}
{82401}{}{Los monitores están en buen estado.}
{82500}{}{Muro}
{82600}{}{una puerta de banco}
{82601}{}{A very sturdy bank vault door. The door looks very secure.}
{82700}{}{Luz}
{82701}{}{Una luz de seguridad.}
{82800}{}{Luz}
{82801}{}{Una luz de seguridad.}
{82900}{}{el pilar}
{82901}{}{Este pilar es la pieza clave de la historia de Arenas Sombrías. Cuenta historias que inspiran en la gente esperanza y paz.}
{83000}{}{un receptáculo de robots}
{83001}{}{Es un sistema de recarga de robots. Cuando no están en funcionamiento, los robots vienen aquí para recargarse.}
{83100}{}{un receptáculo de robots}
{83101}{}{Es un sistema de recarga de robots. Cuando no están en funcionamiento, los robots vienen aquí para recargarse.}
{83200}{}{un receptáculo de robots}
{83201}{}{Es un sistema de recarga de robots. Cuando no están en funcionamiento, los robots vienen aquí para recargarse.}
{83300}{}{un receptáculo de robots}
{83301}{}{Es un sistema de recarga de robots. Cuando no están en funcionamiento, los robots vienen aquí para recargarse.}
{83400}{}{un receptáculo de robots}
{83401}{}{Es un sistema de recarga de robots. Cuando no están en funcionamiento, los robots vienen aquí para recargarse.}
{83500}{}{una máquina}
{83501}{}{Esta máquina tiene algo que ver con los servicios de robótica. No parece muy interesante.}
{83600}{}{una máquina}
{83601}{}{Esta máquina tiene algo que ver con los servicios de robótica. No parece muy interesante.}
{83700}{}{una banda}
{83800}{}{una banda}
{83900}{}{una banda}
{84000}{}{una banda}
{84100}{}{una banda}
{84200}{}{una banda}
{84300}{}{una banda}
{84400}{}{una banda}
{84500}{}{una banda}
{84600}{}{una banda}
{84700}{}{una banda}
{84800}{}{Puerta}
{84801}{}{Una puerta de madera muy normal.}
{84900}{}{Puerta}
{84901}{}{Una puerta de madera muy normal.}
{85000}{}{Puerta}
{85001}{}{Una puerta de madera muy normal.}
{85100}{}{una señal}
{85101}{}{Esta señal pertenece a la Compañía de Crédito Amistoso.}
{85200}{}{Emblema}
{85201}{}{Este emblema es utilizado por los Seguidores del Apocalipsis.}
{85300}{}{una mesa de operaciones}
{85301}{}{Parece una mesa de análisis médicos.}
{85400}{}{una señal}
{85401}{}{Es un rótulo de neón del Halcón Maltés.}
{85500}{}{Grafiti}
{85600}{}{Grafiti}
{85700}{}{Grafiti}
{85800}{}{Grafiti}
{85900}{}{Grafiti}
{86000}{}{Grafiti}
{86100}{}{Grafiti}
{86200}{}{Grafiti}
{86300}{}{Grafiti}
{86400}{}{Grafiti}
{86500}{}{Grafiti}
{86600}{}{Grafiti}
{86700}{}{Grafiti}
{86800}{}{Grafiti}
{86900}{}{una señal}
{86901}{}{Pone: ARMAS. Puede que vendan armas ahí.}
{87000}{}{una señal}
{87001}{}{En la señal pone: Policía}
{87100}{}{una señal}
{87101}{}{Esta es la señal de los Comerciantes de Ultramar.}
{87200}{}{una señal}
{87201}{}{En la señal pone: Pistoleros.}
{87300}{}{una señal}
{87301}{}{Esta es la señal de la compañía de comercio Caravana Carmesí.}
{87400}{}{una señal}
{87401}{}{En la señal pone: Hospital. Es bueno saberlo.}
{87500}{}{una señal}
{87501}{}{Esta es la señal de la Posada.}
{87600}{}{una señal}
{87601}{}{En esta señal pone: Mercado de coches usados de Bob.}
{87700}{}{una señal}
{87701}{}{Esta es la señal de los Mercaderes de Agua, una compañía de comercio del Eje.}
{87800}{}{una cáscara de huevo}
{87801}{}{Partes de un huevo roto de Garra Mortal.}
{87900}{}{una cáscara de huevo}
{87901}{}{Partes de un huevo roto de Garra Mortal.}
{88000}{}{una cáscara de huevo}
{88001}{}{Partes de un huevo roto de Garra Mortal.}
{88100}{}{una cáscara de huevo}
{88101}{}{Partes de un huevo roto de Garra Mortal.}
{88200}{}{una cáscara de huevo}
{88201}{}{Partes de un huevo roto de Garra Mortal.}
{88300}{}{una cáscara de huevo}
{88301}{}{Partes de un huevo roto de Garra Mortal.}
{88400}{}{una cáscara de huevo}
{88401}{}{Partes de un huevo roto de Garra Mortal.}
{88500}{}{una cáscara de huevo}
{88501}{}{Partes de un huevo roto de Garra Mortal.}
{88600}{}{Poste de luz}
{88601}{}{Una farola. Todo parece estar en orden.}
{88700}{}{una señal}
{88701}{}{En la señal pone: Motel.}
{88800}{}{unos champiñones}
{88801}{}{Esta mesa de cultivo ha sido abonada con estiércol y los champiñones crecen alegremente.}
{88900}{}{unos champiñones}
{88901}{}{Esta mesa de cultivo ha sido abonada con estiércol y los champiñones crecen alegremente.}
{89000}{}{un esqueleto}
{89100}{}{una señal}
{89101}{}{En esta señal pone: Cárcel.}
{89200}{}{una señal}
{89201}{}{Esta es la señal del bar Fosa Común.}
{89300}{}{una señal}
{89301}{}{Un anuncio de cuchillas fabricadas por los Navajas.}
{89400}{}{una ducha}
{89401}{}{Una ducha normal.}
{89500}{}{una ducha}
{89501}{}{Una ducha normal.}
{89600}{}{una señal}
{89601}{}{Esta es la señal de la Compañía de Crédito Amistoso.}
{89700}{}{una señal}
{89701}{}{Esta es la señal de la Compañía de Crédito Amistoso.}
{89800}{}{un póster}
{89801}{}{Es un póster de una película de terror de antes de la guerra.}
{89900}{}{un póster}
{89901}{}{Es un póster de una película de terror de antes de la guerra.}
{90000}{}{Barra}
{90001}{}{Hay una urna en este bar. La urna parece un poco deteriorada, pero puede ser valiosa.}
{90100}{}{el hueco del ascensor}
{90101}{}{El hueco tiene una cuerda que cuelga desde arriba.}
{90200}{}{el hueco del ascensor}
{90201}{}{El hueco tiene una cuerda que cuelga desde arriba.}
{90300}{}{una cama médica}
{90301}{}{Esta cama tiene un mecanismo que muestra el progreso de los pacientes.}
{90400}{}{la bomba de agua}
{90401}{}{Es una pieza de maquinaria que proyecta agua desde el subsuelo.}
{90500}{}{una cama médica}
{90501}{}{Esta cama tiene un mecanismo que muestra el progreso de los pacientes.}
{90600}{}{unas piezas de la Armadura de Energía}
{90601}{}{Son piezas de un traje de Armadura de Energía.}
{90700}{}{Luz}
{90701}{}{Esta luz de seguridad está parpadeando en un rojo brillante.}
{90800}{}{Luz}
{90801}{}{Esta luz de seguridad está parpadeando en un rojo brillante.}
