{200}{}{Caverna, Puerta del Refugio}
{201}{}{Entrance, Medical}
{202}{}{Aposentos}
{203}{}{Biblioteca, Suministros, Comando}
{210}{}{Old Shack}
{211}{}{Cavern Entrance}
{212}{}{Aposentos}
{213}{}{Biblioteca, Suministros, Comando}
{220}{}{Entrance, Town Hall}
{221}{}{Campo de Cultivo}
{222}{}{Corral de Brahmines}
{223}{}{Cuevas de los Escorpiones Rad}
{230}{}{Entrance, Hospital}
{231}{}{General Store, Hotel}
{232}{}{Casino, Bar}
{240}{}{Campo base}
{250}{}{Hotel de la perdición}
{251}{}{Sala de los Difuntos}
{252}{}{El almacén de agua}
{260}{}{Entrance, Caravaners}
{261}{}{Downtown, Market, Casino}
{262}{}{Heights, Hightower}
{263}{}{Ciudad Antigua}
{264}{}{Water Merchants, Church}
{265}{}{Deathclaw Lair}
{270}{}{Entrada}
{271}{}{Nivel 1}
{272}{}{Nivel 2}
{273}{}{Nivel 3}
{274}{}{Nivel 4}
{280}{}{Entrada}
{281}{}{Fortaleza Nivel 1}
{282}{}{Fortaleza Nivel 2}
{283}{}{Tanques Nivel 1}
{284}{}{Tanques Nivel 2}
{290}{}{Cráter}
{291}{}{Nivel 1}
{292}{}{Nivel 2}
{293}{}{Nivel 3}
{294}{}{Nivel 4}
{295}{}{Nivel 5}
{296}{}{Nivel 6}
{300}{}{Adytum}
{301}{}{Centro de la ciudad}
{302}{}{Biblioteca}
{303}{}{Fortaleza}
{304}{}{Almacén}
{310}{}{Entrada}
{311}{}{Interior}
{500}{}{You have stopped the Super Mutant threat.}
{501}{}{Ruinas}
{1000}{}{Desierto}
{1001}{}{Montañas}
{1002}{}{Ciudad}
{1003}{}{Costa}
{1004}{}{Desconocido}
