{1000}{}{¡No me enrolé para esto!}
{1001}{}{¡No me pagan lo suficiente para esto!}
{1002}{}{¡Retrocede!}
{1003}{}{¡Reagrupamiento!}
{1004}{}{¡No pienso morir por esto!}
{1005}{}{Ya tengo suficiente}
{1006}{}{Voy a darte una lección}
{1007}{}{¡Acabas de cometer un grave error!}
{1008}{}{¡Por aquí no nos gustan los tipos como tú!}
{1009}{}{No me gusta la gente como tú}
{1010}{}{Ese fue tu último error}
{1011}{}{La sangre resuelve lo que las palabras no pueden}
{1012}{}{Cómete esto}
{1013}{}{¡Piensa rápido!}
{1014}{}{¡Ahora es cuando mueres!}
{1015}{}{Ya van dos hoy...}
{1016}{}{Siempre disfruto de un buen entrenamiento}
{1017}{}{Estás a punto de morir.}
{1018}{}{Veamos lo duro que eres...}
{1019}{}{Punk}
{1020}{}{¡Al ataque!}
{1021}{}{Veamos si te gusta esto}
{1022}{}{Demasiado lento}
{1023}{}{Hace años que hago esto, mocoso}
{1024}{}{No eres lo bastante bueno}
{1025}{}{Ese fue tu último error}
{1026}{}{Aficionado}
{1027}{}{¿Eso es todo lo que sabes hacer?}
{1028}{}{¡Ah! Hijo de puta}
{1029}{}{Te mataré por esto}
{1030}{}{Creo que podría tener una conmoción cerebral}
{1031}{}{Eso no ha estado bien}
{1032}{}{¡Maldita sea, tengo el brazo destrozado!}
{1033}{}{¡Mi brazo!}
{1034}{}{¡AHH! Creo que está roto...}
{1035}{}{Puto listillo}
{1036}{}{¡Mi brazo!}
{1037}{}{¡Oh!}
{1038}{}{Oh...}
{1039}{}{[Jadea fuertemente]}
{1040}{}{¡Mis costillas!}
{1041}{}{¡Mi rodilla!}
{1042}{}{¡Me las pagarás por esto!}
{1043}{}{No siento mi pierna}
{1044}{}{¡Joder, me la has roto!}
{1045}{}{Espero no quedarme cojo}
{1046}{}{¡Mi rodilla!}
{1047}{}{¡No veo!}
{1048}{}{¡Mi ojo!}
{1049}{}{¡Mierda! al menos tengo otro}
{1050}{}{¡Ohhhhh, la ingle!}
{1051}{}{Joder, buen tiro}
{1052}{}{Peleas sucio}
{1053}{}{¡Urp!}
{1054}{}{¡Uf!}
{1055}{}{Eso duele}
{1100}{}{¡Refuerzos!}
{1101}{}{La discreción es la mejor parte del valor}
{1102}{}{¡Un médico!}
{1103}{}{¡Retirada! ¡Retirada!}
{1104}{}{¡Retrocede! ¡Retrocede!}
{1105}{}{Puedes haber ganado la batalla...}
{1106}{}{¡Hora de poner mi entrenamiento a prueba!}
{1107}{}{Voy a acabar contigo}
{1108}{}{Voy a enseñarte un poco de educación}
{1109}{}{¡Eres historia!}
{1110}{}{¡Al ataque!}
{1111}{}{¡Enterremos a este perdedor!}
{1112}{}{¡Toma esto!}
{1113}{}{¡Ya te tengo!}
{1114}{}{¡Ahora es cuando mueres!}
{1115}{}{¿Qué te parece esto?}
{1116}{}{¿Ya pagaste tu ataúd?}
{1117}{}{No deberías empezar lo que no puedes terminar}
{1118}{}{¡Será mejor que reces a los dioses!}
{1119}{}{¡Es la hora de morir!}
{1120}{}{Esto va a ser fácil}
{1121}{}{Te veré en el infierno}
{1122}{}{¡Ja! ¿En serio?}
{1123}{}{¿Eso es todo lo que sabes hacer?}
{1124}{}{¡Vamos perdedor! ¡Lucha!}
{1125}{}{La próxima vez intenta apuntar}
{1126}{}{Civil}
{1127}{}{Típico}
{1128}{}{Uuufff... no puedo pensar con claridad}
{1129}{}{¡Mi cara!}
{1130}{}{¡Me has roto la nariz!}
{1131}{}{¡Me has roto el brazo!}
{1132}{}{¡No voy a parar por un brazo destrozado!}
{1133}{}{Te lo haré pagar}
{1134}{}{¡Me lo has roto!}
{1135}{}{De todas formas no necesitaba ese codo}
{1136}{}{Menos mal que soy un zurdo}
{1137}{}{¡Bah! No me ha dolido nada}
{1138}{}{¡Uck!}
{1139}{}{¡Vas a arrepentirte!}
{1140}{}{¡Uff! Me las vas a pagar}
{1141}{}{Has tenido suerte}
{1142}{}{¡Me las pagarás por esto!}
{1143}{}{¡No voy a parar por una herida así!}
{1144}{}{¡Oh, mi pierna!}
{1145}{}{Quédate con mi pierna, que yo mientras te quito la vida}
{1146}{}{¡Pagarás por esto!}
{1147}{}{¡Estoy ciego!}
{1148}{}{¡Me arden los ojos!}
{1149}{}{¡No veo!}
{1150}{}{¡Ohh, la ingle!}
{1151}{}{¡Ack!}
{1152}{}{¡Uf!}
{1153}{}{No... puedo... respirar...}
{1154}{}{Hijo de puta}
{1155}{}{Mamón}
{1200}{}{¡Hay que largarse de aquí!}
{1201}{}{Volveré...}
{1202}{}{¡No podrás matarme hoy!}
{1203}{}{¡Hasta luego, mocoso!}
{1204}{}{¡Todavía no he dicho la última palabra!}
{1205}{}{¡Pagarás por esto... luego!}
{1206}{}{¡Eres historia!}
{1207}{}{Carne fresca...}
{1208}{}{Bailaré sobre tu tumba}
{1209}{}{¡Eh, todo el mundo! ¡A practicar la puntería!}
{1210}{}{¡Sangra, sangra, sangra!}
{1211}{}{Voy a divertirme con esto...}
{1212}{}{Voy a vender tu cuerpo a Doc Mórbid}
{1213}{}{No te preocupe gritar suplicando clemencia...}
{1214}{}{Esta es la mejor parte...}
{1215}{}{Tienes los zapatos desatados}
{1216}{}{Vas a ser la comida de los perros}
{1217}{}{No deberías empezar lo que no puedes terminar}
{1218}{}{Espero que mueras lentamente}
{1219}{}{Solo quedará uno de nosotros}
{1220}{}{¡Muere!}
{1221}{}{Me como a los novatos para desayunar}
{1222}{}{Serás comida para mi iguana}
{1223}{}{Mi sonrisa será lo último que veras}
{1224}{}{Este es mi trabajo favorito}
{1225}{}{Eres un payaso}
{1226}{}{¿Eso es todo lo que sabes hacer?}
{1227}{}{Lo que sea}
{1228}{}{Guau, esa estuvo cerca}
{1229}{}{¡Muy lento!}
{1230}{}{Desgraciado}
{1231}{}{¡En la cara no!}
{1232}{}{¡Ow!}
{1233}{}{¡Me has roto la nariz!}
{1234}{}{¡Oh, mi brazo!}
{1235}{}{¡Me has roto el brazo!}
{1236}{}{Puedo conseguir recolocarlo}
{1237}{}{¡No voy a pararme por un brazo destrozado!}
{1238}{}{¡Me has roto el brazo!}
{1239}{}{No siento mis dedos...}
{1240}{}{¡Ay, mis costillas!}
{1241}{}{Ese fue tu tiro de regalo. Hora de morir}
{1242}{}{Haré que me las pagues por esto}
{1243}{}{¡Mi pierna!}
{1244}{}{¡Me las pagarás por esto!}
{1245}{}{Puedo matarte aun estando cojo}
{1246}{}{¡Mi pierna!}
{1247}{}{¡Agh!}
{1248}{}{Eso no me parará, colega}
{1249}{}{¡Agh! ¡Mis ojos!}
{1250}{}{¡Mi ojo! ¡Me las vas a pagar!}
{1251}{}{¡Joder! Eres historia}
{1252}{}{¡Ohhhhh, la ingle!}
{1253}{}{¡Ohh! Tengo que aprender ese movimiento...}
{1254}{}{Directo en los huevos...}
{1255}{}{¡Urp!}
{1256}{}{A mi chica no le va gustar esto}
{1257}{}{¡Oh! ¡Te mataré por esto!}
{1300}{}{¿No has oído a alguien llamándome?}
{1301}{}{}
{1302}{}{¡Ayuda!}
{1303}{}{¡Aaaaahhhh!}
{1304}{}{¡Hay que huir!}
{1305}{}{}
{1306}{}{Haré que parezcas una galleta machacada}
{1307}{}{¡Mira! ¡Tienes los cordones desatados!}
{1308}{}{Espera a que te coja...}
{1309}{}{}
{1310}{}{Voy a darte una paliza descomunal}
{1311}{}{}
{1312}{}{¡Toma esto!}
{1313}{}{¡Ya te tengo!}
{1314}{}{¡Ya te tengo!}
{1315}{}{¿Qué te parece esto?}
{1316}{}{Cómete esto}
{1317}{}{Esta será una experiencia que te cambiará la vida}
{1318}{}{No voy a arrepentirme de esto, ¿verdad?}
{1319}{}{}
{1320}{}{}
{1321}{}{}
{1322}{}{¡Ja, no me has dado!}
{1323}{}{¡No, no!}
{1324}{}{¡Ja!}
{1325}{}{¡No, no!}
{1326}{}{¡Qué petardo!}
{1327}{}{No puedes tocarme}
{1328}{}{¡Cuidado con el pelo!}
{1329}{}{¡Miz dientez! ¡He pezdido un diente!}
{1330}{}{¡Miz dientez, miz dientez!}
{1331}{}{¡Oh, mi brazo!}
{1332}{}{¡Ow!}
{1333}{}{¡Ay, quita!}
{1334}{}{¡Oh, mi brazo!}
{1335}{}{¡Ow!}
{1336}{}{¡Ay, quita!}
{1337}{}{¡No quiero ser zurdo!}
{1338}{}{¡Oh!}
{1339}{}{Eso no ha estado bien}
{1340}{}{Puedes arrepentirte de eso, yo lo hice}
{1341}{}{Creo que me voy a desmayar}
{1342}{}{¿Qué te crees que soy? ¿Un saco de boxeo?}
{1343}{}{No eres muy amable}
{1344}{}{¡Oh, mi pierna!}
{1345}{}{¡Ah, no lo hagas!}
{1346}{}{!}
{1347}{}{¡Oh, mi pierna!}
{1348}{}{¡Ay! ¡Eres malo!}
{1349}{}{}
{1350}{}{¿Por qué está tan oscuro?}
{1351}{}{¿A dónde ha ido todo el mundo?}
{1352}{}{¡Ahh, mi retina!}
{1353}{}{¡Ohhhhh, la ingle!}
{1354}{}{¡Mi ingle es la ingle de fuego!}
{1355}{}{¡Mi ingle es la ingle de fuego!}
{1356}{}{No... puedo... respirar...}
{1357}{}{}
{1358}{}{Me duele, me duele...}
{1400}{}{¡Fuera!}
{1401}{}{¡Adiós!}
{1402}{}{¡Aaaaahhhh!}
{1403}{}{A la mierda}
{1404}{}{Me largo}
{1405}{}{Nos vemos}
{1406}{}{Te voy a joder}
{1407}{}{¡Eres historia!}
{1408}{}{¡El juego ha terminado!}
{1409}{}{Alguien se muere}
{1410}{}{Dame si puedes}
{1411}{}{¡Vámonos!}
{1412}{}{¡Toma esto!}
{1413}{}{¡Muere!}
{1414}{}{Desgraciado}
{1415}{}{Punk}
{1416}{}{Cómete esto, puta}
{1417}{}{¡Espero que te duela!}
{1418}{}{Reza algo}
{1419}{}{No dudes ahora}
{1420}{}{Te enterraré}
{1421}{}{¡Estás muerto!}
{1422}{}{¡No me has dado!}
{1423}{}{No me causa buena impresión}
{1424}{}{Patético}
{1425}{}{Eres un lento}
{1426}{}{No sirves para nada}
{1427}{}{¡Ja!}
{1428}{}{¡Joder, eso duele!}
{1429}{}{¡Mi cara!}
{1430}{}{¡Ay! Mi nariz...}
{1431}{}{¡Ow!}
{1432}{}{¡Ow! ¡Mi brazo!}
{1433}{}{¡Ay! ¡Me lo has roto!}
{1434}{}{Otra vez no...}
{1435}{}{¡Mi brazo!}
{1436}{}{Hora de vengarse}
{1437}{}{¡Ow!}
{1438}{}{¡Ay!}
{1439}{}{¡Oh!}
{1440}{}{[Jadea fuertemente]}
{1441}{}{¡Uf!}
{1442}{}{¡Ugh!}
{1443}{}{¡Ow!}
{1444}{}{¡Oh! ¡Mi rodilla!}
{1445}{}{¡Oh! ¡Mi pierna!}
{1446}{}{¡Mierda!}
{1447}{}{¡Mi pierna!}
{1448}{}{Mi rodilla...}
{1449}{}{¡Estoy ciego!}
{1450}{}{¡No veo!}
{1451}{}{¡Mi ojo!}
{1452}{}{¡Mi ingle!}
{1453}{}{¡Ayyy!}
{1454}{}{Joder, cómo duele}
{1455}{}{¡Uf!}
{1456}{}{¡Urp!}
{1457}{}{¡Ohhhhh, como escuece!}
{1500}{}{¡Me largo de aquí! Es hora de comer}
{1501}{}{¡Me voy!}
{1502}{}{¡Vaya, he escogido al oponente equivocado!}
{1503}{}{Puede que no fuera una buena idea}
{1504}{}{¡Alguien podía resultar herido aquí!}
{1505}{}{Solo bromeaba}
{1506}{}{Ha llegado el momento de la verdad}
{1507}{}{El trabajo de un guardia nunca termina}
{1508}{}{Tu cara puede quedar mejor en pedazos}
{1509}{}{Otra vez no. ¡Las municiones son muy caras!}
{1510}{}{Espero que no me encasqueten los deberes de enterrador}
{1511}{}{¿Quién te crees que eres?}
{1512}{}{Ante ti tienes a todo un profesional}
{1513}{}{No deberías haberte levantado esta mañana}
{1514}{}{¡Te vas a echar una siestecita!}
{1515}{}{A ver si luchas mejor que tu abuela}
{1516}{}{Y ahora te tumbo para que descanses...}
{1517}{}{Como quitarle un caramelo a un niño...}
{1518}{}{Solo sobreviven los más fuertes y tú no estás en forma}
{1519}{}{Preferiría estar navegando}
{1520}{}{¡Cae muerto!}
{1521}{}{¡Seré lo último que verás!}
{1522}{}{No soy tan fácil}
{1523}{}{Ahhhh. ¿Que no me has dado?}
{1524}{}{Sigue intentándolo. ¡Algún día lo conseguirás!}
{1525}{}{Muy buena, idiota}
{1526}{}{¿Quieres que me quede quieto para ti?}
{1527}{}{Estoy casi estupefacto}
{1528}{}{Ahora no podré escuchar tus gritos}
{1529}{}{¡Me retumba la cabeza!}
{1530}{}{¡Auh! ¡Mi oído! Oh, espera, me sobra una.}
{1531}{}{¡Auh, me gustaba ese brazo!}
{1532}{}{¡Me has roto el brazo!}
{1533}{}{Auh... me desarmas...}
{1534}{}{¡Esa era mi mano favorita!}
{1535}{}{¡Está roto, como mi corazón! Te odio}
{1536}{}{Auh... me desarmas...}
{1537}{}{Debes creer que eres muy bueno}
{1538}{}{¿Eso es lo mejor que puedes hacer? Ehh}
{1539}{}{¡Uf! ¡Puta!}
{1540}{}{¿Quieres venir aquí y volver a intentarlo?}
{1541}{}{Supongo que cuando crezcas querrás ser tan bueno como yo}
{1542}{}{¡Al menos no fue tan feo como tu cara!}
{1543}{}{¡Auch! ¡Maldita sea!}
{1544}{}{¿Dónde está mi pie?}
{1545}{}{Es solo un rasguño... y algunos huesos rotos}
{1546}{}{De todas formas, no me hacía falta esa rodilla}
{1547}{}{Ahora solo me queda UN pie izquierdo}
{1548}{}{¿A dónde ha ido mi rodilla esta vez?}
{1549}{}{Genial, ahora me tendrá que crecer una nueva. Imbécil.}
{1550}{}{¡Estoy ciego!}
{1551}{}{Ahora no tengo que ver tu horrible cara}
{1552}{}{Aún puedo olerte}
{1553}{}{¡Mi ingle, mi ingle!}
{1554}{}{Estás haciendo de esto algo personal}
{1555}{}{Se acabaron los niños}
{1556}{}{¡Aquí se acaba mi vida sexual!}
{1557}{}{¡Oh, qué dolor!}
{1558}{}{¡Ay! ¡A esto lo llamo dolor!}
{1600}{}{¡Eh, podría morir aquí fuera!}
{1601}{}{Puede que no fuera una buena idea}
{1602}{}{¡Abandono! Tú ganas}
{1603}{}{¡Ayuda! ¡Tengo miedo!}
{1604}{}{¡Aaaaahhhh!}
{1605}{}{¡Dejadme salir de aquí!}
{1606}{}{¡Por fin un poco de acción!}
{1607}{}{¡No deberías meterte conmigo!}
{1608}{}{¡Ahora podré probarme en batalla!}
{1609}{}{Esto es todo... ¿no?}
{1610}{}{Esta vez quitaré el seguro}
{1611}{}{¡Esto podría ser divertido!}
{1612}{}{¡Toma esto!}
{1613}{}{¡Ya te tengo!}
{1614}{}{¡Esto es increíble!}
{1615}{}{¿Qué te parece esto?}
{1616}{}{¡Muere, saqueador imbécil!}
{1617}{}{¡Monstruo mutante!}
{1618}{}{¡Al ataque!}
{1619}{}{¡Deja de moverte!}
{1620}{}{No grites que me asustas}
{1621}{}{No sangres demasiado}
{1622}{}{¡Ja, no me has dado!}
{1623}{}{¡Has fallado!}
{1624}{}{Hábil movimiento, ¿eh?}
{1625}{}{¿Eso es todo lo que sabes hacer?}
{1626}{}{¡Eh! ¡Eso podía haber dolido!}
{1627}{}{¡Ten cuidado, esa estuvo cerca!}
{1628}{}{¿Podemos tomarnos un descanso?}
{1629}{}{¡Mi cara! ¡Qué has hecho!}
{1630}{}{¡Aggghhh! ¡Mi cara! ¡No! ¡No!}
{1631}{}{¿En serio? Ahora no podré pelear}
{1632}{}{¡Mi brazo, mi brazo!}
{1633}{}{¡Mierda, no!}
{1634}{}{¡Auh, ese era mi mano de disparar!}
{1635}{}{Mi brazo, ¿qué le has hecho?}
{1636}{}{¡Aggghhh!}
{1637}{}{¡Ow!}
{1638}{}{Maldita sea. Eso sí que duele}
{1639}{}{¡Pupa, pupa, pupa!}
{1640}{}{No estoy seguro de que me gusta esto...}
{1641}{}{Ten calma conmigo, solo soy un principiante}
{1642}{}{¡Uf!}
{1643}{}{¡Ack!}
{1644}{}{¡Auch! ¡Eso duele!}
{1645}{}{¡Venga ya, la necesitaba!}
{1646}{}{Mi pierna, ¿qué has hecho?}
{1647}{}{¡Aggghhh!}
{1648}{}{¡Oh, mi pierna!}
{1649}{}{¡Mi pierna! No...}
{1650}{}{La necesito para huir...}
{1651}{}{¡No veo!}
{1652}{}{¡Mis ojos!}
{1653}{}{¡Socorro!}
{1654}{}{¡Ay, la ingle!}
{1655}{}{Oooooo, tú, pequeño y sucio...}
{1656}{}{¡Urp!}
{1657}{}{¿Son éstas mis entrañas?}
{1658}{}{No... puedo... respirar...}
{1659}{}{¡Maldita sea, cómo me duele!}
{1700}{}{¡No voy a morir por esto!}
{1701}{}{¡El trabajo no merece la pena!}
{1702}{}{¡Me largo!}
{1703}{}{Ahí va mi repu...}
{1704}{}{No pienso poner mi carne en el asador}
{1705}{}{Apartadme de este cabeza hueca}
{1706}{}{¡Otro gamberro no!}
{1707}{}{¡Acabas de cruzar la línea!}
{1708}{}{¡No vas a salir de esta con eso aquí!}
{1709}{}{¡No delante de mis narices, colega!}
{1710}{}{¡Voy a liquidarte!}
{1711}{}{[pone una mirada] Otra vez no...}
{1712}{}{¡Esto es lo que les hago a los alborotadores!}
{1713}{}{Apaga las luces...}
{1714}{}{Así aprenderás a no causar problemas}
{1715}{}{¡Voy a explorarte!}
{1716}{}{Haré que te duela}
{1717}{}{Veamos lo duro que eres...}
{1718}{}{Crees que eres un tipo peligroso, ¿eh?}
{1719}{}{No deberías empezar lo que no puedes terminar}
{1720}{}{¿Esperas salir con eso?}
{1721}{}{Me desayuno a las nenitas como tú}
{1722}{}{Haces que mi trabajo sea fácil}
{1723}{}{No tienes astucia, tío}
{1724}{}{Tío, ¡no tienes músculos!}
{1725}{}{¿Eso es todo lo que sabes hacer?}
{1726}{}{No esperabas darme, ¿verdad?}
{1727}{}{Vamos, mariquita. ¡Venga, lucha!}
{1728}{}{¡Me has roto la nariz!}
{1729}{}{¡Ah! ¡Maldito seas!}
{1730}{}{¡Maldita sea! ¡Cómo me duele!}
{1731}{}{¡Oh, mi brazo!}
{1732}{}{¡Voy a congelarte por eso!}
{1733}{}{Eso ha sido un error}
{1734}{}{Tú, hijoputa}
{1735}{}{¡Voy a machacarte por esto!}
{1736}{}{Que más da, puedo matarte sin él}
{1737}{}{¡Otra pierna destrozada no!}
{1738}{}{¡Ow!}
{1739}{}{Eso ha sido un error}
{1740}{}{¡Ah! ¿Intentas despedazarme?}
{1741}{}{Muy mal, colega}
{1742}{}{Me duele...}
{1743}{}{¡No veo! Eso ha sido un golpe bajo}
{1744}{}{¡Ahh! Lo has conseguido, me has cabreado}
{1745}{}{No necesito verte para retorcerte el pescuezo!}
{1746}{}{¡Ohhh! ¡En las pelotas!}
{1747}{}{Hazlo de nuevo y acabo contigo}
{1748}{}{¡Mierda! ¡Eso pica!}
{1749}{}{¡Ah! ¡Mis partes! No mola}
{1750}{}{Voy a necesitar algo de hielo}
{1751}{}{¡Ups! Buena puntería...}
{1800}{}{¡Piedad!}
{1801}{}{¡Que alguien me ayude!}
{1802}{}{¡Por favor, para!}
{1803}{}{¡Ayuda!}
{1804}{}{¡Aaaaahhhh!}
{1805}{}{[llora]}
{1806}{}{Mmm, eh, ¡para!}
{1807}{}{No me gustan los tipos como tú...}
{1808}{}{Realmente esperaba que no tuviéramos que llegar a esto...}
{1809}{}{No quiero hacerme daño}
{1810}{}{Supongo que tengo que defenderme}
{1811}{}{Aquí viene un don nadie}
{1812}{}{¡Toma esto!}
{1813}{}{¡No deberías haber empezado esto!}
{1814}{}{¡Te lo has buscado!}
{1815}{}{¿Qué te parece esto?}
{1816}{}{Es tu culpa}
{1817}{}{¡Eres una bestia!}
{1818}{}{¡No quiero hacerlo!}
{1819}{}{Quédate quieto un segundo}
{1820}{}{No quería pelear, pero...}
{1821}{}{¡Eres un sinvergüenza!}
{1822}{}{¡Mierda, eso estuvo cerca!}
{1823}{}{¡No me has dado!}
{1824}{}{¡Esa podía haber dolido!}
{1825}{}{¡Guau! ¡Sigo vivo!}
{1826}{}{¡Eh! ¡Eso podía haber dolido!}
{1827}{}{Bien, bien, nada está sangrando}
{1828}{}{¡Mi cara, mi cara!}
{1829}{}{¡Joder! ¡Me duele!}
{1830}{}{¡Oh Dios!}
{1831}{}{¡Oh, no!}
{1832}{}{¡Ow!}
{1833}{}{¡Me has roto el brazo!}
{1834}{}{Mi brazo...}
{1835}{}{¡Aaaayyy!}
{1836}{}{¡Dios mío, mi brazo!}
{1837}{}{¡Ay, eso ha dolido!}
{1838}{}{Creo que me voy a desmayar}
{1839}{}{¡Ay!}
{1840}{}{Voy a necesitar tomar el aire}
{1841}{}{¡Me duele!}
{1842}{}{¡Déjame en paz!}
{1843}{}{¡Ooo, me duele!}
{1844}{}{¿Por qué? ¿POR QUÉ?}
{1845}{}{Sip, definitivamente rota.}
{1846}{}{¿Ahora cómo se supone que voy a caminar?}
{1847}{}{¡Aayy, ahora mi pierna es inútil!}
{1848}{}{¡Mi rodilla!}
{1849}{}{¡Aaaarrrrggghhh!}
{1850}{}{¡Estoy ciego! ¡Dios mío, estoy ciego!}
{1851}{}{¡La cara! ¡Mis ojos! ¡Aaaah!}
{1852}{}{¡Mis ojos! ¿¡Qué le has hecho a mis ojos!?}
{1853}{}{¡Oooooh, la ingle! Oooooh...}
{1854}{}{¡Ay... quema!}
{1855}{}{Todo... se está... oscureciendo...}
{1856}{}{¡Oooh, aaah...!}
{1857}{}{No... puedo... respirar...}
{1858}{}{Me duele, me duele...}
{1900}{}{Me largo por donde he venido}
{1901}{}{¡Volveré!}
{1902}{}{¡Hasta luego, mocoso!}
{1903}{}{Esto es divertido, pero me voy}
{1904}{}{¡Pagarás por esto... luego!}
{1905}{}{¡Hagámoslo otra vez!}
{1906}{}{¡Voy a tirarte de las orejas!}
{1907}{}{¡Carne fresca! Delicioso.}
{1908}{}{¡Me has dado el día!}
{1909}{}{¡Vas a ser mi zorra!}
{1910}{}{Eres jodida historia, colega}
{1911}{}{¡Voy a ajustarte las cuentas!}
{1912}{}{Deja de gritar, es molesto}
{1913}{}{Espero que no le tengas miedo a la sangre}
{1914}{}{Por favor, no me supliques. Has de tener una muerte digna}
{1915}{}{Espero que no mueras demasiado rápido}
{1916}{}{¿Un último deseo?}
{1917}{}{¡Toma esto!}
{1918}{}{¡Muere, muere, muere, muere!}
{1919}{}{¿Quieres ver tus entrañas?}
{1920}{}{Vamos a abrirte un poquito...}
{1921}{}{Eres comida para perros, amigo}
{1922}{}{Ni siquiera me has rozado}
{1923}{}{Ja, ja, muy buena}
{1924}{}{Vamos, mocoso. ¡Pelea un poquito!}
{1925}{}{¿Eso es todo lo que sabes hacer?}
{1926}{}{Esto va a ser más fácil de lo que creía}
{1927}{}{¡Guau! ¿Cómo es que sigues vivo?}
{1928}{}{¡Ésta va a ser una bonita cicatriz!}
{1929}{}{Estoy empezando a enfadarme}
{1930}{}{Hazlo otra vez, cerdo}
{1931}{}{¡Me has herido!}
{1932}{}{Buen tiro. El mío será mejor}
{1933}{}{Me has roto el brazo, pero yo te romperé el cuello}
{1934}{}{¿Así que así es como quieres jugar?}
{1935}{}{Es solo un arañazo...}
{1936}{}{Me rompes el brazo, pues yo te rompo el cuello...}
{1937}{}{De acuerdo perra, vas a morir}
{1938}{}{¡Uff! Voy a retorcerte el pescuezo por esto...}
{1939}{}{Una herida superficial, a diferencia de la tuya}
{1940}{}{¡Uff! ¿Es eso lo mejor que sabes hacer?}
{1941}{}{¡Me encanta el sonido de las costillas al romperse!}
{1942}{}{Duele, pero aún estoy cabreado}
{1943}{}{¡Ahh! Ven y vuelve a intentarlo}
{1944}{}{Me encanta el sonido de huesos crujientes}
{1945}{}{Nop, sigue pegado}
{1946}{}{Creo que me la has roto. ¡Muere!}
{1947}{}{Me encanta el sonido de huesos crujientes}
{1948}{}{No importa, aún puedo acabar contigo}
{1949}{}{Duele un poco, pero no lo suficiente}
{1950}{}{Eh, estoy ciego. Vaya cosa}
{1951}{}{No veo. Así esto será justo}
{1952}{}{¡Mis ojos! ¡Zorra!}
{1953}{}{¡Ahh, mi material!}
{1954}{}{Eso ha sido un golpe bajo}
{1955}{}{Inténtalo... de nuevo... [jadea fuertemente]}
{1956}{}{¡Suficiente, estas jodidamente muerto!}
{1957}{}{Conque así es como quieres que juguemos}
{1958}{}{¡Ack!}
{2000}{}{¡Ataca a otro, por favor!}
{2001}{}{¡Ten compasión!}
{2002}{}{¡Que alguien me ayude!}
{2003}{}{¡Por favor, para!}
{2004}{}{Vaya, yo no hice nada!}
{2005}{}{¡No voy a morir por esto!}
{2006}{}{Espera a que te coja...}
{2007}{}{¿Por qué estás haciendo esto?}
{2008}{}{¡Eh, tú!}
{2009}{}{No eres bienvenido aquí}
{2010}{}{Nadie va a tomar este lugar...}
{2011}{}{¿Quién te crees que eres?}
{2012}{}{Necesitaba algo de entrenamiento}
{2013}{}{¿Dónde está esa maldita pala?}
{2014}{}{¡Esto es lo que le hacemos a la gentuza!}
{2015}{}{¡Monstruo mutante!}
{2016}{}{No me mataras sin pelear antes}
{2017}{}{Vas a ser la comida de los perros}
{2018}{}{¡Así aprenderás!}
{2019}{}{Bien. Te lo has buscado.}
{2020}{}{¡Serás animal!}
{2021}{}{Allá donde fueres...}
{2022}{}{Debe ser mi día de suerte}
{2023}{}{Un brahmin es más rápido que tú}
{2024}{}{¡Guau! Esa estuvo cerca}
{2025}{}{No has tirado, ¿eh?}
{2026}{}{Gracias a Dios}
{2027}{}{¡Has fallado!}
{2028}{}{¡Maldita sea, cómo pica!}
{2029}{}{¡Aggghhh!}
{2030}{}{¡Ooohhh, mierda!}
{2031}{}{¡Ahhh! ¡Mi brazo!}
{2032}{}{¡Auh, auh ,auh!}
{2033}{}{¡Venga ya, lo necesitaba!}
{2034}{}{¡Ahhh! ¡Mi brazo!}
{2035}{}{¡Nooooo...!}
{2036}{}{¡Creo que me lo has roto!}
{2037}{}{¡Maldición!}
{2038}{}{Eso me ha dolido mucho...}
{2039}{}{¡Agh!}
{2040}{}{¡Ay!}
{2041}{}{¡Ugh!}
{2042}{}{¡Uf!}
{2043}{}{¡Ow!}
{2044}{}{¡Ahhh! ¡Mi pierna!}
{2045}{}{Necesito una silla}
{2046}{}{¡Mi pierna!}
{2047}{}{¡Ahhh! ¡Mi pierna!}
{2048}{}{Fantástico, ahí va mi trabajo}
{2049}{}{¡Au! ¡No!}
{2050}{}{¡Ahhh! ¡Estoy ciego!}
{2051}{}{¡El infierno te maldiga!}
{2052}{}{¡Mi ojo!}
{2053}{}{Auuu}
{2054}{}{¡Ohhhhhhhhh!}
{2055}{}{No... puedo... respirar...}
{2056}{}{Oh no...}
{2057}{}{Me duele, me duele...}
{2058}{}{¡Maldición!}
{2100}{}{¡Me voy!}
{2101}{}{¡Piedad! ¡Misericordia!}
{2102}{}{¡Por favor, para!}
{2103}{}{¡Ayuda!}
{2104}{}{¡Vete!}
{2105}{}{Dejémoslo en tablas}
{2106}{}{¿No podemos hablarlo?}
{2107}{}{¿De verdad que tenemos que hacerlo?}
{2108}{}{La verdad es que no quiero hacer esto}
{2109}{}{Voy a tener que pegarte}
{2110}{}{¿Estás seguro de que es una buena idea?}
{2111}{}{Espero no acabar herido}
{2112}{}{No estoy de humor para esto}
{2113}{}{¡Te lo has buscado!}
{2114}{}{No estoy de humor para peleas, pero...}
{2115}{}{¡Yo no quería que pasara esto!}
{2116}{}{¿Por qué empezaste esto?}
{2117}{}{¡No quiero hacerlo!}
{2118}{}{No creas que es algo personal...}
{2119}{}{Espero no herirte de gravedad}
{2120}{}{¿Te das cuenta de que tú empezaste esto?}
{2121}{}{¡Es en defensa propia!}
{2122}{}{¡Guau!}
{2123}{}{Realmente no tienes por qué hacer esto}
{2124}{}{¡Eh! ¡Eso podía haber dolido!}
{2125}{}{No deberíamos estar luchando}
{2126}{}{La violencia no resuelve los problemas}
{2127}{}{Tu corazón no está en esto}
{2128}{}{¡En la cara no!}
{2129}{}{¡Aaaah, mi cara!}
{2130}{}{¡Oh! ¡Mi oído!}
{2131}{}{¡Por favor, para!}
{2132}{}{¡Ay!}
{2133}{}{¡Me has roto el brazo!}
{2134}{}{¿Qué has hecho?}
{2135}{}{¡Ugh!}
{2136}{}{¡Me has roto el brazo!}
{2137}{}{¡No quiero ser un lisiado!}
{2138}{}{¡Mi rodilla!}
{2139}{}{¡Oh! ¡Tengo la pierna destrozada!}
{2140}{}{Eso va a dejar marca}
{2141}{}{¿Era necesario?}
{2142}{}{¡Oh! ¡Tengo la pierna destrozada!}
{2143}{}{¡Estoy ciego!}
{2144}{}{¡Lloro lágrimas de sangre!}
{2145}{}{Oh dios, el dolor...}
{2146}{}{¡Ohhhhh, la ingle!}
{2147}{}{Necesito una siesta}
{2148}{}{¿Ya acabaste?}
{2149}{}{No... puedo... respirar...}
{2150}{}{¡Mis partes!}
{2151}{}{¡Oooh! Necesito tumbarme...}
{2200}{}{¡El Maestro te encontrará!}
{2201}{}{¡No me matarás!}
{2202}{}{¡Volveré!}
{2203}{}{¡Mis amigos te cogerán por mí!}
{2204}{}{¡Tengo amigos que me ayudarán!}
{2205}{}{¡Somos los Elegidos! ¡Morirás pronto!}
{2206}{}{¡Se acerca el momento de tu muerte!}
{2207}{}{¡Te ha llegado la hora!}
{2208}{}{¡Las armas humanas no me hacen daño!}
{2209}{}{¡Vas a sufrir, mucho!}
{2210}{}{¡Machaco cuerpos con mis dedos!}
{2211}{}{¡Somos el futuro y nos reímos de la humanidad!}
{2212}{}{¡Este es el fin!}
{2213}{}{¡Nadie te salvará ahora!}
{2214}{}{¡Eres impuro!}
{2215}{}{¡Ahora tendrás una muerte a fuego lento!}
{2216}{}{¡Hoy entrarás al infierno!}
{2217}{}{Sonrío mientras mato}
{2218}{}{¡Tu sangre es mi vino!}
{2219}{}{¡Ahora es cuando mueres!}
{2220}{}{¡Así es como vas a morir!}
{2221}{}{¡Sufre, humano!}
{2222}{}{¿Por qué luchas?}
{2223}{}{¿¡Eso es lo mejor que ofrecen los humanos!?}
{2224}{}{¡No tienes poder!}
{2225}{}{¡Me desternillas!}
{2226}{}{¿Ha sido eso un ataque?}
{2227}{}{¡No eres nadie!}
{2228}{}{¡Ahhhh! ¡Mi cara!}
{2229}{}{¡Mi cara! ¡Sufrirás!}
{2230}{}{¡Ahhh! ¡Voy a despedazarte!}
{2231}{}{¡Aaaagh! Te aplastaré}
{2232}{}{¿A eso lo llamas dolor? ¡Me das risa!}
{2233}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{2234}{}{¡No volverás a hacerlo!}
{2235}{}{¿A eso lo llamas dolor? ¡Me das risa!}
{2236}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{2237}{}{¡Sigo en pie!}
{2238}{}{¡Serás convertido o quemado!}
{2239}{}{¡Eso ha sido un error por tu parte!}
{2240}{}{¡Argh, inténtalo de nuevo!}
{2241}{}{¡Grrrr! Ahora sangrarás}
{2242}{}{¡Ja, ja, ja! ¡Ha eso lo llamas dolor!}
{2243}{}{¡Aah! ¡Me haces enfadar!}
{2244}{}{¡Aaah! Mi pierna. Ven aquí...}
{2245}{}{¿A eso lo llamas dolor? ¡Me das risa!}
{2246}{}{¡Aaah! ¡Voy a quebrarte como si fueras una ramita!}
{2247}{}{¡Mi pierna no se rompe con facilidad!}
{2248}{}{¿A eso lo llamas dolor? ¡Ja!}
{2249}{}{¡Ahhh! ¡Te retorceré el cuello por esto!}
{2250}{}{¡Ahhhgh! ¡Humano miserable! ¡Estoy ciego!}
{2251}{}{¡Ahhh! ¡Qué dolor! ¡Qué has hecho!}
{2252}{}{¡Ahhh! ¡Te torturaré durante días!}
{2253}{}{¡Eso es debilidad humana!}
{2254}{}{¡No puedes herirme ahí!}
{2255}{}{¡Eres un humano estúpido!}
{2256}{}{¿Por qué me atacas ahí?}
{2257}{}{¡Tu muerte será dolorosa, humano!}
{2258}{}{Morirás por ello...}
{2300}{}{¡Retroceded, retroceded! ¡Reagrupaos!}
{2301}{}{¡El Maestro te destruirá por esto!}
{2302}{}{¡Esto no ha terminado! Conquistaremos todo}
{2303}{}{¡La venganza del Maestro caerá sobre ti!}
{2304}{}{¡Traeré refuerzos!}
{2305}{}{Otro día me divertiré con tu corazón}
{2306}{}{Tu muerte es algo inminente}
{2307}{}{¡Has enfurecido a tus superiores, por eso tendrás que morir!}
{2308}{}{¡Vengo por mis enemigos, esgrimiendo la Llama Sagrada!}
{2309}{}{¡Aquellos que se opongan a la Unidad serán dejados atrás!}
{2310}{}{¡Muerte a los enemigos del Maestro!}
{2311}{}{¡Somos el futuro y vosotros sois historia!}
{2312}{}{¡Este es el fin!}
{2313}{}{¡Ni hombre ni dios alguno podrá salvarte ahora!}
{2314}{}{¡Bienvenido a tu tumba!}
{2315}{}{¡Este es el toque del Maestro!}
{2316}{}{¡Hoy entrarás al infierno!}
{2317}{}{Morirás en mis manos}
{2318}{}{En el nombre del Maestro, ¡muere!}
{2319}{}{¡Qué caiga el soplo de la muerte!}
{2320}{}{¡Te quemaré con la Llama Sagrada!}
{2321}{}{¡Sufre, humano!}
{2322}{}{¡Das pena! ¿Cómo te atreves a luchar?}
{2323}{}{¿Eso es lo mejor que la humanidad puede ofrecer?}
{2324}{}{¡Tu ataque es tan débil como tu espíritu!}
{2325}{}{Ese fue tu último error}
{2326}{}{¡El Maestro me protege de sus enemigos!}
{2327}{}{No puedes herir a los Elegidos}
{2328}{}{¡Eso no ha sido nada, te enseñaré lo que es el dolor!}
{2329}{}{¡Vas a sufrir por esto!}
{2330}{}{¡Aah! ¡Te haré pedacitos!}
{2331}{}{¡Morirás hecho pedazos!}
{2332}{}{¡No soy tan fácil de vencer!}
{2333}{}{¡Aaah! Te romperé todos los huesos por esto}
{2334}{}{¡Vosotros, los humanos, sois débiles!}
{2335}{}{¡Aaah! ¡Me las pagaras!}
{2336}{}{No vivirás para arrepentirte}
{2337}{}{¡Aah! ¡Muere!}
{2338}{}{¡Pufff!}
{2339}{}{¡Maestro!}
{2340}{}{Me has humillado...}
{2341}{}{¡No es suficiente!}
{2342}{}{¡Grrr!}
{2343}{}{¡Ahhh! ¡Mi pierna!}
{2344}{}{¡No soy tan fácil de vencer!}
{2345}{}{¡Voy a despedazarte por eso!}
{2346}{}{¡Ahhh! ¡Mi pierna!}
{2347}{}{¡Hará falta más que eso para derribarme!}
{2348}{}{¡Voy a aplastarte por eso!}
{2349}{}{¡Aaah! ¡Humano miserable! ¡Me has dejado ciego!}
{2350}{}{¡Ahhh! ¡Qué dolor! ¡Qué has hecho!}
{2351}{}{¡Aaah! ¡Te has ganado una vida de agonía por esto!}
{2352}{}{¡No voy a compartir la debilidad contigo, humano!}
{2353}{}{¡Soy mucho más fuerte que tú!}
{2354}{}{¡Vaya táctica más patética, humano!}
{2355}{}{¡El Maestro me protege, humano!}
{2356}{}{¡Tu muerte será cada vez más dolorosa!}
{2357}{}{¡Uff! Quizás debería probar tus puntos débiles}
{2400}{}{¡Maestro! ¡Por qué me abandonas!}
{2401}{}{¡El Maestro me vengará!}
{2402}{}{¡Maestro, perdóname, pero debo huir!}
{2403}{}{¿No te da miedo el castigo merecido?}
{2404}{}{¡Llama Sagrada, protégeme!}
{2405}{}{¡Ayúdame, Maestro, ayúdame!}
{2406}{}{¡Los Enemigos del Maestro deben quemarse en la Llama Sagrada!}
{2407}{}{¡Los Enemigos del Maestro deben morir!}
{2408}{}{¡La Unidad prevalecerá!}
{2409}{}{¡La sangre de los Niños será vengada!}
{2410}{}{¡La Paz ha de alimentarse con la sangre de los enemigos!}
{2411}{}{¡La Unidad o la Muerte!}
{2412}{}{No corras, somos tus amigos}
{2413}{}{¡Muere en nombre del Maestro!}
{2414}{}{¡Mira la Llama Sagrada!}
{2415}{}{¡Besa el fuego, toca la tumba!}
{2416}{}{¡Unidad!}
{2417}{}{¡Nadie detendrá la causa de la Paz!}
{2418}{}{¡No vas a detener la Unidad!}
{2419}{}{¡Por la Unidad!}
{2420}{}{¡Maestro, bendíceme!}
{2421}{}{¡Quémate en el Fuego Sagrado!}
{2422}{}{¡El Maestro me protege!}
{2423}{}{¡Mientras rece no podrás herirme!}
{2424}{}{¡Gracias Maestro!}
{2425}{}{¡La misericordia del Maestro es infinita!}
{2426}{}{¡Estoy protegido por la Llama Sagrada!}
{2427}{}{No puedes hacer daño a los Niños}
{2428}{}{¡Aaah! ¿¡Qué me ha dado!?}
{2429}{}{¡Maestro, protégeme!}
{2430}{}{¡Uf!}
{2431}{}{¡¡Mi brazo!!}
{2432}{}{La Unidad curará mis heridas...}
{2433}{}{¡Maestro! ¡Qué me han hecho!}
{2434}{}{¡Oh, mi brazo!}
{2435}{}{El Maestro curará mis heridas...}
{2436}{}{Te quitaré el doble de lo que tú me has quitado}
{2437}{}{¡Uf!}
{2438}{}{¡Ack!}
{2439}{}{¡Maestro, protégeme!}
{2440}{}{¡Maestro, véngame!}
{2441}{}{¡Gulp!}
{2442}{}{¡Oh, mi pierna!}
{2443}{}{¡Me has roto la pierna!}
{2444}{}{¡Maestro! ¡Qué me han hecho!}
{2445}{}{¡Mi pierna!}
{2446}{}{¡Me lo has roto!}
{2447}{}{¡Maestro! ¿Puedes hacer crecer extremidades? }
{2448}{}{¡Maestro, estoy ciego!}
{2449}{}{¡Maestro, los ojos, me queman!}
{2450}{}{¡Maestro, no veo!}
{2451}{}{¡Ohhhhh, la ingle!}
{2452}{}{¡Maestro!}
{2453}{}{¡Maestro, protégeme del dolor!}
{2454}{}{No... puedo... respirar...}
{2455}{}{¡Maestro, nuestros enemigos son crueles!}
{2456}{}{Maestro, deberías haberme avisado}
{2500}{}{¡Por qué me has abandonado!}
{2501}{}{¡Seré vengado!}
{2502}{}{¡Perdóname, pero debo huir!}
{2503}{}{¿No te da miedo el castigo merecido?}
{2504}{}{¡Llama Sagrada, protégeme!}
{2505}{}{¡Llama Sagrada, guía mi huida!}
{2506}{}{¡Nuestros enemigos deben quemarse en la Llama Sagrada!}
{2507}{}{¡Nuestros enemigos deben morir!}
{2508}{}{¡La Unidad prevalecerá!}
{2509}{}{¡La sangre de los Niños será vengada!}
{2510}{}{¡La Paz ha de alimentarse con la sangre de los enemigos!}
{2511}{}{La Llama Sagrada y la Unidad están sobre ti}
{2512}{}{¡Muere!}
{2513}{}{¡Muere en nombre de la Llama!}
{2514}{}{¡Mira la Llama Sagrada!}
{2515}{}{En nombre de la Paz, ¡muere!}
{2516}{}{¡Unidad!}
{2517}{}{¡Nadie detendrá la causa de la Paz!}
{2518}{}{¡Pagano!}
{2519}{}{¡No corras, somos tus amigos!}
{2520}{}{¡Maestro, bendíceme!}
{2521}{}{¡Arde en el Fuego Sagrado, pagano!}
{2522}{}{¡El Maestro me protege!}
{2523}{}{¡No podrás herirme mientras rece a la Llama Sagrada!}
{2524}{}{¡Tu dios es falso!}
{2525}{}{¡Tu mal se derrota a sí mismo!}
{2526}{}{¡Estoy protegido por la Llama Sagrada!}
{2527}{}{No puedes hacer daño a los Niños}
{2528}{}{¡Aaah! ¿Qué me ha dado?}
{2529}{}{¡Maestro, protégeme!}
{2530}{}{¡Ow!}
{2531}{}{¡Oh, mi brazo!}
{2532}{}{¡Me has roto el brazo!}
{2533}{}{¡¿Qué me has hecho?!}
{2534}{}{¡No! ¡Maestro!}
{2535}{}{¡La venganza será mía!}
{2536}{}{¡Pecador!}
{2537}{}{¡Auch! ¡Eso duele!}
{2538}{}{¡JODER!}
{2539}{}{¡Oh, oh, me duele!}
{2540}{}{¡Ay!}
{2541}{}{¡Oh!}
{2542}{}{¡Uf!}
{2543}{}{¡Maestro! ¡Quema!}
{2544}{}{¡Me las pagarás por esto!}
{2545}{}{¡Qué me has hecho!}
{2546}{}{¡Oh, mi pierna!}
{2547}{}{¡Me has roto la pierna!}
{2548}{}{¡¡Maldición!!}
{2549}{}{¡No veo!}
{2550}{}{¡Mis ojos!}
{2551}{}{¡Me he quedado ciego por mis pecados!}
{2552}{}{¡Ohhhhh, la ingle!}
{2553}{}{¡Ohhh, eres un verdadero demonio!}
{2554}{}{Llama Sagrada, ¡protege mi semilla!}
{2555}{}{¡El Maestro obra de maneras misteriosas!}
{2556}{}{No... puedo... respirar...}
{2557}{}{¡Nuestros enemigos son crueles!}
{2600}{}{¡La Iglesia te cogerá!}
{2601}{}{¡La Iglesia puede cuidar de sí misma!}
{2602}{}{¡Ayuda!}
{2603}{}{Que le den, hay demasiado ruido}
{2604}{}{Algún otro mariquita se encargará de ti}
{2605}{}{¡No voy a morir por esto!}
{2606}{}{No delante de mis narices...}
{2607}{}{¡Enterremos a este matón!}
{2608}{}{¡Es la hora de morir!}
{2609}{}{¡No tienes permiso para estar aquí!}
{2610}{}{Es hora de deshacernos de la basura...}
{2611}{}{Pagarás por tus "pecados"...}
{2612}{}{¡Toma esto!}
{2613}{}{¡Chiflado!}
{2614}{}{¡Y ahora, muere!}
{2615}{}{Vamos, ¡a rodar, amigo!}
{2616}{}{Desearás que te hubiéramos lavado el cerebro}
{2617}{}{Voy a darte por todas partes}
{2618}{}{Hora de morir...}
{2619}{}{Hora de hacer la "Unidad" con mi "Llama Sagrada"}
{2620}{}{¡Besa mi Llama Sagrada, amigo!}
{2621}{}{¡Chúpate esto!}
{2622}{}{¡Ja, no me has dado!}
{2623}{}{¡Vaya un patán!}
{2624}{}{¡Ja, no me has dado!}
{2625}{}{¡Eres incluso peor perdedor que los zombis!}
{2626}{}{¿Alguien te ha enseñado a apuntar?}
{2627}{}{Ja, ja, no te hagas daño}
{2628}{}{¡Ugh!}
{2629}{}{¡Uf!}
{2630}{}{¡Maldita sea! ¡Cómo me duele!}
{2631}{}{¡Oh, mi brazo!}
{2632}{}{¡Me las vas a pagar por esa!}
{2633}{}{¡Te romperé los dos brazos por esto!}
{2634}{}{¡Mi brazo! ¿¡Qué le has hecho a mi brazo!?}
{2635}{}{Eres peor que estos jodidos zombis}
{2636}{}{Ven aquí y repítelo, bastardo}
{2637}{}{¡Oooohhh, mi pierna!}
{2638}{}{¡Me las vas a pagar por esa!}
{2639}{}{¡Mierdecilla! ¡Voy por ti!}
{2640}{}{¡Oh, mi pierna!}
{2641}{}{¡Esa me la pagas!}
{2642}{}{¡Ow!}
{2643}{}{¡Voy a ponerte en tu sitio por esto!}
{2644}{}{¡Mi ojo! ¡Me las vas a pagar!}
{2645}{}{¡Ese ha sido un golpe bajo!}
{2646}{}{¡Oh, me has dado en los mismísimos!}
{2647}{}{¡Maldita sea, cómo me duele!}
{2648}{}{¡Maldito chupapollas! ¡Mierda! ¡JODER!}
{2649}{}{¡Oh, maldita sea!}
{2650}{}{¡Hijo de...!}
{2651}{}{¡No me enseñaste la tuya antes!}
{2700}{}{Esta batalla es innecesaria. ¡Lucha!}
{2701}{}{¡Seré vengado!}
{2702}{}{¡Tu triunfo durará poco!}
{2703}{}{No derrotarás a la Unidad. ¡Unidad!}
{2704}{}{¡Mis siervos me protegerán!}
{2705}{}{¡Esperanza! ¡Debo tener esperanza!}
{2706}{}{Tus pecados serán ahora castigados. ¡Castigados!}
{2707}{}{¡Mis enemigos deben morir! Muere. ¡Muere!}
{2708}{}{¡La Unidad prevalecerá! ¡Prevalecerá!}
{2709}{}{¡No te permitiremos que destruyas nuestro mundo!}
{2710}{}{¡El futuro ha de ser preservado! ¡Preservadlo!}
{2711}{}{¡A mí la Unidad o la Muerte! Unidad. ¡Muerte!}
{2712}{}{¡Muere!}
{2713}{}{Serás totalmente destruida. ¡Destruido!}
{2714}{}{Has sellado tu destrucción}
{2715}{}{¡Pagarás por lo que has hecho!}
{2716}{}{No derrotarás a la Unidad. ¡Unidad!}
{2717}{}{¡Nadie detendrá la causa de la paz! ¡Paz!}
{2718}{}{Solo te espera el fuego. ¡Fuego!}
{2719}{}{Éste será tu epitafio. ¡Epitafio!}
{2720}{}{No eres nadie. Nadie}
{2721}{}{Este es el fin de tu existencia. Fin. ¡Fin!}
{2722}{}{¡Tus esfuerzos son inútiles! ¡Inútiles!}
{2723}{}{¡No prevalecerás frente a mí! ¡Prevalecerme! ¡A mí!}
{2724}{}{Has vuelto a fallar, humano. ¡Humano!}
{2725}{}{¡Tu mal se vuelve contra ti! Mal. ¡Mal!}
{2726}{}{No sobrevivirás. ¡No sobrevivirás!}
{2727}{}{Tu acción es inadecuada. ¡Inadecuada!}
{2728}{}{Herida en la cabeza. Seré vengado. ¡Vengado!}
{2729}{}{Ha sido un dolor muy desagradable. Dolor. ¡Dolor!}
{2730}{}{Eso no me incapacitará ¡Incapacitarme! ¡A mí!}
{2731}{}{¿Crees que puedes herirme ahí? ¡A mí! ¡AHÍ!}
{2732}{}{Herida menor, humano. Menor. ¡Menor!}
{2733}{}{Un dolor ligeramente desagradable. ¡Dolor!}
{2734}{}{Ningún daño orgánico o en los circuitos que no pueda ser reparado. ¡Daño!}
{2735}{}{¡Muere! ¡Muere! Muere}
{2736}{}{Sistema comprometido, compensando...}
{2737}{}{Alcanzados los sistemas, registrando daños menores}
{2738}{}{Sistemas alcanzados, sistemas alcanzados, sistemas alcanzados}
{2800}{}{¡Hay que largarse de aquí!}
{2801}{}{Volveré...}
{2802}{}{¡No podrás matarme hoy!}
{2803}{}{¡Hasta luego, amigo!}
{2804}{}{¡Todavía no has oído la última palabra!}
{2805}{}{¡Pagarás por esto... luego!}
{2806}{}{¡Eres historia!}
{2807}{}{Carne fresca...}
{2808}{}{Ah, ya está aquí la cena}
{2809}{}{Sesos...}
{2810}{}{Voy a cavar tu tumba...}
{2811}{}{Espero dejar intacta tu cabeza...}
{2812}{}{¡Ese es tu número!}
{2813}{}{No te preocupe gritar suplicando clemencia...}
{2814}{}{Voy a divertirme}
{2815}{}{¡Ohhh, eso va a doler!}
{2816}{}{¡Toma normalito!}
{2817}{}{¡Voy a comerme tu hígado!}
{2818}{}{Espero que mueras lentamente}
{2819}{}{¡Hora de comer!}
{2820}{}{¡Muere!}
{2821}{}{Me como a los mocosos como tú para desayunar y almorzar. Y cenar.}
{2822}{}{¡No puedes herirme!}
{2823}{}{Normales. Qué típico.}
{2824}{}{Oh, mira, casi me das}
{2825}{}{¡Has fallado, tío!}
{2826}{}{¡No puedes matar a quien eres incapaz de alcanzar!}
{2827}{}{¡Muy lento!}
{2828}{}{Oh, mi cara bonita}
{2829}{}{¡Ay, mi cabeza!}
{2830}{}{¡Uf!}
{2831}{}{¡Mi mano!}
{2832}{}{¡Ow!}
{2833}{}{¡Oh!!}
{2834}{}{¡Oh, mi brazo!}
{2835}{}{¡Me has roto el brazo!}
{2836}{}{¡Vas a arrepentirte!}
{2837}{}{([Gruñe])}
{2839}{}{¡Oh, vaya!}
{2840}{}{¡Grrr!}
{2841}{}{¡Vas a arrepentirte!}
{2842}{}{¡Deberías parar mientras vayas por delante!}
{2843}{}{¡Usaré tus órganos para remplazar los míos!}
{2844}{}{¡Garrr!}
{2845}{}{¡Oh, mi pierna!}
{2846}{}{¡Me las pagarás por esto!}
{2847}{}{¡Ah! ¡Me has roto la pierna, yo te romperé el cuello!}
{2848}{}{¡Mi pierna!}
{2849}{}{¡Intenta eso de nuevo, normalito!}
{2850}{}{Pierdo el equilibrio...}
{2851}{}{¡Tengo sangre en los ojos!}
{2852}{}{¡Mi ojo! ¡Me las vas a pagar!}
{2853}{}{¡Bastardo!}
{2854}{}{¡Ohhhhh, la ingle!}
{2855}{}{¡Ohh! Tengo que aprender ese movimiento...}
{2856}{}{¡Cerdo humano!}
{2857}{}{¡AAAAAAAAAAAAHHHHHHHHH!}
{2858}{}{¡Urp!}
{2859}{}{¡Uff! ¡Te mataré por esto!}
{2900}{}{¡Retrocede! ¡Retrocede! ¡Sector seis!}
{2901}{}{¡Hoy no vas a matarme!}
{2902}{}{¡Esto no ha terminado!}
{2903}{}{¡Mis amigos te cogerán por mí!}
{2904}{}{¡Pagarás por esto... luego!}
{2905}{}{Otro día me divertiré con tu corazón}
{2906}{}{¡Te mataré, humano!}
{2907}{}{¡Nada nos desafía y sigue con vida!}
{2908}{}{¡Tus armas dan pena, no podrás herirme con ellas!}
{2909}{}{¡Otra víctima viene a jugar con nosotros!}
{2910}{}{Te sacaré de tu miseria}
{2911}{}{El Maestro está conmigo}
{2912}{}{Escoria humana}
{2913}{}{Te arrancaré los brazos}
{2914}{}{¡Ahora es cuando mueres!}
{2915}{}{¡Así es como tratamos a los idiotas!}
{2916}{}{Voy a divertirme mucho...}
{2917}{}{¡Gah! ¡Sufrirás!}
{2918}{}{¡Tus dioses te han abandonado!}
{2919}{}{¡Quiero oír tus gritos!}
{2920}{}{¡Así es como vas a morir!}
{2921}{}{¡Sufre, humano!}
{2922}{}{¡Das pena! ¿Cómo te atreves a luchar?}
{2923}{}{¿Eso es lo mejor que la humanidad puede ofrecer?}
{2924}{}{¡Tu ataque es tan débil como tu espíritu!}
{2925}{}{Ese fue tu último error}
{2926}{}{¡Idiota! ¿Y tú quieres derrotarme?}
{2927}{}{¡Patético!}
{2928}{}{¡Ahhhh! ¡Mi cara!}
{2929}{}{¡La cara! ¡Sufrirás por esto!}
{2930}{}{¡Arrghhggh! ¡Voy a hacerte pedazos!}
{2931}{}{¡Ahhh! ¡Mi brazo!}
{2932}{}{¡Ahhh! ¡No es tan fácil derrotarme!}
{2933}{}{¡Ahhh! ¡Te retorceré el cuello por esto!}
{2934}{}{¡Ahhh! ¡Mi brazo!}
{2935}{}{¡Ahhh! ¡No es tan fácil derrotarme!}
{2936}{}{¡Ahhh! ¡Te retorceré el cuello por esto!}
{2937}{}{Me haré unos trofeos con tus huesos}
{2938}{}{¡Uf!}
{2939}{}{¡Arrrggg!}
{2940}{}{[Sonríe]}
{2941}{}{¡No me ha dolido!}
{2942}{}{Puedes hacerlo mejor que eso}
{2943}{}{¡Hasta estos necrófagos son más fuertes que tú!}
{2944}{}{Ja, ja, ja, sigo en pie}
{2945}{}{Muchos sufrirán por tu culpa}
{2946}{}{¡Ja, ja! Vaya intento más poco convincente... (gruñe)}
{2947}{}{¡Ahhh! ¡Mi pierna!}
{2948}{}{¡Ahhh! ¡No es tan fácil derrotarme!}
{2949}{}{¡Ahhh! ¡Te retorceré el cuello por esto!}
{2950}{}{¡Ahhh! ¡Mi pierna!}
{2951}{}{¡Ahhh! ¡No es tan fácil derrotarme!}
{2952}{}{¡Ahhh! ¡Te retorceré el cuello por esto!}
{2953}{}{¡Ahhh! ¡Humano miserable! ¡Me has dejado ciego!}
{2954}{}{¡Ahhh! ¡Qué dolor! ¡Qué has hecho!}
{2955}{}{¡Uf! ¡Te has ganado días de agonía por esto!}
{2956}{}{¡No voy a compartir la debilidad contigo, humano!}
{2957}{}{¡Soy mucho más fuerte que tú!}
{2958}{}{¡Vaya táctica más patética, humano!}
{2959}{}{¡Ese no es mi punto vulnerable, humano!}
{2960}{}{¡Tu muerte será cada vez más dolorosa!}
{2961}{}{Quizá debería comprobar tus puntos débiles}
{3000}{}{¡Huye, huye!}
{3001}{}{¡Retirada!}
{3002}{}{¡Reagrupamiento!}
{3003}{}{¡Retrocede!}
{3004}{}{¡Retirada!}
{3005}{}{¡Aaaahhh!}
{3006}{}{¡Mata a este idiota!}
{3007}{}{Carne fresca...}
{3008}{}{¡A saquear!}
{3009}{}{¡Este es mío!}
{3010}{}{¡Cógelo!}
{3011}{}{¡Estás muerto! Espero que hayas disfrutado...}
{3012}{}{Disfruta los últimos segundos de tu vida}
{3013}{}{¡Sangre! ¡Sangre! ¡Sangre!}
{3014}{}{¡Tu corazón es mío!}
{3015}{}{¡¡RAAAAAAARRRR!!}
{3016}{}{¡Tus armas serán mis trofeos!}
{3017}{}{¡Muerte!}
{3018}{}{¡Seré yo el que te mate!}
{3019}{}{Tus huesos irán a parar a los desperdicios!}
{3020}{}{¡Sangre y oscuridad!}
{3021}{}{¡Fabricaré armas con tus huesos!}
{3022}{}{¡Aprende, bastardo retorcido!}
{3023}{}{¡Malgastas tus esfuerzos!}
{3024}{}{¡Has fallado!}
{3025}{}{¡Mi sangre es más fuerte que la tuya!}
{3026}{}{¡¡Estoy vivo!!}
{3027}{}{¡Tu cuerpo es tan débil que da pena!}
{3028}{}{¡Aaaahh! ¡Mi cara!}
{3029}{}{¡¿¡¡PERO QUÉ COÑO!!?!}
{3030}{}{¡Me has roto la nariz!}
{3031}{}{¡Mi brazo!}
{3032}{}{¡Me has roto el brazo!}
{3033}{}{¡Morirás por eso!}
{3034}{}{¡Yo te quitaré ambos!}
{3035}{}{¡Me lo has roto!}
{3036}{}{¡Pagarás por esto!}
{3037}{}{¡Joder!}
{3038}{}{¡¿A eso lo llamas dolor!?}
{3039}{}{¡Ay!}
{3040}{}{¡Uf!}
{3041}{}{¡Maldita sea, eso duele!}
{3042}{}{¡Ven aquí y deja que te haga yo lo mismo!}
{3043}{}{¡Lo vas a pagar! ¡Lo juro!}
{3044}{}{[Jadea fuertemente]}
{3045}{}{¡Maldición! ¡Zorra!}
{3046}{}{¡Ese llegó a la raíz!}
{3047}{}{¡Mi pierna!}
{3048}{}{¡Morirás por eso!}
{3049}{}{¡Ah! ¡Me has roto la pierna, yo te romperé el cuello!}
{3050}{}{¡Mi pierna!}
{3051}{}{¡Morirás por eso!}
{3052}{}{¡¡Ah!!}
{3053}{}{¡Ah! ¡Te despedazaré vivo!}
{3054}{}{¡Mi ojo!}
{3055}{}{¡Mi ojo! ¡Morirás lentamente por eso!}
{3056}{}{¡Ohhhhh, la ingle!}
{3057}{}{¡Auu! Tú... vas... ha sufrir...}
{3058}{}{¡Ohh! Te... voy... a matar...}
{3059}{}{¡Auu! Mutilaré tu...}
{3060}{}{¡Urp!}
{3061}{}{¡Te mataré por esto!}
{3100}{}{¡Khans! ¡Cubridme!}
{3101}{}{¡Retirada!}
{3102}{}{¡Reagrupamiento!}
{3103}{}{¡Retrocede!}
{3104}{}{¡Retirada!}
{3105}{}{Volveré}
{3106}{}{¡Qué empiece el desafío!}
{3107}{}{Carne fresca...}
{3108}{}{¡A saquear!}
{3109}{}{¡Este es mío!}
{3110}{}{¡Khans, al ataque!}
{3111}{}{¡Te voy a KHANbiar la cara a golpes!}
{3112}{}{¡Khans, matad!}
{3113}{}{¡Sangre! ¡Sangre! ¡Sangre!}
{3114}{}{¡Soy una máquina!}
{3115}{}{¡¡RAAAAAAARRRR!!}
{3116}{}{¡Los Khans son invencibles!}
{3117}{}{¡Nunca nos retiramos! ¡Nunca nos rendimos!}
{3118}{}{¡Seré yo el que te mate!}
{3119}{}{Tus huesos irán a parar a los desperdicios!}
{3120}{}{¡Sangre y oscuridad!}
{3121}{}{¡Los Khans son los que mandan!}
{3122}{}{¡Ja, ja, ja, ja, inténtalo de nuevo!}
{3123}{}{¡No me puedes tocar!}
{3124}{}{¡Soy indestructible!}
{3125}{}{¡Mi sangre es más fuerte que la tuya!}
{3126}{}{¡Mis esclavos luchan mejor que tú!}
{3127}{}{¡No mereces luchar conmigo!}
{3128}{}{¡Un golpe de suerte!}
{3129}{}{¡Ese ha sido tu último ataque!}
{3130}{}{¡Un intento patético!}
{3131}{}{¡Aún te puedo ganar con un solo brazo!}
{3132}{}{¡Me has roto un brazo! Ahora estamos igualados}
{3133}{}{¡Ha sido tu último golpe!}
{3134}{}{¡Aún te puedo ganar con un solo brazo!}
{3135}{}{¡Me has roto un brazo! Ahora estamos igualados}
{3136}{}{¡Acabaré contigo!}
{3137}{}{¡Por eso, tu muerte será legendaria!}
{3138}{}{¡Por eso que has hecho, lo festejaré con tus ojos!}
{3139}{}{¡Soy indestructible!}
{3140}{}{¡Mi sangre es más fuerte que la tuya!}
{3141}{}{¡Soy indestructible!}
{3142}{}{¡Por eso que has hecho, lo festejaré con tus ojos!}
{3143}{}{¡¡RAAAAAAARRRR!!}
{3144}{}{Me duelen las costillas. ¡Pronto te arrancaré las tuyas! Es lo justo}
{3145}{}{Me duelen las costillas. ¡Pronto te arrancaré las tuyas! Es lo justo}
{3146}{}{¡Sangre y oscuridad!}
{3147}{}{¡No necesito estar de pie para matarte!}
{3148}{}{¡Morirás por eso!}
{3149}{}{¡Mi pierna! ¡Te quitaré la tuya con mis puños!}
{3150}{}{¡No necesito estar de pie para matarte!}
{3151}{}{¡Morirás por eso!}
{3152}{}{¡Mi pierna! ¡Te quitaré la tuya con mis puños!}
{3153}{}{¡Ah! ¡Te despedazaré vivo!}
{3154}{}{¡Mis ojos! ¡Canjearé mi vista por tu muerte!}
{3155}{}{¡Mi ojo! ¡Morirás lentamente por eso!}
{3156}{}{¡No me robarás la hombría!}
{3157}{}{¡Auu! Tú... vas... ha sufrir...}
{3158}{}{¡Ohh! Te... voy... a matar...}
{3159}{}{¡Auu! Mutilaré tu...}
{3160}{}{¡Urp!}
{3161}{}{¡No me robarás la hombría!}
{3200}{}{¡No creas que esto se ha acabado!}
{3201}{}{¡Necesito ayuda aquí!}
{3202}{}{¡Que alguien me ayude!}
{3203}{}{¡Te haremos justicia!}
{3204}{}{Algún día, tendrás lo que te mereces}
{3205}{}{¡No voy a morir por esto!}
{3206}{}{}
{3207}{}{}
{3208}{}{}
{3209}{}{¡Por aquí no nos gustan los tipos como tú!}
{3210}{}{Nadie va a tomar este lugar...}
{3211}{}{¡Arenas Sombrías no necesita a los que son como tú!}
{3212}{}{}
{3213}{}{Voy a hacerte una herida bien grande}
{3214}{}{¡Esto es lo que le hacemos a la gentuza!}
{3215}{}{}
{3216}{}{Así hacemos frente a los problemas en Arenas Sombrías}
{3217}{}{¡Así aprenderás!}
{3218}{}{Utilizaré tu cuerpo como fertilizante}
{3219}{}{Bien. Te lo has buscado.}
{3220}{}{¡Serás animal!}
{3221}{}{¡Te arrepentirás de haber venido!}
{3222}{}{No eres tan bueno como te piensas}
{3223}{}{}
{3224}{}{Eres más tonto que las ratas topo}
{3225}{}{Arenas Sombrías no se rinde ni muere por nadie}
{3226}{}{}
{3227}{}{Ese fue tu último error}
{3228}{}{¡Maldición!}
{3229}{}{¡Aggghhh!}
{3230}{}{¡Mi cara, mi cara!}
{3231}{}{¡Ahhh! ¡Mi brazo!}
{3232}{}{¡Mi brazo!}
{3233}{}{El maldito brazo ya no me sirve...}
{3234}{}{¡Ahhh! ¡Mi brazo!}
{3235}{}{¡Mi brazo!}
{3236}{}{El maldito brazo ya no me sirve...}
{3237}{}{¡Ay!}
{3238}{}{¡Oh!}
{3239}{}{}
{3240}{}{Espero que mueras de sed, frío y soledad...}
{3241}{}{[Jadea fuertemente]}
{3242}{}{}
{3243}{}{Por favor, no...}
{3244}{}{}
{3245}{}{Mal karma golpearme así}
{3246}{}{¡Gack!}
{3247}{}{¡Ahhh! ¡Mi pierna!}
{3248}{}{¡Mi pierna!}
{3249}{}{Maldición, la pierna ya no me sirve...}
{3250}{}{¡Ahhh! ¡Mi pierna!}
{3251}{}{¡Mi pierna!}
{3252}{}{Maldición, la pierna ya no me sirve...}
{3253}{}{¡Ahhh! ¡Estoy ciego!}
{3254}{}{¡Maldita sea! ¡Todo está oscuro!}
{3255}{}{¡Mi ojo! ¡Me las vas a pagar!}
{3256}{}{¡Ohhhhh, la ingle!}
{3257}{}{¡Ooooooooooffffff!}
{3258}{}{No... puedo... respirar...}
{3259}{}{!}
{3260}{}{Me duele, me duele...}
{3261}{}{¡Maldita sea, cómo me duele!}
{3300}{}{Me largo}
{3301}{}{}
{3302}{}{¡Aaaaahhhh!}
{3303}{}{Luego, quizá.}
{3304}{}{}
{3305}{}{Te veré por aquí}
{3306}{}{}
{3307}{}{¿Qué pasa ahora?}
{3308}{}{Yo me encargaré...}
{3309}{}{¡Otra interrupción no!}
{3310}{}{Si no son escorpiones rad, entonces son los malditos saqueadores...}
{3311}{}{}
{3312}{}{}
{3313}{}{¡Muere!}
{3314}{}{Desgraciado}
{3315}{}{Punk}
{3316}{}{}
{3317}{}{¡Ese es tu número!}
{3318}{}{Lo estás echando a perder}
{3319}{}{Esto es un regalo de Arenas Sombrías}
{3320}{}{No volverás a molestar a nadie otra vez}
{3321}{}{Prepárate para subir, cariñito}
{3322}{}{No me causa buena impresión}
{3323}{}{Aficionado}
{3324}{}{Patético}
{3325}{}{Eres un lento}
{3326}{}{No sirves para nada}
{3327}{}{No abandones tu trabajo de día}
{3328}{}{Eso duele}
{3329}{}{¡Mis ojos!}
{3330}{}{¡Ay! Me has destrozado la nariz...}
{3331}{}{¡Ow!}
{3332}{}{¡Ow! ¡Mi brazo!}
{3333}{}{¡Ay! ¡Me lo has roto!}
{3334}{}{¡Ow!}
{3335}{}{¡Ow! ¡Mi brazo!}
{3336}{}{¡Ay! ¡Me lo has roto!}
{3337}{}{¡Demonios! ¡Eso me ha dolido!}
{3338}{}{¡Ay!}
{3339}{}{¡Ow!}
{3340}{}{}
{3341}{}{(Sujetándose las costillas) ¡Auch!}
{3342}{}{¡Venga! ¡No se lucha en la ciudad!}
{3343}{}{[Jadea fuertemente]}
{3344}{}{¡Ay! Me has decepcionado...}
{3345}{}{¡Uf!}
{3346}{}{¡Me duele!}
{3347}{}{¡Ow!}
{3348}{}{¡Oh! ¡Mi rodilla!}
{3349}{}{¡Oh! ¡Mi pierna!}
{3350}{}{¡Ow!}
{3351}{}{¡Oh! ¡Mi rodilla!}
{3352}{}{¡Oh! ¡Mi pierna!}
{3353}{}{¡Estoy ciego!}
{3354}{}{¡No veo!}
{3355}{}{Está oscuro}
{3356}{}{¡Ohhhhh, la ingle!}
{3357}{}{¡Ayyy!}
{3358}{}{Joder, cómo duele}
{3359}{}{¡Uf!}
{3360}{}{¡Urp!}
{3361}{}{No... puedo... respirar...}
{3400}{}{}
{3401}{}{}
{3402}{}{Necesito un médico}
{3403}{}{Luego, quizá.}
{3404}{}{Será mejor que me quite de en medio}
{3405}{}{Te veré por aquí}
{3406}{}{Amigo, acabas de cometer un grave error}
{3407}{}{¿Qué pasa ahora?}
{3408}{}{Yo me encargaré...}
{3409}{}{¡Otra interrupción no!}
{3410}{}{Si no son escorpiones rad, entonces son alborotadores...}
{3411}{}{}
{3412}{}{}
{3413}{}{}
{3414}{}{Canalla}
{3415}{}{Punk}
{3416}{}{Esto es lo que hacemos con los alborotadores}
{3417}{}{¡Espero que te duela!}
{3418}{}{La verdad es que te quedaste ahí petrificado}
{3419}{}{Esto es un regalo de Arenas Sombrías}
{3420}{}{No volverás a molestar a nadie otra vez}
{3421}{}{No voy a dejar que salgas de esta}
{3422}{}{No me causa buena impresión}
{3423}{}{No deberías luchar a no ser que sepas lo que estás haciendo}
{3424}{}{Patético}
{3425}{}{Eres un lento}
{3426}{}{}
{3427}{}{}
{3428}{}{}
{3429}{}{¡Mi cráneo!}
{3430}{}{¡Ay! Una maldita nariz destrozada...}
{3431}{}{¡Ow!}
{3432}{}{¡Ow! ¡Mi brazo!}
{3433}{}{¡Ay! ¡Me lo has roto!}
{3434}{}{¡Ow!}
{3435}{}{¡Ow! ¡Mi brazo!}
{3436}{}{¡Ay! ¡Me lo has roto!}
{3437}{}{¡Ow!}
{3438}{}{¡Por Dharma! ¡Eso duele!}
{3439}{}{El que busca jaleo... lo encuentra...}
{3440}{}{¡Uf!}
{3441}{}{¡Uff! Te castigaré por esto...}
{3442}{}{¡Oh! ¡Me duele!}
{3443}{}{¡Ay! Eso ha sido muy desagradable}
{3444}{}{¡Ay! ¿Por qué haces esto?}
{3445}{}{¡Ahh! Tengo que controlar mis emociones...}
{3446}{}{¡Ahh! ¡Pareces un excremento de escorpión rad!}
{3447}{}{¡Ow!}
{3448}{}{¡Oh! ¡Mi rodilla!}
{3449}{}{¡Oh! ¡Mi pierna!}
{3450}{}{¡Ow!}
{3451}{}{¡Oh! ¡Mi rodilla!}
{3452}{}{¡Oh! ¡Mi pierna!}
{3453}{}{¡Mis ojos!}
{3454}{}{¡Ahh! Conque así es como quieres jugar...}
{3455}{}{¡Agghh! Pequeño sucio hijo de...}
{3456}{}{¡Ohhhhh, la ingle!}
{3457}{}{¡Ayyy!}
{3458}{}{[lloriquea]}
{3459}{}{¡Uf!}
{3460}{}{¡Ohhhhh! ¡No me lo siento! ¡Ay!}
{3461}{}{¡Ohhhhh! Me duele. Debo estar envejeciendo.}
{3500}{}{Puede que me tome un breve descanso.}
{3501}{}{¡Volveré!}
{3502}{}{¡Hasta luego, mocoso!}
{3503}{}{}
{3504}{}{}
{3505}{}{¡Hagámoslo otra vez!}
{3506}{}{Lucha conmigo o quiéreme...}
{3507}{}{¡Carne fresca!}
{3508}{}{!}
{3509}{}{}
{3510}{}{¡Los Destripadores te van a hacer pedazos!}
{3511}{}{Vamos a bailar!}
{3512}{}{¡Voy a trincharte como si fueras carne de iguana en un pincho!}
{3513}{}{}
{3514}{}{Por favor, no te mueras todavía. ¡Quiero que sufras!}
{3515}{}{}
{3516}{}{¡Servidor de la muerte, presente!}
{3517}{}{Estarás tan guapo cuando mueras...}
{3518}{}{¡Muere, muere, muere, muere!}
{3519}{}{¡Tu dolor es mi alegría!}
{3520}{}{Vamos a abrirte un poquito...}
{3521}{}{Y yo que creía que hoy no habría derramamiento de sangre...}
{3522}{}{}
{3523}{}{¡Estoy MUY asustado!}
{3524}{}{Éste es mi chico, ¡lucha un poquito!}
{3525}{}{¿Eso es todo lo que sabes hacer?}
{3526}{}{¡No eres nada comparado conmigo!}
{3527}{}{Esto va a ser más fácil de lo que creía}
{3528}{}{¡Esa será una bonita cicatriz!}
{3529}{}{¿Intentas impresionarme?}
{3530}{}{Hazlo otra vez, cariño.}
{3531}{}{Me encanta el sonido de los huesos cuando crujen}
{3532}{}{¡Ohh, te estás poniendo demasiado serio!}
{3533}{}{Me gusta fuerte, cariño}
{3534}{}{Me encanta el sonido de los huesos cuando crujen}
{3535}{}{¡Ohh, te estás poniendo demasiado serio!}
{3536}{}{Me gusta fuerte, cariño}
{3537}{}{Me gusta cuando te pones duro...}
{3538}{}{Dame otro golpecito de amor...}
{3539}{}{¡Ohh! ¡Oh, duele, cariño!}
{3540}{}{¡Uf!}
{3541}{}{¡Oh!}
{3542}{}{¡Ah! ¿Significa esto que ya has acabado?}
{3543}{}{[Jadea fuertemente]}
{3544}{}{Dame otra vez, por favor...}
{3545}{}{La próxima vez llegaré al punto máximo}
{3546}{}{Oh, el dolor, el dolor...}
{3547}{}{Me encanta el sonido de los huesos cuando crujen}
{3548}{}{¡Ohh, te estás poniendo demasiado serio!}
{3549}{}{}
{3550}{}{Me encanta el sonido de los huesos cuando crujen}
{3551}{}{}
{3552}{}{¡Me gusta!}
{3553}{}{Eh, estoy ciego. ¡Qué confusión!}
{3554}{}{No veo. ¡Supongo que tendré que oler tu miedo!}
{3555}{}{¡Mis ojos! Tío, me gusta tu forma de luchar}
{3556}{}{¡Ohhhhh, la ingle!}
{3557}{}{Eso ha sido un golpe bajo}
{3558}{}{¡Ohhh! ¿Eso es una proposición, encanto?}
{3559}{}{}
{3560}{}{Conque así es como quieres que juguemos}
{3561}{}{Ohhhh, bonito movimiento, tío}
{3600}{}{}
{3601}{}{}
{3602}{}{}
{3603}{}{¡No ganarás!}
{3604}{}{¡Retrocede!}
{3605}{}{No necesito esto...}
{3606}{}{¡Al ataque!}
{3607}{}{¡Voy a disfrutar mucho enterrándote en una tumba poco profunda!}
{3608}{}{}
{3609}{}{Alguien se muere}
{3610}{}{¡Muerte al intruso!}
{3611}{}{}
{3612}{}{}
{3613}{}{¡Muere!}
{3614}{}{¡Baila!}
{3615}{}{De ahí viene nuestro nombre}
{3616}{}{}
{3617}{}{¡Espero que te duela!}
{3618}{}{Será divertido}
{3619}{}{¡Tu cabeza formará parte de mi colección!}
{3620}{}{Te enterraré}
{3621}{}{Hoy se te va a torcer un poco el día}
{3622}{}{¡Soy más recto que el mismo Dios!}
{3623}{}{No me causa buena impresión}
{3624}{}{¡Demuestra que tienes pelotas!}
{3625}{}{}
{3626}{}{¡Tu mamá se acuesta con El Destripador!}
{3627}{}{¿Intentas aplastar moscas, primo?}
{3628}{}{}
{3629}{}{¡¡Ahh!!}
{3630}{}{¡Ay! Me has destrozado la nariz...}
{3631}{}{¡Ow!}
{3632}{}{¡Ow! ¡Mi brazo!}
{3633}{}{¡Ay! ¡Me lo has roto!}
{3634}{}{¡Ow!}
{3635}{}{¡Ow! ¡Mi brazo!}
{3636}{}{¡Ay! ¡Me lo has roto!}
{3637}{}{¡Ow!}
{3638}{}{¡Ah, maldita sea!}
{3639}{}{¡Auch! Ese ha sido un grave error...}
{3640}{}{¡Au! Vas a ver...}
{3641}{}{[Jadea fuertemente]}
{3642}{}{No puedo respirar...}
{3643}{}{}
{3644}{}{¡Uf!}
{3645}{}{¡Eso duele, tío!}
{3646}{}{}
{3647}{}{¡Ow!}
{3648}{}{¡Oh! ¡Mi rodilla!}
{3649}{}{¡Oh! ¡Mi pierna!}
{3650}{}{¡Ow!}
{3651}{}{¡Oh! ¡Mi rodilla!}
{3652}{}{¡Oh! ¡Mi pierna!}
{3653}{}{¡Estoy ciego!}
{3654}{}{¡No veo!}
{3655}{}{¡Mis ojos! Hijo de Destripador...}
{3656}{}{¡Ohhhhh, la ingle!}
{3657}{}{¡Ayyy!}
{3658}{}{Joder, cómo duele}
{3659}{}{¡Uf!}
{3660}{}{Te mataré por esto, mocoso}
{3661}{}{No... puedo... respirar...}
{3700}{}{Me encantaría ver amanecer mañana}
{3701}{}{Puede que no fuera una buena idea}
{3702}{}{}
{3703}{}{}
{3704}{}{¡No voy a morir por esto!}
{3705}{}{No puedo creer lo que están haciendo...}
{3706}{}{Intentando hacer músculos a nuestra costa, ¿eh?}
{3707}{}{¡Alguien acaba de cometer un gran error!}
{3708}{}{Hora de vaciar el cargador...}
{3709}{}{¿Quién te crees que eres?}
{3710}{}{Hora de enseñar la mercancía}
{3711}{}{Espera a que te coja...}
{3712}{}{¡Llévate contigo mis balas al infierno!}
{3713}{}{}
{3714}{}{}
{3715}{}{¿Qué te parece esto?}
{3716}{}{Voy a dejarte como si fueras un mal vicio}
{3717}{}{¿Qué tal la potencia de fuego?}
{3718}{}{Veamos lo duro que eres...}
{3719}{}{La lucha es mi vida}
{3720}{}{}
{3721}{}{Quizá así aprendas un poco de respeto}
{3722}{}{No esperabas darme, ¿verdad?}
{3723}{}{Hace años que hago esto, mocoso}
{3724}{}{No esperabas darme, ¿verdad?}
{3725}{}{Ese fue tu último error}
{3726}{}{Aficionado}
{3727}{}{Esto no es como disparar a las ratas topo, amigo}
{3728}{}{¡Oh! Hijo de...}
{3729}{}{Te mataré por esto}
{3730}{}{¡Te arrancaré la cabeza!}
{3731}{}{¡Oh, mi brazo!}
{3732}{}{Maldita sea. ¡Tengo el brazo destrozado!}
{3733}{}{¡Mi brazo!}
{3734}{}{¡Oh, mi brazo!}
{3735}{}{Maldita sea. ¡Tengo el brazo destrozado!}
{3736}{}{¡Mi brazo!}
{3737}{}{He visto a muchos novatos hacerlo mejor que tú...}
{3738}{}{¡Ay!}
{3739}{}{Tengo que acordarme de devolverte este dolor algún día}
{3740}{}{¡Uf!}
{3741}{}{}
{3742}{}{¡Maldición!}
{3743}{}{¡Maldito idiota!}
{3744}{}{}
{3745}{}{[Jadea fuertemente]}
{3746}{}{¡Ay!}
{3747}{}{¡Oh, mi pierna!}
{3748}{}{}
{3749}{}{¡Mi rodilla!}
{3750}{}{¡Oh, mi pierna!}
{3751}{}{¡Vas a pagar por esto, en carne!}
{3752}{}{¡Mi rodilla!}
{3753}{}{¡No veo!}
{3754}{}{¡Mi ojo! ¡Me las vas a pagar!}
{3755}{}{¡Ayyyyyy! ¡Estoy ciego!}
{3756}{}{¡Ohhhhh, la ingle!}
{3757}{}{Conque así es como quieres jugar}
{3758}{}{}
{3759}{}{¡Urp!}
{3760}{}{}
{3761}{}{Me duele, me duele...}
{3800}{}{¡Necesito refuerzos!}
{3801}{}{¡Que alguien me ayude!}
{3802}{}{¡Reagrupamiento!}
{3803}{}{¡Retirada! ¡Retirada!}
{3804}{}{¡Retrocede! ¡Retrocede!}
{3805}{}{¡Tenemos que encontrar una posición mejor!}
{3806}{}{¡Tenemos un objetivo!}
{3807}{}{¡Nos atacan!}
{3808}{}{¡Alerta! ¡Los mantendré alejados!}
{3809}{}{Tenemos un problema, pero le haré frente.}
{3810}{}{¡Objetivo localizado, vamos a interceptarlo!}
{3811}{}{¡Enganchando objetivo!}
{3812}{}{¡Novato del submundo criminal!}
{3813}{}{No voy a incluirte en nuestra miseria}
{3814}{}{¡No eres mejor que un animal!}
{3815}{}{Será mejor que esta vez te quedes donde estás}
{3816}{}{Nunca volverás a molestar a nadie}
{3817}{}{¡No hay misericordia para los mocosos!}
{3818}{}{¡Será mejor que reces a los dioses!}
{3819}{}{¡Llévate contigo mis balas al infierno!}
{3820}{}{Dejo caer el martillo sobre ti}
{3821}{}{Te veré en el infierno}
{3822}{}{¡Tu ataque apesta más que tu aliento, gusano!}
{3823}{}{Venga perdedor. Cae muerto para mí}
{3824}{}{}
{3825}{}{¡Te estás equivocando de juego, saco de escoria!}
{3826}{}{¿Qué te pasa, mocoso?}
{3827}{}{No moriré tan fácilmente.}
{3828}{}{¡Ahh! ¡Has tenido suerte!}
{3829}{}{¡Mi cara!}
{3830}{}{¡Me has roto la nariz!}
{3831}{}{¡Ahh! ¡Has tenido suerte!}
{3832}{}{¡No voy a pararme por un brazo destrozado!}
{3833}{}{}
{3834}{}{¡Ahh! ¡Has tenido suerte!}
{3835}{}{¡No voy a pararme por un brazo destrozado!}
{3836}{}{No me gusta ese sonido}
{3837}{}{¡Ahh! ¡Has tenido suerte!}
{3838}{}{}
{3839}{}{No vas a dejarme lisiado, colega.}
{3840}{}{¡Ahh! ¡Has tenido suerte!}
{3841}{}{}
{3842}{}{No vas a dejarme lisiado, colega.}
{3843}{}{¡Estoy ciego!}
{3844}{}{¡Me arden los ojos!}
{3845}{}{¡No veo!}
{3846}{}{¡Ohhhhh, la ingle!}
{3847}{}{Sí, los mocosos siempre apuntáis a la entrepierna}
{3848}{}{¡Cómo me duele, maldición!}
{3849}{}{No... puedo... respirar...}
{3850}{}{Ohhhhh. Eres un sádico hijo de...}
{3851}{}{Mamón}
{3900}{}{¡Necesito refuerzos!}
{3901}{}{¡Que alguien me ayude!}
{3902}{}{}
{3903}{}{¡Retirada! ¡Retirada!}
{3904}{}{¡Retrocede! ¡Retrocede!}
{3905}{}{¡Ayuda!}
{3906}{}{¡Por Adytum!}
{3907}{}{¡Nos atacan!}
{3908}{}{¡Necesito refuerzos!}
{3909}{}{¡Al ataque!}
{3910}{}{¡Por aquí no nos gustan los tipos como tú!}
{3911}{}{¡A las armas! ¡A las armas!}
{3912}{}{¡Esto es por Adytum!}
{3913}{}{¡Esto es lo que hacemos con los animales!}
{3914}{}{Bienvenido al infierno, mocoso}
{3915}{}{Será mejor que esta vez te quedes donde estás}
{3916}{}{Nunca volverás a molestar a nadie}
{3917}{}{¡No hay misericordia para los mocosos!}
{3918}{}{¡Será mejor que reces a los dioses!}
{3919}{}{}
{3920}{}{Acaba de tocarte una casa bajo tierra}
{3921}{}{Espero que hayas disfrutado de tu vida; la veras pasar delante de tus ojos}
{3922}{}{Eres un desecho}
{3923}{}{}
{3924}{}{}
{3925}{}{Ahora me toca a mí}
{3926}{}{¿Sorprendido, mocoso?}
{3927}{}{No es fácil matarnos}
{3928}{}{¡Ahh! Justo en la cara.}
{3929}{}{¡Mi cara!}
{3930}{}{¡Me has roto la nariz!}
{3931}{}{¡Ahh! ¡Mi brazo!}
{3932}{}{¡Oh! ¡Me duele!}
{3933}{}{Maldita sea, deben haberme malherido}
{3934}{}{¡Ahh! ¡Mi brazo!}
{3935}{}{¡Oh! ¡Me duele!}
{3936}{}{Maldita sea, deben haberme malherido}
{3937}{}{¡Ay!}
{3938}{}{¡Uff! ¡Eso duele!}
{3939}{}{¡Uff! Me... cuesta... res... pirar...}
{3940}{}{¡Me han dado! ¡Un médico!}
{3941}{}{Estaré bien, es una herida sin importancia}
{3942}{}{¡Agh!}
{3943}{}{¡Auch! ¡Maldita sea!}
{3944}{}{¡Ah! Te atraparé}
{3945}{}{}
{3946}{}{}
{3947}{}{¡Ahh! ¡Has tenido suerte!}
{3948}{}{Maldita sea, justo en la rodilla...}
{3949}{}{No voy a caerme, imbécil. Ay.}
{3950}{}{¡Ahh! ¡Has tenido suerte!}
{3951}{}{Maldita sea, justo en la rodilla...}
{3952}{}{No voy a caerme, imbécil. Ay.}
{3953}{}{¡Estoy ciego, que alguien me ayude!}
{3954}{}{¡Maldita sea, justo en los ojos!}
{3955}{}{¡No veo!}
{3956}{}{¡Ohhhhh, la ingle!}
{3957}{}{Sí, los mocosos siempre apuntáis a la entrepierna}
{3958}{}{¡Cómo me duele, maldición!}
{3959}{}{No... puedo... respirar...}
{3960}{}{Ohhhhh. Eres un sádico hijo de...}
{3961}{}{Mamón}
{4000}{}{¡Qué alguien me cubra!}
{4001}{}{¡Que alguien me ayude!}
{4002}{}{¡Un médico!}
{4003}{}{¡Retirada! ¡Retirada!}
{4004}{}{¡Retrocede! ¡Retrocede!}
{4005}{}{¡Ayuda!}
{4006}{}{Creo que va a haber problemas.}
{4007}{}{¡Nos atacan!}
{4008}{}{¡Tenemos problemas!}
{4009}{}{¡Una vez más en la brecha!}
{4010}{}{¡Moriré antes de dejar que me pisotees!}
{4011}{}{Estás metiéndote con la persona equivocada}
{4012}{}{Debiste huir cuando tuviste oportunidad}
{4013}{}{Es hora de acabar con esto}
{4014}{}{}
{4015}{}{}
{4016}{}{Otro fiambre para mi conciencia...}
{4017}{}{Esta vez te liquidaré a base de bien}
{4018}{}{¡Será mejor que reces a los dioses!}
{4019}{}{}
{4020}{}{}
{4021}{}{No vas a salir de ésta}
{4022}{}{No vas a ganar esta pelea}
{4023}{}{}
{4024}{}{No puedes ganar...}
{4025}{}{Ahora me toca a mí}
{4026}{}{¿No lo coges? ¡No vas a ganar!}
{4027}{}{No es fácil matarnos}
{4028}{}{¡Ahh! Justo en la cara.}
{4029}{}{¡Mi cara!}
{4030}{}{¡Me has roto la nariz!}
{4031}{}{¡Ahh! ¡Mi brazo!}
{4032}{}{¡Oh! ¡Me duele!}
{4033}{}{Maldita sea, deben haberme malherido}
{4034}{}{¡Ahh! ¡Mi brazo!}
{4035}{}{¡Oh! ¡Me duele!}
{4036}{}{Maldita sea, deben haberme malherido}
{4037}{}{¡Oh! Eso me ha dolido mucho}
{4038}{}{}
{4039}{}{¡Uff! Tienes que hacerlo mejor que eso}
{4040}{}{¡Auch! ¿¡Crees que puedes hacer que cambie de idea tan fácilmente!?}
{4041}{}{¡Ay!}
{4042}{}{¡Agh!}
{4043}{}{¡Uf!}
{4044}{}{[Jadea fuertemente]}
{4045}{}{}
{4047}{}{¡Ahh! ¡Mi pierna!}
{4048}{}{Maldita sea, justo en la rodilla...}
{4049}{}{¡Ahh! Apenas puedo estar en pie...}
{4050}{}{¡Ahh! ¡Mi pierna!}
{4051}{}{Maldita sea, justo en la rodilla...}
{4052}{}{¡Ahh! Apenas puedo estar en pie...}
{4053}{}{¡Estoy ciego, que alguien me ayude!}
{4054}{}{}
{4055}{}{¡No veo!}
{4056}{}{¡Ohhhhh, la ingle!}
{4057}{}{}
{4058}{}{¡Maldición!}
{4059}{}{No... puedo... respirar...}
{4060}{}{}
{4061}{}{¡Novato!}
{4100}{}{}
{4101}{}{¡Qué alguien me ayude!}
{4102}{}{}
{4103}{}{¡Retirada! ¡Retirada!}
{4104}{}{¡Retrocede! ¡Retrocede!}
{4105}{}{¡Ayuda!}
{4106}{}{}
{4107}{}{Creo que tenemos un problema}
{4108}{}{Veamos si puedo acabar con esto rápido}
{4109}{}{Mejor será ocuparnos de ellos desde aquí}
{4110}{}{Eso parece una potencia de fuego bastante seria}
{4111}{}{Estás metiéndote con la persona equivocada}
{4112}{}{Debiste huir cuando tuviste oportunidad}
{4113}{}{Es hora de acabar con esto}
{4114}{}{}
{4115}{}{Después de esto no serás una amenaza}
{4116}{}{}
{4117}{}{}
{4118}{}{}
{4119}{}{Un canalla menos en el Cementerio de LA}
{4120}{}{}
{4121}{}{No vas a salir de ésta}
{4122}{}{No vas a ganar}
{4123}{}{}
{4124}{}{}
{4125}{}{Ahora me toca a mí}
{4126}{}{¡No puedes ganar!}
{4127}{}{}
{4128}{}{¡Aggghh!}
{4129}{}{}
{4130}{}{¡Mi cara!}
{4131}{}{¡Ahh! ¡Mi brazo!}
{4132}{}{Demonios, tengo el miembro inutilizado...}
{4133}{}{Maldita sea, deben haberme malherido}
{4134}{}{¡Ahh! ¡Mi brazo!}
{4135}{}{Demonios, tengo el miembro inutilizado...}
{4136}{}{Maldita sea, deben haberme malherido}
{4137}{}{¡Auh! Tengo que advertir a los demás sobre ti}
{4138}{}{¡Uff! Tengo que vivir, tengo que vivir...}
{4139}{}{}
{4140}{}{¡Uf!}
{4141}{}{¡Bah!}
{4142}{}{¡Ack!}
{4143}{}{¡Ow!}
{4144}{}{}
{4145}{}{}
{4146}{}{}
{4147}{}{¡Ahh! ¡Mi pierna!}
{4148}{}{Maldita sea, justo en la rodilla...}
{4149}{}{¡Ahh! Apenas puedo estar en pie...}
{4150}{}{¡Ahh! ¡Mi pierna!}
{4151}{}{Maldita sea, justo en la rodilla...}
{4152}{}{¡Ahh! Apenas puedo estar en pie...}
{4153}{}{¡Estoy ciego! Puede que si chupo la sangre...}
{4154}{}{¡Maldita sea, justo en los ojos!}
{4155}{}{¡No veo!}
{4156}{}{}
{4157}{}{¡Ahh!}
{4158}{}{}
{4159}{}{No... puedo... respirar...}
{4160}{}{}
{4161}{}{}
{4200}{}{}
{4201}{}{¡No hay refuerzos suficientes y estoy muy grave!}
{4202}{}{}
{4203}{}{}
{4204}{}{¡Retrocede! ¡Retrocede!}
{4205}{}{¡Que alguien me cubra!}
{4206}{}{}
{4207}{}{}
{4208}{}{¡Defendamos esto!}
{4209}{}{}
{4210}{}{¡Intrusos!}
{4211}{}{Acabas de firmar tu sentencia de muerte}
{4212}{}{}
{4213}{}{}
{4214}{}{}
{4215}{}{Después de esto ya no serás una amenaza...}
{4216}{}{Esto va a doler}
{4217}{}{Voy a liquidarte...}
{4218}{}{}
{4219}{}{Un canalla menos en el Cementerio de LA}
{4220}{}{}
{4221}{}{No vas a salir de esta}
{4222}{}{No vas a ganar esta pelea}
{4223}{}{}
{4224}{}{}
{4225}{}{Ahora me toca a mí}
{4226}{}{Acabas de cometer un grave error}
{4227}{}{}
{4228}{}{¡Maldición!}
{4229}{}{}
{4230}{}{Creo que tengo la nariz destrozada}
{4231}{}{¡Mi brazo!}
{4232}{}{}
{4233}{}{Creo que me han malherido...}
{4234}{}{¡Mi brazo!}
{4235}{}{Demonios, tengo el miembro inutilizado...}
{4236}{}{¡Maldición, deben haberme malherido...!}
{4237}{}{}
{4238}{}{}
{4239}{}{}
{4240}{}{¡Uf!}
{4241}{}{¡Bah!}
{4242}{}{¡Ack!}
{4243}{}{¡Ow!}
{4244}{}{¡Uff! Puede que esté herido}
{4245}{}{¡Maldita sea, cómo me duele!}
{4246}{}{}
{4247}{}{¡Mi pierna!}
{4248}{}{Maldita sea, justo en la rodilla...}
{4249}{}{¡Ahh! Apenas puedo estar en pie...}
{4250}{}{¡Mi pierna!}
{4251}{}{Maldita sea, justo en la rodilla...}
{4252}{}{¡Ahh! Apenas puedo estar en pie...}
{4253}{}{¡Estoy ciego!}
{4254}{}{¡Maldita sea, justo en los ojos!}
{4255}{}{¡No veo!}
{4256}{}{¡Ahhh! ¡Mis partes!}
{4257}{}{}
{4258}{}{¡Esto es un infierno!}
{4259}{}{No... puedo... respirar...}
{4260}{}{}
{4261}{}{}
{4300}{}{Tengo que encontrar una posición mejor...}
{4301}{}{No tengo suficiente apoyo y estoy malherida...}
{4302}{}{¡Esto no ha terminado!}
{4303}{}{Será mejor que nos reagrupemos...}
{4304}{}{¡Retrocede!}
{4305}{}{La fuerza bruta no ganará en esta pelea}
{4306}{}{Podré con esto}
{4307}{}{¡Esto no va a ser bonito!}
{4308}{}{¡Defendamos esto!}
{4309}{}{¡No podemos permitir que esta escoria detenga nuestra misión!}
{4310}{}{}
{4311}{}{}
{4312}{}{Esto no me hace gracia}
{4313}{}{Es hora de acabar con esto}
{4314}{}{}
{4315}{}{No deberías de haber venido}
{4316}{}{Esto va a doler}
{4317}{}{No dejaré que destruyas lo que he construido}
{4318}{}{}
{4319}{}{Lo siento, tengo que hacer esto}
{4320}{}{¡Maldito seas por hacerme hacer esto!}
{4321}{}{Me das lástima}
{4322}{}{No puedo dejarte ganar}
{4323}{}{Eres tan torpe como violento}
{4324}{}{Sabemos cómo cuidarnos a nosotros mismos}
{4325}{}{Ahora me toca a mí}
{4326}{}{Este ha sido tu último error}
{4327}{}{}
{4328}{}{Maldita sea, me pica}
{4329}{}{Se me ha partido el pómulo. No pararé por eso}
{4330}{}{Creo que tengo la nariz destrozada}
{4331}{}{¡Mi brazo!}
{4332}{}{El miembro está inutilizado. Tengo que seguir}
{4333}{}{¡Maldita sea! Debo de estar malherida}
{4334}{}{¡Mi brazo!}
{4335}{}{El miembro está inutilizado. Tengo que seguir}
{4336}{}{¡Maldita sea! Debo de estar malherida}
{4337}{}{}
{4338}{}{¡Uf!}
{4339}{}{}
{4340}{}{}
{4341}{}{[Jadea fuertemente]}
{4342}{}{¡Ack!}
{4343}{}{¡Ow!}
{4344}{}{¡Uff! Puedes derrotarme, pero la causa seguirá viva}
{4345}{}{¡Agh!}
{4346}{}{}
{4347}{}{¡Mi pierna!}
{4348}{}{Maldita sea, justo en la rodilla...}
{4349}{}{}
{4350}{}{¡Mi pierna!}
{4351}{}{Maldita sea, justo en la rodilla...}
{4352}{}{Estoy sin pierna, ¡pero seguiré luchando!}
{4353}{}{¡Estoy ciega! Nada me detendrá...}
{4354}{}{¡Estoy ciego!}
{4355}{}{¡No veo!}
{4356}{}{¡AAUGH!!}
{4357}{}{}
{4358}{}{¡Uf!}
{4359}{}{}
{4360}{}{¡Ahh!}
{4361}{}{}
{4400}{}{¡Pronto morirás!}
{4401}{}{¡Volveré!}
{4402}{}{¡Hasta luego, mocoso!}
{4403}{}{}
{4404}{}{¡Te reservaré para más tarde!}
{4405}{}{}
{4406}{}{¡Voy a arrancarte la cabeza!}
{4407}{}{¡Carne fresca!}
{4408}{}{}
{4409}{}{}
{4410}{}{¡Te comeré de un solo bocado!}
{4411}{}{}
{4412}{}{¡Voy a trincharte como si fueras carne de iguana en un pincho!}
{4413}{}{}
{4414}{}{No te mueras todavía. Quiero que sufras.}
{4415}{}{¡Has ofendido al Rey del Cementerio de LA!}
{4416}{}{}
{4417}{}{Estarás tan guapo cuando mueras...}
{4418}{}{¡Muere, muere, muere, muere!}
{4419}{}{}
{4420}{}{Esta noche servirás de alimento a los gusanos.}
{4421}{}{¡Te despellejaré vivo!}
{4422}{}{}
{4423}{}{¡Venga! ¡Inténtalo de nuevo, mamón!}
{4424}{}{Venga, mocoso. ¡Pelea conmigo!}
{4425}{}{¿Eso es todo lo que sabes hacer?}
{4426}{}{¡No eres nadie!}
{4427}{}{¡No puedo ser asesinado!}
{4428}{}{}
{4429}{}{}
{4430}{}{¡Ack!}
{4431}{}{Me encanta el sonido de los huesos cuando crujen}
{4432}{}{}
{4433}{}{¡Me gustan fuertes, cariñito!}
{4434}{}{¡Mi brazo!}
{4435}{}{}
{4436}{}{¡Bastardo! ¡Mi brazo!}
{4437}{}{¡Mi pecho!}
{4438}{}{¡Ah! Ese ha sido tu último error}
{4439}{}{}
{4440}{}{[Jadea fuertemente]}
{4441}{}{¡Bah!}
{4442}{}{¡Ahh! Eso va a dejar una bonita magulladura}
{4443}{}{¡Ow!}
{4444}{}{¡Idiota!}
{4445}{}{Podemos intercambiar golpes durante todo el día}
{4446}{}{}
{4447}{}{Me encanta el sonido de los huesos cuando crujen}
{4448}{}{}
{4449}{}{}
{4450}{}{¡Mi pierna!}
{4451}{}{}
{4452}{}{¡Te maldigo!}
{4453}{}{}
{4454}{}{¡Solo tengo que oler tu miedo!}
{4455}{}{¡Mis ojos! Tío, me gusta tu forma de luchar}
{4456}{}{¡Ahh! ¡Mi entrepierna!}
{4457}{}{}
{4458}{}{¡Ohhh! ¿Eso es una proposición, encanto?}
{4459}{}{}
{4460}{}{Conque así es como quieres que juguemos}
{4461}{}{}
{4500}{}{¡Me largo de aquí!}
{4501}{}{}
{4502}{}{}
{4503}{}{¡No ganarás!}
{4504}{}{}
{4505}{}{Te veré por aquí}
{4506}{}{¡Al ataque!}
{4507}{}{¡Eres historia!}
{4508}{}{¡No sabes con quién te metes!}
{4509}{}{Nadie se pone a hacer musculitos en nuestro césped!}
{4510}{}{}
{4511}{}{}
{4512}{}{¡Soy tu Maestro!}
{4513}{}{¡Muere!}
{4514}{}{Canalla}
{4515}{}{De ahí viene nuestro nombre}
{4516}{}{Voy a escribir tu epitafio}
{4517}{}{¡Espero que te duela!}
{4518}{}{}
{4519}{}{}
{4520}{}{Te enterraré}
{4521}{}{Estás muerto}
{4522}{}{¡Soy más recto que el mismo Dios!}
{4523}{}{}
{4524}{}{¡Demuestra que tienes pelotas!}
{4525}{}{¡Eres tan débil como un Destripador!}
{4526}{}{}
{4527}{}{¡Tú no eres un Navaja!}
{4528}{}{}
{4529}{}{¡Mis ojos!}
{4530}{}{¡Auh! ¡Has destrozado mi nariz!}
{4531}{}{¡Ow!}
{4532}{}{¡Ow! ¡Mi brazo!}
{4533}{}{¡Ay! ¡Me lo has roto!}
{4534}{}{¡Ow!}
{4535}{}{¡Ow! ¡Mi brazo!}
{4536}{}{¡Ay! ¡Me lo has roto!}
{4537}{}{¡Ow!}
{4538}{}{¡Ay! ¡Mi pecho!}
{4539}{}{¡Uff! ¡Mis costillas!}
{4540}{}{Grrr}
{4541}{}{¡Me río de mi dolor!}
{4542}{}{[Jadea fuertemente]}
{4543}{}{¿Eso es todo lo fuerte que sabes pegar?}
{4544}{}{}
{4545}{}{¡Uf!}
{4546}{}{}
{4547}{}{¡Ow!}
{4548}{}{¡Oh! ¡Mi rodilla!}
{4549}{}{¡Oh! ¡Mi pierna!}
{4550}{}{¡Ow!}
{4551}{}{¡Oh! ¡Mi rodilla!}
{4552}{}{¡Oh! ¡Mi pierna!}
{4553}{}{¡Estoy ciego!}
{4554}{}{¡No veo!}
{4555}{}{¡Mis ojos! Hijo de Destripador...}
{4556}{}{¡Ohhhhh, la ingle!}
{4557}{}{¡Ayyy!}
{4558}{}{Joder, cómo duele}
{4559}{}{¡Uf!}
{4560}{}{Voy a hacerte pedacitos}
{4561}{}{No... puedo... respirar...}
{4600}{}{}
{4601}{}{}
{4602}{}{¡Solo es un respiro, mocoso!}
{4603}{}{¡No ganarás!}
{4604}{}{¡No te rías! Voy a mear sobre tu tumba}
{4605}{}{Te veré por aquí}
{4606}{}{}
{4607}{}{}
{4608}{}{¡No sabes con quién te metes!}
{4609}{}{}
{4610}{}{}
{4611}{}{¡Muere!}
{4612}{}{}
{4613}{}{¡Muere!}
{4614}{}{}
{4615}{}{¿De qué tamaño quieres la cicatriz?}
{4616}{}{}
{4617}{}{¡Espero que te duela!}
{4618}{}{}
{4619}{}{}
{4620}{}{Te enterraré}
{4621}{}{Estás muerto}
{4622}{}{¡Soy tu Maestro!}
{4623}{}{}
{4624}{}{¡Demuestra que tienes pelotas!}
{4625}{}{¡Eres mío!}
{4626}{}{}
{4627}{}{}
{4628}{}{Eso duele}
{4629}{}{¡Mis ojos!}
{4630}{}{¡Ay! Mi nariz...}
{4631}{}{¡Ow!}
{4632}{}{¡Ow! ¡Mi brazo!}
{4633}{}{¡Ay! ¡Me lo has roto!}
{4634}{}{¡Ow!}
{4635}{}{¡Ow! ¡Mi brazo!}
{4636}{}{¡Ay! ¡Me lo has roto!}
{4637}{}{¡Ow!}
{4638}{}{¡Ay! ¡Mi pecho!}
{4639}{}{¡Uff! ¡Mis costillas!}
{4640}{}{Grrr}
{4641}{}{¡Ja! ¡Me río del dolor!}
{4642}{}{[Jadea fuertemente]}
{4643}{}{}
{4644}{}{}
{4645}{}{¡Uf!}
{4646}{}{¡Oh, sí, eso me ha despertado!}
{4647}{}{¡Ow!}
{4648}{}{¡Oh! ¡Mi rodilla!}
{4649}{}{¡Oh! ¡Mi pierna!}
{4650}{}{¡Ow!}
{4651}{}{¡Oh! ¡Mi rodilla!}
{4652}{}{¡Oh! ¡Mi pierna!}
{4653}{}{¡Estoy ciego!}
{4654}{}{¡No veo!}
{4655}{}{¡Mis ojos! Hijo de Destripador...}
{4656}{}{¡Ohhhhh, la ingle!}
{4657}{}{¡Ayyy!}
{4658}{}{Joder, cómo duele}
{4659}{}{¡Uf!}
{4660}{}{Voy a hacerte pedacitos}
{4661}{}{No... puedo... respirar...}
{4700}{}{}
{4701}{}{Puede que no fuera una buena idea}
{4702}{}{}
{4703}{}{}
{4704}{}{¡No voy a morir por esto!}
{4705}{}{No puedo creer lo que están haciendo...}
{4706}{}{Hora de vaciar el cargador...}
{4707}{}{¡Alguien acaba de cometer un gran error!}
{4708}{}{}
{4709}{}{¿Quién te crees que eres?}
{4710}{}{Hora de enseñar la mercancía}
{4711}{}{}
{4712}{}{}
{4713}{}{¡A practicar la puntería!}
{4714}{}{}
{4715}{}{¿Qué te parece esto?}
{4716}{}{}
{4717}{}{¿Qué tal la potencia de fuego?}
{4718}{}{Veamos cómo respondes a esto...}
{4719}{}{}
{4720}{}{}
{4721}{}{¡Llévate contigo mis balas al infierno!}
{4722}{}{}
{4723}{}{}
{4724}{}{No esperabas eso, ¿verdad?}
{4725}{}{Ese fue tu último error}
{4726}{}{Aficionado}
{4727}{}{¡Tus movimientos son débiles!}
{4728}{}{¡Oh! Hijo de...}
{4729}{}{Te mataré por esto}
{4730}{}{¡Te arrancaré la cabeza!}
{4731}{}{¡Oh, mi brazo!}
{4732}{}{Maldita sea. ¡Tengo el brazo destrozado!}
{4733}{}{¡Mi brazo!}
{4734}{}{¡Oh, mi brazo!}
{4735}{}{Maldita sea. ¡Tengo el brazo destrozado!}
{4736}{}{¡Mi brazo!}
{4737}{}{¡Ow!}
{4738}{}{¡Ay! ¡Mi pecho!}
{4739}{}{¡Uff! ¡Mis costillas!}
{4740}{}{}
{4741}{}{}
{4742}{}{}
{4743}{}{}
{4744}{}{Puede que requiera atención médica... }
{4745}{}{}
{4746}{}{¡Uf!}
{4747}{}{¡Oh, mi pierna!}
{4748}{}{¡Me las pagarás por esto!}
{4749}{}{¡Mi rodilla!}
{4750}{}{¡Oh, mi pierna!}
{4751}{}{¡Me las pagarás por esto!}
{4752}{}{¡Mi rodilla!}
{4753}{}{¡No veo!}
{4754}{}{¡Mi ojo! ¡Me las vas a pagar!}
{4755}{}{}
{4756}{}{¡Ohhhhh, la ingle!}
{4757}{}{Conque así es como quieres jugar}
{4758}{}{}
{4759}{}{¡Urp!}
{4760}{}{}
{4761}{}{¡Cerdo!}
{4800}{}{¡Necesito refuerzos!}
{4801}{}{¡Que alguien me ayude!}
{4802}{}{¡Un médico!}
{4803}{}{¡Retirada! ¡Retirada!}
{4804}{}{¡Retrocede! ¡Retrocede!}
{4805}{}{¡Reagrupamiento!}
{4806}{}{Me encargaré de esto}
{4807}{}{¡Nos atacan!}
{4808}{}{}
{4809}{}{¡Al ataque!}
{4810}{}{}
{4811}{}{¡A las armas! ¡A las armas!}
{4812}{}{¡Esto es por Adytum!}
{4813}{}{¡Esto es lo que hacemos con los animales!}
{4814}{}{Bienvenido al infierno, mocoso}
{4815}{}{Disfruta de tus dos últimos segundos de vida...}
{4816}{}{Nunca volverás a molestar a nadie}
{4817}{}{}
{4818}{}{No deberías haber empezado esto}
{4819}{}{}
{4820}{}{}
{4821}{}{¡Estás acabado, mocoso!}
{4822}{}{}
{4823}{}{Apuntas a tu manera, mocoso}
{4824}{}{}
{4825}{}{}
{4826}{}{Ese era de broma, ¿verdad?}
{4827}{}{No soy fácil de matar...}
{4828}{}{¡Maldita sea! Justo en la cara.}
{4829}{}{¡Mi cara!}
{4830}{}{¡Mi nariz!}
{4831}{}{¡Maldita sea! ¡Mi brazo!}
{4832}{}{¡Oh! ¡Me duele!}
{4833}{}{Maldita sea, deben haberme malherido}
{4834}{}{¡Maldita sea! ¡Mi brazo!}
{4835}{}{¡Oh! ¡Me duele!}
{4836}{}{Maldita sea, deben haberme malherido}
{4837}{}{¡Ow!}
{4838}{}{¡Ay! ¡Justo en el pecho!}
{4839}{}{¡Uff! ¡Me has dado en las costillas!}
{4840}{}{¡Uf!}
{4841}{}{}
{4842}{}{¡Uff! ¡Justo en la tripa!}
{4843}{}{¡Agh!}
{4844}{}{¡Ay!}
{4845}{}{¡Uf!}
{4846}{}{Necesito... aire...}
{4847}{}{¡Buen tiro!}
{4848}{}{Maldita sea, justo en la rodilla...}
{4849}{}{No voy a caerme, mocoso}
{4850}{}{¡Buen tiro!}
{4851}{}{Maldita sea, justo en la rodilla...}
{4852}{}{No voy a caerme, mocoso}
{4853}{}{Maldita sea, algo va mal...}
{4854}{}{¡Maldita sea, justo en los ojos!}
{4855}{}{¡No veo!}
{4856}{}{¡Ohhhhh, la ingle!}
{4857}{}{}
{4858}{}{¡Cómo me duele, maldición!}
{4859}{}{No... puedo... respirar...}
{4860}{}{Eres un sádico hijo de...}
{4861}{}{Mamón}
{4900}{}{¡Hay que largarse de aquí!}
{4901}{}{}
{4902}{}{¡Piedad! ¡Misericordia!}
{4903}{}{}
{4904}{}{}
{4905}{}{}
{4906}{}{¡¿Por qué me ocurren estas cosas?!}
{4907}{}{¿Dónde está mi retaguardia?}
{4908}{}{¡Podría usar algo de ayuda aquí!}
{4909}{}{}
{4910}{}{}
{4911}{}{}
{4912}{}{No te tomes esto como algo personal}
{4913}{}{}
{4914}{}{}
{4915}{}{}
{4916}{}{Supongo que tengo que herirte}
{4917}{}{Por favor, baja}
{4918}{}{Por favor, no me mates por esto}
{4919}{}{}
{4920}{}{Creo que voy a vomitar}
{4921}{}{}
{4922}{}{¡Estoy vivo! ¡Vivo!}
{4923}{}{}
{4924}{}{Tienes que apuntar un poquito más a la derecha}
{4925}{}{}
{4926}{}{Hoy no es tu día}
{4927}{}{}
{4928}{}{¡En la cara no!}
{4929}{}{¡Ay, mi cabeza!}
{4930}{}{¡Me has roto la nariz!}
{4931}{}{¡Oh, mi brazo!}
{4932}{}{¡Me has roto el brazo!}
{4933}{}{¿Ha sido eso realmente necesario?}
{4934}{}{¡Oh, mi brazo!}
{4935}{}{¡Me has roto el brazo!}
{4936}{}{¿Ha sido eso realmente necesario?}
{4937}{}{¡Uf!}
{4938}{}{¡Ay, me duele mucho!}
{4939}{}{}
{4940}{}{[Jadea fuertemente] ¡No me des!}
{4941}{}{¡Ahh! ¡Cómo duele!}
{4942}{}{¡Ah! ¡Para, por favor!}
{4943}{}{¡Ay!}
{4944}{}{¡Uf!}
{4945}{}{¡Uf!}
{4946}{}{¡Uff! [Jadea fuertemente] ¡Ohh! ¡Ay! ¡Ayayai!}
{4947}{}{¡Oh, mi pierna!}
{4948}{}{¡Ey, cómo duele!}
{4949}{}{}
{4950}{}{¡Oh, mi pierna!}
{4951}{}{¡Ey, cómo duele!}
{4952}{}{¿Ha sido eso realmente necesario?}
{4953}{}{¡Agh! ¡La retina!}
{4954}{}{¡Mi ojo! ¡Oh, dios mío, estoy ciego!}
{4955}{}{¡Por qué es tan cruel la vida!}
{4956}{}{¡Ohhhhh, la ingle!}
{4957}{}{¡Ohh! ¡Me duele!}
{4958}{}{Eso no ha sido muy amistoso.}
{4959}{}{}
{4960}{}{¡Urp!}
{4961}{}{}
{5000}{}{¡Me largo de aquí!}
{5001}{}{}
{5002}{}{¡Aaaaahhhh!}
{5003}{}{}
{5004}{}{}
{5005}{}{Te veré por aquí}
{5006}{}{}
{5007}{}{}
{5008}{}{Alguien se merece una lección}
{5009}{}{Alguien se muere}
{5010}{}{}
{5011}{}{}
{5012}{}{}
{5013}{}{¡Muere!}
{5014}{}{¡Muerte y fuego!}
{5015}{}{Punk}
{5016}{}{¡Fuego atómico!}
{5017}{}{}
{5018}{}{Nunca debiste mezclarte con nosotros}
{5019}{}{¡Irás al Ardor!}
{5020}{}{Voy a sellar tu tumba}
{5021}{}{¡Estás muerto!}
{5022}{}{}
{5023}{}{No me causa buena impresión}
{5024}{}{}
{5025}{}{Estoy cavando tu tumba}
{5026}{}{¡No vas a enterrarme!}
{5027}{}{¿Qué esperabas?}
{5028}{}{}
{5029}{}{¡Mis ojos!}
{5030}{}{¡Ow!}
{5031}{}{¡Ow!}
{5032}{}{¡Ow! ¡Mi brazo!}
{5033}{}{¡Ay! ¡Me lo has roto!}
{5034}{}{¡Ow!}
{5035}{}{¡Ow! ¡Mi brazo!}
{5036}{}{}
{5037}{}{¡Ow!}
{5038}{}{¡Uf!}
{5039}{}{¡Ay!}
{5040}{}{¡Gack!}
{5041}{}{¡Agh!}
{5042}{}{¡Grrr!}
{5043}{}{}
{5044}{}{¡Me comeré tu hígado por eso!}
{5045}{}{}
{5046}{}{¡Uf!}
{5047}{}{¡Ow!}
{5048}{}{¡Oh! ¡Mi rodilla!}
{5049}{}{¡Oh! ¡Mi pierna!}
{5050}{}{¡Ow!}
{5051}{}{¡Oh! ¡Mi rodilla!}
{5052}{}{¡Oh! ¡Mi pierna!}
{5053}{}{¡Estoy ciego!}
{5054}{}{¡No veo!}
{5055}{}{¡Mi ojo!}
{5056}{}{¡Ohhhhh, la ingle!}
{5057}{}{¡Ohh! ¡Me duele!}
{5058}{}{Eso no ha sido muy amistoso.}
{5059}{}{}
{5060}{}{¡Urp!}
{5061}{}{}
{5100}{}{¡Retirada!}
{5101}{}{¡Retirada!}
{5102}{}{¡Reagrupamiento!}
{5103}{}{¡Esto no ha terminado!}
{5104}{}{¡Volveré!}
{5105}{}{¡Volveremos!}
{5106}{}{}
{5107}{}{}
{5108}{}{¡Capturad al intruso!}
{5109}{}{¡Muerte al humano!}
{5110}{}{}
{5111}{}{}
{5112}{}{¡Irás al Ardor!}
{5113}{}{}
{5114}{}{¡Humano mugriento!}
{5115}{}{}
{5116}{}{}
{5117}{}{¡Muerte y fuego!}
{5118}{}{¡Arderás!}
{5119}{}{}
{5120}{}{¡Vas a caer y no podrás levantarte nunca!}
{5121}{}{Voy a sellar tu tumba}
{5122}{}{No has dado en el blanco}
{5123}{}{¡Nadie sellará mi tumba!}
{5124}{}{No eres un luchador}
{5125}{}{}
{5126}{}{No ganarás, humano}
{5127}{}{}
{5128}{}{Eso duele}
{5129}{}{¡Mis ojos!}
{5130}{}{¡Ahh!}
{5131}{}{¡Ahh!}
{5132}{}{¡Ow! ¡Mi brazo!}
{5133}{}{¡Ay! ¡Me lo has roto!}
{5134}{}{¡Ahh!}
{5135}{}{¡Ow! ¡Mi brazo!}
{5136}{}{¡Ay! ¡Me lo has roto!}
{5137}{}{¡Ow!}
{5138}{}{¡Uf!}
{5139}{}{¡Ay!}
{5140}{}{¡Gack!}
{5141}{}{¡Agh!}
{5142}{}{¡Grrr!}
{5143}{}{¡Uf! Todos los esqueléticos sois iguales}
{5144}{}{¡Me comeré tu hígado por eso!}
{5145}{}{}
{5146}{}{¡Uf!}
{5147}{}{¡Ahh!}
{5148}{}{¡Oh! ¡Mi rodilla!}
{5149}{}{¡Oh! ¡Mi pierna!}
{5150}{}{¡Ahh!}
{5151}{}{¡Oh! ¡Mi rodilla!}
{5152}{}{¡Oh! ¡Mi pierna!}
{5153}{}{¡Te maldigo con fuego!}
{5154}{}{¡No veo!}
{5155}{}{¡Mi ojo!}
{5156}{}{¡Ohhhhh, la ingle!}
{5157}{}{¡Uf!}
{5158}{}{¡Destrozaré tu tumba!}
{5159}{}{}
{5160}{}{¡Urp!}
{5161}{}{}
{5200}{}{¡Corred!}
{5201}{}{¡No me matarás!}
{5202}{}{¡Volveré!}
{5203}{}{¡Mis amigos te cogerán por mí!}
{5204}{}{Pagarás por eso... ¡luego!}
{5205}{}{¡Somos los Elegidos! ¡Morirás pronto!}
{5206}{}{¡Se acerca el momento de tu muerte!}
{5207}{}{¡Los que molestan a los Elegidos, no vuelven a molestar nunca a nadie!}
{5208}{}{¡Las armas humanas no me hacen daño!}
{5209}{}{¡Vas a sufrir, mucho!}
{5210}{}{}
{5211}{}{¿Quién es lo bastante estúpido para enfadarnos?}
{5212}{}{}
{5213}{}{¡Nadie te salvará ahora!}
{5214}{}{}
{5215}{}{¡Tendrás una muerte a fuego!}
{5216}{}{¡Muere, humano idiota!}
{5217}{}{Ahora grita hasta la muerte}
{5218}{}{}
{5219}{}{Ahora te aplastaré}
{5220}{}{¡No puedes luchar contra los Elegidos!}
{5221}{}{¡Sufre, humano!}
{5222}{}{¿Por qué luchas?}
{5223}{}{¡Eso es todo lo que los humanos pueden hacer!}
{5224}{}{¡No tienes poder!}
{5225}{}{¡Me desternillas!}
{5226}{}{¿Ha sido eso un ataque?}
{5227}{}{¡Somos los Elegidos!}
{5228}{}{¡Ahhhh! ¡Mi cara!}
{5229}{}{¡Mi cara! ¡Sufrirás!}
{5230}{}{¡Ahhh! ¡Voy a despedazarte!}
{5231}{}{¡Ahhhh!}
{5232}{}{}
{5233}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5234}{}{¡Ahhhh!}
{5235}{}{}
{5236}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5237}{}{¡Uf!}
{5238}{}{¡Grrr!}
{5239}{}{¡Te mataré por eso!}
{5240}{}{¡No me harás daño cuando estés muerto!}
{5241}{}{¡Tu debilucho ataque me da risa!}
{5242}{}{¡Grrr!}
{5243}{}{¡Oh!}
{5244}{}{¡Voy a darte un bañito!}
{5245}{}{¡Grrr! Haces que me enfade}
{5246}{}{Agh!}
{5247}{}{¡Ahhh! ¡Mi pierna!}
{5248}{}{}
{5249}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5250}{}{¡Ahhh! ¡Mi pierna!}
{5251}{}{}
{5252}{}{¡Ahhh! ¡Te retorceré el cuello por esto!}
{5253}{}{¡Ahhhgh! ¡Humano miserable! ¡Estoy ciego!}
{5254}{}{¡Ahhh! ¡Qué dolor! ¡Qué has hecho!}
{5255}{}{¡Ahhh! ¡Te torturaré durante días!}
{5256}{}{¡Eso es debilidad humana!}
{5257}{}{}
{5258}{}{¡Eres estúpido, humano!}
{5259}{}{¿Por qué me atacas ahí?}
{5260}{}{Te haré daño durante horas}
{5261}{}{}
{5300}{}{¡Corred!}
{5301}{}{¡No me matarás!}
{5302}{}{Tengo que escapar}
{5303}{}{}
{5304}{}{Pagarás por eso... ¡luego!}
{5305}{}{¡Morirás más tarde!}
{5306}{}{¿Quién osa molestar a los Elegidos?}
{5307}{}{¡Me haces enfadar!}
{5308}{}{¡Las armas humanas no me hacen daño!}
{5309}{}{}
{5310}{}{¡No hay piedad para los enemigos!}
{5311}{}{¡Cuando lucho, mato!}
{5312}{}{}
{5313}{}{¡Nadie te salvará ahora!}
{5314}{}{¡Ahora es cuando mueres!}
{5315}{}{¡Deja que vea tu dolor!}
{5316}{}{¡Romperé tu cuerpo!}
{5317}{}{}
{5318}{}{}
{5319}{}{Ahora muere}
{5320}{}{¡Te haré mucho daño!}
{5321}{}{¡Sufre!}
{5322}{}{¡Eres débil!}
{5323}{}{Eres poca cosa...}
{5324}{}{¡No tienes poder!}
{5325}{}{}
{5326}{}{¿Ha sido eso un ataque?}
{5327}{}{No sirves para nada}
{5328}{}{¡Ahhhh! ¡Mi cara!}
{5329}{}{¡Mi cara! ¡Sufrirás!}
{5330}{}{¡Ahhh! ¡Voy a despedazarte!}
{5331}{}{¡Ahhhh!}
{5332}{}{¡Ay! ¡Casi hieres al Elegido!}
{5333}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5334}{}{¡Ahhhh!}
{5335}{}{}
{5336}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5337}{}{¡Te devolveré todo este dolor!}
{5338}{}{¡Uf!}
{5339}{}{¡Ay!}
{5340}{}{¡Mmm, puedes tener problemas!}
{5341}{}{¡Grrr! Estoy deseando que mueras}
{5342}{}{¡Grrr!}
{5343}{}{¡Puedes herirme pero no vas a ganar!}
{5344}{}{¡Grrr!}
{5345}{}{¡Auh! No ha sido buena idea herirme}
{5346}{}{}
{5347}{}{¡Ahhh! ¡Mi pierna!}
{5348}{}{}
{5349}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5350}{}{¡Ahhh! ¡Mi pierna!}
{5351}{}{¡Casi haces daño a un Elegido!}
{5352}{}{¡Ahhh! ¡Te retorceré el cuello por esto!}
{5353}{}{¡Ahhhgh! ¡Estoy ciego!}
{5354}{}{¡Ahhhh! ¡Qué dolor! ¡Qué me haces!}
{5355}{}{¡Ahhhh! ¡Los ojos me queman como fuego del Ardor!}
{5356}{}{¡Eso es debilidad humana!}
{5357}{}{}
{5358}{}{}
{5359}{}{¿Por qué me atacas ahí?}
{5360}{}{¡Tu muerte será dolorosa, humano!}
{5361}{}{}
{5400}{}{¡Corred!}
{5401}{}{¡No me matarás!}
{5402}{}{¡Volveré!}
{5403}{}{}
{5404}{}{Pagarás por eso... ¡luego!}
{5405}{}{¡Morirás más tarde!}
{5406}{}{¡Se acerca el momento de tu muerte!}
{5407}{}{}
{5408}{}{¡Las armas humanas no me hacen daño!}
{5409}{}{¡Vas a sufrir, mucho!}
{5410}{}{¡Veo enemigos que destruir!}
{5411}{}{¿Quién es lo bastante estúpido para enfadarnos?}
{5412}{}{}
{5413}{}{¡Nadie te salvará ahora!}
{5414}{}{¡Somos tus Maestros!}
{5415}{}{¡Ahora tendrás una muerte de fuego!}
{5416}{}{¡Muere, humano idiota!}
{5417}{}{Ahora grita hasta la muerte}
{5418}{}{}
{5419}{}{Ahora te aplastaré}
{5420}{}{}
{5421}{}{¡Sufre, humano!}
{5422}{}{¿Por qué luchas?}
{5423}{}{¡Eso es todo lo que los humanos pueden hacer!}
{5424}{}{¡No tienes poder!}
{5425}{}{}
{5426}{}{}
{5427}{}{¡Somos los Elegidos!}
{5428}{}{¡Ahhhh! ¡Mi cara!}
{5429}{}{¡Mi cara! ¡Sufrirás!}
{5430}{}{¡Ahhh! ¡Voy a despedazarte!}
{5431}{}{¡Ahhhh!}
{5432}{}{¿A eso lo llamas dolor? ¡Me das risa!}
{5433}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5434}{}{¡Ahhhh!}
{5435}{}{¿A eso lo llamas dolor? ¡Me das risa!}
{5436}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5437}{}{¡No hay dolor!}
{5438}{}{¡Uff! Te mataré}
{5439}{}{¡Odio a los que son como tú!}
{5440}{}{}
{5441}{}{¡Agh!}
{5442}{}{¡Grrr!}
{5443}{}{¡Ay! ¡Yo mismo me encargaré de ti!}
{5444}{}{}
{5445}{}{¡Grrr!}
{5446}{}{¡Uf!}
{5447}{}{¡Ahhh! ¡Mi pierna!}
{5448}{}{¿A eso lo llamas dolor? ¡Me das risa!}
{5449}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5450}{}{¡Ahhh! ¡Mi pierna!}
{5451}{}{¿A eso lo llamas dolor? ¡Me das risa!}
{5452}{}{¡Ahhh! ¡Te retorceré el cuello por esto!}
{5453}{}{¡Ahhhgh! ¡Humano miserable! ¡Estoy ciego!}
{5454}{}{¡Ahhh! ¡Qué dolor! ¡Qué has hecho!}
{5455}{}{¡Ahhh! ¡Te torturaré durante días!}
{5456}{}{}
{5457}{}{}
{5458}{}{¡Eres un humano estúpido!}
{5459}{}{¿Por qué me atacas ahí?}
{5460}{}{Te haré daño durante horas}
{5461}{}{}
{5500}{}{¡Corred!}
{5501}{}{¡No me matarás!}
{5502}{}{¡Volveré!}
{5503}{}{¡Esto no se ha terminado!}
{5504}{}{¡La victoria te durará poco!}
{5505}{}{¡Somos los Elegidos! ¡Morirás luego!}
{5506}{}{¡Un paso al frente, la muerte viaja con nosotros!}
{5507}{}{}
{5508}{}{¡Las armas humanas no nos hacen daño!}
{5509}{}{¡Vas a sufrir!}
{5510}{}{¡Nadie nos resistirá!}
{5511}{}{}
{5512}{}{}
{5513}{}{Nadie puede salvarte}
{5514}{}{¡Somos tus Maestros!}
{5515}{}{¡Ahora tendrás una muerte a fuego lento!}
{5516}{}{¡Muere, humano idiota!}
{5517}{}{Ahora puedes gritar hasta la muerte}
{5518}{}{¡Tu sangre es mi vino!}
{5519}{}{Ahora te aplastaré}
{5520}{}{¡No puedes luchar contra los Elegidos!}
{5521}{}{¡Sufre, humano!}
{5522}{}{¿Por qué luchas de forma tan lamentable?}
{5523}{}{}
{5524}{}{¿Llamas lucha a esta tontería vacilante?}
{5525}{}{Tu forma de atacar solo me hace reír.}
{5526}{}{}
{5527}{}{}
{5528}{}{¡Ahhhh! ¡Mi cara!}
{5529}{}{¡Mi cara! ¡Sufrirás!}
{5530}{}{¡Ahhh! ¡Voy a despedazarte!}
{5531}{}{¡Ahhhh!}
{5532}{}{¿A eso lo llamas dolor? ¡Me das risa!}
{5533}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5534}{}{¡Ahhhh!}
{5535}{}{}
{5536}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5537}{}{¡No puedes derrotarme!}
{5538}{}{¡Te mataré por esto!}
{5539}{}{¡Tu muerte será leyenda!}
{5540}{}{¡Estoy muy enfadado!}
{5541}{}{¡Uf!}
{5542}{}{¡Grrr!}
{5543}{}{¡Uf! No sobrevivirás}
{5544}{}{}
{5545}{}{No tienes ni idea de a lo que te enfrentas, humano}
{5546}{}{¡Lavaré mi cara con tu sangre!}
{5547}{}{¡Ahhh! ¡Mi pierna!}
{5548}{}{}
{5549}{}{¡Ahhhh! ¡Te retorceré el cuello!}
{5550}{}{¡Ahhh! ¡Mi pierna!}
{5551}{}{}
{5552}{}{¡Ahhh! ¡Te retorceré el cuello por esto!}
{5553}{}{¡Ahhhgh! ¡Humano miserable! ¡Estoy ciego!}
{5554}{}{¡Ahhh! Pero no necesito los ojos para matarte}
{5555}{}{¡Ahhh! ¡Te torturaré durante días!}
{5556}{}{¡Eso es debilidad humana!}
{5557}{}{}
{5558}{}{¡Eres un humano estúpido!}
{5559}{}{¿Por qué me atacas ahí?}
{5560}{}{Te haré daño durante horas}
{5561}{}{¡Esa fue la afrenta final!}
{5600}{}{¡Me largo de aquí!}
{5601}{}{¡Ten compasión!}
{5602}{}{¡Por favor, para!}
{5603}{}{¡Ayuda!}
{5604}{}{¡Aaaaahhhh!}
{5605}{}{¡Hay que huir!}
{5606}{}{}
{5607}{}{¡No nos dejas muchas opciones!}
{5608}{}{¿Quién te crees que eres?}
{5609}{}{Nadie va a tomar este lugar...}
{5610}{}{Podíamos haber hecho un trato}
{5611}{}{Ese ha sido un mal movimiento, amigo}
{5612}{}{No deberías empezar lo que no puedes terminar}
{5613}{}{¡Te lo has buscado!}
{5614}{}{}
{5615}{}{¡Sé cómo tratar a los cerdos!}
{5616}{}{¡Pagarás por lo que has hecho!}
{5617}{}{¡Ese es tu número!}
{5618}{}{}
{5619}{}{}
{5620}{}{Hora de contar tus derrotas}
{5621}{}{}
{5622}{}{¡Guau!}
{5623}{}{No vales ni veinte chapas}
{5624}{}{No eres muy bueno en esto}
{5625}{}{Eres un artículo en rebajas, mocoso}
{5626}{}{¡Deberías largarte!}
{5627}{}{}
{5628}{}{¡En la cara no!}
{5629}{}{}
{5630}{}{¡Oh! ¡Mi oído!}
{5631}{}{¡Oh, mi brazo!}
{5632}{}{¡Te maldigo!}
{5633}{}{¡Me has roto el brazo!}
{5634}{}{¡Oh, mi brazo!}
{5635}{}{¡Te maldigo!}
{5636}{}{¡Me has roto el brazo!}
{5637}{}{¡Ow!}
{5638}{}{¡Uf!}
{5639}{}{¡Ay!}
{5640}{}{¡Gack!}
{5641}{}{¡Agh!}
{5642}{}{}
{5643}{}{¡Debería haber hecho un trato!}
{5644}{}{¡Uf! Me pregunto cuánto podré sacar por tu cadáver}
{5645}{}{¡Ow!}
{5646}{}{¡Uf!}
{5647}{}{¡Oh, mi pierna!}
{5648}{}{¡Mi rodilla!}
{5649}{}{¡Oh! ¡Tengo la pierna destrozada!}
{5650}{}{¡Oh, mi pierna!}
{5651}{}{¡Mi rodilla!}
{5652}{}{¡Oh! ¡Tengo la pierna destrozada!}
{5653}{}{¡Estoy ciego!}
{5654}{}{¡Ugggh. ¡Mi cara! ¡Mis ojos!}
{5655}{}{¡Mis ojos! Ojalá te pudras en el infierno...}
{5656}{}{¡Ohhhhh, la ingle!}
{5657}{}{Ohhhhh, eso ha sido un golpe bajo, mocoso}
{5658}{}{¡Urp!}
{5659}{}{No... puedo... respirar...}
{5660}{}{}
{5661}{}{Me duele, me duele...}
{5700}{}{¡Tengo que largarme de aquí!}
{5701}{}{¡A correr, a correr!}
{5702}{}{¡Que alguien me ayude!}
{5703}{}{¡Vamos a morir todos!}
{5704}{}{Algún día, tendrás lo que te mereces}
{5705}{}{¡No voy a morir por esto!}
{5706}{}{Demasiado tarde para correr}
{5707}{}{¿Quién te ha dejado entrar en el Eje?}
{5708}{}{¡Eh, tú!}
{5709}{}{¡Por aquí no nos gustan los tipos como tú!}
{5710}{}{Nadie va a tomar este lugar...}
{5711}{}{¿Quién te crees que eres?}
{5712}{}{¡Toma esto!}
{5713}{}{¿Qué te parece esto?}
{5714}{}{¡Esto es lo que le hacemos a la gentuza!}
{5715}{}{¡Esta va por ti!}
{5716}{}{¡Adiós!}
{5717}{}{}
{5718}{}{¡Escoria alborotadora!}
{5719}{}{}
{5720}{}{¡Serás animal!}
{5721}{}{¡Te arrepentirás de haber pisado el suelo del Eje!}
{5722}{}{No eres tan bueno como te piensas}
{5723}{}{}
{5724}{}{Solo eres un delincuente común}
{5725}{}{}
{5726}{}{No voy a ser tu víctima}
{5727}{}{Ese fue tu último error}
{5728}{}{}
{5729}{}{¡Aggghhh!}
{5730}{}{¡Mi cara, mi cara!}
{5731}{}{¡Ahhh! ¡Mi brazo!}
{5732}{}{¡Mi brazo!}
{5733}{}{El maldito brazo ya no me sirve...}
{5734}{}{¡Ahhh! ¡Mi brazo!}
{5735}{}{¡Mi brazo!}
{5736}{}{El maldito brazo ya no me sirve...}
{5737}{}{¡Ow!}
{5738}{}{¡Uf!}
{5739}{}{¡Ay!}
{5740}{}{¡Gack!}
{5741}{}{¡Agh!}
{5742}{}{¡Grrr!}
{5743}{}{!}
{5744}{}{}
{5745}{}{¡Ay!}
{5746}{}{¡Uf!}
{5747}{}{¡Ahhh! ¡Mi pierna!}
{5748}{}{¡Mi pierna!}
{5749}{}{Maldición, la pierna ya no me sirve...}
{5750}{}{¡Ahhh! ¡Mi pierna!}
{5751}{}{¡Mi pierna!}
{5752}{}{Maldición, la pierna ya no me sirve...}
{5753}{}{¡Ahhh! ¡Estoy ciego!}
{5754}{}{¡Maldita sea! Todo arde...}
{5755}{}{¡Mi ojo! ¡Me las vas a pagar!}
{5756}{}{¡Ohhhhh, la ingle!}
{5757}{}{¡Ohhhhhhhhh!}
{5758}{}{No... puedo... respirar...}
{5759}{}{}
{5760}{}{Me duele, me duele...}
{5761}{}{¡Maldita sea, cómo me duele!}
{5800}{}{}
{5801}{}{¡A correr, a correr!}
{5802}{}{¡Voy a largarme de aquí!}
{5803}{}{¡Soy demasiado joven para morir!}
{5804}{}{¡A las sombras!}
{5805}{}{No me gusta esta pelea...}
{5806}{}{¡Agarremos a este canalla!}
{5807}{}{Llora como una mujer lo que no...}
{5808}{}{¡Eh, tú!}
{5809}{}{No me gusta tu actitud...}
{5810}{}{Nadie va a tomar este lugar...}
{5811}{}{¿Quién te crees que eres?}
{5812}{}{}
{5813}{}{¿Qué te parece esto?}
{5814}{}{¡Esto es lo que le hacemos a la gentuza!}
{5815}{}{Te arroparé para una siesta macabra!}
{5816}{}{¡Eres un insolente perro sarnoso!}
{5817}{}{Eres un verdadero fastidio}
{5818}{}{¡Me pones enfermo!}
{5819}{}{¡Muerte o gloria!}
{5820}{}{Vas a meterte en un lío horrible}
{5821}{}{¡Te arrepentirás de haber pisado el suelo del Eje!}
{5822}{}{Me estoy rebajando al luchar contigo}
{5823}{}{}
{5824}{}{Solo eres un delincuente común}
{5825}{}{}
{5826}{}{No deberías haber molestado}
{5827}{}{Ese fue tu último error}
{5828}{}{¡Maldita sea, cómo pica!}
{5829}{}{¡Aggghhh!}
{5830}{}{¡La cara! ¡Mi cara bonita!}
{5831}{}{¡Ahhh! ¡Mi brazo!}
{5832}{}{¡Mi brazo!}
{5833}{}{El maldito brazo ya no me sirve...}
{5834}{}{¡Ahhh! ¡Mi brazo!}
{5835}{}{¡Mi brazo!}
{5836}{}{El maldito brazo ya no me sirve...}
{5837}{}{}
{5838}{}{¡Uf!}
{5839}{}{¡Ay!}
{5840}{}{¡Uf! Me duelen las costillas}
{5841}{}{¡Maldita sea! ¡Me duele!}
{5842}{}{¡Auch! ¡Maldito seas!}
{5843}{}{¡Agh!}
{5844}{}{}
{5845}{}{}
{5846}{}{¡Uf!}
{5847}{}{¡Ahhh! ¡Mi pierna!}
{5848}{}{¡Mi pierna!}
{5849}{}{Maldición, la pierna ya no me sirve...}
{5850}{}{¡Ahhh! ¡Mi pierna!}
{5851}{}{¡Mi pierna!}
{5852}{}{Maldición, la pierna ya no me sirve...}
{5853}{}{¡Ahhh! ¡Estoy ciego!}
{5854}{}{¡Maldita sea! Todo arde...}
{5855}{}{¡¿Qué me has hecho?!}
{5856}{}{¡Ohhhhh, la ingle!}
{5857}{}{¡No eres sino un delincuente común!}
{5858}{}{}
{5859}{}{}
{5860}{}{}
{5861}{}{¡Maldita sea, cómo me duele!}
{5900}{}{¡Me largo de aquí!}
{5901}{}{¡Adiós!}
{5902}{}{¡Aaaaahhhh!}
{5903}{}{Luego, quizá.}
{5904}{}{}
{5905}{}{Te veré por aquí}
{5906}{}{}
{5907}{}{¡Defendamos nuestros hogares!}
{5908}{}{Alguien se merece una lección}
{5909}{}{Alguien se muere}
{5910}{}{}
{5911}{}{¡Nadie se mete con el Eje!}
{5912}{}{¡Toma esto!}
{5913}{}{¡Muere y quédate así!}
{5914}{}{¡Cae muerto!}
{5915}{}{Punk}
{5916}{}{¡Eres un gallina!}
{5917}{}{¡Espero que te duela!}
{5918}{}{Nunca debiste mezclarte con nosotros}
{5919}{}{¡Irás al Ardor!}
{5920}{}{¡Vete al infierno!}
{5921}{}{Estás muerto}
{5922}{}{¡Un fallo!}
{5923}{}{No me causa buena impresión}
{5924}{}{}
{5925}{}{No soy tan fácil}
{5926}{}{¡Nadie va a derrotarme!}
{5927}{}{¿Qué esperabas?}
{5928}{}{Eso duele}
{5929}{}{¡Ohh, me duele el cráneo!}
{5930}{}{¡Ow!}
{5931}{}{¡Ow!}
{5932}{}{¡Ow! ¡Mi brazo!}
{5933}{}{¡Ay! ¡Mi codo!}
{5934}{}{¡Ow!}
{5935}{}{¡Ow! ¡Mi brazo!}
{5936}{}{¡Ay! ¡Mi codo!}
{5937}{}{¡Ay! ¡Mi pecho!}
{5938}{}{¡Uf!}
{5939}{}{¡Ay!}
{5940}{}{}
{5941}{}{}
{5942}{}{¡Auch! ¡Maldito seas!}
{5943}{}{¡Agh!}
{5944}{}{¡Ow!}
{5945}{}{}
{5946}{}{¡Uf!}
{5947}{}{¡Ow!}
{5948}{}{¡Oh! ¡Mi rodilla!}
{5949}{}{¡Oh! ¡Mi pierna!}
{5950}{}{¡Ow!}
{5951}{}{¡Oh! ¡Mi rodilla!}
{5952}{}{¡Oh! ¡Mi pierna!}
{5953}{}{¡Estoy ciego!}
{5954}{}{¡No veo!}
{5955}{}{¡Mi ojo!}
{5956}{}{¡Ohhhhh, la ingle!}
{5957}{}{¡Ohh! ¡Me duele!}
{5958}{}{}
{5959}{}{}
{5960}{}{¡Urp!}
{5961}{}{}
{6000}{}{¡Ataca a otro, por favor!}
{6001}{}{¡Ten compasión!}
{6002}{}{¡Que alguien me ayude!}
{6003}{}{¡Por favor, para!}
{6004}{}{Puede que no fuera una buena idea}
{6005}{}{¡No voy a morir por esto!}
{6006}{}{Espera a que te coja...}
{6007}{}{}
{6008}{}{¡Eh, tú!}
{6009}{}{¡Por aquí no nos gustan los tipos como tú!}
{6010}{}{}
{6011}{}{Voy a tirarte como a un reloj barato}
{6012}{}{¡Toma esto!}
{6013}{}{¿Qué te parece esto?}
{6014}{}{¡Muere!}
{6015}{}{¡Monstruo mutante!}
{6016}{}{Me como a los novatos para desayunar}
{6017}{}{Vas a ser la comida de los perros}
{6018}{}{}
{6019}{}{Bien. Te lo has buscado.}
{6020}{}{}
{6021}{}{}
{6022}{}{No eres tan bueno como te piensas}
{6023}{}{¿Eso es todo lo que sabes hacer?}
{6024}{}{}
{6025}{}{}
{6026}{}{}
{6027}{}{Lamentable}
{6028}{}{¡Maldición!}
{6029}{}{¡Mi pobre cráneo dolorido!}
{6030}{}{¡Mi cara, mi cara!}
{6031}{}{¡Ahhh! ¡Mi brazo!}
{6032}{}{¡Mi brazo!}
{6033}{}{¡Oh, tío, cómo duele!}
{6034}{}{¡Ahhh! ¡Mi brazo!}
{6035}{}{¡Mi brazo!}
{6036}{}{}
{6037}{}{}
{6038}{}{¡Uf!}
{6039}{}{¡Ay!}
{6040}{}{¡Uf! Me duelen las costillas}
{6041}{}{¡Ugh! ¡Me duele!}
{6042}{}{¡Maldición! ¡Te desprecio!}
{6043}{}{¡Agh!}
{6044}{}{Oh, ¡mis costillas!}
{6045}{}{¡Oh!!!}
{6046}{}{¡Uf!}
{6047}{}{¡Ahhh! ¡Mi pierna!}
{6048}{}{¡Mi pierna!}
{6049}{}{Ahí va mi rodilla}
{6050}{}{¡Ahhh! ¡Mi pierna!}
{6051}{}{¡Mi pierna!}
{6052}{}{Ahí va mi rodilla}
{6053}{}{¡Ahhh! ¡Estoy ciego!}
{6054}{}{¡Mis ojos, mis ojos!}
{6055}{}{¡Mi ojo! ¡Me las vas a pagar!}
{6056}{}{¡Ohhhhh, la ingle!}
{6057}{}{¡Ohhhhhhhhh!}
{6058}{}{No... puedo... respirar...}
{6059}{}{}
{6060}{}{Me duele, me duele...}
{6061}{}{¡Maldita sea, cómo me duele!}
{6100}{}{¡Me largo de aquí!}
{6101}{}{Puede que no fuera una buena idea}
{6102}{}{Ataca a otro, ¿vale?}
{6103}{}{¡Ja!}
{6104}{}{¡No voy a morir por esto!}
{6105}{}{Es demasiado para mí}
{6106}{}{¡Eh, tú!}
{6107}{}{Voy a enseñarte un poco de educación}
{6108}{}{¡Por aquí no nos gustan los tipos como tú!}
{6109}{}{¡Tienes que aprender a tener algo de respeto!}
{6110}{}{Hora de ganarme mi paga...}
{6111}{}{Espera a que te coja...}
{6112}{}{}
{6113}{}{}
{6114}{}{}
{6115}{}{¿Qué te parece esto?}
{6116}{}{}
{6117}{}{}
{6118}{}{Veamos lo duro que eres...}
{6119}{}{Punk}
{6120}{}{¡Llévate contigo mis balas al infierno!}
{6121}{}{Te voy a dar una buena}
{6122}{}{Your mama teach you that move?}
{6123}{}{}
{6124}{}{No eres lo bastante bueno}
{6125}{}{Ese fue tu último error}
{6126}{}{Aficionado}
{6127}{}{¿Aprendiste a pelear en un bar?}
{6128}{}{¡Oh! Hijo de...}
{6129}{}{¡Me has roto la nariz!}
{6130}{}{¡Te arrancaré la cabeza!}
{6131}{}{¡Oh, mi brazo!}
{6132}{}{Acabas de cometer el error más grave de toda tu vida}
{6133}{}{¡Mi brazo!}
{6134}{}{¡Oh, mi brazo!}
{6135}{}{Acabas de cometer el error más grave de toda tu vida}
{6136}{}{¡Mi brazo!}
{6137}{}{¡Urp!}
{6138}{}{¡Uf!}
{6139}{}{¡Ay!}
{6140}{}{}
{6141}{}{¡Ugh! ¡Me duele!}
{6142}{}{¡Ay!}
{6143}{}{¡Agh!}
{6144}{}{¡Oh, creo que me has roto una costilla!}
{6145}{}{¡¡Ah!!! ¡Mi bazo!}
{6146}{}{¡Uf!}
{6147}{}{¡Oh, mi pierna!}
{6148}{}{¡No necesito estar de pie para matarte!}
{6149}{}{¡Mi rodilla!}
{6150}{}{¡Oh, mi pierna!}
{6151}{}{¡No necesito estar de pie para matarte!}
{6152}{}{¡Mi rodilla!}
{6153}{}{¡No veo!}
{6154}{}{Esta lucha está empeorando por momentos}
{6155}{}{¡Ese ha sido un golpe bajo!}
{6156}{}{¡Ohhhhh, la ingle!}
{6157}{}{Por la mañana recordaré este golpe}
{6158}{}{}
{6159}{}{¡Urp!}
{6160}{}{}
{6161}{}{}
{6200}{}{Volveremos a vernos, puedes apostarlo}
{6201}{}{Me debes el partido de vuelta. Más tarde}
{6202}{}{Has ganado esta vez, pero el juego no ha terminado}
{6203}{}{Te alcanzaré más tarde}
{6204}{}{Si sabes lo que te conviene, te irás de la ciudad}
{6205}{}{Esto no se ha acabado, amigo}
{6206}{}{}
{6207}{}{Voy a enseñarte un poco de educación}
{6208}{}{}
{6209}{}{¡Tienes que aprender a tener algo de respeto!}
{6210}{}{}
{6211}{}{}
{6212}{}{}
{6213}{}{}
{6214}{}{}
{6215}{}{¿Qué te parece esto?}
{6216}{}{}
{6217}{}{}
{6218}{}{Veamos lo duro que eres...}
{6219}{}{Punk}
{6220}{}{}
{6221}{}{Vas a salir disparado de la patada que te voy a dar en el culo}
{6222}{}{Estás fuera de la liga}
{6223}{}{}
{6224}{}{No eres lo bastante bueno}
{6225}{}{Deberías dejarlo ahora que todavía estás de una pieza}
{6226}{}{Aficionado}
{6227}{}{}
{6228}{}{¡Oh! Hijo de...}
{6229}{}{}
{6230}{}{¡Te arrancaré la cabeza!}
{6231}{}{¡Oh, mi brazo!}
{6232}{}{Estás empezando a fastidiarme}
{6233}{}{¡Mi brazo!}
{6234}{}{¡Oh, mi brazo!}
{6235}{}{Estás empezando a fastidiarme}
{6236}{}{¡Mi brazo!}
{6237}{}{¡Ahh!}
{6238}{}{¡Uf!}
{6239}{}{¡Ay!}
{6240}{}{¡Uff! Vas a por mis riñones, ¿eh?}
{6241}{}{}
{6242}{}{}
{6243}{}{}
{6244}{}{Oh, ¡mis costillas!}
{6245}{}{}
{6246}{}{}
{6247}{}{¡Oh, mi pierna!}
{6248}{}{Buen golpe. Espera a que sea mi turno}
{6249}{}{¡Mi rodilla!}
{6250}{}{¡Oh, mi pierna!}
{6251}{}{Buen golpe. Espera a que sea mi turno}
{6252}{}{¡Mi rodilla!}
{6253}{}{¡No veo!}
{6254}{}{Esta lucha está empeorando por momentos}
{6255}{}{}
{6256}{}{¡Ahhh!!!}
{6257}{}{}
{6258}{}{Eh, solo vale por encima del cinturón}
{6259}{}{¡Urp!}
{6260}{}{}
{6261}{}{}
{6300}{}{¡Hay que largarse de aquí!}
{6301}{}{Volveré...}
{6302}{}{¡Vas a pagar por lo que has hecho!}
{6303}{}{¡Hasta luego, mocoso!}
{6304}{}{¡Todavía no has oído la última palabra!}
{6305}{}{¡Pagarás por esto... luego!}
{6306}{}{}
{6307}{}{Carne fresca...}
{6308}{}{Bailaré sobre tu tumba}
{6309}{}{Hora de vaciar el cargador...}
{6310}{}{¡Es hora de matar!}
{6311}{}{}
{6312}{}{}
{6313}{}{Siéntete libre para gritar}
{6314}{}{Voy a divertirme con esto.}
{6315}{}{}
{6316}{}{Vas a ser la comida de los perros}
{6317}{}{Nadie nos va a arrebatar Ciudad Vertedero}
{6318}{}{}
{6319}{}{Voy a conseguir un bono por esto}
{6320}{}{¡Muere!}
{6321}{}{Me como a los novatos para desayunar}
{6322}{}{}
{6323}{}{¿Eso es todo lo que sabes hacer?}
{6324}{}{}
{6325}{}{La próxima vez intenta apuntar...}
{6326}{}{}
{6327}{}{Desgraciado}
{6328}{}{¡En la cara no!}
{6329}{}{Ah, me duele la cabeza}
{6330}{}{¡Me has roto la nariz!}
{6331}{}{¡Oh, mi brazo!}
{6332}{}{¡Me has roto el brazo!}
{6333}{}{}
{6334}{}{¡Oh, mi brazo!}
{6335}{}{¡Me has roto el brazo!}
{6336}{}{}
{6337}{}{¡Auch! Me duele}
{6338}{}{¡Uf!}
{6339}{}{¡Ay!}
{6340}{}{}
{6341}{}{¡Ugh! ¡Me duele!}
{6342}{}{}
{6343}{}{¡Uf!}
{6344}{}{Voy a darte patadas en las costillas por esto}
{6345}{}{¡Ah!}
{6346}{}{¡Uf!}
{6347}{}{¡Oh, mi pierna!}
{6348}{}{¡Me las pagarás por esto!}
{6349}{}{¡Oh, mi rodilla!}
{6350}{}{¡Oh, mi pierna!}
{6351}{}{}
{6352}{}{Oh, mi rodilla}
{6353}{}{¡Agh!}
{6354}{}{Mis ojos... mis ojos no...}
{6355}{}{¡Ese ha sido un golpe bajo!}
{6356}{}{¡Ohhhhh, la ingle!}
{6357}{}{}
{6358}{}{}
{6359}{}{}
{6360}{}{¡Urp!}
{6361}{}{¡Oh! ¡Te mataré por esto!}
{6400}{}{¡Hay que largarse de aquí!}
{6401}{}{Volveré...}
{6402}{}{¡Ayuda!}
{6403}{}{¡Hay que huir!}
{6404}{}{¡Todavía no has oído la última palabra!}
{6405}{}{}
{6406}{}{}
{6407}{}{Carne fresca...}
{6408}{}{Bienvenido a Ciudad Vertedero. ¡Bonito lugar para tu tumba!}
{6409}{}{¡Al ataque Kalaveras!}
{6410}{}{¡Es hora de matar!}
{6411}{}{Hora de vaciar el cargador...}
{6412}{}{Vamos a añadir tu calavera a nuestra colección}
{6413}{}{Siéntete libre para gritar}
{6414}{}{Voy a divertirme con esto.}
{6415}{}{}
{6416}{}{Vas a ser la comida de los perros}
{6417}{}{Nadie nos va a arrebatar Ciudad Vertedero}
{6418}{}{Espero que mueras lentamente}
{6419}{}{}
{6420}{}{¡Muere!}
{6421}{}{}
{6422}{}{}
{6423}{}{¡Soy demasiado bueno para morir!}
{6424}{}{}
{6425}{}{¡Intenta apuntar al blanco, yonqui!}
{6426}{}{}
{6427}{}{¡Ah!}
{6428}{}{¡En la cara no!}
{6429}{}{Tío, esto es peor que una resaca}
{6430}{}{¡Me has roto la nariz!}
{6431}{}{¡Oh, mi brazo!}
{6432}{}{¡Me has roto el brazo!}
{6433}{}{¡Mi brazo, mi brazo!}
{6434}{}{¡Oh, mi brazo!}
{6435}{}{¡Me has roto el brazo!}
{6436}{}{¡Mi brazo, mi brazo!}
{6437}{}{¡Tío, eso me ha dolido!}
{6438}{}{¡Uff! Te arrepentirás}
{6439}{}{[Jadea fuertemente]}
{6440}{}{[Jadea fuertemente] Necesito... aire...}
{6441}{}{Voy a escupir en tu cadáver, ¡mamón!}
{6442}{}{¡Maldición!}
{6443}{}{¡Uf!}
{6444}{}{¡Ese ha sido un golpe bajo!}
{6445}{}{¡Uf!}
{6446}{}{¡Ay!}
{6447}{}{¡Oh, mi pierna!}
{6448}{}{¡Nadie va a convertirme en un lisiado!}
{6449}{}{¡Oh, mi rodilla!}
{6450}{}{¡Oh, mi pierna!}
{6451}{}{¡Nadie va a convertirme en un lisiado!}
{6452}{}{Oh, mi rodilla}
{6453}{}{¡Agh! ¡Mis ojos!}
{6454}{}{Mis ojos... mis ojos no...}
{6455}{}{}
{6456}{}{¡Ohhhhh, la ingle!}
{6457}{}{}
{6458}{}{}
{6459}{}{}
{6460}{}{¡Urp!}
{6461}{}{¡Oh! ¡Te mataré por esto!}
{6500}{}{¡Hay que largarse de aquí!}
{6501}{}{Volveré...}
{6502}{}{¡Ayuda!}
{6503}{}{¡Hay que huir!}
{6504}{}{¡Todavía no has oído la última palabra!}
{6505}{}{¡Tendrás lo que te mereces, te lo prometo!}
{6506}{}{¡Ha terminado, mocoso! ¡Eres historia!}
{6507}{}{Nunca debiste cruzarte conmigo}
{6508}{}{Necesitas comportarte de otro modo, mocoso}
{6509}{}{Nadie tropieza con Gizmo más de una vez}
{6510}{}{Vas a morir y te enterraremos}
{6511}{}{Me estás haciendo muy infeliz}
{6512}{}{Voy a añadir tus rótulas a mi colección}
{6513}{}{Esto es lo que hago con los mocosos y los perdedores}
{6514}{}{Voy a divertirme mucho}
{6515}{}{¡Ohhh, eso va a doler!}
{6516}{}{Te has metido con el hombre equivocado}
{6517}{}{Nadie me va a apartar de Ciudad Vertedero}
{6518}{}{Espero que mueras lentamente}
{6519}{}{¡Voy a despedazarte miembro a miembro!}
{6520}{}{¡Estás muerto!}
{6521}{}{¡Prueba esto!}
{6522}{}{Realmente patético}
{6523}{}{Te vendrían bien unos Esteroides}
{6524}{}{Eres más perdedor que el propio Killian}
{6525}{}{}
{6526}{}{¡Ese ha sido tu último tiro!}
{6527}{}{}
{6528}{}{}
{6529}{}{¡Cómo me haces esto!}
{6530}{}{¡Me has roto la nariz!}
{6531}{}{Eres un asqueroso escorpión rad de...}
{6532}{}{¡Me has roto el brazo!}
{6533}{}{¡Mi brazo, mi brazo!}
{6534}{}{Eres un asqueroso escorpión rad de...}
{6535}{}{¡Me has roto el brazo!}
{6536}{}{¡Mi brazo, mi brazo!}
{6537}{}{}
{6538}{}{}
{6539}{}{¡Uf!}
{6540}{}{¡Uff! Mis costillas...}
{6541}{}{!}
{6542}{}{¡Ow!}
{6543}{}{¡Agh!}
{6544}{}{Nadie me hace eso, ¡nadie!}
{6545}{}{¡Oh!!!}
{6546}{}{¡Uf!}
{6547}{}{¡Oh, mi pierna!}
{6548}{}{Apenas... puedo... respirar...}
{6549}{}{¡Oh, mi rodilla!}
{6550}{}{¡Oh, mi pierna!}
{6551}{}{Apenas... puedo... respirar...}
{6552}{}{Oh, mi rodilla}
{6553}{}{¡Uggh! ¡Noooo!}
{6554}{}{Mis ojos... mis ojos no...}
{6555}{}{}
{6556}{}{¡Ohhhhh, la ingle!}
{6557}{}{¡Ooo! No está mal}
{6558}{}{¡Ohh! Estás cavando tu tumba, tío}
{6559}{}{¡Ohh! Estás más muerto que un albino en el Ardor}
{6560}{}{¡Urp!}
{6561}{}{¡Oh! ¡Te mataré por esto!}
{6600}{}{¡Me largo de aquí!}
{6601}{}{¡Ten compasión!}
{6602}{}{¡Por favor, para!}
{6603}{}{¡Ayuda!}
{6604}{}{¡Aaaaahhhh!}
{6605}{}{}
{6606}{}{¡Oye!}
{6607}{}{}
{6608}{}{¿Quién te crees que eres?}
{6609}{}{Nadie va a tomar este lugar...}
{6610}{}{Estás haciendo que sea muy desagradable}
{6611}{}{Eres un hijo de...}
{6612}{}{}
{6613}{}{¡Te lo has buscado!}
{6614}{}{}
{6615}{}{}
{6616}{}{¿Por qué empezaste esto?}
{6617}{}{Muere, hijo de...}
{6618}{}{No te lo tomes como algo personal...}
{6619}{}{¡Te mereces todo esto y más!}
{6620}{}{¿Te das cuenta de que tú empezaste esto?}
{6621}{}{}
{6622}{}{¡Guau!}
{6623}{}{Realmente no tienes por qué hacer esto}
{6624}{}{Eres la disculpa de los luchadores}
{6625}{}{Me recuerdas a alguien con quien solía salir}
{6626}{}{No podrás conmigo}
{6627}{}{}
{6628}{}{¡Mi cara!}
{6629}{}{Ah, me duele la cabeza}
{6630}{}{Me estás haciendo la cara un cuadro!}
{6631}{}{¡Oh, mi brazo!}
{6632}{}{¡Intentas lisiarme!}
{6633}{}{¡Mi brazo!}
{6634}{}{¡Oh, mi brazo!}
{6635}{}{¡Intentas lisiarme!}
{6636}{}{¡Me has roto el brazo!}
{6637}{}{¡Ow!}
{6638}{}{!}
{6639}{}{¡Oh! ¡Me duele!}
{6640}{}{}
{6641}{}{¡No golpees ahí a una señorita!}
{6642}{}{¡Oh!!}
{6643}{}{¡Ay!}
{6644}{}{¡Oh! Eres un trozo de...}
{6645}{}{¡AH! ¡Joder!}
{6646}{}{¡Maldito! ¡Gusano asqueroso!}
{6647}{}{¡¡¡Mi pierna!!!}
{6648}{}{¡Mi rodilla!}
{6649}{}{¡Oh! ¡Tengo la pierna destrozada!}
{6650}{}{¡Oh, mi pierna!}
{6651}{}{¡Mi rodilla!}
{6652}{}{}
{6653}{}{¡Mi cara, mi cara!}
{6654}{}{Mis... ojos... ¡MIS OJOS!}
{6655}{}{¡Bastardo! ¡Te mataré!}
{6656}{}{Deberías luchar con hombres}
{6657}{}{}
{6658}{}{¡Desperdicio del desierto!}
{6659}{}{¡Este es mi espacio personal!}
{6660}{}{¡Baboso!}
{6661}{}{¡Serás animal!}
{6700}{}{¡Necesito refuerzos!}
{6701}{}{¡Que alguien me ayude!}
{6702}{}{}
{6703}{}{¡Retirada!}
{6704}{}{¡Retrocede!}
{6705}{}{¡La próxima vez!}
{6706}{}{¡Voy!}
{6707}{}{}
{6708}{}{}
{6709}{}{No deberías haber empezado esto}
{6710}{}{Espero que los Paladines estén mirando}
{6711}{}{}
{6712}{}{}
{6713}{}{}
{6714}{}{¡Ahora es cuando mueres!}
{6715}{}{¿Qué te parece esto?}
{6716}{}{Métete con los mejores y te reunirás con los peores}
{6717}{}{No deberías empezar lo que no puedes terminar}
{6718}{}{}
{6719}{}{¡Veamos si te gusta!}
{6720}{}{}
{6721}{}{Te veré en el infierno}
{6722}{}{Acéptalo. No das la talla.}
{6723}{}{¿Eso es todo lo que sabes hacer?}
{6724}{}{¡Perdedor! ¡Lucha conmigo!}
{6725}{}{}
{6726}{}{Somos los Maestros del Combate!}
{6727}{}{No puedes tocar a la Hermandad}
{6728}{}{Iré a por ti por esto}
{6729}{}{¡Ow!}
{6730}{}{¡Me has roto la nariz!}
{6731}{}{¡Me has roto el brazo!}
{6732}{}{¡No voy a parar por un brazo destrozado!}
{6733}{}{}
{6734}{}{¡Me has roto el brazo!}
{6735}{}{¡No voy a parar por un brazo destrozado!}
{6736}{}{}
{6737}{}{¡Me has destrozado una costilla!}
{6738}{}{¡Uf!}
{6739}{}{¡Ay!}
{6740}{}{¡Uff! Conque esto es el dolor...}
{6741}{}{¡Oh! ¡Mi entrenador no me preparó para esto!}
{6742}{}{¡Uff! ¡La Hermandad me vengará si muero!}
{6743}{}{¡Ay!}
{6744}{}{}
{6745}{}{¡Oh! ¡Me duelen las costillas! ¡Iré a por ti!}
{6746}{}{¡Uf!}
{6747}{}{¡Oh, mi pierna!}
{6748}{}{¡Lo pagarás muy caro por esto!}
{6749}{}{No vas a lisiarme. Oh...}
{6750}{}{¡Oh, mi pierna!}
{6751}{}{¡Lo pagarás muy caro por esto!}
{6752}{}{No vas a lisiarme. Oh.}
{6753}{}{¡Estoy ciego!}
{6754}{}{¡Me arden los ojos!}
{6755}{}{¡No veo!}
{6756}{}{¡Ohhhhh, la ingle!}
{6757}{}{}
{6758}{}{El dolor...}
{6759}{}{No... puedo... respirar...}
{6760}{}{¡Iré a por ti!}
{6761}{}{Mamón}
{6800}{}{¡Necesito refuerzos!}
{6801}{}{Estoy fuera de esta pelea}
{6802}{}{Retrocede}
{6803}{}{¡Retirada!}
{6804}{}{¡Retrocede!}
{6805}{}{No puedo seguir aquí por más tiempo}
{6806}{}{}
{6807}{}{}
{6808}{}{Espera un momento...}
{6809}{}{No deberías haber empezado esto}
{6810}{}{}
{6811}{}{¡Allá voy!}
{6812}{}{¡Toma esto!}
{6813}{}{¡Ya te tengo!}
{6814}{}{¡Ahora es cuando mueres!}
{6815}{}{¿Qué te parece esto?}
{6816}{}{Sé cómo tratar a los tipos como tú}
{6817}{}{Esto te dejará fuera de combate}
{6818}{}{}
{6819}{}{¡Veamos si te gusta este regalito!}
{6820}{}{}
{6821}{}{}
{6822}{}{Me parece que no estás a la altura}
{6823}{}{¿Eso es todo?}
{6824}{}{Pequeño tonto estúpido}
{6825}{}{Eso ha sido patético}
{6826}{}{Me insultas con tu incompetencia}
{6827}{}{No puedes tocar a la Hermandad}
{6828}{}{¡Ah!}
{6829}{}{¡Ow!}
{6830}{}{¡Ohh, mi nariz!}
{6831}{}{Eso ha sonado a fractura}
{6832}{}{¡Ohh, mi brazo!}
{6833}{}{Mi brazo se torció por completo}
{6834}{}{Eso ha sonado a fractura}
{6835}{}{¡Ohh, mi brazo!}
{6836}{}{Mi brazo se torció por completo}
{6837}{}{}
{6838}{}{¡Uf!}
{6839}{}{}
{6840}{}{¡Uf! Dolor... mi viejo amigo}
{6841}{}{}
{6842}{}{¡Uff! ¡La Hermandad vengará mi muerte!}
{6843}{}{¡Ay!}
{6844}{}{}
{6845}{}{¡Oh! ¡Mis pobres costillas doloridas! Iré a por ti}
{6846}{}{¡Uf!}
{6847}{}{¡Oh, mi pierna!}
{6848}{}{¡Ohh, mi rodilla!}
{6849}{}{Oh...}
{6850}{}{¡Oh, mi pierna!}
{6851}{}{Ohh, mi rodilla}
{6852}{}{Oh...}
{6853}{}{¡Estoy ciego!}
{6854}{}{¡Estoy ciego! ¡Necesito ayuda!}
{6855}{}{¡Mis ojos!}
{6856}{}{¡Ohhhhh, la ingle!}
{6857}{}{Ohhhhh, me has dejado sin aire}
{6858}{}{Ohhhhh, me duele}
{6859}{}{No... puedo... respirar...}
{6860}{}{¡Estoy herido! ¡Necesito ayuda!}
{6861}{}{Me duele...}
{6900}{}{¡Necesito refuerzos!}
{6901}{}{Estoy fuera de esta pelea}
{6902}{}{Retrocede}
{6903}{}{¡Retirada!}
{6904}{}{¡Retrocede!}
{6905}{}{No puedo seguir aquí por más tiempo}
{6906}{}{¡Allá voy!}
{6907}{}{¡Este es mío!}
{6908}{}{}
{6909}{}{Una vez más en la brecha}
{6910}{}{}
{6911}{}{¡Allá voy!}
{6912}{}{Es hora de acabar con esto}
{6913}{}{¡Ya te tengo!}
{6914}{}{¡Ahora es cuando mueres!}
{6915}{}{¡Se acabó!}
{6916}{}{¡Al suelo!}
{6917}{}{Esto te dejará fuera de combate}
{6918}{}{}
{6919}{}{Veamos de qué estás hecho}
{6920}{}{Estoy calentando}
{6921}{}{Aquí viene el trueno}
{6922}{}{No eres lo bastante diestro}
{6923}{}{¿Eso es todo lo que sabes hacer?}
{6924}{}{Pequeño tonto estúpido}
{6925}{}{Eso ha sido patético}
{6926}{}{Me insultas con tu incompetencia}
{6927}{}{No eres un luchador}
{6928}{}{¡Ah!}
{6929}{}{¡Ow!}
{6930}{}{Oooooh}
{6931}{}{Eso ha sonado a fractura}
{6932}{}{¡Ow!}
{6933}{}{Mi brazo se torció por completo}
{6934}{}{Eso ha sonado a fractura}
{6935}{}{¡Ow!}
{6936}{}{Mi brazo se torció por completo}
{6937}{}{¡Oh! ¡Estoy preparado para los tipos como tú!}
{6938}{}{¡Uf!}
{6939}{}{¡Ay!}
{6940}{}{¡Uff! He estado peor}
{6941}{}{¡Oh! ¡Haz lo que quieras, yo estoy preparado!}
{6942}{}{¡La Hermandad me vengará si muero!}
{6943}{}{¡Ay!}
{6944}{}{¡Agh!}
{6945}{}{}
{6946}{}{¡Uf!}
{6947}{}{¡Oh, mi pierna!}
{6948}{}{}
{6949}{}{Oh...}
{6950}{}{¡Oh, mi pierna!}
{6951}{}{}
{6952}{}{Oh...}
{6953}{}{¡Aggghh!}
{6954}{}{¡Estoy ciego! ¡Necesito ayuda!}
{6955}{}{¡Mis ojos!}
{6956}{}{¡Ohhhhh, la ingle!}
{6957}{}{Ohhhhh, me has dejado sin aire}
{6958}{}{Ohhhhh, me duele}
{6959}{}{No... puedo... respirar...}
{6960}{}{Respetemos las reglas}
{6961}{}{Me duele...}
{7000}{}{¡Me retiro! ¡Me largo! ¡Me piro!}
{7001}{}{Estoy fuera de esta pelea}
{7002}{}{Retrocede}
{7003}{}{Viviré para luchar otro día}
{7004}{}{No puedo hacer nada bueno aquí}
{7005}{}{}
{7006}{}{¡Allá voy!}
{7007}{}{¡Este es mío!}
{7008}{}{Esto debería ser rápido}
{7009}{}{Una vez más en la brecha}
{7010}{}{Neutralicemos a este alborotador}
{7011}{}{¡Allá voy!}
{7012}{}{Disfruta de estos últimos segundos}
{7013}{}{¡Vamos a ponerte a raya!}
{7014}{}{Así es como se hace}
{7015}{}{¡Se acabó!}
{7016}{}{¡Fuego inminente!}
{7017}{}{Aprecio el ejercicio, pero es hora de acabar con esto}
{7018}{}{}
{7019}{}{Veamos de qué estás hecho}
{7020}{}{Ya está bien de jugar}
{7021}{}{Casi siento pena por ti}
{7022}{}{¡Eres un tonto debilucho!}
{7023}{}{¿Eso es todo lo que sabes?}
{7024}{}{¿Te estás tomando esta pelea en serio?}
{7025}{}{Mantén los ojos en el objetivo, ¡idiota!}
{7026}{}{Ese será tu último error}
{7027}{}{Deberías haberte quedado en casa}
{7028}{}{Mmm, ¡me duele!}
{7029}{}{¡Uh!}
{7030}{}{Oooooh}
{7031}{}{Eso ha sonado a fractura}
{7032}{}{Mmm, me ha dado en el antebrazo}
{7033}{}{Mi brazo se torció por completo}
{7034}{}{Eso ha sonado a fractura}
{7035}{}{Mmm, me ha dado en el antebrazo}
{7036}{}{Mi brazo se torció por completo}
{7037}{}{¡Oh! ¡Perro!}
{7038}{}{¡Uf!}
{7039}{}{¡Ay!}
{7040}{}{¡Uf! Mi madre me ha hecho más daño}
{7041}{}{¡Oh! ¡Sinvergüenza!}
{7042}{}{¡Uff! ¡La Hermandad me vengará si muero!}
{7043}{}{¡Dominaré mi dolor como te dominaré a ti!}
{7044}{}{Sí... dolor, mi viejo amigo}
{7045}{}{}
{7046}{}{¡Solo es un poco de carne herida!}
{7047}{}{Mmm, una pierna herida}
{7048}{}{¡Mi pierna está temblando!}
{7049}{}{Oh...}
{7050}{}{Mmm, una pierna herida}
{7051}{}{Mi pierna está empezando a torcerse}
{7052}{}{Oh...}
{7053}{}{¡Aggghh!}
{7054}{}{¡Se me ha nublado la vista!}
{7055}{}{¡Mis ojos!}
{7056}{}{¡Ohhhhh, la ingle!}
{7057}{}{Está empezando a dejar de gustarme este mocoso}
{7058}{}{Me he sentido mejor}
{7059}{}{Así que a este tipo le gusta ir a las partes bajas}
{7060}{}{Es hora de apartar a este mocoso}
{7061}{}{¡Otro artista de los golpes bajos no!}
{7100}{}{¡Cubridme!}
{7101}{}{No confundas esto con cobardía, cacho perro}
{7102}{}{¡No me toca a mí!}
{7103}{}{Te devolveré ésta, chucho callejero}
{7104}{}{No creas que esto ya se ha acabado}
{7105}{}{}
{7106}{}{Allá voy}
{7107}{}{¿Tengo que hacerlo todo yo?}
{7108}{}{Esto debería ser rápido}
{7109}{}{Puede que esto sea un desafío}
{7110}{}{Alguien acaba de cometer un gran error}
{7111}{}{¿Alguien quiere molestarnos? ¿Quién es el imbécil?}
{7112}{}{Demasiado fácil}
{7113}{}{Preparados, apunten, fuego...}
{7114}{}{Así es como se hace}
{7115}{}{¡Se acabó!}
{7116}{}{¡Allá voy!}
{7117}{}{Aprecio el ejercicio, pero es hora de acabar con esto}
{7118}{}{Hora de terminar con tus errores}
{7119}{}{Es una lección muy dura para alguien tan joven}
{7120}{}{Ya está bien de jugar}
{7121}{}{Un regalo de los Ancianos, chico}
{7122}{}{Lo vi venir}
{7123}{}{He tardado veinte años en aprender a esquivar así}
{7124}{}{Tienes talento, pero tu entrenamiento es patético}
{7125}{}{La experiencia no tiene sustituto}
{7126}{}{Ahora... me toca a mí}
{7127}{}{Deberías haberte quedado en casa}
{7128}{}{Mmm, ¡me duele!}
{7129}{}{¡Uh!}
{7130}{}{Ohh, no ha sido un mal golpe}
{7131}{}{}
{7132}{}{Mmm, me ha dado en el antebrazo}
{7133}{}{Se me ha paralizado el brazo. No es la primera vez}
{7134}{}{}
{7135}{}{Mmm, me ha dado en el antebrazo}
{7136}{}{Se me ha paralizado el brazo. No es la primera vez}
{7137}{}{¡No sentiré dolor!}
{7138}{}{¡Vivo!}
{7139}{}{¡Vivo! ¡Herido, pero vivo!}
{7140}{}{¡Oh! Has cometido un grave error táctico}
{7141}{}{¡Uff! ¡La Hermandad prevalecerá!}
{7142}{}{¡Uff! ¡La Hermandad me vengará si muero!}
{7143}{}{¡Uf!}
{7144}{}{[Jadea fuertemente]}
{7145}{}{¡Me duele!}
{7146}{}{Sentirás la furia de la Hermandad por esto!}
{7147}{}{Mmm, una pierna herida}
{7148}{}{¡Mi pierna está temblando!}
{7149}{}{No ha sido agradable}
{7150}{}{Mmm, una pierna herida}
{7151}{}{Mi pierna está empezando a torcerse}
{7152}{}{No ha sido agradable}
{7153}{}{Debo mantener la calma. Sé dónde apuntar}
{7154}{}{Me ha dado en los ojos. Eso no es bueno}
{7155}{}{¡Mis ojos!}
{7156}{}{¡Ohhhhh, la ingle!}
{7157}{}{}
{7158}{}{Este chico está intentando sacarme de quicio}
{7159}{}{}
{7160}{}{Hora de acabar con este tonto}
{7161}{}{¡Otro artista de los golpes bajos no!}
{7200}{}{¡Me largo!}
{7201}{}{Estoy fuera de esta lucha}
{7202}{}{¡Retirada!}
{7203}{}{Lucharé otro día}
{7204}{}{No puedo hacer nada bueno aquí}
{7205}{}{}
{7206}{}{¡Allá voy!}
{7207}{}{¡Este es mío!}
{7208}{}{Voy a ocuparme de este canalla}
{7209}{}{Deja que te presente al dolor}
{7210}{}{Pequeño bastardo insolente}
{7211}{}{¡Allá voy!}
{7212}{}{Disfruta de estos últimos segundos}
{7213}{}{Estoy cansado de ti}
{7214}{}{Así es como se hace}
{7215}{}{¡Se acabó!}
{7216}{}{Así es como lo hace un profesional}
{7217}{}{De verdad estás empezando a fastidiarme}
{7218}{}{}
{7219}{}{Te estás buscando que te conviertan en escoria, chico}
{7220}{}{Ya está bien de jugar}
{7221}{}{Casi siento pena por ti}
{7222}{}{No tienes habilidades}
{7223}{}{Deja de hacerme perder el tiempo, chico}
{7224}{}{¿Te estás tomando esta pelea en serio?}
{7225}{}{No hace mucho que haces esto, ¿verdad?}
{7226}{}{Tonto enclenque}
{7227}{}{Deberías haberte quedado en casa}
{7228}{}{Mmm, ¡me duele!}
{7229}{}{¡Uh!}
{7230}{}{Oooooh}
{7231}{}{}
{7232}{}{Mmm, me ha dado en el antebrazo}
{7233}{}{Mi brazo se torció por completo}
{7234}{}{}
{7235}{}{Mmm, me ha dado en el antebrazo}
{7236}{}{Mi brazo se torció por completo}
{7237}{}{¡No sentiré dolor!}
{7238}{}{¡Uf! ¡Perro insolente!}
{7239}{}{¡Uf! ¡Chucho insolente! ¡Siente mi furia!}
{7240}{}{¡Oh! Has cometido un grave error táctico}
{7241}{}{¡Ay!}
{7242}{}{¡Ufff! La Hermandad vengará mi muerte}
{7243}{}{¡Uf!}
{7244}{}{El dolor me hace saber que sigo vivo}
{7245}{}{¡Me duele!}
{7246}{}{}
{7247}{}{Una pierna herida no impedirá que te mate}
{7248}{}{¡Mi pierna está temblando!}
{7249}{}{Oh...}
{7250}{}{Una pierna herida no impedirá que te mate}
{7251}{}{Mi pierna está empezando a torcerse}
{7252}{}{Oh...}
{7253}{}{¡Aggghh!}
{7254}{}{¡Hijo de...!}
{7255}{}{¡Mis ojos!}
{7256}{}{Chico, los que juegan conmigo acaban muertos!}
{7257}{}{}
{7258}{}{Me he sentido mejor}
{7259}{}{}
{7260}{}{Hora de acabar con este tonto}
{7261}{}{No espero demasiado de alguien como tú}
{7300}{}{Esto ha sido divertido, pero debo irme}
{7301}{}{Esta batalla no tiene sentido. ¡Adiós, tonto!}
{7302}{}{No voy a gastar más tiempo contigo}
{7303}{}{¡Tengo mejores cosas que hacer que mancharme las manos contigo!}
{7304}{}{Dejaré que los Nocturnos se ocupen de ti}
{7305}{}{Adiós, idiota. No vivirás lo suficiente para que volvamos a vernos}
{7306}{}{¡Ha pasado mucho tiempo desde la última vez que tuve sangre caliente entre mis dedos!}
{7307}{}{¡Vas a morir por lo que has hecho!}
{7308}{}{¡Cuando termine, serás la comida de las ratas!}
{7309}{}{¡Otra interrupción no!}
{7310}{}{¡No toleraré tu insolencia!}
{7311}{}{Has traspasado el reino del perdón}
{7312}{}{¡Toma esto!}
{7313}{}{¡Te unjo con la Llama Sagrada!}
{7314}{}{Así trato a los animales}
{7315}{}{¡Pequeño salvaje innombrable!}
{7316}{}{¡Te oiré gritar!}
{7317}{}{¡Esto es solo el principio de tu agonía!}
{7318}{}{Soy Morfeo y esgrimo un bastón negro!}
{7319}{}{¡Vas a arder!}
{7320}{}{Soy Morfeo, Maestro de la Muerte!}
{7321}{}{Te arrojaré y pondré fin a tu vida}
{7322}{}{No me impresionas en absoluto}
{7323}{}{¡No pasé diez años en los Destripadores para nada!}
{7324}{}{Patético}
{7325}{}{He tenido mejores peleas con las putas}
{7326}{}{¿Siempre has sido un incompetente o es un logro reciente?}
{7327}{}{Blasfemo, fracasado, tonto. Pronto añadiremos tu cadáver a la lista de victorias}
{7328}{}{¡Agggh!}
{7329}{}{¡Mis ojos!}
{7330}{}{¡Buen tiro!}
{7331}{}{¡Ow!}
{7332}{}{¡Ow! ¡Mi brazo!}
{7333}{}{¡Oh! ¡Maldigo tu suerte!}
{7334}{}{¡Ow!}
{7335}{}{¡Ow! ¡Mi brazo!}
{7336}{}{¡Oh! ¡Maldigo tu suerte!}
{7337}{}{¡Maldita sea tu suerte!}
{7338}{}{¡Oh! ¡No me rendiré!}
{7339}{}{¡Eres como un grano en el culo!}
{7340}{}{Te estás condenando a ti mismo ante los ojos del Maestro}
{7341}{}{¡Ow!}
{7342}{}{¡Ay!}
{7343}{}{¡Uf!}
{7344}{}{[Jadea fuertemente]}
{7345}{}{¡Oh, eso duele!}
{7346}{}{¡Mis secuaces te harán mucho daño por esto!}
{7347}{}{¡Ow!}
{7348}{}{¡Oh! ¡Mi rodilla!}
{7349}{}{¡Oh! ¡Mi pierna!}
{7350}{}{¡Ow!}
{7351}{}{¡Oh! ¡Mi rodilla!}
{7352}{}{¡Oh! ¡Mi pierna!}
{7353}{}{¡Mis ojos! ¡Cerdo asqueroso!}
{7354}{}{¡He de verte despedazado miembro a miembro!}
{7355}{}{¡Agghh! Pequeño sucio hijo de...}
{7356}{}{¡Ohhhhh, la ingle!}
{7357}{}{¡Ayyy!}
{7358}{}{¡Te veré sufrir!}
{7359}{}{¡Uf!}
{7360}{}{¡Tu muerte será ahora especialmente dolorosa!}
{7361}{}{¡Cómo osas atacar las ijadas de Morfeo!}
{7400}{}{Chico, ya has sido castigado. ¡Fuera de aquí!}
{7401}{}{No deberías resistirte a mí, niño. Trabajaremos en eso}
{7402}{}{No voy a gastar más tiempo contigo}
{7403}{}{¡Tengo mejores cosas que hacer que mancharme las manos contigo!}
{7404}{}{Dejaré que los Nocturnos se ocupen de ti}
{7405}{}{Volveré a castigarte luego}
{7406}{}{Te has merecido el castigo}
{7407}{}{Debes recibir medidas disciplinarias}
{7408}{}{Estate quieto. Esto te va a doler}
{7409}{}{Debes aprender modales, niño}
{7410}{}{La juventud de hoy. Ni disciplina ni educación. Yo te enseñaré}
{7411}{}{Te has ganado el dolor que te espera}
{7412}{}{¡Siente mi castigo y te purificarás!}
{7413}{}{¡Te unjo con la Llama Sagrada!}
{7414}{}{¡Eres una criatura débil, admítelo!}
{7415}{}{¡Mereces un castigo! ¡Admítelo!}
{7416}{}{¡Grita, niño! ¡En el dolor está la redención!}
{7417}{}{No me alegraré de tu dolor, chico}
{7418}{}{¡Confiesa tu pecado! ¡Confiesa tu pecado!}
{7419}{}{Eres vil y pagano. ¡Admítelo!}
{7420}{}{Tu resistencia se añade a tu pecado. ¡Sométete!}
{7421}{}{¡Sométete a la autoridad divina y serás purgado!}
{7422}{}{Tus acciones solo reflejan una mente enferma y retorcida}
{7423}{}{Tu resistencia me pone enfermo, pero sobreviviré}
{7424}{}{Me temo que estás más allá de mi capacidad de redimir}
{7425}{}{¿Tu perfidia no tiene fin, niño?}
{7426}{}{Aunque me ataques, todavía te quiero}
{7427}{}{Blasfemo, fracasado, tonto. ¡Muestra arrepentimiento!}
{7428}{}{Sobrellevo tus golpes con paciencia, chico}
{7429}{}{No me harás daño porque mi causa es sagrada}
{7430}{}{Lo soportaré}
{7431}{}{El Maestro es mi escudo. No siento dolor}
{7432}{}{Los santos me protegen, chico}
{7433}{}{La Llama Sagrada me auxilia. Tus golpes no son nada para mí}
{7434}{}{El Maestro es mi escudo. No siento dolor}
{7435}{}{Los santos me protegen, chico}
{7436}{}{La Llama Sagrada me auxilia. Tus golpes no son nada para mí}
{7437}{}{Después del dolor viene el perdón, niño}
{7438}{}{Yo entiendo el dolor. ¿Y tú?}
{7439}{}{Puedo sentir tus golpes, pero el dolor no importa}
{7440}{}{Hazlo otra vez, me gusta sentirte}
{7441}{}{El Maestro me da el poder de sobrevivir}
{7442}{}{[Jadea fuertemente] No eres más que un niño}
{7443}{}{Mi cuerpo es como un armazón}
{7444}{}{No puedes detener a la Unidad}
{7445}{}{Siento tu dolor, niño}
{7446}{}{¡No vuelvas a intentar eso!}
{7447}{}{Después del dolor viene el perdón, niño}
{7448}{}{El Maestro es mis brazos y mis piernas, niño}
{7449}{}{Cada debilidad del cuerpo hace mi alma más fuerte, niño}
{7450}{}{Después del dolor viene el perdón, niño}
{7451}{}{El Maestro es mis brazos y mis piernas, niño}
{7452}{}{Cada debilidad del cuerpo hace mi alma más fuerte, niño}
{7453}{}{Después del dolor viene el perdón, niño}
{7454}{}{Ningún sacrificio es lo bastante grande para el Maestro, niño}
{7455}{}{Cada debilidad del cuerpo hace mi alma más fuerte, niño}
{7456}{}{¡Aunque mi carne es débil, mi espíritu es fuerte!}
{7457}{}{El dolor es un artefacto de la mentes débiles. Sobreviviré}
{7458}{}{Mi sufrimiento me da fuerzas}
{7459}{}{¡Uf!}
{7460}{}{Hasta en la batalla se nota tu naturaleza decadente}
{7461}{}{¡Tus pecados se multiplicarán por dos, niño!}
{7500}{}{¡Tus males recibirán el castigo que merecen!}
{7501}{}{¡Ahora tienes la marca de los Niños!}
{7502}{}{¡Volveré a verte!}
{7503}{}{¡Veré tu cadáver!}
{7504}{}{Nos veremos en otro momento}
{7505}{}{¡Esto no ha terminado!}
{7506}{}{¡Los blasfemos han de ser castigados!}
{7507}{}{¡Muere en nombre de la Llama Sagrada!}
{7508}{}{¡Cómo osas interrumpir nuestro gran trabajo!}
{7509}{}{Tienes que aprender modales, chico}
{7510}{}{¡Niños, destruid al intruso!}
{7511}{}{Te mereces mucho dolor, niño}
{7512}{}{¡Este es tu castigo!}
{7513}{}{¡Blasfemo!}
{7514}{}{¡Sufre a los Niños!}
{7515}{}{¡Muere, en nombre de la Llama Sagrada!}
{7516}{}{Y ahora llegará tu noche}
{7517}{}{¡Conoce el lugar de tu tumba, niño!}
{7518}{}{¡Qué caiga el soplo de la muerte!}
{7519}{}{¡Profanas la Llama Sagrada!}
{7520}{}{¡Sufre, idiota!}
{7521}{}{¡Solo al final lo entiendes!}
{7522}{}{Tus acciones solo reflejan una mente enferma y retorcida}
{7523}{}{No puedes hacerme daño, niño}
{7524}{}{Me temo que estás más allá de mi capacidad de perdonar}
{7525}{}{¿Tu perfidia no tiene fin, niño?}
{7526}{}{¡Me protege la Llama Sagrada!}
{7527}{}{Mi fuerza está más allá de tu entendimiento}
{7528}{}{¡Malvada pequeña bestia!}
{7529}{}{¡Morirás por esto!}
{7530}{}{¡Ow!}
{7531}{}{El Maestro es mi escudo. No siento dolor}
{7532}{}{¡La Muerte te encontrará pronto!}
{7533}{}{¡Ow!}
{7534}{}{El Maestro es mi escudo. No siento dolor}
{7535}{}{¡La Muerte te encontrará pronto!}
{7536}{}{¡Ow!}
{7537}{}{¡Pecador!}
{7538}{}{¡Ow!}
{7539}{}{¡Estás derramando la sangre de una mujer sagrada!}
{7540}{}{¡Uff! No tendrás éxito}
{7541}{}{¡Oh! Te castigaré por tus pecados}
{7542}{}{¡Oh! Te deshonras a ti mismo}
{7543}{}{¡Oh!}
{7544}{}{Mi Maestro me protege de tus débiles intentos}
{7545}{}{¡Ow!}
{7546}{}{¡Uf!}
{7547}{}{El Maestro es mi escudo. No siento dolor}
{7548}{}{Mi sangre es un sacrificio a la misericordia}
{7549}{}{¡Ow!}
{7550}{}{Después del dolor viene el perdón, niño}
{7551}{}{Mi sangre es un sacrificio a la misericordia}
{7552}{}{¡Ow!}
{7553}{}{¡Mis ojos!}
{7554}{}{¡Aggh! ¡Maldito!}
{7555}{}{Mis ojos están ardiendo!}
{7556}{}{¡Eres abominable!}
{7557}{}{¡Te placen las victorias sucias!}
{7558}{}{Mi sufrimiento me da fuerzas}
{7559}{}{¡Uf!}
{7560}{}{Hasta en la batalla se nota tu naturaleza decadente}
{7561}{}{¡Tus pecados se multiplicarán por dos, niño!}
{7600}{}{Esto no merece mi tiempo}
{7601}{}{¡No tengo tiempo para morir!}
{7602}{}{¡Vas a pagar por lo que has hecho!}
{7603}{}{}
{7604}{}{¡Todavía no he dicho la última palabra!}
{7605}{}{¡Vivo para luchar otro día!}
{7606}{}{¡Eres historia!}
{7607}{}{¡Te has equivocado de gente!}
{7608}{}{Bailaré sobre tu tumba}
{7609}{}{¡Acabas de comprarte una casa a poca profundidad!}
{7610}{}{¡Cuando termine contigo, las ratas harán el resto!}
{7611}{}{Tu vida no significa nada para mí}
{7612}{}{¡Hora de dar de comer a los gusanos!}
{7613}{}{Estás a punto de ponerte muy feo}
{7614}{}{}
{7615}{}{¡Ese es tu número!}
{7616}{}{Dentro de dos segundos conocerás al que te ha creado}
{7617}{}{¡Voy a dejarte, como si fueras un mal vicio!}
{7618}{}{}
{7619}{}{Voy a conseguir un bono por esto}
{7620}{}{¡Muere!}
{7621}{}{Te daré patadas en el culo hasta la tumba}
{7622}{}{¿Eso ha sido una advertencia?}
{7623}{}{Déjame adivinar, estabas intentando fallar}
{7624}{}{}
{7625}{}{¡Conque así es como fallas! Gracias por enseñármelo}
{7626}{}{¡Me ha hecho más daño una buena maldición!}
{7627}{}{Desgraciado}
{7628}{}{}
{7629}{}{Ah, me duele la cabeza}
{7630}{}{¡Me has roto la nariz!}
{7631}{}{¡Oh, mi brazo!}
{7632}{}{¡Me has roto el brazo!}
{7633}{}{No necesitaba eso}
{7634}{}{¡Oh, mi brazo!}
{7635}{}{¡Me has roto el brazo!}
{7636}{}{¡Mi buen brazo!}
{7637}{}{¡Uf!}
{7638}{}{¡Me duele!}
{7639}{}{¡Venga, inténtalo otra vez!}
{7640}{}{¡Uf!}
{7641}{}{[Jadea fuertemente]}
{7642}{}{¡Oh, maldita sea!}
{7643}{}{¡Ah, uff!}
{7644}{}{¡Ay!}
{7645}{}{¡Auch! ¡Eso duele!}
{7646}{}{¡Ey! ¡No estaba preparado para eso!}
{7647}{}{¡Oh, mi pierna!}
{7648}{}{¡Lo pagarás muy caro por esto!}
{7649}{}{¡Oh, mi rodilla!}
{7650}{}{¡Oh, mi pierna!}
{7651}{}{¡Lo pagarás muy caro por esto!}
{7652}{}{Oh, mi rodilla}
{7653}{}{¡Agh! ¡La retina!}
{7654}{}{Mis ojos... mis ojos no...}
{7655}{}{¡Ese ha sido un golpe bajo!}
{7656}{}{¡Ohhhhh, la ingle!}
{7657}{}{¡Ohh! Tengo que aprender ese movimiento...}
{7658}{}{Por la mañana recordaré este golpe}
{7659}{}{Odio los golpes en la entrepierna}
{7660}{}{¡Urp!}
{7661}{}{¡Oh! ¡Te mataré por esto!}
{7700}{}{}
{7701}{}{Puede que no fuera una buena idea}
{7702}{}{Creo que me he quedado sin munición}
{7703}{}{}
{7704}{}{¡No voy a morir por esto!}
{7705}{}{Es demasiado para mí}
{7706}{}{¡Eh, tú!}
{7707}{}{Alguien tiene graves problemas}
{7708}{}{¡Por aquí no nos gustan los tipos como tú!}
{7709}{}{¿Quién te crees que eres?}
{7710}{}{Hora de vaciar el cargador...}
{7711}{}{¡Policía del Eje!}
{7712}{}{¡Toma esto!}
{7713}{}{¡Ya te tengo!}
{7714}{}{Baja y quédate ahí}
{7715}{}{¿Qué te parece esto?}
{7716}{}{}
{7717}{}{Lo que sea}
{7718}{}{¿Crees que tienes problemas? Piénsalo otra vez}
{7719}{}{Punk}
{7720}{}{¡Voy a por ti!}
{7721}{}{Quizá así aprendas un poco de respeto}
{7722}{}{No esperabas darme, ¿verdad?}
{7723}{}{Soy un profesional entrenado}
{7724}{}{No eres lo bastante bueno}
{7725}{}{Ese fue tu último error}
{7726}{}{Aficionado}
{7727}{}{¿Aprendiste a pelear en un bar?}
{7728}{}{¡Oh! Hijo de...}
{7729}{}{Te mataré por esto}
{7730}{}{¡Te arrancaré la cabeza!}
{7731}{}{¡Oh, mi brazo!}
{7732}{}{Maldita sea. ¡Tengo el brazo destrozado!}
{7733}{}{¡Mi brazo!}
{7734}{}{¡Oh, mi brazo!}
{7735}{}{Maldita sea. ¡Tengo el brazo destrozado!}
{7736}{}{¡Mi brazo!}
{7737}{}{¡Vas a pagar por esto!}
{7738}{}{¡Va contra la ley golpear a un oficial!}
{7739}{}{¡Ay!}
{7740}{}{¡Uf!}
{7741}{}{¡Eso es todo! ¡Ya he tenido suficiente!}
{7742}{}{Voy a deshacerme de ti por esto}
{7743}{}{Golpéame de nuevo ahí y no tendremos que ver a un juez}
{7744}{}{Repítelo bajo tu propia responsabilidad}
{7745}{}{¡Uf! ¡Déjalo!}
{7746}{}{}
{7747}{}{¡Oh, mi pierna!}
{7748}{}{¡Lo pagarás muy caro por esto!}
{7749}{}{¡Mi rodilla!}
{7750}{}{¡Oh, mi pierna!}
{7751}{}{¡Lo pagarás muy caro por esto!}
{7752}{}{¡Mi rodilla!}
{7753}{}{¡No veo!}
{7754}{}{¡Mi ojo! ¡Me las vas a pagar!}
{7755}{}{¡¡Estoy ciego!! Necesito ayuda}
{7756}{}{¡Ohhhhh, la ingle!}
{7757}{}{Por la mañana recordaré este golpe}
{7758}{}{¡Novato!}
{7759}{}{¡Urp!}
{7760}{}{Te lo estás tomando como algo personal!}
{7761}{}{Maldita sea, me duele}
{7800}{}{Esto no ha terminado. ¡Todavía queda mucho!}
{7801}{}{Volveré...}
{7802}{}{Estás muerto. ¿Me oyes? ¡Muerto!}
{7803}{}{¡Pronto te veré muerto!}
{7804}{}{¡Todavía no has oído la última palabra!}
{7805}{}{¡Tendrás lo que te mereces, te lo prometo!}
{7806}{}{¡Has terminado! ¡Eres historia!}
{7807}{}{Nunca debiste cruzarte conmigo}
{7808}{}{Necesitas una nueva actitud}
{7809}{}{Eres un error que quiero corregir}
{7810}{}{Vas en el tren expreso destino al infierno}
{7811}{}{Se acabó, alguien va a morir}
{7812}{}{¡Toma esto!}
{7813}{}{Esto es lo que hago con los mocosos y los perdedores}
{7814}{}{Voy a divertirme}
{7815}{}{¡Esto te va a doler!}
{7816}{}{Te has metido con el hombre equivocado}
{7817}{}{Nadie me va a apartar del Eje}
{7818}{}{Espero que mueras lentamente}
{7819}{}{¡Nadie se mete con Decker!}
{7820}{}{¡Muere!}
{7821}{}{¡Prueba esto!}
{7822}{}{Realmente patético}
{7823}{}{¡No tienes la cabeza en su sitio!}
{7824}{}{Todavía sé arreglármelas en una pelea}
{7825}{}{No puedes terminar el trabajo}
{7826}{}{¡Ese ha sido tu último tiro!}
{7827}{}{Desgraciado}
{7828}{}{¡Mi pobre cráneo dolorido!}
{7829}{}{¡Cómo me haces esto!}
{7830}{}{¡Me has roto la nariz!}
{7831}{}{Eres un asqueroso escorpión rad de...}
{7832}{}{¡Me has roto el brazo!}
{7833}{}{¡Mi brazo, mi brazo!}
{7834}{}{Eres un asqueroso escorpión rad de...}
{7835}{}{¡Me has roto el brazo!}
{7836}{}{¡Mi brazo, mi brazo!}
{7837}{}{Eres un despreciable HDP, ¿lo sabías?}
{7838}{}{¡Uff! ¡Me van a doler las costillas durante días!}
{7839}{}{¡Oh! ¿Queteee crees que soy, un saco de boxeo?}
{7840}{}{¡Uf!}
{7841}{}{¡Ow!}
{7842}{}{¡No te metas conmigo de esa manera, no lo voy a permitir!}
{7843}{}{¡Uf! ¡Tuviste tu oportunidad y la echaste a perder!}
{7844}{}{¡Oh! Eso ha sido muy desagradable}
{7845}{}{¡Uff! Voy a recordar esto...}
{7846}{}{[Jadea fuertemente] Nece... sito... aire...}
{7847}{}{¡Oh, mi pierna!}
{7848}{}{Ooo... ¡novato!}
{7849}{}{¡Oh, mi rodilla!}
{7850}{}{¡Oh, mi pierna!}
{7851}{}{Ooo... ¡novato!}
{7852}{}{Oh, mi rodilla}
{7853}{}{Sangre. Toda esta sangre...}
{7854}{}{Mis ojos... mis ojos no...}
{7855}{}{¡Ese ha sido un golpe bajo!}
{7856}{}{¡Ohhhhh, la ingle!}
{7857}{}{¡Ooo! No está mal}
{7858}{}{¡Ooo! Estás cavando tu tumba, amigo}
{7859}{}{¡Ooo! ¡Voy a enterrarte vivo en el Ardor!}
{7860}{}{¡Urp!}
{7861}{}{¡Oh! ¡Te mataré por esto!}
{7900}{}{Esto no ha terminado. ¡Todavía queda mucho!}
{7901}{}{Volveré...}
{7902}{}{Estás muerto. ¿Me oyes? ¡Muerto!}
{7903}{}{¡Pronto te veré muerto!}
{7904}{}{¡Todavía no has oído la última palabra!}
{7905}{}{¡Tendrás lo que te mereces, te lo prometo!}
{7906}{}{Soy muy bueno solucionando problemas}
{7907}{}{Nunca debiste meterte con el Sr. Decker}
{7908}{}{Voy a cambiar tu actitud}
{7909}{}{Al Sr. Decker no le gustas}
{7910}{}{Vas en el tren expreso rumbo al infierno}
{7911}{}{Se acabó, alguien va a morir}
{7912}{}{¡Toma esto!}
{7913}{}{Decker cree que tienes que recibir algo de respeto}
{7914}{}{Este es un mensaje de Decker}
{7915}{}{¡Esto te va a doler!}
{7916}{}{Te has metido con el hombre equivocado}
{7917}{}{Decker te manda saludos}
{7918}{}{Es demasiado tarde para disculpas}
{7919}{}{¡Nadie se mete con Decker!}
{7920}{}{¡Muere!}
{7921}{}{¡Prueba esto!}
{7922}{}{Realmente patético}
{7923}{}{¡No tienes la cabeza en su sitio!}
{7924}{}{No creo que puedas darle al objetivo}
{7925}{}{No puedes terminar el trabajo}
{7926}{}{Ese fue tu último error}
{7927}{}{Tienes un mal día. Quédate. Irá a peor}
{7928}{}{¡Mi pobre cráneo dolorido!}
{7929}{}{Oooo...}
{7930}{}{¡Me has roto la nariz!}
{7931}{}{Oooo...}
{7932}{}{¡Me has roto el brazo!}
{7933}{}{¡Mi brazo!}
{7934}{}{Oooo...}
{7935}{}{¡Me has roto el brazo!}
{7936}{}{¡Mi brazo!}
{7937}{}{¡Uf! Nadie va a derrotarme...}
{7938}{}{¡Uff! ¡Mis costillas!}
{7939}{}{¡Oh! Te voy a joder vivo}
{7940}{}{¡Ja! ¡Tengo magulladuras más grandes de otros trabajos!}
{7941}{}{¡Uff! Todos los mocosos sois iguales...}
{7942}{}{¡Gulp! Tengo... que respirar...}
{7943}{}{¡Ay!}
{7944}{}{¡Oh! Vete al infierno, mocoso!}
{7945}{}{Ah, maldita sea...}
{7946}{}{¡Agh! Creo que me has roto una costilla!}
{7947}{}{¡Oh, mi pierna!}
{7948}{}{Oooo...}
{7949}{}{¡Oh, mi rodilla!}
{7950}{}{¡Oh, mi pierna!}
{7951}{}{Oooo...}
{7952}{}{Oh, mi rodilla}
{7953}{}{Sangre. Toda esta sangre...}
{7954}{}{Mis ojos...}
{7955}{}{¡Ese ha sido un golpe bajo!}
{7956}{}{¡Ohhhhh, la ingle!}
{7957}{}{¡Ooo! Voy a devolverte el favor}
{7958}{}{¡Ooo! Estás cavando tu propia tumba}
{7959}{}{¡Ooo! Supongo que te hace gracia}
{7960}{}{¡Urp!}
{7961}{}{¡Oh! Creo que no me gustas}
{8000}{}{¡Mi papá va a matarte! ¡Espera a que llegue!}
{8001}{}{¡¡¡Mami!!!}
{8002}{}{¡Que alguien me ayude!}
{8003}{}{¡Ayuda!}
{8004}{}{¡Aaaaahhhh!}
{8005}{}{¡Buaahhhh!!}
{8006}{}{¡Eh, tú!}
{8007}{}{¡Te odio! ¡Te odio!}
{8008}{}{}
{8009}{}{¡Eres un mutante deforme!}
{8010}{}{¡Alguien tiene que ocuparse de ti!}
{8011}{}{¡Te voy a matar!}
{8012}{}{¡Cabeza de escorpión rad!}
{8013}{}{¡Te voy a matar!}
{8014}{}{¡Perdedor mutante!}
{8015}{}{¡Arde, pequeño perdedor! ¡Arde, pequeño perdedor!}
{8016}{}{¡Muérete, feo!}
{8017}{}{Your mama was a mole rat!}
{8018}{}{¡Bebé del Ardor, gusano acorralado!}
{8019}{}{¡Voy a ponerte muy feo!}
{8020}{}{¡Te odio!}
{8021}{}{¡Amante de escorpión rad! ¡Te acuestas con escorpiones rad!}
{8022}{}{Your mama was a Glow Baby!}
{8023}{}{¡No puedes tocarme, cerebro de escorpión rad!}
{8024}{}{¡Ni siquiera puedes vencer a un niño!}
{8025}{}{¡Perdedor!}
{8026}{}{¡No me has dado, cerebro de mosquito!}
{8027}{}{¿Qué te pasa, Bebé del Ardor?}
{8028}{}{¡Mi cara!}
{8029}{}{Ohhh, me duele...}
{8030}{}{¡Oh! ¡Mi oído!}
{8031}{}{¡Oh, mi brazo!}
{8032}{}{Ohhh, me duele...}
{8033}{}{¡Me has roto el brazo! ¡Papi!}
{8034}{}{¡Oh, mi brazo!}
{8035}{}{Ohhh, me duele}
{8036}{}{¡Me has roto el brazo! ¡Papi!}
{8037}{}{¡Ow!}
{8038}{}{¡Oh! ¡Mami, ese hombre malo me está haciendo daño!}
{8039}{}{¡Auch! ¡Has sido malo!}
{8040}{}{¡Oh! Si fuera más grande, te ibas a enterar}
{8041}{}{¡Ay, ay, ay! ¡Mamá!}
{8042}{}{¡Oh! ¡Mi papá es más grande que el tuyo!}
{8043}{}{¡Oooo, voy... a... llorar! ¡Buaaaahhhhh!}
{8044}{}{¡Ay!}
{8045}{}{¡Ow!}
{8046}{}{¡Oh! ¡Oh! ¡Eres malo!}
{8047}{}{¡Oh, mi pierna!}
{8048}{}{¡Mi rodilla!}
{8049}{}{¡Me has roto la pierna! ¡Papá!}
{8050}{}{¡Oh, mi pierna!}
{8051}{}{¡Mi rodilla!}
{8052}{}{¡Me has roto la pierna! ¡Papá!}
{8053}{}{¡Aaaaaahhhh!!!}
{8054}{}{¿A dónde ha ido todo el mundo?}
{8055}{}{Todo está oscuro...}
{8056}{}{¡Ohhhhh, la ingle!}
{8057}{}{¡Oh! ¡Apestoso Bebé del Ardor!}
{8058}{}{¡Urp!}
{8059}{}{No... puedo... respirar...}
{8060}{}{Ooooo...}
{8061}{}{Me duele, me duele...}
{8100}{}{Iniciada opción de retirada}
{8101}{}{Plan táctico: retirada}
{8102}{}{Efectividad del combate mínima. Aconsejable retirada}
{8103}{}{Análisis táctico completado. Se recomienda retirada}
{8104}{}{Cargando programa de huida}
{8105}{}{Iniciada secuencia de retirada}
{8106}{}{¡Objetivo localizado!}
{8107}{}{¡Finalizar! ¡Finalizar!}
{8108}{}{El humanoide no debe escapar}
{8109}{}{Exterminar al intruso}
{8110}{}{Iniciada secuencia de combate}
{8111}{}{Cargando programa de combate}
{8112}{}{Iniciada secuencia de combate}
{8113}{}{Atacando al objetivo}
{8114}{}{Iniciando secuencia de ataque}
{8115}{}{¡El intruso ha de ser destruido!}
{8116}{}{Selección de opciones tácticas completada}
{8117}{}{Comenzando ataque}
{8118}{}{El objetivo será destruido}
{8119}{}{Secuencia de exterminio del enemigo iniciada}
{8120}{}{El objetivo ha de ser eliminado}
{8121}{}{Selección de ofensiva completada}
{8122}{}{Análisis. Éxito del programa de defensa}
{8123}{}{Análisis. Ataque insignificante al objetivo.}
{8124}{}{Fracasado ataque al objetivo. Calculando respuesta}
{8125}{}{Unidad no dañada en el ataque}
{8126}{}{Recalculando capacidad de ataque del objetivo}
{8127}{}{Análisis. El objetivo erró en selección táctica. Unidad sin daños}
{8128}{}{¡Precaución! Registrado funcionamiento defectuoso de la CPU}
{8129}{}{¡Precaución! ¡CPU dañada! ¡Procesamiento dañado!}
{8130}{}{¡Precaución! ¡CPU dañada! ¡Cambio del sistema crítico!}
{8131}{}{Registrado daño en el manipulador}
{8132}{}{Unidad alcanzó manipulador izquierdo. Evaluación de daños}
{8133}{}{Registrado golpe en el manipulador. Intentando compensar}
{8134}{}{Registrado daño en el manipulador}
{8135}{}{Unidad alcanzó manipulador derecho. Evaluación de daños}
{8136}{}{Registrado golpe en el manipulador. Intentando compensar}
{8137}{}{Armazón alcanzado. Corrigiendo daños}
{8138}{}{Armazón alcanzado. Iniciadas reparaciones internas}
{8139}{}{Estructura principal bajo ataque}
{8140}{}{Armadura penetrada}
{8141}{}{Estructura principal bajo ataque. Corrigiendo}
{8142}{}{Esta unidad está siendo atacada}
{8143}{}{Intentando maniobra de combate}
{8144}{}{¡Brzzt!}
{8145}{}{Daños menores}
{8146}{}{¡Brzzt!}
{8147}{}{Registrado daño en el motivador}
{8148}{}{Unidad alcanzó motivador derecho. Evaluación de daños}
{8149}{}{Registrado alcance en el motivador. Intentando compensación}
{8150}{}{Registrado daño en el motivador}
{8151}{}{Unidad alcanzó motivador izquierdo. Evaluación de daños}
{8152}{}{Registrado alcance en el motivador. Intentando compensación}
{8153}{}{¡Sensor alcanzado! ¡Sensor alcanzado!}
{8154}{}{¡Sensores dañados! ¡Sensores dañados!}
{8155}{}{Funcionamiento defectuoso del sistema de sensores, intentando bypass}
{8156}{}{Registrado funcionamiento defectuoso del regulador}
{8157}{}{¡Daños en el regulador! ¡Regulación dañada!}
{8158}{}{¡Daños en el regulador! ¡Cambio del sistema crítico!}
{8200}{}{¡No voy a morir por esto!}
{8201}{}{¡El trabajo no merece la pena!}
{8202}{}{¡Que otro vaya a por ellos!}
{8203}{}{Ahí se va mi reputación...}
{8204}{}{¡Ja!}
{8205}{}{¡Voy a luchar!}
{8206}{}{¡Otro majadero no!}
{8207}{}{¡Acabas de cruzar la línea!}
{8208}{}{¡No vas a salir de esta con eso aquí!}
{8209}{}{¡En eso no!}
{8210}{}{¡Nadie hace eso aquí!}
{8211}{}{¡Eh, tú!}
{8212}{}{¡Esto es lo que les hago a los alborotadores!}
{8213}{}{Apaga las luces...}
{8214}{}{Así aprenderás a no causar problemas}
{8215}{}{¡Ese es tu número!}
{8216}{}{Vas en declive}
{8217}{}{Veamos lo duro que eres...}
{8218}{}{Punk}
{8219}{}{¿Lo sientes ahora?}
{8220}{}{¿Esperas salir con eso?}
{8221}{}{Me como a los novatos para desayunar}
{8222}{}{¿Eso son tiros de aviso o estás jugando?}
{8223}{}{No eres solo un mocoso, ¡eres un mocoso incompetente!}
{8224}{}{Tío, ¡tú esnifas!}
{8225}{}{¿Eso es todo lo que sabes hacer?}
{8226}{}{No esperabas darme, ¿verdad?}
{8227}{}{¿Siempre has sido un fracasado o es algo reciente?}
{8228}{}{¡Me has roto la nariz!}
{8229}{}{De todas formas no necesitaba esa oreja}
{8230}{}{¡Maldita sea! ¡Cómo me duele!}
{8231}{}{¡Oh, mi brazo!}
{8232}{}{Puedes lisiarme, pero seguiré dándote patadas en el culo}
{8233}{}{Eso ha sido un error}
{8234}{}{¡Oh, mi brazo!}
{8235}{}{Puedes lisiarme, pero seguiré dándote patadas en el culo}
{8236}{}{Eso ha sido un error}
{8237}{}{¡Ow!}
{8238}{}{Eso ha sido un error}
{8239}{}{¡Uf!}
{8240}{}{¡Oh! Vale, ¡eso es!}
{8241}{}{¡Oh! Estoy loco}
{8242}{}{¡Uf!}
{8243}{}{¡Agh!}
{8244}{}{¡Ay!}
{8245}{}{¡Uff! Voy a coger la escopeta para metértela por el...}
{8246}{}{¡Gulp!}
{8247}{}{¡Otra pierna destrozada no! Oh bueno...}
{8248}{}{Puedes lisiarme, pero seguiré dándote patadas en el culo}
{8249}{}{Eso ha sido un error}
{8250}{}{¡Otra pierna destrozada no! Oh bueno...}
{8251}{}{Puedes lisiarme, pero seguiré dándote patadas en el culo}
{8252}{}{Eso ha sido un error}
{8253}{}{¡No veo! ¡Estás empezando a fastidiarme!}
{8254}{}{¡No tengo que verte para matarte!}
{8255}{}{¡Oh! Buen tiro...}
{8256}{}{¡Ohhhhh, la ingle!}
{8257}{}{Te lo estás tomando como algo personal!}
{8258}{}{La entrepierna. El último refugio del canalla}
{8259}{}{Soy una mujer, imbécil}
{8260}{}{Te estás equivocando de señorita}
{8261}{}{¡Urp!}
{8300}{}{¡¡Iiichhh!!}
{8301}{}{¡Iiichhh!}
{8302}{}{¡Iiichhh!}
{8303}{}{iiichhh}
{8400}{}{¡Hora de salir de aquí!}
{8401}{}{¡Agh!}
{8402}{}{¡Retirada!}
{8403}{}{Esto va a dolerte mucho y a mí nada}
{8404}{}{Voy a darte de patadas en el culo}
{8405}{}{Voy a intentar que esto sea rápido}
{8406}{}{Veamos si esto te divierte}
{8407}{}{Toma esto.}
{8408}{}{¡Te tengo!}
{8409}{}{¡Perdedor!}
{8410}{}{¡Inténtalo con más brío!}
{8411}{}{¡Maldita sea, eso duele!}
{8412}{}{¡Me has roto la nariz!}
{8413}{}{¡Agh! ¡Me has roto el brazo!}
{8414}{}{¡Tengo el brazo destrozado!}
{8415}{}{¡Agh! ¡Me has roto el brazo!}
{8416}{}{¡Tengo el brazo destrozado!}
{8417}{}{¡Uf!}
{8418}{}{¡Agh!}
{8419}{}{Me las pagarás...}
{8420}{}{Vamos, ¡inténtalo otra vez!}
{8421}{}{¡Oh! ¡Me has roto la pierna!}
{8422}{}{¡Uh! ¡La rodilla!}
{8423}{}{¡Oh! ¡Me has roto la pierna!}
{8424}{}{¡Uh! ¡La rodilla!}
{8425}{}{¡Aah! ¡No veo!}
{8426}{}{¡Me has dejado ciego, mamón!}
{8427}{}{Oooohhh...}
{8500}{}{Hora de una huida táctica}
{8501}{}{Esto durará poco}
{8502}{}{Adentro}
{8503}{}{Cómete ésta}
{8504}{}{Que tengas un buen día.}
{8505}{}{Tengo algo para ti}
{8506}{}{Casi}
{8507}{}{Cerca, pero no}
{8508}{}{Oh. Buen tiro}
{8509}{}{Ugh.}
{8510}{}{He perdido otro trozo de mi oreja...}
{8511}{}{Maldita sea, ahí va otro diente...}
{8512}{}{Ugh.}
{8513}{}{No necesitaba ese brazo de todas formas}
{8514}{}{Ay.}
{8515}{}{¡Toma, disparaba con esa mano!}
{8516}{}{Ay.}
{8517}{}{¡Toma, otra costilla destrozada!}
{8518}{}{Si quieres matarme, apunta a la cabeza}
{8519}{}{Puedes lisiarme poco a poco, pero te cogeré}
{8520}{}{Ya he tenido la pierna rota otras veces}
{8521}{}{Puedes lisiarme poco a poco, pero te cogeré}
{8522}{}{Ya he tenido la pierna rota otras veces}
{8523}{}{Eso es jugar sucio}
{8524}{}{Si estoy ciego, voy a hacerte mucho daño antes de matarte}
{8525}{}{¡Ugh! ¡Túmbate!}
{8526}{}{Oh, mis partes...}
{8527}{}{ESO duele}
{8600}{}{¿¡Por qué estás haciendo esto!?}
{8601}{}{¡No por favor, estoy desarmado!}
{8602}{}{¿Qué te sucedió?}
{8603}{}{¡Que alguien me ayude!}
{8604}{}{Esto está fuera de mi alcance}
{8605}{}{¡Dios mío, no!}
{8606}{}{¡Traidor!}
{8607}{}{¡No puedo creer que hayas hecho eso!}
{8608}{}{¡La superficie debe volver loca a la gente!}
{8609}{}{¡Te has vuelto loco!}
{8610}{}{¡A defender el Refugio!}
{8611}{}{¡Creía que eras mi amigo!}
{8612}{}{Nunca debiste haber vuelto}
{8613}{}{¡Y pensar que solíamos ser amigos!}
{8614}{}{Ojalá nunca hubieras salido a la superficie}
{8615}{}{Hola, viejo amigo. Hora de morir}
{8616}{}{Nunca debiste haber vuelto}
{8617}{}{¡Y pensar que solíamos ser amigos!}
{8618}{}{Ojalá nunca hubieras salido a la superficie}
{8619}{}{¡La superficie debe volver loca a la gente!}
{8620}{}{¡La superficie debe volver loca a la gente!}
{8621}{}{Hola, viejo amigo. Hora de morir}
{8622}{}{I saw that one coming}
{8623}{}{Peleabas mejor cuando éramos pequeños}
{8624}{}{Tu puntería no ha mejorado}
{8625}{}{Todavía das un paso atrás cada vez que intentas ese movimiento}
{8626}{}{Nunca podrás ganarme}
{8627}{}{¿Cómo te eligieron a ti para que salieras a la superficie?}
{8628}{}{¡Oh, me duele el cráneo!}
{8629}{}{Uh}
{8630}{}{Oooooh}
{8631}{}{¡Mi brazo!}
{8632}{}{¡Oh! He oído crujir algo...}
{8633}{}{Mi brazo se torció por completo}
{8634}{}{¡Mi brazo!}
{8635}{}{¡Oh! He oído crujir algo...}
{8636}{}{Mi brazo se torció por completo}
{8637}{}{¡Ow!}
{8638}{}{¡Uf! Y eso que éramos amigos...}
{8639}{}{¡Uf!}
{8640}{}{¡Oh! Vale, ¡eso es!}
{8641}{}{¡Oh! Estoy loco}
{8642}{}{¡Uf!}
{8643}{}{¡Agh!}
{8644}{}{¡Ay!}
{8645}{}{Todavía golpeas como una niña}
{8646}{}{¡Gulp!}
{8647}{}{¡Ow!}
{8648}{}{Mi pierna está empezando a torcerse}
{8649}{}{Oh, mi rodilla}
{8650}{}{Eh, ¡todavía necesito esa pierna!}
{8651}{}{Mi pierna está empezando a torcerse}
{8652}{}{Oh, mi rodilla}
{8653}{}{¡Aggghhh!}
{8654}{}{¡Pequeño bastardo!}
{8655}{}{¡Mis ojos!}
{8656}{}{Siempre te gustaron los golpes bajos...}
{8657}{}{Nunca cambiarás, ¿verdad?}
{8658}{}{Me siento mejor...}
{8659}{}{¡Ohh, la ingle!}
{8660}{}{Siempre fuiste el luchador más sucio de todo el Refugio}
{8661}{}{¡Pequeña rata asquerosa!}
{8700}{}{¡Vale, es toda tuya!}
{8701}{}{¡Te regalo a la zorra!}
{8702}{}{Tandi es tuya. ¡Déjame en paz!}
{8703}{}{¡Vale, es toda tuya!}
{8704}{}{Tandi es tuya. ¡Déjame en paz!}
{8705}{}{¡Te regalo a la zorra!}
{8706}{}{¡Que la lucha del honor comience!}
{8707}{}{¡Que la lucha del honor comience!}
{8708}{}{¡Que la lucha del honor comience!}
{8709}{}{¡Que la lucha del honor comience!}
{8710}{}{¡Que la lucha del honor comience!}
{8711}{}{¡Que la lucha del honor comience!}
{8712}{}{¡Seré yo el que te mate!}
{8713}{}{¡Sangre! ¡Sangre! ¡Sangre!}
{8714}{}{¡Soy una máquina!}
{8715}{}{¡¡RAAAAAAARRRR!!}
{8716}{}{¡Los Khans son invencibles!}
{8717}{}{¡Nunca nos retiramos! ¡Nunca nos rendimos!}
{8718}{}{¡Seré yo el que te mate!}
{8719}{}{¡Soy una máquina!}
{8720}{}{¡Sangre y oscuridad!}
{8721}{}{¡Los Khans son los que mandan!}
{8722}{}{¡Ja, ja, ja, ja, inténtalo de nuevo!}
{8723}{}{¡No me puedes tocar!}
{8724}{}{¡Soy indestructible!}
{8725}{}{¡Mi honor es mayor que el tuyo!}
{8726}{}{¡Mi honor es mayor que el tuyo!}
{8727}{}{¡No mereces luchar conmigo!}
{8728}{}{¡Un golpe de suerte!}
{8729}{}{¡Ese ha sido tu último ataque!}
{8730}{}{¡Un intento patético!}
{8731}{}{¡Aún te puedo ganar con un solo brazo!}
{8732}{}{¡Me has roto un brazo! Ahora estamos igualados}
{8733}{}{¡Me has roto un brazo! Ahora estamos igualados}
{8734}{}{¡Aún te puedo ganar con un solo brazo!}
{8735}{}{¡Me has roto un brazo! Ahora estamos igualados}
{8736}{}{¡Me has roto un brazo! Ahora estamos igualados}
{8737}{}{¡Por eso, tu muerte será legendaria!}
{8738}{}{¡Por eso que has hecho, lo festejaré con tus ojos!}
{8739}{}{¡Soy indestructible!}
{8740}{}{¡Uf!}
{8741}{}{¡Mi honor es mayor que el tuyo!}
{8742}{}{¡¡RAAAAAAARRRR!!}
{8743}{}{Me duelen las costillas. ¡Pronto te arrancaré las tuyas! Es lo justo}
{8744}{}{Me duelen las costillas. ¡Pronto te arrancaré las tuyas! Es lo justo}
{8745}{}{¡Soy indestructible!}
{8746}{}{¡Ay! ¡Eso duele!}
{8747}{}{¡No necesito estar de pie para matarte!}
{8748}{}{¡Vaya golpe más malo!}
{8749}{}{¡Mi pierna! ¡Te quitaré la tuya con mis puños!}
{8750}{}{¡No necesito estar de pie para matarte!}
{8751}{}{¡Vaya golpe más malo!}
{8752}{}{¡Mi pierna! ¡Te quitaré la tuya con mis puños!}
{8753}{}{¡Mi ojo! ¡Morirás lentamente por eso!}
{8754}{}{¡Mis ojos! ¡Canjearé mi vista por tu muerte!}
{8755}{}{¡No ha sido muy caballeroso!}
{8756}{}{¡Auu! Mutilaré tu...}
{8757}{}{¡Auu! Mutilaré tu...}
{8758}{}{¡Auu! Tú... vas... ha sufrir...}
{8759}{}{¡Auu! Tú... vas... ha sufrir...}
{8760}{}{¡No me robarás la hombría!}
{8761}{}{¡No me robarás la hombría!}
{8862}{}{}
{8863}{}{}
{8864}{}{}
{8865}{}{}
{8866}{}{}
{8867}{}{}
{8868}{}{}
{8869}{}{}
{8870}{}{}
{8871}{}{}
{8872}{}{}
{8873}{}{}
{8874}{}{[bufe]}
{8875}{}{}
{8876}{}{[gruñe]}
{8877}{}{[bufe]}
{8878}{}{}
{8879}{}{[gruñe]}
{8880}{}{[bufe]}
{8881}{}{}
{8882}{}{[gruñe]}
{8883}{}{[bufe]}
{8884}{}{}
{8885}{}{[gruñe]}
{8886}{}{[bufe]}
{8887}{}{}
{8888}{}{[gruñe]}
{8889}{}{[bufe]}
{8890}{}{}
{8891}{}{[gruñe]}
{8892}{}{[bufe]}
{8893}{}{}
{8894}{}{[gruñe]}
{8895}{}{[bufe]}
{8896}{}{}
{8897}{}{[gruñe]}
{8900}{}{¡No me enrolé para esto!}
{8901}{}{¡No me pagan lo suficiente para esto!}
{8902}{}{¡Retrocede!}
{8903}{}{¡Reagrupamiento!}
{8904}{}{¡No pienso morir por esto!}
{8905}{}{Ya tengo suficiente}
{8906}{}{I'm gonna teach you a lesson}
{8907}{}{¡Acabas de cometer un grave error!}
{8908}{}{Let's settle this like scavs}
{8909}{}{Veamos de qué estás hecho}
{8910}{}{Va a conseguir creativo con este}
{8911}{}{La sangre resuelve lo que las palabras no pueden}
{8912}{}{¡Cómete esto!}
{8913}{}{Take it!}
{8914}{}{Having second thoughts?}
{8915}{}{Hey look, target practice}
{8916}{}{Siempre disfruto de un buen entrenamiento}
{8917}{}{Any last words?}
{8918}{}{Veamos lo duro que eres...}
{8919}{}{Veamos lo duro que eres...}
{8920}{}{Having second thoughts?}
{8921}{}{Veamos si te gusta esto}
{8922}{}{Haha, too slow}
{8923}{}{Hace años que hago esto, mocoso}
{8924}{}{No eres lo bastante bueno}
{8925}{}{Don't forget, I was a scav}
{8926}{}{Are you for real?}
{8927}{}{Don't forget, I was a scav}
{8928}{}{Ow! You fucker}
{8929}{}{Te mataré por esto}
{8930}{}{Creo que podría tener una conmoción cerebral}
{8931}{}{Eso no ha estado bien}
{8932}{}{¡Maldita sea, tengo el brazo destrozado!}
{8933}{}{¡Joder, me la has roto!}
{8934}{}{GAH!}
{8935}{}{Puto listillo}
{8936}{}{¡Mi brazo!}
{8937}{}{¡Oh!}
{8938}{}{I liked that organ}
{8939}{}{You'll regret that}
{8940}{}{¡Mis costillas!}
{8941}{}{¡Mi rodilla!}
{8942}{}{¡Me las pagarás por esto!}
{8943}{}{Shit, my leg's going numb}
{8944}{}{You'll regret that}
{8945}{}{Espero no quedarme cojo}
{8946}{}{¡Mi rodilla!}
{8947}{}{¡No veo!}
{8948}{}{¡Mi ojo!}
{8949}{}{¡Mierda! al menos tengo otro}
{8950}{}{I didn't want to have kids anyway}
{8951}{}{Joder, buen tiro}
{8952}{}{You fight dirty!}
{8953}{}{¡Uf!}
{8954}{}{What a cheap shot}
{8955}{}{I didn't want to have kids anyway}
