{0}{}{End simulation and return to main menu?}
{1}{}{Versión Demo}
{2}{}{Se usará el personaje por defecto.}
{3}{}{Captura guardada.}
{4}{}{Carga rápido completada.}
{5}{}{Guardado rápido completado.}
{6}{}{Sobrepasado límite de tiempo de la demo.}
{7}{}{¡Pip-Boy no disponible durante el combate!}
{8}{}{Error guardando la captura.}
{9}{}{INTRODUCCION}
{10}{}{NUEVO JUEGO}
{11}{}{CARGAR PARTIDA}
{12}{}{CREDITOS}
{13}{}{SALIR}
{14}{}{Fallout Fixt v0.PRUEBAS por Sduibek. DESCARGAR: de la Prueba. INSTALAR: Pruebas.}
{15}{}{Ptos. Acción}
{16}{}{Puntos de Salud}
{17}{}{Error: motion sensor not available!}
{18}{}{Al Sensor de Movimiento no le queda carga.}
{100}{}{¡Error al guardar el archivo de configuración del juego!}
{101}{}{Preferencias no guardadas.}
{1000}{}{Sientes algo de náuseas y tu piel está sensible.}
{1001}{}{Te sientes muy mareado, y tras vomitar levemente, ligeramente fatigado.}
{1002}{}{Estás muy fatigado, no paras de vomitar, y tu tiempo de recuperación se ve afectado.}
{1003}{}{Sufres una violenta hemorragia. Estás muy enfermo, y tu pelo se está cayendo.}
{1004}{}{Tienes una violenta hemorragia. Tus vómitos están manchados de sangre. La piel se despega de tus huesos.}
{1005}{}{Te sangran los intestinos y tienes una severa diarrea. Te sientes hinchado y sufres una intensa agonía.}
{1006}{}{Has muerto por envenenamiento por radiación.}
{1007}{}{Has recibido una gran cantidad de radiación.}
{1008}{}{El contador Geiger está sonando.}
{1009}{}{El contador Geiger suena salvajemente.}
{2000}{}{Acción abortada.}
{2001}{}{La cerradura está atascada.}
{3000}{}{¡Has sido envenenado!}
{3001}{}{You sustain 1 hit point of damage from the poison.}
{4000}{}{Due to your inept handling, the explosives detonate prematurely.}
{5000}{}{usa}
{5001}{}{se ha quedado sin munición para}
{5002}{}{recarga su}
{6000}{}{¿Sobre qué quieres preguntarme?}
