{0}{}{End simulation and return to main menu?}
{1}{}{Versión Demo}
{2}{}{Se usará el personaje por defecto.}
{3}{}{Pantalla guardada.}
{4}{}{Carga rápido completada.}
{5}{}{Guardado rápido completado.}
{6}{}{Sobrepasado límite de tiempo de la demo.}
{7}{}{¡Pip-Boy no disponible durante el combate!}
{8}{}{Error al guardar pantalla.}
{9}{}{INTRODUCCION}
{10}{}{NUEVA PARTIDA}
{11}{}{CARGAR PARTIDA}
{12}{}{CREDITOS}
{13}{}{EXIT}
{14}{}{Fallout Fixt v0.TESTING by Sduibek. DOWNLOAD: Testing. INSTALL: Testing.}
{15}{}{Puntos de Acción}
{16}{}{Puntos de Salud}
{17}{}{Error: motion sensor not available!}
{18}{}{Al Sensor de Movimiento no le queda carga.}
{100}{}{¡Error al guardar el archivo de configuración del juego!}
{101}{}{Configuraciones del juego no guardadas.}
{1000}{}{Sientes algo de náuseas y tu piel está sensible.}
{1001}{}{Sientes muchas náuseas, después de vomitar un poco te sientes cansado.}
{1002}{}{Sientes gran cansancio, no paras de vomitar y tu recuperación es difícil.}
{1003}{}{Tienes una violenta hemorragia. Estás muy mal y se te está cayendo el pelo.}
{1004}{}{Tienes una violenta hemorragia. Tus vómitos están manchados de sangre. La piel se despega de tus huesos.}
{1005}{}{Te sangran los intestinos y tienes una fuerte diarrea. Te sientes hinchado y sufres gran agonía.}
{1006}{}{La radiación te han matado.}
{1007}{}{Has recibido una gran cantidad de radiación.}
{1008}{}{The geiger counter is clicking.}
{1009}{}{The geiger counter is clicking wildly.}
{2000}{}{Acción abortada.}
{2001}{}{La cerradura está atascado.}
{3000}{}{¡Te han envenenado!}
{3001}{}{You sustain 1 hit point of damage from the poison.}
{4000}{}{Due to your inept handling, the explosives detonate prematurely.}
{5000}{}{usa}
{5001}{}{se ha quedado sin munición para}
{5002}{}{recarga su}
{6000}{}{¿Preguntar sobre qué?}
