{10}{}{<Nada>}
{100}{}{Cristal}
{101}{}{Metal}
{102}{}{Plástico}
{103}{}{Madera}
{104}{}{Porquería}
{105}{}{Piedra}
{106}{}{Cemento}
{107}{}{Cuero}
{150}{}{Armadura}
{151}{}{Contenedor}
{152}{}{Droga}
{153}{}{Arma}
{154}{}{Munición}
{155}{}{Objetos Variados}
{156}{}{Llave}
{200}{}{Portal}
{201}{}{Escaleras}
{202}{}{el ascensor}
{203}{}{Base de Escalera}
{204}{}{Final de Escalera}
{205}{}{Escenario Genérico}
{250}{}{normal_dam}
{251}{}{laser}
{252}{}{fire}
{253}{}{plasma}
{254}{}{electrical}
{255}{}{emp}
{256}{}{explosion}
{300}{}{Ninguno}
{301}{}{Cohete}
{302}{}{Flamer Fuel}
{303}{}{Célula de Energía C}
{304}{}{Célula de Energía D}
{305}{}{.223}
{306}{}{5mm}
{307}{}{Calibre .40}
{308}{}{10mm}
{309}{}{Calibre .44}
{310}{}{14mm}
{311}{}{Calibre 12}
{312}{}{9mm}
{313}{}{BB}
{314}{}{RESERVED}
{315}{}{RESERVED}
{316}{}{RESERVED}
{317}{}{RESERVED}
{318}{}{RESERVED}
{350}{}{Caucasiano}
{351}{}{Africano}
{400}{}{Bípedo}
{401}{}{Cuadrúpedo}
{402}{}{Robótico}
{450}{}{Hombres:}
{451}{}{Mujeres:}
{452}{}{Niños:}
{453}{}{Supermutantes:}
{454}{}{Necrófagos:}
{455}{}{Brahmines:}
{456}{}{Escorpiones Rad:}
{457}{}{Ratas:}
{458}{}{Flotantes:}
{459}{}{Centauros:}
{460}{}{Robots:}
{461}{}{Perros:}
{462}{}{Mantis:}
{463}{}{Garras Mortales:}
{464}{}{The Master:}
{465}{}{This is the number of adult human males that you have permanently and forcefully removed from the gene pool.}
{466}{}{Esta línea muestra el número de humanos adultos de sexo femenino que has liquidado brutalmente en el transcurso de tus aventuras.}
{467}{}{La cantidad de inocentes e indefensos niños humanos que has matado en el transcurso de tus aventuras. Canalla.}
{468}{}{Este es el número total de espantosos Supermutantes que has masacrado a través del yermo.}
{469}{}{Número de criaturas irradiadas con aspecto de zombi has puesto a descansar. Incluye miembros de ambos sexos. (Tampoco hay mucha diferencia en lo que a ti te concierne)}
{470}{}{This is the tally of how many brahmin (mutant two-headed cows) you have chopped up and butchered during your travels.}
{471}{}{This is the number of huge mutated scorpions that you have exterminated as you strode the land.}
{472}{}{Este es el número de adorables y peludas ratas que has eliminado de la cadena alimenticia. Incluye a todos los miembros de la familia de las ratas.}
{473}{}{Este es el número total de esas criaturas mutantes extrañas y flotantes a las que has dado muerte con gusto.}
{474}{}{Tu lista de cuantos monstruosos multicéfalos y multípedos Centauros has tenido el placer de ejecutar.}
{475}{}{Este es el número de robots que has destruido sin ninguna piedad, convertido en piezas de repuesto, o simplemente desactivado.}
{476}{}{This line shows how many nice friendly doggies you have sent to the great kennel in the sky, you heartless jerk.}
{477}{}{This is the total number of manti (oversized mutated preying mantis-like insects) that you have squashed so far.}
{478}{}{This line indicates that you have slain the legendary Deathclaw, and/or any of her many ferocious spawn. Well done.}
{479}{}{This indicates you have killed the Master. Master! Master.}
{480}{}{Ves: %s.}
{485}{}{Examinas: %s.}
{486}{}{Cierras: %s.}
{487}{}{Está cerrada.}
{490}{}{Ves: %s.}
{491}{}{Ves un cadáver: %s.}
{492}{}{Ves los restos de: %s.}
{493}{}{No ves nada fuera de lo común.}
{500}{}{no tener pulso}
{501}{}{estar a punto de morir}
{502}{}{tener heridas graves}
{503}{}{tener heridas}
{504}{}{gozar de buena salud}
{510}{}{Mod. de CA: %d}
{511}{}{Mod. de RD: %d}
{512}{}{Mod. de daño: %d/%d}
{518}{}{Pareces %s }
{519}{}{%s %s }
{520}{}{Pareces %s.}
{521}{}{%s %s.}
{522}{}{Parece: %s }
{523}{}{Parece: %s }
{524}{}{Parece: %s }
{525}{}{%s tiene %d/%d puntos de salud.}
{526}{}{Tiene %d/%d disparos de %s.}
{530}{}{y tiene las extremidades rotas.}
{531}{}{pero tiene las extremidades rotas.}
{532}{}{y tiene las extremidades rotas.}
{533}{}{pero tiene las extremidades rotas.}
{535}{}{Tiene %d/%d puntos de salud}
{536}{}{Tiene %d/%d puntos de salud}
{537}{}{Tiene %d/%d puntos de salud}
{540}{}{Pesa %d libras.}
{541}{}{Pesa %d libra.}
{544}{}{, }
{545}{}{.}
{546}{}{ y está empuñando un/una %s.}
{547}{}{ y está empuñando un/una %s con %d/%d disparos de %s.}
{550}{}{\nError: ¡lookup_val fuera de alcance!}
{551}{}{\nError: obj_examine: ¡proto_ptr ha fallado!}
{580}{}{Usas el %s.}
{581}{}{Usas el %s sobre %s.}
{582}{}{Eso no hace nada de interés.}
{583}{}{Para tu consternación descubres que ya está muerto.}
{584}{}{Cuando llegas, descubres que ya está muerto.}
{585}{}{Lástima, llegas demasiado tarde.}
{586}{}{Eso no funciona con los muertos.}
{587}{}{Enciendes la bengala.}
{588}{}{La bengala ya está encendida.}
{589}{}{Pones en hora el reloj.}
{590}{}{¡El reloj ya está en funcionamiento!}
{620}{}{Ganas %d puntos de experiencia por matar: %s.}
{621}{}{%s ganas %d puntos de experiencia.}
{622}{}{Por derrotar a tus enemigos,}
{623}{}{Por asesinar a tus enemigos,}
{624}{}{Vences en el combate;}
{625}{}{Por aplastar a tus enemigos,}
{626}{}{Por destruir a tus enemigos sin sufrir un rasguño,}
{650}{}{[Hecho]}
{651}{}{[Más]}
{652}{}{[Más]}
{653}{}{[Volver]}
{654}{}{[Volver]}
{655}{}{[Continuar]}
{656}{}{Err...}
{660}{}{Allí no puedes ver.}
{661}{}{Demasiado lejos.}
{670}{}{Vale.}
{671}{}{Claro.}
{672}{}{Como quieras.}
{673}{}{Lo que tú digas.}
{674}{}{Lo intentaré.}
{675}{}{No puedo hacer eso.}
{676}{}{No creo que pueda hacerlo.}
{677}{}{¡Arf!}
{678}{}{¡Guau!}
{700}{}{You do not have enough Action Points to do that.}
{800}{}{Lees el libro.}
{801}{}{No aprendes nada nuevo.}
{802}{}{Aprendes sobre la aplicación práctica de las ciencias y la tecnología.}
{803}{}{Aprendes sobre reparación de aparatos electrónicos y mecánicos.}
{804}{}{Aprendes mejores técnicas de curación de heridas.}
{805}{}{Aprendes cómo manejar y mantener mejor tus armas.}
{806}{}{Aprendes mucho sobre técnicas de supervivencia.}
{900}{}{Los suministros del maletín médico se han agotado.}
{901}{}{Los suministros del botiquín de primeros auxilios se han agotado.}
{902}{}{No puedes hacer eso en combate.}
{903}{}{Esa persona no hará trueques contigo.}
{904}{}{Esa persona no tiene nada que decirte.}
{905}{}{No puedes recoger esto. Llevas ya todo el peso que puedes.}
{913}{}{Esta criatura es incapaz de llevar nada.}
