{101}{}{}
{102}{}{}
{103}{}{Comerciante de Arenas Sombrías}
{104}{}{Guardaespaldas}
{105}{}{Brahmin}
{106}{}{Guardia del Foso de los Pistoleros}
{107}{}{Guardia}
{108}{}{Perdedor}
{109}{}{Campesino de Arenas Sombrías}
{110}{}{Pistolero}
{111}{}{Entrada al Mapa}
{112}{}{}
{113}{}{Centinela Supermutante}
{114}{}{Pozo de Arenas Sombrías}
{115}{}{Set}
{116}{}{Harry}
{117}{}{Estimulante}
{118}{}{una tapa}
{119}{}{Alcantarilla}
{120}{}{Escalera}
{121}{}{Silla}
{122}{}{Máquina de Nuka-Cola}
{123}{}{Mesa del Encargado}
{124}{}{Cadáver}
{125}{}{una mesa}
{126}{}{Cadáver de Necrófago}
{127}{}{}
{128}{}{Alcantarilla}
{129}{}{Escalera}
{130}{}{Gerente Necrófago}
{131}{}{Mapa Manuscrito}
{132}{}{Necrófago}
{133}{}{Aradesh}
{134}{}{Brahmin}
{135}{}{Cougar}
{136}{}{Flash}
{137}{}{Guardia de Ciudad Vertedero}
{138}{}{Campesino de Ciudad Vertedero}
{139}{}{Butch}
{140}{}{Cabbot}
{141}{}{Niño de la Catedral}
{142}{}{Decker}
{143}{}{Anciano}
{144}{}{Gizmo}
{145}{}{Harold}
{146}{}{Jain}
{147}{}{Killian}
{148}{}{Laura}
{149}{}{Loxley}
{150}{}{El Teniente}
{151}{}{Maestro}
{152}{}{Maxson}
{153}{}{Morfeo}
{154}{}{Nicole}
{155}{}{El Supervisor}
{156}{}{Rhombus}
{157}{}{Tandi}
{158}{}{Vree}
{159}{}{}
{160}{}{Cámara de Aire de Necrópolis}
{161}{}{Barry}
{162}{}{Computadora}
{163}{}{Puerta}
{164}{}{Bandido Necrófagos}
{165}{}{Gary}
{166}{}{Necrófago}
{167}{}{Necrófago}
{168}{}{Resplandeciente}
{169}{}{Cadáver de Necrófago}
{170}{}{Centinela Necrófago}
{171}{}{Cadáver de Necrófago}
{172}{}{Guardia de Set}
{173}{}{Gerente Necrófago}
{174}{}{Refugiado Necrófago}
{175}{}{Guardia Necrófago}
{176}{}{Resplandeciente enjaulado}
{177}{}{Subterráneo}
{178}{}{Guardia}
{179}{}{Harry}
{180}{}{Larry}
{181}{}{Líder Subterráneo}
{182}{}{Gerente Necrófago}
{183}{}{Cadáver mutilado}
{184}{}{Campesino Necrófago}
{185}{}{Supermutante}
{186}{}{Ordenador de Agua}
{187}{}{la bomba de agua}
{188}{}{Muro}
{189}{}{Prisionero Necrófago}
{190}{}{Sally}
{191}{}{Grafiti}
{192}{}{Nevera de Set}
{193}{}{Mesa de Set}
{194}{}{Puerta}
{195}{}{Guardaespaldas de Set}
{196}{}{Muro}
{197}{}{Olor extraño}
{198}{}{Estimulante}
{199}{}{Despensa de Necrópolis}
{200}{}{Supermutante}
{201}{}{Terry}
{202}{}{Garret}
{203}{}{Gretch}
{204}{}{Doc Mórbid}
{205}{}{Dumar}
{206}{}{Barstow}
{207}{}{Iniciado de los Niños de la Catedral}
{208}{}{Curandero de los Niños de la Catedral}
{209}{}{Centinela Subterráneo}
{210}{}{Computadora}
{211}{}{Habitación cerrada}
{212}{}{Desierto}
{213}{}{Guardia}
{214}{}{Cocinero de Arenas Sombrías}
{215}{}{Ciudadano de Arenas Sombrías}
{216}{}{Silla}
{217}{}{Cama de Agatha}
{218}{}{Cama de Razlo}
{219}{}{Mujer de Razlo}
{220}{}{una cómoda}
{221}{}{una esterilla}
{222}{}{una estantería}
{223}{}{Fuente de Fruta}
{224}{}{una mesa}
{225}{}{Estante}
{226}{}{una mesa}
{227}{}{Fruta Alterada}
{228}{}{Olor a corral de Brahmines}
{229}{}{Razlo}
{230}{}{Ciudadano del Refugio 13}
{231}{}{Cámara de Aire del Refugio 13}
{232}{}{Monitor del Refugio 13}
{233}{}{Sistema Central del Refugio 13}
{234}{}{Ordenador de la Biblioteca del Refugio 13}
{235}{}{Kalnor}
{236}{}{Saqueador}
{237}{}{Garl}
{238}{}{Prisionero de los Saqueadores}
{239}{}{Petrox}
{240}{}{Tolya}
{241}{}{Gwen}
{242}{}{Diana}
{243}{}{Alya}
{244}{}{Aposentos}
{245}{}{Sala de Reuniones}
{246}{}{Despensa}
{247}{}{Biblioteca}
{248}{}{Sistema Central}
{249}{}{Sala de Reuniones}
{250}{}{Aposentos}
{251}{}{Aposentos}
{252}{}{Pasadizo cerrado}
{253}{}{Pasadizo cerrado}
{254}{}{Cámara de Aire}
{255}{}{Sala de los Difuntos}
{256}{}{Gabriel}
{257}{}{una mesa de dados}
{258}{}{Alcantarilla}
{259}{}{Alcantarilla}
{260}{}{Escalera}
{261}{}{Escalera}
{262}{}{Guardia de la Puerta}
{263}{}{Guardia de la Ración de Agua}
{264}{}{Almacén de Agua}
{265}{}{Alcantarilla}
{266}{}{Alcantarilla}
{267}{}{Alcantarilla}
{268}{}{Ciudadano del Refugio 13}
{269}{}{Escalera}
{270}{}{Escalera}
{271}{}{Escalera}
{272}{}{Andrew}
{273}{}{Hotel de los Difuntos}
{274}{}{Lorraine}
{275}{}{Alcantarilla}
{276}{}{Alcantarilla}
{277}{}{Alcantarilla}
{278}{}{Oficial del Refugio 13}
{279}{}{Escalera}
{280}{}{Escalera}
{281}{}{Escalera}
{282}{}{Cuevas de los Escorpiones Rad}
{283}{}{Seth}
{284}{}{Médico del Refugio 13}
{285}{}{Ciudadano del Refugio 13}
{286}{}{Casino de Ciudad Vertedero}
{287}{}{Posada de Ciudad Vertedero}
{288}{}{Entrada a Ciudad Vertedero}
{289}{}{Pasadizo cerrado}
{290}{}{Cámara de Aire}
{291}{}{Escondite Médico}
{292}{}{Entrada al Refugio 15}
{293}{}{Arenas Sombrías}
{294}{}{Arenas Sombrías}
{295}{}{Laboratorio Médico}
{296}{}{Choza Abandonada}
{297}{}{Seth}
{298}{}{Escriba de la Hermandad}
{299}{}{Refugio 13}
{300}{}{Ascensor}
{301}{}{Ascensor}
{302}{}{Ascensor}
{303}{}{Ascensor}
{304}{}{Ascensor Roto}
{305}{}{Entrada a la Hermandad del Acero}
{306}{}{Comedero de ratas}
{307}{}{Oscuridad}
{308}{}{Abertura de Cueva}
{309}{}{Ciudadano del Refugio 13}
{310}{}{Tus Aposentos}
{311}{}{Katrina}
{312}{}{Abertura de Cueva}
{313}{}{Sistema Central del Refugio 13}
{314}{}{Computadora}
{315}{}{Sala de Operaciones del Refugio 13}
{316}{}{Sala de Seguridad del Refugio 13}
{317}{}{Despensa del Refugio 13}
{318}{}{Sala de Reuniones del Refugio 13}
{319}{}{Laboratorio Médico del Refugio 13}
{320}{}{Desguace}
{321}{}{Guardia de Ciudad Vertedero}
{322}{}{}
{323}{}{Bengala}
{324}{}{Ascensor}
{325}{}{Ascensor}
{326}{}{Ascensor}
{327}{}{Ascensor}
{328}{}{Refugio 15}
{329}{}{Perro}
{330}{}{Guardia Necrófago}
{331}{}{Necrófago Enfadado}
{332}{}{Guardia Supermutante}
{333}{}{Centinela Supermutante}
{334}{}{Supermutante}
{335}{}{Ian}
{336}{}{Curtis}
{337}{}{}
{338}{}{Los Khans}
{339}{}{Fruta Alterada}
{340}{}{Guardia Saqueador}
{341}{}{Avellone}
{342}{}{Perro}
{343}{}{Duc}
{344}{}{Ciudad}
{345}{}{Costa}
{346}{}{Montaña}
{347}{}{Hernández}
{348}{}{Cuevas}
{349}{}{Miles}
{350}{}{Smitty}
{351}{}{Residencia de Adytum}
{352}{}{Regulador}
{353}{}{Lorraine}
{354}{}{Sammael}
{355}{}{Caleb}
{356}{}{Tine}
{357}{}{Julianna}
{358}{}{Erudito de los Seguidores}
{359}{}{Iniciado de los Seguidores}
{360}{}{Explorador de los Nocturnos}
{361}{}{Erudito de los Niños de la Catedral}
{362}{}{Iniciado de los Niños de la Catedral}
{363}{}{Explorador de los Seguidores}
{364}{}{Guardia de los Seguidores}
{365}{}{Supermutante Intelectual}
{366}{}{Heather}
{367}{}{Peter}
{368}{}{Jake}
{369}{}{Orfeo}
{370}{}{Marney}
{371}{}{Neil}
{372}{}{Amber}
{373}{}{Uthern}
{374}{}{Talius}
{375}{}{Guardia de los Niños de la Catedral}
{376}{}{Explorador de los Niños de la Catedral}
{377}{}{Explorador Supermutante}
{378}{}{Cuchilla}
{379}{}{Bandido de los Navajas}
{380}{}{Fuego}
{381}{}{Beca}
{382}{}{Maestro de Armas de los Navajas}
{383}{}{Michelle}
{384}{}{Vigilante Nocturno de los Navajas}
{385}{}{Romero}
{386}{}{Hermandad del Acero}
{387}{}{Hermandad del Acero}
{388}{}{Jon}
{389}{}{Prisionero}
{390}{}{Escriba de la Hermandad}
{391}{}{Escalera}
{392}{}{Cuerpo Carbonizado}
{393}{}{Huesos Secos}
{394}{}{Persona en una armadura extraña}
{395}{}{Holodisco Vacío}
{396}{}{Punto caliente de Radiación}
{397}{}{Persona en una armadura extraña}
{398}{}{Puerta Segura}
{399}{}{Computadora}
{400}{}{Puerta Segura}
{401}{}{Generador}
{402}{}{la bomba de agua}
{403}{}{Aposentos}
{404}{}{Arma de Centinela}
{405}{}{Puerta pintada de rojo}
{406}{}{Puerta pintada de azul}
{407}{}{Puerta Segura}
{408}{}{Caja de Seguridad}
{409}{}{Ordenador de Control de Defensas}
{410}{}{Jaula}
{411}{}{una mesa}
{412}{}{Superordenador}
{413}{}{Esqueleto extraño}
{414}{}{Nota}
{415}{}{Farli}
{416}{}{Darrel}
{417}{}{Guardia Paladín de la Hermandad}
{418}{}{Talus}
{419}{}{Sophia}
{420}{}{Michael}
{421}{}{Puerta Segura}
{422}{}{Escriba de la Hermandad}
{423}{}{Escriba de la Hermandad}
{424}{}{Centinela Paladín de la Hermandad}
{425}{}{Paladín de la Hermandad}
{426}{}{Guardia Paladín de la Hermandad}
{427}{}{Paladín de la Hermandad}
{428}{}{Ascensor pintado de azul}
{429}{}{Caballero de La Hermandad}
{430}{}{Caballero de La Hermandad}
{431}{}{una mesa}
{432}{}{Sistemas de Armas Activados}
{433}{}{Disco Antiguo Hermandad}
{434}{}{Vitrina}
{435}{}{Vapores Nocivos}
{436}{}{Láseres}
{437}{}{Saqueador Enloquecido}
{438}{}{Sinthia}
{439}{}{Marcelles}
{440}{}{Depósito Seguro}
{441}{}{Bob}
{442}{}{Trish}
{443}{}{Puerta del Refugio 13}
{444}{}{Puerta al Ordenador}
{445}{}{Disco de Experimentos Alfa}
{446}{}{Disco de Experimentos Delta}
{447}{}{Disco de Experimentos VEF}
{448}{}{Informes de Autopsia Vree}
{449}{}{Disco de Anulación de Seguridad}
{450}{}{Disco Decodificador de Cifrados}
{451}{}{Jugador}
{452}{}{Phil}
{453}{}{Albóndiga}
{454}{}{una máquina tragaperras}
{455}{}{una máquina tragaperras}
{456}{}{Mesa de Blackjack}
{457}{}{Mesa de Blackjack}
{458}{}{Técnico de los Niños de la Catedral}
{459}{}{Abel}
{460}{}{un campo de fuerza}
{461}{}{Radio}
{462}{}{una señal}
{463}{}{Puerta muy Segura}
{464}{}{Computadora}
{465}{}{Cerebrobot}
{466}{}{Cerebrobot}
{467}{}{Flip}
{468}{}{Computadora}
{469}{}{Sargento de los Nocturnos}
{470}{}{Centinela de los Nocturnos}
{471}{}{Computadora}
{472}{}{Lenore}
{473}{}{Computadora}
{474}{}{Perro}
{475}{}{Lenore}
{476}{}{Phil}
{477}{}{Zack}
{478}{}{Theresa}
{479}{}{Ciudadano triste del Refugio 13}
{480}{}{Refrigerador}
{481}{}{Escriba de la Hermandad}
{482}{}{Jason}
{483}{}{Gorila}
{484}{}{Fustigador}
{485}{}{Vinnie}
{486}{}{Víctor}
{487}{}{Tiburón}
{488}{}{Sherry}
{489}{}{Tycho}
{490}{}{Bandido de los Kalaveras}
{491}{}{Barriobajero}
{492}{}{Zark}
{493}{}{Calder}
{494}{}{Centinela de los Nocturnos}
{495}{}{Niño con carácter}
{496}{}{Miembro del Coro}
{497}{}{Tonelada}
{498}{}{Miembro del Coro}
{499}{}{Hermana Francis}
{500}{}{Dr. Wu}
{501}{}{Rutger}
{502}{}{Phrax}
{503}{}{Generador}
{504}{}{Bandido de la Cripta}
{505}{}{Capataz Tonto}
{506}{}{Lenny}
{507}{}{Piqueta}
{508}{}{Skizzer}
{509}{}{Ciudadano de Desguace}
{510}{}{una piedra}
{511}{}{Lex}
{512}{}{Rayze}
{513}{}{Skippy}
{514}{}{Baka}
{515}{}{Explorar las Criptas}
{516}{}{Explorar a los Locos}
{517}{}{Seguidor del Apocalipsis}
{518}{}{Computadora}
{519}{}{}
{520}{}{Refrigerador}
{521}{}{Escalera}
{522}{}{Escalera}
{523}{}{Alcantarilla}
{524}{}{Alcantarilla}
{525}{}{Refugio de Necrópolis}
{526}{}{Mapa de la Ciudad}
{527}{}{Puerta de Cámara de Aire}
{528}{}{una estantería}
{529}{}{una estantería}
{530}{}{Cuevas}
{531}{}{Puerta Segura}
{532}{}{Centro de Mando}
{533}{}{Centinela Supermutante}
{534}{}{Krupper}
{535}{}{Van Haggen}
{536}{}{Vásquez}
{537}{}{Explorador de Ciudad Vertedero}
{538}{}{Ciudadano de Ciudad Vertedero}
{539}{}{Saqueador}
{540}{}{Jarvis}
{541}{}{Fortaleza}
{542}{}{Tanques}
{543}{}{Entrada a la Base Militar}
{544}{}{Niños de la Catedral}
{545}{}{Niños de la Catedral}
{546}{}{Refugio del Maestro}
{547}{}{Refugio del Maestro}
{548}{}{Computadora}
{549}{}{una cabeza nuclear}
{550}{}{Ascensor}
{551}{}{Ascensor}
{552}{}{Hueco de Escalera}
{553}{}{una escalera}
{554}{}{una escalera}
{555}{}{Hueco de Escalera}
{556}{}{Puerta}
{557}{}{Cuevas}
{558}{}{Refugio 13}
{559}{}{Puerta Segura}
{560}{}{Focos}
{561}{}{Ladrón de Agua}
{562}{}{Jennifer}
{563}{}{Explosión}
{564}{}{Silla}
{565}{}{Muro de la Cueva}
{566}{}{Ascensor}
{567}{}{Ascensor}
{568}{}{Ascensor}
{569}{}{Ascensor}
{570}{}{Ascensor}
{571}{}{Ascensor}
{572}{}{Ascensor}
{573}{}{Barfly}
{574}{}{Refugio 15}
{575}{}{Camión de Nuka-Cola}
{576}{}{Platillo Volante}
{577}{}{Ardor}
{578}{}{Ardor}
{579}{}{Ardor}
{580}{}{Cementerio de LA}
{581}{}{Cementerio de LA}
{582}{}{Cementerio de LA}
{583}{}{Cementerio de LA}
{584}{}{Eje}
{585}{}{Eje}
{586}{}{Eje}
{587}{}{Eje}
{588}{}{Eje}
{589}{}{Cueva}
{590}{}{Extraña Cabina de Teléfonos}
{591}{}{Gran Huella}
{592}{}{Desguace}
{593}{}{Rebaño de Brahmines}
{594}{}{Alcantarilla}
{595}{}{Escalera}
{596}{}{Viola}
{597}{}{Surf}
{598}{}{Puerta}
{599}{}{Dane}
{600}{}{Jonathan}
{601}{}{Estudiante de la Hermandad}
{602}{}{Niños de la Catedral}
{603}{}{Puerta Segura}
{604}{}{Alcantarillas}
{605}{}{Alcantarillas}
{606}{}{Alcantarillas}
{607}{}{Lyle}
{608}{}{Neal}
{609}{}{el suelo}
{610}{}{Kenji}
{611}{}{Ardor}
{612}{}{Ardor}
{613}{}{una escalera}
{614}{}{una escalera}
{615}{}{una escalera}
{616}{}{Base Militar}
{617}{}{}
{618}{}{Lars}
{619}{}{Ascensor}
{620}{}{Ascensor}
{621}{}{Ascensor}
{622}{}{Ascensor}
{623}{}{Ascensor}
{624}{}{Soldado Supermutante}
{625}{}{Sargento Supermutante}
{626}{}{Puerta muy Segura}
{627}{}{Trofeo}
{628}{}{Saúl}
{629}{}{Gustofer}
{630}{}{}
{631}{}{Centinela Supermutante}
{632}{}{Sargento de los Nocturnos}
{633}{}{Centinela Supermutante}
{634}{}{Holodisk}
{635}{}{Garret}
{636}{}{Guardia Nocturno}
{637}{}{un campo de fuerza}
{638}{}{un campo de fuerza}
{639}{}{un campo de fuerza}
{640}{}{un campo de fuerza}
{641}{}{un campo de fuerza}
{642}{}{un campo de fuerza}
{643}{}{un campo de fuerza}
{644}{}{un campo de fuerza}
{645}{}{Computadora}
{646}{}{Guardia Supermutante}
{647}{}{Guardia Supermutante}
{648}{}{Guardia Supermutante}
{649}{}{Guardia Supermutante}
{650}{}{Guardia Supermutante}
{651}{}{Guardia Supermutante}
{652}{}{Guardia Supermutante}
{653}{}{Guardia Supermutante}
{654}{}{Guardia de Lorenzo}
{655}{}{Guardia de Lorenzo}
{656}{}{Billy}
{657}{}{Bob}
{658}{}{una señal}
{659}{}{Guardia de Lorenzo}
{660}{}{Cleo}
{661}{}{Conductor de Caravana}
{662}{}{Dan}
{663}{}{Mujer de Dan}
{664}{}{Habitante del Eje}
{665}{}{Guardia de Decker}
{666}{}{Demetre}
{667}{}{Ayudante Fry}
{668}{}{Albóndiga}
{669}{}{Puerta muy Segura}
{670}{}{el suelo}
{671}{}{Granjero}
{672}{}{Guardia de los Comerciantes de Ultramar}
{673}{}{Oficial de Policía del Eje}
{674}{}{Mercader Comerciante de Ultramar}
{675}{}{Yonqui}
{676}{}{Guido}
{677}{}{Puerta Segura}
{678}{}{Guardaespaldas}
{679}{}{Guardia de los Niños de la Catedral}
{680}{}{Granjero}
{681}{}{Guardia del Eje}
{682}{}{Daren Hightower}
{683}{}{Guardia de Hightower}
{684}{}{Mujer de Hightower}
{685}{}{Habitante del Eje}
{686}{}{Mercader de Caravanas}
{687}{}{Oficial de Policía del Eje}
{688}{}{Hippie}
{689}{}{Jake}
{690}{}{Paciente de los Niños de la Catedral}
{691}{}{Smitty}
{692}{}{Jasmine}
{693}{}{Puesto de Trabajo}
{694}{}{Kane}
{695}{}{Keri}
{696}{}{Guardia de Lorenzo}
{697}{}{Lorenzo}
{698}{}{Maestro Mercader}
{699}{}{Richie}
{700}{}{Rufus}
{701}{}{Rutger}
{702}{}{Sid}
{703}{}{Thorndyke}
{704}{}{Troy}
{705}{}{Comerciante de los Mercaderes de Agua}
{706}{}{Guardia de los Mercaderes de Agua}
{707}{}{Computadora}
{708}{}{Centinela Supermutante}
{709}{}{Mercader de Caravanas}
{710}{}{Atención}
{711}{}{Alarma}
{712}{}{el suelo}
{713}{}{el suelo}
{714}{}{el suelo}
{715}{}{el suelo}
{716}{}{Taquilla}
{717}{}{Beth}
{718}{}{Guardia de la Hermandad}
{719}{}{Guardia de la Hermandad}
{720}{}{Entrenador de la Hermandad}
{721}{}{QA Tramposo}
{722}{}{Izo}
{723}{}{Katja}
{724}{}{Alcantarilla}
{725}{}{Escalera}
{726}{}{Escalera}
{727}{}{Alcantarilla}
{728}{}{una escalera}
{729}{}{Hueco de Escalera}
{730}{}{Puerta muy Segura}
{731}{}{Sr. Mañoso}
{732}{}{Estudiante de la Hermandad}
{733}{}{Thomas}
{734}{}{Modificar reacción}
{735}{}{Alcantarilla}
{736}{}{Escalera}
{737}{}{Alcantarilla}
{738}{}{Escalera}
{739}{}{Guardia de Gizmo}
{740}{}{Bandido de los Destripadores}
{741}{}{Disco de Transmisiones Supermutantes}
{742}{}{Garra Mortal}
{743}{}{Prole de Garra Mortal}
{744}{}{Pescador}
{745}{}{Hijo del Pescador}
{746}{}{Extraña Cabina de Teléfonos}
{747}{}{Gran Huella}
{748}{}{Extraña Cabina de Teléfonos}
{749}{}{Brahmin}
{750}{}{Rebaño de Brahmines}
{751}{}{Campesino herido}
{752}{}{Guardia duro}
{753}{}{Animado Siempre}
{754}{}{Hueco de Escalera}
{755}{}{una escalera}
{756}{}{Expendedora de periódicos}
{757}{}{Vendedor de Coches Usados}
{758}{}{Desguace}
{759}{}{Brotherhood of Steel - Destroyed}
{760}{}{Cathedral - Destroyed}
{761}{}{Military Base - Destroyed}
{762}{}{Sarah}
{763}{}{Agatha}
{764}{}{Chuck}
{765}{}{Alan}
{766}{}{Brenden}
{767}{}{Patrick}
{768}{}{Ismarc}
{769}{}{}
{770}{}{Alex}
{771}{}{Gideon}
{772}{}{Jeremiah}
{773}{}{Guardia Supermutante}
{774}{}{Guardia Supermutante}
{775}{}{Dr. Lorri}
{776}{}{Moore}
{777}{}{Lucy}
{778}{}{Escalofrío}
{779}{}{Científica Loco}
{780}{}{Vincent}
{781}{}{Piezas de Granja}
{782}{}{Prisionero}
{783}{}{Prisionero}
{784}{}{Computadora}
{785}{}{Thomas}
{786}{}{Mascota del Maestro}
{787}{}{Computadora}
{788}{}{Rae}
{789}{}{Puerta muy Segura}
{790}{}{Ayudante del Doctor}
{791}{}{Tu compañero de habitación}
{792}{}{Iniciado de la Hermandad del Acero}
{793}{}{Coyote}
{794}{}{Centinela Supermutante}
{795}{}{Guardia Supermutante}
{796}{}{Sheriff Greene}
{797}{}{Camarero}
{798}{}{Mercader del Eje}
{799}{}{Lance}
{800}{}{Saqueador}
{801}{}{Mercader del Eje}
{802}{}{Explorador Paladín de la Hermandad}
{803}{}{Trent}
{804}{}{Croupier de Dados}
{805}{}{una máquina tragaperras}
{806}{}{Borracho}
{807}{}{Jugador}
{808}{}{Prostituta}
{809}{}{John}
{810}{}{Croupier}
{811}{}{Supermutante rezando}
{812}{}{Niño de la Catedral rezando}
{813}{}{Campesino}
{814}{}{Croupier de Ruleta}
{815}{}{Campesino de Ciudad Vertedero}
{816}{}{Instructor de la Hermandad}
{817}{}{Escriba de la Hermandad}
{818}{}{Caballero de La Hermandad}
{819}{}{Paladín de la Hermandad}
{820}{}{una máquina tragaperras}
{821}{}{una escalera}
{822}{}{Hueco de Escalera}
{823}{}{Escriba de la Hermandad}
{824}{}{Caballero de La Hermandad}
{825}{}{Terminal del Ordenador}
{826}{}{Terminal del Ordenador}
{827}{}{Terminal del Ordenador}
{828}{}{Terminal del Ordenador}
{829}{}{Terminal del Ordenador}
{830}{}{Terminal del Ordenador}
{831}{}{Terminal del Ordenador}
{832}{}{Terminal del Ordenador}
{833}{}{Terminal del Ordenador}
{834}{}{Taquilla}
{835}{}{}
{836}{}{Mesa de Trabajo}
{837}{}{Científica Loco}
{838}{}{Mujer Prisionera}
{839}{}{un fregadero}
{840}{}{Pasadizo de la Repugnancia}
{841}{}{Generador}
{842}{}{Computadora}
{843}{}{Maletín}
{844}{}{Holodisk}
{845}{}{Holodisk}
{846}{}{Holodisk}
{847}{}{Refrigerador}
{848}{}{una estantería}
{849}{}{Saqueador}
{850}{}{Saqueador}
{851}{}{Saqueador}
{852}{}{Mercader}
{853}{}{Mercader}
{854}{}{Mercader}
{855}{}{Guardia}
{856}{}{Guardia}
{857}{}{Guardia}
{858}{}{Paladín de la Hermandad}
{859}{}{Paladín de la Hermandad}
{860}{}{Paladín de la Hermandad}
{861}{}{Caravan Guard}
{862}{}{}
{863}{}{Merodeador}
{864}{}{Mercancías en venta}
{865}{}{Caravana viajando}
{866}{}{Cosas dichas normalmente}
{867}{}{Lugar Provisional}
{868}{}{Lugar Provisional}
{869}{}{Lugar Provisional}
{870}{}{Caballero Larry}
{871}{}{Escriba Vree}
{872}{}{Guardia Vree}
{873}{}{Guardia de Maxson}
{874}{}{Jeremiah}
{875}{}{Puerta}
{876}{}{Puerta Sólida}
{877}{}{Caravana viajando}
{878}{}{Mercader de Caravanas}
{879}{}{Mercader de los Comerciantes de Ultramar}
{880}{}{Mercader de las Caravanas Carmesíes}
{881}{}{Comerciante de los Mercaderes de Agua}
{882}{}{Mitch}
{883}{}{Tendero}
{884}{}{Mercancías en venta}
{885}{}{Luz Atenuada}
{886}{}{Cuerda}
{887}{}{Jake}
{888}{}{Guardia Necrófago}
{889}{}{Celda de la Cárcel de Ciudad Vertedero}
{890}{}{Centinela Necrófago}
{891}{}{Centinela Necrófago}
{892}{}{Resplandeciente}
{893}{}{Computadora}
{894}{}{Granjero}
{895}{}{Granjero}
{896}{}{Mercader de Caravanas}
{897}{}{Mercader de Caravanas}
{898}{}{Mercader de Caravanas}
{899}{}{Mercader de Caravanas}
{900}{}{Puerta}
{901}{}{Puerta}
{902}{}{una colchoneta}
{903}{}{Luke}
{904}{}{John}
{905}{}{Puerta}
{906}{}{Biblioteca}
{907}{}{Habitación Alquilada}
{908}{}{Puerta}
{909}{}{una mesa}
{910}{}{una estantería}
{911}{}{Técnico de los Niños de la Catedral}
{912}{}{Vicioso}
{913}{}{Caja de Almacenamiento de Raciones de Agua}
{914}{}{Computadora}
{915}{}{Puerta}
{916}{}{Julio}
{917}{}{Líder de la Caravana}
{918}{}{una estantería}
{919}{}{Paladín de Asalto}
{920}{}{Explorador de los Seguidores}
{921}{}{Mike}
{922}{}{Vance}
{923}{}{Enganchado a las drogas}
{924}{}{Residuos}
{925}{}{Residuos}
{926}{}{Residuos}
{927}{}{Residuos}
{928}{}{Terminal de Energía}
{929}{}{Huellas}
{930}{}{Guardia de los Mercaderes de Agua}
{931}{}{Robot Centinela}
{932}{}{Puerta Segura}
{933}{}{Mercader}
{934}{}{Guardia de la Caravana Carmesí}
{935}{}{Guardia Boxeador}
{936}{}{Taquilla}
{937}{}{Puerta Muy Sólida}
{938}{}{Mutante Estúpido}
{939}{}{un tablón de anuncios}
{940}{}{Maletín de los Pistoleros}
{941}{}{Gunther}
{942}{}{Slappy}
{943}{}{Tendero}
{944}{}{una mesa}
{945}{}{Kyle}
{946}{}{Lemmy}
{947}{}{Guardia}
{948}{}{Explorador Supermutante}
{949}{}{Hombre de Caravana de Comerciantes de Ultramar}
{950}{}{Patrullera Supermutante}
{951}{}{Caja Fuerte}
{952}{}{Refrigerador}
{953}{}{Puerta}
{954}{}{Patrullera Supermutante}
{955}{}{Fango tóxico}
{956}{}{Extraño Misterioso}
{957}{}{}
{958}{}{Puerta muy Segura}
{959}{}{Taquilla}
{960}{}{Taquilla de la Hermandad}
{961}{}{Holodisco de datos del Refugio}
{962}{}{Srta. Stapleton}
{963}{}{Luz de Alarma}
{964}{}{Conmutador de Palanca}
{965}{}{Caballero Paul}
{966}{}{León}
{967}{}{el suelo}
{968}{}{el suelo}
{969}{}{el suelo}
{970}{}{George}
{971}{}{Rick}
{972}{}{Caja Fuerte}
{973}{}{Puerta}
{974}{}{Puerta}
{975}{}{Emisor de Campo de Fuerza}
{976}{}{un campo de fuerza}
{977}{}{Nevera}
{978}{}{Puerta}
{979}{}{un campo de fuerza}
{980}{}{Emisor de Campo de Fuerza}
{981}{}{un campo de fuerza}
{982}{}{Emisor de Campo de Fuerza}
{983}{}{un campo de fuerza}
{984}{}{Emisor de Campo de Fuerza}
{985}{}{un campo de fuerza}
{986}{}{Emisor de Campo de Fuerza}
{987}{}{un campo de fuerza}
{988}{}{Emisor de Campo de Fuerza}
{989}{}{}
{990}{}{Lenore}
{991}{}{Bob}
{992}{}{Puerta}
{993}{}{un campo de fuerza}
{994}{}{Emisor de Campo de Fuerza}
{995}{}{un campo de fuerza}
{996}{}{Emisor de Campo de Fuerza}
{997}{}{Campo de Dolor}
{998}{}{un campo de fuerza}
{999}{}{Emisor de Campo de Fuerza}
{1000}{}{un campo de fuerza}
{1001}{}{Emisor de Campo de Fuerza}
{1002}{}{un campo de fuerza}
{1003}{}{Emisor de Campo de Fuerza}
{1004}{}{una puerta de ascensor}
{1005}{}{}
{1006}{}{Puerta de Seguridad}
{1007}{}{Guardia Regulador}
{1008}{}{Necrófago}
{1009}{}{Guardia del Teniente}
{1010}{}{Computadora}
{1011}{}{Muro}
{1012}{}{Mutante Invasor}
{1013}{}{Guardia Regulador}
{1014}{}{Ayudante Fry}
{1015}{}{Guardia Mutante}
{1016}{}{Soldado del Maestro}
{1017}{}{Dugan}
{1018}{}{MacRae}
{1019}{}{Guardia de la Caravana Carmesí}
{1020}{}{Guardia de la Caravana Carmesí}
{1021}{}{Madre Garra Mortal}
{1022}{}{Garra Mortal}
{1023}{}{Michael}
{1024}{}{Christine}
{1025}{}{Greg}
{1026}{}{Navaja}
{1027}{}{Huevo de Garra Mortal}
{1028}{}{}
{1029}{}{una caja}
{1030}{}{una caja}
{1031}{}{Emisor de Campo de Fuerza}
{1032}{}{Puerta}
{1033}{}{Taquilla}
{1034}{}{}
{1035}{}{Irwin}
{1036}{}{Armadura de Energía}
{1037}{}{Caja Fuerte}
{1038}{}{Saqueador}
{1039}{}{Mathia}
{1040}{}{el suelo}
{1041}{}{Brahmin}
{1042}{}{Anciano de la Hermandad}
{1043}{}{}
{1044}{}{Anciano de la Hermandad}
{1045}{}{Necrófago}
{1046}{}{Neverita}
{1047}{}{Decoder Disk}
{1048}{}{un campo de fuerza}
{1049}{}{un campo de fuerza}
{1050}{}{Kenny}
{1051}{}{Guardia de la Hermandad}
{1052}{}{Granja de Irwin}
{1053}{}{}
{1054}{}{Taquilla}
{1055}{}{Regulator Transmissions}
{1056}{}{Prisionero}
{1057}{}{Seguidores}
{1058}{}{Puerta}
{1059}{}{Emisor de Campo de Fuerza Dañado}
{1060}{}{}
{1061}{}{Objeto del Tramposo}
{1062}{}{Cliente de la Caravana}
{1063}{}{Boxeador}
{1064}{}{}
{1065}{}{}
{1066}{}{Brahmin}
{1067}{}{}
{1068}{}{}
{1069}{}{}
{1070}{}{Prostituta}
{1071}{}{}
{1072}{}{Campo de Fuerza Estropeado}
{1073}{}{Saqueador}
{1074}{}{Saqueador}
{1075}{}{Saqueador}
{1076}{}{Saqueador}
{1077}{}{Saqueador}
{1078}{}{Saqueador}
