{101}{}{I do not need your services right now. Perhaps later.}
{102}{}{Help! Save me!}
{103}{}{You must die for what you've done!}
{104}{}{Spare me! Please!}
{105}{}{Are they dead yet? Maybe there's more of them!}
{106}{}{Your arrival was timely, my friend. Allow me to present you with a small token of my gratitude.}
{107}{}{Your arrival was timely, my friend. Allow me to present you with a small token of my gratitude.}
