{100}{}{You see a member of the Blades.}
{101}{}{Hey.}
{102}{}{Hallo.}
{103}{}{Hab einen schönen Tag.}
{104}{}{Nice weather we are having today.}
{105}{}{I wonder if it will rain.}
{106}{}{Have you ever seen the rain glow?}
{107}{}{Gotta get back to work.}
{108}{}{We don't get many outsiders here.}
{109}{}{Muss gehen.}
{110}{}{Man sieht sich.}
{111}{}{Good day.}
{112}{}{Danke für die Hilfe.}
{113}{}{We won't forget you.}
{114}{}{Nice to have you on our side.}
{115}{}{Things are going to be better now.}
