{0}{}{GUARDAR PARTIDA}
{1}{}{CARGAR PARTIDA}
{2}{}{PREFERENCIAS}
{3}{}{ABANDONAR JUEGO}
{4}{}{HECHO}
{100}{}{PREFERENCIAS DE JUEGO}
{101}{}{DIFICULTAD DEL JUEGO}
{102}{}{DIFICULTAD DEL COMBATE}
{103}{}{NIVEL DE VIOLENCIA}
{104}{}{RESALTAR OBJETIVOS}
{105}{}{SIN USAR}
{106}{}{MENSAJES EN COMBATE}
{107}{}{INJURIAS EN COMBATE}
{108}{}{FILTRO DE LENGUAJE}
{109}{}{CORRER}
{110}{}{SUBTITULOS}
{111}{}{RESALTAR OBJETOS}
{112}{}{VELOCIDAD DE COMBATE}
{113}{}{FLOAT MESSAGES LIFESPAN}
{114}{}{VOLUMEN DE SONIDO GENERAL}
{115}{}{MUSIC AND MOVIE VOLUME}
{116}{}{VOLUMEN DE EFECTOS DE SONIDO}
{117}{}{VOLUMEN DE DIÁLOGOS}
{118}{}{BRIGHTNESS / CONTRAST}
{119}{}{SENSIBILIDAD DEL RATON}
{120}{}{POR DEFECTO}
{121}{}{CANCELAR}
{122}{}{Affect player speed?}
{123}{}{SIN USAR}
{201}{}{Sí}
{202}{}{No}
{203}{}{Facil}
{204}{}{Normal}
{205}{}{Dificil}
{206}{}{Debil}
{207}{}{Normal}
{208}{}{Duro}
{209}{}{Normal}
{210}{}{Rápida}
{211}{}{Detallado}
{212}{}{Breve}
{213}{}{Sólo al apuntar}
{214}{}{Nada}
{215}{}{Mínima}
{216}{}{Gore}
{217}{}{8 seconds}
{218}{}{Fast}
{219}{}{Siempre}
{220}{}{Mucho}
{221}{}{Bajo}
{222}{}{Alto}
{223}{}{Máximo}
{224}{}{Ancho}
{300}{}{UNPAUSE}
{301}{}{PAUSA}
{1000}{}{SIN USAR}
{1001}{}{SIN USAR}
