{100}{}{Tù ves Baka.}
{101}{}{Estás viendo a una mujer.}
{102}{}{Criptas no deberìan estar aquì, ¿deberìan los chicos? (los otros tontos sacuden sus cabezas) Creo que deberìas irte. }
{103}{}{Cometí un error al unirme a las criptas. Quiero estar de tu lado. }
{104}{}{Vine con un mensaje de Phrax. }
{105}{}{Eso haré, gracias.}
{106}{}{¿Entonces deberíamos usar el abrigo de un traidor? ¿Uno que entregaría el suyo? Ningún perro es tan bajo como tú.}
{107}{}{Siento como si tu abrigo se volviera a poner, pero tus palabras me influyen.}
{108}{}{¿Phrax no es lo suficientemente valiente como para pronunciar este mensaje con su propia voz? Él no es hombre, de eso lo sé. Y envía a este chico a decir sus palabras. Bueno, entonces, diles y listo.}
{109}{}{Muere.}
{110}{}{Dijo que abandones la ciudad y que no te matarán.}
{111}{}{Dijo que tengas un buen dìa. }
{112}{}{Jajaja! Me gusta un hombre con sentido del humor. Puedes vivir. Perdòn, solo bromeaba. }
{113}{}{No creo que entiendas completamente las ramificaciones de lo que acabas de decir. Espero que los aprendas antes de que tus huesos se sequen en el sol del desierto. Lamentablemente, no creo que tengas mucho tiempo.}
{114}{}{¿Qué tenemos aquí? Escuchamos que alguien nuevo estaba en la ciudad. Este debes ser tú; todos los demás se ven tan familiares. Por favor permítame presentarme. Soy Baka, Reina de los locos. }
{115}{}{¿Por què se llaman los Tontos?}
{116}{}{I hear there are disagreements between you and the Crypts.}
{117}{}{You look like a fool to me.}
{118}{}{After the War, only the Foolish remain. If I was brave enough, I would have taken my own life years ago. Instead, I pander to whatever gods of chance are left.}
{119}{}{Understandable. I sort of agree with it. Can I join?}
{120}{}{We could use another hand. Let me think about this. [She puts her hand to her chin, and parades around the room dramatically.]}
{121}{}{Be careful with the words you choose. Not all are as forgiving as I am. I play the part, or the part plays me, but there is always room for another corpse to liven the drama.}
{122}{}{I wasn't sure, was that a threat?}
{123}{}{I'll try and behave.}
{124}{}{It was, now it is among the last words you will ever hear.}
{125}{}{Good, see that you do.}
{126}{}{¿Qué quieres ahora?}
{127}{}{I want to join your gang.}
{128}{}{Why do you want the power generator?}
{129}{}{I don't know if I should trust you. Prove your worth.}
{130}{}{This chicken walks into a bar...}
{131}{}{I'm the best fighter around.}
{132}{}{You could use a good man around here.}
{133}{}{(Minutes pass as you finish your joke. With a nervous smile, you meet her eyes. She laughs.) I like you. You have proven you understand the Joke. You are now a Fool. Betray us and die.}
{134}{}{Eso ya lo veremos.}
{135}{}{Skippy? Your turn.}
{136}{}{There is only one thing that separates Scrapheap from the wasteland: the stench of brahmin dung. But without that dung, there would be no power generator.}
{137}{}{Why don't you control it?}
{138}{}{¡Gracias!}
{139}{}{Because the Crypts do! They outnumber us for the moment, but if you were to join with us, we could take them.}
{140}{}{Sure. I'll join.}
{141}{}{No, gracias.}
{142}{}{You are a Fool... just kidding. Did you think I would let you join that easily?}
{143}{}{Sí.}
{144}{}{Uh, no!}
{145}{}{Oh, okay. You're in. You are now a Fool. Betray us and die. Yadda-yadda-yadda.}
{146}{}{You lie!}
{147}{}{Well, how does it feel to be a Fool?}
{148}{}{I like it.}
{149}{}{Great! What do I do now?}
{150}{}{How can I get some of that cool armor?}
{151}{}{You'd better. Not many can delve the humorous depths of full Fooldom.}
{152}{}{Uh, yes. Thanks. Uh, what next?}
{153}{}{Hmm, yes. Good question. Well, I suppose we should plan our attack on the Crypts. We have to gain control of that power generator, or all is lost.}
{154}{}{¿Qué quieres que haga?}
{155}{}{Well, since you are the newest member of the Fools, and therefore the most expendable, I want you to scout the enemy and report.}
{156}{}{Vale.}
{157}{}{Well, should we attack?}
{158}{}{¡Sí!}
{159}{}{¡No!}
{160}{}{Then why do you bother me? Do your job and report back as soon as possible!}
{161}{}{Excellent! Fools! We go to battle!}
{162}{}{You are a Fool on double-secret probation. You don't get Fool armor until you pass probation.}
{163}{}{[Hecho]}
{164}{}{[Más]}
{165}{}{The Crypts shall be buried once more!}
{166}{}{Perish, scum!}
{167}{}{Who said you could come out of your graves? Return!}
{168}{}{Oh, nada.}
{169}{}{You lie! Get to work before I open a can of whup-ass on you!}
{170}{}{I don't think I'm ready.}
{171}{}{Oh, sí. Adiós.}
{172}{}{Gods of fortune, gods of fate. I care not as long as I get the last laugh. We can't join death so we laugh at it.}
{173}{}{You shall be as if a Fool, but listen well and mark these words of mine: if you betray us as you would your former mates, then you shall die - with a grimace, not a laugh.}
{174}{}{And no, you shall not wear the mantle of a Fool. You will wear the mantle of a traitor, and my garrot will be it's mate.}
{175}{}{Yes, you can be the next jester in the Fool's court. Welcome to the Fools. Betray us and die.}
{176}{}{And without that power generator, there is no reason to be in this dunghole. The generator provides light, warmth and even some hair-raising experiences.}
{177}{}{Go gather some intelligence or something, and bring back news of the enemy. (She waves her hand in a dismissive gesture)}
{178}{}{Only the Foolish remain! Now I, Queen Baka, rule the Scrapheap.}
