{100}{}{Este es un escritorio desvencijado con un ordenador viejo y polvoriento colocado encima de él.}
{101}{}{¡Vuelves a colocar el chip perdido y la pantalla se enciende!}
{102}{}{Los daños parecen más físicos que eléctricos. Quizás se pueda arrancar con algo de trabajo.}
{103}{}{Este equipo parece no funcionar.}
{104}{}{Te tropiezas y te cortas las manos con la carcasa. ¡Aaay!}
{105}{}{Macro$oft (tm) Wyndoze 99 (c) iniciando...   Hecho.            U:\ > }
{106}{}{DIR}
{107}{}{EXIT}
{108}{}{FALLOUT    <DIR>          10-20-99   1:04p                          0 bytes en 1 archivo, 0 bytes asignados, 4.379.255 bytes libres}
{109}{}{CD FALLOUT}
{110}{}{Wow, this is a great game!}
{111}{}{ U:\ > }
{112}{}{Después de varios minutos buscando, encuentras un activador del Modo Debug y lo cambias a 01.}
{113}{}{FALLOUTW.EXE}
{114}{}{U:\Fallout\ > }
{115}{}{FALLOUTW.EXE     1384432   10-20-99   1:04p                      FALLDEMO.EXE     995328    04-22-97   2:13p                   2.379.760 bytes en 4 archivos, 2.436.874 bytes asignados}
{116}{}{[Continuar]}
{117}{}{> CARGANDO...  }
{118}{}{[Hecho]}
{119}{}{Ganas 100 puntos de experiencia por jugar a Fallout.}
{120}{}{    U:\Fallout\ > }
{121}{}{No me canso de este juego, el Fallout. Ya no los hacen como antes, durante la preguerra.}
{122}{}{Ummm... me pregunto que cambiará esta opción}
{123}{}{> Iniciar secuencia debug}
{124}{}{*clic* ............. Por favor espere ... ... ... ... ... ...                %s Hecho.}
{125}{}{Consigues 50 puntos de experiencia.}
{126}{}{FALLDEMO.EXE}
{128}{}{[Hecho]}
{129}{}{VOLCADO DE MEMORIA INICIADO >>> NO APAGUES O RESETEES ESTA TERMINAL
...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  }
{130}{}{No entiendo nada de esto. ¡No soy un genio de la informática!}
{131}{}{Ves: Escritorio.}
{132}{}{> POR FAVOR INTRODUCE DISPOSITIVO DE EXTRACCIÓN <}
{133}{}{Um... no tengo nada que se le parezca.}
{134}{}{[Compruebas si hay algo en las bahías externas]}
{135}{}{

¡Genial! Encuentras un disquete de 5" debajo del teclado. Está lleno de polvo pero parece funcionar.}
{136}{}{

No encuentras nada que se parezca a un disco o cartucho...}
{137}{}{[Continuar buscando]}
{138}{}{

Hay un viejo holodisco en la unidad de cartuchos que parece que funcionaría en tu Pip-Boy!}
{139}{}{[Instalar disco]}
{140}{}{rrrggg... en-doh?}
{141}{}{

Empujas el holodisco hasta el fondo de la ranura de cintas después de soplar en él, y comprobar que la cinta esté correctamente alineada dentro de las bobinas. Después de sacar el polvo del disquete de 5", lo insertas en la disquetera y le das a la palanca de bloqueo.}
{142}{}{> 12:50 [Presionas Volver]}
{143}{}{[Por unos momentos las luces parpadean en la disquetera mientras hace un zumbido agudo. Esto para y es seguido por un chirrío constante.]}
{144}{}{>>> NO APAGUES O RESETEES ESTA TERMINAL >>> :: SUFRIRÁS CORRUPCIÓN DE DATOS ::

VERIFICANDO DATOS: 0% ### ### ### 32% ### ### ### 59% ### ### ### 82% ### ### ### 99% ### ### ### ... hecho.
ESCRIBIENDO 512KB A LA MEMORIA BUFFER: 0% ### ### ### 28% ### ### ### 62% ### ### ### 77% ### ### ### 95% ### ### ### ... hecho.
VERIFICANDO MEMORIA: 0% ### ### ### 17% ### ### ### 50% ### ### ### 79% ### ### ### 97% ### ### ### ... hecho.}
{145}{}{:::TRANSFERECIA AL DISPOSITIVO EN PROGRESO:::
.
...
.....
Transfiriendo 6.759.015 bytes al dispositivo de respaldo................................
.......
.........
...........}
{146}{}{TRANSFERENCIA COMPLETADA. POR FAVOR QUITA EL DISPOSITIVO EXTERNO. QUE TENGAS UN BUEN DÍA.
[El sistema se apaga, se cortocircuita y queda en completo silencio]}
{147}{}{¡Gracias!}
{148}{}{Según parece el ordenador está tan estropeado que no se puede reparar.}
{149}{}{Muchos circuitos se han quemado por un incendio del EMP.}
{150}{}{No funciona.}
{151}{}{01100110011000010110110001101100011011110111010101110100011101110010111001100101011110000110010100100000001000000010000000100000001000000011000100110011001110000011010000110100001100110011001000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000110011001100001011011000110110001100100011001010110110101101111001011100110010101111000011001010010000000100000001000000010000000100000001110010011100100110101001100110011001000111000}
{152}{}{You earn 25 experience for playing Fallout (again).}
{153}{}{Interesante. ¡Estoy seguro de que la versión completa será un gran juego!}
{154}{}{Hmm. La versión completa de Fallout es mejor, sim embargo la demo tiene su encanto.}
{155}{}{Ganas 25 puntos de experiencia por jugar a la Demo Interactiva de Fallout.}
{156}{}{You earn 42 experience for playing Fallout Fixt.}
{157}{}{Congratulations, you have achieved all possible endings of the Fallout Interactive Demo!}
{158}{}{Felicidades, has conseguido todas las posibles terminaciones de la Precipitación: Un Post-Nuclear, Juego de Rol!}
{159}{}{Wow, esto es increíble! Incluso mejor que el juego original.}
{160}{}{Usted jugar a Fallout Fixt. Quien crea esto debe haber sido muy talentosos.}
{400}{}{Con el generador roto, hay pocas razones por las que las bandas luchen por el Desguace. La gente del Desguace llevará una vida más pobre; pero sin las bandas, al menos tendrán una vida. Tu trabajo aquí ha terminado, pero tu misión para encontrar el chip de purificación de agua continúa.}
{401}{}{Tras una larga y sangrienta batalla, prevaleces. Con las bandas derrotadas, el Desguace es ahora un lugar seguro. La gente del pueblo está agradecida; te dan algo de información valiosa, y tu misión en el Desguace ha terminado. Sin embargo, la misión para encontrar el chip de purificación de agua continúa.}
{500}{}{After stopping the Master and his lab with which he was creating his army of Super Mutants, you return home, only to discover that you are thrown out of your Vault for being too destructive. Thank you for playing Fallout.}
{501}{}{After convincing the Master to abandon his ill-conceived domination and destroying the Vats, you return home, only to find you are exiled, allegedly to prevent others from leaving the Vault. Thank you for playing Fallout.}
{502}{}{After destroying the Vats, the Master, and his army of Super Mutants, you return home, but are forbidden from entering. You retaliate, leaving the shattered corpse of the Overseer behind you. Thank you for playing Fallout.}
{503}{}{You are dipped in FEV and join the Master's Unity, revealing the location of Vault 13. You are rewarded with leading the assault against your Vault, killing the Overseer with your bare fists. Thank you for playing Fallout.}
