{100}{}{La guardia está furioso y empieza a atacar.}
{101}{}{El guardia se asusta con su poder.}
{102}{}{Sólo la Sombra de la Espada puede intimidar a este guardia, por su propia presencia. Debe hacerlo a través de las palabras.}
{103}{}{Correctamente pase algo de la guardia.}
{104}{}{Se han manchado.}
{105}{}{La guardia no tiene nada más en él.}
{106}{}{El guardia no se ve afectada.}
{107}{}{Un Junktown guardia de la puerta.}
{108}{}{¿Qué estás haciendo en Junktown, extraño?}
{109}{}{Buscando un poco de diversión.}
{110}{}{Me dan todo lo que tienen!}
{111}{}{Podría usted ayudarme en la adquisición de equipo?}
{112}{}{Nada. Gracias. Adiós.}
{113}{}{Hay un montón de cosas que hacer aquí. Vamos a ver. Usted puede practicar su objetivo en el brahmán, o puede simplemente pasear alrededor de Junktown y ver los lugares de interés, siempre y cuando no se inicie ningún problema.}
{114}{}{¿Hay algo más por aquí?}
{115}{}{Bien! Me dan todo lo que tienen!}
{116}{}{Gracias. Adiós.}
{117}{}{Bueno, supuestamente uno de los antiguos pobladores tenían un desagradable arma escondida en su casa, en el lado noroeste. Pero nadie tiene toda la encontró.}
{118}{}{Bien. Gracias por su tiempo.}
{119}{}{¿Había algo más?}
{120}{}{Bueno, bueno, bueno. Por favor, no me hagas daño.}
{121}{}{No pierdas la oportunidad! Morir escoria!!}
{122}{}{Bueno, supuestamente el hombre que vivía en el edificio hacia el noroeste, tuvo una muy desagradable arma de fuego. Tal vez usted lo puede encontrar.}
{123}{}{Lo siento, yo sólo soy un guardia. Trate de hablar con algunos de los otros residentes.}
{124}{}{Esto es solo una muestra de las cosas que usted puede hacer cuando el juego salga. Usted puede: matar todo lo que se interponga en su camino, inviolable y colarse a su manera a través de las situaciones, o puede hablar de su manera de salir de problemas y en las gracias de los demás.}
{125}{}{Cuando el juego salga, usted será capaz de ver más uso de sus habilidades de aquí.}
