{100}{}{Gracias.}
{101}{}{Adiós.}
{102}{}{Hola.}
{103}{}{Ganas }
{104}{}{ puntos de experiencia.}
{105}{}{¡Uh, oh!}
{106}{}{¡Clic!}
{107}{}{¡Uy!}
{108}{}{¡Ay!}
{109}{}{Nos vemos.}
{110}{}{Tómatelo con calma.}
{111}{}{Ha sido divertido.}
{112}{}{Aquí tienes.}
{113}{}{¿Algo más?}
{114}{}{Sí.}
{115}{}{No.}
{116}{}{Ganas }
{117}{}{ puntos de habilidad en Armas Pequeñas.}
{118}{}{ puntos de habilidad en Armas Grandes.}
{119}{}{ puntos de habilidad en Armas de Energía.}
{120}{}{ puntos de habilidad en Combate Desarmado.}
{121}{}{ puntos de habilidad en Armas de Melé.}
{122}{}{ puntos de habilidad en Armas Arrojadizas.}
{123}{}{ puntos de habilidad en Primeros Auxilios.}
{124}{}{ puntos de habilidad en Médico.}
{125}{}{ puntos de habilidad en Sigilo.}
{126}{}{ puntos de habilidad en Robar.}
{127}{}{ puntos de habilidad en Ganzúa.}
{128}{}{ puntos de habilidad en Trampas.}
{129}{}{ puntos de habilidad en Ciencia.}
{130}{}{ puntos de habilidad en Reparar.}
{131}{}{ puntos de habilidad en Conversación.}
{132}{}{ puntos de habilidad en Trueque.}
{133}{}{ puntos de habilidad en Jugar.}
{134}{}{ puntos de habilidad en Supervivencia.}
{135}{}{Ganas 1 punto de habilidad en Armas Pequeñas.}
{136}{}{Ganas 1 punto de habilidad en Armas Grandes.}
{137}{}{Ganas 1 punto de habilidad en Armas de Energía.}
{138}{}{Ganas 1 punto de habilidad en Combate Desarmado.}
{139}{}{Ganas 1 punto de habilidad en Armas de Melé.}
{140}{}{Ganas 1 punto de habilidad en Armas Arrojadizas.}
{141}{}{Ganas 1 punto de habilidad en Primeros Auxilios.}
{142}{}{Ganas 1 punto de habilidad en Médico.}
{143}{}{Ganas 1 punto de habilidad en Sigilo.}
{144}{}{Ganas 1 punto de habilidad en Robar.}
{145}{}{Ganas 1 punto de habilidad en Ganzúa.}
{146}{}{Ganas 1 punto de habilidad en Trampas.}
{147}{}{Ganas 1 punto de habilidad en Ciencia.}
{148}{}{Ganas 1 punto de habilidad en Reparar.}
{149}{}{Ganas 1 punto de habilidad en Conversación.}
{150}{}{Ganas 1 punto de habilidad en Trueque.}
{151}{}{Ganas 1 punto de habilidad en Jugar.}
{152}{}{Ganas 1 punto de habilidad en Supervivencia.}
{153}{}{Tu Fuerza ha incrementado en }
{154}{}{Tu Percepción ha incrementado en }
{155}{}{Tu Resistencia ha incrementado en }
{156}{}{Tu Carisma ha incrementado en}
{157}{}{Tu Inteligencia ha incrementado en }
{158}{}{Tu Agilidad ha incrementado en }
{159}{}{Tu Suerte ha incrementado en }
{160}{}{ points.}
{161}{}{Tu Fuerza ha aumentado 1 punto.}
{162}{}{Tu Percepción ha aumentado 1 punto.}
{163}{}{Tu Resistencia ha aumentado 1 punto.}
{164}{}{Tu Carisma ha aumentado 1 punto.}
{165}{}{Tu Inteligencia ha aumentado 1 punto.}
{166}{}{Tu Agilidad ha aumentado 1 punto.}
{167}{}{Tu Suerte ha aumentado 1 punto.}
{168}{}{Gracias por tu ayuda.}
{169}{}{Gracias por nada.}
{170}{}{Fallas al intentar ponerte una armadura humana; la armadura queda destruida.}
{171}{}{Creo que el Maestro desea hablar contigo.}
{172}{}{¡Pagarás por tu BLASFEMIA!}
{173}{}{Este robot parece estar fuera de servicio. Posiblemente se deba a la falta de energía.}
{174}{}{No ves nada especial en este robot.}
{175}{}{Este Navaja se niega a hablar contigo.}
{176}{}{La maleta está sellada y no puede abrirse.}
{177}{}{Por favor, debemos darnos prisa. No hay tiempo para hablar.}
{178}{}{Solo Morfeo tiene la llave de esta puerta. Debo irme ahora para hacerle saber a Nicole lo que ocurre aquí.}
{179}{}{Por favor, tengo que irme de aquí antes de que descubran quién soy.}
{180}{}{No puedes robar nada y piensas que quizás te han pillado.}
{181}{}{Los miembros de la Hermandad te han pillado robando.}
{182}{}{You see: Marauding Super Mutant.}
{183}{}{}
{184}{}{}
{185}{}{}
{186}{}{Escuchas el altavoz: "¡Atención! Se ha detectado a un intruso".}
{187}{}{La sustancia pegajosa ha interrumpido la transmisión de tu jugada maestra.}
{188}{}{Armadura de Metal.}
{189}{}{Armadura de Cuero.}
{190}{}{Hazte a un lado, por favor.}
{191}{}{Tycho es ahora de nivel }
{192}{}{Ian es ahora de nivel }
{193}{}{Katja es ahora de nivel }
{194}{}{Fren move! [You scowl and stamp your feet]}
{195}{}{Go, go, no need fren.}
{196}{}{We be fren?}
{197}{}{}
{198}{}{ He is wearing: }
{199}{}{ She is wearing: }
{200}{}{Estás viendo un emisor de campo muy dañado.}
{201}{}{El emisor está demasiado dañado para utilizarse.}
{202}{}{El emisor está demasiado dañado para repararse.}
{203}{}{Te das cuenta de que el campo está demasiado dañado para funcionar.}
{204}{}{Armadura de Energía.}
{205}{}{Armadura de Combate.}
{206}{}{Chupa de Cuero.}
{207}{}{Túnica.}
{208}{}{Armadura de Energía (R).}
{209}{}{Armadura de la Hermandad}
{210}{}{Armadura Tesla.}
{211}{}{No puedes robarle a esta criatura.}
{212}{}{Te miras durante un rato. ¿Te gusta lo que ves?}
{214}{}{El veneno ha abandonado tu sistema.}
{215}{}{Thanks, I'll make good use of that in combat!}
{216}{}{ Camina al estar cerca.}
{217}{}{ Corre siempre.}
{218}{}{Debes de tener mucho tiempo para estar viéndote de esta forma.}
{219}{}{El nivel de violencia es }
{220}{}{Ninguno.}
{221}{}{Mínimo.}
{222}{}{Normal.}
{223}{}{Máximo.}
{224}{}{ Nivel máximo recomendado para personajes con Masacre.}
{225}{}{Buen intento, pero eso no funcionará.}
{291}{}{Tycho has gained a level!}
{292}{}{Ian has gained a level!}
{293}{}{Katja has gained a level!}
{294}{}{Ahora eres de nivel }
{295}{}{.}
{296}{}{ (max).}
{300}{}{Vale.}
{301}{}{Ups, lo siento.}
{302}{}{Oh, perdona.}
{400}{}{La explosión debilita en gran medida este campo de energía. Ahora debería ser inofensivo pasar a través de él.}
{401}{}{CONTACTA CON SDUIBEK SI VES ESTE MENSAJE}
{402}{}{Variables del mod EndGame reseteadas. Por favor, intenta entrar de nuevo al Refugio 13.}
{403}{}{Has muerto. El Refugio está condenado.}
{404}{}{Tu título: }
{405}{}{Morador del Refugio.}
{406}{}{Vástago del Refugio.}
{407}{}{Veterano del Refugio.}
{408}{}{Élite del Refugio.}
{409}{}{Nómada.}
{410}{}{Nómada del Desierto.}
{411}{}{Nómada del Yermo.}
{412}{}{Élite Nómada.}
{413}{}{Viajero.}
{414}{}{Viajero del Desierto.}
{415}{}{Viajero del Yermo.}
{416}{}{Elite Strider.}
{417}{}{Héroe del Refugio.}
{418}{}{Héroe Errante.}
{419}{}{Héroe Viajero.}
{420}{}{Héroe del Desierto.}
{421}{}{Héroe del Yermo.}
{422}{}{Héroe de las Tierras Resplandecientes.}
{423}{}{Parangón.}
{424}{}{Leyenda Viva.}
{425}{}{Myth of the Wastes.}
{426}{}{Revenant Paragon.}
{427}{}{Striding Paragon.}
{428}{}{Paragon of the Wastes.}
{429}{}{Elite Paragon.}
{430}{}{Legendary Paragon.}
{431}{}{Supreme Paragon.}
{432}{}{Striding Commander.}
{433}{}{Pip-Boy displays: "FixtOS v}
{434}{}{0.9.0 }
{435}{}{active}
{436}{}{. Simulation began on FixtOS v}
{437}{}{. Upgraded from FixtOS v}
{438}{}{0.}
{439}{}{.}
{440}{}{alpha}
{441}{}{beta}
{442}{}{"}
{443}{}{. Simulation began on FixtOS v0.5.3 or older.}
{444}{}{}
{445}{}{}
{446}{}{}
{447}{}{}
{448}{}{}
{449}{}{}
{450}{}{}
{500}{}{La puerta se burla de ti al resistir, desafiante, la explosión, recibiendo solo algunas abolladuras.}
{501}{}{A la puerta le preocupa su habilidad para recibir más daño mientras cruje y se retuerce debido a la explosión.}
{502}{}{La puerta gime en agonía mientras sale volando de sus engranajes, cayendo al suelo y provocando un gran estruendo.}
{503}{}{Ganas }
{504}{}{ puntos de experiencia por utilizar explosivos con éxito.}
{505}{}{La explosión no termina de destruir la puerta. Necesitaras una más.}
{506}{}{Hmm, that doesn't seem to work.}
{533}{}{Commander of the Wastes.}
{534}{}{Elite Commander.}
{535}{}{Legendary Commander.}
{536}{}{Supreme Commander.}
{537}{}{Striding Exemplar.}
{538}{}{Exemplar of The Wastes.}
{539}{}{Elite Exemplar.}
{540}{}{Legendary Exemplar.}
{541}{}{Supreme Exemplar.}
{542}{}{Mythical Wanderer.}
{543}{}{Mythical Strider.}
{544}{}{Mythical Elite.}
{545}{}{Mythical Paragon.}
{546}{}{Mythical Commander.}
{547}{}{Mythical Exemplar.}
{548}{}{Mythical Hero.}
{549}{}{Supreme Jerk.}
{550}{}{You see: }
{551}{}{, the }
{552}{}{, the }
{553}{}{, a }
{554}{}{, a }
{601}{}{No deberías estar aquí, Iniciado.}
{602}{}{¿Qué estás haciendo aquí?}
{603}{}{Por favor, vete. No deberías estar aquí.}
{604}{}{Ey, no Iniciados.}
{605}{}{Lo siento, no puedo hablar con nadie. Ya sabes como es.}
{606}{}{Esta no es la biblioteca, chico. Si quieres investigar, por favor, ve a la biblioteca.}
{607}{}{Esta no es la biblioteca, chica. Si quieres investigar, por favor, ve a la biblioteca.}
{700}{}{¡Ganas 10000 puntos de experiencia!}
{701}{}{You earn 10000 experience for destroying the Vats!}
{702}{}{You earn 10000 experience for eliminating The Master!}
{800}{}{¿Por qué les hablas a las ratas?}
{900}{}{Pip-Boy displays: "VAULT WATER - }
{901}{}{}
{902}{}{ DÍAS."}
{903}{}{ DAY LEFT."}
{1000}{}{You place the ticking explosives at your feet.}
{1001}{}{Recibes una pequeña cantidad de radiación.}
{1002}{}{Recibes una moderada cantidad de radiación.}
{1003}{}{Recibes una gran cantidad de radiación.}
{1004}{}{Has sido levemente irradiado.}
{1005}{}{Has sido moderadamente irradiado.}
{1006}{}{Has sido fuertemente irradiado.}
{1007}{}{You've been irradiated!}
{1008}{}{Has recibido una leve cantidad de radiación.}
{1009}{}{Has recibido una pequeña cantidad de radiación.}
{1010}{}{Has recibido una moderada cantidad de radiación.}
{1011}{}{Has recibido una gran cantidad de radiación.}
{1153}{}{Your Strength was decreased by }
{1154}{}{Your Perception was decreased by }
{1155}{}{Your Endurance was decreased by }
{1156}{}{Your Charisma was decreased by }
{1157}{}{Your Intelligence was decreased by }
{1158}{}{Your Agility was decreased by }
{1159}{}{Your Luck was decreased by }
{1160}{}{ points.}
{1161}{}{ point.}
{1170}{}{Your attempt to wield a human weapon has failed; the weapon is destroyed.}
{1171}{}{Your large hands are too clumsy to wield the human weapon, and it falls to your feet.}
{1180}{}{You have killed a large number of innocent people. You're now a Berserker! This generally isn't a good thing to be known for, and you are clearly a very bad person.}
{1181}{}{You are no longer a Berserker.}
