{100}{}{Estás viendo a un borracho.}
{101}{}{Estás viendo a un cliente.}
{102}{}{Estás viendo a una sórdida mujer.}
{103}{}{Estás viendo a un hombre de aspecto extraño.}
{104}{}{Estás viendo a un jugador.}
{105}{}{Ves a una chica muy guapa. Parece ocupada.}
{106}{}{Estás viendo a una mujer.}
{107}{}{Estás viendo a un hombre.}
{108}{}{Estás viendo a un jugador muy triste.}
{109}{}{Estás viendo a un mercenario.}
{110}{}{Déjame ahogar lash penas.}
{111}{}{Sí, querishísimo amigo.}
{112}{}{Anda eresh... *hip*... ¿Dónde eshtoy?}
{113}{}{¿Quién eres?}
{114}{}{¿Te conozco?}
{115}{}{No me siento muy bien.}
{116}{}{Tengo la bebida en la sangre.}
{117}{}{¿Quiénes sois vosotros dos?}
{118}{}{¡Quédate donde estás, tío!}
{119}{}{¡Quédate donde estás, chica!}
{120}{}{¡Vete de aquí, escoria!}
{121}{}{Estás acabando con la elegancia de este lugar.}
{122}{}{Vete, ¡gafe!}
{123}{}{No me desconcentres.}
{124}{}{¡Voy a ganar esta partida!}
{125}{}{¿No sabes hacer esto?}
{126}{}{¿Has visto eso? ¡Es imposible!}
{127}{}{Creo que están bromeando.}
{128}{}{Ahora hay posibilidades.}
{129}{}{Gano seguro.}
{130}{}{¿Qué? ¿Cómo he podido perder?}
{131}{}{Esta mesa está gafada.}
{132}{}{Estoy ocupado.}
{133}{}{¿No ves que estoy intentando jugar?}
{134}{}{Apuesta o calla.}
{135}{}{Déjanos solos o llamaré a los guardias.}
{136}{}{Cuidado, soy amiga íntima del Ayudante Fry.}
{137}{}{¿Te importa?}
{138}{}{¡Odio a los mirones!}
{139}{}{No me gustan los grupos.}
{140}{}{Estoy demasiado cansada para otro.}
{141}{}{Estás soñando, tío. ¡Vete!}
{142}{}{¡Vete de aquí! }
{143}{}{¿Qué diablos crees que estás haciendo?}
{144}{}{¡Cuidado con tus modales!}
{145}{}{¡Llamaré a la policía!}
{146}{}{¡Ni lo sueñes!}
{147}{}{¡Vete!}
{148}{}{¡Lárgate!}
{149}{}{¿Qué es lo que miras?}
{150}{}{¿Formas parte de la orgía?}
{151}{}{¡Vete de nuestra habitación!}
{152}{}{¡Vete!}
{153}{}{¿Formas parte de la orgía?}
{154}{}{¡Vete, pervertido!}
{155}{}{¿Cuál es tu problema?}
{156}{}{Vete antes de que me enfade.}
{157}{}{Búscate a otra.}
{158}{}{Ésta es mía.}
{159}{}{¡Maldición!}
{160}{}{¿Estás de broma?}
{161}{}{Tendría que haber ganado yo.}
{162}{}{¡Por los pelos!}
{163}{}{He perdido por los pelos.}
{164}{}{¿Cuáles son las reglas?}
{165}{}{Antes era bueno en esto.}
{166}{}{Gracias por nada.}
{167}{}{¡No me lo creo!}
{168}{}{Quería perder, de verdad}
{169}{}{Hagan sus apuestas.}
{170}{}{Las manos quietas, por favor.}
{171}{}{¡Ganador!}
{172}{}{Lo siento, amigos, puede que la próxima.}
{173}{}{¡Otro ganador!}
{174}{}{¡Manos fuera!}
{175}{}{Su turno, por favor.}
{176}{}{Lo siento, es una apuesta inválida.}
{177}{}{Eso es.}
{178}{}{¿Alguien más?}
{200}{}{Ey, cariño, ¿buscas un buen rato?}
{201}{}{¿Qué's lo que buscas, cariño?}
{202}{}{¿Buscas compañía?}
{203}{}{Hola, monada.}
{204}{}{¿Te gusta lo que ves? A mí sí.}
{205}{}{Enséñame lo que tienes, cariño}
{206}{}{Me gusta duro, si es lo que te va.}
{207}{}{Sin enfermedades, ¡estoy limpia!}
{208}{}{Hago grupales, por un extra.}
{209}{}{Haré lo que sea por un buen precio...}
{210}{}{Nunca he estado con una chica antes...}
{211}{}{Soy tus sueños hechos realidad, preciosa.}
{212}{}{Si tienes las chapas, me apunto.}
{213}{}{¿Te gusta lo que ves? A mí sí.}
{214}{}{Hola, dulzura.}
{215}{}{Ey, cariño, ¿buscas un buen rato?}
{216}{}{Me gusta duro, si es lo que te va.}
{217}{}{Sin enfermedades, ¡estoy limpia!}
{218}{}{Hago grupales, por un extra.}
{219}{}{Haré lo que sea por un buen precio...}
{220}{}{¿Cuánto cuesta la diversión?}
{221}{}{Veinte chapas.}
{222}{}{Vamos al grano...}
{223}{}{No, gracias, no me interesa.}
{224}{}{Gracias por el buen rato. Hasta luego.}
{225}{}{¿Cuánto por algo de acción en grupo?}
{226}{}{Cien chapas.}
{227}{}{Vale. ¿Qués lo que buscas?}
{228}{}{De acuerdo, sígueme...}
{229}{}{Gracias, extraño. [se guarda las chapas y te lanza un beso]}
{230}{}{Lapdance.}
{231}{}{Estriptís.}
{232}{}{Señorita guapa. ¿Conmigo?}
{233}{}{Oh dios... cariño. Tengo que ganarme la vida pero hasta yo tengo estándares.}
{234}{}{Juega contigo misma mientras yo miro.}
{235}{}{¡YO QUERER!}
{236}{}{Lo de siempre.}
{237}{}{¡Cualquier cosa! Sorpréndeme...}
{238}{}{Hmph.}
{239}{}{Lo siento cariño. Si encuentras un nuevo cerebro, hazme una visita.}
{240}{}{Mmf. Val-e, yo ir.}
{241}{}{Depende de lo que busques cariño.}
{242}{}{De acuerdo, seguidme todos...}
{243}{}{¿Chapa?}
{244}{}{[suspiro] Sí, idiota. Chapas de botella. Págame 150 y te daré un buen rato. Eso será suficiente como para ahogar mi vergüenza en el Halcón y que me queden beneficios.}
{245}{}{No me importa, acabemos con esto.}
{246}{}{Sexo sin más.}
{247}{}{Para ti, }
{248}{}{¿Para ti, cariño? }
{249}{}{Vale, suena bien.}
{250}{}{Pensándolo mejor, déjalo.}
{251}{}{Como quieras, seguro que vuelves.}
{252}{}{No tengo tantas chapas.}
{253}{}{¿Entonces por qué coño estás hablando conmigo? ¡Lárgate!}
{254}{}{[Continuar]}
{255}{}{[Hecho]}
{256}{}{Gracias, cariño. ¡Vuelve pronto!}
{257}{}{Aquí ir.}
{258}{}{Yo no tener dineros...}
{259}{}{¡Hmph!}
{260}{}{No me creo que este haciendo esto...}
{261}{}{Lárgate de aquí, que voy a vomitar.}
{262}{}{Tengo que encontrar un nuevo trabajo.}
{263}{}{¿Tú de nuevo? Lárgate, no trabajo con retrasados que no pueden pagar.}
{264}{}{Urr...}
{265}{}{¿Buh?}
{300}{}{ chapas.}
{301}{}{Tras observarla por un momento, se te hace obvio que se trata de una prostituta con un cliente. Te hace señas para que te vayas, inmediatamente.}
{302}{}{Tras observarla por un momento, se te hace obvio que se trata de una prostituta. Al mirarte te brinda una sonrisa falsa.}
{400}{}{Bueno, eso fue interesante.}
{401}{}{¡Guau!}
{402}{}{Deberíamos volver al trabajo.}
{403}{}{Ugh, me siento sucio.}
{404}{}{Oh, wow...}
{405}{}{Bueno... supongo que podría hacer una excepción. Más vales que tengas un montonazo de chapas.}
