{100}{}{Ves: al Sheriff Justin Greene.}
{101}{}{Guau, éste es el asesino de los inocentes. He oído hablar de ti y tienes suerte, porque llevo una insignia que me impide volarte la cabeza. Te sugiero que te marches de nuestra ciudad... ahora mismo. Y mantente alejado de nuestros hijos.}
{102}{}{¡Hola, señor! Me llamo Justin Greene. Soy el Sheriff de esta bonita ciudad. ¿Hay algo que pueda hacer por ti ahora?}
{103}{}{¡Hola, señora! Me llamo Justin Greene. Soy el Sheriff de esta bonita ciudad. ¿Hay algo que pueda hacer por ti ahora?}
{104}{}{Sí, ¡desaparece!}
{105}{}{Decker intentó contratarme para matar a un mercader y a su mujer.}
{106}{}{Decker intentó contratarme para matar a una tal Jain.}
{107}{}{Nada, no importa.}
{108}{}{Lo siento, no puedo decirte nada. Me matarían.}
{109}{}{Gracias. Intentamos hacerlo bien. Es muy difícil en una ciudad de este tamaño, pero hacemos lo que podemos con los recursos disponibles. Es difícil cuando esos tipos tienen mejores armas de fuego que nosotros.}
{110}{}{Gracias otra vez.}
{111}{}{Es hora de irse, asesino de niños.}
{112}{}{No podemos aceptar. Pero si cambias de opinión, házmelo saber. Este lugar es muy peligroso y alguien tiene que velar por que las cosas funcionen bien.}
{113}{}{¡Excelente! Ya me había enterado de este plan por otras fuentes. Eres la confirmación final que necesitaba para tomar medidas contra él. Va a resultar difícil aunque utilizaré toda la ayuda que pueda conseguir. Puedo pagarte 1.300 chapas. 300 ahora y el resto cuando el trabajo esté acabado. ¿Qué opinas?}
{114}{}{Llegas demasiado tarde... ¡Demonios! Sabía que era culpable. Solo me hubiera gustado saberlo a tiempo para poder pararlo. De todos modos, eres el testigo final que necesitaba para actuar. Tendremos que "sacarlo de ahí". Va a resultar difícil y tendré que utilizar toda la ayuda que pueda conseguir. Puedo pagarte 1.300 chapas. 300 ahora y el resto cuando el trabajo esté acabado. ¿Qué opinas?}
{115}{}{Llegas demasiado tarde. ¿Cómo sé que no eres culpable? Seguro que Decker no te dejaría con vida si supieras de sus planes.}
{116}{}{Me juraron que ya está muerta... espera un momento. ¿Cómo puedo saber que no fue culpa tuya? Me parece raro que Decker deje la vida a alguien que sabe algo.}
{117}{}{Será un placer.}
{118}{}{Lo siento, lo quiero todo por adelantado.}
{119}{}{¡Ni hablar! Es tu problema y no el mío.}
{120}{}{De ninguna manera. Parece que se puede confiar en ti, pero, ¿cómo puedo estar seguro de que no nos vas a dejar tirados cuando la cosa se ponga chunga? Por eso, por lo menos uno de nosotros tiene que sobrevivir para poder pagarte. De este modo, se le añadirá "algo" de seguridad a la cosa.}
{121}{}{Vale.}
{122}{}{Hazlo tú solo, Sheriff.}
{123}{}{¡Fantástico! Aquí está la primera parte de tu paga. [El Sheriff te da 300 chapas]}
{124}{}{Estoy preparado.}
{125}{}{Vale, adiós.}
{126}{}{Lamento oír eso. Si cambias de opinión, por favor, házmelo saber, pero no puedo esperar mucho.}
{127}{}{Vale, lo haré. Espera a que coja algunos suministros.}
{128}{}{Estás mal de la cabeza.}
{129}{}{Adiós.}
{130}{}{¡Fantástico! Aquí está la primera parte de tu paga. [El Sheriff te da 300 chapas]}
{131}{}{¿Qué? ¿Pretendes que me dedique a matar a gente inocente? Tengo una deuda contraída con esta ciudad, que no espero que entiendas.}
{132}{}{Tienes razón. Ahora te toca a ti.}
{133}{}{¿Cómo te atreves a acusarme?}
{134}{}{Me da igual lo que pienses.}
{135}{}{Bien. Él no ha intentado nada.}
{136}{}{Estuvimos en el Halcón; estaba lleno.}
{137}{}{Lo siento. Decker ha estado jugando con nosotros enfrentándonos los unos a los otros. Ya no sé en quién confiar. Sin embargo creo que podría necesitar tu ayuda. Será difícil, pero te pagaré 1.300 chapas. 300 ahora y 1.000 cuando el trabajo esté acabado.}
{138}{}{¡Conozco a una rata de lejos! Tienes suerte de que no tenga pruebas, y te recomiendo abandonar la ciudad antes de que encuentre alguna.}
{139}{}{¡Qué raro! Es la primera vez que oigo que Decker ha salido de su despacho. Se estará volviendo valiente. ¡Ese maldito asesino... ¡argh! ¡Lo pescaré! Te diré lo que vamos a hacer: tú nos ayudas y yo te pagaré 1.300 chapas... 300 ahora y 1.000 cuando esté acabado. ¿Qué opinas?}
{140}{}{Esa es la mayor cantidad de mierda de brahmin que he oído nunca. Decker nunca sale de su oficina. Sabía que había algo chungo en ti. Tienes suerte de que no tengo pruebas, ¡y te sugiero que te marches de la ciudad antes de que las encuentre!}
{141}{}{Vale, vamos...}
{142}{}{Así que has vuelto para entregarte, ¿eh? Me impresionas.}
{143}{}{Sí, lo siento.}
{144}{}{¿Entregarme? No me hagas reír.}
{145}{}{¡Cogedlo!}
{146}{}{¡Cogedla!}
{147}{}{Vale, te meteré en tu celda.}
{148}{}{No muevas ni un dedo. No te vas a mover en una temporada.}
{149}{}{¡Fugitivo! ¡Cogedle!}
{150}{}{¡Fugitiva! ¡Cogedla!}
{151}{}{¿Preparado para sacar a Decker?}
{152}{}{Sí.}
{153}{}{No.}
{154}{}{Ag.}
{155}{}{No me puedo creer que Decker haya muerto por fin. Creía que nunca llegaría este día.}
{156}{}{¿Has cambiado de opinión? ¿Aún podemos utilizarte para deshacernos de esa enfermedad de la que hablamos?}
{157}{}{Iré.}
{158}{}{No, lo siento.}
{159}{}{¿Eh?}
{160}{}{Te estaremos vigilando.}
{161}{}{¡He de denunciar un delito!}
{162}{}{Tienes un buen trabajo.}
{163}{}{Venga, ya nos volveremos a ver.}
{164}{}{Vale.}
{165}{}{Hola de nuevo, señor. ¿En qué puedo ayudarte hoy?}
{166}{}{Hola de nuevo, señora. ¿En qué puedo ayudarte hoy?}
{167}{}{Hola, ¿en qué puedo ayudarte?}
{168}{}{¿Sí?}
{169}{}{Déjalo, ¿vale?}
{170}{}{¡Estás bromeando! Bueno... uh... te... ¿preguntó por ti personalmente?}
{171}{}{Sí, lo hizo.}
{172}{}{Tío, ¡aquella si que fue una batalla infernal! Lo hiciste muy bien. Ahora que Decker y Kane ya no están, el resto de los Clandestinos caerán pronto. Sin un líder, organizaciones como éstas no pueden durar. Nadie aquí es lo suficientemente listo como para tomar las riendas.}
{173}{}{Aquí está el resto de tu recompensa. Gracias otra vez por tu ayuda. Esta ciudad te debe gratitud. [El Sheriff te da 1.000 chapas]}
{174}{}{Puedes irte en cuanto estés preparado.}
{175}{}{Dime cuando estés listo. Te esperaremos, pero no tardes mucho.}
{180}{}{Iguana Bob es el uso de la carne de cadáveres humanos para su primera Opción Seleccionar los cortes.}
{181}{}{Estás bromeando! Estás seguro? Hmmm... déjame mirar en esto y voy a volver a usted.}
{182}{}{Vale.}
{183}{}{Así, su historia comprueba. Maldita sea. Bob siempre me pareció un poco "off", pero nunca iba a tener la sospecha de que él era la venta de carne humana para nosotros. Yo estaba teniendo uno o dos de esos para el almuerzo todos los días!}
{184}{}{Yo sé. Es una lástima, teniendo en cuenta lo deliciosos que son.}
{185}{}{¡¡¡¡El plato del día está hecho con personas!!!! ¡¡¡¡Está hecho con personas!!!}
{186}{}{A la derecha. Bueno, nosotros nos encargaremos de esto. Gracias por su informe.}
{187}{}{Genial, yo estoy feliz de saber que voy a recibir la debida justicia. Bye!}
{188}{}{Lo que, sin comisión de intermediario?}
{189}{}{Seguro, en cualquier momento.}
{190}{}{Maldito tonto, yo sabía que ibas a decir eso! Aquí, tome su recompensa y salir. [Greene manos a 250 caps]}
{191}{}{Da igual, adiós.}
{192}{}{Gracias. Tenga un buen día!}
