{100}{}{Ves a un Caballero.}
{101}{}{Hola, Iniciado. Soy Larry, ¿en qué puedo ayudarte?}
{102}{}{Vree me dijo que podrías enseñarme una pistola láser.}
{103}{}{Vree me dijo que me podrías darme una pistola láser.}
{104}{}{Ag.}
{105}{}{Eh, vale...}
{106}{}{Eh, sí. Esas cosas son fantásticas. Su alcance es... como tu vista. [Larry habla durante lo que te parecen horas pero de vez en cuando oyes cosas sobre el uso de armas de energía.]}
{107}{}{¿Eh? Pero ella sabe que aún no están listas... Oh, seguro que quería decir que te las mostrara. Sí, puedo enseñártelas. Observa que funciona gracias a células de energía que proceden de... [Larry habla durante lo que te parecen horas, pero de vez en cuando oyes cosas sobre el uso de armas de energía.]}
{108}{}{Seguro que sí. Creo que debes irte, extranjero.}
{109}{}{No me gustan los mentirosos. Vete.}
{200}{}{Eso no es cierto.}
{201}{}{Allá vamos.}
{202}{}{El mecanismo de encendido sigue atascado.}
{203}{}{Así está mucho mejor.}
{204}{}{Casi lo tienes.}
{205}{}{Esto va a llevar un tiempo.}
{206}{}{¡Ese es el problema!}
{207}{}{John, creo que he aislado el problema.}
{208}{}{¡Maldición!}
{209}{}{¡Mecachis!}
{210}{}{¡Es culpa mía!}
{211}{}{Estoy bien.}
{212}{}{Vale, eso duele.}
{213}{}{Lo he hecho a propósito.}
{214}{}{¿Por qué sigue pasando eso?}
{215}{}{¡Mis ojos!}
{216}{}{No eres un Caballero.}
{217}{}{Necesito hablar con un Caballero.}
{218}{}{No lo entiendo, continúa el cortocircuito en las células de energía.}
{219}{}{Deberías mantenerte lejos. Puede ser peligroso.}
{220}{}{Por favor, no me distraigas.}
{221}{}{Mira donde pisas.}
{222}{}{¿Perdiste?}
{223}{}{Lo siento, no puedo hablar ahora.}
{300}{}{Tu habilidad de Armas de Energía aumenta en un 5%.}
