{111}{}{¡Nos atacan!}
{112}{}{Sí, por favor.}
{113}{}{¡Ayúdanos!}
{114}{}{Oh no...}
{115}{}{No quiero hablar contigo.}
{116}{}{Ayúdame, por favor...}
{117}{}{Vete por favor.}
{118}{}{¿Eso es todo?}
{119}{}{¡Deja que vea tu dolor!}
{120}{}{Pasas }
{121}{}{Muchas gracias.}
{122}{}{Bienvenido, colega.}
{123}{}{Te puedes marchar sin problemas.}
{124}{}{Gracias por la charla.}
{125}{}{Tienes un verdadero problema de comportamiento.}
{126}{}{Gracias por nada.}
{127}{}{Gracias por tu ayuda.}
{128}{}{We're in your debt, friend. Please accept these }
{129}{}{ caps as a token of our appreciate for taking care of those raiders.}
{130}{}{Gracias por ayudarnos a defendernos de esos saqueadores borrachos. Por ayudarnos a ganar toma estas }
{131}{}{ chapas.}
{132}{}{¿Quién es su líder?}
{133}{}{ chapas que te entregamos por ayudarnos a defendernos de esa escoria.}
