{100}{}{Estás viendo un ordenador muy sofisticado de la Hermandad.}
{101}{}{No tienes acceso a este terminal.}
{102}{}{La clase dura seis horas. Estás agotado.}
{103}{}{Ya has asimilado todo lo que puedes.}
{200}{}{Estás viendo un ordenador. Ves que tiene algunas trozos de algo que podría ser carne humana.}
{201}{}{Toqueteas el ordenador un rato pero no puedes hackear su sistema de seguridad.}
{202}{}{You find an interesting data file on a secret base to the northwest, and download the coordinates into your Pip-Boy.}
{203}{}{Ganas }
{204}{}{ experience for hacking into the computer!}
{205}{}{You discover some new information about Mariposa Military Base which you didn't known yet.}
{206}{}{Ganas }
{207}{}{ experience for hacking into the computer!}
{208}{}{Ganas }
{209}{}{ experience for your detective work}
{210}{}{, but ultimately you don't find any new intel while searching this terminal.}
{211}{}{You've learned all you can from the system.}
{300}{}{Este ordenador funciona perfectamente.}
