{100}{}{Usas el ordenador de la puerta pero éste no acepta tu código de acceso.}
{101}{}{Utilizas el ordenador de la puerta. Un altavoz se pone en marcha.}
{102}{}{Perdona, pero no podemos dejarte volver ahora. Uh, problemas técnicos. Inténtalo más tarde.}
{103}{}{Estás viendo el ordenador de la puerta de entrada del Refugio 13.}
{104}{}{Te estamos agradecidos por habernos salvado pero ya no te podemos dejar entrar.}
{105}{}{Lo sentimos, pero no puedes volver. Te deseamos lo mejor.}
{106}{}{El Supervisor ha hablado, debes marcharte.}
{107}{}{Mira, muchos de nosotros estamos indignados con la decisión del Supervisor, pero debemos acatarla.}
{108}{}{Debes seguir tu vida en el mundo exterior. Buena suerte amigo.}
{109}{}{Eres un peligro para el futuro de este Refugio. Debes marcharte de inmediato.}
{110}{}{No eres bienvenido aquí. Márchate.}
{111}{}{No permitiremos a asesinos en el Refugio. ¡Lárgate!}
{112}{}{Tememos en lo que te has convertido y en lo que podrías hacernos... márchate.}
{113}{}{Después de lo que le hiciste al Supervisor, ¿pensabas que te dejaríamos volver?}
{114}{}{¡¿Cómo has podido traicionarnos de esta manera?!}
{115}{}{Lárgate, lunático.}
{116}{}{The computer explodes in a spectacular shower of sparks and wiring, short-circuiting the entire system.}
{117}{}{Estás viendo el ordenador destruido de la puerta de entrada al Refugio 13.}
{118}{}{Es un desastre absoluto y es imposible de reparar.}
{119}{}{ La puerta no se volverá a cerrar nunca más.}
{120}{}{ La puerta no se volverá a abrir nunca más.}
{121}{}{You bastard! What have you done?!}
{122}{}{You bitch! What have you done?!}
{123}{}{The damaged computer is unusable.}
{124}{}{With the door sealed and no replacement Water Chip, the inhabitants of Vault 13 will soon discover their Vault has become a tomb.}
{125}{}{> Command? }
{126}{}{Open the Vault 13 blast door.}
{127}{}{Close the Vault 13 blast door.}
{128}{}{Modificar los parámetros de configuración.}
{129}{}{Nada, no importa.}
{130}{}{Bienvenido a su SimTek 5000 interactivo de personalización! Vault-Tec está comprometido a proporcionar un agradable integración en el mundo exterior. Recuerde, una configuración incorrecta puede causar inestable anomalías! (Nulidad de la garantía después de 2077)}
{131}{}{El refugio 13 de la puerta de entrada de la computadora, no se puede acceder durante el combate.}
{132}{}{Yo entiendo. [Execute "SPOILERS.EXE"]}
{133}{}{Se abre!}
{134}{}{¿Se cierran.}
{135}{}{Changey?}
{136}{}{A-diós.}
{137}{}{Boosh. [Execute "SPOILERS.EXE"]}
{138}{}{Recalibrar el refugio 13 de niveles de agua los sistemas de monitoreo.}
{139}{}{Ver o modificar la simulación de la terminación de los parámetros.}
{140}{}{[Super Mutant Invasions]}
{141}{}{Clasificar situacional opciones de combate.}
{142}{}{Recalcular cruz-páramo encuentro de estadísticas.}
{143}{}{[Los Artículos, El Inventario, El Trueque]}
{144}{}{[Levelup stuff]}
{145}{}{[Social sexy veces]}
{146}{}{Hmm... en Realidad, vamos a volver.}
{147}{}{DO NOT WANT!}
{148}{}{Gracias, yo estoy listo. [Sistema de salida]}
{149}{}{This boring!  [Exit system]}
{150}{}{Bueno, estoy haciendo aquí. [Ir al menú principal]}
{151}{}{Reproducción de alimentación de los datos históricos.}
{152}{}{El cálculo de... Sistema de monitores indican que la Bóveda de 13 de reservas de agua actualmente están cayendo a un ritmo constante. Estimado de días que quedan hasta el total agotamiento: }
{153}{}{. Introduzca un nuevo valor para volver a calibrar el sistema. (El valor predeterminado de la base de datos de valor: 150)}
{154}{}{> ¿Comando?}
{155}{}{[30]}
{156}{}{[60]}
{157}{}{[90]}
{158}{}{[120]}
{159}{}{[150]}
{160}{}{[MÁS]}
{161}{}{[ATRÁS]}
{162}{}{[180]}
{163}{}{[210]}
{164}{}{[240]}
{165}{}{[270]}
{166}{}{[300]}
{167}{}{[330]}
{168}{}{[365]}
{169}{}{[730]}
{170}{}{Me like.  [Go to main menu]}
{171}{}{[125]}
{172}{}{[135]}
{173}{}{[140]}
{174}{}{[145]}
{175}{}{Alinear la calibración con el Supervisor de las estimaciones. [120 - 150]}
{176}{}{O-vidente nums! [120 - 150]}
{177}{}{[999]}
{178}{}{[64000]}
{179}{}{[130]}
{180}{}{La prioridad de la Bóveda de 13 waterchip de sustitución de las subrutinas.}
{181}{}{Cómo detener el mutante de las invasiones}
{182}{}{Reevaluar la prioridad relativa de la Bóveda de 13 de supervivencia de los vectores.}
{183}{}{[Endgame Condición: ¿se Puede jugar después de ser sumergido?]}
{184}{}{Si el Yermo ser tan bruto como parece, tal vez debería tomar un momento para reflexionar sobre cualquier personal de las neurosis que puede afectar mi supervivencia por ahí.}
{185}{}{Me es fuerte, muchos inteligente. Tal vez tiene locos. Quiero un gran desafío! [Opcional jugabilidad restricciones]}
{186}{}{Si todas las demás amenazas a la Bóveda son eliminados, en caso de emergencia de aguas residuales de la redistribución de protocolo puede negar la necesidad de un Chip de Agua. El protocolo es en la actualidad: }
{187}{}{. Alternar el estado del protocolo? (Estado predeterminado: enabled (Habilitado)}
{188}{}{MOVILIDAD}
{189}{}{HABILITADO}
{190}{}{Se ve bien; vamos a retroceder. [Ir al menú anterior]}
{191}{}{The Master.}
{192}{}{The Vats.}
{193}{}{Either the Master or the Vats.}
{194}{}{Both the Master and the Vats.}
{195}{}{Para detener las invasiones de los pueblos, en la actualidad usted necesita para eliminar: }
{196}{}{ Requisito de cambio para dejar de fumar? (Predeterminado requisito: El Maestro)}
{197}{}{La comprobación de... de forma predeterminada, esta simulación se terminará si los sensores indican Bóveda de 13 de Supervivencia se ha reducido a cero. Configuración actual: }
{198}{}{ State the desired status.}
{199}{}{No.}
{200}{}{Me hace! Donde otros? [Ir al menú anterior]}
{201}{}{Sí.}
{202}{}{k!}
{203}{}{[Restorations]}
{204}{}{[Skills]}
{205}{}{Los miembros del partido}
{206}{}{[Personalizado estilos de juego]}
{207}{}{[Misc]}
{208}{}{Gracias por confiar en Vault-Tec y SimTek 5000 con su personalización necesita! Por favor, el estado de un comando.}
{209}{}{La simulación termina cuando la Supervivencia llega a cero.}
{210}{}{La simulación puede continuar si la fuente era extranjero.}
{211}{}{La simulación puede continuar si la fuente era orgánico.}
{212}{}{Simulación continúa independientemente de la capacidad de Supervivencia de calificación.}
{213}{}{El jugador puede seguir jugando después de que/si se han convertido en un Super Mutante? Actual reseteando: }
{214}{}{ (Por Defecto: No.)}
{215}{}{[ESPECIAL]}
{216}{}{Adytum.}
{217}{}{Necrópolis.}
{218}{}{The Hub.}
{219}{}{Nah-nah.}
{220}{}{La Hermandad del Acero.}
{221}{}{Ciudad Vertedero.}
{222}{}{De Arenas Sombrías.}
{223}{}{Del Refugio 13.}
{224}{}{For which location would you like to change the invasion time?}
{225}{}{Usted está viendo el número de días hasta la invasión de }
{226}{}{ Current value: }
{227}{}{. Seleccionar el nuevo valor por debajo de modificar. (Valor predeterminado: }
{228}{}{)}
{229}{}{Instantánea (0 días)}
{230}{}{1/4 de forma predeterminada.}
{231}{}{1/2 de forma predeterminada.}
{232}{}{Default value.}
{233}{}{2x default.}
{234}{}{3x default.}
{235}{}{4x default.}
{236}{}{Movilidad. (esta ubicación no será invadido)}
{237}{}{Do weapons fall to the ground upon death?}
{238}{}{Qué jugador recibe dadiation por golpe de bichos?}
{239}{}{Detalles de Childkiller estado}
{240}{}{De luz ambiental y Bengalas}
{241}{}{}
{242}{}{}
{243}{}{}
{244}{}{}
{245}{}{}
{246}{}{}
{247}{}{Hardcore: No carga salva. Debe completar en 1 sesión.}
{248}{}{La codependencia Perdedor: Si un asalariado, hojas o muere, más de juego.}
{249}{}{Lone Wolf: Si los miembros del partido, más de juego}
{250}{}{Pacifista: Si reproductor de tierras de cualquier golpe en el combate, más de juego.}
{251}{}{Killswitch: Si el modo de combate es siempre activa, más de juego.}
{252}{}{Me Gusta Duro: difficulty_level de Duro solamente.}
{253}{}{Me Gusta a la intemperie: combat_difficulty de diamantes en Bruto sólo.}
{254}{}{Especificar si alguna de las siguientes características se aplican a usted, y los sensores se adaptará en consecuencia.}
{255}{}{Yo soy Especial: Si las estadísticas se ha criado, más de juego.}
{256}{}{ Este estilo de juego es en la actualidad: }
{257}{}{. Cambiar estado?}
{258}{}{Arma Caída Mod es en la actualidad: }
{259}{}{de los maleficios de cadáver. Su comando?}
{260}{}{, con armas de caer  }
{261}{}{ to }
{262}{}{Disable it.}
{263}{}{Permiten, con una distancia de caída de 0 hexes de cadáver.}
{264}{}{Permiten, con una distancia de caída de 0-1 hexes de cadáver.}
{265}{}{Permiten, con una distancia de caída de 0-2 de los maleficios de cadáver.}
{266}{}{Permiten, con una distancia de caída de 1 hex de cadáver.}
{267}{}{Permiten, con una distancia de caída de 1 a 2 hexágonos de cadáver.}
{268}{}{Permiten, con una distancia de caída de 2 hexes de cadáver.}
{269}{}{No hay criaturas iluminará el jugador, tras el aterrizaje de un ataque. Qué tipo usted desea alternar?}
{270}{}{Intel indicates: }
{271}{}{, }
{272}{}{tendrá una oportunidad para irradiar el jugador cuando aterrizaje hits, basado en el Combate de la Dificultad y del jugador de estadísticas. Qué tipo usted desea alternar?}
{273}{}{Irradiated Rats}
{274}{}{unos flotantes}
{275}{}{Centaurs}
{276}{}{Glowing Ghouls}
{277}{}{Non-glowing Ghouls}
{278}{}{Brillante, los Demonios y las Ratas Irradiadas, con un máximo de 1 rad por golpe (2077 manual de campo predeterminados)}
{279}{}{Sólo brillante, los demonios y las ratas irradiadas tendrá una oportunidad para irradiar el jugador cuando aterrizaje de visitas, con 1/6 de probabilidad de 1 rad por golpe. Qué tipo usted desea alternar?}
{280}{}{Número de veces que se puede actualizar Rifle de Plasma y el Poder de la Armadura?}
{281}{}{Artículos recibidos al inicio del juego}
{282}{}{Mrs Stapleton}
{283}{}{Killian}
{284}{}{Explosives ruin lockers}
{285}{}{Armadura}
{286}{}{Holodisks}
{287}{}{Intercambio de derribo/no-derribo en Mandarrias}
{288}{}{Específicas de la configuración de los comerciantes/comerciantes}
{289}{}{La Base militar de rojas campos de fuerza - que hacen daño?}
{290}{}{Mr Handy in Military Base}
{291}{}{Puede contratado Pnj de nivel a todos?}
{292}{}{¿Cuántos niveles de jugadores por NPC levelup?}
{293}{}{Es el aumento de nivel de seguimiento relativa o absoluta?}
{294}{}{Después de unirse a los jugadores de su equipo, puede Ian/Tycho/Katja los niveles de ganancia? (Actualmente se }
{295}{}{can.)}
{296}{}{no puede.)}
{297}{}{ Vainilla predeterminado: contrató a los NPCs no los niveles de ganancia.}
{298}{}{[1]}
{299}{}{[2]}
{300}{}{[3]}
{301}{}{[4]}
{302}{}{[5]}
{303}{}{[6]}
{304}{}{[7]}
{305}{}{[8]}
{306}{}{¿Cuántos niveles de jugadores se tarda para desencadenar un mercenario levelup?. (En la actualidad se lleva a }
{307}{}{ el nivel de los jugadores para un NPC para ganar un nivel.) NPC Mod por defecto: 4.}
{308}{}{ los niveles de jugadores para un NPC para ganar un nivel.) NPC Mod por defecto: 4.}
{309}{}{Cuando los asalariados unirse a su equipo, en caso de que inmediatamente levelup a ser lo que haría si había conseguido en el nivel 1? (Actualmente se }
{310}{}{hacer). NPC Mod por defecto: no.}
{311}{}{no.) NPC Mod por defecto: no.}
{312}{}{}
{313}{}{}
{314}{}{}
{315}{}{}
{316}{}{}
{317}{}{}
{318}{}{Número de Turbo Rifle de Plasma actualizaciones permitido?}
{319}{}{Número de Armadura de Poder actualizaciones permitido?}
{320}{}{El jugador será capaz de actualizar este muchos Rifles de Plasma: }
{321}{}{El jugador será capaz de actualizar esto, muchos de Alimentación de Armaduras: }
{322}{}{. Seleccione un nuevo valor si lo deseas. (Vainilla por defecto: 1)}
{323}{}{Para cambiar entre el estándar y no-knockback versión de maza de elementos, seleccione una opción a continuación.}
{324}{}{Quitar el derribo de todos los Super Trineos en el inventario del jugador.}
{325}{}{Quitar el derribo de todas las Mandarrias en el inventario del jugador.}
{326}{}{Agregar derribo a todos los Super Trineos en el inventario del jugador.}
{327}{}{Añadir escudo para todos los Mandarrias en el inventario del jugador.}
{328}{}{Processing... Done!  }
{329}{}{}
{330}{}{}
{331}{}{}
{332}{}{}
{333}{}{}
{334}{}{}
{335}{}{}
{336}{}{}
{337}{}{}
{338}{}{}
{339}{}{}
{340}{}{}
{341}{}{}
{342}{}{}
{343}{}{}
{344}{}{}
{345}{}{}
{346}{}{}
{347}{}{}
{348}{}{}
{349}{}{}
{350}{}{}
{351}{}{}
{352}{}{}
{353}{}{}
{354}{}{}
{355}{}{}
{356}{}{}
{357}{}{}
{358}{}{}
{359}{}{}
{360}{}{}
{361}{}{}
{362}{}{}
{363}{}{}
{364}{}{}
{365}{}{}
{366}{}{}
{367}{}{}
{368}{}{}
{369}{}{}
{370}{}{}
{371}{}{}
{372}{}{}
{373}{}{}
{374}{}{}
{375}{}{}
{376}{}{}
{377}{}{}
{378}{}{}
{379}{}{}
{380}{}{}
{381}{}{}
{382}{}{}
{383}{}{}
{384}{}{}
{385}{}{}
{386}{}{}
{387}{}{}
{388}{}{}
{389}{}{}
{390}{}{}
{391}{}{}
{392}{}{}
{393}{}{}
{394}{}{}
{395}{}{}
{396}{}{}
{397}{}{}
{398}{}{}
{399}{}{}
{400}{}{}
{401}{}{}
{402}{}{}
{403}{}{}
{404}{}{}
{405}{}{}
{1000}{}{You notice blinking lights on the door computer.}
{1001}{}{Hmm... I wonder why those are blinking?}
