{100}{}{Ускоренный метаболизм}
{101}{}{Здоровяк}
{102}{}{Миниатюрный}
{103}{}{Однорукий}
{104}{}{Точность}
{105}{}{Камикадзе}
{106}{}{Тяжелая рука}
{107}{}{Стрельба навскидку}
{108}{}{Кровавая баня}
{109}{}{Порченый}
{110}{}{Добрая душа}
{111}{}{Drug-Reliant}
{112}{}{Сопротивляемость урону}
{113}{}{Ночн. существо}
{114}{}{Тренированный}
{115}{}{Одаренный}
{200}{}{Your metabolic rate is twice that of your fellow vault-dwellers. Because your body heals faster, it has not developed a normal resistance to the elements.                  +2 Healing Rate, but Poison Resistance & Radiation Resistance start at 0%}
{201}{}{Пожертвовать скоростью ради мощности. Вы бьете редко, но уж если бьете, будьте уверены - это заметят! Общее число ваших очков действия уменьшено, но показатель силы увеличен.}
{202}{}{You are not quite as big as the other vault-dwellers, but that never slowed you down.                                               +1 Agility, but Carry Weight is lowered by 10 times your Strength.       (-10 lb at STR 1 up to -100 lb at STR 10)}
{203}{}{One of your hands is very dominant. You excel with 1-handed weapons.                  +20% Chance To Hit with all 1-handed weapons (including melee and unarmed), but -40% Chance To Hit with all 2-handed weapons.}
{204}{}{Your attacks show a lot of finesse. You cause more critical hits, but you don't do as much damage.                            +10% Critical Chance, but your attacks deal 30% less damage.}
{205}{}{Вы действуете в бою гораздо быстрее. У вас нет добавок к классу брони за ловкость (играет роль только то, что надето на вас), но повышаются шансы опередить противника.}
{206}{}{Главное - хорошо размахнуться, а целиться - дело десятое. Ваши удары жестоки, но не всегда точны. Критический удар для вас редкость, но вы всегда наносите дополнительный урон.}
{207}{}{You attack faster than normal, so you don't have time to make targeted attacks.               All attacks (including melee and unarmed) cost 1 less Action Point, but you can't aim for specific body parts.}
{208}{}{Странная ирония судьбы: люди вокруг вас постоянно умирают жестокой смертью. Из всех способов умереть вы всегда выбираете для вашей жертвы самый кошмарный.}
{209}{}{Mayhem seems to follow you everywhere. Everyone around you has more critical failures in combat. The bad thing is, so do you!                All combat failures (misses) have a fairly high chance of being "upgraded" to a Critical Failure (critical miss).}
{210}{}{You spent more time than normal studying non-combative skills growing up.             +15% to First Aid, Doctor, Speech, and Barter, but -10% to Small Guns, Big Guns, Energy Weapons, Throwing, Melee Weapons, and Unarmed.}
{211}{}{You have enjoyed your trips to the vault medic a bit too much.                     You recover twice as fast as normal from the ill effects of drug addiction, but your chance to become addicted is also twice normal.}
{212}{}{You are resistant to all drugs and medications. This caused a lot of frustrations for the vault medic.                                               Your chance to become addicted to drugs is 50% of normal, but drugs only affect you half as long as normal.}
{213}{}{A night owl even as a child, you are more awake and alert when the sun goes down.                                                              +1 Intelligence and +1 Perception between 6:01 PM and 6:00 AM, but you have  -1 Intelligence and -1 Perception between 6:01 AM and 6:00 PM.}
{214}{}{You've spent more time honing your skills than most, because you were born with less potential than most.                    +10% to all skills and +5 Skill Points per level, but Perks only every 4th level. (Normal is every 3rd)}
{215}{}{Ваши природные данные великолепны, но вы мало тренируетесь. Все ваши характеристики выше на 1, но каждый навык на начало игры меньше на 10%, и вы получаете на 5 очков навыков меньше за уровень.}
