{100}{}{Вы видите Баку.}
{101}{}{Вы видите женщину.}
{102}{}{Crypts should not be here, should they boys? (The other Fools shake their heads) I think you should leave.}
{103}{}{I made a mistake joining the Crypts. I want to be on your side.}
{104}{}{У меня сообщение от Фракса.}
{105}{}{Конечно, спасибо.}
{106}{}{Then we should wear the coat of a betrayer? One who would deliver their own? No dog is as low as you.}
{107}{}{I feel as if your coat may turn again, but your words sway me.}
{108}{}{Phrax is not brave enough to speak this message with his own voice? He is no man, of that I know. And he sends this boy to say his words. Well, then, say them and be done.}
{109}{}{Die.}
{110}{}{He said to leave town and you won't be killed.}
{111}{}{Он пожелал хорошего дня.}
{112}{}{Hahaha! I like a man with a sense of humor. You can live. Sorry, just joking.}
{113}{}{I don't think you fully understand the ramifications of what you just said. I hope you learn them before your bones dry in the desert sun. Unfortunately, I don't think you have very long.}
{114}{}{What have we here? We heard that someone new was in town. This must be you; everyone else looks oh so familiar. Please allow me to introduce myself. I am Baka, Queen of the Fools.}
{115}{}{Почему вы называете себя Глупцами?}
{116}{}{I hear there are disagreements between you and the Crypts.}
{117}{}{Ну, как по мне, вы больше похожи именно на банду.}
{118}{}{After the War, only the Foolish remain. If I was brave enough, I would have taken my own life years ago. Instead, I pander to whatever gods of chance are left.}
{119}{}{Understandable. I sort of agree with it. Can I join?}
{120}{}{We could use another hand. Let me think about this. [She puts her hand to her chin, and parades around the room dramatically.]}
{121}{}{Be careful with the words you choose. Not all are as forgiving as I am. I play the part, or the part plays me, but there is always room for another corpse to liven the drama.}
{122}{}{Не понял, это угроза?}
{123}{}{Я попробую держать себя в руках.}
{124}{}{It was, now it is among the last words you will ever hear.}
{125}{}{Хорошо... "попробуй".}
{126}{}{Чего тебе надо?}
{127}{}{Я хочу вступить в вашу банду.}
{128}{}{Зачем вам генератор?}
{129}{}{Не знаю, могу ли я доверять тебе. Докажи, что ты достоин.}
{130}{}{This chicken walks into a bar...}
{131}{}{Я лучший боец в округе.}
{132}{}{Вам бы тут пригодился хороший человек.}
{133}{}{(Minutes pass as you finish your joke. With a nervous smile, you meet her eyes. She laughs.) I like you. You have proven you understand the Joke. You are now a Fool. Betray us and die.}
{134}{}{Ну, это мы еще посмотрим.}
{135}{}{Скиппи? Твой ход.}
{136}{}{There is only one thing that separates Scrapheap from the wasteland: the stench of brahmin dung. But without that dung, there would be no power generator.}
{137}{}{Почему вы им не управляете?}
{138}{}{Спасибо!}
{139}{}{Because the Crypts do! They outnumber us for the moment, but if you were to join with us, we could take them.}
{140}{}{Конечно. Я присоединюсь.}
{141}{}{Нет, спасибо.}
{142}{}{You are a Fool... just kidding. Did you think I would let you join that easily?}
{143}{}{Да.}
{144}{}{Ох, нет!}
{145}{}{Oh, okay. You're in. You are now a Fool. Betray us and die. Yadda-yadda-yadda.}
{146}{}{Ты врешь!}
{147}{}{Ну, как ты сейчас себя чувствуешь?}
{148}{}{Мне нравится.}
{149}{}{Отлично! И что мне делать?}
{150}{}{Где можно достать силовую броню?}
{151}{}{You'd better. Not many can delve the humorous depths of full Fooldom.}
{152}{}{Ну, э-э, и что?}
{153}{}{Hmm, yes. Good question. Well, I suppose we should plan our attack on the Crypts. We have to gain control of that power generator, or all is lost.}
{154}{}{И что мне делать?}
{155}{}{Well, since you are the newest member of the Fools, and therefore the most expendable, I want you to scout the enemy and report.}
{156}{}{Ладно.}
{157}{}{Что будем делать?}
{158}{}{Да!}
{159}{}{Нет!}
{160}{}{Then why do you bother me? Do your job and report back as soon as possible!}
{161}{}{Excellent! Fools! We go to battle!}
{162}{}{You are a Fool on double-secret probation. You don't get Fool armor until you pass probation.}
{163}{}{[Готово]}
{164}{}{[Дальше]}
{165}{}{The Crypts shall be buried once more!}
{166}{}{Умри, мразь!}
{167}{}{Who said you could come out of your graves? Return!}
{168}{}{Да ничего.}
{169}{}{You lie! Get to work before I open a can of whup-ass on you!}
{170}{}{Нет.}
{171}{}{Все понятно. Счастливо!}
{172}{}{Gods of fortune, gods of fate. I care not as long as I get the last laugh. We can't join death so we laugh at it.}
{173}{}{You shall be as if a Fool, but listen well and mark these words of mine: if you betray us as you would your former mates, then you shall die - with a grimace, not a laugh.}
{174}{}{And no, you shall not wear the mantle of a Fool. You will wear the mantle of a traitor, and my garrot will be it's mate.}
{175}{}{Yes, you can be the next jester in the Fool's court. Welcome to the Fools. Betray us and die.}
{176}{}{And without that power generator, there is no reason to be in this dunghole. The generator provides light, warmth and even some hair-raising experiences.}
{177}{}{Go gather some intelligence or something, and bring back news of the enemy. (She waves her hand in a dismissive gesture)}
{178}{}{Only the Foolish remain! Now I, Queen Baka, rule the Scrapheap.}
