{100}{}{Вы видите Зака Барстоу, послушника Чад Собора.}
{101}{}{Приветствую от имени Чад Собора. Чем я могу помочь тебе сегодня?}
{102}{}{Ур-рууу?}
{103}{}{В чем смысл вселенной?}
{104}{}{I'm hurt pretty bad. Think you can help me?}
{105}{}{Как починить помпу?}
{106}{}{Можешь мне что-нибудь рассказать про это место?}
{107}{}{I am ill-suited for that. Perhaps if you talk to Laura, she will be willing give you the information you need to know.}
{108}{}{Oh, fixing water pumps is easy. It's just a flag.}
{109}{}{I don't have the tools to assist you with that problem. Please talk to one of my superiors.}
{110}{}{А, это. Это просто флаг.}
{111}{}{Please consult with Laura. I have told you all I know.}
