{100}{}{Вы видите Майлза, послушника Чад Собора.}
{101}{}{Приветствую тебя, мой друг! Чем могу помочь тебе сегодня?}
{102}{}{Ар-ро?}
{103}{}{Каков текущий статус пациентов?}
{104}{}{I'm hurt pretty bad. Think you can help me?}
{105}{}{Тебе удалось починить насос?}
{106}{}{Расскажи мне про Лос-Анджелес?}
{107}{}{I am ill-suited for that. Perhaps if you talk to Laura, she will be willing give you the information you need to know.}
{108}{}{Oh, fixing water pumps is easy. It's just a flag.}
{109}{}{I don't have the tools to assist you with that problem. Please talk to one of my superiors.}
{110}{}{О, зайка, это просто отвратительно.}
{111}{}{Please consult with Laura. I have told you all I know.}
