{100}{}{Вы видите работника конторы Красный караван.}
{101}{}{You see a clerk from the Water Merchants.}
{102}{}{You see a clerk from the Far Go Traders.}
{103}{}{Hello. Are you looking for a job?}
{104}{}{Да.}
{105}{}{Нет.}
{106}{}{Great. We have space for another guard. Are you interested?}
{107}{}{Okay. If you need work, just stop by and we'll set you up.}
{108}{}{Sorry to hear that. Bye.}
{109}{}{Excellent. We have caravans leaving for L.A. Boneyard, Junktown, Necropolis and the Brotherhood of Steel. Which would you like to work on?}
{110}{}{Excellent. We have caravans leaving for L.A. Boneyard, Junktown and the Brotherhood of Steel. Which would you like to work on?}
{111}{}{Excellent. We have caravans leaving for L.A. Boneyard and Junktown. Which would you like to work on?}
{112}{}{Могильник Лос-Анджелеса}
{113}{}{Джанктаун.}
{114}{}{Братство Стали.}
{115}{}{Necropolis.}
{116}{}{Нет, я воздержусь.}
{117}{}{Great. We leave now.}
