{100}{}{Вы видите работника конторы Красный караван.}
{101}{}{You see a clerk from the Water Merchants.}
{102}{}{You see a clerk from the Far Go Traders.}
{103}{}{Привет. Ищешь работу?}
{104}{}{Да.}
{105}{}{Нет.}
{106}{}{Отлично. У нас есть место для еще одного охранника. Интересует?}
{107}{}{Хорошо. Если тебе нужна работа, то подходи, обеспечим.}
{108}{}{Печально слышать. Пока.}
{109}{}{Excellent. We have caravans leaving for L.A. Boneyard, Junktown, Necropolis and the Brotherhood of Steel. Which would you like to work on?}
{110}{}{Excellent. We have caravans leaving for L.A. Boneyard, Junktown and the Brotherhood of Steel. Which would you like to work on?}
{111}{}{Excellent. We have caravans leaving for L.A. Boneyard and Junktown. Which would you like to work on?}
{112}{}{Могильник Лос-Анджелеса}
{113}{}{Джанктаун.}
{114}{}{Братство Стали.}
{115}{}{Necropolis.}
{116}{}{Нет, я воздержусь.}
{117}{}{Great. We leave now.}
