{100}{}{Do you wish to enter the debug dialog? [If unsure, click No]}
{101}{}{Вы открыли замок.}
{102}{}{Okay. How much? [Numbers at beginning are number you can hit to choose that selection]}
{103}{}{1    One second  [10 ticks]}
{104}{}{2    One minute}
{105}{}{3    One hour}
{106}{}{4    One day}
{107}{}{5    One week}
{108}{}{6    One month [30 days]}
{109}{}{7    Six months}
{110}{}{Ничего.}
{111}{}{Включить питание в Свечении.}
{112}{}{Okay. How much? [Numbers at beginning are number you can hit to choose that selection]}
{113}{}{1    One second  [10 ticks]}
{114}{}{2    One minute}
{115}{}{3    One hour}
{116}{}{4    One day}
{117}{}{5    One week}
{118}{}{6    One month [30 days]}
{119}{}{7    Six months}
{120}{}{Ничего.}
{121}{}{7  Give me all the keys in the game.}
{122}{}{In a backpack or directly in your inventory?}
{123}{}{1    In a backpack.}
{124}{}{2    In my inventory.}
{125}{}{Ничего.}
{126}{}{8    13 years}
{127}{}{8    13 years}
{200}{}{Я могу вам помочь?}
{201}{}{Опыт}
{202}{}{2  Damage, Poison, Radiation.}
{203}{}{       Сопр. ядам:}
{204}{}{    Сопр. рад.:}
{205}{}{3  Delete ALL items from my inventory - Includes equipped!}
{206}{}{4  Toggle "BUG FIXES ONLY" global variable [gvar 0]}
{207}{}{8  Nothing. [close dialog]}
{208}{}{"Fixes Only" mode currently ENABLED. Disable?}
{209}{}{1    Yes, Disable it.}
{210}{}{2    No. [back]}
{211}{}{"Fixes Only" mode currently DISABLED. Enable?}
{212}{}{1    Yes, Enable.}
{213}{}{before: }
{214}{}{after: }
{215}{}{[Hands you a Burrito Supreme] Enjoy your Grade D Beef.}
{216}{}{Now you glow like a 50-rad light bulb.}
{217}{}{Договорились.}
{221}{}{[Grinning Visciously] I was happy to 'help' you.}
{222}{}{Я могу вам помочь?}
{223}{}{Сломана лев. нога}
{224}{}{Сломана пр. нога}
{225}{}{Сломана лев. рука}
{226}{}{Сломана пр. рука}
{227}{}{5    Blind Me }
{228}{}{Не трогай меня.}
{229}{}{TEST ROLLS mmm, rolls}
{230}{}{Договорились.}
{231}{}{Давай посмотрим тут.}
{232}{}{1    500}
{233}{}{    человеческую.}
{234}{}{    человеческую.}
{235}{}{4    10 thousand}
{236}{}{5    50 thousand}
{237}{}{6    210 thousand}
{238}{}{7    negative 5 thousand}
{239}{}{Ничего.}
{240}{}{У тебя есть }
{241}{}{How many Exp points do you want? [Numbers at beginning are number you can hit to choose that selection]}
{242}{}{        Здоровье:}
{243}{}{А зачем тебе это знать?}
{244}{}{1    One HP.}
{245}{}{2    Five HP.}
{246}{}{3    Ten HP.}
{247}{}{4    Twenty HP.}
{248}{}{5    Thirty HP.}
{249}{}{6    Forty HP.}
{250}{}{7    Fifty HP.}
{251}{}{9    999 HP. (kill me...)}
{252}{}{9  Teleport to another map...}
{253}{}{Убежище Некрополя}
{254}{}{Убежище 13 - вторжение}
{255}{}{Джанктаун - казино}
{256}{}{Братство}
{257}{}{Военная база}
{258}{}{Шейди Сэндс - колодец}
{259}{}{7    The Hub - Downtown}
{260}{}{Ничего.}
{261}{}{9    Master's Lair - 3/4}
{262}{}{Ладно, что ты предлагаешь?}
{263}{}{5  Modify game time (roll back or forward)}
{264}{}{6  Give me cheater debug items (lots)}
{265}{}{Да.}
{266}{}{Okay, roll back or roll forward?}
{267}{}{Ты в порядке?}
{268}{}{[назад]}
{269}{}{Убежище Некрополя}
{270}{}{Братство Стали.}
{271}{}{Пациент - Чада Собора}
{272}{}{Хаб}
{273}{}{5  Boneyard Adytum,  Raiders}
{274}{}{Дислокация: военная база Марипоза}
{275}{}{7  The Glow,  Desert}
{276}{}{Караваны}
{277}{}{Особая встреча}
{278}{}{Ничего.}
{279}{}{Ничего.}
{280}{}{Концовки}
{300}{}{DESERT1.MAP}
{301}{}{DESERT2.MAP}
{302}{}{DESERT3.MAP}
{303}{}{HALLDED.MAP}
{304}{}{Некрополь}
{305}{}{WATRSHD.MAP}
{306}{}{VAULT13.MAP}
{307}{}{VAULTENT.MAP}
{308}{}{VAULTBUR.MAP}
{309}{}{VAULTNEC.MAP}
{310}{}{JUNKENT.MAP}
{311}{}{JUNKCSNO.MAP}
{312}{}{JUNKKILL.MAP}
{313}{}{BROHDENT.MAP}
{314}{}{BROHD12.MAP}
{315}{}{BROHD34.MAP}
{316}{}{Радскорпионьи пещеры}
{317}{}{CHILDRN1.MAP}
{318}{}{CHILDRN2.MAP}
{319}{}{CITY1.MAP}
{320}{}{COAST1.MAP}
{321}{}{COAST2.MAP}
{322}{}{COLATRUK.MAP}
{323}{}{FSAUSER.MAP}
{324}{}{RAIDERS.MAP}
{325}{}{SHADYE.MAP}
{326}{}{SHADYW.MAP}
{327}{}{GLOWENT.MAP}
{328}{}{LAADYTUM.MAP}
{329}{}{LAFOLLWR.MAP}
{330}{}{MBENT.MAP}
{331}{}{MBSTRG12.MAP}
{332}{}{MBVATS12.MAP}
{333}{}{MSTRLR12.MAP}
{334}{}{MSTRLR34.MAP}
{335}{}{V13ENT.MAP}
{336}{}{HUBENT.MAP}
{337}{}{DETHCLAW.MAP}
{338}{}{HUBDWNTN.MAP}
{339}{}{HUBHEIGT.MAP}
{340}{}{HUBOLDTN.MAP}
{341}{}{HUBWATER.MAP}
{342}{}{GLOW1.MAP}
{343}{}{GLOW2.MAP}
{344}{}{LABLADES.MAP}
{345}{}{LARIPPER.MAP}
{346}{}{LAGUNRUN.MAP}
{347}{}{CHILDEAD.MAP}
{348}{}{MBDEAD.MAP}
{349}{}{MOUNTN1.MAP}
{350}{}{MOUNTN2.MAP}
{351}{}{FOOT.MAP}
{352}{}{TARDIS.MAP}
{353}{}{TALKCOW.MAP}
{354}{}{USEDCAR.MAP}
{355}{}{BRODEAD.MAP (not used in-game)}
{356}{}{DESCRVN1.MAP}
{357}{}{DESCRVN2.MAP}
{358}{}{MNTCRVN1.MAP}
{359}{}{MNTCRVN2.MAP}
{360}{}{VIPERS.MAP (not used in-game)}
{361}{}{DESCRVN3.MAP}
{362}{}{MNTCRVN3.MAP}
{363}{}{DESCRVN4.MAP}
{364}{}{MNTCRVN4.MAP}
{365}{}{HUBMIS1.MAP}
{366}{}{HUBMIS1.MAP}
