{100}{}{На старом столе стоит пыльный сломанный компьютер.}
{101}{}{You plug a loose chip back in and surprisingly the monitor lights up!}
{102}{}{The damage appears to be physical rather than electrical. It may still boot up with a little work.}
{103}{}{Это оборудование не работает.}
{104}{}{Вы порезались об острый край.}
{105}{}{Macro$oft (tm) Wyndoze 99 (c) booting up...   Done.
            U:\ > }
{106}{}{DIR}
{107}{}{ВЫХОД}
{108}{}{FALLOUT    <DIR>          10-20-99   1:04p
                          0 bytes in 0 files, 0 bytes allocated, 4,379,255 bytes free}
{109}{}{ФАЛЛАУТ}
{110}{}{Это алтарь.}
{111}{}{ U:\ > }
{112}{}{After several minutes of searching, you find a Debug Mode jumper setting and change it to 01.}
{113}{}{ФАЛЛАУТ}
{114}{}{U:\Fallout\ > }
{115}{}{FALLOUTW.EXE     1384432   10-20-99   1:04p
                      FALLDEMO.EXE     995328    04-22-97   2:13p
                   2,379,760 bytes in 2 files,  2,436,874 bytes allocated}
{116}{}{Сосуд}
{117}{}{> LOADING...  }
{118}{}{[Готово]}
{119}{}{Вы получаете 150 ед. опыта за убийство охранника.}
{120}{}{    U:\Fallout\ > }
{121}{}{I can't get enough of this Fallout game. They just don't make 'em like they used to in the pre-War days.}
{122}{}{Hmmm... I wonder what that setting changes?}
{123}{}{Начат цикл атаки}
{124}{}{*click* ............. Please stand by ... ... ... ... ... ... 
               %s  Done.}
{125}{}{> Begin memory dump protocol}
{126}{}{FALLDEMO.EXE}
{127}{}{Вы получаете 50 ед. опыта.}
{128}{}{[Готово]}
{129}{}{MEMORY DUMP INITIATED >>> DO NOT POWER OFF OR RESET THIS TERMINAL
...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  }
{130}{}{I don't understand any of this. I'm not a tech wizz!}
{131}{}{Вы видите Ромеро.}
{132}{}{> PLEASE INSERT EXTRACTION MEDIA <}
{133}{}{Ничего не удалось найти? Жаль.}
{134}{}{[Check if there's anything in the computer's external drives]}
{135}{}{

Success! You find a 5" floppy disk under the keyboard. It's very dusty but appears to be functional.}
{136}{}{

You don't find anything that looks like a disk or cartridge...}
{137}{}{[Continue to search]}
{138}{}{

There's an old holodisk in the tape catridge drive that looks like it would work in your Pip-Boy 2000!}
{139}{}{[Install the disks]}
{140}{}{rrrggg... In-doh?}
{141}{}{

You push the holodisk all the way into the tapedrive slot after blowing on it and checking that the tape is properly aligned inside the spools. After dusting off the 5" floppy disk, you insert it into the floppy drive slot and turn the locking lever.}
{142}{}{> 12:50 [Press Return]}
{143}{}{[For a few moments the lights blink on the floppy port and the tapedrive makes a high-pitched whirring. This stops, followed by a steady grinding sound from the floppy drive.]}
{144}{}{>>> DO NOT POWER OFF OR RESET THIS TERMINAL >>> :: DATA CORRUPTION WILL OCCUR ::

VERIFYING DATA: 0% ### ### ### 32% ### ### ### 59% ### ### ### 82% ### ### ### 99% ### ### ### ... Done.
WRITING 512KB TO MEMORY BUFFER: 0% ### ### ### 28% ### ### ### 62% ### ### ### 77% ### ### ### 95% ### ### ### ... Done.
VERIFYING MEMORY: 0% ### ### ### 17% ### ### ### 50% ### ### ### 79% ### ### ### 97% ### ### ### ... Done.}
{145}{}{:::MEDIA TRANSFER IN PROGRESS:::
.
...
.....
Transferring 6,759,015 bytes to tape backup drive................................
.......
.........
...........}
{146}{}{MEDIA TRANSFER COMPLETE. PLEASE REMOVE EXTERNAL MEDIA. HAVE A NICE DAY.
[The system powers down, short-circuits and goes completely silent]}
{147}{}{Спасибо!}
{148}{}{Судя по всему, компьютер сильно поврежден и не подлежит ремону.}
{149}{}{Часть схем выгорела под воздействием мощного электромагнитного импульса.}
{150}{}{Не работает.}
{151}{}{01100110011000010110110001101100011011110111010101110100011101110010111001100101011110000110010100100000001000000010000000100000001000000011000100110011001110000011010000110100001100110011001000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000110011001100001011011000110110001100100011001010110110101101111001011100110010101111000011001010010000000100000001000000010000000100000001110010011100100110101001100110011001000111000}
{152}{}{Вы получаете 35 ед. опыта за убийство собаки.}
{153}{}{Interesting. I bet the full version will be a great game!}
{154}{}{Hmm. The full version of Fallout is better, but this demo has a unique charm nonetheless.}
{155}{}{Вы получаете 25 очков опыта за взлом замка.}
{156}{}{}
{157}{}{}
{158}{}{}
{159}{}{}
{400}{}{With the generator broken, there is little reason for the gangs to fight over Scrapheap. The people of Scrapheap will lead a poorer life without their power; but with the gangs gone, at least they will have a life. Your job here is done, but your mission to find the water purification chip continues.}
{401}{}{After a long battle and much bloodshed, you prevail. With the gangs defeated, Scrapheap is a safe haven once again. The townspeople are grateful - They give you some valuable information, and your task in Scrapheap is now complete. However, the mission to find the water purification chip continues.}
{500}{}{После уничтожения Создателя и его Лаборатории, где он создавал армию супермутантов, вы возвращаетесь домой и узнаете, что вас вышвырнули из Убежища за то, что вы причинили слишком много разрушений. Спасибо, что играли в Fallout. }
{501}{}{После уничтожения Создателя и его Лаборатории, где он создавал армию супермутантов, вы возвращаетесь домой и узнаете, что вас вышвырнули из Убежища за то, что вы причинили слишком много разрушений. Спасибо, что играли в Fallout. }
{502}{}{После уничтожения Создателя и его Лаборатории, где он создавал армию супермутантов, вы возвращаетесь домой и узнаете, что вас вышвырнули из Убежища за то, что вы причинили слишком много разрушений. Спасибо, что играли в Fallout. }
{503}{}{503 You are dipped in FEV and join the Master's Unity, revealing the location of Vault 13. You are rewarded with leading the assault against your Vault, killing the Overseer with your bare fists. Thank you for playing Fallout.}
