{100}{}{Вы видите Люка.}
{101}{}{Вы видите дверь.}
{102}{}{[Дальше]}
{103}{}{[Готово]}
{104}{}{[Lex whispers.] Best be careful. Rock doesn't always tell the truth.}
{105}{}{С чего вдруг?}
{106}{}{Меня это не интересует.}
{107}{}{Rock is a member of the Crypts, a gang. He tries to get strangers, like yourself, into trouble. If you listen to him, you could find yourself dead and buried.}
{108}{}{Кто ты?}
{109}{}{Спасибо за информацию. Всего хорошего.}
{110}{}{I'm Lex. Scrapheap is my home, and I guess I speak for her people.}
{111}{}{Что еще мне надо знать?}
{112}{}{Well, there are also the Fools. They would control Scrapheap, if the Crypts were gone. The two gangs fight over who controls this place. Currently, the Crypts are on top. Now that you are here, things could change.}
{113}{}{С чего вдруг?}
{114}{}{If you could get rid of the gangs, we would be grateful. We don't have the numbers or the strength to drive them off, and few people care about this place. If you care, then we might be able to help you.}
{115}{}{Ты о чем?}
{116}{}{I've heard of you. You want to find the lost city of Necropolis. A grateful people could provide information on where to go.}
{117}{}{Я учту это.}
{118}{}{Огромное спасибо!}
{119}{}{Пока!}
{120}{}{Я лучше спрошу про другое.}
{121}{}{Why should you not? I have the best interests of my people at heart, and I would like to see you come to no harm.}
{122}{}{Ты о чем?}
{123}{}{There are forces at work here in Scrapheap that would like to use you, and if that is not possible, to see you dead and buried. Choose your friends wisely, and your enemies with even more care. Good day.}
{124}{}{Приятного дня.}
{125}{}{We thank you for getting rid of the Crypts and the Fools. Without the power generator, my people will have a poor life. Do you think you could fix it?}
{126}{}{Разумеется.}
{127}{}{Сам разбирайся с этим, раз ты такой крутой.}
{128}{}{Спасибо.}
{129}{}{Very well, you shall have it. You have cast my people into a cold night and then abandoned us to the wolves - but I understand that your quest is more important.}
{130}{}{The violence you have started may lead straight back to my people. Please finish it.}
{131}{}{Just like you cowards to lay the task of death on the shoulders of others.}
{132}{}{Я работаю над этим.}
{133}{}{If you need help, I will provide it, but don't ask my people. They are too tired of death and pain. I will join you, if that is what you wish.}
{134}{}{Yes, follow me, and attack when I do.}
{135}{}{Нет, просто заглянул.}
{136}{}{Just as I suspected, you don't care about anything except your own needs. Join our enemies, bring fear to my people, and betray your own background.}
{137}{}{Я тебя за это убью}
{138}{}{It's a plan. I'm infiltrating this gang.}
{139}{}{Заткнись.}
{140}{}{Я думал, что ты мой друг!}
{141}{}{Perhaps, but actions speak louder than words.}
{142}{}{Ты еще пожалеешь!}
{143}{}{Чем я могу тебе помочь?}
{144}{}{Расскажи про другие банды.}
{145}{}{Расскажи мне о Гильдии воров.}
{146}{}{Расскажи мне про банды.}
{147}{}{Расскажи мне про Сета.}
{148}{}{У меня все, спасибо.}
{149}{}{Scrapheap is our town. It was our home. And it will be again, hopefully.}
{150}{}{The power generator supplies all the electicity in town. Without it, we would surely die. It is the most important thing in town. Whoever controls it, controls Scrapheap.}
{151}{}{The Crypts are a gang run by Rayze. He's an animal and has one of the largest guns I've ever seen. He lets Lenny live, cuz he takes care of the brahmin, which provide fuel for the generator. The Crypts are in the big house.}
{152}{}{Baka leads the Fools. If she had any more men, she'd surely attack the Crypts and try to take back the power generator. You can tell the Crypts from the Fools by their armor. Fools wear metal, Crypts leather.}
