{100}{}{Вы видите Могильщика.}
{101}{}{Вы видите члена банды.}
{102}{}{Добро пожаловать в банду, чувак.}
{103}{}{Мы, Склепы, похороним этих Шутов.}
{104}{}{Я рад, что ты на нашей стороне.}
{105}{}{С твоей помощью мы можем перебить этих Шутов.}
{106}{}{Этот город теперь весь наш. }
{107}{}{Мне нравится твой стиль.}
{108}{}{Придется тебе найти что-нибудь кожаное, ты теперь один из Склепов.}
{109}{}{We don't want your kind around here, Fool.}
{110}{}{Get out, before we throw you out.}
{111}{}{If you start any trouble, the whole Crypt will come down on you.}
{112}{}{You made the wrong choice. Now you gonna be buried.}
{113}{}{Ты что здесь делаешь?}
{114}{}{Scrapheap belongs to us.}
{115}{}{In Scrapheap, if you ain't with us, you're either a loser or a Fool. What are you?}
{116}{}{You talking to me? Are you talking to me?}
{117}{}{This ain't no game, man. You either a Crypt or you gonna be buried.}
{118}{}{Only Crypts got the right to wear leathers.}
{119}{}{Run, Fools, while you still have a chance to live.}
{120}{}{Hey, Rayze, hunting season just opened, and Fools are on the list of dumb animals.}
{121}{}{Hey guys, leave a Fool for me to kill.}
