{100}{}{Уничтожьте банды, живущие на Свалке.}
{101}{}{Если вы не уничтожите всех бандитов, они будут искать расплаты. }
{102}{}{Склепы и Шуты сражаются за контроль над электрогенератором. }
{200}{}{Провести разведку для Шутов}
{201}{}{Вам нужно разведать для Шутов, что там у Склепов.}
{300}{}{Scout for the Crypts}
{301}{}{You need to go scout out the Fools for the Crypts.}
{400}{}{The Power Generator}
{401}{}{Without the generator, the peasants will lead a poorer life.}
{402}{}{The generator is the most important thing in Scrapheap. Whomever controls it controls Scrapheap.}
{403}{}{There are exposed wires which lead away from the generator.}
{500}{}{Проблема Фила с собакой.}
{501}{}{Phil has some problem with a dog.}
{502}{}{The dog looks hungry enough to eat Phil.}
