{100}{}{Какая-то странная дискета. Кажется, ее можно прочитать в вашем Pip-Boy 2000.}
{101}{}{Pip-Boy 2000: "Загрузка данных с диска... Отмена, данные уже присутствуют!"}
{102}{}{Pip-Boy 2000: "Загрузка данных с диска ... ... ... Готово. Хорошего дня!"}
{103}{}{Вы замечаете на диске полузатертую надпись "Журнал эксперимента Дельта".}
{104}{}{Вы видите диск эксперимента "Дельта".}
{105}{}{The Military has deemed it necessary for us to research further in-depth the effects of wave technology upon living organisms. We have taken light and sound as the basis of our studies. By manipulating the amplitude of the light waves and magnifying the frequency, we have been able to get lasers which will cut through a few feet of steel. Unfortunately, the power to do such a task has not been fully developed. We have other scientists looking into this.}
{106}{}{**НАЧАЛО ДИСКА**}
{107}{}{**END-DISK**}
{108}{}{[Дальше]}
