{100}{}{Вы видите Думара, чемпиона Чад Собора.}
{101}{}{Приветствую, путешественник. Мы слышали рассказы о том, который пересекает Пустошь. Как мы можем помочь тебе сегодня?}
{102}{}{Ы? Ар-ро?}
{103}{}{The Wasteland is a rough place. I have been injured pretty bad. Can you you help me out with that?}
{104}{}{Я хочу убить тебя и всех ваших приспешников!}
{105}{}{Расскажи мне о Шэйди Сэндс.}
{106}{}{Huh? Can't hear you. Can you speak up please?}
{107}{}{Who might I consult in order to become a member of this establishment?}
{108}{}{I wish to comprehend the wisdom upon which you and your fellow followers have based this establishment of beliefs.}
{109}{}{I'm sorry, but I am a bit too busy at the moment to relate the entire tale of the Children of the Cathedral. They are having me clean off the pews. Talk to Laura if you need information.}
{110}{}{I am sorry, but your words are far to above me to understand what you said. Perhaps our wiser followers, like Laura, might be able to help you better than I.}
{111}{}{I am truly sorry to hear about your ailment. Alas, I am merely an acrolyte and am unable to assist with your healing. Only the full members are granted training in the healing arts.}
{112}{}{Ah, child, it seems that you and I are speaking at different levels. Maybe if you talk to Laura, she can help you better than I can. Peace with you child.}
{113}{}{Поговори с Лаурой. Она может помочь тебе лучше меня.}
{114}{}{We are really a peaceful people. Please do not shed blood within this holy place.}
{115}{}{Once upon a time, there was a little traveller who walked around the world. He walked up to a young lady named Laura and asked her to tell him a story. The end.}
{116}{}{Dumar pleads with you to cease your vicious attacks.}
