{100}{}{You see a power generator. This must be what supplies electricity to the doors, elevators and lights in this complex.}
{101}{}{Генераторы включены.}
{102}{}{Генераторы выключены. Интересно, сможете ли вы включить их.}
{103}{}{Генераторы уже включены.}
{104}{}{Вы запускаете генераторы, и все системы включаются.}
{105}{}{Вам не удалось запустить генераторы.}
{106}{}{Ваших навыков недостаточно, чтобы отремонтировать эту систему.}
{107}{}{You hear a constant mechanical humming on this level, which reminds you of something that you can't quite put your finger on...}
