{100}{}{Вы видите здорового охотника за головами. На значке у него написано: 'Я - Кристофер, ты - мясо.'}
{101}{}{Чего ты хочешь?}
{102}{}{Пончик.}
{103}{}{Что ты здесь делаешь?}
{104}{}{Просто смотрю тут.}
{105}{}{Ничего.}
{106}{}{Мы тут умников не жалуем. Отвали.}
{107}{}{Шутка не смешная даже в первый раз. Ты сейчас узнаешь, почему меня считают самым ужасным охотником за головами в пустоши. И мне даже не надо будет платы за это.}
{108}{}{Не твое дело.}
{109}{}{Иди лучше в другом месте людей доставать.}
{110}{}{Ты знаешь, что за твою голову платят }
{111}{}{(He looks you over, carefully, considering something. It seems he's made a decision already.) Tell me, how often do you visit The Hub or Junktown?}
{112}{}{Часто. А что?}
{113}{}{Well, you see... business takes almost all of my time and I don't have an opportunity to get there. And as an incurable smoker I miss an old Zippo lighter very much. It's said, many of those pre-War items can be found in the shops there. If you get a Zippo for me, I'll share some information about the neighboring settlements. I think it could be of use!}
{114}{}{It's a pity. Looks like I made a mistake about you. Get out of here.}
{115}{}{Конечно, почему нет? Для тебя все, что угодно.}
{116}{}{Ладно.}
{117}{}{Hey, I have one right here. I don't really need it and can give it to you in exchange for the information.}
{118}{}{Thank you! (He takes the lighter.) So, what do you want to hear, exactly?}
{119}{}{Here is your lighter. Time to give me some information.}
{120}{}{Все ясно, спасибо.}
{121}{}{[Дальше]}
{122}{}{Что еще тебя интересует?}
{123}{}{Мне нужно узнать еще кое-что.}
{124}{}{Buuhhh.. Wuh?}
{125}{}{Серьезно? Долой с глаз моих.}
{126}{}{I'm going to do the world a favor by putting a bullet through your skull.}
{200}{}{ крышек? За убийство детей? Пришло время ее получить!}
