{100}{}{Ты думаешь, твоя жалкая кожа защитит тебя от Баки?}
{101}{}{Куда тебе против нас!}
{102}{}{Будь я столь же уродлив, я б себя прикончил.}
{103}{}{У вас, Склепов, нет никакого шанса.}
{104}{}{Нравится боль?}
{105}{}{О, мне это понравится. }
{106}{}{Ты умрешь, скотина!}
{107}{}{Время расплаты.}
{108}{}{Готов к боли?}
{109}{}{Глупее тебя только Райзе.}
{110}{}{I guess afterbirth can live a little while.}
{111}{}{Склепы будут похоронены снова!}
{112}{}{Сдохни, мразь!}
{113}{}{Кто сказал, что тебе можно вылезать из могилы? Возвращайся!}
{114}{}{Thy lowly ways shall be eradicated from the earth!}
{115}{}{Only Fools have true knowledge to rule Scrapheap.}
{116}{}{Begone gut slime of a three legged chicken!}
{117}{}{Что с тобой случилось? Мама головой уронила?}
{118}{}{}
{119}{}{}
{120}{}{}
{200}{}{Бегите, Шуты, пока у вас еще есть шанс выжить.}
{201}{}{Hey, Rayze, hunting season just openned, and Fools are on the list of dumb animals.}
{202}{}{Эй, пацаны, дайте и мне Шута убить. }
{203}{}{Склепы тебя похоронят!}
{204}{}{Шутам незачем жить.}
{205}{}{The Foolish shall perish.}
{206}{}{Look who got hit with the ugly stick.}
{207}{}{Тебя похоронят, Шут!}
{208}{}{I am going to kick some serious ass! I am ready to ruuummmblllle!}
{209}{}{Crypts rule! And Fools drool!}
{210}{}{Мы несем смерть!}
{211}{}{Не беспокойся, это будет быстро и больно!}
{212}{}{PURPLE BABOONS!}
{213}{}{Брамины умней Шутов.}
{214}{}{The Fools are so weak, even Lex can beat them all up.}
{215}{}{Haha! More fools to kill!!}
{216}{}{The only thing you Fools will rule is a tombstone.}
{217}{}{Наконец-то. Я заждался.}
{218}{}{Даже Ленни стреляет лучше.}
{219}{}{Жрите свинец, Шуты.}
{220}{}{Я твою голову на пику насажу.}
{300}{}{Hey! The generator is broken. Let's leave this dump.}
{400}{}{With the generator broken, there is little reason for the gangs to fight over Scrapheap. Your job here is done, but your mission to find the water purification chip continues.}
{402}{}{With the gangs defeated, Scrapheap is a safe haven once again.}
