{100}{}{You think that puny leather will save you from Baka?}
{101}{}{Ты не из этого дома.}
{102}{}{If I were that ugly, I'd kill myself.}
{103}{}{Жаль, но наличных денег у меня нет.}
{104}{}{???У тебя есть?}
{105}{}{О, мне это понравится. }
{106}{}{За это ты умрешь!}
{107}{}{Пора бы уже.}
{108}{}{Все, можем отправляться?}
{109}{}{Я знаю только одну очень быструю вещь - смерть.}
{110}{}{I guess afterbirth can live a little while.}
{111}{}{Склепы будут похоронены снова!}
{112}{}{Умри, мразь!}
{113}{}{Кто сказал, что тебе можно вылезать из могилы? Возвращайся!}
{114}{}{Thy lowly ways shall be eradicated from the earth!}
{115}{}{Only Fools have true knowledge to rule Scrapheap.}
{116}{}{Begone gut slime of a three legged chicken!}
{117}{}{Что с тобой случилось? Кто-то выстрелил тебе в голову?}
{118}{}{}
{119}{}{}
{120}{}{}
{200}{}{Run, Fools, while you still have a chance to live.}
{201}{}{Hey, Rayze, hunting season just openned, and Fools are on the list of dumb animals.}
{202}{}{Hey guys, leave a Fool for me to kill.}
{203}{}{Церковь до тебя доберется!}
{204}{}{Вам не отвечают.}
{205}{}{The Foolish shall perish.}
{206}{}{Look who got hit with the ugly stick.}
{207}{}{Готовься к смерти}
{208}{}{I am going to kick some serious ass! I am ready to ruuummmblllle!}
{209}{}{Crypts rule! And Fools drool!}
{210}{}{Мы мастера боя!}
{211}{}{Не беспокойся. Я с ними разберусь.}
{212}{}{PURPLE BABOONS!}
{213}{}{. Брамин дрожит от ярости}
{214}{}{The Fools are so weak, even Lex can beat them all up.}
{215}{}{Haha! More fools to kill!!}
{216}{}{The only thing you Fools will rule is a tombstone.}
{217}{}{Признаться никогда не поздно, тем более, что мне давно хотелось поточить свой клинок.}
{218}{}{Даже если я умру, я буду выглядеть лучше чем ты.}
{219}{}{Сожри свинца!}
{220}{}{Хочу сделать из тебя отбивную!}
{300}{}{Hey! The generator is broken. Let's leave this dump.}
{400}{}{With the generator broken, there is little reason for the gangs to fight over Scrapheap. Your job here is done, but your mission to find the water purification chip continues.}
{402}{}{With the gangs defeated, Scrapheap is a safe haven once again.}
