{100}{}{Вы видите Леона.}
{101}{}{Вы видите налетчика, который, похоже, сошел с ума.}
{102}{}{[дальше]}
{103}{}{[Готово]}
{104}{}{You hurt one of my friends! We'll make you pay for that! Get 'em, girls!}
{105}{}{Хмм, привет.}
{106}{}{Ты что здесь делаешь?}
{107}{}{Что за Караваны?}
{108}{}{How come these animals stink so much?}
{109}{}{They do? I hadn't noticed. I guess I've been hanging around them for so long, it doesn't bother me. They're my friends.}
{110}{}{These are Brahmin. They're my friends. I sleep in the pen with them so they don't get frightened at night. This place can get a little scary, if you know what I mean.}
{111}{}{Не знаю, что такое водяной чип. Извини.}
{112}{}{Можно, я его заберу?}
{113}{}{NO! No! I'm not a slaver, like some of these people. How could you sell your friends!?}
{114}{}{Пока нет.}
{115}{}{Осторожнее с ней. Смотри, какие зубы!}
{116}{}{Easy, I make more money that way.}
{117}{}{Oh, I understand. You don't realize how important Brahmin are to me. That's okay. I don't think people understand me.}
{118}{}{Угу, пока.}
{119}{}{Да? Чем могу помочь?}
{120}{}{Как скажешь.}
{121}{}{Oh. Oh, I get it. Hey, you're kinda nice. I like you. I should warn you about those Fool guys. They don't like me. They don't like anyone.}
{122}{}{Спасибо за рассказ.}
{123}{}{The bad people. They fight over things. Things I don't understand. The worst are the Fools. They pick on me. They don't like me. [sniff] I don't like them.}
{124}{}{Привет! Опять ты.}
{125}{}{Что ты знаешь о пропавших караванах?}
{126}{}{Что ты знаешь о пропавших караванах?}
{127}{}{Расскажи мне про Создателя.}
{128}{}{Увидимся.}
{129}{}{I don't like the Fools, they're always picking on me. They live in the garage to the north. They fight the Crypts, but we all lose.}
{130}{}{Спасибо.}
{131}{}{The Crypts are really mean. They hold the 'lectricity and if we are bad, they take it away from us. They hate the Fools, worse than any. Worse than they hate my friends.}
{132}{}{Что такое Единство?}
{133}{}{Не знаю.}
{134}{}{It feeds the lights. It makes all the stuff go. I don't know, but if we don't have it, it's not good.}
{135}{}{Я не буду с тобой говорить.}
{136}{}{I'm spending some time with my friends. I spend a lot of time with them. They're nice. They don't treat me bad. Not like some people. [Lenny squints his eyes.] I hate some people. I hate the Fools.}
{137}{}{А-а-а!}
{138}{}{Ты можешь начать с ответа на мой вопрос.}
{139}{}{Oh, sorry. Lex says I scare him, too. I don't mean it. And I never scare my friend.}
{140}{}{Ты что, боишься?}
{141}{}{Кто это?}
{142}{}{Oh, I watch the Brahmin and make sure nothing happens to them.}
{143}{}{Now, that wasn't so difficult, was it? What are your friends?}
{144}{}{Lex is nice. Lex treats my friends like family. About once a month, he even takes one of my friends home for dinner. [Lenny smiles.] Then he lets them play with a bunch of sky Brahmin. Isn't that nice?}
{145}{}{Yes, Lenny, it's very nice. Now tell me about your friends.}
{146}{}{Эй, я думаю, тебе пора уезжать отсюда. Мы не хотим тебя тут видеть.}
{147}{}{No, you lie! You are a liar! Lex would never do that! You stinking liar! I'm going to hurt you for saying that in front of my friends.}
