{100}{}{Вы видите Ленни.}
{101}{}{Вы видите неудачника, пахнущего словно брамин.}
{102}{}{[дальше]}
{103}{}{[Готово]}
{104}{}{You hurt one of my friends! We'll make you pay for that! Get 'em, girls!}
{105}{}{Хмм, привет.}
{106}{}{Что ты здесь делаешь?}
{107}{}{Что это за звери?}
{108}{}{How come these animals stink so much?}
{109}{}{They do? I hadn't noticed. I guess I've been hanging around them for so long, it doesn't bother me. They're my friends.}
{110}{}{These are Brahmin. They're my friends. I sleep in the pen with them so they don't get frightened at night. This place can get a little scary, if you know what I mean.}
{111}{}{Не знаю, о чем ты. Почему это место страшное?}
{112}{}{Можно купить один?}
{113}{}{NO! No! I'm not a slaver, like some of these people. How could you sell your friends!?}
{114}{}{Да нет, это просто звери.}
{115}{}{Я бы этого не делал на твоем месте, я просто пошутил.}
{116}{}{Easy, I make more money that way.}
{117}{}{Oh, I understand. You don't realize how important Brahmin are to me. That's okay. I don't think people understand me.}
{118}{}{Угу, пока.}
{119}{}{Злой ты. Ненавижу тебя.}
{120}{}{Как скажешь.}
{121}{}{Oh. Oh, I get it. Hey, you're kinda nice. I like you. I should warn you about those Fool guys. They don't like me. They don't like anyone.}
{122}{}{Спасибо за рассказ.}
{123}{}{The bad people. They fight over things. Things I don't understand. The worst are the Fools. They pick on me. They don't like me. [sniff] I don't like them.}
{124}{}{Привет! Опять ты.}
{125}{}{Расскажи, что ты знаешь о Шутах.}
{126}{}{Расскажи, что ты знаешь о Склепах.}
{127}{}{Расскажи мне про генератор.}
{128}{}{Увидимся.}
{129}{}{I don't like the Fools, they're always picking on me. They live in the garage to the north. They fight the Crypts, but we all lose.}
{130}{}{Спасибо.}
{131}{}{The Crypts are really mean. They hold the 'lectricity and if we are bad, they take it away from us. They hate the Fools, worse than any. Worse than they hate my friends.}
{132}{}{Что такое лектричество?}
{133}{}{Генратор? Не знаю такого.}
{134}{}{It feeds the lights. It makes all the stuff go. I don't know, but if we don't have it, it's not good.}
{135}{}{Я не буду с тобой говорить.}
{136}{}{I'm spending some time with my friends. I spend a lot of time with them. They're nice. They don't treat me bad. Not like some people. [Lenny squints his eyes.] I hate some people. I hate the Fools.}
{137}{}{Ты меня пугаешь.}
{138}{}{Хорошо, но ты мне не ответил.}
{139}{}{Oh, sorry. Lex says I scare him, too. I don't mean it. And I never scare my friend.}
{140}{}{Что у тебя за друзья?}
{141}{}{Кто такой Лекс?}
{142}{}{Oh, I watch the Brahmin and make sure nothing happens to them.}
{143}{}{Now, that wasn't so difficult, was it? What are your friends?}
{144}{}{Lex is nice. Lex treats my friends like family. About once a month, he even takes one of my friends home for dinner. [Lenny smiles.] Then he lets them play with a bunch of sky Brahmin. Isn't that nice?}
{145}{}{Yes, Lenny, it's very nice. Now tell me about your friends.}
{146}{}{Ленни, я думаю, тебе надо кое-то знать. Лекс ест твоих друзей.}
{147}{}{No, you lie! You are a liar! Lex would never do that! You stinking liar! I'm going to hurt you for saying that in front of my friends.}
