{100}{}{Вы видите Лекса, главаря банды Гадюк.}
{101}{}{Огромный парень с плохими манерами, взирает на вас.}
{102}{}{[...You steadily wake up and take a look around. You see an unfamiliar place, three tents and several people near them. Looks like you managed to regain consciousness before they could clean your pockets. Your eyes focus on the man standing next to you] Oh, our unfortunate buyer has awaken.}
{103}{}{[Дальше]}
{104}{}{Как это будет? Ты можешь дать нам все свои крышки, и мы отпустим тебя. Или мы можем играть в бесстрашных ковбоев.}
{105}{}{И какие гарантии, что я уйду отсюда живым, если вы получите деньги?}
{106}{}{Я всегда любил вестерны.}
{107}{}{Ковбой.}
{108}{}{Слово налетчика!}
{109}{}{Думаю, я могу тебе доверять. Вот, бери. [Вы даете ему свои сбережения]}
{110}{}{Эти слова ничего для меня не значат.}
{111}{}{So, a stubborn one? I rather like it. I think the guys will have some fun with you then.}
{112}{}{If you don't trust the words, you should trust our guns! A wimp like you is not a match for the whole gang!}
{113}{}{Then again, I'd rather kill you. To be sure that nobody'll chatter too much around. Farewell.}
{114}{}{Хороший парень. Это мудрое решение. Ты можешь свободно идти прямо сейчас.}
