{100}{}{В этом компьютере содержится огромный объем информации, сохранившейся со времен Великой Войны.}
{101}{}{Вы запускаете обучающую систему на компьютере убежища.}
{102}{}{Вы проводите некоторое время за обучающей системой, но не узнаете ничего важного. Внешний мир теперь ваш учитель.}
{103}{}{You spend 6 hours researching any topic that seems important. You feel you have gained vital knowledge that will help you in your travels outside the Vault.}
{104}{}{Вы проводите некоторое время, копаясь в интервеб, ни над чем не работая.}
{105}{}{Вы играетесь с компьютером немного, но понимаете, что нужны некоторые научные знания, чтобы добыть из терминала что-то полезное.}
{106}{}{Вы видите Синди.}
{107}{}{Вы проводите некоторое время за обучающей системой, но не узнаете ничего важного. Внешний мир теперь ваш учитель.}
{108}{}{ hours on the interwebs doing nothing of importance. It was fun but leaves you feeling empty inside.}
{109}{}{ hours on the interwebs searching for pornography and videos of cats.}
