{100}{}{Робот не работает. Слой пыли на нем позволяет предположить, что в последнее время им не пользовались.}
{101}{}{Робот отремонтирован, но все еще не работает.}
{102}{}{Проблема не в деталях. Должно быть, дело в его программе.}
{103}{}{У вас нет доступа к функциям робота, так как он отключен.}
{104}{}{Вы кое-как чините неработающие компоненты, но вам нужно больше времени, чтобы полностью отремонтировать их.}
{105}{}{Вы перезагружаете встроенный компьютер и успешно перезапускаете робота. Вы замечаете, что рация робота сломана.}
{106}{}{Вы проводите некоторое время, работая с компьютером робота, но не можете перезагрузить его.}
{107}{}{Робот #462 готов. Проверка. Определение данных о местонахождении. исправлено. Восстановление файла памяти. Исправлено. Ошибка - задача не выполнена.}
{108}{}{Рогга.}
{109}{}{Какая задача не выполнена?}
{110}{}{Что ж, выполни задачу и убирайся!}
{111}{}{[Щелчок] Отлично! Перезапуск задачи.}
{112}{}{Робот #462 предназначен для уборки. Должен закончить уборку и текущий ремонт данного уровня.}
{113}{}{Приступай!}
{114}{}{Что тебе осталось убрать?}
{115}{}{Цистерну в диспетчерской. [Щелчок] Конец списка.}
{116}{}{Хе. Заканчивай свое задание.}
{117}{}{Вы получили 1000 очков опыта за то, что сделали небольшую уборку.}
{118}{}{Это ничего не даст.}
{119}{}{This Mr. Handy robot is in moderate condition, but appears fully functional.}
{120}{}{You jury-rig the robot's radio system; it should be usable now.}
{121}{}{Вы открыли дверь.}
{122}{}{Охранник ничего тебе не отвечает.}
{123}{}{Дверь открыта.}
{124}{}{Hold off on that for a moment. What functions can you perform?}
{125}{}{Unit #462 assists with duties as specified by memory files and programming.}
{126}{}{Yeah, yeah, skip to the interesting parts.}
{127}{}{Пожалуйста, будьте точнее.}
{128}{}{[Click] Unit #462 can perform nuclear reactor fuel core replacements, hazardous materials cleanup, radiation cleansing, and basic mechanical repair procedures.}
{129}{}{Что еще интересного?}
{130}{}{[Beep!] Unit #462 is also equipped with self-maintenance routines, self-defense mechanisms, and a fully customizable operating system.}
{131}{}{Self-defense mechanisms?}
{132}{}{О'кей, спасибо.}
{133}{}{[Click] Unit #462 is authorized to commit deadly force in preservation of itself, as permitted by prior programming.}
{134}{}{Deadly force?}
{135}{}{(A speaker crackles to life, and a recorded message of a male voice begins playing. It sounds like an advertisement.) "RobCo is committed to your safety and well-being. All RobCo Mister Handy units are equipped with state-of-the-art safety overrides, to prevent any unfortunate incidents. Rest assured, Mr. Handy is the best and safety investment your family will ever make." (The speaker shuts off.)}
{136}{}{[Дальше]}
{137}{}{[Click] Processing... [Click] Memory file data indicates that as of Unit #462's manufacture date, out of 4,628 recorded self-defense events initiated by similar Units, only 930 have resulted in deaths of unarmed civilians.}
{138}{}{Не нравится мне все это.}
{139}{}{Hmm. I could use some help cleaning up this place, if you get my drift. Could you help me out?}
{140}{}{Can the self-defense system be reprogrammed into a combat system?}
{141}{}{I think Vault-Dwellers would be considered civilians, so I'll do my best to not piss you off.}
{142}{}{[Click] Checking... [Click] Unit #462's programming is not currently configured to allow such assistance. Ownership transfers and weapons system reallocations not permitted under current protocols.}
{143}{}{[Try to hack the unit and bypass the programming protocols]}
{144}{}{(It takes you a while, but you're finally able to crack the codes and get root access to the system.)}
{145}{}{Робот #462 готов. Проверка. Определение данных о местонахождении. исправлено. Восстановление файла памяти. Исправлено. Ошибка - задача не выполнена.}
{146}{}{Follow me and keep self-defense mechanisms active at all times. Oh, and don't shoot me, I'm not a threat. So you should probably add that to the self-defense protocols as well.}
{147}{}{[Щелчок] Отлично! Перезапуск задачи.}
{148}{}{(You try to get root access to the system but fail. Lights begin flashing on the unit. Uh-oh...}
{149}{}{Alert! Alert! Threat detected! [Click] Initiating self-defense protocols.}
{150}{}{Заключенный не обращает внимания на ваши попытки заговорить с ним.}
{151}{}{Unit #462, at your service.}
