{100}{}{Вы видите крестьянина.}
{101}{}{Thanks for getting rid of the gangs, but without the generator, we are going to have a worse life.}
{102}{}{Мне страшно.}
{103}{}{Хочу такую же.}
{104}{}{Э-э, спасибо. Наверное.}
{105}{}{If you don't kill all the gangs, they are going to take their revenge on us!}
{106}{}{You started this bloodbath, you finish it.}
{107}{}{Можно было бы и сказать тебе это, но придется тебя убить.}
{108}{}{Это алтарь.}
{109}{}{Ну, он еще ничего не сделал.}
{110}{}{Я думал, ты хороший человек. Ладно. Так тому и быть.}
{111}{}{Just another Crypt. I suppose you are going to hurt me now.}
{112}{}{Зачем тебе?}
{113}{}{Оставь меня в покое!}
{114}{}{Говорят, что вы тот }
{115}{}{It's a Fool! Oops, I didn't mean it that way.}
{116}{}{Эй, мне проблемы не нужны!}
{117}{}{Оставь меня в покое!}
{118}{}{Мне нужно поговорить с Создателем.}
{119}{}{Хочу есть.}
{120}{}{У меня самый широкий ассортимент.}
{121}{}{Is Phil still having trouble with that dog?}
{122}{}{Scrapheap is going to blow away into the desert wind, if those gangs have their way.}
{123}{}{Я буду говорить только с Создателем.}
{124}{}{Брамин наверняка воняет в это время года.}
{125}{}{Электрический заряд}
{126}{}{Привет.}
{127}{}{[Готово]}
