{100}{}{Вы видите крестьянина.}
{101}{}{Thanks for getting rid of the gangs, but without the generator, we are going to have a worse life.}
{102}{}{Мне холодно.}
{103}{}{Хочу света.}
{104}{}{Мы должны поблагодарить тебя. Наверное.}
{105}{}{If you don't kill all the gangs, they are going to take their revenge on us!}
{106}{}{You started this bloodbath, you finish it.}
{107}{}{Я бы помог, да колено подводит.}
{108}{}{Это твоя вина.}
{109}{}{Насилием ничего не остановить.}
{110}{}{Я думал, ты хороший человек.}
{111}{}{Just another Crypt. I suppose you are going to hurt me now.}
{112}{}{Я не причиню неприятностей.}
{113}{}{Прошу оставь меня в покое.}
{114}{}{Слышал, ты присоединился к Шутам.}
{115}{}{It's a Fool! Oops, I didn't mean it that way.}
{116}{}{Я не причиню неприятностей.}
{117}{}{Прошу оставь меня в покое.}
{118}{}{Обещаю смеяться над твоими шутками.}
{119}{}{Хочу есть.}
{120}{}{Куда делись все добрые люди?}
{121}{}{Is Phil still having trouble with that dog?}
{122}{}{Scrapheap is going to blow away into the desert wind, if those gangs have their way.}
{123}{}{По ночам холодно без обогревателей.}
{124}{}{Брамины сильно воняют летом.}
{125}{}{Электричество, электричество.}
{126}{}{Привет.}
{127}{}{[Готово]}
