{100}{}{Вы видите Могильщика.}
{101}{}{That fridge ain't your property. I would highly suggest not touching it.}
{102}{}{Почему?}
{103}{}{Ты хочешь меня убить!}
{104}{}{No, I'm gonna get my fellow Crypts and we're gonna make you feel pain.}
{105}{}{О как.}
{106}{}{It belongs to the Crypts. It ain't yours.}
{107}{}{Мне просто нужно было поговорить.}
{108}{}{Мда, ну ладно.}
{109}{}{There ain't no drinks in that fridge. Keep away from it.}
{110}{}{You should not be messing with things that ain't yours. And that definately ain't yours. Dumb move.}
{111}{}{You may be a Crypt, but this room is not for you. Don't mess with anything.}
{112}{}{Спускаясь по лестнице, вы падаете.}
{113}{}{Не создавай проблем.}
{114}{}{[ГОТОВО]}
{115}{}{[ЕЩЕ]}
{116}{}{Phil has more courage than any Fool!}
{117}{}{PUPLE BABBOONS!}
{118}{}{. Брамин дрожит от ярости}
{119}{}{The Fools are so weak, even Lex can beat them all up.}
