{100}{}{Вы видите Склепа Фракса.}
{101}{}{That fridge ain't your property. I would highly suggest not touching it.}
{102}{}{Почему?}
{103}{}{Хочешь меня заставить?}
{104}{}{No, I'm gonna get my fellow Crypts and we're gonna make you feel pain.}
{105}{}{О как.}
{106}{}{It belongs to the Crypts. It ain't yours.}
{107}{}{Мне просто охота выпить.}
{108}{}{Мда, ну ладно.}
{109}{}{There ain't no drinks in that fridge. Keep away from it.}
{110}{}{You should not be messing with things that ain't yours. And that definately ain't yours. Dumb move.}
{111}{}{You may be a Crypt, but this room is not for you. Don't mess with anything.}
{112}{}{Ты попал не в то место, не в то время.}
{113}{}{Эта комната не для тебя. Ничего не трогай, я за всем слежу.}
{114}{}{[ГОТОВО]}
{115}{}{[ЕЩЕ]}
{116}{}{Phil has more courage than any Fool!}
{117}{}{PUPLE BABBOONS!}
{118}{}{Брамины умней Шутов.}
{119}{}{Шуты настолько слабы, что даже Лекс может победить их всех.}
