{100}{}{Вы видите Рока.}
{101}{}{Вы видите мужчину.}
{102}{}{You might want to think about putting that gun away, son. The Crypts don't like it when people flash hardware that way.}
{103}{}{Да неужели. Я просто поговорю с ними об этом. Где они?}
{104}{}{А, ладно. Где тут можно выпить?}
{105}{}{Кто такие Склепы?}
{106}{}{Похоже, тебе бы не помешало выпить.}
{107}{}{[Готово]}
{108}{}{Да, отправляйся в большое здание внутри города и скажи, что тебя отправил Рок.}
{109}{}{Ладно.}
{110}{}{The Crypts? They are the biggest, baddest crew around. Don't mess with them, if you want to leave Scrapheap in one piece.}
{111}{}{Где они?}
{112}{}{They are in the big building just inside the gate. You looking for some steady work? Someplace to use that gun of yours?}
{113}{}{Нет.}
{114}{}{Да, конечно.}
{115}{}{Then I suggest you turn right back around and leave. Scrapheap is no place for those who ain't with the Crypts. If you want to go in, you can - but it's your life.}
{116}{}{Ладно.}
{117}{}{Отлично. Скажи им, что Рок отправил тебя в большой дом.}
{118}{}{Ладно.}
{119}{}{Приятно слышать, что ты на хорошей стороне в Свалке. Добро пожаловать в банду.}
{120}{}{Спасибо.}
{121}{}{Ты сделал ошибку. Страшную, ужасную ошибку.}
{122}{}{Добро пожаловать в Свалку, сынок. Не будь дураком, и все будет хорошо.}
{123}{}{Спасибо, что это за место?}
{124}{}{Кто тут главный?}
{125}{}{Scrapheap is the armpit of the desert. No better place to raise children, in my opinion. [Chuckles] This place makes Junktown look like a living city of the ancients.}
{126}{}{Спасибо.}
{127}{}{Well, there is a commune, run by Lex. But the real power is always behind the throne. In this case, the people not to mess around with are the Crypts.}
{128}{}{Спасибо.}
{129}{}{Ну, ты наверняка будешь задавать много вопросов. Я думаю, тебе просто нужно двигаться вперед.}
{130}{}{Ладно.}
{131}{}{[Готово]}
{132}{}{Склепы тебя похоронят!}
{133}{}{Шутам незачем жить.}
{134}{}{Шуты канут в лету.}
{135}{}{Посмотрите, кого побили этой уродской палкой.}
