{100}{}{Вы видите Снейка.}
{101}{}{Вы видите мужчину.}
{102}{}{Привет. Как жизнь?}
{103}{}{Вы видите Шута.}
{104}{}{Welcome to Scrapheap. Keep your hands to yourself.}
{105}{}{Хорошо.}
{106}{}{You be good, and Rock won't have to come down on you.}
{107}{}{Хорошо.}
{108}{}{[Готово]}
{109}{}{Член клана Клинков не хочет с вами разговаривать.}
{110}{}{Тебя похоронят, Шут!}
{111}{}{I am going to kick some serious ass! I am ready to ruuummmblllle!}
{112}{}{Crypts rule! And Fools drool!}
{113}{}{Мы несем смерть!}
