{100}{}{Вы видите новейший компьютер Братства.}
{101}{}{Доступ к этому терминалу закрыт.}
{102}{}{Урок заканчивается через шесть часов. Вы измотаны.}
{103}{}{Вы уже выпили столько, сколько могли.}
{200}{}{Вы видите компьютер. На нем какие-то ошметки, которые могли когда-то быть человеческой плотью.}
{201}{}{Вы возитесь с компьютером какое-то время, но не можете пробиться через систему безопасности.}
{202}{}{You find an interesting data file on a secret base to the northwest, and download the coordinates into your Pip-Boy.}
{203}{}{Вы получаете }
{204}{}{ experience for hacking into the computer!}
{205}{}{You discover some new information about Mariposa Military Base which you didn't known yet.}
{206}{}{Вы получаете }
{207}{}{ experience for hacking into the computer!}
{208}{}{Вы получаете }
{209}{}{ experience for your detective work}
{210}{}{, but ultimately you don't find any new intel while searching this terminal.}
{211}{}{You've learned all you can from the system.}
{300}{}{Этот компьютер прекрасно работает.}
