{100}{}{Вы используете входной компьютер. Компьютер не признает ваш код доступа.}
{101}{}{Вы используете входной компьютер. Громкоговоритель потрескивает и возвращается к жизни.}
{102}{}{Прости, но мы не можем тебя сейчас снова впустить. Ну, технические трудности. Приходи снова попозже.}
{103}{}{Вы видите входной компьютер Убежища 13.}
{104}{}{Извини, это хороший аргумент. но я не могу впустить тебя.}
{105}{}{We're sorry, but you can't come back. We wish you the best.}
{106}{}{Смотритель не сможет выступить против такой большой группы.}
{107}{}{Look, many of us are outraged with the Overseer's decision, but we must comply with his wishes.}
{108}{}{You must make your life in the outside world from now on. Good luck, friend.}
{109}{}{You are a danger to the future of this vault; leave at once.}
{110}{}{Мы не хотим тебя здесь видеть. Пожалуйста, уйди.}
{111}{}{Такие, как ты, нам не нужны. Уходи!}
{112}{}{We are afraid of what you have become and what you may do to us. Leave.}
{113}{}{After what you did to the Overseer, you think we'll let you back?}
{114}{}{Как можно было совершить такое предательство? Оставь меня в покое!}
{115}{}{Уйди, идиот.}
{116}{}{The computer explodes in a spectacular shower of sparks and wiring, short-circuiting the entire configuration.}
{117}{}{Вы видите входной компьютер Убежища 13.}
{118}{}{It's a total mess and completely beyond repair.}
{119}{}{Этот фонарь никогда больше не будет работать.}
{120}{}{Прошу прощения. Этого больше не повторится.}
{121}{}{Direct3D 9}
{122}{}{Uh-oh! }
{123}{}{Этот компьютер сломан.}
{124}{}{With the door forever sealed shut and no replacement Water Chip, the inhabitants of Vault 13 will soon discover that their Vault has become a tomb.}
