{100}{}{You need %d Action Points to do that.}
{101}{}{This weapon's clip is empty.}
{102}{}{Target is out of range for this weapon.}
{103}{}{Cannot end combat now. If no hostiles are present, try End Turn.}
{104}{}{Tu objetivo está bloqueado.}
{105}{}{You cannot use weapons with both arms crippled.}
{106}{}{You cannot use two-handed weapons with a crippled arm.}
{107}{}{You are not strong enough to use this weapon properly.}
{108}{}{ y }
{200}{}{were knocked out}
{201}{}{were knocked down}
{202}{}{te lisias la pierna izquierda}
{203}{}{te deja lisiada la pierna derecha}
{204}{}{te lisias el brazo izquierdo}
{205}{}{te lisias el brazo derecho}
{206}{}{se queda ciega}
{207}{}{has muerto}
{208}{}{impacto}
{209}{}{crítico}
{210}{}{te prenden fuego}
{211}{}{armadura traspasada}
{212}{}{explotó tu arma}
{213}{}{tu arma ha sido destruida}
{214}{}{se te cayó el arma}
{215}{}{has perdido tu siguiente turno}
{216}{}{te golpeas a ti misma}
{217}{}{pierdes el resto de la munición}
{218}{}{dispara un tiro defectuoso}
{219}{}{te golpeas a ti misma}
{220}{}{es golpeada al azar}
{221}{}{se lisia un miembro al azar}
{222}{}{acribillada con fragmentos}
{250}{}{were knocked out}
{251}{}{were knocked down}
{252}{}{te lisias la pierna izquierda}
{253}{}{te deja lisiada la pierna derecha}
{254}{}{te lisias el brazo izquierdo}
{255}{}{te lisias el brazo derecho}
{256}{}{se queda ciega}
{257}{}{has muerto}
{258}{}{impacto}
{259}{}{crítico}
{260}{}{te prenden fuego}
{261}{}{armadura traspasada}
{262}{}{explotó tu arma}
{263}{}{tu arma ha sido destruida}
{264}{}{se te cayó el arma}
{265}{}{has perdido tu siguiente turno}
{266}{}{te golpeas a ti misma}
{267}{}{pierdes el resto de la munición}
{268}{}{dispara un tiro defectuoso}
{269}{}{te golpeas a ti misma}
{270}{}{es golpeada al azar}
{271}{}{se lisia un miembro al azar}
{272}{}{acribillada con fragmentos}
{300}{}{was knocked out}
{301}{}{was knocked down}
{302}{}{se lisia la pierna izquierda}
{303}{}{se lisia la pierna derecha}
{304}{}{se lisia el brazo izquierdo}
{305}{}{se lisia el brazo derecho}
{306}{}{se queda ciega}
{307}{}{se muere}
{308}{}{impacto}
{309}{}{crítico}
{310}{}{la prenden fuego}
{311}{}{le traspasan su armadura}
{312}{}{su arma explotó}
{313}{}{su arma ha sido destruida}
{314}{}{se le cayó el arma}
{315}{}{perdió su siguiente turno}
{316}{}{es golpeado}
{317}{}{perdió el resto de su munición}
{318}{}{dispara un tiro defectuoso}
{319}{}{se hizo daño a si mismo}
{320}{}{es golpeada al azar}
{321}{}{se lisia un miembro al azar}
{322}{}{acribillada con fragmentos}
{400}{}{was knocked out}
{401}{}{was knocked down}
{402}{}{se lisia la pierna izquierda}
{403}{}{se lisia la pierna derecha}
{404}{}{se lisia el brazo izquierdo}
{405}{}{se lisia el brazo derecho}
{406}{}{se queda ciega}
{407}{}{se muere}
{408}{}{impacto}
{409}{}{crítico}
{410}{}{la prenden fuego}
{411}{}{le traspasan su armadura}
{412}{}{su arma explotó}
{413}{}{su arma ha sido destruida}
{414}{}{se le cayó el arma}
{415}{}{perdió su siguiente turno}
{416}{}{es golpeada}
{417}{}{perdió el resto de su munición}
{418}{}{dispara un tiro defectuoso}
{419}{}{se hizo daño si misma}
{420}{}{es golpeada al azar}
{421}{}{se lisia un miembro al azar}
{422}{}{acribillada con fragmentos}
{506}{}{Usted}
{509}{}{¡Ups! %Te han dado, ¡en vez de %s!}
{511}{}{%sTe han dado críticamente (%s), pierdes %d puntos de salud}
{512}{}{%sTe han dado (%s), pierdes %d puntos de salud}
{513}{}{%sTe han dado, pierdes %d puntos de salud}
{514}{}{%s falló críticamente}
{515}{}{%s falló}
{520}{}{%sTe han dado críticamente, pierdes %d puntos de salud}
{521}{}{%sTe han dado críticamente (%s), pierdes 1 punto de salud}
{522}{}{%sTe han dado (%s), pierdes 1 punto de salud}
{523}{}{%sTe han dado, pierdes 1 punto de salud}
{524}{}{%sFallas críticamente, pierdes 1 punto de salud}
{525}{}{%s were critically hit in %s but take no damage}
{526}{}{%s were hit in %s but take no damage}
{527}{}{%s were hit but take no damage}
{528}{}{%s were critically hit but take no damage}
{533}{}{%s falla críticamente, pierde 1 punto de salud}
{534}{}{%s falla críticamente, pierde %d puntos de salud}
{556}{}{Usted}
{559}{}{¡Ups! %Te han dado, ¡en vez de %s!}
{561}{}{%sTe han dado críticamente (%s), pierdes %d puntos de salud}
{562}{}{%sTe han dado (%s), pierdes %d puntos de salud}
{563}{}{%sTe han dado, pierdes %d puntos de salud}
{564}{}{%s falló críticamente}
{565}{}{%s falló}
{570}{}{%sTe han dado críticamente, pierdes %d puntos de salud}
{571}{}{%sTe han dado críticamente (%s), pierdes 1 punto de salud}
{572}{}{%sTe han dado (%s), pierdes 1 punto de salud}
{573}{}{%sTe han dado, pierdes 1 punto de salud}
{574}{}{%sFallas críticamente, pierdes 1 punto de salud}
{575}{}{%s were critically hit in %s but take no damage}
{576}{}{%s were hit in %s but take no damage}
{577}{}{%s were hit but take no damage}
{578}{}{%s were critically hit but take no damage}
{583}{}{%s falla críticamente, pierde 1 punto de salud}
{584}{}{%s falla críticamente, pierde %d puntos de salud}
{608}{}{¡Ups! ¡Le dieron a %s en vez de a ti!}
{609}{}{¡Ups! ¡Le dieron a %s en vez de a %s!}
{611}{}{%s fue golpeada críticamente (%s), pierde %d puntos de salud}
{612}{}{%s fue golpeada (%s), pierde %d puntos de salud}
{613}{}{%s fue golpeada, pierde %d puntos de salud}
{614}{}{%s falló críticamente}
{615}{}{%s falló}
{620}{}{%s fue golpeada críticamente, pierde %d puntos de salud}
{621}{}{%s fue golpeada críticamente (%s), pierde 1 punto de salud}
{622}{}{%s fue golpeada (%s), pierde 1 punto de salud}
{623}{}{%s fue golpeada, pierde 1 punto de salud}
{624}{}{%s fue golpeada críticamente, pierde 1 punto de salud}
{625}{}{%s was critically hit in %s but takes no damage}
{626}{}{%s was hit in %s but takes no damage}
{627}{}{%s was hit but takes no damage}
{628}{}{%s was critically hit but takes no damage}
{633}{}{%s falla críticamente, pierde 1 punto de salud}
{634}{}{%s falla críticamente, pierde %d puntos de salud}
{708}{}{¡Ups! ¡Le dieron a %s en vez de a ti!}
{709}{}{¡Ups! ¡Le dieron a %s en vez de a %s!}
{711}{}{%s fue golpeada críticamente (%s), pierde %d puntos de salud}
{712}{}{%s fue golpeada (%s), pierde %d puntos de salud}
{713}{}{%s fue golpeada, pierde %d puntos de salud}
{714}{}{%s falló críticamente}
{715}{}{%s falló}
{720}{}{%s fue golpeada críticamente, pierde %d puntos de salud}
{721}{}{%s fue golpeada críticamente (%s), pierde 1 punto de salud}
{722}{}{%s fue golpeada (%s), pierde 1 punto de salud}
{723}{}{%s fue golpeada, pierde 1 punto de salud}
{724}{}{%s fue golpeada críticamente, pierde 1 punto de salud}
{725}{}{%s was critically hit in %s but takes no damage}
{726}{}{%s was hit in %s but takes no damage}
{727}{}{%s was hit but takes no damage}
{728}{}{%s was critically hit but takes no damage}
{733}{}{%s falla críticamente, pierde 1 punto de salud}
{734}{}{%s falla críticamente, pierde %d puntos de salud}
{1010}{}{cabeza}
{1011}{}{brazo I}
{1012}{}{brazo D}
{1013}{}{torso}
{1014}{}{pata D}
{1015}{}{pata I}
{1016}{}{ojos}
{1017}{}{ingle}
{1018}{}{}
{1110}{}{cabeza}
{1111}{}{brazo I}
{1112}{}{brazo D}
{1113}{}{torso}
{1114}{}{pata D}
{1115}{}{pata I}
{1116}{}{ojos}
{1117}{}{ingle}
{1118}{}{}
{1150}{}{cabezas}
{1151}{}{pata I}
{1152}{}{pata D}
{1153}{}{torso}
{1154}{}{pata D}
{1155}{}{pata I}
{1156}{}{ojos}
{1157}{}{ubres}
{1158}{}{}
{1160}{}{cabeza}
{1161}{}{pata D}
{1162}{}{pata D}
{1163}{}{torso}
{1164}{}{pata I}
{1165}{}{pata I}
{1166}{}{ojos}
{1167}{}{ingle}
{1168}{}{}
{1170}{}{CPU}
{1171}{}{brazos I}
{1172}{}{brazos D}
{1173}{}{carcasa}
{1174}{}{motor}
{1175}{}{motivador}
{1176}{}{sensores}
{1177}{}{regulador}
{1178}{}{}
{1180}{}{cerebro}
{1181}{}{brazo I}
{1182}{}{brazo D}
{1183}{}{torso}
{1184}{}{pata D}
{1185}{}{pata I}
{1186}{}{monóculo}
{1187}{}{ingle}
{1188}{}{}
{1190}{}{cabeza}
{1191}{}{garra I}
{1192}{}{garra D}
{1193}{}{torso}
{1194}{}{pata D}
{1195}{}{pata I}
{1196}{}{ojos}
{1197}{}{ingle}
{1198}{}{}
{1210}{}{cabeza}
{1211}{}{brazo I}
{1212}{}{brazo D}
{1213}{}{torso}
{1214}{}{pata D}
{1215}{}{pata I}
{1216}{}{ojos}
{1217}{}{ingle}
{1218}{}{}
{1220}{}{cabeza}
{1221}{}{cola}
{1222}{}{pinzas}
{1223}{}{caparazón}
{1224}{}{patas}
{1225}{}{patas}
{1226}{}{ojos}
{1227}{}{cerebro}
{1228}{}{}
{1230}{}{cabeza}
{1231}{}{boca}
{1232}{}{boca}
{1233}{}{torso}
{1234}{}{vejiga flotante}
{1235}{}{cola}
{1236}{}{ganglio}
{1237}{}{oviscapto}
{1238}{}{}
{1240}{}{cabeza}
{1241}{}{garra I}
{1242}{}{garra D}
{1243}{}{torso}
{1244}{}{pata D}
{1245}{}{pata I}
{1246}{}{ojos}
{1247}{}{ingle}
{1248}{}{}
{1250}{}{cabezas}
{1251}{}{colas}
{1252}{}{brazos}
{1253}{}{torso}
{1254}{}{patas D}
{1255}{}{patas I}
{1256}{}{ojos}
{1257}{}{ingle}
{1258}{}{}
{1270}{}{cabeza}
{1271}{}{brazo I}
{1272}{}{brazo D}
{1273}{}{torso}
{1274}{}{pata D}
{1275}{}{pata I}
{1276}{}{ojos}
{1277}{}{ingle}
{1278}{}{}
{1460}{}{cabeza}
{1461}{}{brazo I}
{1462}{}{brazo D}
{1463}{}{torso}
{1464}{}{pata D}
{1465}{}{pata I}
{1466}{}{ojos}
{1467}{}{ingle}
{1468}{}{}
{1490}{}{cabeza}
{1491}{}{brazo I}
{1492}{}{brazo D}
{1493}{}{torso}
{1494}{}{pata D}
{1495}{}{pata I}
{1496}{}{ojos}
{1497}{}{ingle}
{1498}{}{}
{1500}{}{cabeza}
{1501}{}{???}
{1502}{}{???}
{1503}{}{CPU}
{1504}{}{toma principal}
{1505}{}{columna vertebral}
{1506}{}{ojos}
{1507}{}{pantalla}
{1508}{}{}
{1510}{}{cabeza}
{1511}{}{brazo I}
{1512}{}{brazo D}
{1513}{}{torso}
{1514}{}{pata D}
{1515}{}{pata I}
{1516}{}{ojos}
{1517}{}{ingle}
{1518}{}{}
{1520}{}{cabeza}
{1521}{}{brazo I}
{1522}{}{brazo D}
{1523}{}{abdomen}
{1524}{}{patas}
{1525}{}{alas}
{1526}{}{ojos}
{1527}{}{metatórax}
{1528}{}{}
{1530}{}{CPU}
{1531}{}{brazo I}
{1532}{}{brazo D}
{1533}{}{carcasa}
{1534}{}{oruga}
{1535}{}{motivador}
{1536}{}{sensores}
{1537}{}{regulador}
{1538}{}{}
{1540}{}{CPU}
{1541}{}{manipulador}
{1542}{}{arma}
{1543}{}{carcasa}
{1544}{}{motivador}
{1545}{}{motivador}
{1546}{}{sensores}
{1547}{}{regulador}
{1548}{}{}
{1550}{}{cabeza}
{1551}{}{garra I}
{1552}{}{garra D}
{1553}{}{torso}
{1554}{}{pata D}
{1555}{}{pata I}
{1556}{}{ojos}
{1557}{}{ingle}
{1558}{}{}
{1580}{}{caparazón}
{1581}{}{caparazón}
{1582}{}{caparazón}
{1583}{}{caparazón}
{1584}{}{caparazón}
{1585}{}{caparazón}
{1586}{}{caparazón}
{1587}{}{caparazón}
{1588}{}{}
{5000}{}{. El ataque la ha dejado fuera de combate}
{5001}{}{. La huelga provoca un dolor inmenso}
{5002}{}{ sin pararse siquiera ante la armadura}
{5003}{}{. El ataque lo ha dejado sin conocimiento}
{5004}{}{. El golpe le ha hecho caer al suelo}
{5005}{}{. El fuerte golpe en la cabeza lo ha dejado fuera de combate}
{5006}{}{. El golpe aplasta la sien. Buenas noches}
{5007}{}{, se convierte en la pesadilla de un agente funerario. Su muerte es instantánea}
{5008}{}{, provocando un grave codazo}
{5009}{}{, quitando el brazo de en medio}
{5010}{}{, haciendo un gran moretón}
{5011}{}{, hiriendo el brazo izquierdo}
{5012}{}{, dejando el brazo izquierdo colgando por la piel}
{5013}{}{. Ese brazo parece ahora un muñón}
{5014}{}{, dejando el brazo derecho herido}
{5015}{}{. Su brazo ha quedado pulverizado por este poderoso golpe}
{5016}{}{ con un poderoso golpe}
{5017}{}{, reventando la armadura}
{5018}{}{, infligiendo una ayuda extra de daños}
{5019}{}{ a través de su armadura, haciendo caer al suelo al combatiente}
{5020}{}{ dejándolo sin aire, se desploma al suelo}
{5021}{}{. Unfortunately for him, his spine is now clearly visible from the front}
{5022}{}{ haciéndole una grave herida en la pierna}
{5023}{}{, derribándolo como si fuese un muñeco de trapo}
{5024}{}{, bowling him over and chopping off that leg like a scarlet side of meat}
{5025}{}{, machacándole la rodilla. Cae al suelo}
{5026}{}{. El intenso dolor de la pierna arrancada hace que se retire}
{5027}{}{ infligiendo algo de dolor extra}
{5028}{}{ causando ceguera, por desgracia para él}
{5029}{}{, y sin protección ahí, causando mucho dolor}
{5030}{}{, y dejando ciego a tu oponente}
{5031}{}{. La pérdida de un ojo es demasiado para él, cae al suelo}
{5032}{}{, por desgracia, está demasiado ocupado sintiendo la brisa en los sesos como para notar que se aproxima la muerte}
{5033}{}{. ¡Ay! Eso tuvo que doler}
{5034}{}{, y tampoco lleva una copa}
{5035}{}{ y sin protección, cae al suelo, gimiendo en agonía}
{5036}{}{. Es demasiado doloroso y cae al suelo hecho polvo}
{5037}{}{. Murmura "Mamá", mientras se le quedan los ojos en blanco}
{5100}{}{. El ataque la ha dejado fuera de combate}
{5101}{}{. La huelga provoca un dolor inmenso}
{5102}{}{ atravesando su armadura}
{5103}{}{. El potente ataque la deja inconsciente}
{5104}{}{. El sopapo hace que se caiga al suelo}
{5105}{}{. El fuerte golpe en la cabeza la deja inconsciente}
{5106}{}{. El golpe aplasta su sien en una fuente de sangre. Buenas noches, Gracie}
{5107}{}{, haciéndola girar en una danza macabra. La muerte es instantánea.}
{5108}{}{, provocando un grave codazo}
{5109}{}{, quitando el brazo de en medio}
{5110}{}{, haciendo un gran moretón}
{5111}{}{, perforando el codo izquierdo con facilidad}
{5112}{}{. El brazo izquierdo le cuelga levemente del hombro}
{5113}{}{. Ese brazo parece ahora un muñón}
{5114}{}{, destrozando su brazo en una lluvia carmesí}
{5115}{}{. Su brazo derecho queda hecho picadillo por el golpe}
{5116}{}{ con un poderoso golpe}
{5117}{}{ traspasando sus defensas}
{5118}{}{, infligiendo una ayuda extra de daños}
{5119}{}{ traspasa su armadura, tirándola al suelo}
{5120}{}{ sacándole el aire. Se desploma en el suelo}
{5121}{}{. Unfortunately for her, most organs have now been exposed to the light}
{5122}{}{ hiriéndola de gravedad en la pierna}
{5123}{}{, tirándola como a una mala cita a ciegas}
{5124}{}{, dejándola fuera de combate y esparciendo esa pierna por todo el suelo}
{5125}{}{, aplastando la rodilla. Opta por el camino rápido al suelo}
{5126}{}{. Grita de dolor por la pierna rota}
{5127}{}{ infligiendo algo de dolor extra}
{5128}{}{ dejándola ciega. Hace una mueca}
{5129}{}{, y sin protección ahí, causando mucho dolor}
{5130}{}{. La herida la deja gravemente ciega, como si pudiese haber una ceguera leve}
{5131}{}{. Se desmaya por el cegador ataque}
{5132}{}{, qué pena, no reza a sus dioses antes de reunirse con ellos}
{5133}{}{. Se lo toma como un hombre. O sea, que llora}
{5134}{}{, cae al suelo}
{5135}{}{. Ya no podrá ser madre, se desploma con la cadera destrozada}
{5200}{}{. El niño empieza a llorar}
{5201}{}{. Inconsciente, el pequeño se desploma}
{5202}{}{. ¡Ayyy!}
{5203}{}{. El golpe es válido, y el chico cae inconsciente}
{5204}{}{, aplastando al chico como a una bolsa de trapo}
{5205}{}{. El brazo izquierdo de este chaval ahora tiene un tajo}
{5206}{}{, lanzando al niño hasta desequilibrarlo}
{5207}{}{, rompiendo ese brazo con un fuerte chasquido. Le caen algunas lágrimas}
{5208}{}{, rompiendo ese brazo como un pedazo de caramelo}
{5209}{}{. El brazo derecho comienza a hincharse, como una pelota}
{5210}{}{, y empieza a llorar}
{5211}{}{ en una espinilla}
{5212}{}{. El ataque a un órgano vital deja KO al niño}
{5213}{}{, dejando KO al niño como un juguete}
{5214}{}{. Ahora este chaval nunca experimentará la vida}
{5215}{}{, infligiendo un corte profundo}
{5216}{}{. El ataque deja al niño inconsciente, y le rompe la pierna}
{5217}{}{, infligiendo un gran daño al pequeño}
{5218}{}{. El chaval alza la vista y se pone a llorar}
{5219}{}{, lo cual deja ciego al joven}
{5220}{}{, aplastando su joven y bonita nariz}
{5221}{}{. Un corte aparece encima de sus ojos y empieza a chorrear sangre}
{5222}{}{, lo cual le abre un ojo como a un grano de uva. El niño parece desconcertado}
{5223}{}{ causándole ceguera. El joven niño se cae al suelo}
{5224}{}{, el golpe continúa hasta su pequeño cerebro y lo convierte en puré}
{5225}{}{. El niño parece confundido y sacudido}
{5226}{}{, dejando a este niño KO en el suelo}
{5300}{}{, hiriendo al fuerte mutante}
{5301}{}{, golpeando un punto vital}
{5302}{}{, golpeando un punto vital y derribando al gigante al suelo}
{5303}{}{. El mutante gigante te mira por un momento y luego se desploma}
{5304}{}{. La cabeza explota como una sandía sangrienta}
{5305}{}{, hiriendo de gravedad al fuerte mutante}
{5306}{}{, haciendo que el gigante maldiga por un momento su existencia}
{5307}{}{, golpeando un nervio y forzando al gigante a agarrarse el brazo de dolor}
{5308}{}{. El golpe le rompe el codo y probablemente no le sienta muy bien}
{5309}{}{, rompiendo el grueso brazo y esparciendo la sangre mutante por el suelo}
{5310}{}{, haciendo que el gigante enemigo se tambalee por un momento y luego caiga como un árbol talado}
{5311}{}{, y litros de vísceras son escupidos contra al suelo}
{5312}{}{, enviando al mutante volar al suelo}
{5313}{}{. El mutante se tambalea y cae. Su pierna ya no lo aguanta en pie}
{5314}{}{, golpeando un punto vital. El mutante se desploma sobre la pierna rota}
{5315}{}{. El dolor de la pierna rota abruma al fuerte gigante}
{5316}{}{, dejando casi ciego al mutante}
{5317}{}{, dejando ciego al mutante furioso}
{5318}{}{, dejando casi ciego al mutante y haciendo que pierda el equilibrio}
{5319}{}{. El mutante ciego da un traspié hacia atrás, quedando vulnerable para el siguiente ataque}
{5320}{}{, dejando ciego al ahora inconsciente mutante}
{5321}{}{. Los ojos del mutante brillan por un momento y luego llega su oscuridad}
{5400}{}{. El necrófago se sorprende, y no consigue defenderse de este ataque}
{5401}{}{. El golpe entierra al necrófago}
{5402}{}{. La mano del necrófago sorprendido vuela por los aires}
{5403}{}{, traspasando su armadura y golpeando un punto vital}
{5404}{}{, traspasando su armadura y arrancándole el brazo}
{5405}{}{. El necrófago se mueve hacia el sitio equivocado en el momento equivocado y pierde un ojo}
{5406}{}{. El necrófago no lleva armadura ahí}
{5407}{}{, y los ojos le explotan como si fueran morcillas}
{5408}{}{, el necrófago parece muy furioso en sus últimos momentos}
{5500}{}{, haciendo caer a la enorme bestia al suelo}
{5501}{}{, aturdiendo ambos cerebros y derribando al gigante animal}
{5502}{}{. La vaca mutante lanza un agudo y sobresaltado "muuu"}
{5503}{}{, rompiendo una de la patas del brahmin}
{5504}{}{, hiriendo de gravedad a la vaca mutante}
{5505}{}{, penetrando con facilidad la gruesa piel de la bestia gigante}
{5506}{}{, atravesando los dos corazones de la vaca mutante}
{5507}{}{, dejando ciegos los dos pares de ojos de un solo golpe}
{5508}{}{, cegando a ambas cabezas y atontando a la vaca mutante}
{5509}{}{, cegando por completo al brahmin y derribándolo}
{5510}{}{, el gran bovino mutante se tambalea un momento}
{5511}{}{. El brahmin se agita con rabia}
{5512}{}{. El brahmin resopla de dolor}
{5513}{}{. El brahmin está enfadadísimo por tu ataque devastador en las ubres}
{5600}{}{, enviando al escorpión rad a volar}
{5601}{}{, separando la cabeza del caparazón}
{5602}{}{, dañando seriamente la cola}
{5603}{}{, haciendo una herida profunda en las garras}
{5604}{}{. El golpe se mete entre las grietas del duro caparazón del escorpión rad}
{5605}{}{, golpeando el duro caparazón sin parar}
{5606}{}{, atravesando la coraza natural y derribando al escorpión rad}
{5607}{}{. El escorpión rad expira de causa "natural", como es la pérdida de órganos internos}
{5608}{}{, haciendo volar al escorpión y destrozando algunas de sus patas}
{5609}{}{. El ataque profundiza en una grieta de la pata, agravándola}
{5610}{}{, hiriendo gravemente y dejando ciega a la criatura mutante}
{5611}{}{, llegando casi hasta el cerebro. Y luego dicen que es asqueroso aplastar cucarachas.}
{5612}{}{, llegando casi hasta el cerebro y dejando ciega a la criatura}
{5613}{}{. El ataque es salvaje, y de sobra sofisticado para esta simple criatura}
{5614}{}{. Si fuese humano, dirías que lo has cabreado}
{5615}{}{, dejando sin sentido a la pobre criatura}
{5616}{}{, clavando los sesos en el suelo}
{5700}{}{. El cadáver del roedor hace unos ruidos poco saludables}
{5701}{}{, aplastando el cráneo del roedor como a una bolsa de papel mojada}
{5702}{}{, y la garra izquierda parece ahora algo plana}
{5703}{}{. La garra izquierda de la rata ha volado por los aires}
{5704}{}{. La garra derecha está muy dañada}
{5705}{}{, reduciendo la garra derecha a una fina pasta roja}
{5706}{}{. La rata ha sido seriamente dañada en este ataque y chilla de dolor}
{5707}{}{, hiriendo gravemente a la rata y dejándola fuera de combate}
{5708}{}{, aplastando a la rata en el suelo}
{5709}{}{, arrancándole fácilmente la pata derecha}
{5710}{}{, haciendo un gran agujero en la pata izquierda}
{5711}{}{, haciendo algo de daño extra en un punto sensible}
{5712}{}{, enviando a la criatura a la gran ratonera celestial}
{5800}{}{, el flotante cae al suelo}
{5801}{}{, el flotante cae el suelo al parecer sin vida}
{5802}{}{, con graves consecuencias para la existencia de la criatura}
{5803}{}{, aturdiendo a la asquerosa criatura}
{5804}{}{, golpeando un punto sensible y aturdiendo a la criatura}
{5805}{}{. El golpe hace que el flotante muera de forma violenta en un rocío carmesí}
{5806}{}{, causando el golpe una violenta reacción en la criatura}
{5807}{}{. De repente el flotante estalla en llamas}
{5808}{}{ luego se sacude salvajemente y tiembla como si fuese a reventar}
{5809}{}{, el golpe ha dado en un punto sensible}
{5810}{}{. La criatura está claramente agitada}
{5900}{}{, abandonado, el centauro se derrumba aturdido}
{5901}{}{ mientras golpeas un punto crítico}
{5902}{}{, causando un masivo fallo neurálgico}
{5903}{}{, aturdiéndolo con tu violento ataque}
{5904}{}{, destrozando el brazo}
{5905}{}{ golpeando un punto crítico, y destrozando el brazo}
{5906}{}{, derribando a la criatura y destrozando la pata}
{5907}{}{, aturdiendo al centauro al tiempo que es derribado con una pata destrozada}
{5908}{}{, blinding one head and liquefying the other}
{5909}{}{, sorprendiendo al centauro. Por un momento se tambalea ciego}
{5910}{}{, sorprendiendo al centauro. Se derrumba en un montón}
{5911}{}{, sorprendiendo al centauro. Se desmaya en una pila de sustancia pegajosa}
{5912}{}{. El ataque no ha sido tan eficaz como hubieras querido}
{6000}{}{, infligiendo algún daño estructural}
{6001}{}{, vuelan chispas y el robot pierde por un momento el control}
{6002}{}{, golpeando un punto crítico y haciendo que el robot pierda el control}
{6003}{}{, golpeando un componente crítico y causando un mal funcionamiento masivo}
{6004}{}{. El robot intenta compensar}
{6005}{}{. El robot se estira para compensar}
{6006}{}{, golpeando algún punto clave y causando graves daños}
{6007}{}{, causando profundos daños estructurales}
{6008}{}{, golpeando un componente crítico y causando daños severos}
{6009}{}{. El robot se estremece con este intenso ataque}
{6010}{}{, desmantelando el robot}
{6011}{}{. El robot intenta compensar, pero falla y cae al suelo}
{6012}{}{. El robot cede ante la presión, cayendo al suelo}
{6013}{}{, rompiendo las lentes del sensor}
{6100}{}{, haciendo caer al chucho al suelo}
{6101}{}{, justo en el hocico}
{6102}{}{. El perro cae al suelo pero todavía respira}
{6103}{}{, haciendo toser al animal una chorro de sangre}
{6104}{}{, destrozando la pata}
{6105}{}{, destrozando la pata. El animal intenta seguir en pie pero no lo consigue}
{6106}{}{. El animal ciego aúlla de dolor}
{6107}{}{, asesinando al pobre animal}
{6200}{}{, derribando al insecto mutante}
{6201}{}{, que se desploma}
{6202}{}{. La mantis está pensando si merece la pena vivir}
{6203}{}{, destrozando el miembro}
{6204}{}{, haciendo que la mantis lama sus heridas. Sujeta el miembro de forma extraña}
{6205}{}{, atravesando el armazón de quitina}
{6206}{}{. La mantis chilla y tiembla horriblemente}
{6207}{}{, lo que hace que la mantis caiga. Un miembro queda extrañamente retorcido}
{6208}{}{, haciendo trizas las alas}
{6209}{}{, atravesando el armazón de quitina y lanzando a la mantis por los aires}
{6210}{}{, dejando ciego al insecto de un solo golpe}
{6300}{}{. Incluso esta bestia parece desconcertada por el ataque}
{6301}{}{, pasando las enormes garras para golpear al monstruo. La Garra Mortal se agita y gruñe}
{6302}{}{. Has causado graves daños en los ojos de la Garra Mortal}
{6400}{}{, breaking past his bio-organic defenses}
{6401}{}{, causing him some serious grief}
{6402}{}{, breaking past his bio-organic defenses and putting the pressure on him}
{6403}{}{, stunning him with a solid offensive plan}
{6404}{}{, causing an overload of cataclysmic proportions in his systems}
{6405}{}{. Still, the attack against him seems to do less damage than it should have}
{6406}{}{. The blow gets by his bio-organic defenses, actually blinding him}
{6500}{}{. Mañana tendrás dolor de cabeza, si es que estás vivo.}
{6501}{}{. Tu armadura no te protege de este golpe}
{6502}{}{. Sientes dolor por un momento antes de perder el conocimiento.}
{6503}{}{, atravesando tu armadura. El golpe te hace caer al suelo}
{6504}{}{, el golpe hace que se te oscurezca la visión. Después de un momento, te das cuenta de que no volverás a ver}
{6505}{}{. Obtienes una bonita vista de tu cuerpo mientras tu cabeza vuela por los aires}
{6506}{}{. Sorprendentemente, el daño no se siente más de lo normal}
{6507}{}{, aturdiéndote por un momento}
{6508}{}{. Sientes dolor}
{6509}{}{. El ataque te deja un brazo inservible}
{6510}{}{, atravesando tu armadura. El golpe rompe los huesos de tu brazo como si fuera un trozo de madera}
{6511}{}{, atravesando tu armadura. El brazo ahora te cuelga del costado}
{6512}{}{. El moretón será precioso y posiblemente la cicatriz te dará mucho de qué hablar}
{6513}{}{, aplastando tus órganos internos. Todo lo que puedes hacer es escupir sangre}
{6514}{}{, sending you head over heels}
{6515}{}{, haciéndote saltar por los aires y rompiéndote una pierna}
{6516}{}{, derritiendo tu armadura. El golpe te derriba y daña seriamente tu rodilla}
{6517}{}{. El dolor de la pierna rota te hace desmayar}
{6518}{}{. El doloroso golpe te hace retroceder pero nada más}
{6519}{}{. Por desgracia para ti, también produce una inmediata pérdida de visión}
{6520}{}{. Te lleva un tiempo limpiarte la sangre de los ojos}
{6521}{}{, traspasa tu armadura. Sigues aturdido y te das cuenta de que no puedes ver}
{6522}{}{. Sientes una sensación extraña en la cabeza. Te das cuenta de qué se trata de una inminente muerte cerebral}
{6523}{}{, haciendo que te acobardes}
{6524}{}{. Te echas mano a la ingle y caes al suelo de dolor}
{6525}{}{. El dolor es lo bastante fuerte como para hacerte caer.}
{6526}{}{. No hay bastantes palabras en el universo para describir el dolor que sientes en estos momentos}
