{100}{}{You need %d Action Points to do that.}
{101}{}{This weapon's clip is empty.}
{102}{}{Target is out of range for this weapon.}
{103}{}{Cannot end combat now. If no hostiles are present, try End Turn.}
{104}{}{Línea de fuego bloqueada.}
{105}{}{No puedes usar armas con los dos brazos rotos.}
{106}{}{No puedes usar armas de dos manos con un brazo roto.}
{107}{}{No eres lo suficientemente fuerte para usar esta arma correctamente.}
{108}{}{ y }
{200}{}{were knocked out}
{201}{}{were knocked down}
{202}{}{te deja lisiada la pierna izquierda}
{203}{}{te deja lisiada la pierna derecha}
{204}{}{te deja lisiado el brazo izquierdo}
{205}{}{te deja lisiado el brazo derecho}
{206}{}{cegado}
{207}{}{mueres}
{208}{}{es herido}
{209}{}{críticamente}
{210}{}{te prenden fuego}
{211}{}{traspasa tu armadura}
{212}{}{tu arma explota}
{213}{}{tu arma ha sido destruida}
{214}{}{tu arma se cae}
{215}{}{pierdes el siguiente turno}
{216}{}{te hieres a ti mismo}
{217}{}{pierdes el resto de tu munición}
{218}{}{dispara un proyectil defectuoso}
{219}{}{hiriéndote}
{220}{}{es golpeado al azar}
{221}{}{se rompe un miembro al azar}
{222}{}{le alcanzan los fragmentos}
{250}{}{were knocked out}
{251}{}{were knocked down}
{252}{}{te deja lisiada la pierna izquierda}
{253}{}{te deja lisiada la pierna derecha}
{254}{}{te deja lisiado el brazo izquierdo}
{255}{}{te deja lisiado el brazo derecho}
{256}{}{cegado}
{257}{}{mueres}
{258}{}{es herido}
{259}{}{críticamente}
{260}{}{te prenden fuego}
{261}{}{traspasa tu armadura}
{262}{}{tu arma explota}
{263}{}{tu arma ha sido destruida}
{264}{}{tu arma se cae}
{265}{}{pierdes el siguiente turno}
{266}{}{te hieres a ti mismo}
{267}{}{pierdes el resto de tu munición}
{268}{}{dispara un proyectil defectuoso}
{269}{}{hiriéndote}
{270}{}{es golpeado al azar}
{271}{}{se rompe un miembro al azar}
{272}{}{le alcanzan los fragmentos}
{300}{}{was knocked out}
{301}{}{was knocked down}
{302}{}{rompe su pierna izquierda}
{303}{}{rompe su pierna derecha}
{304}{}{rompe su brazo izquierdo}
{305}{}{rompe su brazo derecho}
{306}{}{cegado}
{307}{}{ha muerto}
{308}{}{es herido}
{309}{}{críticamente}
{310}{}{la prenden fuego}
{311}{}{traspasando su armadura}
{312}{}{su arma explota}
{313}{}{su arma ha sido destruida}
{314}{}{su arma se cae}
{315}{}{pierde su siguiente turno}
{316}{}{se hiere a sí mismo}
{317}{}{pierde el resto de su munición}
{318}{}{dispara un proyectil defectuoso}
{319}{}{hiriéndose}
{320}{}{es golpeado al azar}
{321}{}{se rompe un miembro al azar}
{322}{}{le alcanzan los fragmentos}
{400}{}{was knocked out}
{401}{}{was knocked down}
{402}{}{rompe su pierna izquierda}
{403}{}{rompe su pierna derecha}
{404}{}{rompe su brazo izquierdo}
{405}{}{rompe su brazo derecho}
{406}{}{cegado}
{407}{}{ha muerto}
{408}{}{es herido}
{409}{}{críticamente}
{410}{}{la prenden fuego}
{411}{}{traspasa su armadura}
{412}{}{su arma explota}
{413}{}{su arma ha sido destruida}
{414}{}{se le cayó el arma}
{415}{}{pierde su siguiente turno}
{416}{}{se hiere a sí misma}
{417}{}{pierde el resto de su munición}
{418}{}{dispara un proyectil defectuoso}
{419}{}{hiriéndose}
{420}{}{es golpeado al azar}
{421}{}{se rompe un miembro al azar}
{422}{}{le alcanzan los fragmentos}
{506}{}{Usted}
{509}{}{¡Ups! %s es herido en vez de %s!}
{511}{}{%s es herido críticamente en %s, pierdes %d puntos de salud}
{512}{}{%s es herido en %s perdiendo %d puntos de salud}
{513}{}{%s es herido perdiendo %d puntos de salud}
{514}{}{%s falla críticamente}
{515}{}{%s falla}
{520}{}{%s es herido críticamente, pierdes %d puntos de salud}
{521}{}{%s es herido críticamente en %s perdiendo 1 punto de salud}
{522}{}{%s es herido en %s y pierdes 1 punto de salud}
{523}{}{%s es herido y pierdes 1 punto de salud}
{524}{}{%s eres críticamente herido y pierdes 1 punto de salud}
{525}{}{%s were critically hit in %s but take no damage}
{526}{}{%s were hit in %s but take no damage}
{527}{}{%s were hit but take no damage}
{528}{}{%s were critically hit but take no damage}
{533}{}{%s falla críticamente, pierde 1 punto de salud}
{534}{}{%s falla críticamente, pierde %d puntos de salud}
{556}{}{Usted}
{559}{}{¡Ups! %s es herido en vez de %s!}
{561}{}{%s es herido críticamente en %s, pierdes %d puntos de salud}
{562}{}{%s es herido en %s perdiendo %d puntos de salud}
{563}{}{%s es herido perdiendo %d puntos de salud}
{564}{}{%s falla críticamente}
{565}{}{%s falla}
{570}{}{%s es herido críticamente, pierdes %d puntos de salud}
{571}{}{%s es herido críticamente en %s perdiendo 1 punto de salud}
{572}{}{%s es herido en %s y pierdes 1 punto de salud}
{573}{}{%s es herido y pierdes 1 punto de salud}
{574}{}{%s eres críticamente herido y pierdes 1 punto de salud}
{575}{}{%s were critically hit in %s but take no damage}
{576}{}{%s were hit in %s but take no damage}
{577}{}{%s were hit but take no damage}
{578}{}{%s were critically hit but take no damage}
{583}{}{%s falla críticamente, pierde 1 punto de salud}
{584}{}{%s falla críticamente, pierde %d puntos de salud}
{608}{}{¡Ups! ¡Le dieron a %s en vez de a ti!}
{609}{}{¡Ups! ¡%s es herido en vez de %s!}
{611}{}{%s es herido críticamente en %s, perdiendo %d puntos de salud}
{612}{}{%s es herido en %s, pierde %d puntos de salud}
{613}{}{%s es herido, pierde %d puntos de salud}
{614}{}{%s falla críticamente}
{615}{}{%s falla}
{620}{}{%s es críticamente herido, pierde %d puntos de salud}
{621}{}{%s es críticamente herido en %s y pierde 1 punto de salud}
{622}{}{%s es herido en %s y pierde 1 punto de salud}
{623}{}{%s es herido y pierde 1 punto de salud}
{624}{}{%s es críticamente herido y pierde 1 punto de salud}
{625}{}{%s was critically hit in %s but takes no damage}
{626}{}{%s was hit in %s but takes no damage}
{627}{}{%s was hit but takes no damage}
{628}{}{%s was critically hit but takes no damage}
{633}{}{%s falla críticamente, pierde 1 punto de salud}
{634}{}{%s falla críticamente, pierde %d puntos de salud}
{708}{}{¡Ups! ¡Le dieron a %s en vez de a ti!}
{709}{}{¡Ups! ¡%s es herido en vez de %s!}
{711}{}{%s es herido críticamente en %s, perdiendo %d puntos de salud}
{712}{}{%s es herido en %s, pierde %d puntos de salud}
{713}{}{%s es herido, pierde %d puntos de salud}
{714}{}{%s falla críticamente}
{715}{}{%s falla}
{720}{}{%s es críticamente herido, pierde %d puntos de salud}
{721}{}{%s es críticamente herido en %s y pierde 1 punto de salud}
{722}{}{%s es herido en %s y pierde 1 punto de salud}
{723}{}{%s es herido y pierde 1 punto de salud}
{724}{}{%s es críticamente herido y pierde 1 punto de salud}
{725}{}{%s was critically hit in %s but takes no damage}
{726}{}{%s was hit in %s but takes no damage}
{727}{}{%s was hit but takes no damage}
{728}{}{%s was critically hit but takes no damage}
{733}{}{%s falla críticamente, pierde 1 punto de salud}
{734}{}{%s falla críticamente, pierde %d puntos de salud}
{1010}{}{la cabeza}
{1011}{}{el brazo izquierdo}
{1012}{}{el brazo derecho}
{1013}{}{el torso}
{1014}{}{la pierna derecha}
{1015}{}{la pierna izquierda}
{1016}{}{los ojos}
{1017}{}{la ingle}
{1018}{}{}
{1110}{}{la cabeza}
{1111}{}{el brazo izquierdo}
{1112}{}{el brazo derecho}
{1113}{}{el torso}
{1114}{}{la pierna derecha}
{1115}{}{la pierna izquierda}
{1116}{}{los ojos}
{1117}{}{la ingle}
{1118}{}{}
{1150}{}{cabezas}
{1151}{}{la pata trasera izquierda}
{1152}{}{la pata trasera derecha}
{1153}{}{el torso}
{1154}{}{la pata delantera derecha}
{1155}{}{la delantera izquierda}
{1156}{}{los ojos}
{1157}{}{las ubres}
{1158}{}{}
{1160}{}{la cabeza}
{1161}{}{la pata trasera}
{1162}{}{la pata trasera}
{1163}{}{el cuerpo}
{1164}{}{la pata delantera}
{1165}{}{la pata delantera}
{1166}{}{los ojos}
{1167}{}{la ingle}
{1168}{}{}
{1170}{}{la CPU}
{1171}{}{brazos I}
{1172}{}{brazos D}
{1173}{}{la estructura}
{1174}{}{motor}
{1175}{}{la unidad motriz}
{1176}{}{los sensores}
{1177}{}{el regulador}
{1178}{}{}
{1180}{}{el cerebro}
{1181}{}{el brazo izquierdo}
{1182}{}{el brazo derecho}
{1183}{}{el torso}
{1184}{}{la pierna derecha}
{1185}{}{la pierna izquierda}
{1186}{}{monóculo}
{1187}{}{la ingle}
{1188}{}{}
{1190}{}{la cabeza}
{1191}{}{la garra izquierda}
{1192}{}{la garra derecha}
{1193}{}{el cuerpo}
{1194}{}{la pierna derecha}
{1195}{}{la pierna izquierda}
{1196}{}{los ojos}
{1197}{}{la ingle}
{1198}{}{}
{1210}{}{la cabeza}
{1211}{}{el brazo izquierdo}
{1212}{}{el brazo derecho}
{1213}{}{el torso}
{1214}{}{la pierna derecha}
{1215}{}{la pierna izquierda}
{1216}{}{los ojos}
{1217}{}{la ingle}
{1218}{}{}
{1220}{}{la cabeza}
{1221}{}{la cola}
{1222}{}{pinzas}
{1223}{}{el caparazón}
{1224}{}{las patas delanteras}
{1225}{}{las patas traseras}
{1226}{}{los ojos}
{1227}{}{el cerebro}
{1228}{}{}
{1230}{}{la cabeza}
{1231}{}{la boca}
{1232}{}{la boca delantera}
{1233}{}{el cuerpo}
{1234}{}{vejiga flotante}
{1235}{}{la cola}
{1236}{}{los ganglios}
{1237}{}{el ovicapto}
{1238}{}{}
{1240}{}{la cabeza}
{1241}{}{la garra izquierda}
{1242}{}{la garra derecha}
{1243}{}{el cuerpo}
{1244}{}{la pierna derecha}
{1245}{}{la pierna izquierda}
{1246}{}{los ojos}
{1247}{}{la ingle}
{1248}{}{}
{1250}{}{cabezas}
{1251}{}{colas}
{1252}{}{brazos}
{1253}{}{el cuerpo}
{1254}{}{patas D}
{1255}{}{patas I}
{1256}{}{los ojos}
{1257}{}{la ingle}
{1258}{}{}
{1270}{}{la cabeza}
{1271}{}{el brazo izquierdo}
{1272}{}{el brazo derecho}
{1273}{}{el torso}
{1274}{}{la pierna derecha}
{1275}{}{la pierna izquierda}
{1276}{}{los ojos}
{1277}{}{la ingle}
{1278}{}{}
{1460}{}{la cabeza}
{1461}{}{el brazo izquierdo}
{1462}{}{el brazo derecho}
{1463}{}{el torso}
{1464}{}{la pierna derecha}
{1465}{}{la pierna izquierda}
{1466}{}{los ojos}
{1467}{}{la ingle}
{1468}{}{}
{1490}{}{la cabeza}
{1491}{}{el brazo izquierdo}
{1492}{}{el brazo derecho}
{1493}{}{el torso}
{1494}{}{la pierna derecha}
{1495}{}{la pierna izquierda}
{1496}{}{los ojos}
{1497}{}{la ingle}
{1498}{}{}
{1500}{}{la cabeza}
{1501}{}{???}
{1502}{}{???}
{1503}{}{la CPU}
{1504}{}{toma principal}
{1505}{}{columna vertebral}
{1506}{}{los ojos}
{1507}{}{pantalla}
{1508}{}{}
{1510}{}{la cabeza}
{1511}{}{el brazo izquierdo}
{1512}{}{el brazo derecho}
{1513}{}{el torso}
{1514}{}{la pierna derecha}
{1515}{}{la pierna izquierda}
{1516}{}{los ojos}
{1517}{}{la ingle}
{1518}{}{}
{1520}{}{la cabeza}
{1521}{}{el brazo izquierdo}
{1522}{}{el brazo derecho}
{1523}{}{el abdomen}
{1524}{}{las patas}
{1525}{}{las alas}
{1526}{}{los ojos}
{1527}{}{el metatórax}
{1528}{}{}
{1530}{}{la CPU}
{1531}{}{el brazo izquierdo}
{1532}{}{el brazo derecho}
{1533}{}{la estructura}
{1534}{}{oruga}
{1535}{}{la unidad motriz}
{1536}{}{los sensores}
{1537}{}{el regulador}
{1538}{}{}
{1540}{}{la CPU}
{1541}{}{el manipulador}
{1542}{}{arma}
{1543}{}{la estructura}
{1544}{}{la unidad motriz}
{1545}{}{la unidad motriz}
{1546}{}{los sensores}
{1547}{}{el regulador}
{1548}{}{}
{1550}{}{la cabeza}
{1551}{}{la garra izquierda}
{1552}{}{la garra derecha}
{1553}{}{el cuerpo}
{1554}{}{la pierna derecha}
{1555}{}{la pierna izquierda}
{1556}{}{los ojos}
{1557}{}{la ingle}
{1558}{}{}
{1580}{}{la cáscara}
{1581}{}{la cáscara}
{1582}{}{la cáscara}
{1583}{}{la cáscara}
{1584}{}{la cáscara}
{1585}{}{la cáscara}
{1586}{}{la cáscara}
{1587}{}{la cáscara}
{1588}{}{}
{5000}{}{. El ataque la ha dejado fuera de combate}
{5001}{}{. La huelga provoca un dolor inmenso}
{5002}{}{ sin pararse siquiera ante la armadura}
{5003}{}{. El ataque lo deja inconsciente}
{5004}{}{. El golpe lo tira al suelo}
{5005}{}{. El fuerte golpe en la cabeza lo deja fuera de combate}
{5006}{}{. El ataque aplasta su sien. Buenas noches, Gracie}
{5007}{}{, se convierte en la pesadilla de un agente funerario. Su muerte es instantánea}
{5008}{}{, causando una grave luxación en el codo}
{5009}{}{, arrancándole el brazo}
{5010}{}{, dejando un gran hematoma}
{5011}{}{, rompiéndole el brazo izquierdo}
{5012}{}{, dejando el brazo izquierdo colgando de la piel}
{5013}{}{. Ahora ese brazo parece un muñón sangriento}
{5014}{}{, dejándole el brazo derecho roto}
{5015}{}{. Su brazo derecho queda pulverizado por este potente golpe}
{5016}{}{ en un potente golpe}
{5017}{}{, al perforar sus defensas}
{5018}{}{, provocando aún mas daño}
{5019}{}{ a través de su armadura, haciendo caer al suelo al combatiente}
{5020}{}{ dejándolo sin aire, se desploma al suelo}
{5021}{}{. Unfortunately for him, his spine is now clearly visible from the front}
{5022}{}{ haciéndole una grave herida en la pierna}
{5023}{}{, tirándole al suelo como un bolo en medio de una bolera}
{5024}{}{, bowling him over and chopping off that leg like a scarlet side of meat}
{5025}{}{, enviándole la rodilla a la ciudad mas cercana. Se cae}
{5026}{}{. El terrible dolor de perder una pierna lo hace huir}
{5027}{}{ infligiendo algo de dolor extra}
{5028}{}{ causando ceguera, por desgracia para él}
{5029}{}{, y sin protección ahí, causando mucho dolor}
{5030}{}{, y cegándolo con un potente golpe}
{5031}{}{. La perdida de un ojo es demasiado para él, y se cae al suelo}
{5032}{}{, por desgracia, está demasiado ocupado sintiendo la brisa en los sesos como para notar que se aproxima la muerte}
{5033}{}{. ¡Ouch! Eso tuvo que doler}
{5034}{}{, y tampoco lleva una copa}
{5035}{}{ y sin protección, cae al suelo, gimiendo en agonía}
{5036}{}{. El dolor es demasiado para él y se desploma como un trapo}
{5037}{}{. Murmura "Mamá", mientras se le quedan los ojos en blanco}
{5100}{}{. El ataque la ha dejado fuera de combate}
{5101}{}{. La huelga provoca un dolor inmenso}
{5102}{}{ atravesando su armadura}
{5103}{}{. El ataque la deja inconsciente}
{5104}{}{. El golpe la tira al suelo}
{5105}{}{. El fuerte golpe en la cabeza la deja fuera de combate}
{5106}{}{. El golpe aplasta su sien en una fuente de sangre. Buenas noches, Gracie}
{5107}{}{, haciéndola girar en una danza macabra. La muerte es instantánea.}
{5108}{}{, causando una grave luxación en el codo}
{5109}{}{, arrancándole el brazo}
{5110}{}{, dejando un gran hematoma}
{5111}{}{, perforando el codo izquierdo con facilidad}
{5112}{}{. El brazo izquierdo y su hombro apenas siguen unidos}
{5113}{}{. Ahora ese brazo parece un muñón sangriento}
{5114}{}{, destrozando su brazo en una lluvia carmesí}
{5115}{}{. El golpe convierte su brazo derecho en carne picada}
{5116}{}{ en un potente golpe}
{5117}{}{ traspasando sus defensas}
{5118}{}{, provocando aún mas daño}
{5119}{}{ traspasa su armadura, tirándola al suelo}
{5120}{}{ sacándole el aire. Se desploma en el suelo}
{5121}{}{. Unfortunately for her, most organs have now been exposed to the light}
{5122}{}{ hiriéndola de gravedad en la pierna}
{5123}{}{, derribándola como a una mala cita a ciegas}
{5124}{}{, dejándola fuera de combate y esparciendo esa pierna por todo el suelo}
{5125}{}{, enviándole la rodilla a la ciudad más cercana. Ella toma la vía rápida al suelo}
{5126}{}{. Ella grita de dolor por su pierna rota}
{5127}{}{ infligiendo algo de dolor extra}
{5128}{}{ dejándola ciega. Hace una mueca}
{5129}{}{, y sin protección ahí, causando mucho dolor}
{5130}{}{. La herida le causa una severa ceguera, como si hubiese más de un tipo de ceguera}
{5131}{}{. Se desmaya por el potente golpe}
{5132}{}{, qué pena, no reza a sus dioses antes de reunirse con ellos}
{5133}{}{. Se lo toma como un hombre. Es decir, le duele}
{5134}{}{, tirándola al suelo}
{5135}{}{. Ya no podrá ser madre, se desploma con la cadera destrozada}
{5200}{}{. El pequeño empieza a llorar}
{5201}{}{. Inconsciente, el pequeño se desploma}
{5202}{}{. ¡Ouch!}
{5203}{}{. El golpe es fuerte, y el niño cae inconsciente}
{5204}{}{, quebrando al niño como a un muñeco de trapo}
{5205}{}{. El brazo izquierdo de este niño ahora parece un muñón}
{5206}{}{, desequilibrando al niño, que cae al suelo}
{5207}{}{, rompiéndole ese brazo con un ruidoso crujido. El niño empieza a llorar}
{5208}{}{, quebrando fácilmente ese brazo como un papel de caramelo}
{5209}{}{. El brazo derecho comienza a hincharse, como un globo}
{5210}{}{, y empieza a llorar}
{5211}{}{ en un punto sensible}
{5212}{}{. El ataque a un órgano vital derriba al niño}
{5213}{}{, derribando al niño como un juguete}
{5214}{}{. Ahora, este niño pequeño nunca experimentará la vida}
{5215}{}{, infligiendo un corte profundo}
{5216}{}{. El ataque derriba al niño, y rompe su pierna}
{5217}{}{, infligiendo un gran daño al niño}
{5218}{}{. El niño alza la vista y empieza a llorar}
{5219}{}{, que ciega al joven}
{5220}{}{, golpeando su joven nariz}
{5221}{}{. Un corte aparece sobre los ojos y la sangre empieza a manar sin control}
{5222}{}{, que le abre un ojo como una uva cuando estalla. El niño parece desconcertado}
{5223}{}{ causándole ceguera. El joven niño se cae al suelo}
{5224}{}{, el golpe continúa hasta su pequeño cerebro y lo convierte en puré}
{5225}{}{. El niño parece confuso y conmocionado}
{5226}{}{, noqueando a este joven hacia el suelo}
{5300}{}{, hiriendo al poderoso mutante}
{5301}{}{, golpeando un punto vital}
{5302}{}{, golpeando un punto vital y derribando al gigante al suelo}
{5303}{}{. El gran mutante mira alrededor un momento, y se desploma en el suelo}
{5304}{}{. La cabeza estalla como una gigante y sangrienta sandía}
{5305}{}{, hiriendo severamente al poderoso mutante}
{5306}{}{, causando que el gigante dedique un momento a maldecir al universo}
{5307}{}{, golpeando un nervio y forzando al mutante a sujetarse el brazo por el dolor}
{5308}{}{. El golpe le rompe el codo y probablemente no se sintió demasiado bien}
{5309}{}{, rompiéndole el grueso brazo y derramando sangre mutante por el suelo}
{5310}{}{, haciendo que el gigante tropiece por un momento y se derrumbe como un árbol talado}
{5311}{}{, y litros de vísceras son escupidos contra al suelo}
{5312}{}{, enviando al gigante volando al suelo}
{5313}{}{. El mutante tropieza y cae, su pierna apenas puede sostenerlo.}
{5314}{}{, golpeando una ubicación vital. El mutante estruja su pierna rota}
{5315}{}{. El dolor de una pierna rota abruma al poderoso gigante}
{5316}{}{, casi cegando al mutante}
{5317}{}{, cegando al furioso mutante}
{5318}{}{, dejando casi ciego al mutante y haciendo que pierda el equilibrio}
{5319}{}{. El mutante cegado tropieza, desprotegido para el siguiente ataque}
{5320}{}{, cegando al ahora inconsciente mutante}
{5321}{}{. Los ojos del mutante brillan un momento, y entonces se desvanecen... permanentemente}
{5400}{}{. El necrófago es sorprendido, y falla al intentar defenderse contra este ataque}
{5401}{}{. El golpe entierra a este necrófago}
{5402}{}{. La mano del necrófago aturdido vuela por los aires}
{5403}{}{, escabulléndose a través de su armadura y golpeando una articulación crítica}
{5404}{}{, escabulléndose a través de su armadura y cortándole el brazo}
{5405}{}{. El necrófago se mueve de la manera equivocada en el momento equivocado, y pierde un ojo}
{5406}{}{. El necrófago no lleva armadura ahí}
{5407}{}{, y los ojos le explotan como si fueran morcillas}
{5408}{}{, haciendo que el necrófago contemple desconcertado su momento final}
{5500}{}{, tumbando a la gran bestia en el suelo}
{5501}{}{, aturdiendo ambos cerebros y derribando al gran animal}
{5502}{}{. La vaca mutante da un fuerte quejido de sorpresa.}
{5503}{}{, rompiendo una de la patas del brahmin}
{5504}{}{, hiriendo seriamente a la vaca mutante}
{5505}{}{, penetrando con facilidad la gruesa piel de la bestia gigante}
{5506}{}{, penetrando directamente a través de ambos corazones de la vaca mutante}
{5507}{}{, cegando ambos pares de ojos con un solo golpe}
{5508}{}{, cegando ambas cabezas y aturdiendo a la vaca mutante}
{5509}{}{, cegando por completo al brahmin y derribándolo}
{5510}{}{, el gran bovino mutante se tambalea un momento}
{5511}{}{. El brahmin se agita con rabia}
{5512}{}{. El brahmin resopla de dolor}
{5513}{}{. El brahmin está enfadadísimo por tu ataque devastador en las ubres}
{5600}{}{, enviando al escorpión rad a volar}
{5601}{}{, separando la cabeza del caparazón}
{5602}{}{, dañando seriamente la cola}
{5603}{}{, dejando una importante herida en sus garras}
{5604}{}{. El golpe se mete entre las grietas del duro caparazón del escorpión rad}
{5605}{}{, atravesando el duro caparazón sin detenerse}
{5606}{}{, atravesando la coraza natural y derribando al escorpión rad}
{5607}{}{. El escorpión rad expira de causa "natural", como es la pérdida de órganos internos}
{5608}{}{, haciendo volar al escorpión y rompiendo algunas de sus patas}
{5609}{}{. El ataque corta la desprotegida articulación de la pierna, amputándola}
{5610}{}{, hiriendo gravemente y cegando a la criatura mutante}
{5611}{}{, penetrando casi hasta el cerebro. Esto sí que es aplastar bichos}
{5612}{}{, penetrando casi hasta el cerebro y cegando a la criatura}
{5613}{}{. El ataque es diabólico y demasiado sofisticado para esta criatura tan simple}
{5614}{}{. Si fuese humano, dirías que lo has cabreado}
{5615}{}{, golpeando a la insensible y pobre criatura}
{5616}{}{, clavando el cerebro al suelo}
{5700}{}{. El cráneo del roedor hace varios sonidos enfermizos}
{5701}{}{, aplastando el cráneo del roedor como una bolsa de papel mojado}
{5702}{}{, y la pata izquierda ahora parece un poco más suelta}
{5703}{}{. La pata izquierda de la rata vuela por los aires}
{5704}{}{. La pata derecha está muy dañada}
{5705}{}{, reduciendo la garra derecha a una fina pasta roja}
{5706}{}{. La rata ha sido seriamente dañada en este ataque y chilla de dolor}
{5707}{}{, hiriendo gravemente a la rata y dejándola fuera de combate}
{5708}{}{, aplastando a la rata contra el suelo}
{5709}{}{, arrancándole fácilmente la pata derecha}
{5710}{}{, haciendo un gran agujero en su pata izquierda}
{5711}{}{, haciendo más daño por darle en un punto sensible}
{5712}{}{, enviando a esta criatura a la gran ratonera celestial}
{5800}{}{, el flotante cae al suelo}
{5801}{}{, el flotante cae el suelo al parecer sin vida}
{5802}{}{, con serias consecuencias para su existencia}
{5803}{}{, aturdiendo a la criatura repugnante}
{5804}{}{, golpeando un punto sensible y aturdiendo al nómada}
{5805}{}{. El golpe hace que el nómada se estremezca violentamente en un chorro carmesí
}
{5806}{}{, causando el golpe una violenta reacción en la criatura}
{5807}{}{. El nómada de repente estalla en llamas}
{5808}{}{ luego se sacude salvajemente y tiembla como si fuese a reventar}
{5809}{}{, golpeando en un punto sensible}
{5810}{}{. La criatura está obviamente agitada}
{5900}{}{, abandonado, el centauro se derrumba aturdido}
{5901}{}{ el golpe alcanzó un punto crítico}
{5902}{}{, causando un masivo fallo neurálgico}
{5903}{}{, aturdiéndolo con tu violento ataque}
{5904}{}{, rompiéndole el brazo}
{5905}{}{ golpeando un punto crítico, y destrozando el brazo}
{5906}{}{, derribando a la criatura y rompiéndole la pata}
{5907}{}{, aturdiendo al centauro al tiempo que es derribado con una pata destrozada}
{5908}{}{, blinding one head and liquefying the other}
{5909}{}{, sorprendiendo al centauro. Cegado, se tropieza}
{5910}{}{, sorprendiendo al centauro. Se desploma}
{5911}{}{, sorprendiendo al centauro. Se desploma en una pila de sustancia pegajosa}
{5912}{}{. El ataque no fue tan eficaz como podría haber sido}
{6000}{}{, infligiendo cierto daño estructural}
{6001}{}{, vuelan chispas y el robot pierde por un momento el control}
{6002}{}{, golpeando un componente crítico y forzando al robot a perder el control}
{6003}{}{, golpeando un componente crítico y causando un mal funcionamiento masivo}
{6004}{}{. El robot intenta compensar}
{6005}{}{. El robot se esfuerza en compensar}
{6006}{}{, golpeando alguna pieza clave y causando graves daños}
{6007}{}{, provocando graves daños estructurales}
{6008}{}{, golpeando un componente crítico y causando daños severos}
{6009}{}{. El robot se estremece bajo este intenso ataque}
{6010}{}{, desmantelando al robot}
{6011}{}{. El robot intenta compensar el golpe, pero falla, cayendo al suelo}
{6012}{}{. El robot cede ante la presión, cayendo al suelo}
{6013}{}{, rompiendo las lentes de los sensores}
{6100}{}{, tirando al perro al suelo}
{6101}{}{, justo en el hocico}
{6102}{}{. El perro cae, pero todavía sigue respirando}
{6103}{}{, haciendo toser al animal una chorro de sangre}
{6104}{}{, rompiendo su pata}
{6105}{}{, rompiendo su pata. El animal intenta seguir en pie, pero no lo logra}
{6106}{}{. El animal cegado aúlla de dolor}
{6107}{}{, castrando al pobre animal}
{6200}{}{, derribando al insecto mutado}
{6201}{}{, que se desploma}
{6202}{}{. La mantis está pensando si merece la pena vivir}
{6203}{}{, rompiéndole la extremidad}
{6204}{}{, haciendo que la mantis lama sus heridas. Sujeta el miembro de forma extraña}
{6205}{}{, traspasando su caparazón}
{6206}{}{. La mantis chilla y tiembla horriblemente}
{6207}{}{, lo que hace que la mantis caiga. Un miembro queda extrañamente retorcido}
{6208}{}{, triturando sus alas}
{6209}{}{, atravesando el armazón de quitina y lanzando a la mantis por los aires}
{6210}{}{, cegando al insecto con un golpe certero}
{6300}{}{. Incluso esta bestia parece desconcertada por ese impresionante ataque}
{6301}{}{, pasando las enormes garras para golpear al monstruo. La Garra Mortal se agita y gruñe}
{6302}{}{. Has causado graves daños en los ojos de la Garra Mortal}
{6400}{}{, breaking past his bio-organic defenses}
{6401}{}{, causing him some serious grief}
{6402}{}{, breaking past his bio-organic defenses and putting the pressure on him}
{6403}{}{, stunning him with a solid offensive plan}
{6404}{}{, causing an overload of cataclysmic proportions in his systems}
{6405}{}{. Still, the attack against him seems to do less damage than it should have}
{6406}{}{. The blow gets by his bio-organic defenses, actually blinding him}
{6500}{}{. Mañana tendrás dolor de cabeza, si es que aún vives}
{6501}{}{. Tu armadura no te brinda protección contra este golpe bien dirigido}
{6502}{}{. Sientes dolor durante un momento, y entonces todo se vuelve oscuro...}
{6503}{}{, traspasando tu armadura. El golpe te derriba}
{6504}{}{, el golpe hace que se te oscurezca la visión. Después de un momento, te das cuenta de que no volverás a ver}
{6505}{}{. Consigues una bonita vista de tu cuerpo cuando tu cabeza vuela por los aires}
{6506}{}{. Sorprendentemente, el daño no se siente peor de lo normal.}
{6507}{}{, aturdiéndote por un momento}
{6508}{}{. Sientes dolor}
{6509}{}{. El ataque te deja el brazo inútil}
{6510}{}{, traspasando tu armadura. El golpe rompe los huesos de tu brazo como madera seca}
{6511}{}{, traspasando tu armadura. Tu brazo ahora cuelga inerte}
{6512}{}{. La contusión se verá bien, y tus cicatrices servirán de tema de conversación}
{6513}{}{, aplastando tus órganos internos. Todo lo que puedes hacer es escupir sangre}
{6514}{}{, haciéndote caer redondo al suelo}
{6515}{}{, haciéndote volar y rompiéndote la pierna}
{6516}{}{, derritiendo tu armadura. El golpe te tira al suelo y daña gravemente tu rodilla}
{6517}{}{. El dolor de la pierna rota te hace desmayar}
{6518}{}{. El doloroso golpe te hace estremecer, pero poco más}
{6519}{}{. Por desgracia para ti, también produce una inmediata pérdida de visión}
{6520}{}{. Te toma un momento limpiar la sangre de tus ojos}
{6521}{}{, traspasando tu armadura. Te quedas atónito cuando te das cuenta de que ya no puedes ver
}
{6522}{}{. Sientes una extraña sensación en tu cabeza. Te das cuenta de que es una muerte cerebral inminente}
{6523}{}{, haciéndote temblar}
{6524}{}{. Te echas las manos a la ingle y caes al suelo retorciéndote de dolor}
{6525}{}{. El dolor es suficiente para hacer que te derrumbes en el suelo. Ouch}
{6526}{}{. No hay bastantes palabras en el universo para describir el dolor que sientes en estos momentos}
