{100}{}{CARGAR PARTIDA}
{101}{}{ESCOGE UNA RANURA DE CARGA RAPIDA}
{102}{}{GUARDAR PARTIDA}
{103}{}{ESCOGE UNA RANURA DE GUARDADO RAPIDA}
{104}{}{SELECT}
{105}{}{CANCELAR}
{106}{}{Error al cargar lista de partidas guardadas!}
{107}{}{Directorio de partidas guardadas:}
{108}{}{No existe o esta corrupto.}
{109}{}{RANURA DE GUARDADO}
{110}{}{RANURA DE GUARDADO}
{111}{}{- VACIO -}
{112}{}{- ARCHIVO CORRUPTO -}
{113}{}{- VERSION ANTIGUA -}
{114}{}{This save slot is empty.}
{115}{}{Error!}
{116}{}{Version antigua.}
{117}{}{ENE}
{118}{}{FEB}
{119}{}{MAR}
{120}{}{ABR}
{121}{}{MAY}
{122}{}{JUN}
{123}{}{JUL}
{124}{}{AGO}
{125}{}{SEP}
{126}{}{OCT}
{127}{}{NOV}
{128}{}{DIC}
{129}{}{Nivel}
{130}{}{DESCRIPCION}
{131}{}{La partida ya existe! Sobreescribir?}
{132}{}{Error al guardar partida!}
{133}{}{Imposible guardar partida.}
{134}{}{Error al cargar partida!}
{135}{}{Imposible cargar partida.}
{136}{}{El archivo de la partida guardada es una versi¨®n antigua.}
{137}{}{Mapa}
{140}{}{Partida guardada.}
{141}{}{Partida cargada.}
{200}{}{SIN USAR}
{201}{}{SIN USAR}
