{0}{}{GUARDAR PARTIDA}
{1}{}{CARGAR PARTIDA}
{2}{}{PREFERENCIAS}
{3}{}{SALIR}
{4}{}{VALE}
{100}{}{PREFERENCIAS}
{101}{}{DIFICULTAD DEL JUEGO}
{102}{}{DIFICULTAD DEL COMBATE}
{103}{}{NIVEL DE VIOLENCIA}
{104}{}{RESALTAR OBJETIVOS}
{105}{}{SIN USAR}
{106}{}{MENSAJES EN COMBATE}
{107}{}{INJURIAS EN COMBATE}
{108}{}{FILTRO DE LENGUAJE}
{109}{}{CORRER}
{110}{}{SUBTITULOS}
{111}{}{RESALTAR OBJETOS}
{112}{}{VELOCIDAD COMBATE}
{113}{}{MENSAJES EN COMBATE}
{114}{}{VOL. MAESTRO}
{115}{}{VOL. MUSICA/PELICULA}
{116}{}{VOL. EFECTOS DE SONIDO}
{117}{}{VOL. DIALOGOS}
{118}{}{BRILLO/CONTRASTE}
{119}{}{SENSIBILIDAD DEL RATON}
{120}{}{POR DEFECTO}
{121}{}{CANCELAR}
{122}{}{Afecta la velocidad del jugador}
{123}{}{SIN USAR}
{201}{}{On}
{202}{}{Off}
{203}{}{Facil}
{204}{}{Normal}
{205}{}{Dificil}
{206}{}{Debil}
{207}{}{Normal}
{208}{}{Duro}
{209}{}{Normal}
{210}{}{Mas rapido}
{211}{}{Prolijo}
{212}{}{Breve}
{213}{}{Solo apuntar}
{214}{}{Ninguno}
{215}{}{Minimo}
{216}{}{Minima sangre}
{217}{}{ segundos.}
{218}{}{Mas rapido}
{219}{}{Siempre}
{220}{}{Mucho}
{221}{}{Bajo}
{222}{}{Alto}
{223}{}{Minimo}
{224}{}{Ancho}
{300}{}{PAUSA}
{301}{}{PAUSA}
{1000}{}{SIN USAR}
{1001}{}{SIN USAR}
