{200}{}{Caverna, Puerta del Refugio}
{201}{}{Entrada de la Caverna, Zona médica}
{202}{}{Aposentos}
{203}{}{Library, Supplies, Command}
{210}{}{Choza}
{211}{}{Entrada a Cueva}
{212}{}{Aposentos}
{213}{}{Library, Supplies, Command}
{220}{}{Entrada al Mapa}
{221}{}{Campo de Cultivo}
{222}{}{Corral de Brahmines}
{223}{}{Cuevas de los Escorpiones Rad}
{230}{}{Entrada al Mapa}
{231}{}{Generador}
{232}{}{Casino}
{240}{}{Campo base}
{250}{}{Hotel de la perdición}
{251}{}{Sala de los Difuntos}
{252}{}{El almacén de agua}
{260}{}{Integrante de Caravana}
{261}{}{Casino de Ciudad Vertedero}
{262}{}{¿Dónde está Hightower?}
{263}{}{Ciudad Antigua}
{264}{}{Guardia de los Mercaderes de Agua}
{265}{}{Carne de Garra Mortal}
{270}{}{Entrada}
{271}{}{Nivel 1}
{272}{}{Nivel 2}
{273}{}{Nivel 3}
{274}{}{Nivel 4}
{280}{}{Entrada}
{281}{}{Fortaleza Nivel 1}
{282}{}{Fortaleza Nivel 2}
{283}{}{Tanques Nivel 1}
{284}{}{Tanques Nivel 2}
{290}{}{Cráter}
{291}{}{Nivel 1}
{292}{}{Nivel 2}
{293}{}{Nivel 3}
{294}{}{Nivel 4}
{295}{}{Nivel 5}
{296}{}{Nivel 6}
{300}{}{Adytum}
{301}{}{Centro de la ciudad}
{302}{}{Biblioteca}
{303}{}{Fortaleza}
{304}{}{Almacén}
{310}{}{Entrada}
{311}{}{Interior}
{500}{}{Estás viendo a un Sargento Supermutante.}
{501}{}{Ruinas}
{1000}{}{Desierto}
{1001}{}{Montañas}
{1002}{}{Ciudad}
{1003}{}{Costa}
{1004}{}{Desconocido}
