{100}{}{You see one of Hightower's guards.}
{101}{}{You better leave. Daren Hightower doesn't take visitors.}
{102}{}{Your company is not desired.}
{103}{}{Leave!}
{104}{}{You're not allowed here.}
{105}{}{Go away, or you'll regret it.}
{106}{}{This house is off limits to the likes of you.}
{107}{}{What the... Get 'em!}
{108}{}{You made a big mistake coming in here!}
{109}{}{What are you doing here? You're dead meat.}
{110}{}{Mmmm, looks good.}
{111}{}{Is that brahmin I smell?}
{112}{}{Hook it into my veins!}
{113}{}{Anything in the fridge?}
{114}{}{How much longer?}
{115}{}{I'm hungry.}
{116}{}{Is it almost ready?}
{117}{}{I'm going to pass out!}
