{101}{}{You see several odd-looking floating creatures...}
{102}{}{You are suddenly attacked by a swarm of mutated manti!}
{103}{}{You are suddenly attacked by a swarm of mutated manti!}
{104}{}{You see a group of peasants being attacked by raiders!}
{105}{}{A swarm of rats is rapidly approaching!}
{106}{}{You see a few people out fishing.}
{107}{}{There is a grisly corpse nearby that's been partially eaten. You've just lost your appetite.}
{200}{}{You stumble upon some water pools.}
{201}{}{Out of dire thirst, you drink some water... It doesn't taste so good.}
{202}{}{The water looks highly radioactive and foul.}
{203}{}{Ahhh...}
{204}{}{Arrgg...}
{205}{}{Yuck!}
{1000}{}{You earn }
{1001}{}{ experience for successful use of your Outdoorsman skill.}
{1002}{}{Encounter: "}
{1003}{}{"}
{1004}{}{. Do you wish to engage?}
{1005}{}{Yes.}
{1006}{}{No.}
{1007}{}{}
{1008}{}{}
{1009}{}{}
{1010}{}{You are ambushed by a blood-thirsty bounty hunter and his goon squad!}
