{100}{}{Du siehst: Abel.}
{101}{}{Du siehst einen riesigen Mutanten.}
{102}{}{Du darfst nicht hier sein.}
{103}{}{Hng.}
{104}{}{Natürlich nicht. Ich bin hier, um dich zu töten!}
{105}{}{Warum sagst du das?}
{106}{}{Oh, ja? Deine Mutter!}
{107}{}{Pik!}
{108}{}{Ich werde dir innen Arsch treten, wenn du das nochmal sagst!}
{109}{}{Pik! Pik!}
{110}{}{Oh, jetzt kriegst du ein paar!}
{111}{}{Du Mensch. Ich Mutant. Mutant töten Mensch.}
{112}{}{Wie machst du das? Was ist mit dem Kraftfeld?}
{113}{}{Abel kümmert sich darum. Dann Abel dir in den Arsch treten!}
{114}{}{Kinder nicht erlaubt sein hier. Das Ort von Mutanten. Geh weg.}
{115}{}{Hng!}
{116}{}{Ich muss durch dieses Kraftfeld kommen. Bitte deaktiviere es.}
{117}{}{Nein.}
{118}{}{Du wieder. Abel dir Arsch treten!}
{970}{}{Ich Abel.}
{971}{}{Ich Abel.}
{972}{}{Ich Abel.}
{973}{}{Ich Abel.}
{974}{}{Ich Abel.}
{975}{}{Ich Abel.}
{976}{}{Ich Abel.}
{977}{}{Ich Abel.}
{978}{}{Ich Abel.}
{979}{}{Ich Abel.}
{980}{}{Hng.}
{981}{}{Warum sagst du das?}
{982}{}{Pik!}
{983}{}{Uh... hä?}
{984}{}{Hmm?}
{985}{}{Was sagst du?}
{986}{}{Was, hmm?}
{987}{}{Uh... nicht ich wissen.}
{988}{}{Nicht ich wissen.}
{989}{}{Was das sein?}
{990}{}{}
{991}{}{}
{992}{}{}
{993}{}{}
{994}{}{}
{995}{}{}
{996}{}{}
{997}{}{}
{998}{}{}
{999}{}{}
