{100}{}{From the look of things, they can't have traveled very far. They must have a lair nearby.}
{101}{}{They appear to have traveled here from somewhere nearby.}
{102}{}{It looks like they traveled from somewhere far north of here.}
{103}{}{Apparently, they were just wandering the wastes.}
{104}{}{You have stumbled into a fierce battle between radscorpions and mole rats.}
{105}{}{AMBUSH!!!}
{106}{}{You have stumbled upon a large pack of radscorpions!}
{107}{}{You have stumbled upon a pack of radscorpions.}
{108}{}{You have stumbled upon a family of mole rats.}
{109}{}{You manage to avoid a serious case of dehydration by searching for water. The search takes an additional hour.}
{110}{}{You manage to avoid a serious case of dehydration by searching for water. The search takes an additional }
{111}{}{ hours.}
{112}{}{You avoid dehydration due to your supply of fluids, emptying }
{113}{}{ points of health damage.}
{114}{}{Your water supply runs out, }
{115}{}{ hours fails to locate any water. Dehydration sets in, causing you }
{116}{}{ water flask}
{117}{}{ water flasks}
{118}{}{flask}
{119}{}{ flask.}
{120}{}{You search for water in the high desert landscape for }
{121}{}{ hours, but you do not find enough to fully satisfy your thirst. You have sustained 1 point of health damage.}
{122}{}{You search for water in the high desert landscape for }
{123}{}{ hours, but you do not find enough to fully satisfy your thirst. You have sustained }
{124}{}{ flasks.}
{125}{}{You avoid dehydration due to your supply of water, emptying }
{126}{}{You've run into some radscorpions hunting mole rats.}
{127}{}{Skinny hostile humanoids with greenish skin approach.}
{128}{}{Junk and rocks are scattered about. You wonder if anything of value could remain...}
{129}{}{A lone radscorpion ambushes you!}
{130}{}{You note a partially-eaten corpse here.}
{131}{}{STAMPEDE!!!}
{132}{}{You stumble onto a very large pack of radscorpions!}
{133}{}{Raiders ambush you!}
{134}{}{A pack of nasty radscorpions strikes from the desert!}
{135}{}{You encounter a group of guardsmen on patrol.}
{136}{}{You come across a merchant with several guards.}
{137}{}{You see a peasant herding several brahmin.}
{138}{}{ You refill your }
{139}{}{Radscorpions hunt mole rats among the ruined city walls.}
{140}{}{ Nuka-colas}
{141}{}{ Nuka-cola}
{142}{}{ beer}
{143}{}{Raiders!!!}
{144}{}{You have stumbled into a large gathering of mole rats.}
{145}{}{You encounter a band of wild radscorpions.}
{146}{}{You encounter some peasants under attack.}
{147}{}{You manage to avoid dehydration by searching for water. The search takes 1 hour.}
{148}{}{ point of health damage.}
{149}{}{ beers}
{150}{}{ bottle of booze}
{151}{}{ bottles of booze}
{152}{}{Resorting to alcohol reduces your }
{153}{}{Strength}
{154}{}{Endurance}
{155}{}{Strength and Endurance}
{156}{}{ by 1 point.}
{157}{}{ by 2 points.}
{158}{}{ by 1 point each.}
{159}{}{flasks}
{160}{}{ with the drinkable water.}
{161}{}{Your supply of fluids runs out, }
{162}{}{and your search of }
{163}{}{but you manage to avoid dehydration by searching for water. The search takes }
{164}{}{1 hour.}
{165}{}{You earn }
{166}{}{ experience for successful use of your Outdoorsman skill.}
{167}{}{}
{168}{}{}
{169}{}{You stumble into a family of radscorpions.}
{170}{}{You come across a traveling merchant and guards.}
{171}{}{You encounter a dead traveler.}
{172}{}{You have stumbled across some items laying on the ground.}
{173}{}{You spot the remains of a caravan, being looted by raiders.}
{174}{}{You come across the remnants of a merchant and his guards.}
{175}{}{Du begegnest einem Reisenden.}
{176}{}{You have stumbled across a small patch of ruined and deserted buildings.}
{187}{}{}
{188}{}{}
{189}{}{}
{190}{}{}
{191}{}{}
{192}{}{}
{193}{}{}
{194}{}{}
{195}{}{}
{196}{}{Radscorpions, incoming!}
{197}{}{Uh-oh... a raiding party!}
{198}{}{You see a lone raider in the distance.}
{199}{}{You come upon the remains of a battlefield, with bodies strewn about.}
{200}{}{Radscorpions, incoming!}
{201}{}{}
{202}{}{}
{203}{}{}
{204}{}{}
{205}{}{}
{206}{}{}
{207}{}{}
{208}{}{}
{209}{}{}
{210}{}{}
{211}{}{}
{212}{}{}
{213}{}{}
{214}{}{}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}
{220}{}{}
{221}{}{}
{222}{}{}
{223}{}{You spot a wandering pack of wild coyotes.}
{224}{}{You notice several individuals scouting about.}
{225}{}{You come across a small party of merchants and guards.}
{226}{}{You see a small war going on - men versus mutants!}
{227}{}{A tremendous horde of radscorpions is coming this way!}
{228}{}{}
{229}{}{}
{230}{}{}
{231}{}{}
{232}{}{}
{233}{}{}
{234}{}{}
{235}{}{}
{236}{}{}
{237}{}{}
{238}{}{}
{239}{}{}
{240}{}{}
{241}{}{}
{242}{}{}
{243}{}{}
{244}{}{}
{245}{}{}
{246}{}{}
{247}{}{}
{248}{}{}
{249}{}{}
{250}{}{Several men in Power Armor are approaching you.}
{251}{}{You see a group of merchants and guards.}
{252}{}{You see a vicious battle underway between several desert raiders and a group of men in Power Armor.}
{253}{}{You see several mutants exploring a patch of hostile ground.}
{254}{}{You see some strange creatures ahead...}
{255}{}{You find some items.}
{256}{}{A patrol unit of Super Mutants is passing close by!}
{257}{}{You spot the ruins of a tiny village.}
{258}{}{}
{259}{}{}
{260}{}{}
{261}{}{}
{262}{}{}
{263}{}{}
{264}{}{}
{265}{}{}
{266}{}{}
{267}{}{}
{268}{}{}
{269}{}{}
{270}{}{}
{271}{}{}
{272}{}{}
{273}{}{}
{274}{}{}
{275}{}{}
{276}{}{}
{277}{}{}
{278}{}{}
{279}{}{Ahead you can see junk strewn about the sands.}
{280}{}{You stumble upon a Super Mutant war party.}
{281}{}{You stumble upon a pack of bizarre creatures.}
{282}{}{You stumble across a pack of hungry radscorpions.}
{283}{}{You feel nauseous, and the air seems to waver with heat. A mutated creature suddenly approaches!}
{284}{}{You have stumbled across a few bizarre mutant creatures.}
{285}{}{You encounter something out of an old Sci-Fi movie.}
{286}{}{The Deathclaw!!}
{287}{}{You stumble into a migrating pack of radscorpions. They seem to be fleeing from...}
{288}{}{You encounter a mutated creature of the desert.}
{289}{}{}
{290}{}{}
{291}{}{}
{292}{}{}
{293}{}{}
{294}{}{}
{295}{}{}
{296}{}{}
{297}{}{}
{298}{}{}
{299}{}{You see several radscorpions some distance away.}
{300}{}{You run across a ragged peasant.}
{301}{}{You encounter a mole rat.}
{302}{}{A young Deathclaw seems to think you are lunch.}
{303}{}{You stumble into a migrating pack of radscorpions.}
{304}{}{}
{305}{}{You come across what's left of merchant Duc's hostile guards.}
{306}{}{A patrol unit of mutants is passing close by. Along with them are some strange creatures!}
{307}{}{You are ambushed by a small Super Mutant war party.}
{308}{}{Looks like you've stumbled into a vicious gang war!}
{309}{}{A group of hostile gangers bursts forth!}
{310}{}{A small group of raiders attack!}
{311}{}{A small group of gangers attack!}
{312}{}{You are suddenly attacked by rats!}
{313}{}{You are suddenly attacked by a swarm of mutated manti!}
{314}{}{Hey! They're really out there.}
{315}{}{You see an overturned truck in the distance.}
{316}{}{You stumble across some wrecked cars in the middle of the wasteland.}
{317}{}{To the northeast you spot a police box.}
{318}{}{You come across a heard of wild brahmin. You feel there is something wrong...}
