{1000}{}{I didn't sign up for this}
{1001}{}{I don't get paid enough for this}
{1002}{}{Fall back!}
{1003}{}{Regroup!}
{1004}{}{I'm not dying for this!}
{1005}{}{That's enough for me}
{1006}{}{I'm going to teach you a lesson}
{1007}{}{You just made a big mistake!}
{1008}{}{We don't like your kind around here!}
{1009}{}{I don't like your kind}
{1010}{}{That was your last mistake}
{1011}{}{Blood resolves what words can't}
{1012}{}{Eat this}
{1013}{}{Think fast!}
{1014}{}{Now you die!}
{1015}{}{Second one today...}
{1016}{}{I enjoy a good workout}
{1017}{}{You are going to die.}
{1018}{}{Let's see how tough you are...}
{1019}{}{Punk}
{1020}{}{Attack!}
{1021}{}{Let's see how you like this}
{1022}{}{Too slow}
{1023}{}{I've been doing this for years, punk}
{1024}{}{You ain't good enough}
{1025}{}{That was your last mistake}
{1026}{}{Amateur}
{1027}{}{Is that all you got?}
{1028}{}{Ow! You son of a bitch}
{1029}{}{I'm gonna kill you for that}
{1030}{}{I think I might have a concussion}
{1031}{}{That's not good}
{1032}{}{Damn, my arm's busted!}
{1033}{}{Min arm!}
{1034}{}{GAH! I think it's broken...}
{1035}{}{Fuck that smarts}
{1036}{}{Min arm!}
{1037}{}{Ooph!}
{1038}{}{Ow}
{1039}{}{[Gasp!]}
{1040}{}{My ribs!}
{1041}{}{My knee!}
{1042}{}{You're gonna pay for that!}
{1043}{}{My leg's going numb}
{1044}{}{Fuck, you broke it!}
{1045}{}{I hope it doesn't buckle}
{1046}{}{My knee!}
{1047}{}{Jag kan inte se!}
{1048}{}{My eye!}
{1049}{}{Fuck! At least I have another one}
{1050}{}{Åååååå, mitt skrev!}
{1051}{}{Fuck, nice shot}
{1052}{}{You fight dirty}
{1053}{}{Urp!}
{1054}{}{Oof!}
{1055}{}{That hurt}
{1100}{}{Reinforcements!}
{1101}{}{Discretion is the better part of valor}
{1102}{}{Medic!}
{1103}{}{Retreat! Retreat!}
{1104}{}{Fall back! Fall back!}
{1105}{}{You may have won the battle...}
{1106}{}{Time to put my training to the test!}
{1107}{}{I'm gonna fucking end you}
{1108}{}{I'm gonna teach you some manners}
{1109}{}{You're history!}
{1110}{}{Attack!}
{1111}{}{Let's bury this loser!}
{1112}{}{Take this!}
{1113}{}{Now I have you!}
{1114}{}{Now you die!}
{1115}{}{How do you like this?}
{1116}{}{Paid for your coffin yet?}
{1117}{}{Shouldn't start what you can't finish}
{1118}{}{You better pray to the gods!}
{1119}{}{Time to die!}
{1120}{}{This will be easy}
{1121}{}{See you in hell}
{1122}{}{Ha! Seriously?}
{1123}{}{Is that the best you can do?}
{1124}{}{C'mon loser. Gimme a fight!}
{1125}{}{Try aiming next time}
{1126}{}{Civilian}
{1127}{}{Figures.}
{1128}{}{Uugghh... can't think straight}
{1129}{}{My face!}
{1130}{}{Du bröt min näsa!}
{1131}{}{You broke my arm!}
{1132}{}{A busted arm is not stopping me!}
{1133}{}{I'm going to get you for that}
{1134}{}{You broke it!}
{1135}{}{I didn't need that elbow anyway}
{1136}{}{Good thing I'm a lefty}
{1137}{}{Emph! That didn't hurt a bit}
{1138}{}{Uck!}
{1139}{}{You're gonna regret that!}
{1140}{}{Ooph! You'll pay for that}
{1141}{}{That was a lucky shot}
{1142}{}{You will pay for that!}
{1143}{}{That kind of wound will not stop me!}
{1144}{}{Ow, my leg!}
{1145}{}{Take my leg, I'll take your life}
{1146}{}{You will pay!}
{1147}{}{I'm blind!}
{1148}{}{My eyes are burning!}
{1149}{}{Jag kan inte se!}
{1150}{}{Ooo, my groin!}
{1151}{}{Ack!}
{1152}{}{Oof!}
{1153}{}{I...can't...breathe...}
{1154}{}{Son of a bitch}
{1155}{}{You punk...}
{1200}{}{Gotta get outta here!}
{1201}{}{I'll be back...}
{1202}{}{You ain't killing me today!}
{1203}{}{Later punk!}
{1204}{}{You ain't seen the last of me!}
{1205}{}{You'll pay for this - later!}
{1206}{}{You're history!}
{1207}{}{Fresh meat...}
{1208}{}{I'm gonna dance on your grave}
{1209}{}{Everybody! It's target practice!}
{1210}{}{Bleed, bleed, bleed!}
{1211}{}{I'm going to enjoy this...}
{1212}{}{Gonna sell your corpse to Doc Morbid}
{1213}{}{Don't bother screaming for mercy...}
{1214}{}{This is the best part...}
{1215}{}{Your shoe's untied}
{1216}{}{Gonna feed you to the dogs}
{1217}{}{Shouldn't start what you can't finish}
{1218}{}{Hope you don't die too quickly.}
{1219}{}{Only one of us is walking away}
{1220}{}{Dö!}
{1221}{}{I eat punks like you for breakfast}
{1222}{}{I'm gonna feed you to my pet iguana}
{1223}{}{The last thing you'll see is my grinnin' face}
{1224}{}{This is my favorite job}
{1225}{}{You're a joke}
{1226}{}{Is that the best you can do?}
{1227}{}{Whatever}
{1228}{}{Whew, that was close}
{1229}{}{För långsamt!}
{1230}{}{Loser}
{1231}{}{Not in the face!}
{1232}{}{Aj!}
{1233}{}{Du bröt min näsa!}
{1234}{}{Ow, my arm!}
{1235}{}{You broke my arm!}
{1236}{}{I can get it reattached}
{1237}{}{A busted arm ain't stopping me!}
{1238}{}{You broke my arm!}
{1239}{}{I can't feel my fingers...}
{1240}{}{Ow, my ribs!}
{1241}{}{That was your one free shot. Time to die.}
{1242}{}{I'm gonna make you pay for that}
{1243}{}{Mitt ben!}
{1244}{}{You're gonna pay for that!}
{1245}{}{I can still kill you with a limp}
{1246}{}{Mitt ben!}
{1247}{}{Argh!}
{1248}{}{Not enough to stop me, pal}
{1249}{}{Argh! My eyes!}
{1250}{}{Mitt öga! Det där ska du få betala för!}
{1251}{}{Fuck! You're history}
{1252}{}{Åååååå, mitt skrev!}
{1253}{}{Ooo! I gotta learn that move...}
{1254}{}{Right in the nuts...}
{1255}{}{Urp!}
{1256}{}{My girlfriend won't be happy about this}
{1257}{}{Ow! I'm gonna kill you for that!}
{1300}{}{Did you hear someone call my name?}
{1301}{}{}
{1302}{}{Hjälp!}
{1303}{}{Aaaaahhhh!}
{1304}{}{Run away!}
{1305}{}{}
{1306}{}{I'm gonna make you look like a cracked pretzel}
{1307}{}{Look! Your shoe's untied!}
{1308}{}{Wait 'til I get you...}
{1309}{}{}
{1310}{}{I'm gonna give you such a walloping}
{1311}{}{}
{1312}{}{Take this!}
{1313}{}{I have you now!}
{1314}{}{I have you now!}
{1315}{}{How do you like this?}
{1316}{}{Eat this}
{1317}{}{This'll be a life changing experience}
{1318}{}{I'm not going to regret this, am I?}
{1319}{}{}
{1320}{}{}
{1321}{}{}
{1322}{}{Ha, missed me!}
{1323}{}{Nyah, nyah!}
{1324}{}{Ha!}
{1325}{}{Nyah, nyah!}
{1326}{}{Watta maroon!}
{1327}{}{Can't touch me}
{1328}{}{Watch the hair!}
{1329}{}{My teef! I loft a toof!}
{1330}{}{My teef! My teef!}
{1331}{}{Ow, my arm!}
{1332}{}{Aj!}
{1333}{}{Ow, quit it!}
{1334}{}{Ow, my arm!}
{1335}{}{Aj!}
{1336}{}{Ow, quit it!}
{1337}{}{I don't want to be a lefty!}
{1338}{}{Ooph!}
{1339}{}{That wasn't very nice}
{1340}{}{You may regret doing that, I sure did}
{1341}{}{I think I'm gonna faint}
{1342}{}{Watta think I am, a punching bag?}
{1343}{}{You're not very nice}
{1344}{}{Ow, my leg!}
{1345}{}{Ow! Don't do that!}
{1346}{}{!}
{1347}{}{Ow, my leg!}
{1348}{}{Ow! You're mean!}
{1349}{}{}
{1350}{}{Why is it so dark?}
{1351}{}{Where'd everybody go?}
{1352}{}{Ouch, my retina!}
{1353}{}{Åååååå, mitt skrev!}
{1354}{}{My groin is the groin of fire!}
{1355}{}{My groin is the groin of fire!}
{1356}{}{I...can't...breathe...}
{1357}{}{}
{1358}{}{Smärtan, smärtan...}
{1400}{}{Outta here!}
{1401}{}{Hej då!}
{1402}{}{Aaaaahhhh!}
{1403}{}{Fuck this}
{1404}{}{I'm out}
{1405}{}{See ya 'round}
{1406}{}{Gonna fuck you up}
{1407}{}{You're history!}
{1408}{}{Playtime's over}
{1409}{}{Somebody's dyin'}
{1410}{}{Deal me in}
{1411}{}{Let's go!}
{1412}{}{Take this!}
{1413}{}{Dö!}
{1414}{}{Loser}
{1415}{}{Punk}
{1416}{}{Eat it, whore}
{1417}{}{Hope this hurts}
{1418}{}{Say a prayer}
{1419}{}{Don't flinch}
{1420}{}{I'll bury you}
{1421}{}{You're dead!}
{1422}{}{Missed me!}
{1423}{}{Not impressed}
{1424}{}{Pathetic}
{1425}{}{You're slow}
{1426}{}{You're useless}
{1427}{}{Ha!}
{1428}{}{Fuck that hurt!}
{1429}{}{My face!}
{1430}{}{Ow! My nose...}
{1431}{}{Aj!}
{1432}{}{Ow! My arm!}
{1433}{}{Ow! You broke it!}
{1434}{}{Not again...}
{1435}{}{Min arm!}
{1436}{}{Payback time}
{1437}{}{Aj!}
{1438}{}{Ouch!}
{1439}{}{Ooph!}
{1440}{}{[Gasp!]}
{1441}{}{Oof!}
{1442}{}{Ugh!}
{1443}{}{Aj!}
{1444}{}{Ow! My knee!}
{1445}{}{Ow! My leg!}
{1446}{}{Skit!}
{1447}{}{Mitt ben!}
{1448}{}{My knee...}
{1449}{}{I'm blind!}
{1450}{}{Jag kan inte se!}
{1451}{}{My eye!}
{1452}{}{My groin!}
{1453}{}{Aieee!}
{1454}{}{Damn that hurts}
{1455}{}{Ooof!}
{1456}{}{Urp!}
{1457}{}{Ohhhhh, it burns!}
{1500}{}{I'm outta here! Lunchtime}
{1501}{}{I'm gone!}
{1502}{}{Whoops, picked the wrong opponent}
{1503}{}{Maybe this wasn't such a good idea}
{1504}{}{A guy could get hurt out here!}
{1505}{}{Just kidding}
{1506}{}{Time to increase the ol' body count}
{1507}{}{A guard's work is never done}
{1508}{}{Your face might look better in pieces}
{1509}{}{Not again... Ammo is so expensive!}
{1510}{}{They better not stick me with burial duty}
{1511}{}{Who do you think you are?}
{1512}{}{Now here's a pro at work}
{1513}{}{You shouldn't have gotten up this morning}
{1514}{}{You're taking a dirt nap!}
{1515}{}{Let's see if you fight better than your grandma}
{1516}{}{And now I lay you down to rest...}
{1517}{}{Like taking candy from a baby...}
{1518}{}{It's survival of the fittest, and you're out of shape}
{1519}{}{I'd rather be sailing}
{1520}{}{Drop dead!}
{1521}{}{I'm gonna be the last thing you ever see!}
{1522}{}{I ain't that easy}
{1523}{}{Awwww, did you miss me?}
{1524}{}{Keep trying and one day you'll hit!}
{1525}{}{Nice one, dumbass}
{1526}{}{Want me to stand still for you?}
{1527}{}{I almost flinched}
{1528}{}{Now I won't hear your screams}
{1529}{}{My head is ringing!}
{1530}{}{Ow! My ear! Oh wait, I have a spare.}
{1531}{}{Aw, but I liked that arm!}
{1532}{}{There it goes...}
{1533}{}{Ow... you're very disarming...}
{1534}{}{That hand was my favorite!}
{1535}{}{It's broken, like my heart. I hate you.}
{1536}{}{Loosened my grip a bit}
{1537}{}{You must think you're pretty good}
{1538}{}{That's all you got? Ugh}
{1539}{}{Oof! Bitch!}
{1540}{}{Want to come over and try that again?}
{1541}{}{When you grow up, I bet you want to be good as me}
{1542}{}{At least that wasn't as ugly as your face!}
{1543}{}{Ouch! Dammit!}
{1544}{}{Where's my foot?}
{1545}{}{Just a scratch ...and a few broken bones}
{1546}{}{Didn't need that knee anyway}
{1547}{}{Now I've only got ONE left feet}
{1548}{}{Where's my knee gone to this time?}
{1549}{}{Great, now I gotta grow a new one. Dick.}
{1550}{}{I'm blind!}
{1551}{}{Now I don't have to see your ugly face}
{1552}{}{Oh well, I can still smell you}
{1553}{}{My groin! My groin!}
{1554}{}{You're making this real personal}
{1555}{}{No more kids for me}
{1556}{}{There goes my sex life!}
{1557}{}{Oh, the pain!}
{1558}{}{Ow! Now that's what I call painful!}
{1600}{}{Hey, I could die out here!}
{1601}{}{Maybe this wasn't such a good idea}
{1602}{}{I quit! You win.}
{1603}{}{Help! I'm scared!}
{1604}{}{Aaaaahhhh!}
{1605}{}{Lemme outta here!}
{1606}{}{At last, some real action!}
{1607}{}{You shouldn't mess with me!}
{1608}{}{Now I can prove myself in battle!}
{1609}{}{This is it... right?}
{1610}{}{Gotta turn off the safety this time}
{1611}{}{This could be fun!}
{1612}{}{Take this!}
{1613}{}{Now I have you!}
{1614}{}{This is great!}
{1615}{}{How do you like this?}
{1616}{}{Die, you raider freak!}
{1617}{}{You mutant freak!}
{1618}{}{Attack!}
{1619}{}{Stop moving!}
{1620}{}{Don't scream, it scares me}
{1621}{}{Don't bleed too much}
{1622}{}{Ha, missed me!}
{1623}{}{You missed!}
{1624}{}{Slick move, huh?}
{1625}{}{Is that the best you can do?}
{1626}{}{Hey! That could have hurt!}
{1627}{}{Hey, watch it, that was close!}
{1628}{}{Can we take a timeout?}
{1629}{}{My face! What have you done!}
{1630}{}{Aggghhh! My face! No! No!}
{1631}{}{Seriously? Now I can't fight}
{1632}{}{My arm, my arm!}
{1633}{}{Oh shit, no!}
{1634}{}{That was my shooting hand!}
{1635}{}{My arm, what did you do to it?}
{1636}{}{Aggghhh!}
{1637}{}{Aj!}
{1638}{}{Damn, that does hurt}
{1639}{}{Owie! Owie! Owie!}
{1640}{}{I'm not sure if I like this...}
{1641}{}{Take it easy on me, I'm just a beginner}
{1642}{}{Oof!}
{1643}{}{Ack!}
{1644}{}{Ouch! That hurt!}
{1645}{}{Come on, I need that!}
{1646}{}{My leg! What have you done?}
{1647}{}{Aggghhh!}
{1648}{}{Ow, my leg!}
{1649}{}{My leg! No...}
{1650}{}{I needed that for running away...}
{1651}{}{Jag kan inte se!}
{1652}{}{Mina ögon!}
{1653}{}{Help me!}
{1654}{}{Ow! My groin!}
{1655}{}{Oooooo, you dirty little...}
{1656}{}{Urp!}
{1657}{}{Are those my entrails?}
{1658}{}{I...can't...breathe...}
{1659}{}{Fan, vad ont det gör!}
{1700}{}{I ain't dyin' for this!}
{1701}{}{The job ain't worth this!}
{1702}{}{I gotta scram!}
{1703}{}{There goes my rep...}
{1704}{}{I got no beef with you}
{1705}{}{Git me away from this lunkhead}
{1706}{}{Not another hooligan...}
{1707}{}{You just crossed the line!}
{1708}{}{You ain't getting away with that here!}
{1709}{}{Not on my watch, buddy!}
{1710}{}{I'm gonna blot you out!}
{1711}{}{[sigh] Not again...}
{1712}{}{This is what I do to troublemakers!}
{1713}{}{Turn out the lights...}
{1714}{}{This'll teach you not to cause trouble}
{1715}{}{I'm gonna open up on you!}
{1716}{}{I'll turn your pain to eleven}
{1717}{}{Let's see how tough you are...}
{1718}{}{Think you're some kinda hot shot, huh?}
{1719}{}{Shouldn't start what you can't finish}
{1720}{}{Did you expect to get away with this?}
{1721}{}{I eat floozies like you for breakfast}
{1722}{}{You make my job easy}
{1723}{}{No finesse, pal}
{1724}{}{Man, you got no muscle!}
{1725}{}{Is that the best you can do?}
{1726}{}{You didn't expect to tag me, did you?}
{1727}{}{C'mon, pansy. Gimme a fight!}
{1728}{}{Du bröt min näsa!}
{1729}{}{Ow! Damn you!}
{1730}{}{Damn! That hurt!}
{1731}{}{Ow, my arm!}
{1732}{}{I'm gonna ice you for that!}
{1733}{}{That was a mistake}
{1734}{}{You sunnovabitch}
{1735}{}{I'm gonna do you in for that!}
{1736}{}{Whatever, I can still kill you without it}
{1737}{}{Not another busted leg!}
{1738}{}{Aj!}
{1739}{}{That was a mistake}
{1740}{}{Ow! You trying to cut me down?}
{1741}{}{Bad move, buddy}
{1742}{}{That hurt...}
{1743}{}{I can't see! Cheap shot}
{1744}{}{Ouch! That's it, you're gonna get it}
{1745}{}{I don't need to see ya to scrag ya!}
{1746}{}{Oooo! In da balls!}
{1747}{}{Do that again and I'll end you}
{1748}{}{Shit that stings!}
{1749}{}{Ack! My jewels! Not cool.}
{1750}{}{Gonna need some ice}
{1751}{}{Urp! Nice aim...}
{1800}{}{Mercy!}
{1801}{}{Somebody help me!}
{1802}{}{Please stop!}
{1803}{}{Hjälp!}
{1804}{}{Aaaaahhhh!}
{1805}{}{[crying]}
{1806}{}{Hmm, uh, stop!}
{1807}{}{I don't like your kind...}
{1808}{}{I really hoped it wouldn't come to this...}
{1809}{}{I don't wanna get hurt}
{1810}{}{I guess I have to defend myself}
{1811}{}{Here goes nothing}
{1812}{}{Take this!}
{1813}{}{You shouldn't have started this!}
{1814}{}{You asked for this!}
{1815}{}{How do you like this?}
{1816}{}{You made this happen}
{1817}{}{You beast!}
{1818}{}{I don't want to do this!}
{1819}{}{Stand still for a second}
{1820}{}{I didn't want this fight, but...}
{1821}{}{You cad!}
{1822}{}{Shit, that was close!}
{1823}{}{You missed me!}
{1824}{}{Wow, that could have hurt!}
{1825}{}{Whew! I'm still alive!}
{1826}{}{Hey! That could have hurt!}
{1827}{}{Oh good, nothing bleeding}
{1828}{}{My face! My face!}
{1829}{}{Fuck! That hurt!}
{1830}{}{Oh god!}
{1831}{}{Oh no!}
{1832}{}{Aj!}
{1833}{}{You broke my arm!}
{1834}{}{My arm...}
{1835}{}{Wahhhh!}
{1836}{}{My God! My arm!}
{1837}{}{Ow! That really hurt!}
{1838}{}{I think I'm gonna faint}
{1839}{}{Ouch!}
{1840}{}{I need some fresh air after that}
{1841}{}{That hurt!}
{1842}{}{Just leave me alone!}
{1843}{}{Ohhh, pain!}
{1844}{}{Why? WHY?}
{1845}{}{Yep, definitely broken.}
{1846}{}{How am I supposed to walk now?}
{1847}{}{Owww, my leg's useless!}
{1848}{}{My knee!}
{1849}{}{Aaaarrrrggghhh!}
{1850}{}{I'm blind! Oh God, I'm blind!}
{1851}{}{My face! My eyes! Arrrrgh!}
{1852}{}{My eyes! What have you done to my eyes!?}
{1853}{}{Ååååååååå, mitt skrev! Ååååååå...}
{1854}{}{Oww...It burns!}
{1855}{}{Everything... going... black...}
{1856}{}{Ooorp! aoooww...}
{1857}{}{I...can't...breathe...}
{1858}{}{Smärtan, smärtan...}
{1900}{}{I'm taking it on the lam}
{1901}{}{I'll be back!}
{1902}{}{Later punk!}
{1903}{}{This was fun, but I'm gone!}
{1904}{}{You'll pay for this - later!}
{1905}{}{Let's do this again soon!}
{1906}{}{I'm gonna pin your ears back!}
{1907}{}{Fresh meat! Delicious}
{1908}{}{You just made my day!}
{1909}{}{You're gonna be my bitch!}
{1910}{}{You're fucking history, pal}
{1911}{}{I'm gonna settle your hash!}
{1912}{}{Stop screaming, it's annoying}
{1913}{}{Hope you're not afraid of blood}
{1914}{}{Please don't beg. Death should be dignified.}
{1915}{}{I hope you don't die too quickly}
{1916}{}{Got any last words?}
{1917}{}{Take this!}
{1918}{}{Die! Die! Die! Die! Die!}
{1919}{}{Wanna see your insides?}
{1920}{}{Let's open you up a little...}
{1921}{}{You're dogfood, friend.}
{1922}{}{You didn't even wing me}
{1923}{}{Haha, nice.}
{1924}{}{C'mon, punk. Give me a fight!}
{1925}{}{Is that the best you can do?}
{1926}{}{This is gonna be easier than I thought}
{1927}{}{Wow, how are you still alive?}
{1928}{}{Det där blir ett häftigt ärr!}
{1929}{}{I'm starting to get annoyed}
{1930}{}{Do that again, pig}
{1931}{}{You winged me!}
{1932}{}{Nice shot. Mine will be better.}
{1933}{}{You broke my arm, but I'll break your neck}
{1934}{}{Oh so that's how you wanna play it?}
{1935}{}{Det är bara en skråma...}
{1936}{}{Break my arm, I'll break your neck...}
{1937}{}{Alright bitch, you're gonna die}
{1938}{}{Oof! I'm gonna scrag you for that...}
{1939}{}{Merely a flesh wound, unlike yours.}
{1940}{}{Oof! Is that all you got?}
{1941}{}{I love the sound of cracking ribs!}
{1942}{}{That hurts, but I'm still pissed off}
{1943}{}{Arg! Come here and try that again}
{1944}{}{I love the sound of bones crunching!}
{1945}{}{Nope, still attached.}
{1946}{}{I think you broke it. Die!}
{1947}{}{I love the sound of bones crunching!}
{1948}{}{Whatever, I can still end you}
{1949}{}{That hurt a bit, but not enough}
{1950}{}{Hey, I'm blind. Big deal.}
{1951}{}{I can't see. That'll make this fair}
{1952}{}{My eyes! Bitch!}
{1953}{}{Oof, my junk!}
{1954}{}{That was a ballsy move}
{1955}{}{Try that... again... [gasp]}
{1956}{}{That's it, you're fucking dead!}
{1957}{}{So that's the way you want to play it}
{1958}{}{Ack!}
{2000}{}{Attack someone else, please!}
{2001}{}{Have mercy!}
{2002}{}{Somebody help me!}
{2003}{}{Please stop!}
{2004}{}{Go away, I didn't do anything!}
{2005}{}{I ain't dyin' for this!}
{2006}{}{Wait 'til I get you...}
{2007}{}{Why are you doing this?}
{2008}{}{Hey you!}
{2009}{}{You're not welcome here}
{2010}{}{Nobody's taking this place over...}
{2011}{}{Who do you think you are?}
{2012}{}{I needed a workout}
{2013}{}{Where's that damn shovel?}
{2014}{}{This is what we do to vermin!}
{2015}{}{You mutant freak!}
{2016}{}{You ain't takin' me without a fight}
{2017}{}{Gonna feed you to the dogs}
{2018}{}{This'll learn ya!}
{2019}{}{Fine. You asked for this.}
{2020}{}{You animal!}
{2021}{}{When in Rome...}
{2022}{}{It must be my lucky day}
{2023}{}{I've seen smarter brahmin than you}
{2024}{}{Whew! Close one}
{2025}{}{I ain't no pushover}
{2026}{}{Thank the gods}
{2027}{}{You missed!}
{2028}{}{Damn that smarts!}
{2029}{}{Aggghhh!}
{2030}{}{Ooooo, shit!}
{2031}{}{Aggghhh! Min arm!}
{2032}{}{Ow, ow, ow!}
{2033}{}{Oh come on, I needed that!}
{2034}{}{Aggghhh! Min arm!}
{2035}{}{Noooo.....}
{2036}{}{I think you broke it!}
{2037}{}{Förbannat!}
{2038}{}{That was pretty painful...}
{2039}{}{Argh!}
{2040}{}{Ouch!}
{2041}{}{Guh!}
{2042}{}{Oof!}
{2043}{}{Aj!}
{2044}{}{Aggghhh! My leg!}
{2045}{}{I need a chair}
{2046}{}{Mitt ben!}
{2047}{}{Aggghhh! My leg!}
{2048}{}{Great, there goes my job}
{2049}{}{Ow! No!}
{2050}{}{Aggghhh! Jag är blind!}
{2051}{}{Damn you to hell!}
{2052}{}{My eye!}
{2053}{}{ouch}
{2054}{}{Åååååååååå!}
{2055}{}{I...can't...breathe...}
{2056}{}{Oh no...}
{2057}{}{Smärtan, smärtan...}
{2058}{}{Förbannat!}
{2100}{}{I'm gone!}
{2101}{}{Mercy! Mercy!}
{2102}{}{Please stop!}
{2103}{}{Hjälp!}
{2104}{}{Go away!}
{2105}{}{I gotta stop mixing it up}
{2106}{}{Can't we settle this?}
{2107}{}{Do we really have to do this?}
{2108}{}{I really don't want to do this}
{2109}{}{I'm gonna have to paste you}
{2110}{}{Are you sure this is a good idea?}
{2111}{}{Hope I don't get hurt}
{2112}{}{I'm really not in the mood for this}
{2113}{}{You asked for this!}
{2114}{}{I ain't in the mood for a fight, but...}
{2115}{}{I didn't ask for this!}
{2116}{}{Why did you start this?}
{2117}{}{I don't want to do this!}
{2118}{}{Don't take this personally...}
{2119}{}{Hope I don't hurt you too bad}
{2120}{}{You realize that you started this?}
{2121}{}{Self defense!}
{2122}{}{Whew!}
{2123}{}{You really don't have to do this}
{2124}{}{Hey! That could have hurt!}
{2125}{}{We shouldn't be fighting}
{2126}{}{Violence won't solve the real problem}
{2127}{}{Your heart isn't in this}
{2128}{}{Not in the face!}
{2129}{}{Ahhhh, my head!}
{2130}{}{Ow! My ear!}
{2131}{}{Please stop!}
{2132}{}{Ouch!}
{2133}{}{You broke my arm!}
{2134}{}{What have you done?}
{2135}{}{Ugh!}
{2136}{}{You broke my arm!}
{2137}{}{I don't wanna be a cripple!}
{2138}{}{My knee!}
{2139}{}{Ow! My leg's busted!}
{2140}{}{That's gonna leave a mark}
{2141}{}{Was that necessary?}
{2142}{}{Ow! My leg's busted!}
{2143}{}{I'm blind!}
{2144}{}{I have tears of blood!}
{2145}{}{Oh god, the pain...}
{2146}{}{Åååååå, mitt skrev!}
{2147}{}{I need a nap}
{2148}{}{Are you done yet?}
{2149}{}{Can't...breathe...}
{2150}{}{My jewels!}
{2151}{}{Oooo! I need to lie down...}
{2200}{}{The Master will find you!}
{2201}{}{You will not kill me!}
{2202}{}{I will be back!}
{2203}{}{My friends will get you for me!}
{2204}{}{I get friends to help!}
{2205}{}{We are Chosen! You die later!}
{2206}{}{Your death comes!}
{2207}{}{Your time is up!}
{2208}{}{Human weapons cannot harm me!}
{2209}{}{You will suffer, suffer great!}
{2210}{}{I crush skulls in my fingers!}
{2211}{}{We are the future and we laugh at you!}
{2212}{}{This is the end!}
{2213}{}{Nobody save you now!}
{2214}{}{You are impure!}
{2215}{}{Now you die a Burning Death!}
{2216}{}{You enter hell today!}
{2217}{}{I laugh as I kill}
{2218}{}{Your blood is my wine!}
{2219}{}{Now you die!}
{2220}{}{This is how you die!}
{2221}{}{Suffer, human!}
{2222}{}{Why do you struggle?}
{2223}{}{Is that best humans can do!?}
{2224}{}{You have no power!}
{2225}{}{You make me laugh hard!}
{2226}{}{Was that an attack?}
{2227}{}{You are nothing!}
{2228}{}{Ahhhgh! My face!}
{2229}{}{My face! You shall suffer!}
{2230}{}{Ahhhgh! I rend you into bits!}
{2231}{}{Ahhhgh! I will crush you}
{2232}{}{You call that pain? I laugh!}
{2233}{}{Ahhhgh! I snap your neck for that!}
{2234}{}{You won't do that again!}
{2235}{}{You call that pain? I laugh!}
{2236}{}{Ahhhgh! I snap your neck for that!}
{2237}{}{I still stand!}
{2238}{}{You will be turned or burn!}
{2239}{}{That was a mistake - on your part!}
{2240}{}{Argh, try that again!}
{2241}{}{Grrrr! Bleed now}
{2242}{}{Hahahaha! You call that pain?}
{2243}{}{Arrr! You anger me!}
{2244}{}{Ahhhgh! My leg. Come here...}
{2245}{}{You call that pain? I laugh!}
{2246}{}{Ahhhgh! I snap you like little twig!}
{2247}{}{My leg is not easily broken!}
{2248}{}{You call that pain? Ha!}
{2249}{}{Ahhhgh! I shall snap your neck for that!}
{2250}{}{Ahhhgh! Miserable human! I am blind!}
{2251}{}{Ahhhgh! Pain! What have you done!}
{2252}{}{Ahhhgh! I will torture you many days!}
{2253}{}{That is human weakness!}
{2254}{}{You cannot hurt me there!}
{2255}{}{You are stupid human!}
{2256}{}{Why you attack me there?}
{2257}{}{Your death will be painful, human!}
{2258}{}{Death to you for that...}
{2300}{}{Fall back! Fall back! Regroup!}
{2301}{}{The Master shall destroy you for this!}
{2302}{}{This isn't over! We will conquer all.}
{2303}{}{The vengeance of the Master shall strike you!}
{2304}{}{I will bring reinforcements!}
{2305}{}{I shall feast on your heart another day!}
{2306}{}{Your death is imminent}
{2307}{}{You have angered your betters, now pay the price!}
{2308}{}{I come for my enemies, wielding Holy Flame!}
{2309}{}{Those who oppose Unity must be swept aside!}
{2310}{}{Death to the enemies of the Master!}
{2311}{}{We are the future and you're history!}
{2312}{}{This is the end!}
{2313}{}{Neither man nor god can save you now!}
{2314}{}{Welcome to your grave!}
{2315}{}{This is the Master's touch!}
{2316}{}{You shall enter hell this day!}
{2317}{}{You will die at my hand}
{2318}{}{In the name of the Master, die!}
{2319}{}{Now falls the death blow!}
{2320}{}{I shall burn you with Holy Flame!}
{2321}{}{Suffer, human!}
{2322}{}{Pitiful! Why do you even struggle?}
{2323}{}{Is this the best that humanity has to offer?}
{2324}{}{Your attack is as weak as your spirit!}
{2325}{}{That was your last mistake}
{2326}{}{The Master shields me from his Enemies!}
{2327}{}{You cannot hurt the Chosen}
{2328}{}{That was nothing, let me show you pain!}
{2329}{}{You shall suffer for that!}
{2330}{}{Ahhhgh! I shall rend you into pieces!}
{2331}{}{You will die in pieces!}
{2332}{}{I am not so easily beaten!}
{2333}{}{Ahhhgh! I shall break all your bones for that}
{2334}{}{You humans are weak!}
{2335}{}{Ahhhgh! You will pay!}
{2336}{}{You won't live to regret that}
{2337}{}{Argh! Die!}
{2338}{}{Duf!}
{2339}{}{Master!}
{2340}{}{You've humbled me...}
{2341}{}{Not good enough!}
{2342}{}{Grrr!}
{2343}{}{Ahhhgh! My leg!}
{2344}{}{I am not so easily beaten!}
{2345}{}{I shall break you for that!}
{2346}{}{Ahhhgh! My leg!}
{2347}{}{It takes more than that to bring me down!}
{2348}{}{I shall crush you for that!}
{2349}{}{Ahhhgh! Miserable human! You have blinded me!}
{2350}{}{Ahhhgh! The pain! What have you done!}
{2351}{}{Ahhhgh! You have earned days of agony for this!}
{2352}{}{I do not share that weakness with you, human!}
{2353}{}{My loins are stronger than yours, human!}
{2354}{}{What a pathetic tactic, human!}
{2355}{}{The Master protects me, human!}
{2356}{}{Your death grows more painful, human!}
{2357}{}{Oof! Perhaps I should test your weak points}
{2400}{}{Master! Why have you forsaken me!}
{2401}{}{The Master shall avenge me!}
{2402}{}{Master forgive me, but I must flee!}
{2403}{}{Do you not fear retribution?}
{2404}{}{Holy Flame protect me!}
{2405}{}{Help me Master, help me!}
{2406}{}{Enemies of the Master must burn in Holy Flame!}
{2407}{}{Enemies of the Master must die!}
{2408}{}{Unity shall prevail!}
{2409}{}{The blood of the Children shall be avenged!}
{2410}{}{Peace must be fed with the blood of enemies!}
{2411}{}{Give me Unity, or give me Death!}
{2412}{}{Don't run, we're your friends}
{2413}{}{Die in the name of the Master!}
{2414}{}{Behold the Holy Flame!}
{2415}{}{Kiss the fire, touch the grave!}
{2416}{}{Unity!}
{2417}{}{None may stop the cause of Peace!}
{2418}{}{You will not stop the Unity!}
{2419}{}{For the Unity!}
{2420}{}{Master, bless me!}
{2421}{}{Burn in Holy Fire!}
{2422}{}{The Master protects me!}
{2423}{}{Praise the Master, you cannot harm me!}
{2424}{}{Thank you Master!}
{2425}{}{The Master's mercy is awesome!}
{2426}{}{I am protected by the Holy Flame!}
{2427}{}{You cannot harm the Children}
{2428}{}{Agghhh! What hit me?!}
{2429}{}{Master! Protect me!}
{2430}{}{Oof!}
{2431}{}{My arm!!}
{2432}{}{Unity shall cleanse all wounds}
{2433}{}{Master! What have they done to me!}
{2434}{}{Ow, my arm!}
{2435}{}{The Master shall heal my wounds...}
{2436}{}{I will take from you twice what you took from me}
{2437}{}{Oof!}
{2438}{}{Ack!}
{2439}{}{Master, protect me!}
{2440}{}{Master, avenge me!}
{2441}{}{Gulp!}
{2442}{}{Ow, my leg!}
{2443}{}{You broke my leg!}
{2444}{}{Master! What have they done to me!}
{2445}{}{Mitt ben!}
{2446}{}{You broke it!}
{2447}{}{Master! Can you regrow limbs?}
{2448}{}{Master, I'm blind!}
{2449}{}{Master, my eyes, they burn!}
{2450}{}{Master, I can't see!}
{2451}{}{Åååååå, mitt skrev!}
{2452}{}{Master!}
{2453}{}{Master, shield me from the pain!}
{2454}{}{I...can't...breathe...}
{2455}{}{Master, our enemies are cruel!}
{2456}{}{Master, you should have warned me}
{2500}{}{Why have you forsaken me!}
{2501}{}{I shall be avenged!}
{2502}{}{Forgive me, but I must flee!}
{2503}{}{Do you not fear retribution?}
{2504}{}{Holy Flame protect me!}
{2505}{}{Holy Flame, guide my escape!}
{2506}{}{Our enemies must burn in Holy Flame!}
{2507}{}{Our enemies must die!}
{2508}{}{Unity shall prevail!}
{2509}{}{The blood of the Children shall be avenged!}
{2510}{}{Peace must be fed with the blood of enemies!}
{2511}{}{Holy Flame and Unity upon you}
{2512}{}{Dö!}
{2513}{}{Die in the name of the Flame!}
{2514}{}{Behold the Holy Flame!}
{2515}{}{In the name of Peace, die!}
{2516}{}{Unity!}
{2517}{}{None may stop the cause of Peace!}
{2518}{}{Heathen!}
{2519}{}{Don't run, we're your friends!}
{2520}{}{Master, bless me!}
{2521}{}{Burn in Holy Fire, heathen!}
{2522}{}{The Master protects me!}
{2523}{}{Praise the Holy Flame, you cannot harm me!}
{2524}{}{Your god is false!}
{2525}{}{Your evil defeats itself!}
{2526}{}{I am protected by the Holy Flame!}
{2527}{}{You cannot harm the Children}
{2528}{}{Agghhh! What hit me!}
{2529}{}{Master! Protect me!}
{2530}{}{Aj!}
{2531}{}{Ow, my arm!}
{2532}{}{You broke my arm!}
{2533}{}{What have you done to me!}
{2534}{}{No! Master!}
{2535}{}{Revenge shall be mine!}
{2536}{}{You sinner!}
{2537}{}{Ouch! That hurt!}
{2538}{}{FUCK!}
{2539}{}{Oh, oh, that hurt!}
{2540}{}{Ouch!}
{2541}{}{Ooph!}
{2542}{}{Oof!}
{2543}{}{Master! It burns!}
{2544}{}{You will pay for that!}
{2545}{}{What have you done!}
{2546}{}{Ow, my leg!}
{2547}{}{You broke my leg!}
{2548}{}{Dammit!!}
{2549}{}{I cannot see!}
{2550}{}{Mina ögon!}
{2551}{}{I have been blinded for my sins!}
{2552}{}{Åååååå, mitt skrev!}
{2553}{}{Oooooo, you are true evil!!}
{2554}{}{Holy Flame, protect my seed!}
{2555}{}{Master works in mysterious ways!}
{2556}{}{I...can't...breathe...}
{2557}{}{Our enemies are cruel!}
{2600}{}{The Church will get you!}
{2601}{}{The Church can take care of itself!}
{2602}{}{Hjälp!}
{2603}{}{Fuck this noise}
{2604}{}{Some other patsy can take you on}
{2605}{}{I'm not gonna die for this!}
{2606}{}{Not on my doorstep...}
{2607}{}{Let's bury this hoodlum!}
{2608}{}{Time to die!}
{2609}{}{You are not allowed in here!}
{2610}{}{Dags att gå ut med soporna...}
{2611}{}{You will pay for your 'sins'...}
{2612}{}{Take this!}
{2613}{}{You screwball!}
{2614}{}{Now, you die!}
{2615}{}{C'mon, you skeev, let's rumble!}
{2616}{}{You'll wish you were brainwashed}
{2617}{}{I'm gonna smack you around.}
{2618}{}{Time to die...}
{2619}{}{Time to 'Unite' you with my 'Holy Flame'}
{2620}{}{Kiss my Holy Flame, pal!}
{2621}{}{Suck it down!}
{2622}{}{Ha, missed me!}
{2623}{}{What a clod!}
{2624}{}{Ha, you missed me!}
{2625}{}{You're an even bigger loser than the zombies!}
{2626}{}{Anyone ever teach you how to aim?}
{2627}{}{Haha, don't hurt yourself}
{2628}{}{Ugh!}
{2629}{}{Oof!}
{2630}{}{Damn! That hurt!}
{2631}{}{Ow, my arm!}
{2632}{}{You're paying for that one!}
{2633}{}{I'll break both your arms for that!}
{2634}{}{My arm! What have you done to my arm?!}
{2635}{}{You're worse than these fucking zombies}
{2636}{}{Come here and do that again, you bastard}
{2637}{}{Oooohhh, my leg!}
{2638}{}{You're paying for that one!}
{2639}{}{You fuckwad! I'm gonna get you!}
{2640}{}{Ow, my leg!}
{2641}{}{I'll do you for that!}
{2642}{}{Aj!}
{2643}{}{I'm gonna put you on the spot for that!}
{2644}{}{Mitt öga! Det där ska du få betala för!}
{2645}{}{That was a real cheap shot!}
{2646}{}{Oh, you got me in the raw!}
{2647}{}{Fan, vad ont det gör!}
{2648}{}{Motherfucking cocksucker! Shit! FUCK!}
{2649}{}{Oh, dammit!}
{2650}{}{You bastard!}
{2651}{}{You didn't show me yours first!}
{2700}{}{This battle is unnecessary. Battle!}
{2701}{}{I shall be avenged!}
{2702}{}{Your triumph shall be short-lived!}
{2703}{}{You will not prevent Unity. Unity!}
{2704}{}{My servants will protect me!}
{2705}{}{Hope! I must have hope!}
{2706}{}{Your sins shall now be punished. Punished!}
{2707}{}{My enemies must die. Die!}
{2708}{}{Unity shall prevail! Prevail!}
{2709}{}{You shall not be permitted to destroy our world. Destroy. World!}
{2710}{}{The future must be preserved! Preserved!}
{2711}{}{Give me Unity, or give me Death! Unity. Death!}
{2712}{}{Your life will end. End!}
{2713}{}{You shall be utterly destroyed. Destroyed!}
{2714}{}{You have sealed your destruction. Destruction!}
{2715}{}{You shall pay for what you have done! Done!}
{2716}{}{You will not prevent Unity. Unity!}
{2717}{}{None may stop the cause of Peace. Peace!}
{2718}{}{Nothing awaits you but the fire. Fire!}
{2719}{}{Let this be your epitaph. Epitaph!}
{2720}{}{You are nothing. Nothing! Nothing.}
{2721}{}{This is the end of your existence. End. End!}
{2722}{}{Your efforts are useless! Useless!}
{2723}{}{You cannot prevail against me! Prevail! Me!}
{2724}{}{You have erred again, human. Human!}
{2725}{}{Your evil defeats itself! Evil. Evil!}
{2726}{}{You will not survive. Survive!}
{2727}{}{Your performance is inadequate. Inadequate!}
{2728}{}{Head wound. I shall be avenged. Avenged!}
{2729}{}{That pain was unpleasant. Pain. Pain!}
{2730}{}{That will not incapacitate me. Incapacitate! Me!}
{2731}{}{You think you can hurt me there? Me? THERE?}
{2732}{}{Minor wound, human. Minor. Minor!}
{2733}{}{That pain was slightly unpleasant. Pain!}
{2734}{}{No circuitry/organics damage that can't be repaired later. Damage!}
{2735}{}{You die! Die! Die.}
{2736}{}{Systems compromised, compensating...}
{2737}{}{Systems hit, registering minor damage}
{2738}{}{Systems hit, systems hit, systems hit}
{2800}{}{Gotta get outta here!}
{2801}{}{I'll be back...}
{2802}{}{You ain't killing me today!}
{2803}{}{Later, normie!}
{2804}{}{You ain't heard the last of me!}
{2805}{}{You'll pay for this - later!}
{2806}{}{You're history!}
{2807}{}{Fresh meat...}
{2808}{}{Ah, dinner's arrived.}
{2809}{}{Brains...}
{2810}{}{I'm gonna dig your grave...}
{2811}{}{Hope I can keep your head intact...}
{2812}{}{Your number is up!}
{2813}{}{Don't bother screaming for mercy...}
{2814}{}{I'm gonna enjoy this}
{2815}{}{Oooo, that's gotta hurt!}
{2816}{}{Take this, normie!}
{2817}{}{I'm gonna eat your liver!}
{2818}{}{Hope you don't die too quickly.}
{2819}{}{Dinnertime!}
{2820}{}{Dö!}
{2821}{}{I eat punks like you for breakfast, and lunch. And dinner.}
{2822}{}{You cannot hurt me!}
{2823}{}{Normie. Figures.}
{2824}{}{Oh look, you nearly hit me}
{2825}{}{You missed, normie!}
{2826}{}{You can't kill what you can't hit!}
{2827}{}{För långsamt!}
{2828}{}{Oh, my pretty face}
{2829}{}{Ow! My head!}
{2830}{}{Oof!}
{2831}{}{My hand!}
{2832}{}{Aj!}
{2833}{}{Ow!!}
{2834}{}{Ow, my arm!}
{2835}{}{You broke my arm!}
{2836}{}{You're gonna regret that!}
{2837}{}{[Grunt!]}
{2839}{}{Oh crap!}
{2840}{}{Grrr!}
{2841}{}{You're gonna regret that!}
{2842}{}{You should stop while you're ahead!}
{2843}{}{I'll use your organs to replace mine!}
{2844}{}{Garrr!}
{2845}{}{Ow, my leg!}
{2846}{}{You're gonna pay for that!}
{2847}{}{Argh! You break my leg, I break your neck!}
{2848}{}{Mitt ben!}
{2849}{}{Try that again, normie!}
{2850}{}{Losing my balance...}
{2851}{}{Damn blood in my eyes!}
{2852}{}{Mitt öga! Det där ska du få betala för!}
{2853}{}{Din jävel!}
{2854}{}{Åååååå, mitt skrev!}
{2855}{}{Ooo! I gotta learn that move...}
{2856}{}{Inhuman swine!}
{2857}{}{AAAAAAAAAAAACCCKKKKKK!}
{2858}{}{Urp!}
{2859}{}{Oof! I'm gonna kill you for that!}
{2900}{}{Fall back! Fall back! Sector six!}
{2901}{}{You're not killing me today!}
{2902}{}{This isn't over!}
{2903}{}{My friends will get you for me!}
{2904}{}{You'll pay for this - later!}
{2905}{}{I shall feast on your heart another day!}
{2906}{}{I will kill you, human!}
{2907}{}{None challenge us and live!}
{2908}{}{Your pitiful weapons will not harm me!}
{2909}{}{Another victim comes to play with us!}
{2910}{}{I shall put you out of your misery}
{2911}{}{Master is on my side!}
{2912}{}{Human scum!}
{2913}{}{I will tear your arms off}
{2914}{}{Now you die!}
{2915}{}{This is how we handle fools!}
{2916}{}{I shall enjoy this...}
{2917}{}{Gah! You will suffer!}
{2918}{}{Your gods have forsaken you!}
{2919}{}{I want to hear your screams!}
{2920}{}{And this is how you die!}
{2921}{}{Suffer, human!}
{2922}{}{Pitiful! Why do you even struggle?}
{2923}{}{Is this the best that humanity has to offer?}
{2924}{}{Your attack is as weak as your spirit!}
{2925}{}{That was your last mistake}
{2926}{}{Fool! And you would beat me?}
{2927}{}{Pathetic!}
{2928}{}{Ahhhgh! My face!}
{2929}{}{My face! You shall suffer for that!}
{2930}{}{Arrghhggh! I shall rend you into pieces!}
{2931}{}{Ahhhgh! My arm!}
{2932}{}{Ahhhgh! I am not so easily beaten!}
{2933}{}{Ahhhgh! I shall snap your neck for that!}
{2934}{}{Ahhhgh! My arm!}
{2935}{}{Ahhhgh! I am not so easily beaten!}
{2936}{}{Ahhhgh! I shall snap your neck for that!}
{2937}{}{I will make trophies from your bones!}
{2938}{}{Oof!}
{2939}{}{Arrrggg!}
{2940}{}{[Smiles]}
{2941}{}{That didn't hurt!}
{2942}{}{You can do better than that}
{2943}{}{Even ghouls are tougher than you!}
{2944}{}{Hahaha, I still stand}
{2945}{}{Many will suffer because of you}
{2946}{}{Haha! What a feeble attempt... [groan]}
{2947}{}{Ahhhgh! My leg!}
{2948}{}{Ahhhgh! I am not so easily beaten!}
{2949}{}{Ahhhgh! I shall snap your neck for that!}
{2950}{}{Ahhhgh! My leg!}
{2951}{}{Ahhhgh! I am not so easily beaten!}
{2952}{}{Ahhhgh! I shall snap your neck for that!}
{2953}{}{Ahhhhh! Miserable human! You have blinded me!}
{2954}{}{Ahhhgh! The pain! What have you done!}
{2955}{}{Oof! You have earned days of agony for this!}
{2956}{}{I do not share that weakness with you, human!}
{2957}{}{My loins are stronger than yours, human!}
{2958}{}{What a pathetic tactic, human!}
{2959}{}{That is not my vulnerable spot, human!}
{2960}{}{Your death grows more painful, human!}
{2961}{}{Perhaps I should test your weak points}
{3000}{}{Flee! Flee!}
{3001}{}{Retreat!}
{3002}{}{Regroup!}
{3003}{}{Fall back!}
{3004}{}{Withdraw!}
{3005}{}{Aaaaghhh!}
{3006}{}{Kill this fool!}
{3007}{}{Fresh meat...}
{3008}{}{Plunder!}
{3009}{}{This one's mine!}
{3010}{}{Take him!}
{3011}{}{You're dead! I hope you have cool stuff...}
{3012}{}{Enjoy the last few seconds of your life}
{3013}{}{Blood! Blood! Blood!}
{3014}{}{Your heart is mine!}
{3015}{}{RAAAAAAARRRR!!}
{3016}{}{Your weapons will be my trophies!}
{3017}{}{Death!}
{3018}{}{You are mine to kill!}
{3019}{}{Your bones shall bleach in the wastes!}
{3020}{}{Blood and darkness!}
{3021}{}{I will make weapons from your bones!}
{3022}{}{Drill the scraggin' bastard!}
{3023}{}{Wasted effort!}
{3024}{}{You have failed!}
{3025}{}{My blood is stronger than yours!}
{3026}{}{I live!!}
{3027}{}{Your body is weak and pitiful!}
{3028}{}{Aaaagghh! My face!}
{3029}{}{WHAT THE FUCK!!?!}
{3030}{}{Du bröt min näsa!}
{3031}{}{Min arm!}
{3032}{}{You broke my arm!}
{3033}{}{You will die for that!}
{3034}{}{I'll take both of yours!}
{3035}{}{You broke it!}
{3036}{}{You'll pay for that!}
{3037}{}{Fuck!}
{3038}{}{You call that pain!?}
{3039}{}{Ouch!}
{3040}{}{Oof!}
{3041}{}{Dammit! That hurt!}
{3042}{}{Come here, and let me do that to you!}
{3043}{}{You're gonna pay! I swear it!}
{3044}{}{[Gasp!]}
{3045}{}{Dammit! Bitch!}
{3046}{}{Eegah! That bit the root!}
{3047}{}{Mitt ben!}
{3048}{}{You will die for that!}
{3049}{}{Argh! You break my leg, I break your neck!}
{3050}{}{Mitt ben!}
{3051}{}{You will die for that!}
{3052}{}{Argh!!}
{3053}{}{Argh! I shall tear you into pieces!}
{3054}{}{My eye!}
{3055}{}{My eye! You will die slowly for that!}
{3056}{}{Åååååå, mitt skrev!}
{3057}{}{Ooo! You... will... suffer...}
{3058}{}{Ooo! I... will... kill...}
{3059}{}{Ooo! I will mutilate you...}
{3060}{}{Urp!}
{3061}{}{I will kill you for that!}
{3100}{}{Khans! Cover me!}
{3101}{}{Retreat!}
{3102}{}{Regroup!}
{3103}{}{Fall back!}
{3104}{}{Withdraw!}
{3105}{}{I'll be back}
{3106}{}{Låt utmaningen börja!}
{3107}{}{Fresh meat...}
{3108}{}{Plunder!}
{3109}{}{This one's mine!}
{3110}{}{Khans, attack!}
{3111}{}{Anything you can do, I Khan do better}
{3112}{}{Khans, kill!}
{3113}{}{Blood! Blood! Blood!}
{3114}{}{Jag är överlägsen!}
{3115}{}{RAAAAAAARRRR!!}
{3116}{}{Khans are invincible!}
{3117}{}{Ingen reträtt! Ingen kapitulation!}
{3118}{}{You are mine to kill!}
{3119}{}{Your bones shall bleach in the wastes!}
{3120}{}{Blood and darkness!}
{3121}{}{Khans are the strong!}
{3122}{}{Ahahaha, try again!}
{3123}{}{I cannot be touched!}
{3124}{}{I am indestructible!}
{3125}{}{My blood is stronger than yours!}
{3126}{}{My slaves fight better than that!}
{3127}{}{You are not worthy of combat with me!}
{3128}{}{A worthy blow!}
{3129}{}{That was your last attack!}
{3130}{}{A pitiful attempt!}
{3131}{}{I can still beat you with one arm!}
{3132}{}{You broke my arm! Now the fight is fair!}
{3133}{}{That was your final blow!}
{3134}{}{I can still beat you with one arm!}
{3135}{}{You broke my arm! Now the fight is fair!}
{3136}{}{I will end you!}
{3137}{}{Your death will be legendary for that!}
{3138}{}{I will feast on your eyes for that!}
{3139}{}{I am indestructible!}
{3140}{}{My blood is stronger than yours!}
{3141}{}{I am indestructible!}
{3142}{}{I will feast on your eyes for that!}
{3143}{}{RAAAAAAARRRR!!}
{3144}{}{My ribs hurt. Soon I will remove yours! It's only fair}
{3145}{}{My ribs hurt. Soon I will remove yours! It's only fair}
{3146}{}{Blood and darkness!}
{3147}{}{I do not need to stand to kill you!}
{3148}{}{You will die for that!}
{3149}{}{My leg! I will remove yours with my fists!}
{3150}{}{I do not need to stand to kill you!}
{3151}{}{You will die for that!}
{3152}{}{My leg! I will remove yours with my fists!}
{3153}{}{Argh! I shall tear you into pieces!}
{3154}{}{My eyes! I will trade my vision for your death!}
{3155}{}{My eye! You will die slowly for that!}
{3156}{}{You will not steal my manhood!}
{3157}{}{Ooo! You... will... suffer...}
{3158}{}{Ooo! I... will... kill...}
{3159}{}{Ooo! I will mutilate you...}
{3160}{}{Urp!}
{3161}{}{You will not steal my manhood!}
{3200}{}{Don't think this is over!}
{3201}{}{I need help here!}
{3202}{}{Somebody help me!}
{3203}{}{We'll bring you to justice yet!}
{3204}{}{Someday, you'll get what's coming to you!}
{3205}{}{I ain't dyin' for this!}
{3206}{}{}
{3207}{}{}
{3208}{}{}
{3209}{}{We don't like your kind around here!}
{3210}{}{Nobody's taking this place over...}
{3211}{}{Shady Sands don't need the likes of you!}
{3212}{}{}
{3213}{}{I'm gonna put the big hurt on you?}
{3214}{}{This is what we do to vermin!}
{3215}{}{}
{3216}{}{This is how we handle trouble in Shady Sands.}
{3217}{}{This'll learn you!}
{3218}{}{I'll use your body for fertilizer.}
{3219}{}{Fine. You asked for this.}
{3220}{}{You animal!}
{3221}{}{You'll regret coming here!}
{3222}{}{You're not as good as you think}
{3223}{}{}
{3224}{}{You're dumber than a mole rat}
{3225}{}{Shady Sands don't roll over and die for no one}
{3226}{}{}
{3227}{}{That was your last mistake}
{3228}{}{Förbannat!}
{3229}{}{Aggghhh!}
{3230}{}{My face! My face!}
{3231}{}{Aggghhh! Min arm!}
{3232}{}{Min arm!}
{3233}{}{Damn arm's useless now...}
{3234}{}{Aggghhh! Min arm!}
{3235}{}{Min arm!}
{3236}{}{Damn arm's useless now...}
{3237}{}{Ouch!}
{3238}{}{Doh!}
{3239}{}{}
{3240}{}{May you die of thirst, alone and cold...}
{3241}{}{[Gasp!]}
{3242}{}{}
{3243}{}{Please don't...}
{3244}{}{}
{3245}{}{Bad karma to hit me like that}
{3246}{}{Gack!}
{3247}{}{Aggghhh! My leg!}
{3248}{}{Mitt ben!}
{3249}{}{Dammit, my leg's useless...}
{3250}{}{Aggghhh! My leg!}
{3251}{}{Mitt ben!}
{3252}{}{Dammit, my leg's useless...}
{3253}{}{Aggghhh! Jag är blind!}
{3254}{}{Dammit! Everything's dark!}
{3255}{}{Mitt öga! Det där ska du få betala för!}
{3256}{}{Åååååå, mitt skrev!}
{3257}{}{Ooooooooooffffff!}
{3258}{}{I...can't...breathe...}
{3259}{}{!}
{3260}{}{Smärtan, smärtan...}
{3261}{}{Fan, vad ont det gör!}
{3300}{}{I'm gone}
{3301}{}{}
{3302}{}{Aaaaahhhh!}
{3303}{}{Later. Maybe.}
{3304}{}{}
{3305}{}{See you around}
{3306}{}{}
{3307}{}{What is it this time?}
{3308}{}{I'll deal with this...}
{3309}{}{Not another interruption!}
{3310}{}{If it ain't radscorpions, it's them damn raiders...}
{3311}{}{}
{3312}{}{}
{3313}{}{Dö!}
{3314}{}{Loser}
{3315}{}{Punk}
{3316}{}{}
{3317}{}{Your number is up!}
{3318}{}{You really loused up here}
{3319}{}{Here's a gift from Shady Sands}
{3320}{}{You ain't bothering this place again}
{3321}{}{Get ready to push up daisies}
{3322}{}{Not impressed}
{3323}{}{Amateur}
{3324}{}{Pathetic}
{3325}{}{You're slow}
{3326}{}{You're useless}
{3327}{}{Don't quit your day job}
{3328}{}{That hurt}
{3329}{}{Mina ögon!}
{3330}{}{Ow! Busted my nose...}
{3331}{}{Aj!}
{3332}{}{Ow! My arm!}
{3333}{}{Ow! You broke it!}
{3334}{}{Aj!}
{3335}{}{Ow! My arm!}
{3336}{}{Ow! You broke it!}
{3337}{}{Damn it! That hurt!}
{3338}{}{Ouch!}
{3339}{}{Aj!}
{3340}{}{}
{3341}{}{(Holding ribs) Ouch!}
{3342}{}{C'mon! No fighting in the town!}
{3343}{}{[Gasp!]}
{3344}{}{Ow! I'm disappointed in you outsiders...}
{3345}{}{Oof!}
{3346}{}{That hurt!}
{3347}{}{Aj!}
{3348}{}{Ow! My knee!}
{3349}{}{Ow! My leg!}
{3350}{}{Aj!}
{3351}{}{Ow! My knee!}
{3352}{}{Ow! My leg!}
{3353}{}{I'm blind!}
{3354}{}{Jag kan inte se!}
{3355}{}{So dark}
{3356}{}{Åååååå, mitt skrev!}
{3357}{}{Aieee!}
{3358}{}{Damn that hurts}
{3359}{}{Ooof!}
{3360}{}{Urp!}
{3361}{}{I...can't...breathe...}
{3400}{}{}
{3401}{}{}
{3402}{}{I need a doctor}
{3403}{}{Later. Maybe.}
{3404}{}{I better stay out of the way}
{3405}{}{See you around}
{3406}{}{Friend, you just made a big mistake}
{3407}{}{What is it this time?}
{3408}{}{I'll deal with this...}
{3409}{}{Not another interruption!}
{3410}{}{If it ain't radscorpions, it's troublemakers...}
{3411}{}{}
{3412}{}{}
{3413}{}{}
{3414}{}{Scab}
{3415}{}{Punk}
{3416}{}{This is what we do to troublemakers}
{3417}{}{Hope this hurts}
{3418}{}{You really screwed up here}
{3419}{}{Here's a gift from Shady Sands}
{3420}{}{You ain't bothering this place again}
{3421}{}{I'm not letting you walk away from this}
{3422}{}{Not impressed}
{3423}{}{Shouldn't fight unless you know what you're doing}
{3424}{}{Pathetic}
{3425}{}{You're slow}
{3426}{}{}
{3427}{}{}
{3428}{}{}
{3429}{}{My skull!}
{3430}{}{Ow! Damn busted nose...}
{3431}{}{Aj!}
{3432}{}{Ow! My arm!}
{3433}{}{Ow! You broke it!}
{3434}{}{Aj!}
{3435}{}{Ow! My arm!}
{3436}{}{Ow! You broke it!}
{3437}{}{Aj!}
{3438}{}{By Dharma! That hurt!}
{3439}{}{Those who start trouble will find it...}
{3440}{}{Oof!}
{3441}{}{Oof! I will punish you for that...}
{3442}{}{Ow! That hurt!}
{3443}{}{Ouch! That was most unpleasant}
{3444}{}{Ow! Why do you do this?}
{3445}{}{Arg! I must control my emotions...}
{3446}{}{Ack! You are akin to radscorpion dung!}
{3447}{}{Aj!}
{3448}{}{Ow! My knee!}
{3449}{}{Ow! My leg!}
{3450}{}{Aj!}
{3451}{}{Ow! My knee!}
{3452}{}{Ow! My leg!}
{3453}{}{Mina ögon!}
{3454}{}{Agghh! So that's how you want to play...}
{3455}{}{Agghh! Dirty little son of a...}
{3456}{}{Åååååå, mitt skrev!}
{3457}{}{Aieee!}
{3458}{}{[whimper]}
{3459}{}{Ooof!}
{3460}{}{Oooooo! I didn't feel that! Ow!}
{3461}{}{Oooooo! That hurt. Must be getting old.}
{3500}{}{Maybe I'll take a short break.}
{3501}{}{I'll be back!}
{3502}{}{Later punk!}
{3503}{}{}
{3504}{}{}
{3505}{}{Let's do this again soon!}
{3506}{}{Fight me or love me...}
{3507}{}{Fresh meat!}
{3508}{}{!}
{3509}{}{}
{3510}{}{Rippers gonna rip you to pieces!}
{3511}{}{Let's dance!}
{3512}{}{I'm gonna carve you like an iguana-on-a-stick!}
{3513}{}{}
{3514}{}{Please don't die yet. I want you to suffer}
{3515}{}{}
{3516}{}{One serving of death, coming right up!}
{3517}{}{You'll be so pretty when you're dead}
{3518}{}{Die! Die! Die! Die! Die!}
{3519}{}{Your pain is my joy!}
{3520}{}{Let's open you up a little...}
{3521}{}{And I thought there'd be no bloodshed today...}
{3522}{}{}
{3523}{}{I'm SO scared!}
{3524}{}{C'mon percy boy, give me a fight!}
{3525}{}{Is that the best you can do?}
{3526}{}{You are nothing compared to me!}
{3527}{}{This is gonna be easier than I thought}
{3528}{}{That'll be a nice scar!}
{3529}{}{You tryin' to impress me?}
{3530}{}{Do that again, honey.}
{3531}{}{I love the sound of bones crunching}
{3532}{}{Ooo, you're getting serious!}
{3533}{}{I like it rough, darling}
{3534}{}{I love the sound of bones crunching}
{3535}{}{Ooo, you're getting serious!}
{3536}{}{I like it rough, darling}
{3537}{}{I love it when you're rough...}
{3538}{}{Give me another love tap...}
{3539}{}{Ouch! Oh, love hurts, baby!}
{3540}{}{Oof!}
{3541}{}{Doh!}
{3542}{}{Argh! Does this mean it's over?}
{3543}{}{[Gasp!]}
{3544}{}{Hit me again, please...}
{3545}{}{I get to pitch next time}
{3546}{}{Oh, the pain, the pain...}
{3547}{}{I love the sound of bones crunching}
{3548}{}{Ooo, you're getting serious!}
{3549}{}{}
{3550}{}{I love the sound of bones crunching}
{3551}{}{}
{3552}{}{I like it!}
{3553}{}{Hey, I'm blind. What a rush!}
{3554}{}{I can't see. I guess I'll just have to smell your fear!}
{3555}{}{My eyes! Man, I like the way you fight}
{3556}{}{Åååååå, mitt skrev!}
{3557}{}{That was a ballsy move}
{3558}{}{Oooo! Is that a proposal, baby?}
{3559}{}{}
{3560}{}{So that's the way you want to play it}
{3561}{}{Ooooo, nice move pal}
{3600}{}{}
{3601}{}{}
{3602}{}{}
{3603}{}{You ain't won!}
{3604}{}{Fall back!}
{3605}{}{I don't need this...}
{3606}{}{Attack!}
{3607}{}{I'm gonna enjoy burying you in a shallow grave!}
{3608}{}{}
{3609}{}{Somebody's dyin'}
{3610}{}{Kill the intruder!}
{3611}{}{}
{3612}{}{}
{3613}{}{Dö!}
{3614}{}{Skank!}
{3615}{}{This is why they call us Blades}
{3616}{}{}
{3617}{}{Hope this hurts}
{3618}{}{Gonna enjoy this}
{3619}{}{Your head is goin' in my collection!}
{3620}{}{I'll bury you}
{3621}{}{Your day is about to get real bad}
{3622}{}{I am more righteous than God!}
{3623}{}{Not impressed}
{3624}{}{Show me some balls!}
{3625}{}{}
{3626}{}{Your Mama slept with Rippers!}
{3627}{}{You tryin' to swat flies, mug?}
{3628}{}{}
{3629}{}{ack!!}
{3630}{}{Ow! Busted my nose...}
{3631}{}{Aj!}
{3632}{}{Ow! My arm!}
{3633}{}{Ow! You broke it!}
{3634}{}{Aj!}
{3635}{}{Ow! My arm!}
{3636}{}{Ow! You broke it!}
{3637}{}{Aj!}
{3638}{}{Ah, shit!}
{3639}{}{Ouch! That was a bad mistake...}
{3640}{}{Ow! I'll show you...}
{3641}{}{[Gasp!]}
{3642}{}{Can't breathe...}
{3643}{}{}
{3644}{}{Oof!}
{3645}{}{You skag! That hurt!}
{3646}{}{}
{3647}{}{Aj!}
{3648}{}{Ow! My knee!}
{3649}{}{Ow! My leg!}
{3650}{}{Aj!}
{3651}{}{Ow! My knee!}
{3652}{}{Ow! My leg!}
{3653}{}{I'm blind!}
{3654}{}{Jag kan inte se!}
{3655}{}{My eyes! You son of a Ripper...}
{3656}{}{Åååååå, mitt skrev!}
{3657}{}{Aieee!}
{3658}{}{Damn that hurts}
{3659}{}{Ooof!}
{3660}{}{I'll kill you for that one, punk}
{3661}{}{I...can't...breathe...}
{3700}{}{I'd really like to watch the sunrise tomorrow}
{3701}{}{Maybe this wasn't a good idea}
{3702}{}{}
{3703}{}{}
{3704}{}{I ain't dyin' for this!}
{3705}{}{I can't believe what they're packing...}
{3706}{}{Trying to muscle in on our business, huh?}
{3707}{}{Somebody just made a big mistake!}
{3708}{}{Time to rip a clip...}
{3709}{}{Who do you think you are?}
{3710}{}{Time to demonstrate some merchandise}
{3711}{}{Wait 'til I get you...}
{3712}{}{Ride my bullet back to hell!}
{3713}{}{}
{3714}{}{}
{3715}{}{How do you like this?}
{3716}{}{I'm gonna drop you like a bad habit}
{3717}{}{How's this for firepower?}
{3718}{}{Let's see how tough you are...}
{3719}{}{Fighting is my life}
{3720}{}{}
{3721}{}{Maybe you'll learn some respect}
{3722}{}{You didn't expect to tag me, did you?}
{3723}{}{I've been doing this for years, punk}
{3724}{}{You didn't expect that , did you?}
{3725}{}{That was your last mistake}
{3726}{}{Amateur}
{3727}{}{This ain't like shooting mole rats, pal.}
{3728}{}{Aj! Din jävla...}
{3729}{}{I'm gonna kill you for that}
{3730}{}{Jag ska hugga huvudet av dig!}
{3731}{}{Ow, my arm!}
{3732}{}{Damn. My arm's busted!}
{3733}{}{Min arm!}
{3734}{}{Ow, my arm!}
{3735}{}{Damn. My arm's busted!}
{3736}{}{Min arm!}
{3737}{}{I've seen junior employees do better than that...}
{3738}{}{Ouch!}
{3739}{}{I must remember to give you that pain back some day}
{3740}{}{Oof!}
{3741}{}{}
{3742}{}{Förbannat!}
{3743}{}{Skaggin' jerk!}
{3744}{}{}
{3745}{}{[Gasp!]}
{3746}{}{Ouch!}
{3747}{}{Ow, my leg!}
{3748}{}{}
{3749}{}{My knee!}
{3750}{}{Ow, my leg!}
{3751}{}{You're gonna pay for that, in spades!}
{3752}{}{My knee!}
{3753}{}{Jag kan inte se!}
{3754}{}{Mitt öga! Det där ska du få betala för!}
{3755}{}{Aaieeee! I'm blind!}
{3756}{}{Åååååå, mitt skrev!}
{3757}{}{So that's the way you want to play}
{3758}{}{}
{3759}{}{Urp!}
{3760}{}{}
{3761}{}{Smärtan, smärtan...}
{3800}{}{I need reinforcements!}
{3801}{}{Somebody help me!}
{3802}{}{Regroup!}
{3803}{}{Retreat! Retreat!}
{3804}{}{Fall back! Fall back!}
{3805}{}{We need to find a better position!}
{3806}{}{We have a target!}
{3807}{}{We are under attack!}
{3808}{}{Sound an alert! I'll hold them off!}
{3809}{}{We have a problem. I'll deal with it.}
{3810}{}{Target spotted, moving to intercept!}
{3811}{}{Engaging target!}
{3812}{}{Gangland punk!}
{3813}{}{I'm putting you out of our misery}
{3814}{}{You're no better than an animal!}
{3815}{}{You'd better stay down this time}
{3816}{}{You'll never bother anyone again}
{3817}{}{No mercy to punks!}
{3818}{}{You better pray to the gods!}
{3819}{}{Ride my bullet back to hell!}
{3820}{}{I'm dropping the hammer on you}
{3821}{}{See you in hell}
{3822}{}{Your attack stinks worse than your breath, maggot!}
{3823}{}{C'mon loser. Just drop dead for me}
{3824}{}{}
{3825}{}{You're playing the wrong game, scumbag!}
{3826}{}{What's the matter punk?}
{3827}{}{I don't kill that easy.}
{3828}{}{Aggghh! Lucky shot!}
{3829}{}{My face!}
{3830}{}{Du bröt min näsa!}
{3831}{}{Aggghh! Lucky shot!}
{3832}{}{A busted arm ain't stopping me!}
{3833}{}{}
{3834}{}{Aggghh! Lucky shot!}
{3835}{}{A busted arm ain't stopping me!}
{3836}{}{I don't like the sound of that}
{3837}{}{Aggghh! Lucky shot!}
{3838}{}{}
{3839}{}{You ain't crippling me, pal.}
{3840}{}{Aggghh! Lucky shot!}
{3841}{}{}
{3842}{}{You ain't crippling me, pal.}
{3843}{}{I'm blind!}
{3844}{}{My eyes are burning!}
{3845}{}{Jag kan inte se!}
{3846}{}{Åååååå, mitt skrev!}
{3847}{}{Yeah, punks always aim for the groin}
{3848}{}{Damn that hurts!}
{3849}{}{I...can't...breathe...}
{3850}{}{Oooooo. You sadistic son of a...}
{3851}{}{You punk...}
{3900}{}{I need reinforcements!}
{3901}{}{Somebody help me!}
{3902}{}{}
{3903}{}{Retreat! Retreat!}
{3904}{}{Fall back! Fall back!}
{3905}{}{Hjälp!}
{3906}{}{For Adytum!}
{3907}{}{We are under attack!}
{3908}{}{I need backup!}
{3909}{}{Attack!}
{3910}{}{We don't like your kind around here!}
{3911}{}{To arms! To arms!}
{3912}{}{This is for Adytum!}
{3913}{}{This is what we do to animals!}
{3914}{}{Welcome to hell, punk}
{3915}{}{You'd better stay down this time}
{3916}{}{You'll never bother anyone again}
{3917}{}{No mercy to punks!}
{3918}{}{You better pray to the gods!}
{3919}{}{}
{3920}{}{You just bought a house six feet under}
{3921}{}{Hope you enjoyed your life; it's about to flash before your eyes}
{3922}{}{You're a waste of ammo}
{3923}{}{}
{3924}{}{}
{3925}{}{Now it's my turn}
{3926}{}{Surprised, punk?}
{3927}{}{We aren't easy to kill}
{3928}{}{Aggghh! Right in the face.}
{3929}{}{My face!}
{3930}{}{Du bröt min näsa!}
{3931}{}{Aggghh! My arm!}
{3932}{}{Ow! That hurt!}
{3933}{}{Damn. I may be hurt bad}
{3934}{}{Aggghh! My arm!}
{3935}{}{Ow! That hurt!}
{3936}{}{Damn. I may be hurt bad}
{3937}{}{Ouch!}
{3938}{}{Oof! That hurt!}
{3939}{}{Oof! It's... hard... to... breathe...}
{3940}{}{I'm hit! Medic!}
{3941}{}{I'll be okay, it's only a minor wound}
{3942}{}{Argh!}
{3943}{}{Ouch! Dammit!}
{3944}{}{Ow! I'll get you}
{3945}{}{}
{3946}{}{}
{3947}{}{Aggghh! Lucky shot!}
{3948}{}{Damn, right in the knee...}
{3949}{}{I'm not falling over, punk. Ow.}
{3950}{}{Aggghh! Lucky shot!}
{3951}{}{Damn, right in the knee...}
{3952}{}{I'm not falling over, punk. Ow.}
{3953}{}{I've been blinded! Somebody help me!}
{3954}{}{Damn, right in the eyes!}
{3955}{}{Jag kan inte se!}
{3956}{}{Åååååå, mitt skrev!}
{3957}{}{Yeah, punks always aim for the groin}
{3958}{}{Damn that hurts!}
{3959}{}{I...can't...breathe...}
{3960}{}{Oooooo. You sadistic son of a...}
{3961}{}{You punk...}
{4000}{}{Can somebody cover me!}
{4001}{}{Somebody help me!}
{4002}{}{Medic!}
{4003}{}{Retreat! Retreat!}
{4004}{}{Fall back! Fall back!}
{4005}{}{Hjälp!}
{4006}{}{This looks like trouble.}
{4007}{}{We are under attack!}
{4008}{}{We have problems!}
{4009}{}{Once more into the breach!}
{4010}{}{I'll die before I let you push me around!}
{4011}{}{You're messing with the wrong people}
{4012}{}{You should have run when you had the chance}
{4013}{}{Time to finish this}
{4014}{}{}
{4015}{}{}
{4016}{}{Another corpse for my conscience...}
{4017}{}{I'm putting you away for good this time}
{4018}{}{You better pray to the gods!}
{4019}{}{}
{4020}{}{}
{4021}{}{You won't walk away from this}
{4022}{}{You're not going to win this fight}
{4023}{}{}
{4024}{}{You can't win...}
{4025}{}{Now it's my turn}
{4026}{}{Don't you get it? You won't win!}
{4027}{}{We aren't easy to kill}
{4028}{}{Aggghh! Right in the face.}
{4029}{}{My face!}
{4030}{}{Du bröt min näsa!}
{4031}{}{Aggghh! My arm!}
{4032}{}{Ow! That hurt!}
{4033}{}{Damn. I may be hurt bad}
{4034}{}{Aggghh! My arm!}
{4035}{}{Ow! That hurt!}
{4036}{}{Damn. I may be hurt bad}
{4037}{}{Ow! That was painful}
{4038}{}{}
{4039}{}{Oof! You gotta do better than that}
{4040}{}{Ouch! You think you can turn me from my cause that easily!?}
{4041}{}{Ouch!}
{4042}{}{Argh!}
{4043}{}{Oof!}
{4044}{}{[Gasp!]}
{4045}{}{}
{4047}{}{Aggghh! My leg!}
{4048}{}{Damn, right in the knee...}
{4049}{}{Aggghh! Can barely stand...}
{4050}{}{Aggghh! My leg!}
{4051}{}{Damn, right in the knee...}
{4052}{}{Aggghh! Can barely stand...}
{4053}{}{I've been blinded! Somebody help me!}
{4054}{}{}
{4055}{}{Jag kan inte se!}
{4056}{}{Åååååå, mitt skrev!}
{4057}{}{}
{4058}{}{Förbannat!}
{4059}{}{I...can't...breathe...}
{4060}{}{}
{4061}{}{You punk!}
{4100}{}{}
{4101}{}{Somebody help!}
{4102}{}{}
{4103}{}{Retreat! Retreat!}
{4104}{}{Fall back! Fall back!}
{4105}{}{Hjälp!}
{4106}{}{}
{4107}{}{I think we have a problem}
{4108}{}{Let's see if I can take this out quickly}
{4109}{}{Better to take care of them out here}
{4110}{}{That looks like some serious firepower}
{4111}{}{You're messing with the wrong people}
{4112}{}{You should have run when you had the chance}
{4113}{}{Time to finish this}
{4114}{}{}
{4115}{}{You'll be no threat after this}
{4116}{}{}
{4117}{}{}
{4118}{}{}
{4119}{}{One less vermin in L.A. Boneyard}
{4120}{}{}
{4121}{}{you're not walking away from this}
{4122}{}{You're not going to win}
{4123}{}{}
{4124}{}{}
{4125}{}{Now it's my turn}
{4126}{}{You can't win!}
{4127}{}{}
{4128}{}{Aggghh!}
{4129}{}{}
{4130}{}{My face!}
{4131}{}{Aggghh! My arm!}
{4132}{}{Well, that limb's bloody useless...}
{4133}{}{Damn. I may be hurt bad}
{4134}{}{Aggghh! My arm!}
{4135}{}{Well, that limb's bloody useless...}
{4136}{}{Damn. I may be hurt bad}
{4137}{}{Aaugh! Gotta warn the rest about you}
{4138}{}{Oof! Gotta live, gotta live...}
{4139}{}{}
{4140}{}{Oof!}
{4141}{}{Bah!}
{4142}{}{Ack!}
{4143}{}{Aj!}
{4144}{}{}
{4145}{}{}
{4146}{}{}
{4147}{}{Aggghh! My leg!}
{4148}{}{Damn, right in the knee...}
{4149}{}{Aggghh! Can barely stand...}
{4150}{}{Aggghh! My leg!}
{4151}{}{Damn, right in the knee...}
{4152}{}{Aggghh! Can barely stand...}
{4153}{}{I'm blind! Maybe if I wipe away the blood...}
{4154}{}{Damn, right in the eyes!}
{4155}{}{Jag kan inte se!}
{4156}{}{}
{4157}{}{Eegah!}
{4158}{}{}
{4159}{}{I...can't...breathe...}
{4160}{}{}
{4161}{}{}
{4200}{}{}
{4201}{}{Not enough cover, and I'm hurt bad!}
{4202}{}{}
{4203}{}{}
{4204}{}{Fall back! Fall back!}
{4205}{}{Somebody cover me!}
{4206}{}{}
{4207}{}{}
{4208}{}{Defend the settlement!}
{4209}{}{}
{4210}{}{Inkräktare!}
{4211}{}{You just signed your death warrant}
{4212}{}{}
{4213}{}{}
{4214}{}{}
{4215}{}{You won't be a threat after this...}
{4216}{}{This is going to hurt}
{4217}{}{I'm putting you away...}
{4218}{}{}
{4219}{}{One less vermin in L.A. Boneyard}
{4220}{}{}
{4221}{}{You ain't walking away from this}
{4222}{}{You're not going to win this fight}
{4223}{}{}
{4224}{}{}
{4225}{}{Now it's my turn}
{4226}{}{You just made a big mistake}
{4227}{}{}
{4228}{}{Förbannat!}
{4229}{}{}
{4230}{}{I think my nose is busted}
{4231}{}{Min arm!}
{4232}{}{}
{4233}{}{I may be hurt bad...}
{4234}{}{Min arm!}
{4235}{}{Well, that limb's bloody useless...}
{4236}{}{Damn! I may be hurt bad...}
{4237}{}{}
{4238}{}{}
{4239}{}{}
{4240}{}{Oof!}
{4241}{}{Bah!}
{4242}{}{Ack!}
{4243}{}{Aj!}
{4244}{}{Oof! That may have hurt me}
{4245}{}{Dammit, that hurt!}
{4246}{}{}
{4247}{}{Mitt ben!}
{4248}{}{Damn, right in the knee...}
{4249}{}{Aggghh! Can barely stand...}
{4250}{}{Mitt ben!}
{4251}{}{Damn, right in the knee...}
{4252}{}{Aggghh! Can barely stand...}
{4253}{}{I'm blind!}
{4254}{}{Damn, right in the eyes!}
{4255}{}{Jag kan inte se!}
{4256}{}{Urgh! My jewels!}
{4257}{}{}
{4258}{}{That hurts like hell!}
{4259}{}{I...can't...breathe...}
{4260}{}{}
{4261}{}{}
{4300}{}{Gotta find a better position...}
{4301}{}{Not enough cover, and I'm hurt bad...}
{4302}{}{This isn't over!}
{4303}{}{Better regroup...}
{4304}{}{Fall back!}
{4305}{}{Brute force won't win this fight}
{4306}{}{I'll handle this}
{4307}{}{This isn't going to be pretty!}
{4308}{}{Defend the settlement!}
{4309}{}{We can't let this scum stop our mission!}
{4310}{}{}
{4311}{}{}
{4312}{}{I take no joy in this}
{4313}{}{Time to finish this}
{4314}{}{}
{4315}{}{You shouldn't have come here}
{4316}{}{This is going to hurt}
{4317}{}{I won't let you destroy what we've built}
{4318}{}{}
{4319}{}{I'm sorry I have to do this}
{4320}{}{Damn you for making me do this!}
{4321}{}{I pity you}
{4322}{}{I can't let you win}
{4323}{}{You're as clumsy as you are violent}
{4324}{}{We know how to take care of ourselves}
{4325}{}{Now it's my turn}
{4326}{}{That's your last mistake}
{4327}{}{}
{4328}{}{Damn. That smarts}
{4329}{}{Cheekbone's cracked. Can't let it stop me.}
{4330}{}{I think my nose is busted}
{4331}{}{Min arm!}
{4332}{}{Limb's useless. Gotta keep going}
{4333}{}{Damn! I may be hurt bad}
{4334}{}{Min arm!}
{4335}{}{Limb's useless. Gotta keep going}
{4336}{}{Damn! I may be hurt bad}
{4337}{}{}
{4338}{}{Oof!}
{4339}{}{}
{4340}{}{}
{4341}{}{[Gasp!]}
{4342}{}{Ack!}
{4343}{}{Aj!}
{4344}{}{Oof! You may defeat me, but the cause will live on}
{4345}{}{Argh!}
{4346}{}{}
{4347}{}{Mitt ben!}
{4348}{}{Damn, right in the knee...}
{4349}{}{}
{4350}{}{Mitt ben!}
{4351}{}{Damn, right in the knee...}
{4352}{}{Leg's gone, but I can still fight!}
{4353}{}{I'm blind! Can't let it stop me...}
{4354}{}{I'm blind!}
{4355}{}{Jag kan inte se!}
{4356}{}{AAUGH!!}
{4357}{}{}
{4358}{}{Oof!}
{4359}{}{}
{4360}{}{Eegah!}
{4361}{}{}
{4400}{}{You gonna die soon!}
{4401}{}{I'll be back!}
{4402}{}{Later punk!}
{4403}{}{}
{4404}{}{I'm saving you for later!}
{4405}{}{}
{4406}{}{I am going to rip your head off!}
{4407}{}{Fresh meat!}
{4408}{}{}
{4409}{}{}
{4410}{}{I will eat you, one piece at a time!}
{4411}{}{}
{4412}{}{I'm gonna carve you like an iguana-on-a-stick!}
{4413}{}{}
{4414}{}{Don't die yet - I want you to suffer.}
{4415}{}{You have offended the King of L.A. Boneyard!}
{4416}{}{}
{4417}{}{You'll be so pretty when you're dead}
{4418}{}{Die! Die! Die! Die! Die!}
{4419}{}{}
{4420}{}{You're gonna be feeding the worms tonight.}
{4421}{}{I'll skin you alive!}
{4422}{}{}
{4423}{}{C'mon! Bring it on, scag!}
{4424}{}{C'mon punk. Give me a fight!}
{4425}{}{Is that the best you can do?}
{4426}{}{You are nothing!}
{4427}{}{I cannot be killed!}
{4428}{}{}
{4429}{}{}
{4430}{}{Ack!}
{4431}{}{I love the sound of bones crunching}
{4432}{}{}
{4433}{}{I like it rough, bim!}
{4434}{}{Min arm!}
{4435}{}{}
{4436}{}{Bastard! My arm!}
{4437}{}{My chest!}
{4438}{}{Argh! That was your last mistake}
{4439}{}{}
{4440}{}{[Gasp!]}
{4441}{}{Bah!}
{4442}{}{Ack! That's gonna leave a bruise}
{4443}{}{Aj!}
{4444}{}{Fool!}
{4445}{}{We can trade blows all day long}
{4446}{}{}
{4447}{}{I love the sound of bones crunching}
{4448}{}{}
{4449}{}{}
{4450}{}{Mitt ben!}
{4451}{}{}
{4452}{}{Damn you!}
{4453}{}{}
{4454}{}{I'll just have to smell your fear!}
{4455}{}{My eyes! Man, I like the way you fight}
{4456}{}{Ack! My groin!}
{4457}{}{}
{4458}{}{Oooo! Is that a proposal, baby?}
{4459}{}{}
{4460}{}{So that's the way you want to play it}
{4461}{}{}
{4500}{}{I'm outta here!}
{4501}{}{}
{4502}{}{}
{4503}{}{You ain't won!}
{4504}{}{}
{4505}{}{See you around}
{4506}{}{Attack!}
{4507}{}{You're history!}
{4508}{}{You messin' with the wrong gang!}
{4509}{}{Nobody muscles in on our turf!}
{4510}{}{}
{4511}{}{}
{4512}{}{I am your Master!}
{4513}{}{Dö!}
{4514}{}{Scab}
{4515}{}{This is why they call us Blades}
{4516}{}{I'm gonna write your epitaph}
{4517}{}{Hope this hurts}
{4518}{}{}
{4519}{}{}
{4520}{}{I'll bury you}
{4521}{}{You're dead}
{4522}{}{I am more righteous than God!}
{4523}{}{}
{4524}{}{Show me some balls!}
{4525}{}{You're as weak as a Ripper!}
{4526}{}{}
{4527}{}{You ain't no Blade!}
{4528}{}{}
{4529}{}{Mina ögon!}
{4530}{}{Ow! Busted my nose!}
{4531}{}{Aj!}
{4532}{}{Ow! My arm!}
{4533}{}{Ow! You broke it!}
{4534}{}{Aj!}
{4535}{}{Ow! My arm!}
{4536}{}{Ow! You broke it!}
{4537}{}{Aj!}
{4538}{}{Ow! My chest!}
{4539}{}{Oof! My ribs!}
{4540}{}{Grymt}
{4541}{}{I laugh at my pain!}
{4542}{}{[Gasp!]}
{4543}{}{Is that as hard as you hit?}
{4544}{}{}
{4545}{}{Oof!}
{4546}{}{}
{4547}{}{Aj!}
{4548}{}{Ow! My knee!}
{4549}{}{Ow! My leg!}
{4550}{}{Aj!}
{4551}{}{Ow! My knee!}
{4552}{}{Ow! My leg!}
{4553}{}{I'm blind!}
{4554}{}{Jag kan inte se!}
{4555}{}{My eyes! Son of a Ripper...}
{4556}{}{Åååååå, mitt skrev!}
{4557}{}{Aieee!}
{4558}{}{Damn that hurts}
{4559}{}{Ooof!}
{4560}{}{I'm gonna tear you to pieces}
{4561}{}{I...can't...breathe...}
{4600}{}{}
{4601}{}{}
{4602}{}{It's just a reprieve, punk!}
{4603}{}{You ain't won!}
{4604}{}{Don't laugh! I'm gonna piss on your grave}
{4605}{}{See you around}
{4606}{}{}
{4607}{}{}
{4608}{}{You messin' with the wrong gang!}
{4609}{}{}
{4610}{}{}
{4611}{}{Dö!}
{4612}{}{}
{4613}{}{Dö!}
{4614}{}{}
{4615}{}{How big you want the scar?}
{4616}{}{}
{4617}{}{Hope this hurts}
{4618}{}{}
{4619}{}{}
{4620}{}{I'll bury you}
{4621}{}{You're dead}
{4622}{}{I am your Master!}
{4623}{}{}
{4624}{}{Show me some balls!}
{4625}{}{I own you!}
{4626}{}{}
{4627}{}{}
{4628}{}{That hurt}
{4629}{}{Mina ögon!}
{4630}{}{Ow! My nose...}
{4631}{}{Aj!}
{4632}{}{Ow! My arm!}
{4633}{}{Ow! You broke it!}
{4634}{}{Aj!}
{4635}{}{Ow! My arm!}
{4636}{}{Ow! You broke it!}
{4637}{}{Aj!}
{4638}{}{Ow! My chest!}
{4639}{}{Oof! My ribs!}
{4640}{}{Grymt}
{4641}{}{Ha! I laugh at the pain!}
{4642}{}{[Gasp!]}
{4643}{}{}
{4644}{}{}
{4645}{}{Oof!}
{4646}{}{Oh, yeah, that woke me up!}
{4647}{}{Aj!}
{4648}{}{Ow! My knee!}
{4649}{}{Ow! My leg!}
{4650}{}{Aj!}
{4651}{}{Ow! My knee!}
{4652}{}{Ow! My leg!}
{4653}{}{I'm blind!}
{4654}{}{Jag kan inte se!}
{4655}{}{My eyes! Son of a Ripper...}
{4656}{}{Åååååå, mitt skrev!}
{4657}{}{Aieee!}
{4658}{}{Damn that hurts}
{4659}{}{Ooof!}
{4660}{}{I'm gonna tear you to pieces}
{4661}{}{I...can't...breathe...}
{4700}{}{}
{4701}{}{Maybe this wasn't a good idea}
{4702}{}{}
{4703}{}{}
{4704}{}{I ain't dyin' for this!}
{4705}{}{I can't believe what they're packing...}
{4706}{}{Time to rip a clip...}
{4707}{}{Somebody just made a big mistake!}
{4708}{}{}
{4709}{}{Who do you think you are?}
{4710}{}{Time to demonstrate the merchandise}
{4711}{}{}
{4712}{}{}
{4713}{}{Target practice!}
{4714}{}{}
{4715}{}{How do you like this?}
{4716}{}{}
{4717}{}{How's this for firepower?}
{4718}{}{Let's see how you handle this...}
{4719}{}{}
{4720}{}{}
{4721}{}{Ride my bullet back to hell!}
{4722}{}{}
{4723}{}{}
{4724}{}{You didn't expect that, did you?}
{4725}{}{That was your last mistake}
{4726}{}{Amateur}
{4727}{}{Your moves are weak!}
{4728}{}{Aj! Din jävla...}
{4729}{}{I'm gonna kill you for that}
{4730}{}{Jag ska hugga huvudet av dig!}
{4731}{}{Ow, my arm!}
{4732}{}{Damn. My arm's busted!}
{4733}{}{Min arm!}
{4734}{}{Ow, my arm!}
{4735}{}{Damn. My arm's busted!}
{4736}{}{Min arm!}
{4737}{}{Aj!}
{4738}{}{Ow! My chest!}
{4739}{}{Oof! My ribs!}
{4740}{}{}
{4741}{}{}
{4742}{}{}
{4743}{}{}
{4744}{}{That might require medical attention...}
{4745}{}{}
{4746}{}{Oof!}
{4747}{}{Ow, my leg!}
{4748}{}{You shall pay for that!}
{4749}{}{My knee!}
{4750}{}{Ow, my leg!}
{4751}{}{You will pay for that!}
{4752}{}{My knee!}
{4753}{}{Jag kan inte se!}
{4754}{}{Mitt öga! Det där ska du få betala för!}
{4755}{}{}
{4756}{}{Åååååå, mitt skrev!}
{4757}{}{So that's the way you want to play}
{4758}{}{}
{4759}{}{Urp!}
{4760}{}{}
{4761}{}{Swine!}
{4800}{}{I need reinforcements!}
{4801}{}{Somebody help me!}
{4802}{}{Medic!}
{4803}{}{Retreat! Retreat!}
{4804}{}{Fall back! Fall back!}
{4805}{}{Regroup!}
{4806}{}{I'll take care of this}
{4807}{}{We are under attack!}
{4808}{}{}
{4809}{}{Attack!}
{4810}{}{}
{4811}{}{To arms! To arms!}
{4812}{}{This is for Adytum!}
{4813}{}{This is what we do to animals!}
{4814}{}{Welcome to hell, punk}
{4815}{}{Enjoy the last few seconds of your life...}
{4816}{}{You'll never bother anyone again}
{4817}{}{}
{4818}{}{You should not have started this}
{4819}{}{}
{4820}{}{}
{4821}{}{You're done, punk!}
{4822}{}{}
{4823}{}{You're aiming wild, punk}
{4824}{}{}
{4825}{}{}
{4826}{}{You were joking with that one, right?}
{4827}{}{I'm not easy to kill...}
{4828}{}{Damn! Right in the face.}
{4829}{}{My face!}
{4830}{}{My nose!}
{4831}{}{Damn! My arm!}
{4832}{}{Ow! That hurt!}
{4833}{}{Damn. I may be hurt bad}
{4834}{}{Damn! My arm!}
{4835}{}{Ow! That hurt!}
{4836}{}{Damn. I may be hurt bad}
{4837}{}{Aj!}
{4838}{}{Ow! Right in the chest!}
{4839}{}{Oof! Got me in the ribs!}
{4840}{}{Oof!}
{4841}{}{}
{4842}{}{Oof! Right in the gut!}
{4843}{}{Argh!}
{4844}{}{Ouch!}
{4845}{}{Oof!}
{4846}{}{I... need... air...}
{4847}{}{Lucky shot!}
{4848}{}{Damn, right in the knee...}
{4849}{}{I'm not falling over, punk.}
{4850}{}{Lucky shot!}
{4851}{}{Damn, right in the knee...}
{4852}{}{I'm not falling over, punk.}
{4853}{}{Damn, this ain't good...}
{4854}{}{Damn, right in the eyes!}
{4855}{}{Jag kan inte se!}
{4856}{}{Åååååå, mitt skrev!}
{4857}{}{}
{4858}{}{Damn that hurts!}
{4859}{}{I...can't...breathe...}
{4860}{}{You sadistic son of a...}
{4861}{}{You punk...}
{4900}{}{Gotta get outta here!}
{4901}{}{}
{4902}{}{Mercy! Mercy!}
{4903}{}{}
{4904}{}{}
{4905}{}{}
{4906}{}{Why do these things happen to me?!}
{4907}{}{Where's my backup?}
{4908}{}{I could use some help here!}
{4909}{}{}
{4910}{}{}
{4911}{}{}
{4912}{}{Don't take this personally}
{4913}{}{}
{4914}{}{}
{4915}{}{}
{4916}{}{I guess I have to hurt you}
{4917}{}{Please go down}
{4918}{}{Please don't kill me for this}
{4919}{}{}
{4920}{}{I think I'm going to be sick}
{4921}{}{}
{4922}{}{I'm alive! I'm alive!}
{4923}{}{}
{4924}{}{You need to aim a little more to the right}
{4925}{}{}
{4926}{}{This isn't your day.}
{4927}{}{}
{4928}{}{Not in the face!}
{4929}{}{Ow! My head!}
{4930}{}{Du bröt min näsa!}
{4931}{}{Ow, my arm!}
{4932}{}{You broke my arm!}
{4933}{}{Was that really necessary?}
{4934}{}{Ow, my arm!}
{4935}{}{You broke my arm!}
{4936}{}{Was that really necessary?}
{4937}{}{Oof!}
{4938}{}{Ow! That hurt me! A lot!}
{4939}{}{}
{4940}{}{[Gasp!] Don't hit me!}
{4941}{}{Ack! That hurt!}
{4942}{}{Argh! Please stop!}
{4943}{}{Ouch!}
{4944}{}{Oof!}
{4945}{}{Oof!}
{4946}{}{Oof! [Gasp!] Argh! Ow! Owie!}
{4947}{}{Ow, my leg!}
{4948}{}{Hey, that hurt!}
{4949}{}{}
{4950}{}{Ow, my leg!}
{4951}{}{Hey, that hurt!}
{4952}{}{Was that really necessary?}
{4953}{}{Argh! My retina!}
{4954}{}{My eye! Oh my god, I'm blind!}
{4955}{}{Why is life so cruel!}
{4956}{}{Åååååå, mitt skrev!}
{4957}{}{Ooo! That hurt!}
{4958}{}{That was most unfriendly.}
{4959}{}{}
{4960}{}{Urp!}
{4961}{}{}
{5000}{}{I'm outta here!}
{5001}{}{}
{5002}{}{Aaaaahhhh!}
{5003}{}{}
{5004}{}{}
{5005}{}{See you around}
{5006}{}{}
{5007}{}{}
{5008}{}{Somebody gotta be taught a lesson}
{5009}{}{Somebody's dyin'}
{5010}{}{}
{5011}{}{}
{5012}{}{}
{5013}{}{Dö!}
{5014}{}{Death and fire!}
{5015}{}{Punk}
{5016}{}{Atom fire!}
{5017}{}{}
{5018}{}{Never shoulda messed with us}
{5019}{}{To the Glow w' you!}
{5020}{}{I'm gonna seal your tomb}
{5021}{}{You're dead!}
{5022}{}{}
{5023}{}{Not impressed}
{5024}{}{}
{5025}{}{I'm building your tomb}
{5026}{}{You ain't burying me!}
{5027}{}{What did you expect?}
{5028}{}{}
{5029}{}{Mina ögon!}
{5030}{}{Aj!}
{5031}{}{Aj!}
{5032}{}{Ow! My arm!}
{5033}{}{Ow! You broke it!}
{5034}{}{Aj!}
{5035}{}{Ow! My arm!}
{5036}{}{}
{5037}{}{Aj!}
{5038}{}{Oof!}
{5039}{}{Ouch!}
{5040}{}{Gack!}
{5041}{}{Argh!}
{5042}{}{Grrr!}
{5043}{}{}
{5044}{}{I will eat your liver for that!}
{5045}{}{}
{5046}{}{Oof!}
{5047}{}{Aj!}
{5048}{}{Ow! My knee!}
{5049}{}{Ow! My leg!}
{5050}{}{Aj!}
{5051}{}{Ow! My knee!}
{5052}{}{Ow! My leg!}
{5053}{}{I'm blind!}
{5054}{}{Jag kan inte se!}
{5055}{}{My eye!}
{5056}{}{Åååååå, mitt skrev!}
{5057}{}{Ooo! That hurt!}
{5058}{}{That was most unfriendly.}
{5059}{}{}
{5060}{}{Urp!}
{5061}{}{}
{5100}{}{Retreat!}
{5101}{}{Withdraw!}
{5102}{}{Regroup!}
{5103}{}{This isn't over!}
{5104}{}{I shall return!}
{5105}{}{We'll be back!}
{5106}{}{}
{5107}{}{}
{5108}{}{Get the intruder!}
{5109}{}{Death to the human!}
{5110}{}{}
{5111}{}{}
{5112}{}{To the Glow w' you!}
{5113}{}{}
{5114}{}{Filthy human!}
{5115}{}{}
{5116}{}{}
{5117}{}{Death and fire!}
{5118}{}{You will burn!}
{5119}{}{}
{5120}{}{You shall fall and never rise again!}
{5121}{}{I'm gonna seal your tomb}
{5122}{}{Missed}
{5123}{}{Nobody seals my tomb!}
{5124}{}{You're no fighter}
{5125}{}{}
{5126}{}{You won't win, human}
{5127}{}{}
{5128}{}{That hurt}
{5129}{}{Mina ögon!}
{5130}{}{Aghh!}
{5131}{}{Aghh!}
{5132}{}{Ow! My arm!}
{5133}{}{Ow! You broke it!}
{5134}{}{Aghh!}
{5135}{}{Ow! My arm!}
{5136}{}{Ow! You broke it!}
{5137}{}{Aj!}
{5138}{}{Oof!}
{5139}{}{Ouch!}
{5140}{}{Gack!}
{5141}{}{Argh!}
{5142}{}{Grrr!}
{5143}{}{Oof! You scrags are all alike}
{5144}{}{I will eat your liver for that!}
{5145}{}{}
{5146}{}{Oof!}
{5147}{}{Aghh!}
{5148}{}{Ow! My knee!}
{5149}{}{Ow! My leg!}
{5150}{}{Aghh!}
{5151}{}{Ow! My knee!}
{5152}{}{Ow! My leg!}
{5153}{}{Curse you with fire!}
{5154}{}{Jag kan inte se!}
{5155}{}{My eye!}
{5156}{}{Åååååå, mitt skrev!}
{5157}{}{Ooof!}
{5158}{}{I shall deface your tomb!}
{5159}{}{}
{5160}{}{Urp!}
{5161}{}{}
{5200}{}{Spring!}
{5201}{}{You will not kill me!}
{5202}{}{I will be back!}
{5203}{}{My friends get you for me!}
{5204}{}{You pay for this - later!}
{5205}{}{We are Chosen! You die later!}
{5206}{}{Your death comes!}
{5207}{}{Those who bother Chosen, bother no one again!}
{5208}{}{Human weapons cannot harm me!}
{5209}{}{You will suffer, suffer great!}
{5210}{}{}
{5211}{}{Who is stupid enough to anger us?}
{5212}{}{}
{5213}{}{Nobody save you now!}
{5214}{}{}
{5215}{}{Now you die burning death!}
{5216}{}{Die Human Fool!}
{5217}{}{Now you die a screaming death}
{5218}{}{}
{5219}{}{Now I crush you}
{5220}{}{You cannot fight the Chosen!}
{5221}{}{Suffer, human!}
{5222}{}{Why do you struggle?}
{5223}{}{Is that best humans can do!}
{5224}{}{You have no power!}
{5225}{}{You make me laugh hard!}
{5226}{}{Was that an attack?}
{5227}{}{We are the Chosen!}
{5228}{}{Ahhhgh! My face!}
{5229}{}{My face! You shall suffer!}
{5230}{}{Ahhhgh! I rend you into bits!}
{5231}{}{Ahhhgh!}
{5232}{}{}
{5233}{}{Ahhhgh! I snap your neck for that!}
{5234}{}{Ahhhgh!}
{5235}{}{}
{5236}{}{Ahhhgh! I snap your neck for that!}
{5237}{}{Oof!}
{5238}{}{Grrr!}
{5239}{}{I kill you for that!}
{5240}{}{You no hurt me when you dead!}
{5241}{}{I laugh at your feeble attack!}
{5242}{}{Grrr!}
{5243}{}{Oh!}
{5244}{}{I'm gonna dip you!}
{5245}{}{Grrr! You anger me}
{5246}{}{Agh!}
{5247}{}{Ahhhgh! My leg!}
{5248}{}{}
{5249}{}{Ahhhgh! I snap your neck for that!}
{5250}{}{Ahhhgh! My leg!}
{5251}{}{}
{5252}{}{Ahhhgh! I shall snap your neck for that!}
{5253}{}{Ahhhgh! Miserable human! I am blind!}
{5254}{}{Ahhhgh! Pain! What have you done!}
{5255}{}{Ahhhgh! I will torture you many days!}
{5256}{}{That is human weakness!}
{5257}{}{}
{5258}{}{You are stupid, human!}
{5259}{}{Why you attack me there?}
{5260}{}{I will hurt you for many hours}
{5261}{}{}
{5300}{}{Spring!}
{5301}{}{You will not kill me!}
{5302}{}{Must escape}
{5303}{}{}
{5304}{}{You pay for this - later!}
{5305}{}{You die later!}
{5306}{}{Who dare bother Chosen?}
{5307}{}{You make me angry!}
{5308}{}{Human weapons cannot harm me!}
{5309}{}{}
{5310}{}{No mercy to enemies!}
{5311}{}{When I fight, I kill!}
{5312}{}{}
{5313}{}{Nobody save you now!}
{5314}{}{Now you die!}
{5315}{}{Let me see your pain!}
{5316}{}{I break your body!}
{5317}{}{}
{5318}{}{}
{5319}{}{Now you die}
{5320}{}{I hurt you much!}
{5321}{}{Suffer!}
{5322}{}{You are weak!}
{5323}{}{You are feeble...}
{5324}{}{You have no power!}
{5325}{}{}
{5326}{}{Was that an attack?}
{5327}{}{You are useless}
{5328}{}{Ahhhgh! My face!}
{5329}{}{My face! You shall suffer!}
{5330}{}{Ahhhgh! I rend you into bits!}
{5331}{}{Ahhhgh!}
{5332}{}{Ow! You almost hurt Chosen!}
{5333}{}{Ahhhgh! I snap your neck for that!}
{5334}{}{Ahhhgh!}
{5335}{}{}
{5336}{}{Ahhhgh! I snap your neck for that!}
{5337}{}{I will return this pain to you!}
{5338}{}{Oof!}
{5339}{}{Ouch!}
{5340}{}{Hmm, you might be trouble}
{5341}{}{Grrr! I look forward to your death}
{5342}{}{Grrr!}
{5343}{}{You can hurt me but you cannot win!}
{5344}{}{Grrr!}
{5345}{}{Ow! That wasn't good idea to hurt me}
{5346}{}{}
{5347}{}{Ahhhgh! My leg!}
{5348}{}{}
{5349}{}{Ahhhgh! I snap your neck for that!}
{5350}{}{Ahhhgh! My leg!}
{5351}{}{You almost hurt Chosen!}
{5352}{}{Ahhhgh! I shall snap your neck for that!}
{5353}{}{Ahhhgh! I am blind!}
{5354}{}{Ahhhgh! Pain! What you do to me?}
{5355}{}{Ahhhgh! Eyes burn like Glow fire!}
{5356}{}{That is human weakness!}
{5357}{}{}
{5358}{}{}
{5359}{}{Why you attack me there?}
{5360}{}{Your death will be painful, human!}
{5361}{}{}
{5400}{}{Spring!}
{5401}{}{You will not kill me!}
{5402}{}{I will be back!}
{5403}{}{}
{5404}{}{You pay for this - later!}
{5405}{}{You die later!}
{5406}{}{Your death comes!}
{5407}{}{}
{5408}{}{Human weapons cannot harm me!}
{5409}{}{You will suffer, suffer great!}
{5410}{}{I see enemies to destroy!}
{5411}{}{Who is stupid enough to anger us?}
{5412}{}{}
{5413}{}{Nobody save you now!}
{5414}{}{We are your Masters!}
{5415}{}{Now you die a burning death!}
{5416}{}{Die Human Fool!}
{5417}{}{Now you die a screaming death}
{5418}{}{}
{5419}{}{Now I crush you}
{5420}{}{}
{5421}{}{Suffer, human!}
{5422}{}{Why do you struggle?}
{5423}{}{Is that best humans can do!}
{5424}{}{You have no power!}
{5425}{}{}
{5426}{}{}
{5427}{}{We are the Chosen!}
{5428}{}{Ahhhgh! My face!}
{5429}{}{My face! You shall suffer!}
{5430}{}{Ahhhgh! I rend you into bits!}
{5431}{}{Ahhhgh!}
{5432}{}{You call that pain? I laugh!}
{5433}{}{Ahhhgh! I snap your neck for that!}
{5434}{}{Ahhhgh!}
{5435}{}{You call that pain? I laugh!}
{5436}{}{Ahhhgh! I snap your neck for that!}
{5437}{}{There is no pain that can hurt me!}
{5438}{}{Oof! I kill you}
{5439}{}{I hate your kind!}
{5440}{}{}
{5441}{}{Argh!}
{5442}{}{Grrr!}
{5443}{}{Ow! I will take care of you myself!}
{5444}{}{}
{5445}{}{Grrr!}
{5446}{}{Oof!}
{5447}{}{Ahhhgh! My leg!}
{5448}{}{You call that pain? I laugh!}
{5449}{}{Ahhhgh! I snap your neck for that!}
{5450}{}{Ahhhgh! My leg!}
{5451}{}{You call that pain? I laugh!}
{5452}{}{Ahhhgh! I shall snap your neck for that!}
{5453}{}{Ahhhgh! Miserable human! I am blind!}
{5454}{}{Ahhhgh! Pain! What have you done!}
{5455}{}{Ahhhgh! I will torture you many days!}
{5456}{}{}
{5457}{}{}
{5458}{}{You are stupid human!}
{5459}{}{Why you attack me there?}
{5460}{}{I will hurt you for many hours}
{5461}{}{}
{5500}{}{Spring!}
{5501}{}{You will not kill me!}
{5502}{}{I will be back!}
{5503}{}{This is not over!}
{5504}{}{Your victory will be very short-lived human!}
{5505}{}{We are the Chosen! You will die later!}
{5506}{}{Step forward, for Death rides with us!}
{5507}{}{}
{5508}{}{Human weapons cannot harm us!}
{5509}{}{You will suffer!}
{5510}{}{None shall withstand us!}
{5511}{}{}
{5512}{}{}
{5513}{}{No one can save you}
{5514}{}{We are your Masters!}
{5515}{}{Now you die a Burning Death!}
{5516}{}{Die Human Fool!}
{5517}{}{Now you die a Screaming Death}
{5518}{}{Your blood is my wine!}
{5519}{}{Now I crush you}
{5520}{}{You cannot fight the Chosen!}
{5521}{}{Suffer, human!}
{5522}{}{Why do you fight so pitifully?}
{5523}{}{}
{5524}{}{Do you call this stumbling foolishness a fight?}
{5525}{}{Your attack only makes me laugh}
{5526}{}{}
{5527}{}{}
{5528}{}{Ahhhgh! My face!}
{5529}{}{My face! You shall suffer!}
{5530}{}{Ahhhgh! I rend you into bits!}
{5531}{}{Ahhhgh!}
{5532}{}{You call that pain? I laugh!}
{5533}{}{Ahhhgh! I snap your neck for that!}
{5534}{}{Ahhhgh!}
{5535}{}{}
{5536}{}{Ahhhgh! I snap your neck for that!}
{5537}{}{You cannot defeat me!}
{5538}{}{I will kill you for that!}
{5539}{}{Your death will be legendary!}
{5540}{}{Now I am angry!}
{5541}{}{Oof!}
{5542}{}{Grrr!}
{5543}{}{Oof! You cannot survive}
{5544}{}{}
{5545}{}{You have no idea what you are dealing with, human}
{5546}{}{I will wash my face with your blood!}
{5547}{}{Ahhhgh! My leg!}
{5548}{}{}
{5549}{}{Ahhhgh! I snap your neck for that!}
{5550}{}{Ahhhgh! My leg!}
{5551}{}{}
{5552}{}{Ahhhgh! I shall snap your neck for that!}
{5553}{}{Ahhhgh! Miserable human! I am blind!}
{5554}{}{Ahhhgh! But I do not need eyes to kill you.}
{5555}{}{Ahhhgh! I will torture you many days!}
{5556}{}{That is human weakness!}
{5557}{}{}
{5558}{}{You are stupid human!}
{5559}{}{Why you attack me there?}
{5560}{}{I will hurt you for many hours}
{5561}{}{That was the final affront!}
{5600}{}{I'm outta here!}
{5601}{}{Have mercy!}
{5602}{}{Please stop!}
{5603}{}{Hjälp!}
{5604}{}{Aaaaahhhh!}
{5605}{}{Run away!}
{5606}{}{}
{5607}{}{You're not giving us much choice!}
{5608}{}{Who do you think you are?}
{5609}{}{Nobody's taking this place over...}
{5610}{}{We could have made a deal}
{5611}{}{That was a bad move, my friend}
{5612}{}{Shouldn't start what you can't finish}
{5613}{}{You asked for this!}
{5614}{}{}
{5615}{}{I know how to deal with swine!}
{5616}{}{You'll pay for what you've done!}
{5617}{}{Your number is up!}
{5618}{}{}
{5619}{}{}
{5620}{}{Time to count your losses}
{5621}{}{}
{5622}{}{Whew!}
{5623}{}{You're not worth twenty caps}
{5624}{}{You're not very good at this}
{5625}{}{You're just a cut rate punk}
{5626}{}{You should just walk away!}
{5627}{}{}
{5628}{}{Not in the face!}
{5629}{}{}
{5630}{}{Ow! My ear!}
{5631}{}{Ow, my arm!}
{5632}{}{Damn you!}
{5633}{}{You broke my arm!}
{5634}{}{Ow, my arm!}
{5635}{}{Damn you!}
{5636}{}{You broke my arm!}
{5637}{}{Aj!}
{5638}{}{Oof!}
{5639}{}{Ouch!}
{5640}{}{Gack!}
{5641}{}{Argh!}
{5642}{}{}
{5643}{}{I should have made a deal!}
{5644}{}{Oof! I wonder how much I will get for your corpse?}
{5645}{}{Aj!}
{5646}{}{Oof!}
{5647}{}{Ow, my leg!}
{5648}{}{My knee!}
{5649}{}{Ow! My leg's busted!}
{5650}{}{Ow, my leg!}
{5651}{}{My knee!}
{5652}{}{Ow! My leg's busted!}
{5653}{}{I'm blind!}
{5654}{}{Ugggh. My face! My eyes!}
{5655}{}{My eyes! Damn you to hell...}
{5656}{}{Åååååå, mitt skrev!}
{5657}{}{Oooooo, that was a cheap one, punk.}
{5658}{}{Urp!}
{5659}{}{I...can't...breathe...}
{5660}{}{}
{5661}{}{Smärtan, smärtan...}
{5700}{}{I've gotta get out of here!}
{5701}{}{Run! Run!}
{5702}{}{Somebody help me!}
{5703}{}{We're all gonna die!}
{5704}{}{Someday, you'll get what's coming to you!}
{5705}{}{I ain't dyin' for this!}
{5706}{}{It's too late to run}
{5707}{}{Who let you in the Hub?}
{5708}{}{Hey you!}
{5709}{}{We don't like your kind around here!}
{5710}{}{Nobody's taking this place over...}
{5711}{}{Who do you think you are?}
{5712}{}{Take this!}
{5713}{}{How do you like this?}
{5714}{}{This is what we do to vermin!}
{5715}{}{This is for you!}
{5716}{}{Goodbye!}
{5717}{}{}
{5718}{}{Troublemaking scum!}
{5719}{}{}
{5720}{}{You animal!}
{5721}{}{You'll regret setting foot in the Hub!}
{5722}{}{You're not as good as you think}
{5723}{}{}
{5724}{}{You're just a common thug}
{5725}{}{}
{5726}{}{I'm not going to be your victim}
{5727}{}{That was your last mistake}
{5728}{}{}
{5729}{}{Aggghhh!}
{5730}{}{My face! My face!}
{5731}{}{Aggghhh! Min arm!}
{5732}{}{Min arm!}
{5733}{}{Damn arm's useless now...}
{5734}{}{Aggghhh! Min arm!}
{5735}{}{Min arm!}
{5736}{}{Damn arm's useless now...}
{5737}{}{Aj!}
{5738}{}{Oof!}
{5739}{}{Ouch!}
{5740}{}{Gack!}
{5741}{}{Argh!}
{5742}{}{Grrr!}
{5743}{}{!}
{5744}{}{}
{5745}{}{Ouch!}
{5746}{}{Oof!}
{5747}{}{Aggghhh! My leg!}
{5748}{}{Mitt ben!}
{5749}{}{Dammit, my leg's useless...}
{5750}{}{Aggghhh! My leg!}
{5751}{}{Mitt ben!}
{5752}{}{Dammit, my leg's useless...}
{5753}{}{Aggghhh! Jag är blind!}
{5754}{}{Dammit! Everything's burning...}
{5755}{}{Mitt öga! Det där ska du få betala för!}
{5756}{}{Åååååå, mitt skrev!}
{5757}{}{Åååååååååå!}
{5758}{}{I...can't...breathe...}
{5759}{}{}
{5760}{}{Smärtan, smärtan...}
{5761}{}{Fan, vad ont det gör!}
{5800}{}{}
{5801}{}{Run! Run!}
{5802}{}{I'm getting out of here!}
{5803}{}{I'm too young to die!}
{5804}{}{Into the shadows!}
{5805}{}{This fight is not going my way...}
{5806}{}{Let's nail this scoundrel!}
{5807}{}{Cry havoc!}
{5808}{}{Hey you!}
{5809}{}{I don't like your attitude...}
{5810}{}{Nobody's taking this place over...}
{5811}{}{Who do you think you are?}
{5812}{}{}
{5813}{}{How do you like this?}
{5814}{}{This is what we do to vermin!}
{5815}{}{I'm going to tuck you in for a dirt nap!}
{5816}{}{You insolent cur!}
{5817}{}{You're a real nuisance}
{5818}{}{You sicken me!}
{5819}{}{Death or glory!}
{5820}{}{You're going to make an awful mess}
{5821}{}{You'll regret setting foot in the Hub!}
{5822}{}{I'm lowering myself when I fight you}
{5823}{}{}
{5824}{}{You're just a common thug}
{5825}{}{}
{5826}{}{You really shouldn't have bothered}
{5827}{}{That was your last mistake}
{5828}{}{Damn that smarts!}
{5829}{}{Aggghhh!}
{5830}{}{My face! My beautiful face!}
{5831}{}{Aggghhh! Min arm!}
{5832}{}{Min arm!}
{5833}{}{Damn arm's useless now...}
{5834}{}{Aggghhh! Min arm!}
{5835}{}{Min arm!}
{5836}{}{Damn arm's useless now...}
{5837}{}{}
{5838}{}{Oof!}
{5839}{}{Ouch!}
{5840}{}{Oof! Mina revben gör ont}
{5841}{}{Crap! That hurt!}
{5842}{}{Ouch! Damn you!}
{5843}{}{Argh!}
{5844}{}{}
{5845}{}{}
{5846}{}{Oof!}
{5847}{}{Aggghhh! My leg!}
{5848}{}{Mitt ben!}
{5849}{}{Dammit, my leg's useless...}
{5850}{}{Aggghhh! My leg!}
{5851}{}{Mitt ben!}
{5852}{}{Dammit, my leg's useless...}
{5853}{}{Aggghhh! Jag är blind!}
{5854}{}{Dammit! Everything's burning...}
{5855}{}{What have you done to me!}
{5856}{}{Åååååå, mitt skrev!}
{5857}{}{You're nothing but a common thug!}
{5858}{}{}
{5859}{}{}
{5860}{}{}
{5861}{}{Fan, vad ont det gör!}
{5900}{}{I'm outta here!}
{5901}{}{Hej då!}
{5902}{}{Aaaaahhhh!}
{5903}{}{Later. Maybe.}
{5904}{}{}
{5905}{}{See you around}
{5906}{}{}
{5907}{}{Defend our homes!}
{5908}{}{Somebody gotta be taught a lesson}
{5909}{}{Somebody's dyin'}
{5910}{}{}
{5911}{}{Nobody messes with the Hub!}
{5912}{}{Take this!}
{5913}{}{Die and stay dead!}
{5914}{}{Drop dead!}
{5915}{}{Punk}
{5916}{}{You creep!}
{5917}{}{Hope this hurts}
{5918}{}{Never shoulda messed with us}
{5919}{}{To the Glow w' you!}
{5920}{}{Go to hell!}
{5921}{}{You're dead}
{5922}{}{Missed!}
{5923}{}{Not impressed}
{5924}{}{}
{5925}{}{I ain't that easy}
{5926}{}{Nobody's taking me down!}
{5927}{}{What did you expect?}
{5928}{}{That hurt}
{5929}{}{Ooo, my aching skull!}
{5930}{}{Aj!}
{5931}{}{Aj!}
{5932}{}{Ow! My arm!}
{5933}{}{Ow! My elbow!}
{5934}{}{Aj!}
{5935}{}{Ow! My arm!}
{5936}{}{Ow! My elbow!}
{5937}{}{Ow! My chest!}
{5938}{}{Oof!}
{5939}{}{Ouch!}
{5940}{}{}
{5941}{}{}
{5942}{}{Ouch! Damn you!}
{5943}{}{Argh!}
{5944}{}{Aj!}
{5945}{}{}
{5946}{}{Oof!}
{5947}{}{Aj!}
{5948}{}{Ow! My knee!}
{5949}{}{Ow! My leg!}
{5950}{}{Aj!}
{5951}{}{Ow! My knee!}
{5952}{}{Ow! My leg!}
{5953}{}{I'm blind!}
{5954}{}{Jag kan inte se!}
{5955}{}{My eye!}
{5956}{}{Åååååå, mitt skrev!}
{5957}{}{Ooo! That hurt!}
{5958}{}{}
{5959}{}{}
{5960}{}{Urp!}
{5961}{}{}
{6000}{}{Attack someone else, please!}
{6001}{}{Have mercy!}
{6002}{}{Somebody help me!}
{6003}{}{Please stop!}
{6004}{}{Maybe this wasn't a good idea}
{6005}{}{I ain't dyin' for this!}
{6006}{}{Wait 'til I get you...}
{6007}{}{}
{6008}{}{Hey you!}
{6009}{}{We don't like your kind around here!}
{6010}{}{}
{6011}{}{I'm gonna take you apart like a cheap watch}
{6012}{}{Take this!}
{6013}{}{How do you like this?}
{6014}{}{Dö!}
{6015}{}{You mutant freak!}
{6016}{}{I eat punks like you for breakfast}
{6017}{}{Gonna feed you to the dogs}
{6018}{}{}
{6019}{}{Fine. You asked for this.}
{6020}{}{}
{6021}{}{}
{6022}{}{You're not as good as you think}
{6023}{}{Is that the best you can do?}
{6024}{}{}
{6025}{}{}
{6026}{}{}
{6027}{}{Pitiful}
{6028}{}{Förbannat!}
{6029}{}{My aching skull}
{6030}{}{My face! My face!}
{6031}{}{Aggghhh! Min arm!}
{6032}{}{Min arm!}
{6033}{}{Åh jösses, det gör ont!}
{6034}{}{Aggghhh! Min arm!}
{6035}{}{Min arm!}
{6036}{}{}
{6037}{}{}
{6038}{}{Oof!}
{6039}{}{Ouch!}
{6040}{}{Oof! Mina revben gör ont}
{6041}{}{Ugh! Det där gjorde ont!}
{6042}{}{Fan också! Jag spottar på dig!}
{6043}{}{Argh!}
{6044}{}{Oh, my ribs!}
{6045}{}{Ow!!!}
{6046}{}{Oof!}
{6047}{}{Aggghhh! My leg!}
{6048}{}{Mitt ben!}
{6049}{}{Där försvann mitt knä}
{6050}{}{Aggghhh! My leg!}
{6051}{}{Mitt ben!}
{6052}{}{Där försvann mitt knä}
{6053}{}{Aggghhh! Jag är blind!}
{6054}{}{Mina ögon! Mina ögon!}
{6055}{}{Mitt öga! Det där ska du få betala för!}
{6056}{}{Åååååå, mitt skrev!}
{6057}{}{Åååååååååå!}
{6058}{}{I...can't...breathe...}
{6059}{}{}
{6060}{}{Smärtan, smärtan...}
{6061}{}{Fan, vad ont det gör!}
{6100}{}{I'm outta here!}
{6101}{}{Maybe this wasn't a good idea}
{6102}{}{Attack someone else, okay!}
{6103}{}{Yikes!}
{6104}{}{I ain't dyin' for this!}
{6105}{}{That's too much for me}
{6106}{}{Hey you!}
{6107}{}{I'm gonna teach you some manners}
{6108}{}{We don't like your kind around here!}
{6109}{}{You need to learn some respect!}
{6110}{}{Time to earn my pay...}
{6111}{}{Wait 'til I get you...}
{6112}{}{}
{6113}{}{}
{6114}{}{}
{6115}{}{How do you like this?}
{6116}{}{}
{6117}{}{}
{6118}{}{Let's see how tough you are...}
{6119}{}{Punk}
{6120}{}{Ride my bullet back to hell!}
{6121}{}{I'm putting you away for good}
{6122}{}{Your mama teach you that move?}
{6123}{}{}
{6124}{}{You ain't good enough}
{6125}{}{That was your last mistake}
{6126}{}{Amateur}
{6127}{}{You learn to fight in bars?}
{6128}{}{Aj! Din jävla...}
{6129}{}{Du bröt min näsa!}
{6130}{}{Jag ska hugga huvudet av dig!}
{6131}{}{Ow, my arm!}
{6132}{}{You just made the biggest mistake of your life}
{6133}{}{Min arm!}
{6134}{}{Ow, my arm!}
{6135}{}{You just made the biggest mistake of your life}
{6136}{}{Min arm!}
{6137}{}{Urp!}
{6138}{}{Oof!}
{6139}{}{Ouch!}
{6140}{}{}
{6141}{}{Ugh! Det där gjorde ont!}
{6142}{}{Ouch!}
{6143}{}{Argh!}
{6144}{}{Åh, jag tror att du bröt ett revben!}
{6145}{}{Aj!!! Min mjälte!}
{6146}{}{Oof!}
{6147}{}{Ow, my leg!}
{6148}{}{Jag behöver inte stå för att döda dig!}
{6149}{}{My knee!}
{6150}{}{Ow, my leg!}
{6151}{}{Jag behöver inte stå för att döda dig!}
{6152}{}{My knee!}
{6153}{}{Jag kan inte se!}
{6154}{}{This fight is getting worse by the second}
{6155}{}{That was a real cheap shot!}
{6156}{}{Åååååå, mitt skrev!}
{6157}{}{I'll feel that in the morning}
{6158}{}{}
{6159}{}{Urp!}
{6160}{}{}
{6161}{}{}
{6200}{}{We'll meet again. Bet on it}
{6201}{}{You owe me a rematch. Later}
{6202}{}{You won this round, but the game ain't over}
{6203}{}{I'll catch up with you later}
{6204}{}{If you know what's good for you, you'll get out of town}
{6205}{}{This ain't over, friend.}
{6206}{}{}
{6207}{}{I'm gonna teach you some manners}
{6208}{}{}
{6209}{}{You need to learn some respect!}
{6210}{}{}
{6211}{}{}
{6212}{}{}
{6213}{}{}
{6214}{}{}
{6215}{}{How do you like this?}
{6216}{}{}
{6217}{}{}
{6218}{}{Let's see how tough you are...}
{6219}{}{Punk}
{6220}{}{}
{6221}{}{I'm gonna kick your ass outta town}
{6222}{}{You're outta your league}
{6223}{}{}
{6224}{}{You ain't good enough}
{6225}{}{You should quit while you're still in one piece}
{6226}{}{Amateur}
{6227}{}{}
{6228}{}{Aj! Din jävla...}
{6229}{}{}
{6230}{}{Jag ska hugga huvudet av dig!}
{6231}{}{Ow, my arm!}
{6232}{}{You're beginning to piss me off}
{6233}{}{Min arm!}
{6234}{}{Ow, my arm!}
{6235}{}{You're beginning to piss me off}
{6236}{}{Min arm!}
{6237}{}{Ahh!}
{6238}{}{Oof!}
{6239}{}{Ouch!}
{6240}{}{Oof! Going for my kidneys, huh?}
{6241}{}{}
{6242}{}{}
{6243}{}{}
{6244}{}{Oh, my ribs!}
{6245}{}{}
{6246}{}{}
{6247}{}{Ow, my leg!}
{6248}{}{Nice shot. Wait 'til it's my turn}
{6249}{}{My knee!}
{6250}{}{Ow, my leg!}
{6251}{}{Nice shot. Wait 'til it's my turn}
{6252}{}{My knee!}
{6253}{}{Jag kan inte se!}
{6254}{}{This fight is getting worse by the second}
{6255}{}{}
{6256}{}{Aaaaaugh!!!}
{6257}{}{}
{6258}{}{Hey, keep it above the belt}
{6259}{}{Urp!}
{6260}{}{}
{6261}{}{}
{6300}{}{Gotta get outta here!}
{6301}{}{I'll be back...}
{6302}{}{You're gonna pay for what you've done!}
{6303}{}{Later punk!}
{6304}{}{You ain't heard the last of me!}
{6305}{}{You'll pay for this - later!}
{6306}{}{}
{6307}{}{Fresh meat...}
{6308}{}{I'm gonna dance on your grave}
{6309}{}{Time to rip a clip...}
{6310}{}{It's killing time!}
{6311}{}{}
{6312}{}{}
{6313}{}{Feel free to scream}
{6314}{}{Gonna enjoy this.}
{6315}{}{}
{6316}{}{Gonna feed you to the dogs}
{6317}{}{Nobody's taking Junktown away from us}
{6318}{}{}
{6319}{}{I'm gonna get a bonus for this}
{6320}{}{Dö!}
{6321}{}{I eat punks like you for breakfast}
{6322}{}{}
{6323}{}{Is that the best you can do?}
{6324}{}{}
{6325}{}{Try aiming next time...}
{6326}{}{}
{6327}{}{Loser}
{6328}{}{Not in the face!}
{6329}{}{Ah, my head hurts}
{6330}{}{Du bröt min näsa!}
{6331}{}{Ow, my arm!}
{6332}{}{You broke my arm!}
{6333}{}{}
{6334}{}{Ow, my arm!}
{6335}{}{You broke my arm!}
{6336}{}{}
{6337}{}{Ouch! That hurt}
{6338}{}{Oof!}
{6339}{}{Ouch!}
{6340}{}{}
{6341}{}{Ugh! Det där gjorde ont!}
{6342}{}{}
{6343}{}{Oof!}
{6344}{}{I'm gonna kick you in the ribs for that}
{6345}{}{Ah!}
{6346}{}{Oof!}
{6347}{}{Ow, my leg!}
{6348}{}{You're gonna pay for that!}
{6349}{}{Oh, my knee!}
{6350}{}{Ow, my leg!}
{6351}{}{}
{6352}{}{Oh, my knee}
{6353}{}{Argh!}
{6354}{}{My eyes... Not my eyes...}
{6355}{}{That was a real cheap shot!}
{6356}{}{Åååååå, mitt skrev!}
{6357}{}{}
{6358}{}{}
{6359}{}{}
{6360}{}{Urp!}
{6361}{}{Ow! I'm gonna kill you for that!}
{6400}{}{Gotta get outta here!}
{6401}{}{I'll be back...}
{6402}{}{Hjälp!}
{6403}{}{Run away!}
{6404}{}{You ain't heard the last of me!}
{6405}{}{}
{6406}{}{}
{6407}{}{Fresh meat...}
{6408}{}{Welcome to Junktown. Nice place for your grave!}
{6409}{}{Skulz! Attack!}
{6410}{}{It's killing time!}
{6411}{}{Time to rip a clip...}
{6412}{}{We gonna add your skull to our collection}
{6413}{}{Feel free to scream}
{6414}{}{Gonna enjoy this.}
{6415}{}{}
{6416}{}{Gonna feed you to the dogs}
{6417}{}{Nobody's taking Junktown away from us}
{6418}{}{Hope you don't die too quickly.}
{6419}{}{}
{6420}{}{Dö!}
{6421}{}{}
{6422}{}{}
{6423}{}{I'm too good to die!}
{6424}{}{}
{6425}{}{Try aiming, scag!}
{6426}{}{}
{6427}{}{Hah!}
{6428}{}{Not in the face!}
{6429}{}{Man, this is worse than a hangover}
{6430}{}{Du bröt min näsa!}
{6431}{}{Ow, my arm!}
{6432}{}{You broke my arm!}
{6433}{}{My arm! My arm!}
{6434}{}{Ow, my arm!}
{6435}{}{You broke my arm!}
{6436}{}{My arm! My arm!}
{6437}{}{Man! That really hurt!}
{6438}{}{Oof! You gonna regret that}
{6439}{}{[Gasp]}
{6440}{}{[Gasp!] Need... air...}
{6441}{}{I'm gonna spit on your corpse, you skag!}
{6442}{}{Förbannat!}
{6443}{}{Oof!}
{6444}{}{That was a cheap shot!}
{6445}{}{Oof!}
{6446}{}{Ouch!}
{6447}{}{Ow, my leg!}
{6448}{}{Nobody's making me into a gimp!}
{6449}{}{Oh, my knee!}
{6450}{}{Ow, my leg!}
{6451}{}{Nobody's making me into a gimp!}
{6452}{}{Oh, my knee}
{6453}{}{Argh! My eyes!}
{6454}{}{My eyes... Not my eyes...}
{6455}{}{}
{6456}{}{Åååååå, mitt skrev!}
{6457}{}{}
{6458}{}{}
{6459}{}{}
{6460}{}{Urp!}
{6461}{}{Ow! I'm gonna kill you for that!}
{6500}{}{Gotta get outta here!}
{6501}{}{I'll be back...}
{6502}{}{Hjälp!}
{6503}{}{Run away!}
{6504}{}{You ain't heard the last of me!}
{6505}{}{You're getting payback, I promise!}
{6506}{}{It's over, punk! You is history!}
{6507}{}{You should never have crossed me, punk}
{6508}{}{You is needing a new attitude, punk.}
{6509}{}{Nobody crosses Gizmo more than once}
{6510}{}{You is gonna be dead and buried}
{6511}{}{You is making me real unhappy}
{6512}{}{I'm gonna add your kneecaps to my collection}
{6513}{}{This is what I do to punks and losers}
{6514}{}{I'm gonna enjoy this.}
{6515}{}{Oooo, that's gotta hurt!}
{6516}{}{You messed with the wrong man}
{6517}{}{Nobody's taking Junktown away from me}
{6518}{}{Hope you don't die too quickly.}
{6519}{}{I'm gonna tear you limb from limb!}
{6520}{}{You is dead!}
{6521}{}{Try this on for size!}
{6522}{}{That's real pathetic}
{6523}{}{You could really use some Buffout}
{6524}{}{You're an even bigger loser than Killian}
{6525}{}{}
{6526}{}{That was your last shot!}
{6527}{}{}
{6528}{}{}
{6529}{}{How dare you do this to me!}
{6530}{}{Du bröt min näsa!}
{6531}{}{You dirty radscorpion kissing...}
{6532}{}{You broke my arm!}
{6533}{}{My arm! My arm!}
{6534}{}{You dirty radscorpion kissing...}
{6535}{}{You broke my arm!}
{6536}{}{My arm! My arm!}
{6537}{}{}
{6538}{}{}
{6539}{}{Oof!}
{6540}{}{Oof! My ribs...}
{6541}{}{!}
{6542}{}{Aj!}
{6543}{}{Argh!}
{6544}{}{No one does that to me, no one!}
{6545}{}{Ow!!!}
{6546}{}{Oof!}
{6547}{}{Ow, my leg!}
{6548}{}{I can... barely... stand...}
{6549}{}{Oh, my knee!}
{6550}{}{Ow, my leg!}
{6551}{}{I can... barely... stand...}
{6552}{}{Oh, my knee}
{6553}{}{Uggh! Noooo!}
{6554}{}{My eyes... Not my eyes...}
{6555}{}{}
{6556}{}{Åååååå, mitt skrev!}
{6557}{}{Ooo! Not bad, punk}
{6558}{}{Ooo! You is digging your grave, punk}
{6559}{}{Ooo! You is deader than an albino in the Glow}
{6560}{}{Urp!}
{6561}{}{Ow! I'm gonna kill you for that!}
{6600}{}{I'm outta here!}
{6601}{}{Have mercy!}
{6602}{}{Please stop!}
{6603}{}{Hjälp!}
{6604}{}{Aaaaahhhh!}
{6605}{}{}
{6606}{}{Hey!}
{6607}{}{}
{6608}{}{Who do you think you are?}
{6609}{}{Nobody's taking this place over...}
{6610}{}{You're forcing me to be real unfriendly.}
{6611}{}{You son of a...}
{6612}{}{}
{6613}{}{You asked for this!}
{6614}{}{}
{6615}{}{}
{6616}{}{Why did you start this?}
{6617}{}{Die, you son of a...}
{6618}{}{Don't take this personal...}
{6619}{}{You deserve every bit of this!}
{6620}{}{You realize that you started this}
{6621}{}{}
{6622}{}{Whew!}
{6623}{}{You really don't have to do this}
{6624}{}{You are a sorry excuse for a fighter}
{6625}{}{You remind me of someone I used to date}
{6626}{}{You can't handle me}
{6627}{}{}
{6628}{}{My face!}
{6629}{}{Ah, my head hurts}
{6630}{}{You're messing up my face!}
{6631}{}{Ow, my arm!}
{6632}{}{You're trying to cripple me!}
{6633}{}{Min arm!}
{6634}{}{Ow, my arm!}
{6635}{}{You're trying to cripple me!}
{6636}{}{You broke my arm!}
{6637}{}{Aj!}
{6638}{}{!}
{6639}{}{Ow! That hurt!}
{6640}{}{}
{6641}{}{Don't hit a lady there!}
{6642}{}{Ow!!}
{6643}{}{Ouch!}
{6644}{}{Ow! You little piece of ...}
{6645}{}{AH! Fuck!}
{6646}{}{Dammit! You little worm!}
{6647}{}{My leg!!!}
{6648}{}{My knee!}
{6649}{}{Ow! My leg's busted!}
{6650}{}{Ow, my leg!}
{6651}{}{My knee!}
{6652}{}{}
{6653}{}{My face! My face!}
{6654}{}{My... eyes... MY EYES!}
{6655}{}{You bastard! I'll kill you!}
{6656}{}{You must be used to fighting men}
{6657}{}{}
{6658}{}{You piece of desert trash!}
{6659}{}{That's my personal space!}
{6660}{}{You slime!}
{6661}{}{You animal!}
{6700}{}{I need reinforcements!}
{6701}{}{Somebody help me!}
{6702}{}{}
{6703}{}{Retreat!}
{6704}{}{Fall back!}
{6705}{}{Next time!}
{6706}{}{I'm coming!}
{6707}{}{}
{6708}{}{}
{6709}{}{You shouldn't have started this}
{6710}{}{I hope the Paladins are watching}
{6711}{}{}
{6712}{}{}
{6713}{}{}
{6714}{}{Now you die!}
{6715}{}{How do you like this?}
{6716}{}{Mess with the best, die like the rest}
{6717}{}{Shouldn't start what you can't finish}
{6718}{}{}
{6719}{}{Let's see how you like this!}
{6720}{}{}
{6721}{}{See you in hell}
{6722}{}{Face facts. You are outclassed.}
{6723}{}{Is that the best you can do?}
{6724}{}{Loser! Gimme a fight!}
{6725}{}{}
{6726}{}{We are the Masters of Combat!}
{6727}{}{You can't touch the Brotherhood}
{6728}{}{I'll get you for that}
{6729}{}{Aj!}
{6730}{}{Du bröt min näsa!}
{6731}{}{You broke my arm!}
{6732}{}{A busted arm is not stopping me!}
{6733}{}{}
{6734}{}{You broke my arm!}
{6735}{}{A busted arm is not going to stop me!}
{6736}{}{}
{6737}{}{You busted a rib!}
{6738}{}{Oof!}
{6739}{}{Ouch!}
{6740}{}{Oof! So that is what pain feels like...}
{6741}{}{Ow! My training did not prepare me for this!}
{6742}{}{Oof! The Brotherhood will revenge me if I die!}
{6743}{}{Ouch!}
{6744}{}{}
{6745}{}{Oh! My aching ribs! I will get you for that}
{6746}{}{Oof!}
{6747}{}{Ow, my leg!}
{6748}{}{You're gonna pay big time for that!}
{6749}{}{You are not crippling me. Ow...}
{6750}{}{Ow, my leg!}
{6751}{}{You're gonna pay big time for that!}
{6752}{}{You are not crippling me.}
{6753}{}{I am blind!}
{6754}{}{My eyes are burning!}
{6755}{}{Jag kan inte se!}
{6756}{}{Åååååå, mitt skrev!}
{6757}{}{}
{6758}{}{The pain...}
{6759}{}{I...can't...breathe...}
{6760}{}{I'll get you for that!}
{6761}{}{You punk...}
{6800}{}{I need reinforcements!}
{6801}{}{I am out of this fight}
{6802}{}{Pull back}
{6803}{}{Retreat!}
{6804}{}{Fall back!}
{6805}{}{I can't stay in this one any longer}
{6806}{}{}
{6807}{}{}
{6808}{}{Hold on a second...}
{6809}{}{You shouldn't have started this}
{6810}{}{}
{6811}{}{I'm going in!}
{6812}{}{Take this!}
{6813}{}{Now I have you!}
{6814}{}{Now you die!}
{6815}{}{How do you like this?}
{6816}{}{I know how to deal with the likes of you}
{6817}{}{This should take the fight out of you}
{6818}{}{}
{6819}{}{Let us see how you like this!}
{6820}{}{}
{6821}{}{}
{6822}{}{The fact is. You are outclassed}
{6823}{}{Is this your best?}
{6824}{}{You stupid little fool}
{6825}{}{That was pathetic}
{6826}{}{You insult me with your incompetence}
{6827}{}{You cannot touch the Brotherhood}
{6828}{}{Ah!}
{6829}{}{Aj!}
{6830}{}{Ooo, my nose!}
{6831}{}{That sounds like a compound fracture}
{6832}{}{Ooo, my arm!}
{6833}{}{My arm just went numb}
{6834}{}{That sounds like a compound fracture}
{6835}{}{Ooo, my arm!}
{6836}{}{My arm just went numb}
{6837}{}{}
{6838}{}{Oof!}
{6839}{}{}
{6840}{}{Oof! Pain...my old friend}
{6841}{}{}
{6842}{}{Oof! The Brotherhood will revenge my death!}
{6843}{}{Ouch!}
{6844}{}{}
{6845}{}{Oh! My aching ribs! I'll get you for that}
{6846}{}{Oof!}
{6847}{}{Ow, my leg!}
{6848}{}{Ooo, my knee!}
{6849}{}{Ow}
{6850}{}{Ow, my leg!}
{6851}{}{Ooo, my knee}
{6852}{}{Ow...}
{6853}{}{I'm blind!}
{6854}{}{I've been blinded! I need help here!}
{6855}{}{Mina ögon!}
{6856}{}{Åååååå, mitt skrev!}
{6857}{}{Oooooo, took the wind outta me}
{6858}{}{Oooooo, that hurt...}
{6859}{}{I...can...not...breathe...}
{6860}{}{I am hurt here! I need help!}
{6861}{}{That hurt...}
{6900}{}{I need reinforcements!}
{6901}{}{I am out of this fight}
{6902}{}{Pull back}
{6903}{}{Retreat!}
{6904}{}{Fall back!}
{6905}{}{I can't stay in this one any longer}
{6906}{}{I am coming!}
{6907}{}{This one is mine!}
{6908}{}{}
{6909}{}{Once more into the breach}
{6910}{}{}
{6911}{}{I'm going in!}
{6912}{}{Time to finish this}
{6913}{}{Now I have you!}
{6914}{}{Now you die!}
{6915}{}{It's over!}
{6916}{}{Fall down!}
{6917}{}{This should take the fight out of you}
{6918}{}{}
{6919}{}{Let's see what you're made of}
{6920}{}{I'm just warming up}
{6921}{}{Here comes the thunder}
{6922}{}{Your skills are weak}
{6923}{}{Is that the best you can do?}
{6924}{}{You stupid little fool}
{6925}{}{That was pathetic}
{6926}{}{You insult me with your incompetence}
{6927}{}{You're no fighter}
{6928}{}{Ah!}
{6929}{}{Aj!}
{6930}{}{Ooo}
{6931}{}{That sounds like a compound fracture}
{6932}{}{Aj!}
{6933}{}{My arm just went numb}
{6934}{}{That sounds like a compound fracture}
{6935}{}{Aj!}
{6936}{}{My arm just went numb}
{6937}{}{Ow! I am prepared for your kind!}
{6938}{}{Oof!}
{6939}{}{Ouch!}
{6940}{}{Oof! I had worse}
{6941}{}{Ow! Do your worst, I'm ready!}
{6942}{}{The Brotherhood will revenge me if I die!}
{6943}{}{Ouch!}
{6944}{}{Argh!}
{6945}{}{}
{6946}{}{Oof!}
{6947}{}{Ow, my leg!}
{6948}{}{}
{6949}{}{Ow}
{6950}{}{Ow, my leg!}
{6951}{}{}
{6952}{}{Ow...}
{6953}{}{Aggghh!}
{6954}{}{I've been blinded! I need help here!}
{6955}{}{Mina ögon!}
{6956}{}{Åååååå, mitt skrev!}
{6957}{}{Oooooo, took the wind outta me}
{6958}{}{Oooooo, that hurt...}
{6959}{}{I...can't...breathe...}
{6960}{}{Let's keep this fair}
{6961}{}{That hurt...}
{7000}{}{Dunkirk! Dunkirk! I'm pulling out!}
{7001}{}{I am out of this fight}
{7002}{}{Pull back}
{7003}{}{I will live to fight another day}
{7004}{}{I can't do any good here}
{7005}{}{}
{7006}{}{I am coming!}
{7007}{}{This one is mine!}
{7008}{}{This should be quick}
{7009}{}{Once more into the breach}
{7010}{}{Let us neutralize this troublemaker}
{7011}{}{I'm going in!}
{7012}{}{Enjoy these last few seconds}
{7013}{}{Let's flatline you!}
{7014}{}{This is how it is done}
{7015}{}{It is over!}
{7016}{}{Incoming fire!}
{7017}{}{I appreciate the exercise, but it is time to end this}
{7018}{}{}
{7019}{}{Let's see what you're made of}
{7020}{}{Enough playing around}
{7021}{}{I almost feel sorry for you}
{7022}{}{You are a weak fool!}
{7023}{}{Was that your best?}
{7024}{}{Are you taking this fight seriously?}
{7025}{}{Keep your eyes on the target, you idiot!}
{7026}{}{That will be your last mistake}
{7027}{}{You should have stayed home}
{7028}{}{Hmm, that hurt!}
{7029}{}{Uh!}
{7030}{}{Ooo}
{7031}{}{That sounds like a compound fracture}
{7032}{}{Hmm, got me in the forearm}
{7033}{}{My arm just went numb}
{7034}{}{That sounds like a compound fracture}
{7035}{}{Hmm, got me in the forearm}
{7036}{}{My arm just went numb}
{7037}{}{Ow! You dog!}
{7038}{}{Oof!}
{7039}{}{Ouch!}
{7040}{}{Oof! I had worse done to me by my mother}
{7041}{}{Ow! You cad!}
{7042}{}{Oof! The Brotherhood will revenge me if I die!}
{7043}{}{I will master my pain as I will master you!}
{7044}{}{Yes...Pain my old friend}
{7045}{}{}
{7046}{}{It's only a flesh wound!}
{7047}{}{Hmm, a leg wound}
{7048}{}{My leg's starting to buckle!}
{7049}{}{Ow}
{7050}{}{Hmm, a leg wound}
{7051}{}{My leg's starting to buckle}
{7052}{}{Ow...}
{7053}{}{Aggghh!}
{7054}{}{My eyesight's gone!}
{7055}{}{Mina ögon!}
{7056}{}{Åååååå, mitt skrev!}
{7057}{}{I'm really starting to dislike this punk}
{7058}{}{I've felt better}
{7059}{}{So, this punk likes going downstairs}
{7060}{}{Time to take this punk apart}
{7061}{}{Not another cheap shot artist}
{7100}{}{Cover me!}
{7101}{}{Do not mistake this for cowardice, cur.}
{7102}{}{This is not my time!}
{7103}{}{I'll give you this one, cur.}
{7104}{}{Don't think this is over yet.}
{7105}{}{}
{7106}{}{I am coming.}
{7107}{}{Must I do everything myself?}
{7108}{}{This should be quick}
{7109}{}{Maybe this will be a challenge}
{7110}{}{Somebody just made a big mistake}
{7111}{}{Someone wants to bother us? Who is this imbecile!}
{7112}{}{All too easy}
{7113}{}{Ready, aim, fire...}
{7114}{}{This is how it's done}
{7115}{}{It's over!}
{7116}{}{Incoming!}
{7117}{}{I appreciate the exercise, but it's time to end this}
{7118}{}{Time to end your delusions}
{7119}{}{This is a hard lesson for one so young}
{7120}{}{Enough playing around}
{7121}{}{A gift from the Elders, child.}
{7122}{}{I could see that one coming}
{7123}{}{It took me twenty years to learn how to dodge like that}
{7124}{}{You have talent, but your training's pathetic}
{7125}{}{There is no substitute for experience}
{7126}{}{Now... it is my turn}
{7127}{}{You should have stayed home}
{7128}{}{Hmm, that hurt!}
{7129}{}{Uh!}
{7130}{}{Ooo, not a bad hit}
{7131}{}{}
{7132}{}{Hmm, got me in the forearm}
{7133}{}{My arm just went numb. Not the first time}
{7134}{}{}
{7135}{}{Hmm, got me in the forearm}
{7136}{}{My arm just went numb. Not the first time}
{7137}{}{I will feel no pain!}
{7138}{}{I live!}
{7139}{}{I live! I hurt, but I live!}
{7140}{}{Ow! You have a made a major tactical error}
{7141}{}{Oof! The Brotherhood will prevail!}
{7142}{}{Oof! The Brotherhood will revenge me if I die!}
{7143}{}{Oof!}
{7144}{}{[Gasp!]}
{7145}{}{That hurt!}
{7146}{}{You will feel that wrath of the Brotherhood for that!}
{7147}{}{Hmm, a leg wound}
{7148}{}{My leg's starting to buckle!}
{7149}{}{That wasn't pleasant}
{7150}{}{Hmm, a leg wound}
{7151}{}{My leg's starting to buckle}
{7152}{}{That wasn't pleasant}
{7153}{}{Must stay calm. I know where to aim}
{7154}{}{Hit in the eyes. This is not good.}
{7155}{}{Mina ögon!}
{7156}{}{Åååååå, mitt skrev!}
{7157}{}{}
{7158}{}{This kid's trying to rile me}
{7159}{}{}
{7160}{}{Time to take this fool apart}
{7161}{}{Not another cheap shot artist}
{7200}{}{I'm pulling out!}
{7201}{}{I'm out of this fight}
{7202}{}{Withdraw!}
{7203}{}{I will fight another day}
{7204}{}{I can't do any good here}
{7205}{}{}
{7206}{}{I am coming!}
{7207}{}{This one is mine!}
{7208}{}{I'm going to take care of this cur.}
{7209}{}{Let me introduce you to pain}
{7210}{}{Insolent little bastard}
{7211}{}{I'm going in!}
{7212}{}{Enjoy these last few seconds}
{7213}{}{I'm tired of you}
{7214}{}{This is how it's done}
{7215}{}{It's over!}
{7216}{}{This is how a professional does it}
{7217}{}{You're really starting to bug me}
{7218}{}{}
{7219}{}{You're asking to be slagged, kid}
{7220}{}{Enough playing around}
{7221}{}{I almost feel sorry for you}
{7222}{}{Your skills are nothing}
{7223}{}{Quit wasting my time kid}
{7224}{}{Are you taking this fight seriously?}
{7225}{}{You haven not been doing this for very long, have you?}
{7226}{}{Weak Fool}
{7227}{}{You should have stayed home}
{7228}{}{Hmm, that hurt!}
{7229}{}{Uh!}
{7230}{}{Ooo}
{7231}{}{}
{7232}{}{Hmm, got me in the forearm}
{7233}{}{My arm just went numb}
{7234}{}{}
{7235}{}{Hmm, got me in the forearm}
{7236}{}{My arm just went numb}
{7237}{}{I will feel no pain!}
{7238}{}{Oof! Insolent dog!}
{7239}{}{Oof! Insolent cur! Feel my wrath!}
{7240}{}{Ow! You have a made a major tactical error}
{7241}{}{Ouch!}
{7242}{}{Oof! The Brotherhood will revenge my death}
{7243}{}{Oof!}
{7244}{}{Pain lets me know I am alive}
{7245}{}{That hurt!}
{7246}{}{}
{7247}{}{A leg wound will not stop me from killing you}
{7248}{}{My leg's starting to buckle!}
{7249}{}{Ow}
{7250}{}{A leg wound will not stop me from killing you}
{7251}{}{My leg's starting to buckle}
{7252}{}{Ow...}
{7253}{}{Aggghh!}
{7254}{}{You bastard!}
{7255}{}{Mina ögon!}
{7256}{}{Kid, people who play games with me wind up dead!}
{7257}{}{}
{7258}{}{I've felt better}
{7259}{}{}
{7260}{}{Time to take this fool apart}
{7261}{}{I would expect from some one like you}
{7300}{}{This has been droll, but I must go.}
{7301}{}{This battle is meaningless. Farewell, fool!}
{7302}{}{I will waste no more time with you}
{7303}{}{I have better things to do than to soil my hands with you!}
{7304}{}{I'll let the Nightkin deal with you}
{7305}{}{Goodbye, fool. You will not survive to meet me again}
{7306}{}{It's been a long time since I enjoyed hot blood on my fingers!}
{7307}{}{I will see you dead for what you've done!}
{7308}{}{When I'm finished, you'll be food for mole rats!}
{7309}{}{Not another interruption!}
{7310}{}{Your insolence will not be tolerated!}
{7311}{}{You have passed beyond the realm of forgiveness}
{7312}{}{Take this!}
{7313}{}{I anoint you with Holy Flame!}
{7314}{}{This is how I deal with animals}
{7315}{}{You unspeakable little savage!}
{7316}{}{I will hear you scream!}
{7317}{}{This is only the beginning of your agony!}
{7318}{}{I am Morpheus, and I wield a black staff!}
{7319}{}{You shall burn!}
{7320}{}{I am Morpheus, Master of Death!}
{7321}{}{I cast you out and end your life}
{7322}{}{I am singularly unimpressed}
{7323}{}{I didn't spend ten years in the Rippers for nothing!}
{7324}{}{Pathetic}
{7325}{}{I've had better fights from whores}
{7326}{}{Have you always been incompetent, or is this a recent development?}
{7327}{}{Blasphemer, failure, fool. Soon we'll add corpse to your list of achievements}
{7328}{}{Agggh!}
{7329}{}{Mina ögon!}
{7330}{}{Lucky shot!}
{7331}{}{Aj!}
{7332}{}{Ow! My arm!}
{7333}{}{Ow! Curse your luck!}
{7334}{}{Aj!}
{7335}{}{Ow! My arm!}
{7336}{}{Ow! Curse your luck!}
{7337}{}{Damn your luck!}
{7338}{}{Ow! I will not surrender!}
{7339}{}{You are a true pain in the ass!}
{7340}{}{You are damning yourself in the eyes of the Master}
{7341}{}{Aj!}
{7342}{}{Ouch!}
{7343}{}{Oof!}
{7344}{}{[Gasp!]}
{7345}{}{Oh, that hurt!}
{7346}{}{My minions will cause you serious pain for that!}
{7347}{}{Aj!}
{7348}{}{Ow! My knee!}
{7349}{}{Ow! My leg!}
{7350}{}{Aj!}
{7351}{}{Ow! My knee!}
{7352}{}{Ow! My leg!}
{7353}{}{My eyes! You filthy swine!}
{7354}{}{I'll see you ripped apart limb from limb!}
{7355}{}{Agghh! Dirty little son of a...}
{7356}{}{Åååååå, mitt skrev!}
{7357}{}{Aieee!}
{7358}{}{I'll see you suffer!}
{7359}{}{Ooof!}
{7360}{}{Your death will be especially painful now!}
{7361}{}{How dare you attack the loins of Morpheus!}
{7400}{}{Child, you have been punished enough. Away with you}
{7401}{}{You should not resist me child. We will work on that.}
{7402}{}{I will waste no more time with you}
{7403}{}{I have better things to do than to soil my hands with you!}
{7404}{}{I'll let the Nightkin deal with you}
{7405}{}{I shall punish you again later}
{7406}{}{You have earned punishment}
{7407}{}{You must receive discipline}
{7408}{}{Hold still. This is going to hurt.}
{7409}{}{You must learn manners, child.}
{7410}{}{Youth today. No discipline. No manners. I will instruct you.}
{7411}{}{You have earned great pain, child.}
{7412}{}{Feel my lash, and be cleansed!}
{7413}{}{I anoint you with Holy Flame!}
{7414}{}{You are a wicked creature! Admit it!}
{7415}{}{You deserve punishment! Admit it!}
{7416}{}{Scream child! In pain there is redemption!}
{7417}{}{I take no joy in your pain, child.}
{7418}{}{Confess your sin! Confess your sin!}
{7419}{}{You are vile and unholy. Admit it!}
{7420}{}{Your resistance only adds to your sin. Submit!}
{7421}{}{Submit to divine authority, and you will be healed!}
{7422}{}{Your actions only reflect a sick and twisted mind}
{7423}{}{Your resistance sickens me, but I shall endure}
{7424}{}{I fear you are beyond my ability to redeem.}
{7425}{}{Is there no end to your perfidy, child?}
{7426}{}{Though you attack me, I still love you}
{7427}{}{Blasphemer, failure, fool. Repent!}
{7428}{}{I bear your blows with patience, child.}
{7429}{}{You shall not harm me, for my cause is holy}
{7430}{}{I shall endure}
{7431}{}{The Master is my shield. I feel no pain.}
{7432}{}{I am protected by the Holies, child.}
{7433}{}{The Holy Flame succors me. Your blows are nothing.}
{7434}{}{The Master is my shield. I feel no pain.}
{7435}{}{I am protected by the Holies, child.}
{7436}{}{The Holy Flame succors me. Your blows are nothing.}
{7437}{}{After pain, there is forgiveness, child.}
{7438}{}{I understand pain. Do you?}
{7439}{}{I may feel your blows, but the pain does not matter}
{7440}{}{Do that again, I like your touch}
{7441}{}{The Master gives me the will to survive}
{7442}{}{[Gasp!] You are but a child}
{7443}{}{My body is but a shell}
{7444}{}{You cannot stop the Unity}
{7445}{}{I feel your pain, child}
{7446}{}{Do not attempt that again!}
{7447}{}{After pain, there is forgiveness, child.}
{7448}{}{The Master is my legs and arms, child.}
{7449}{}{Each weakness of body makes my souls stronger, child.}
{7450}{}{After pain, there is forgiveness, child.}
{7451}{}{The Master is my legs and arms, child.}
{7452}{}{Each weakness of body makes my souls stronger, child.}
{7453}{}{After pain, there is forgiveness, child.}
{7454}{}{No sacrifice is too great for the Master, child.}
{7455}{}{Each weakness of body makes my souls stronger, child.}
{7456}{}{Though my flesh is weak, my spirit is strong!}
{7457}{}{Pain is an artifact of a weak mind. I shall endure}
{7458}{}{My suffering strengthens me}
{7459}{}{Ooof!}
{7460}{}{Even in battle, you betray a decadent nature}
{7461}{}{Your sins shall be multiplied on you tenfold, child!}
{7500}{}{Your evils will receive punishment in due course!}
{7501}{}{The mark of the Children is on you now!}
{7502}{}{I will see you again!}
{7503}{}{I shall see your corpse!}
{7504}{}{We shall meet another time}
{7505}{}{This isn't over!}
{7506}{}{Blasphemers must be punished!}
{7507}{}{Death in the name of the Holy Flame!}
{7508}{}{How dare you interrupt our great work!}
{7509}{}{You must learn manners, child}
{7510}{}{Children, destroy the intruder!}
{7511}{}{You have earned great pain, child}
{7512}{}{This is your punishment!}
{7513}{}{Blasphemer!}
{7514}{}{Suffer the Children!}
{7515}{}{In the name of the Holy Flame, Die!}
{7516}{}{And now comes the night}
{7517}{}{Know the piece of the grave, child!}
{7518}{}{Now falls the death blow!}
{7519}{}{You desecrate the Holy Flame!}
{7520}{}{Suffer, fool!}
{7521}{}{Only in the end do you understand!}
{7522}{}{Your actions only reflect a sick and twisted mind}
{7523}{}{You cannot harm me, child.}
{7524}{}{I fear you are beyond my ability to redeem}
{7525}{}{Is there no end to your perfidy, child?}
{7526}{}{The Holy Flame protects me!}
{7527}{}{My strength is beyond your comprehension}
{7528}{}{You evil little beast!}
{7529}{}{You shall die for this!}
{7530}{}{Aj!}
{7531}{}{The Master is my shield. I feel no pain}
{7532}{}{Death shall find you soon!}
{7533}{}{Aj!}
{7534}{}{The Master is my shield. I feel no pain}
{7535}{}{Death shall find you soon!}
{7536}{}{Aj!}
{7537}{}{Sinner!}
{7538}{}{Aj!}
{7539}{}{You are spilling the blood of a holy woman!}
{7540}{}{Oof! You cannot succeed}
{7541}{}{Ow! I will punish you for your sins}
{7542}{}{Ow! You disgrace yourself}
{7543}{}{Oh!}
{7544}{}{My Master protects from your feeble attempts}
{7545}{}{Aj!}
{7546}{}{Oof!}
{7547}{}{The Master is my shield. I feel no pain}
{7548}{}{My blood is a sacrifice to piety}
{7549}{}{Aj!}
{7550}{}{After pain, there is forgiveness, child}
{7551}{}{My blood is a sacrifice to piety}
{7552}{}{Aj!}
{7553}{}{Mina ögon!}
{7554}{}{Aggh! You devil!}
{7555}{}{My eyes are aflame!}
{7556}{}{You are an abomination!}
{7557}{}{You take pleasure in cheap victories!}
{7558}{}{My suffering strengthens me}
{7559}{}{Ooof!}
{7560}{}{Even in battle, you betray a decadent nature}
{7561}{}{Your sins shall be multiplied on you tenfold, child!}
{7600}{}{This isn't worth my time}
{7601}{}{I ain't got time to die!}
{7602}{}{You're gonna pay for what you've done!}
{7603}{}{}
{7604}{}{You ain't seen the last of me!}
{7605}{}{I'm livin' to fight another day!}
{7606}{}{You're history!}
{7607}{}{You messed with the wrong people!}
{7608}{}{I'm gonna dance on your grave}
{7609}{}{You just bought yourself a home six feet under!}
{7610}{}{When I'm done with you, the rats will clean you up!}
{7611}{}{Your life means nothin' to me}
{7612}{}{Time to feed the worms!}
{7613}{}{You're about to get real ugly}
{7614}{}{}
{7615}{}{Your number is up!}
{7616}{}{Two more seconds, and you'll meet your maker}
{7617}{}{I'm gonna drop you like a bad habit!}
{7618}{}{}
{7619}{}{I'm gonna get a bonus for this}
{7620}{}{Dö!}
{7621}{}{I'm gonna kick your ass to the grave}
{7622}{}{Was that a warning shot, or do you just suck?}
{7623}{}{Let me guess, you were intending to miss}
{7624}{}{}
{7625}{}{So that's how you miss the target! Thanks for showing me.}
{7626}{}{I've been more hurt by a good cuss!}
{7627}{}{Loser}
{7628}{}{}
{7629}{}{Ah, my head hurts}
{7630}{}{Du bröt min näsa!}
{7631}{}{Ow, my arm!}
{7632}{}{You broke my arm!}
{7633}{}{I didn't need that}
{7634}{}{Ow, my arm!}
{7635}{}{You broke my arm!}
{7636}{}{My good arm!}
{7637}{}{Oof!}
{7638}{}{That hurt!}
{7639}{}{Go on, try that again!}
{7640}{}{Oof!}
{7641}{}{[Gasp!]}
{7642}{}{Ow, bugger all!}
{7643}{}{Ah, oof!}
{7644}{}{Ouch!}
{7645}{}{Ouch! That hurt!}
{7646}{}{Hey! I wasn't ready for that!}
{7647}{}{Ow, my leg!}
{7648}{}{You're gonna pay big time for that!}
{7649}{}{Oh, my knee!}
{7650}{}{Ow, my leg!}
{7651}{}{You're gonna pay big time for that!}
{7652}{}{Oh, my knee}
{7653}{}{Argh! My retina!}
{7654}{}{My eyes... Not my eyes...}
{7655}{}{That was a real cheap shot!}
{7656}{}{Åååååå, mitt skrev!}
{7657}{}{Ooo! I gotta learn that move...}
{7658}{}{I'll feel that in the morning}
{7659}{}{I hate crotch shots}
{7660}{}{Urp!}
{7661}{}{Ow! I'm gonna kill you for that!}
{7700}{}{}
{7701}{}{Maybe this wasn't a good idea}
{7702}{}{I think I may be outgunned}
{7703}{}{}
{7704}{}{I ain't dyin' for this!}
{7705}{}{That's too much for me}
{7706}{}{Hey you!}
{7707}{}{Somebody's got big problems}
{7708}{}{We don't like your kind around here!}
{7709}{}{Who do you think you are?}
{7710}{}{Time to rip a clip...}
{7711}{}{Hub Police!}
{7712}{}{Take this!}
{7713}{}{Now I have you!}
{7714}{}{Go down and stay down}
{7715}{}{How do you like this?}
{7716}{}{}
{7717}{}{Whatever}
{7718}{}{You think you're trouble? Think again}
{7719}{}{Punk}
{7720}{}{I'm taking you in!}
{7721}{}{Maybe you'll learn some respect}
{7722}{}{You didn't expect to tag me, did you?}
{7723}{}{I'm a trained professional}
{7724}{}{You ain't good enough}
{7725}{}{That was your last mistake}
{7726}{}{Amateur}
{7727}{}{You learn to fight in bars?}
{7728}{}{Aj! Din jävla...}
{7729}{}{I'm gonna kill you for that}
{7730}{}{Jag ska hugga huvudet av dig!}
{7731}{}{Ow, my arm!}
{7732}{}{Damn. My arm's busted!}
{7733}{}{Min arm!}
{7734}{}{Ow, my arm!}
{7735}{}{Damn. My arm's busted!}
{7736}{}{Min arm!}
{7737}{}{You're gonna do some time for that!}
{7738}{}{It's against the law to hit an officer!}
{7739}{}{Ouch!}
{7740}{}{Oof!}
{7741}{}{That's it! I've had enough of you!}
{7742}{}{Gonna put you away for that}
{7743}{}{Hit me there again, and we won't have to see a judge}
{7744}{}{Do that again at your own peril}
{7745}{}{Oof! Give it up!}
{7746}{}{}
{7747}{}{Ow, my leg!}
{7748}{}{You're gonna pay big time for that!}
{7749}{}{My knee!}
{7750}{}{Ow, my leg!}
{7751}{}{You're gonna pay big time for that!}
{7752}{}{My knee!}
{7753}{}{Jag kan inte se!}
{7754}{}{Mitt öga! Det där ska du få betala för!}
{7755}{}{I'm blind!! I need backup}
{7756}{}{Åååååå, mitt skrev!}
{7757}{}{I'll feel that in the morning}
{7758}{}{You punk!}
{7759}{}{Urp!}
{7760}{}{Now you're getting personal!}
{7761}{}{Dammit, that hurt}
{7800}{}{This isn't over. Not by a long shot!}
{7801}{}{I'll be back...}
{7802}{}{You're dead. Do you hear me, dead!}
{7803}{}{I'll see you dead yet!}
{7804}{}{You ain't heard the last of me!}
{7805}{}{You're getting payback, I promise!}
{7806}{}{It's over, punk! You're history!}
{7807}{}{You should never have crossed me, punk}
{7808}{}{You need a new attitude, punk}
{7809}{}{You're a mistake that I mean to correct}
{7810}{}{You're on the express train to hell, punk}
{7811}{}{That's it, someone's dying}
{7812}{}{Take this!}
{7813}{}{This is what I do to punks and losers}
{7814}{}{I'm gonna enjoy this}
{7815}{}{This is gonna hurt!}
{7816}{}{You messed with the wrong man}
{7817}{}{Nobody's taking the Hub away from me}
{7818}{}{Hope you don't die too quickly.}
{7819}{}{Nobody messes with Decker!}
{7820}{}{Dö!}
{7821}{}{Try this on for size!}
{7822}{}{That's real pathetic}
{7823}{}{You're in way over your head!}
{7824}{}{I can still handle myself in a fight}
{7825}{}{You can't get the job done}
{7826}{}{That was your last shot!}
{7827}{}{Loser}
{7828}{}{Min värkande skalle!}
{7829}{}{How dare you do this to me!}
{7830}{}{Du bröt min näsa!}
{7831}{}{You dirty radscorpion-kissing...}
{7832}{}{You broke my arm!}
{7833}{}{My arm! My arm!}
{7834}{}{You dirty radscorpion kissing...}
{7835}{}{You broke my arm!}
{7836}{}{My arm! My arm!}
{7837}{}{You're an underhanded SOB, you know that?}
{7838}{}{Oof! My ribs are going to ache for days!}
{7839}{}{Ow! Whaddaya think I am, a punching bag?}
{7840}{}{Oof!}
{7841}{}{Aj!}
{7842}{}{Don't be messing with me like that, I won't take it}
{7843}{}{Oof! You had your chance to deal, and you blew it!}
{7844}{}{Ow! That was most unpleasant}
{7845}{}{Oof! I'm going remember that...}
{7846}{}{[gasp!] I... outta... air...}
{7847}{}{Ow, my leg!}
{7848}{}{Ooo... You punk!}
{7849}{}{Oh, my knee!}
{7850}{}{Ow, my leg!}
{7851}{}{Ooo... You punk!}
{7852}{}{Oh, my knee}
{7853}{}{Blood. All this blood...}
{7854}{}{My eyes... Not my eyes...}
{7855}{}{That was a real cheap shot!}
{7856}{}{Åååååå, mitt skrev!}
{7857}{}{Ooo! Not bad, punk}
{7858}{}{Ooo! You're digging your grave, punk}
{7859}{}{Ooo! I'm going to bury you alive in the Glow!}
{7860}{}{Urp!}
{7861}{}{Ow! I'm gonna kill you for that!}
{7900}{}{This isn't over. Not by a long shot!}
{7901}{}{I'll be back...}
{7902}{}{You're dead. Do you hear me, dead!}
{7903}{}{I'll see you dead yet!}
{7904}{}{You ain't heard the last of me!}
{7905}{}{You're getting payback, I promise!}
{7906}{}{I'm very good at fixing problems}
{7907}{}{You should never have crossed Mr. Decker}
{7908}{}{I'm going to change your attitude}
{7909}{}{Mr. Decker doesn't like you}
{7910}{}{You're on the express train to hell}
{7911}{}{That's it, someone's dying}
{7912}{}{Take this!}
{7913}{}{Decker thinks you need to learn respect}
{7914}{}{This is a message from Decker}
{7915}{}{This is gonna hurt!}
{7916}{}{You messed with the wrong man}
{7917}{}{Decker says hello.}
{7918}{}{It's too late for apologies}
{7919}{}{Nobody messes with Decker!}
{7920}{}{Dö!}
{7921}{}{Try this on for size!}
{7922}{}{That's real pathetic}
{7923}{}{You're in way over your head!}
{7924}{}{I don't think you can hit the target}
{7925}{}{You can't get the job done}
{7926}{}{That was your last mistake}
{7927}{}{You're having a bad day. Stick around. It gets worse.}
{7928}{}{Min värkande skalle!}
{7929}{}{Oooo...}
{7930}{}{Du bröt min näsa!}
{7931}{}{Oooo...}
{7932}{}{You broke my arm!}
{7933}{}{Min arm!}
{7934}{}{Oooo...}
{7935}{}{You broke my arm!}
{7936}{}{Min arm!}
{7937}{}{Oof! No punk like you is going to take me down...}
{7938}{}{Oof! My ribs!}
{7939}{}{Ow! I'm gonna fuck you up}
{7940}{}{Ha! I've got bigger bruises from working out!}
{7941}{}{Oof! You punks are all alike...}
{7942}{}{Gulp! Gotta... breathe...}
{7943}{}{Ouch!}
{7944}{}{Ow! Piss off you brat!}
{7945}{}{Ah, crap...}
{7946}{}{Argh! I think you cracked a rib!}
{7947}{}{Ow, my leg!}
{7948}{}{Oooo...}
{7949}{}{Oh, my knee!}
{7950}{}{Ow, my leg!}
{7951}{}{Oooo...}
{7952}{}{Oh, my knee}
{7953}{}{Blood. All this blood...}
{7954}{}{My eyes...}
{7955}{}{That was a real cheap shot!}
{7956}{}{Åååååå, mitt skrev!}
{7957}{}{Ooo! I'm gonna return the favor}
{7958}{}{Ooo! You're digging your grave}
{7959}{}{Ooo! I bet you think that's funny}
{7960}{}{Urp!}
{7961}{}{Ow! I don't think I like you}
{8000}{}{My dad's gonna kill you! Wait 'til he gets here!}
{8001}{}{Mom!!!}
{8002}{}{Somebody help me!}
{8003}{}{Hjälp!}
{8004}{}{Aaaaahhhh!}
{8005}{}{Waaaaahhhh!!}
{8006}{}{Hey you!}
{8007}{}{I hate you! I hate you!}
{8008}{}{}
{8009}{}{You're a misshapen mutant!}
{8010}{}{Somebody needs to rip you apart!}
{8011}{}{I'm gonna kill you!}
{8012}{}{Radscorpion head!}
{8013}{}{I'm gonna kill you!}
{8014}{}{Mutant loser!}
{8015}{}{Glow Baby Loser! Glow Baby Loser!}
{8016}{}{Die, ugly!}
{8017}{}{Your mama was a mole rat!}
{8018}{}{Worm ridden Glow Baby!}
{8019}{}{I'm gonna make you ugly!}
{8020}{}{I hate you!}
{8021}{}{Radscorpion lover! You sleep with radscorpions!}
{8022}{}{Your mama was a Glow Baby!}
{8023}{}{You can't touch me, radscorpion brain!}
{8024}{}{You can't even beat up a kid}
{8025}{}{Loser!}
{8026}{}{Missed me, radiation brain!}
{8027}{}{What's the matter, Glow Baby?}
{8028}{}{My face!}
{8029}{}{Oooo, that hurts...}
{8030}{}{Ow! My ear!}
{8031}{}{Ow, my arm!}
{8032}{}{Oooo, that hurts...}
{8033}{}{You broke my arm! Daddy!}
{8034}{}{Ow, my arm!}
{8035}{}{Oooo, that hurts}
{8036}{}{You broke my arm! Daddy!}
{8037}{}{Aj!}
{8038}{}{Ow! Mommy, the bad man is hurting me!}
{8039}{}{Ouch! That was mean!}
{8040}{}{Ow! If I was bigger, I'd beat you up!}
{8041}{}{Owie! Owie! Owie! Mommy!}
{8042}{}{Ow! My dad is bigger than your dad!}
{8043}{}{Oooo, I'm... gonna... cry! Brahhhhh!}
{8044}{}{Ouch!}
{8045}{}{Aj!}
{8046}{}{Ow! Ow! You're mean!}
{8047}{}{Ow, my leg!}
{8048}{}{My knee!}
{8049}{}{You broke my leg! Daddy!}
{8050}{}{Ow, my leg!}
{8051}{}{My knee!}
{8052}{}{You broke my leg! Daddy!}
{8053}{}{Aaaaaahhhh!!!}
{8054}{}{Where'd everybody go?}
{8055}{}{It's all dark...}
{8056}{}{Åååååå, mitt skrev!}
{8057}{}{Ow! You dirty stinking Glow Baby!}
{8058}{}{Urp!}
{8059}{}{I...can't...breathe...}
{8060}{}{Ooooo...}
{8061}{}{Smärtan, smärtan...}
{8100}{}{Retreat option initiated}
{8101}{}{Tactical plan: retreat}
{8102}{}{Combat effective minimal. Retreat advised}
{8103}{}{Tactical analysis complete. Retreat recommended.}
{8104}{}{Downloading escape program}
{8105}{}{Retreat sequence initiated}
{8106}{}{Target acquired!}
{8107}{}{Terminate! Terminate!}
{8108}{}{The humanoid must not escape}
{8109}{}{Terminate the intruder}
{8110}{}{Combat sequence initiated}
{8111}{}{Uploading combat program}
{8112}{}{Combat sequence initiated}
{8113}{}{Attacking target}
{8114}{}{Initiating attack sequence}
{8115}{}{The intruder must be destroyed!}
{8116}{}{Tactical options selection completed}
{8117}{}{Commencing attack}
{8118}{}{The target will be destroyed}
{8119}{}{Enemy termination sequence begun}
{8120}{}{Target must be eliminated}
{8121}{}{Offensive selection completed}
{8122}{}{Analysis. Defensive program success}
{8123}{}{Analysis. Target offense negligible.}
{8124}{}{Target attack failed. Calculating response}
{8125}{}{Unit was unharmed by attack}
{8126}{}{Recalculating target's offensive abilities}
{8127}{}{Analysis. Target erred in tactical selection. Unit undamaged}
{8128}{}{Warning, CPU malfunction registered!}
{8129}{}{Warning! CPU damage! Processing impaired!}
{8130}{}{Warning! CPU damaged! Rerouting critical system!}
{8131}{}{Manipulator damage registered}
{8132}{}{Unit struck in left manipulator. Damage assessment}
{8133}{}{Manipulator hit registered. Attempting to compensate}
{8134}{}{Manipulator damage registered}
{8135}{}{Unit struck in right manipulator. Damage assessment}
{8136}{}{Manipulator hit registered. Attempting to compensate}
{8137}{}{Frame hit. Correcting for damage}
{8138}{}{Frame hit. Internal repairs initiated}
{8139}{}{Main structure under attack}
{8140}{}{Armor penetrated}
{8141}{}{Main structure under attack. Correcting}
{8142}{}{This unit under attack}
{8143}{}{Attempting combat maneuver}
{8144}{}{Brzzt!}
{8145}{}{Minor damage}
{8146}{}{Brzzt!}
{8147}{}{Motivator damage registered}
{8148}{}{Unit struck in right motivator. Damage assessment}
{8149}{}{Motivator hit registered. Attempting to compensate}
{8150}{}{Motivator damage registered}
{8151}{}{Unit struck in left motivator. Damage assessment}
{8152}{}{Motivator hit registered. Attempting to compensate}
{8153}{}{Sensor hit! Sensor hit!}
{8154}{}{Sensors impaired! Sensors impaired!}
{8155}{}{Sensor system malfunction, attempting bypass}
{8156}{}{Regulator malfunction registered!}
{8157}{}{Regulator damage! Regulation impaired!}
{8158}{}{Regulator damaged! Rerouting critical system!}
{8200}{}{I ain't dyin' for this!}
{8201}{}{The job ain't worth this!}
{8202}{}{Somebody else get 'em!}
{8203}{}{There goes my reputation...}
{8204}{}{Yikes!}
{8205}{}{I ain't fighting that!}
{8206}{}{Not another bonehead!}
{8207}{}{You just crossed the line!}
{8208}{}{You ain't getting away with that here!}
{8209}{}{Not on my watch!}
{8210}{}{Nobody does that around my place!}
{8211}{}{Hey you!}
{8212}{}{This is what I do to troublemakers!}
{8213}{}{Turn out the lights...}
{8214}{}{This'll teach you not to cause trouble}
{8215}{}{Your number is up!}
{8216}{}{You're goin' down}
{8217}{}{Let's see how tough you are...}
{8218}{}{Punk}
{8219}{}{You sorry now?}
{8220}{}{Did you expect to get away with this?}
{8221}{}{I eat punks like you for breakfast}
{8222}{}{Are you taking warning shots, or do you just suck!}
{8223}{}{You're not just a punk, you're an incompetent punk!}
{8224}{}{Man, you suck!}
{8225}{}{Is that the best you can do?}
{8226}{}{You didn't expect to tag me, did you?}
{8227}{}{Were you always a failure, or was this a recent thing?}
{8228}{}{Du bröt min näsa!}
{8229}{}{I didn't need that ear anyway}
{8230}{}{Damn! That hurt!}
{8231}{}{Ow, my arm!}
{8232}{}{You can cripple me, but I'll still kick your butt}
{8233}{}{That was a mistake}
{8234}{}{Ow, my arm!}
{8235}{}{You can cripple me, but I'll still kick your butt}
{8236}{}{That was a mistake}
{8237}{}{Aj!}
{8238}{}{That was a mistake}
{8239}{}{Oof!}
{8240}{}{Ow! Okay, that does it!}
{8241}{}{Ow! Now I'm mad}
{8242}{}{Oof!}
{8243}{}{Argh!}
{8244}{}{Ouch!}
{8245}{}{Oof! I'm gonna take this shotgun and shove it...}
{8246}{}{Gulp!}
{8247}{}{Not another busted leg! Oh well...}
{8248}{}{You can cripple me, but I'll still kick your butt}
{8249}{}{That was a mistake}
{8250}{}{Not another busted leg! Oh well...}
{8251}{}{You can cripple me, but I'll still kick your butt}
{8252}{}{That was a mistake}
{8253}{}{I can't see! You're starting to bug me!}
{8254}{}{I don't need to see you to kill you!}
{8255}{}{Ow! Lucky shot...}
{8256}{}{Åååååå, mitt skrev!}
{8257}{}{Now you're getting personal!}
{8258}{}{The groin. The last refuge of a scoundrel}
{8259}{}{I'm a woman, you twit.}
{8260}{}{You're messing with the wrong lady}
{8261}{}{Urp!}
{8300}{}{Squeak!!}
{8301}{}{Squeak!}
{8302}{}{Squeak!}
{8303}{}{squeak}
{8400}{}{Time to get out of here!}
{8401}{}{Arrgh!}
{8402}{}{Retreat!}
{8403}{}{This is gonna hurt you a lot, and me not at all.}
{8404}{}{I'm gonna kick your ass.}
{8405}{}{I'll try and make this quick.}
{8406}{}{Let's see if you enjoy this.}
{8407}{}{Take this.}
{8408}{}{Gotcha!}
{8409}{}{You loser!}
{8410}{}{Try harder!}
{8411}{}{Dammit, that hurts!}
{8412}{}{Du bröt min näsa!}
{8413}{}{Agh! You broke my arm!}
{8414}{}{My arm's busted!}
{8415}{}{Agh! You broke my arm!}
{8416}{}{My arm's busted!}
{8417}{}{Oof!}
{8418}{}{Argh!}
{8419}{}{You'll pay for that...}
{8420}{}{C'mon, try that again!}
{8421}{}{Ow! You broke my leg!}
{8422}{}{Uh! My knee!}
{8423}{}{Ow! You broke my leg!}
{8424}{}{Uh! My knee!}
{8425}{}{Aah! I can't see!}
{8426}{}{You blinded me, you asshole!}
{8427}{}{Oooohhh...}
{8500}{}{Time for a tactical withdrawal.}
{8501}{}{I'll keep this short.}
{8502}{}{Moving in.}
{8503}{}{Eat this.}
{8504}{}{Have a nice day.}
{8505}{}{Got somethin' for ya.}
{8506}{}{Not quite.}
{8507}{}{Close, but that wasn't a nuke.}
{8508}{}{Ow. Good shot.}
{8509}{}{Ugh.}
{8510}{}{Lost another piece of my ear...}
{8511}{}{Dammit, there goes another tooth...}
{8512}{}{Ugh.}
{8513}{}{Didn't need that arm anyway.}
{8514}{}{Aj.}
{8515}{}{Dang it, that's my shootin' hand.}
{8516}{}{Aj.}
{8517}{}{Dang it, another busted rib.}
{8518}{}{If you wanna kill me, try the head.}
{8519}{}{You can slow me down, but I'll still get ya.}
{8520}{}{I've had a broken leg before.}
{8521}{}{You can slow me down, but I'll still get ya.}
{8522}{}{I've had a broken leg before.}
{8523}{}{Now that's fighting dirty.}
{8524}{}{If I'm blind, I'm gonna hurt you before I kill you.}
{8525}{}{Ugh! Lay off!}
{8526}{}{Oh, my balls...}
{8527}{}{Now THAT hurt.}
{8600}{}{Why are you doing this?!}
{8601}{}{Please don't, I'm unarmed!}
{8602}{}{What happened to you?}
{8603}{}{Somebody help me!}
{8604}{}{This is way out of my league}
{8605}{}{My god, no!}
{8606}{}{Traitor!}
{8607}{}{I can't believe you did that!}
{8608}{}{The surface must drive people insane!}
{8609}{}{You've gone insane!}
{8610}{}{Defend the Vault!}
{8611}{}{I thought you were my friend!}
{8612}{}{You should never have come back}
{8613}{}{And to think that we used to be friends!}
{8614}{}{I wish you had never gone to the surface}
{8615}{}{Hello, old friend. Time to die.}
{8616}{}{You should never have come back}
{8617}{}{And to think that we used to be friends!}
{8618}{}{I wish you had never gone to the surface}
{8619}{}{The surface must drive people insane!}
{8620}{}{The surface must drive people insane!}
{8621}{}{Hello, old friend. Time to die.}
{8622}{}{I saw that one coming}
{8623}{}{You fought better when we were kids}
{8624}{}{Your aim hasn't improved}
{8625}{}{You still take a step back every time you try that move}
{8626}{}{You never could beat me}
{8627}{}{How'd they ever chose you to go out into the surface?}
{8628}{}{Oh, my aching skull!}
{8629}{}{Uh}
{8630}{}{Ooo}
{8631}{}{Min arm!}
{8632}{}{Ow! I heard something crack...}
{8633}{}{My arm just went numb}
{8634}{}{Min arm!}
{8635}{}{Ow! I heard something crack...}
{8636}{}{My arm just went numb}
{8637}{}{Aj!}
{8638}{}{Oof! And we used to be friends...}
{8639}{}{Oof!}
{8640}{}{Ow! Okay, that does it!}
{8641}{}{Ow! Now I'm mad}
{8642}{}{Oof!}
{8643}{}{Argh!}
{8644}{}{Ouch!}
{8645}{}{You still hit like a sissy}
{8646}{}{Gulp!}
{8647}{}{Aj!}
{8648}{}{My leg's starting to buckle}
{8649}{}{ow, my knee}
{8650}{}{Hey, I still need that leg!}
{8651}{}{My leg's starting to buckle}
{8652}{}{Ouch, my knee}
{8653}{}{Aggghhh!}
{8654}{}{You little bastard!}
{8655}{}{Mina ögon!}
{8656}{}{You always did like low blows...}
{8657}{}{You never change, do you?}
{8658}{}{I've felt better...}
{8659}{}{Ooo, my groin!}
{8660}{}{You always were the dirtiest fighter in the Vault}
{8661}{}{You dirty little cave rat!}
{8700}{}{Okay, you can have her!}
{8701}{}{The bitch is yours!}
{8702}{}{Tandi is yours. Leave me alone!}
{8703}{}{Okay, you can have her!}
{8704}{}{Tandi is yours. Leave me alone!}
{8705}{}{The bitch is yours!}
{8706}{}{Let the fight of honor begin!}
{8707}{}{Let the fight of honor begin!}
{8708}{}{Let the fight of honor begin!}
{8709}{}{Let the fight of honor begin!}
{8710}{}{Let the fight of honor begin!}
{8711}{}{Let the fight of honor begin!}
{8712}{}{You are mine to kill!}
{8713}{}{Blood! Blood! Blood!}
{8714}{}{Jag är överlägsen!}
{8715}{}{RAAAAAAARRRR!!}
{8716}{}{Khans are invincible!}
{8717}{}{Ingen reträtt! Ingen kapitulation!}
{8718}{}{You are mine to kill!}
{8719}{}{Jag är överlägsen!}
{8720}{}{Blood and darkness!}
{8721}{}{Khans are the strong!}
{8722}{}{Ahahaha, try again!}
{8723}{}{I cannot be touched!}
{8724}{}{I am indestructible!}
{8725}{}{My honor is stronger than yours!}
{8726}{}{My honor is stronger than yours!}
{8727}{}{You are not worthy of combat with me!}
{8728}{}{A worthy blow!}
{8729}{}{That was your last attack!}
{8730}{}{A pitiful attempt!}
{8731}{}{I can still beat you with one arm!}
{8732}{}{You broke my arm! Now the fight is fair!}
{8733}{}{You broke my arm! Now the fight is fair!}
{8734}{}{I can still beat you with one arm!}
{8735}{}{You broke my arm! Now the fight is fair!}
{8736}{}{You broke my arm! Now the fight is fair!}
{8737}{}{Your death will be legendary for that!}
{8738}{}{I will feast on your eyes for that!}
{8739}{}{I am indestructible!}
{8740}{}{Oof!}
{8741}{}{My honor is stronger than yours!}
{8742}{}{RAAAAAAARRRR!!}
{8743}{}{My ribs hurt. Soon I will remove yours! It's only fair}
{8744}{}{My ribs hurt. Soon I will remove yours! It's only fair}
{8745}{}{I am indestructible!}
{8746}{}{Argh! That hurt!}
{8747}{}{I do not need to stand to kill you!}
{8748}{}{That was a cheap blow!}
{8749}{}{My leg! I will remove yours with my fists!}
{8750}{}{I do not need to stand to kill you!}
{8751}{}{That was a cheap blow!}
{8752}{}{My leg! I will remove yours with my fists!}
{8753}{}{My eye! You will die slowly for that!}
{8754}{}{My eyes! I will trade my vision for your death!}
{8755}{}{That was not honorable!}
{8756}{}{Ooo! I will mutilate you...}
{8757}{}{Ooo! I will mutilate you...}
{8758}{}{Ooo! You... will... suffer...}
{8759}{}{Ooo! You... will... suffer...}
{8760}{}{You will not steal my manhood!}
{8761}{}{You will not steal my manhood!}
{8862}{}{}
{8863}{}{}
{8864}{}{}
{8865}{}{}
{8866}{}{}
{8867}{}{}
{8868}{}{}
{8869}{}{}
{8870}{}{}
{8871}{}{}
{8872}{}{}
{8873}{}{}
{8874}{}{[snort]}
{8875}{}{}
{8876}{}{[grunt]}
{8877}{}{[snort]}
{8878}{}{}
{8879}{}{[grunt]}
{8880}{}{[snort]}
{8881}{}{}
{8882}{}{[grunt]}
{8883}{}{[snort]}
{8884}{}{}
{8885}{}{[grunt]}
{8886}{}{[snort]}
{8887}{}{}
{8888}{}{[grunt]}
{8889}{}{[snort]}
{8890}{}{}
{8891}{}{[grunt]}
{8892}{}{[snort]}
{8893}{}{}
{8894}{}{[grunt]}
{8895}{}{[snort]}
{8896}{}{}
{8897}{}{[grunt]}
{8900}{}{I didn't sign up for this}
{8901}{}{I don't get paid enough for this}
{8902}{}{Fall back!}
{8903}{}{Regroup!}
{8904}{}{I'm not dying for this!}
{8905}{}{That's enough for me}
{8906}{}{I'm gonna teach you a lesson}
{8907}{}{You just made a big mistake!}
{8908}{}{Let's settle this like scavs}
{8909}{}{Let's see what you're made of}
{8910}{}{Gonna get creative with this one}
{8911}{}{Blood resolves what words can't}
{8912}{}{Eat this!}
{8913}{}{Take it!}
{8914}{}{Having second thoughts?}
{8915}{}{Hey look, target practice}
{8916}{}{I enjoy a good workout}
{8917}{}{Any last words?}
{8918}{}{Let's see how tough you are...}
{8919}{}{Let's see how tough you are...}
{8920}{}{Having second thoughts?}
{8921}{}{Let's see how you like this}
{8922}{}{Haha, too slow}
{8923}{}{I've been doing this for years, punk}
{8924}{}{You ain't good enough}
{8925}{}{Don't forget, I was a scav}
{8926}{}{Are you for real?}
{8927}{}{Don't forget, I was a scav}
{8928}{}{Ow! You fucker}
{8929}{}{I'm gonna kill you for that}
{8930}{}{I think I might have a concussion}
{8931}{}{That's not good}
{8932}{}{Damn, my arm's busted!}
{8933}{}{Fuck, you broke it!}
{8934}{}{GAH!}
{8935}{}{Fuck that smarts}
{8936}{}{Min arm!}
{8937}{}{Ooph!}
{8938}{}{I liked that organ}
{8939}{}{You'll regret that}
{8940}{}{My ribs!}
{8941}{}{My knee!}
{8942}{}{You're gonna pay for that!}
{8943}{}{Shit, my leg's going numb}
{8944}{}{You'll regret that}
{8945}{}{I hope it doesn't buckle}
{8946}{}{My knee!}
{8947}{}{Jag kan inte se!}
{8948}{}{My eye!}
{8949}{}{Fuck! At least I have another one}
{8950}{}{I didn't want to have kids anyway}
{8951}{}{Fuck, nice shot}
{8952}{}{You fight dirty!}
{8953}{}{Oof!}
{8954}{}{What a cheap shot}
{8955}{}{I didn't want to have kids anyway}
