{200}{}{Cavern, Vault Door}
{201}{}{Entrance, Medical}
{202}{}{Bostadsutrymme}
{203}{}{Library, Supplies, Command}
{210}{}{Old Shack}
{211}{}{Grottingång}
{212}{}{Bostadsutrymme}
{213}{}{Library, Supplies, Command}
{220}{}{Entrance, Town Hall}
{221}{}{Garden}
{222}{}{Brahma-inhängnad}
{223}{}{Radscorpion Caves}
{230}{}{Entrance, Hospital}
{231}{}{General Store, Hotel}
{232}{}{Casino, Bar}
{240}{}{Base Camp}
{250}{}{Hotel of Doom}
{251}{}{Hall of the Dead}
{252}{}{The Watershed}
{260}{}{Entrance, Caravaners}
{261}{}{Downtown, Market, Casino}
{262}{}{Heights, Hightower}
{263}{}{Gamla stan}
{264}{}{Water Merchants, Church}
{265}{}{Deathclaw Lair}
{270}{}{Entrance}
{271}{}{Level 1}
{272}{}{Level 2}
{273}{}{Level 3}
{274}{}{Level 4}
{280}{}{Entrance}
{281}{}{Fästning Nivå 1}
{282}{}{Fästning Nivå 2}
{283}{}{Vats Level 1}
{284}{}{Vats Level 2}
{290}{}{Krater}
{291}{}{Level 1}
{292}{}{Level 2}
{293}{}{Level 3}
{294}{}{Level 4}
{295}{}{Level 5}
{296}{}{Level 6}
{300}{}{Adytum}
{301}{}{Downtown}
{302}{}{Bibliotek}
{303}{}{Fästning}
{304}{}{Warehouse}
{310}{}{Entrance}
{311}{}{Interiör}
{500}{}{You have stopped the Super Mutant threat.}
{501}{}{Ruins}
{1000}{}{Desert}
{1001}{}{Mountains}
{1002}{}{City}
{1003}{}{Coast}
{1004}{}{Okänt}
