{0}{}{End simulation and return to main menu?}
{1}{}{Demo version}
{2}{}{Default character will be used.}
{3}{}{Saved screenshot.}
{4}{}{Quick-Load game successfully loaded.}
{5}{}{Quick-Save game successfully saved.}
{6}{}{Demo time limit exceeded.}
{7}{}{Pip-Boy 2000 is not available in combat!}
{8}{}{Error saving screenshot.}
{9}{}{INTRO}
{10}{}{NEW GAME}
{11}{}{LOAD GAME}
{12}{}{CREDITS}
{13}{}{EXIT}
{14}{}{Fallout Fixt v0.TESTING by Sduibek. DOWNLOAD: Testing. INSTALL: Testing.}
{15}{}{Action Points}
{16}{}{Hit Points}
{17}{}{Error: motion sensor not available!}
{18}{}{Der Bewegungssensor hat keine Ladung mehr übrig.}
{100}{}{Error saving game config file!}
{101}{}{Game settings not saved.}
{1000}{}{You feel somewhat nauseous. Your skin is red and tender.}
{1001}{}{You feel very nauseous, and after some mild vomiting, slightly fatigued.}
{1002}{}{Du bist sehr erschöpft, der Brechreiz lässt nicht nach, und deine Erholungszeit ist gestört.}
{1003}{}{You are hemorrhaging violently. You are very sick, and your hair is falling out.}
{1004}{}{You are hemorrhaging violently and continuously. The vomitus is stained red from your blood. Your skin is falling off your bones.}
{1005}{}{There is bleeding from your intestines and you have severe diarrhea. You feel bloated and are in intense agony.}
{1006}{}{You have died from radiation sickness.}
{1007}{}{You have received a large dose of radiation.}
{1008}{}{The geiger counter is clicking.}
{1009}{}{The geiger counter is clicking wildly.}
{2000}{}{Action aborted.}
{2001}{}{Das Schloss klemmt.}
{3000}{}{You have been poisoned!}
{3001}{}{You sustain 1 hit point of damage from the poison.}
{4000}{}{Due to your inept handling, the explosives detonate prematurely.}
{5000}{}{uses}
{5001}{}{is out of ammo for the}
{5002}{}{reloads the}
{6000}{}{Ask about what?}
