{100}{}{Tu vois une SuperArmure endommagée.}
{101}{}{Impossible de l'utiliser sans la réparer.}
{102}{}{Une pièce impossible à trouver paraît manquer.}
{103}{}{Il est clair que tu n'as pas encore les compétences suffisantes pour la réparer.}
{104}{}{A toi de réparer l'armure.}
{105}{}{Rien ne se passe.}
{106}{}{Tu n'as pas réussi à réparer l'armure.}
{107}{}{Tu gagnes }
{108}{}{ points d'expérience pour avoir réparé la SuperArmure.}
