{100}{}{Voici Billy.}
{101}{}{Salut.}
{102}{}{Salut. Qu'est-ce que tu fais ?}
{103}{}{Je peux avoir une brahmine ?}
{104}{}{Salut. Euh, au revoir.}
{105}{}{Arg !}
{106}{}{Merci.}
{107}{}{Qu'est-ce que tu pourrais bien faire d'une brahmine ? T'as une caravane ? Bon, peu importe. Elles appartiennent à Dan et il ne voudra pas t'en vendre.}
{108}{}{Pourquoi ?}
{109}{}{Je blaguais.}
{110}{}{A cause de toutes les caravanes disparues. Il n'en a aucune de disponible, la plupart servent pour les caravanes et les autres sont vendues pour la viande. Bon, j'ferais mieux de la fermer parce que Dan va encore se mettre en pétard s'il me voit causer à quelqu'un qu'est pas du coin.}
{111}{}{Oh, d'accord.}
{112}{}{Rien... Enfin, si, je garde les brahmines.}
{113}{}{A quoi sert ta lance ? Elles sont dangereuses ?}
{114}{}{C'est quoi, une brahmine ?}
{115}{}{C'est quoi une brahmine ? Tu plaisantes ? Elles servent principalement au transport des caravanes et à la bouffe. Dan dit que c'est un boulot important, mais je ne suis pas d'accord.}
{116}{}{Oh, ça, je savais !}
{117}{}{Dan a raison. Tu fais un boulot super.}
{118}{}{Ouais, ça m'en a tout l'air. Amuse-toi bien.}
{119}{}{Eh, tu serais pas un de ces skags ?}
{120}{}{Vraiment ? Tu crois ? Ah, alors merci.}
{121}{}{Toi, t'es pas d'ici, hein ? Alors, un conseil : te fais pas prendre à voler !}
{122}{}{Certainement, merci.}
{123}{}{Ca me viendrait pas à l'idée de voler. C'est mal.}
{124}{}{Ouais, finalement t'as peut-être raison. Ce boulot est pas si mal après tout. C'est drôle, mais il me donne de la satisfaction. Bon, faut que j'y aille avant de m'attirer des ennuis.}
{125}{}{Pitié, nous fais pas de mal, à moi et mes brahmines.}
{126}{}{Me fais pas de mal !}
{127}{}{Arrête !}
{128}{}{S'il te plait. Laisse-moi tranquille.}
{129}{}{Tu me fais peur.}
{130}{}{Eh, qu'est-ce que t'essaies de faire ? J'ai rien qui t'intéresse.}
{131}{}{Arrête ça !}
{132}{}{Dangereux ? Non, pas vraiment. Des fois, elles peuvent te mordre, mais elles sont plutôt tranquilles. Elles pètent et rotent beaucoup. Je sais pas pourquoi.}
{133}{}{Alors, à quoi sert la lance ?}
{134}{}{Ok, merci.}
{135}{}{Oh, elles sont horriblement têtues. Je leur donne juste un petit coup de cravache pour les faire avancer... Et puis je ne m'en approche pas trop parce qu'elles donnent parfois des coups de pied.}
{136}{}{S'il te plaît, ne me parle pas. Dan va encore me crier après. Il pète les plombs... J'veux dire, il se met en colère, quand je ne fais pas attention à ce que je fais.}
{137}{}{Il veut seulement t'aider. Travaille dur et tu verras, il sera plus sympa.}
{138}{}{Tiens, voilà 50 capss. Prends-les et éloignes toi cette crapule.}
{139}{}{D'accord.}
{140}{}{Aaaaaarg !}
{141}{}{Euh ?}
{142}{}{Arrête, j'ai déjà assez d'ennuis comme ça.}
{143}{}{Mais, je travaille dur !}
{144}{}{Pardon, c'est pas ce que je voulais dire. Il essaie de t'aider, c'est tout.}
{145}{}{Non, c'est pas vrai. Tu n'es qu'un gros flemmard !}
{146}{}{D'accord.}
{147}{}{Ouais, t'as peut-être raison... C'est vrai qu'il a l'air assez cool, mais j'aimerais qu'il arrête de me gueuler dessus pour un oui pour un non.}
{148}{}{Ouais, c'est vrai.}
{149}{}{Va te faire foutre, vieux schnock !}
{150}{}{Va te faire foutre, vieille sorcière !}
{151}{}{Waouh ! Avec ça, j'en ai assez pour le reste de mes jours ! Merci beaucoup, m'sieur !}
{152}{}{OUAH ! J'en ai pour au moins jusqu'à la fin de ma vie ! Merci beaucoup, m'dame !}
{153}{}{Waouh ! Merci... Euh... ? T'essaie encore de m'attirer des ennuis !}
{154}{}{S'il te plaît, me parle pas, Dan est vraiment dingue.}
{155}{}{T'inquiète. Je lui ai causé et il va essayer d'être plus gentil avec toi.}
{156}{}{Et c'est pas étonnant ! T'es vraiment pas un cadeau !}
{157}{}{Ouah.}
{158}{}{Salut !}
{159}{}{Ces filles là-bas, elles sont vraiment pas futées.}
{160}{}{Re-bonjour.}
{161}{}{Les brahmines sont super.}
{162}{}{Dan va m'emmener au Faucon si je travaille bien.}
{163}{}{Dan va m'emmener sur une caravane un de ces jours !}
{164}{}{Je deviendrai aventurier quand j'aurai l'âge.}
{165}{}{Vraiment ? Oh, d'accord. J'espère que tu lui as pas fait mal. Il est pas vraiment méchant. C'est juste un braillard.}
{166}{}{Rebonjour.}
{167}{}{Qu'est-ce que tu fait déjà ?}
{168}{}{Je peux avoir une brahmine ?}
{169}{}{Je ne fais que regarder, c'est tout. Salut.}
{170}{}{Arg !}
{171}{}{Merci.}
{172}{}{J'ferais mieux de retourner au boulot.}
{173}{}{Ces filles là-bas, elles sont vraiment pas futées.}
{174}{}{Re-bonjour.}
{175}{}{Je deviendrai aventurier quand j'aurai l'âge.}
{176}{}{Sûr que les brahmines ch... euh, font leurs besoins régulièrement.}
{177}{}{Je peux pas te parler maintenant.}
{178}{}{Je veux pas m'attirer des ennuis.}
