{100}{}{Voici un membre dévot des Enfants de la Cathédrale.}
{101}{}{Viens chez nous recevoir un esprit sain dans un corps sain. Est-ce que je peux t'aider ?}
{102}{}{Oui. Aide-moi.}
{103}{}{Qui êtes-vous ?}
{104}{}{Gnngh.}
{105}{}{Ca me convient très bien, mon enfant. Nous allons t'examiner maintenant.}
{106}{}{Que la douceur de l'esprit soit bénie ! Tu n'as rien, mon enfant. Pars et va jouer.}
{107}{}{Tout va bien désormais. Il faudra faire preuve de plus de prudence à l'avenir.}
{108}{}{Tu es blessé.}
{109}{}{Aucune blessure. C'est bien.}
{110}{}{Tu as subi un empoisonnement.}
{111}{}{Hmm, une sorte d'empoisonnement par irradiation. Malheureusement, nous ne pouvons rien y faire.}
{113}{}{Il faut faire un don de }
{114}{}{ caps avant que nous puissions te soigner. Est-ce que ça te convient ?}
{115}{}{Oui.}
{116}{}{Non.}
{117}{}{Mais je n'ai pas cette somme d'argent !}
{118}{}{Vous contenterez-vous de }
{119}{}{ caps ?}
{120}{}{Les Enfants ne marchandent pas. Bon, est-ce que tu acceptes notre prix ?}
{121}{}{Bien sûr que j'accepte.}
{122}{}{Non je te remercie.}
{123}{}{Merci, mon fils. Nous prierons pour ta guérison.}
{124}{}{Merci, ma fille. Nous prierons pour ta guérison.}
{125}{}{Voici. La paix et les bénédictions des Enfants t'accompagnent.}
{126}{}{Tu n'as pas assez d'argent. Si tu nous donnes tout ce que tu peux, nous te guérirons. Ca te convient ?}
{127}{}{Oui.}
{128}{}{Non.}
{129}{}{Si tu nous donnes tout ce que tu peux, nous te guérirons. Ca te convient ?}
{130}{}{Oui.}
{131}{}{Non.}
{132}{}{Ce que tu as est largement suffisant pour faire un don. Tu as besoin de prendre des leçons de math, mon enfant.}
{133}{}{Nous sommes les Enfants de la Cathédrale. Nous vivons et travaillons aux côtés des miséreux qui vivent dans le désert. Si un jour tu passes au Cimetière de L.A., arrête-toi à la Cathédrale.}
{134}{}{Merci.}
{135}{}{Que fais-tu ?}
{136}{}{Nous sommes les guérisseurs et les enseignants de la paix. Nous soignons le corps pour guérir l'esprit. Tout ce que nous demandons est un petit geste pour payer le matériel.}
{137}{}{Ca m'a l'air d'une bonne idée.}
{138}{}{Ce sont des conneries.}
{139}{}{On t'a rien demandé. Je vois que tu en as marre d'écouter nos croyances. Si jamais tu avais besoin de quoi que ce soit, sache que nous serons toujours là.}
{140}{}{C'est notre idée la plus sacrée. Nous travaillons pour qu'enfin la paix ultime règne dans le désert. Toutes les créatures seront enfin unies.}
{141}{}{Merci. Bonne journée.}
{142}{}{Nous n'avons pas le temps de discuter. Nous partons. Cet endroit est dangereux pour nous.}
{143}{}{Pourquoi fais-tu cela ? Nous ne te ferons aucun mal !}
{1000}{}{Cathedral}
{1001}{}{Mutants}
{1002}{}{Maître}
{1003}{}{Cimetière de L.A.}
{1004}{}{Followers}
{1005}{}{Puce d'eau|Puce eau|Puce|Eau|Controleur}
{1006}{}{Apocalypse}
{1007}{}{Nécropolis}
{1008}{}{Set}
{1009}{}{Watershed}
{1010}{}{Hall}
{1011}{}{Cimetière|Le Cimetière|Cimetière de L.A.|Los Angeles}
{1012}{}{L.A. Boneyard}
{1100}{}{That is us.}
{1101}{}{They are people who got mutated from the nuclear fallout. But they are still good people.}
{1102}{}{We all have masters, don't we?}
{1103}{}{Peut-être que nous pouvons remplacer quelques fournitures.}
{1104}{}{C'est ici. Les tristes ruines d'un monde ancien.}
{1105}{}{I have no clue as to what you are talking about.}
{1106}{}{C'est ici. Les tristes ruines d'un monde ancien.}
{1107}{}{J'imagine que c'est un des Goules.}
{1108}{}{C'est ça, par là en direction du Nord-Est.}
{1109}{}{Je ne sais rien là-dessus.}
{1110}{}{Je vois pas de quoi tu parles.}
{1111}{}{Peut-être que nous pouvons remplacer quelques fournitures.}
{1112}{}{Peut-être que nous pouvons remplacer quelques fournitures.}
