{100}{}{This is a badly worn-out reception desk with a dusty, cracked computer seated precariously atop it.}
{101}{}{Tu rebranches un composant mal fixé et étonnamment l'écran s'allume !}
{102}{}{Les dommages semblent d'avantage mécaniques qu'électroniques. Ca devrait pouvoir démarrer avec un peu de travail.}
{103}{}{This equipment appears to be non-functional.}
{104}{}{Tu trifouilles à l'intérieur et te coupes les mains sur un bord du boîtier. Ouch !}
{105}{}{Macro$oft [tm) Wyndoze 99 (c] Démarrage... Fait.       U:\ > }
{106}{}{DIR}
{107}{}{EXIT}
{108}{}{FALLOUT  <DIR>     10-20-99  13:04 						0 octets alloués dans 0 fichiers, 4,379,255 octets libres.}
{109}{}{CD FALLOUT}
{110}{}{Woah ! C'est un super jeu !}
{111}{}{U:\ > }
{112}{}{After several minutes of searching, you find a Debug Mode jumper setting and change it to 01.}
{113}{}{FALLOUTW.EXE}
{114}{}{U:\Fallout\ > }
{115}{}{FALLOUTW.EXE   1384432  10-20-99  13:04 					 FALLDEMO.EXE 995328 04-22-97 14:13 				  2,379,760 octets dans 2 fichiers, 2,436,874 octets alloués }
{116}{}{[Continue]}
{117}{}{> CHARGEMENT...}
{118}{}{[Terminé]}
{119}{}{points d'expérience pour avoir joué à Fallout.}
{120}{}{U:\Fallout\ > }
{121}{}{J'en ai jamais assez de ce "Fallout". Il est si particulier, même pour un jeu d'avant-guerre.}
{122}{}{Hmmm... I wonder what that setting changes?}
{123}{}{> Initiate debug sequence}
{124}{}{*click* ............. Please stand by ... ... ... ... ... ... 
               %s  Done.}
{125}{}{You earn 50 experience.}
{126}{}{FALLDEMO.EXE}
{128}{}{[Terminé]}
{129}{}{MEMORY DUMP INITIATED >>> DO NOT POWER OFF OR RESET THIS TERMINAL
...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  }
{130}{}{Je pige rien à tout ça, je suis pas un génie de l'informatique !}
{131}{}{You see: Computer Desk.}
{132}{}{> PLEASE INSERT EXTRACTION MEDIA <}
{133}{}{Um... I don't have anything like that.}
{134}{}{[Check if there's anything in the computer's external drives]}
{135}{}{

Success! You find a 5" floppy disk under the keyboard. It's very dusty but appears to be functional.}
{136}{}{

You don't find anything that looks like a disk or cartridge...}
{137}{}{[Continue to search]}
{138}{}{

There's an old holodisk in the tape catridge drive that looks like it would work in your Pip-Boy 2000!}
{139}{}{[Install the disks]}
{140}{}{Grrggg... Gngnh ?}
{141}{}{

You push the holodisk all the way into the tapedrive slot after blowing on it and checking that the tape is properly aligned inside the spools. After dusting off the 5" floppy disk, you insert it into the floppy drive slot and turn the locking lever.}
{142}{}{> 12:50 [Press Return]}
{143}{}{[For a few moments the lights blink on the floppy port and the tapedrive makes a high-pitched whirring. This stops, followed by a steady grinding sound from the floppy drive.]}
{144}{}{>>> DO NOT POWER OFF OR RESET THIS TERMINAL >>> :: DATA CORRUPTION WILL OCCUR ::

VERIFYING DATA: 0% ### ### ### 32% ### ### ### 59% ### ### ### 82% ### ### ### 99% ### ### ### ... Done.
WRITING 512KB TO MEMORY BUFFER: 0% ### ### ### 28% ### ### ### 62% ### ### ### 77% ### ### ### 95% ### ### ### ... Done.
VERIFYING MEMORY: 0% ### ### ### 17% ### ### ### 50% ### ### ### 79% ### ### ### 97% ### ### ### ... Done.}
{145}{}{:::MEDIA TRANSFER IN PROGRESS:::
.
...
.....
Transferring 6,759,015 bytes to tape backup drive................................
.......
.........
...........}
{146}{}{MEDIA TRANSFER COMPLETE. PLEASE REMOVE EXTERNAL MEDIA. HAVE A NICE DAY.
[The system powers down, short-circuits and goes completely silent]}
{147}{}{Merci !}
{148}{}{The computer looks badly damaged and unrepairable.}
{149}{}{Many circuits are fried from an EMP burst.}
{150}{}{It doesn't work.}
{151}{}{01100110011000010110110001101100011011110111010101110100011101110010111001100101011110000110010100100000001000000010000000100000001000000011000100110011001110000011010000110100001100110011001000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000010000000100000001000000110011001100001011011000110110001100100011001010110110101101111001011100110010101111000011001010010000000100000001000000010000000100000001110010011100100110101001100110011001000111000}
{152}{}{You earn 25 experience for playing Fallout (again).}
{153}{}{Sympa, je parie que le jeu complet est une tuerie !}
{154}{}{La version complète de Fallout est bien plus sympa, mais cette démo a néanmoins son charme.}
{155}{}{points d'expérience pour avoir joué à la démo de Fallout.}
{156}{}{You earn 42 experience for playing Fallout Fixt.}
{157}{}{Congratulations, you have achieved all possible endings of the Fallout Interactive Demo!}
{158}{}{Congratulations, you have achieved all possible endings of Fallout: A Post-Nuclear Role-Playing Game!}
{159}{}{Wow, this is amazing! Even better than the original game.}
{160}{}{You play Fallout Fixt. Whoever created this must have been very talented.}
{400}{}{Le générateur détruit, les gangs n'ont plus de raison de se battre pour Scraphead. Les gens de Scraphead auront une vie plus difficile sans énergie; mais les gangs partis, ils auront au moins une vie. Ton travail ici est achevé, mais ta mission pour trouver la puce de purification de l'eau continue.}
{401}{}{Après une longue bataille et beaucoup de sang versé, vous vous en sortez. Une fois les gangs vaincus, le ScrapHeap est de nouveau un havre de sûreté. Les habitants vous sont reconnaissants - Ils vous donnent de précieuses informations et votre tâche à Scrapheap est terminée. Bien entendu, votre mission pour trouver la puce de purification de l'eau continue.}
{500}{}{500 Après avoir arrêté le Maitre et anéanti son laboratoire dans lequel il créait son armée de Super Mutants, vous retournez enfin chez vous. Tout ça pour découvrir que vous êtes exilé de l'Abri à cause de votre pouvoir de destruction. Merci d'avoir joué à Fallout.}
{501}{}{501 Après avoir convaincu le Maitre d'abandonner son plan malade de domination et détruit les cuves, vous retournez enfin chez vous. Tout ça pour découvrir que vous êtes exilé afin d'éviter que d'autres habitants ne suivent votre exemple et ne soient tenté de quitter l'Abri. Merci d'avoir joué à Fallout.}
{502}{}{502 Après avoir détruit les cuves, le Maitre, et son armée de Super Mutants, vous retournez enfin chez vous. Mais il vous est interdit d'entrer dans l'Abri. Vous ne vous laissez pas faire, laissant le cadavre désarticulé du Dirigeant sur vos pas. Merci d'avoir joué à Fallout.}
{503}{}{503 Vous êtes plongé dans une cuve à FEV et vous rejoignez l'armée du Maitre. Vous révélez l'emplacement de l'Abri 13. Vous êtes récompensé en étant mis aux commandes de l'assaut contre votre Abri, et vous tuez le Dirigeant de vos propres mains. Merci d'avoir joué à Fallout.}
