{100}{}{C'est une sorte de disquette bizarre. Peut-être qu'il peut être lu dans ton Pip-Boy 2000.}
{101}{}{Message du Pip-Boy : fichier déjà présent sur le système. Abandon du chargement.}
{102}{}{Message du Pip-Boy : chargement des données sur le disque. Terminé.}
{103}{}{Tu remarques une étiquette fanée par le temps sur le disque. Il y est écrit: "Notes sur les expériences Alpha".}
{104}{}{Tu vois: Disque sur les expériences Alpha.}
