{100}{}{Cowboys.}
{101}{}{Tu repères un dispositif de déclenchement sur le placard et tu le désamorces.}
{102}{}{Tu repères un dispositif de déclenchement sur le placard, mais tu ne parviens pas à le désamorcer.}
{103}{}{Tu repères un dispositif de déclenchement sur le placard et, accidentellement, tu le déclenches !}
{104}{}{Tu désamorces le piège.}
{105}{}{Tu ne parviens pas à désarmer le piège.}
{106}{}{Tu déclenches accidentellement le dispositif de déclenchement !}
{107}{}{Tu sembles digne de confiance. Tiens, voici ce que tu veux. [Tu lui donnes tes économies]}
{108}{}{Tu ne parviens pas à court-circuiter le verrou du placard.}
{109}{}{Ce qu'il va se passer ? Tu peux nous donner tous tes caps et nous te laisserons partir. Ou nous pouvons jouer aux intrépides cowboys.}
{110}{}{En maniant le verrou, tu fais une fausse manipulation au niveau de la gorge. Il n'y a plus rien à faire maintenant.}
{111}{}{Tu remarques qu'il y a un dispositif de déclenchement d'explosif sur le placard.}
