{100}{}{Merci.}
{101}{}{Au revoir.}
{102}{}{Bonjour.}
{103}{}{Tu gagnes }
{104}{}{ points d'expérience.}
{105}{}{Oh oh !}
{106}{}{Clic !}
{107}{}{Houp !}
{108}{}{Ouch!}
{109}{}{A un de ces quatre.}
{110}{}{Mollo !}
{111}{}{C'était marrant.}
{112}{}{Voilà.}
{113}{}{Et avec ça ?}
{114}{}{Oui.}
{115}{}{Non.}
{116}{}{Tu gagnes }
{117}{}{ points compétence en Armes légères.}
{118}{}{ points compétence en Armes lourdes.}
{119}{}{ points compétence en Armes à énergie.}
{120}{}{ points de compétence en Corps-à-corps.}
{121}{}{ points de compétence en Armes de mêlée.}
{122}{}{ points de compétence en Projectiles.}
{123}{}{ points de compétence en Secourisme.}
{124}{}{ points de compétence en Médecine.}
{125}{}{ points de compétence en Furtivité.}
{126}{}{ points de compétence en Vol.}
{127}{}{ points de compétence en Crochetage.}
{128}{}{ points de compétence en Pièges.}
{129}{}{ points de compétence en science.}
{130}{}{ points de compétence en Réparation.}
{131}{}{ points de compétence en Discours.}
{132}{}{ points de compétence en Troc.}
{133}{}{ points de compétence en Jeu.}
{134}{}{ points de compétence en Vie en plein air.}
{135}{}{Tu gagnes un point de compétence en Armes légères.}
{136}{}{Tu gagnes un point de compétence en Armes lourdes.}
{137}{}{Tu gagnes un point de compétence en Armes à énergie.}
{138}{}{Tu gagnes un point de compétence en Corps-à-corps.}
{139}{}{Tu gagnes un point de compétence en Armes de mêlée.}
{140}{}{Tu gagnes un point de compétence en Projectiles.}
{141}{}{Tu gagnes un point de compétence en Secourisme.}
{142}{}{Tu gagnes un point de compétence en Médecine.}
{143}{}{Tu gagnes un point de compétence en Furtivité.}
{144}{}{Tu gagnes un point de compétence en Vol.}
{145}{}{Tu gagnes un point de compétence en Crochetage.}
{146}{}{Tu gagnes un point de compétence en Pièges.}
{147}{}{Tu gagnes un point de compétence en Science.}
{148}{}{Tu gagnes un point de compétence en Réparation.}
{149}{}{Tu gagnes un point de compétence en Discours.}
{150}{}{Tu gagnes un point de compétence en Troc.}
{151}{}{Tu gagnes un point de compétence en Jeu.}
{152}{}{Tu gagnes un point de compétence en vie en Plein air.}
{153}{}{Ta Force augmente de }
{154}{}{Ta Perception augmente de }
{155}{}{Ton Endurance augmente de }
{156}{}{Ton Charisme augmente de }
{157}{}{Ton Intelligence augmente de }
{158}{}{Ton Agilité augmente de }
{159}{}{Ta Chance augmente de }
{160}{}{ points.}
{161}{}{Ta Force augmente d'un point.}
{162}{}{Ta Perception augmente d'un point.}
{163}{}{Ton Endurance augmente d'un point.}
{164}{}{Ton Charisme augmente d'un point.}
{165}{}{Ton Intelligence augmente d'un point.}
{166}{}{Ton Agilité augmente d'un point.}
{167}{}{Ta Chance augmente d'un point.}
{168}{}{Merci de ton aide.}
{169}{}{Merci quand même.}
{170}{}{Votre tentative pour équiper une armure humaine est un échec. L'armure est détruite.}
{171}{}{Je crois que le Maître souhaite te parler.}
{172}{}{Tu paieras pour ce BLASPHEME !}
{173}{}{Ce robot ne semble pas fonctionner. Peut-être une défaillance au niveau de l'alimentation.}
{174}{}{Ce robot te semble tout à fait normal.}
{175}{}{Cet Ecorcheur refuse de te parler.}
{176}{}{La valise est scellée et impossible à ouvrir.}
{177}{}{S'il te plait, nous devons nous dépêcher. Pas le temps de parler.}
{178}{}{Seul Morpheus a les clés de cette porte. Je dois partir maintenant pour faire savoir à Nicole ce qu'il se passe ici.}
{179}{}{Je dois quitter cet endroit avant qu'ils ne découvrent qui je suis.}
{180}{}{Tu ne parviens pas à t'emparer de quoi que ce soit et tu te demandes si tu t'es fait repérer.}
{181}{}{Les membres de la Confrérie t'ont surpris en train de voler.}
{182}{}{You see: Marauding Super Mutant.}
{183}{}{}
{184}{}{}
{185}{}{}
{186}{}{Le haut-parleur se met à hurler : "Alerte ! Intrus détecté."}
{187}{}{La substance gluante a ralenti la transmission de ta frappe.}
{188}{}{Metal Armor.}
{189}{}{Leather Armor.}
{190}{}{active le Stealth-Boy.}
{191}{}{Tycho is now level }
{192}{}{Ian is now level }
{193}{}{Katja is now level }
{194}{}{Fren move! [You scowl and stamp your feet]}
{195}{}{Go, go, no need fren.}
{196}{}{We be fren?}
{197}{}{}
{198}{}{ He is wearing: }
{199}{}{ She is wearing: }
{200}{}{Tu vois un champ émetteur terriblement endommagé.}
{201}{}{L'émetteur est trop endommagé pour être utilisé.}
{202}{}{L'émetteur est trop endommagé être réparable.}
{203}{}{Tu remarques que le champ est si faible que tu peux le traverser.}
{204}{}{SuperArmure.}
{205}{}{Combat Armor.}
{206}{}{Leather Jacket.}
{207}{}{Robes.}
{208}{}{Hardened Power Armor.}
{209}{}{Brotherhood Armor.}
{210}{}{Tesla Armor.}
{211}{}{You cannot steal from this critter.}
{212}{}{You look at yourself for a while. Do you like what you see?}
{214}{}{Le poison n'est plus présent dans ton organisme.}
{215}{}{Thanks, I'll make good use of that in combat!}
{216}{}{ Walk when close.}
{217}{}{ Always run.}
{218}{}{You must have a lot of time on your hands to be checking yourself out like this.}
{219}{}{Violence Level is currently }
{220}{}{None.}
{221}{}{Minimal.}
{222}{}{Normal.}
{223}{}{Maximum Blood.}
{224}{}{ Maximum Blood advised for characters with Bloody Mess.}
{225}{}{Nice try, but that won't work.}
{291}{}{Tycho has gained a level!}
{292}{}{Ian has gained a level!}
{293}{}{Katja has gained a level!}
{294}{}{You are now level }
{295}{}{. }
{296}{}{ (max).}
{300}{}{D'accord.}
{301}{}{% de résistance aux dommages.}
{302}{}{Oh, excuse me.}
{400}{}{L'explosion a affaibli fortement le champ énergétique, le traverser est maintenant inoffensif.}
{401}{}{CONTACT SDUIBEK IF YOU SEE THIS MESSAGE}
{402}{}{EndGame Mod variables reset. Please try to enter Vault 13 again.}
{403}{}{You have died. The Vault is doomed.}
{404}{}{Your title: }
{405}{}{Vault Dweller.}
{406}{}{Vault Scion.}
{407}{}{Vault Veteran.}
{408}{}{Vault Elite.}
{409}{}{Wanderer.}
{410}{}{Desert Wanderer.}
{411}{}{Wanderer of the Wastes.}
{412}{}{Elite Wanderer.}
{413}{}{Strider.}
{414}{}{Desert Strider.}
{415}{}{Strider of the Wastes.}
{416}{}{Elite Strider.}
{417}{}{Vault Hero.}
{418}{}{Wandering Hero.}
{419}{}{Striding Hero.}
{420}{}{Hero of the Desert.}
{421}{}{Hero of the Wastes.}
{422}{}{Hero of the Glowing Lands.}
{423}{}{Paragon.}
{424}{}{Living Legend.}
{425}{}{Myth of the Wastes.}
{426}{}{Revenant Paragon.}
{427}{}{Striding Paragon.}
{428}{}{Paragon of the Wastes.}
{429}{}{Elite Paragon.}
{430}{}{Legendary Paragon.}
{431}{}{Supreme Paragon.}
{432}{}{Striding Commander.}
{433}{}{Pip-Boy displays: "FixtOS v}
{434}{}{0.9.0 }
{435}{}{active}
{436}{}{. Simulation began on FixtOS v}
{437}{}{. Upgraded from FixtOS v}
{438}{}{0.}
{439}{}{.}
{440}{}{alpha}
{441}{}{beta}
{442}{}{"}
{443}{}{. Simulation began on FixtOS v0.5.3 or older.}
{444}{}{}
{445}{}{}
{446}{}{}
{447}{}{}
{448}{}{}
{449}{}{}
{450}{}{}
{500}{}{La porte se moque de toi en résistant à l'explosion, ne recevant que des bosses et des marques de brûlure.}
{501}{}{La porte se pose des question sur sa capacité à supporter plus de dégât, tandis que le souffle la fait voler en éclat.}
{502}{}{La porte agonise alors qu'elle éclate en morceaux, s'évaporant dans un bruit assourdissant.}
{503}{}{Tu gagnes }
{504}{}{ points d'expérience pour avoir utiliser avec succès des explosifs.}
{505}{}{Le souffle n'endommage pratiquement pas la porte. Il va te falloir un second essai.}
{506}{}{Hmm, that doesn't seem to work.}
{533}{}{Commander of the Wastes.}
{534}{}{Elite Commander.}
{535}{}{Legendary Commander.}
{536}{}{Supreme Commander.}
{537}{}{Striding Exemplar.}
{538}{}{Exemplar of The Wastes.}
{539}{}{Elite Exemplar.}
{540}{}{Legendary Exemplar.}
{541}{}{Supreme Exemplar.}
{542}{}{Mythical Wanderer.}
{543}{}{Mythical Strider.}
{544}{}{Mythical Elite.}
{545}{}{Mythical Paragon.}
{546}{}{Mythical Commander.}
{547}{}{Mythical Exemplar.}
{548}{}{Mythical Hero.}
{549}{}{Supreme Jerk.}
{550}{}{You see: }
{551}{}{, the }
{552}{}{, the }
{553}{}{, a }
{554}{}{, a }
{601}{}{Tu n'as rien à faire ici, Initié.}
{602}{}{Que fais-tu ici ?}
{603}{}{Sors, je te prie. Tu n'as rien à faire ici.}
{604}{}{Hé, pas d'initiés ici.}
{605}{}{Je regrette mais je ne dois parler à personne. Tu sais ce que c'est.}
{606}{}{Tu n'as rien à faire ici, mon garçon. Si tu veux consulter, va à la bibliothèque.}
{607}{}{Tu n'as rien à faire ici, ma fille. Si tu veux consulter, va à la bibliothèque.}
{700}{}{points d'expérience !}
{701}{}{points d'expérience pour avoir détruit les Cuves.}
{702}{}{points d'expérience pour avoir détruit le Maitre.}
{800}{}{Why are you talking to rats?}
{900}{}{Pip-Boy displays: "VAULT WATER - }
{901}{}{}
{902}{}{ DAYS LEFT."}
{903}{}{ DAY LEFT."}
{1000}{}{You place the ticking explosives at your feet.}
{1001}{}{You receive a small dose of radiation.}
{1002}{}{You receive a moderate dose of radiation.}
{1003}{}{You receive a large dose of radiation.}
{1004}{}{You have been mildly irradiated.}
{1005}{}{You have been moderately irradiated.}
{1006}{}{You have been strongly irradiated.}
{1007}{}{You've been irradiated!}
{1008}{}{You have received a mild dose of radiation.}
{1009}{}{You have received a small dose of radiation.}
{1010}{}{You have received a moderate dose of radiation.}
{1011}{}{You have received a large dose of radiation.}
{1153}{}{Your Strength was decreased by }
{1154}{}{Your Perception was decreased by }
{1155}{}{Your Endurance was decreased by }
{1156}{}{Your Charisma was decreased by }
{1157}{}{Your Intelligence was decreased by }
{1158}{}{Your Agility was decreased by }
{1159}{}{Your Luck was decreased by }
{1160}{}{ points.}
{1161}{}{ point.}
{1170}{}{Your attempt to wield a human weapon has failed; the weapon is destroyed.}
{1171}{}{Your large hands are too clumsy to wield the human weapon, and it falls to your feet.}
{1180}{}{You have killed a large number of innocent people. You're now a Berserker! This generally isn't a good thing to be known for, and you are clearly a very bad person.}
{1181}{}{You are no longer a Berserker.}
