{100}{}{Tu vois un Goule zombifié.}
{101}{}{Tu vois un zombie.}
{102}{}{Ugh.}
{103}{}{Ceeerrrveeellle}
{104}{}{Beuu...}
{105}{}{gnnuuu..}
{106}{}{Grrr!}
{107}{}{Uungh.}
{108}{}{Euuuhh...}
{109}{}{Arrrr !}
{110}{}{Grrrrr !}
{111}{}{*grogne*}
{112}{}{*gargouillis*}
{113}{}{Mmmm}
{114}{}{*grogne*}
{200}{}{Vous examinez la chose pitoyable, mais ne comprenez pas ce qui pourrait l'avoir rendu comme ça.}
{201}{}{Il semble avoir été autrefois humain, ou avoir des origines humaines. Vous supposez que la détérioration de l'organisme est probablement dûe à de l'acide ou aux radiations.}
{202}{}{L'organisme de l'humanoïde paraît fortement irradié, mais toujours en fonctionnement. Jadis il était un homme, il semble avoir maintenant trouvé un style de vie plus animal.}
{203}{}{Le corps de l'humanoïde a l'air très irradié et les muscles et le cerveau semblent détériorés. Pourtant, d'après les indicateurs génétiques, tu penses qu'il descend, comme toi, des êtres entrés dans les Abris.}
{204}{}{La misérable créature est grandement irradiée. Tu n'arrives pas à savoir si sa folie est dû à l'enfermement ou aux dégâts irrémédiables causés à son cerveau par les radiations.}
{205}{}{Le corps de la créature est grandement irradié, cependant elle a conservé assez de matière grise et de fonction motrice pour pouvoir parler.}
