{100}{}{Arrête !}
{101}{}{J'espère avoir assez de cartouches.}
{102}{}{A mort.}
{103}{}{Tu paieras pour tes péchés !}
{104}{}{Tu n'as pas le droit d'être armé dans ce secteur, petit frère. Explique-toi.}
{105}{}{Tu n'as pas le droit d'être armée dans ce secteur, petite soeur. Explique-toi.}
{106}{}{Euhh.}
{107}{}{C'est bon, je travaille ici.}
{108}{}{C'est bon, j'ai un laissez-passer.}
{109}{}{J'ai l'autorisation du Lieutenant.}
{110}{}{Allons bon, qu'est-ce que c'est que cette trahison ?!}
{111}{}{Alors, montre ton laissez-passer.}
{112}{}{Je, euh, je l'ai laissé dans mon autre robe.}
{113}{}{Le voilà, au bout de mon fusil.}
{114}{}{Bon, fais vite ce que t'as à faire, mais attention : je t'ai à l'oeil.}
{115}{}{Oui, petit frère. Comment je peux t'aider ?}
{116}{}{Oui, petite soeur. Comment je peux t'aider ?}
{117}{}{Grr !}
{118}{}{Humm, où il est ce Maître ?}
{119}{}{Gloire à l'Unité, frère.}
{120}{}{C'est fâcheux, mais il faudra que tu trouves la voie vers l'Unité par toi-même.}
{121}{}{Hérétique ! Tu vas payer pour tes péchés !}
{122}{}{Il réside au Niveau 3, comme il se doit. Pourquoi une question aussi idiote ?}
{123}{}{Oh, euh, comme ça.}
{124}{}{Je vais lui régler son compte de manière, euh, définitive !}
{125}{}{Quelle question ? J'ai dit "Vive ce Maître adoré."}
{126}{}{Tu m'insultes ! Meurs donc !}
{127}{}{Gloire à l'Unité}
{128}{}{Tu ne sembles pas croire à ce que tu dis. Pas vrai ? Ou as-tu quitté le chemin de la vertu ?}
{129}{}{Tu te trompes ; si ma voix tremble, ce n'est pas de peur, c'est un rhume.}
{130}{}{Je crains fort que ton espèce ne soit condamnée. Tiens, je vais te le prouver avec l'aide de mes amis...}
{131}{}{Quand tu seras des nôtres, tu ne craindras plus ces broutilles. Hors de ma vue.}
{132}{}{Que veux-tu encore ? Je n'ai guère le temps de discuter.}
{133}{}{Euh !}
{134}{}{J'ai n'ai pas le temps de m'occuper de ta vie... Meurs donc !}
{135}{}{Rien, excuse-moi.}
{136}{}{Gloire à l'Unité, frère.}
{137}{}{Qui es-tu au juste ? Que je voie... Ahh ! Un intrus...}
{138}{}{Déguerpis. Fais ce que tu as à faire pour l'Unité et cesse de m'importuner !}
{139}{}{Allez, file.}
{140}{}{File. Fais ce que tu as à faire pour l'Unité.}
