{100}{}{On dirait la porte qui conduit à un placard d'armes.}
{101}{}{Tu crochètes le verrou de la porte.}
{102}{}{Tu n'as pas réussi à crocheter la porte.}
{103}{}{Cet objet n'a aucun effet sur la porte.}
{104}{}{La porte est verrouillée.}
{105}{}{Tu crochètes le verrou de la porte.}
{106}{}{Tu n'as pas réussi à crocheter la porte.}
{107}{}{Cette compétence ne te permet pas d'ouvrir la porte.}
