{100}{}{Un garde de Dépôtville.}
{101}{}{C'est Dépôtville. Un endroit où il fait bon vivre tant qu'on sait choisir le bon camp.}
{102}{}{Méfie-toi de Gizmo et de ses croulants.}
{103}{}{Mon chef, c'est le meilleur !}
{104}{}{Range-moi ça. Dépôtville est un endroit où il fait bon vivre et on entend bien qu'il le reste.}
{105}{}{Ranger quoi ?}
{106}{}{Me dis pas ce que j'ai à faire, minable.}
{107}{}{Ca semble correct. Au fait, qu'en est-il de la loi sur les armes par ici ?}
{108}{}{Uh oh.}
{109}{}{Ton arme, crétin. Killian ne te prendra pas tes armes, mais je te conseille de ne pas les sortir.}
{110}{}{Oh, excuse.}
{111}{}{Pas question ! Personne ne me fera déposer mes flingues !}
{112}{}{Tu ferais mieux de bien te comporter, puisque c'est la loi, et que j'applique la loi. Range ton arme, ne la sors pas sauf en cas de légitime défense, et tu n'auras pas de problème avec nous, les gardes.}
{113}{}{[Plus]}
{114}{}{Désobéis à la loi, et nous te renverrons dans le désert sans loi, mort ou vif.}
{115}{}{Bon, j'avais pas vu les choses sous cet angle.}
{116}{}{Va te faire cuire un oeuf !}
{117}{}{Bon, bon. Ca va. Mais fais gaffe !}
{118}{}{Bien, alors. Heh.}
{119}{}{Bonne question. Interdiction de faire usage des armes, sauf en cas de légitime défense. Si c'est toi qui fais feu le premier, ce sera de ta faute. Sinon, tu as parfaitement le droit de porter une arme.Ne dégaine ton couteau ou ton fusil que si tu as une bonne raison de le faire. Bonne continuation.}
{120}{}{Merci, toi aussi.}
{121}{}{Hé, toi ! Qu'est-ce que tu fais avec une arme ? T'as des oreilles, non ? Pas d'armes ici.}
{122}{}{Dorf !}
{123}{}{Tu gagnes 150 points d'expérience en tuant le garde.}
