{100}{}{Voici un ivrogne.}
{101}{}{Voici un client.}
{102}{}{Tu vois une femme sordide.}
{103}{}{Voici un homme étrange.}
{104}{}{Voici un joueur.}
{105}{}{Tu vois une très jolie dame. Elle semble être occupée.}
{106}{}{Voici une femme.}
{107}{}{Tu vois un homme.}
{108}{}{Voici un joueur bouleversé.}
{109}{}{Voici un mercenaire.}
{110}{}{Laisse-moi à mon chagrin.}
{111}{}{Tu es mon meilleur ami.}
{112}{}{Pourquoi t'es... [hic] J'suis où là ?}
{113}{}{Qui es-tu ?}
{114}{}{Je te connais ?}
{115}{}{J'ai un peu mal au coeur.}
{116}{}{C'est ma tournée, hum j'veux dire la tienne.}
{117}{}{Pourquoi je te vois en double ?}
{118}{}{Reste immobile, mec !}
{119}{}{Reste immobile, fillette !}
{120}{}{Dégage d'ici, loser !}
{121}{}{Tu ne fais pas honneur à cette maison de jeu.}
{122}{}{Va t'en, tu vas me porter la poisse !}
{123}{}{Ne me déconcentre pas.}
{124}{}{Je vais gagner !}
{125}{}{Tu es bon à ça ?}
{126}{}{Tu as vu ça ? C'est impossible !}
{127}{}{Je crois qu'ils trichent.}
{128}{}{C'est une belle donne.}
{129}{}{C'est sûr.}
{130}{}{Quoi ? Comment ai-je pu perdre ?}
{131}{}{Cette table porte malheur !}
{132}{}{Je n'ai pas le temps.}
{133}{}{Tu ne vois pas que je suis en train de jouer ?}
{134}{}{Joue ou fiche le camp.}
{135}{}{Laisse-nous tranquilles ou j'appelle les gardes.}
{136}{}{Attention, le Député Fry est un des mes amis.}
{137}{}{Qu'est-ce que tu veux ?!}
{138}{}{Pas de coups d'oeil !}
{139}{}{Je n'accepte pas les groupes.}
{140}{}{Je n'en peux plus. J'arrête.}
{141}{}{Tu rêves mon gars, casse-toi !}
{142}{}{Fiche le camp d'ici !}
{143}{}{Mais pour qui te prends-tu ?}
{144}{}{Attention à ce que tu fais !}
{145}{}{Je vais appeler les flics !}
{146}{}{Ne te fais pas d'illusions !}
{147}{}{Sors !}
{148}{}{Fiche le camp !}
{149}{}{Qu'est-ce que tu regardes ?}
{150}{}{Tu fais partie de l'orchestre ?}
{151}{}{Sors de ma chambre !}
{152}{}{Sors !}
{153}{}{Tu fais partie de l'orchestre ?}
{154}{}{Casse-toi, pervers !}
{155}{}{C'est quoi ton problème ?}
{156}{}{Fiche le camp avant que je ne m'énerve !}
{157}{}{Comme tu voudras.}
{158}{}{Elle est à moi.}
{159}{}{Damn!}
{160}{}{Tu triches ?}
{161}{}{Ca aurait dû être à moi.}
{162}{}{Presque !}
{163}{}{Raté.}
{164}{}{Quelles sont les règles déjà ?}
{165}{}{Je me débrouillais bien à ce jeu autrefois.}
{166}{}{Merci quand même.}
{167}{}{Je n'arrive pas à y croire !}
{168}{}{C'est ce que je voulais faire, vraiment.}
{169}{}{Faites vos jeux.}
{170}{}{Retirez vos mains, monsieur.}
{171}{}{Gagné !}
{172}{}{Excusez-moi, peut-être la prochaine fois.}
{173}{}{Un autre gagnant !}
{174}{}{Bas les pattes !}
{175}{}{C'est à vous.}
{176}{}{Excuse-moi, ce pari n'est pas valable.}
{177}{}{C'est comme ça.}
{178}{}{Quelqu'un d'autre ?}
{200}{}{Hé chérie, on cherche du bon temps ?}
{201}{}{Qu'est-ce que tu désires chéri ?}
{202}{}{En recherche d'une certaine compagnie ?}
{203}{}{Hé là, beautée.}
{204}{}{T'aimes bien ce que tu vois ? Moi oui.}
{205}{}{Alors montre moi ce que t'as, mon chou.}
{206}{}{J'aime quand c'est violent, si t'es dans ce genre là.}
{207}{}{Pas de maladies, je suis saine !}
{208}{}{Pour un p'tit extra, j'accepte les groupes.}
{209}{}{Je ferai n'importe quoi pour un bon prix...}
{210}{}{Je n'ai jamais été avec une fille auparavant...}
{211}{}{Je suis ton rêve qui devient réalité, ma chérie.}
{212}{}{Si t'as les caps, j'en suis.}
{213}{}{T'aimes bien ce que tu vois ? Moi oui.}
{214}{}{Salut, ma belle...}
{215}{}{Hé chérie, on cherche du bon temps ?}
{216}{}{J'aime quand c'est violent, si t'es dans ce genre là.}
{217}{}{Pas de maladies, je suis saine !}
{218}{}{Pour un p'tit extra, j'accepte les groupes.}
{219}{}{Je ferai n'importe quoi pour un bon prix...}
{220}{}{Combien coûte le tour de manège ?}
{221}{}{Vingt capsules.}
{222}{}{Passons aux choses sérieuses...}
{223}{}{Non merci, pas intéressé.}
{224}{}{Merci du bon temps. Je reviendrai plus tard.}
{225}{}{Combien pour un groupe ?}
{226}{}{Cent capsules.}
{227}{}{Très bien. Qu'est-ce que tu cherches, chéri ?}
{228}{}{Bien, suis-moi...}
{229}{}{Merci étranger. [Elle empoche les caps et te donne un baiser]}
{230}{}{Lapdance.}
{231}{}{Strip-tease.}
{232}{}{Ma jolie. Tu me suis ?}
{233}{}{Mon dieu... chérie, je dois gagner ma vie mais j'ai des limites.}
{234}{}{Amuse toi toute seule, je vais regarder.}
{235}{}{MOI JE VEUX !}
{236}{}{Les choses habituelles.}
{237}{}{Tout est n'importe quoi ! Surprends moi...}
{238}{}{Hmpf.}
{239}{}{Désolé chéri. Si tu te trouve un autre cerveau, reviens me voir.}
{240}{}{Mmf. Oh-k, moi partir.}
{241}{}{Tout dépend de ce que tu cherches, mon chou.}
{242}{}{Bien, tout le monde me suit...}
{243}{}{Caps ?}
{244}{}{[soupir] Oui idiot, des capsules. Paies moi 150 caps et t'auras du bon temps. C'est assez pour noyer mon chagrin et ma honte au bar tout en gardant un petit bénef.}
{245}{}{Ca m'est égal, allons-y et c'est tout.}
{246}{}{Seulement du sexe.}
{247}{}{Pour toi, }
{248}{}{Pour toi, sucre d'orge ? }
{249}{}{Bien, ça semble honnête.}
{250}{}{Après réflexion, je m'abstiens.}
{251}{}{Comme tu veux mon sucre d'orge, tu reviendras.}
{252}{}{Je n'ai pas autant de caps.}
{253}{}{Alors putain de merde, pourquoi tu me parles ? Tire-toi !}
{254}{}{[Continue]}
{255}{}{[Terminé]}
{256}{}{Merci surcre d'orge, reviens vite !}
{257}{}{Je suis partir.}
{258}{}{Moi pas agent...}
{259}{}{Hmpf !}
{260}{}{Je ne peux pas croire que je suis en train de faire ça...}
{261}{}{Pars, je vais aller vomir maintenant.}
{262}{}{J'ai besoin d'un nouveau boulot.}
{263}{}{Encore toi ? Casse-toi, je bosse pas avec les attardés... Surtout ceux qui ne paient pas...}
{264}{}{Grr...}
{265}{}{Hein ?}
{300}{}{ caps.}
{301}{}{Après une meilleure inspection, il semble évident qu'il s'agit d'une prostituée avec un client. Elle te fait signe de partir immédiatement !}
{302}{}{Après réflexion, il est évident que c'est une prostituée.}
{400}{}{Et bien ce fut plutôt intéressant.}
{401}{}{Wouaf !}
{402}{}{On devrait y aller maintenant.}
{403}{}{Heu, Je me sens sale.}
{404}{}{Oh ouoho...}
{405}{}{Bien... je suppose que je pourrais faire une exception. T'as intérêt à avoir un bon paquet de caps.}
