{100}{}{Devant toi se trouve une table de jeu de Craps à mises élevées. La partie coûte 40 caps.}
{101}{}{Tu as fait 7. Gagné !!}
{102}{}{Tu as fait un double 1. Perdu.}
{103}{}{Tu as fait }
{104}{}{! Gagné !!}
{105}{}{Tu as fait }
{106}{}{. Perdu !}
{107}{}{Tu as fait }
{108}{}{ avant de marquer ton point. Perdu.}
{109}{}{Tu as fait ton point. Gagné.}
{110}{}{Tu as fait }
{111}{}{. Tu as le point. Lance à nouveau les dés.}
{112}{}{Tu obtiens 70 points d'expérience pour avoir tué le croupier.}
