{100}{}{Il a l'air d'être un garde très expérimenté.}
{101}{}{T'as intérêt à faire gaffe, ici !}
{102}{}{Mieux vaut ne pas s'attirer d'ennuis ici.}
{103}{}{Tiens-toi tranquille, qu'on ne nous cherche pas des noises.}
{104}{}{C'est bon.}
{105}{}{Le travail, c'est la santé.}
{106}{}{Belle journée, pas vrai ?}
{107}{}{C'est Dépôtville. Un endroit où il fait bon vivre tant qu'on sait choisir le bon camp.}
{108}{}{Méfie-toi de Gizmo et de ses croulants.}
{109}{}{Mon chef, c'est le meilleur !}
{110}{}{Range-moi ça. Dépôtville est un endroit où il fait bon vivre et on entend bien qu'il le reste.}
{111}{}{Ranger quoi ?}
{112}{}{Me dis pas ce que j'ai à faire, minable.}
{113}{}{Ca semble correct. Au fait, qu'en est-il de la loi sur les armes par ici ?}
{114}{}{Euh, oh.}
{115}{}{Ton arme, crétin. Killian ne te prendra pas tes armes, mais je te conseille de ne pas les sortir.}
{116}{}{Oh, excuse.}
{117}{}{Pas question ! Personne ne me fera ranger mes flingues !!}
{118}{}{T'as intérêt à te tenir à carreau. La loi, c'est la loi et je suis chargé de la faire respecter. Range ton arme. Ne tire qu'en cas de légitime défense et nous autres, les gardes, on te laissera tranquille. Mais si jamais l'idée te prend de ne pas respecter la loi, sois certain qu'on te renverra illico dans ce foutu désert - toi ou ton cadavre.}
{119}{}{Bon, j'avais pas vu les choses sous cet angle.}
{120}{}{Va te faire cuire un oeuf !}
{121}{}{Bon, bon. Ca va. Mais fais gaffe !}
{122}{}{Bonne question. Interdiction de faire usage des armes, sauf en cas de légitime défense. Si c'est toi qui fais feu le premier, ce sera de ta faute. Sinon, tu as parfaitement le droit de porter une arme.Ne dégaine ton couteau ou ton fusil que si tu as une bonne raison de le faire. Bonne continuation.}
{123}{}{Hé, toi ! Qu'est-ce que tu fais avec une arme ? T'as des oreilles, non ? Pas d'armes ici.}
{124}{}{Hé ! Toi ! Qu'est-ce que tu mijotes ?}
{125}{}{Rien.}
{126}{}{J'fais rien. J'fais que me promener en faisant gaffe à mes fesses.}
{127}{}{Euhhh.}
{128}{}{Alors va voir ailleurs si j'y suis !}
{129}{}{Le garde t'observe pendant un moment. Tu lis dans ses yeux qu'il te reconnaît. Il sort son arme.}
{130}{}{Bon, euh, ok. Peu importe. L'important, c'est d'être réglo.}
{131}{}{Merci, au revoir.}
{132}{}{Certainement m'sieur !}
{133}{}{Certainement m'dame !}
{134}{}{Range-moi cette arme ou bien tu l'auras cherché !}
{135}{}{On ne te le dira pas deux fois. Quitte la ville et n'y remets plus jamais les pieds, sinon attends-toi au pire !}
{136}{}{Hé, tu te crois où ?}
{137}{}{Cette fois, tu ne l'auras pas volée.}
{138}{}{Cette fois, tu es dans un joli pétrin...}
{139}{}{Vous autres Skulz, vous êtes en état d'arrestation !}
