{100}{}{Tu vois Lex.}
{101}{}{Tu vois un loser.}
{102}{}{[Plus]}
{103}{}{[Plus]}
{104}{}{[Lex murmure.] Sois prudent. Rock ne dit pas toujours la vérité.}
{105}{}{Pourquoi ça ?}
{106}{}{Et pourquoi je devrais te faire confiance ?}
{107}{}{Rock est un membre des Crypts. C'est un gang. Il essaie de mettre les étrangers, comme toi, dans le petrin. Si tu l'écoute, tu vas finir mort et enterré.}
{108}{}{Qui es-tu ?}
{109}{}{Merci pour l'info. Bonne journée.}
{110}{}{Je suis Lex. Scrapheap c'est ma ville, et je pense que je parle au nom de tous les habitants.}
{111}{}{Qui d'autre dois-je connaître ?}
{112}{}{Et bien, il y a aussi les Fools. Il dirigeraient Scrapheap, si les Crypts n'étaient pas là. Les deux gangs luttent pour le contrôle de la ville.}
{113}{}{Qu'est-ce qui te fait dire ça ?}
{114}{}{Si tu pouvais nous débarrasser de ces gangs, nous en serions reconnaissants. Nous n'avons ni le nombre, ni la puissance, pour les repousser. Si tu es volontaire, on pourrait peut-être s'entraider.}
