{100}{}{Tu vois un disque qui porte d'étranges inscriptions, et des tâches qui semblent être du sang.}
{101}{}{Message du Pip-Boy : fichier déjà présent sur le système. Abandon du chargement.}
{102}{}{Message du Pip-Boy : chargement des données sur le disque. Terminé.}
{103}{}{On dirait que cet holodisque était utilisé pour enregistrer des transmissions radio de l'armée.}
{104}{}{Tu vois un disque de transmissions radio des Super Mutants.}
{105}{}{Le disque porte d'étranges inscriptions, et des tâches qui semblent être du sang.}
