{100}{}{A première vue, ils n'ont pas dû voyager bien loin. Ils doivent avoir un repaire près d'ici.}
{101}{}{On dirait qu'ils ne venaient pas de très loin.}
{102}{}{On dirait qu'ils venaient de quelque part au Nord d'ici.}
{103}{}{Apparemment, ils erraient dans le désert.}
{104}{}{Tu tombes sur une violente échauffourée entre des radscorpions et des rataupes.}
{105}{}{EMBUSCADE !!}
{106}{}{Tu tombes sur un important groupe de radscorpions !}
{107}{}{Tu tombes sur un groupe de radscorpions.}
{108}{}{Tu tombes sur une famille de rataupes.}
{109}{}{Tu parviens à éviter la déshydratation en trouvant de l'eau. Les recherches t'ont prit 1 heure.}
{110}{}{Tu parviens à éviter la déshydratation en trouvant de l'eau. Les recherches t'ont prit }
{111}{}{ heures.}
{112}{}{Tes réserves d'eau sont épuisées, et tes recherches ont échoué à trouver de l'eau. Tu souffres de déshydratation sévère, causant }
{113}{}{ points de dégats.}
{114}{}{Tes réserves d'eau sont épuisées, et tes recherches ont pris }
{115}{}{ heures, mais tu n'en trouves pas assez pour étancher ta soif. Tu perds }
{116}{}{ points de dégats.}
{117}{}{Tu recherches de l'eau dans le désert pendant 1 heure mais tu n'en trouves pas assez pour étancher ta soif. Tu perds un point d'impact.}
{118}{}{Tu recherches de l'eau dans le désert pendant 1 heure mais tu n'en trouves pas assez pour étancher ta soif. Tu perds}
{119}{}{ points de dégats.}
{120}{}{Tu recherches de l'eau dans le désert pendant }
{121}{}{ heures, mais tu n'en trouves pas assez pour étancher ta soif. Tu perds 1 points de dégats.}
{122}{}{Tu recherches de l'eau dans le désert pendant }
{123}{}{ heures, mais tu n'en trouves pas assez pour étancher ta soif. Tu perds }
{124}{}{ points de dégats.}
{125}{}{Tu parviens à éviter la déshydratation en utilisant tes ressources en eau.}
{126}{}{Tu tombes sur des radscorpions chassant des rataupes.}
{127}{}{Des humanoïdes hostiles, maigres et à la peau verdâtre s'approchent.}
{128}{}{Des déchets et des pierres sont éparpillés. Tu te demandes s'il reste quelque chose de valeur.}
{129}{}{Un radscorpion solitaire te tend une embuscade !}
{130}{}{Tu remarques un cadavre partiellement dévoré.}
{131}{}{PANIQUE !!}
{132}{}{Tu tombes sur un important groupe de radscorpions !}
{133}{}{Des pillards te tendent une embuscade !}
{134}{}{Un groupe d'horribles radscorpions venant du désert attaque !}
{135}{}{Tu rencontres un groupe de gardes en patrouille.}
{136}{}{Tu rencontres un marchand accompagné de plusieurs gardes.}
{137}{}{Tu tombes sur un paysan gardant des brahmines.}
{138}{}{ Tu remplis  }
{139}{}{Des radscorpions chassant des rataupes au milieu des ruines d'un village.}
{140}{}{ Nuka-colas}
{141}{}{ Nuka-cola}
{142}{}{ beer}
{143}{}{Des pillards !!}
{144}{}{Tu tombes sur un grand rassemblement de rataupes.}
{145}{}{Tu rencontres une bande de radscorpions sauvages.}
{146}{}{Tu rencontres des paysans victimes d'une attaque.}
{147}{}{Tu t'efforces à trouver de l'eau afin d'éviter la déshydratation. Les recherches t'ont prit 1 heure.}
{148}{}{ point of health damage.}
{149}{}{ beers}
{150}{}{ bottle of booze}
{151}{}{ bottles of booze}
{152}{}{Resorting to alcohol reduces your }
{153}{}{Strength}
{154}{}{Endurance}
{155}{}{Strength and Endurance}
{156}{}{ by 1 point.}
{157}{}{ by 2 points.}
{158}{}{ by 1 point each.}
{159}{}{tes flasques}
{160}{}{ avec l'eau potable.}
{161}{}{Your supply of fluids runs out, }
{162}{}{and your search of }
{163}{}{but you manage to avoid dehydration by searching for water. The search takes }
{164}{}{1 hour.}
{165}{}{Tu gagnes }
{166}{}{ points d'expérience pour avoir utilisé avec succès ta compétence Vie en plein air.}
{167}{}{}
{168}{}{}
{169}{}{Tu tombes sur une famille de radscorpions.}
{170}{}{Tu tombes sur un marchand nomade et ses gardes.}
{171}{}{Tu découvres un voyageur mort.}
{172}{}{Tu découvres des objets éparpillés au sol.}
{173}{}{Tu aperçois les restes d'une caravane mise à sac par des pillards.}
{174}{}{Tu tombes sur les restes d'un marchand et de ces gardes.}
{175}{}{Tu rencontres un voyageur.}
{176}{}{Tu te retrouves au milieu de ruines et d'immeubles abandonnés.}
{187}{}{}
{188}{}{}
{189}{}{}
{190}{}{}
{191}{}{}
{192}{}{}
{193}{}{}
{194}{}{}
{195}{}{}
{196}{}{Radscorpions en vue !}
{197}{}{Oh-oh... une fête de pillards !}
{198}{}{Tu aperçois un pillard solitaire.}
{199}{}{Tu découvres les restes d'un champ de bataille jonché de cadavres.}
{200}{}{Radscorpions en vue !}
{201}{}{}
{202}{}{}
{203}{}{}
{204}{}{}
{205}{}{}
{206}{}{}
{207}{}{}
{208}{}{}
{209}{}{}
{210}{}{}
{211}{}{}
{212}{}{}
{213}{}{}
{214}{}{}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}
{220}{}{}
{221}{}{}
{222}{}{}
{223}{}{Tu aperçois une meute errante de coyotes sauvages.}
{224}{}{Tu aperçois des individus à l'affût.}
{225}{}{Tu tombes sur une petite fête entre des marchands et leurs gardes.}
{226}{}{Tu assistes à une petite échauffourée : des hommes contre des mutants !}
{227}{}{Une immense horde de radscorpions arrive dans cette direction !}
{228}{}{}
{229}{}{}
{230}{}{}
{231}{}{}
{232}{}{}
{233}{}{}
{234}{}{}
{235}{}{}
{236}{}{}
{237}{}{}
{238}{}{}
{239}{}{}
{240}{}{}
{241}{}{}
{242}{}{}
{243}{}{}
{244}{}{}
{245}{}{}
{246}{}{}
{247}{}{}
{248}{}{}
{249}{}{}
{250}{}{Des hommes portant des SuperArmures se dirigent vers toi.}
{251}{}{Tu aperçois un groupe de marchands et de gardes.}
{252}{}{Tu assistes à une violente échauffourée entre des pillards du désert et un groupe d'hommes en SuperArmures.}
{253}{}{Tu aperçois des mutants explorant une parcelle de terre hostile.}
{254}{}{Tu aperçois d'étranges créatures...}
{255}{}{Tu trouves des objets.}
{256}{}{Une patrouille de super mutants passe tout près !}
{257}{}{Tu aperçois les ruines d'un petit village.}
{258}{}{}
{259}{}{}
{260}{}{}
{261}{}{}
{262}{}{}
{263}{}{}
{264}{}{}
{265}{}{}
{266}{}{}
{267}{}{}
{268}{}{}
{269}{}{}
{270}{}{}
{271}{}{}
{272}{}{}
{273}{}{}
{274}{}{}
{275}{}{}
{276}{}{}
{277}{}{}
{278}{}{}
{279}{}{Devant toi, tu aperçois des déchets éparpillés dans le sable.}
{280}{}{Tu tombes sur une bataille de super mutants.}
{281}{}{Tu tombes sur une bande de créatures bizarres.}
{282}{}{Tu tombes sur une bande de radscorpions affamés.}
{283}{}{Tu as des nausées et l'air semble vaciller avec la chaleur. Soudain, une créature mutante approche.}
{284}{}{Tu tombes sur d'étranges créatures flottantes.}
{285}{}{Tu rencontres quelque chose semblant tout droit sorti d'un vieux film de science-fiction.}
{286}{}{Le Griffemort !!}
{287}{}{Tu tombes sur une bande de radscorpions en déplacement. Ils semblent fuir quelque chose...}
{288}{}{Tu rencontres une créature mutante du désert.}
{289}{}{}
{290}{}{}
{291}{}{}
{292}{}{}
{293}{}{}
{294}{}{}
{295}{}{}
{296}{}{}
{297}{}{}
{298}{}{}
{299}{}{Tu aperçois des radscorpions.}
{300}{}{Tu rencontres un paysan en haillons.}
{301}{}{Tu rencontres un rataupe.}
{302}{}{Un jeune Griffemort semblant penser que tu es son casse-croûte.}
{303}{}{Tu tombes sur une bande de radscorpions en déplacement.}
{304}{}{}
{305}{}{Tu découvres les restes des gardes hostiles de Duc le marchand.}
{306}{}{Une patrouille de mutants passe tout près, accompagnée d'étranges créatures !}
{307}{}{Tu te fais prendre en embuscade par une petite équipe de super mutants.}
{308}{}{Il semble que tu te retrouves au coeur d'une violente guerre entre bandes !}
{309}{}{Un groupe de bandits hostiles t'attaque !}
{310}{}{Un petit groupe de pillards attaque !}
{311}{}{Un petit groupe de bandits attaque !}
{312}{}{Soudain, des rats t'attaquent !}
{313}{}{Soudain, une nuée de mantes mutantes t'attaque !}
{314}{}{Hé ! Ils sont vraiment là.}
{315}{}{Tu aperçois un camion renversé.}
{316}{}{Tu découvres des épaves de voitures en plein milieu du désert.}
{317}{}{Au Nord-Est, tu aperçois une cabine de police.}
{318}{}{Tu rencontres une horde de Brahmines sauvages. C'est étrange...}
