{100}{}{C'est une sorte de disquette bizarre. Peut-être qu'il peut être lu dans ton Pip-Boy 2000.}
{101}{}{Message du Pip-Boy : fichier déjà présent sur le système. Abandon du chargement.}
{102}{}{Message du Pip-Boy : chargement des données sur le disque. Terminé.}
{103}{}{Ce disque est en mauvais état. Il n'a pas d'étiquette mais quelqu'un a griffonné le mot "overide" sur le coté.}
{104}{}{Tu vois: Disque d'annulation de Sécurité.}
{105}{}{Nom d'utilisateur: "admin". Mot de passe: "muerte". Annulation du protocole de sécurité : Gamma Omicron Delta.}
{106}{}{**BEGIN-DISK**}
{107}{}{**END-DISK**}
{108}{}{[Continue]}
{109}{}{Le Pip-Boy 2000 affiche: 'Nom d'utilisateur: "admin". Mot de passe : "muerte". Contournement du protocole de sécurité : Gamma Omicron Delta.'}
