{100}{}{Tu remarques et parviens à éviter un fil monofilament tendu dans le couloir.}
{101}{}{Tu ressens une douleur intense dans tes jambes. Tu as été coupé en deux par un fil monofilament.}
{102}{}{Il endommage sévèrement ta jambe droite.}
{103}{}{Il endommage sévèrement ta jambe gauche.}
{104}{}{Tu désarmes le piège à fil monofilament et tu te débarrasses du fil en toute sécurité avant de te couper les mains.}
{105}{}{Tu essayes de désarmer le fil, mais tu n'arrives pas à le maîtriser. Tu te retires avant qu'il ne te coupe.}
{106}{}{Tu essayes de désarmer le fil, mais tu glisses et tu te coupes avec.}
