{100}{}{Tu vois Baka.}
{101}{}{Voici une femme.}
{102}{}{Les Crypts n'ont rien à faire là. Pas vrai les gars ? [Les autres Fools font un signe de tête.] Tu devrais t'en aller.}
{103}{}{J'ai fait une erreur en rejoignant les Crypts. Je veux être de votre côté.}
{104}{}{Je suis venu délivrer un message de Phrax.}
{105}{}{Je vais le faire, merci.}
{106}{}{Alors nous devrions revêtir le manteau d'un traître ? Quelqu'un qui livrerait les siens ? Mêmes les chiens ne sont pas aussi bas que toi.}
{107}{}{J'ai peur que tu retournes encore ta veste, mais tes propos sont convainquant.}
{108}{}{Phrax est trop lâche pour venir lui-même ? Et il envoie un garçon à sa place ? Hé bien, délivre ton message et va-t-en.}
{109}{}{Meurs.}
{110}{}{Il vous dit de quitter la ville, si vous voulez vivre.}
{111}{}{Il vous dit bonjour.}
{112}{}{Hahaha! J'aime un homme avec de l'humour. Tu peux vivre... Non, je plaisante...}
{113}{}{Je doute que tu comprennes ce que tes mots impliquent. J'espère que tu comprendras avant que tes os ne sèchent dans le soleil du désert. Malheureusement, ça sera dans pas longtemps.}
{114}{}{Qu'avons-nous là ? Il parait qu'il y a un nouveau venu en ville. Ca doit être toi. Permets-moi de me présenter. Je suis Baka, reine des Fools.}
{115}{}{Pourquoi vous appelez-vous les Fools?}
{116}{}{J'ai cru comprendre que vous aviez des problèmes avec les Crypts.}
{117}{}{T'as surtout l'air d'une folle.}
{118}{}{Après la guerre, seuls les fous et les idiots subsistent. Si j'avais du cran, je me serais déjà tué. À la place, je fais avec ce que les dieux de la chance nous ont laissé.}
{119}{}{Ca fait du sens. Je suis plus ou moins d'accord. Je peux me joindre à vous ?}
{120}{}{On pourrait avoir besoin de plus de bras. Laisse-moi réfléchir. [Elle met la main au menton et fait une parade dramatique dans la pièce.]}
{121}{}{Choisi bien tes mots. Certains ne sont pas aussi indulgents que moi. Je joue le rôle, ou le rôle se joue de moi, mais il y a toujours de la place pour un cadavre exquis.}
{122}{}{J'ai pas bien compris. Était-ce une menace ?}
{123}{}{Je vais essayer de bien me comporter.}
{124}{}{C'en était une. C'étaient aussi les derniers mots que tu entendras.}
{125}{}{Bien. On va voir ce que tu vaux.}
{126}{}{Que veux-tu cette fois ?}
{127}{}{Je veux rejoindre votre bande.}
{128}{}{Pourquoi vous voulez le générateur électrique ?}
{129}{}{Je ne sais pas si je peux te faire confiance. Il te faut prouver ta valeur.}
{130}{}{Une poule entre dans un bar...}
{131}{}{Je suis le meilleur combattant dans les environs.}
{132}{}{On aurait bien besoin d'un homme compétent par ici.}
{133}{}{[Plusieurs minutes s'écoulent après la fin de ta blague. Tu la regardes, avec nervosité. Elle rit.] Bravo. Tu as prouvé que tu comprenais la blague. Bienvenu.}
{134}{}{C'est ce qu'on verra.}
{135}{}{Skippy? C'est ton tour.}
{136}{}{Y a qu'une chose qui sépare Scrapheap des terres désolées, l'odeur de la merde de brahmines. Mais sans cette merde de brahmine, le générateur ne fonctionnerait pas.}
{137}{}{Pourquoi vous ne le contrôlez pas ?}
{138}{}{Merci !}
{139}{}{Parce que les Crypts le contrôlent ! Ils sont plus nombreux. Mais si tu nous rejoins, on devrait pouvoir les battre.}
{140}{}{Bien sûr. Je vous rejoins.}
{141}{}{Non, merci.}
{142}{}{Tu es stupide. Pensais-tu que j'allais vous rejoindre aussi facilement ?}
{143}{}{Oui.}
{144}{}{Ah, non !}
{145}{}{Ah, ok. Tu en es. Tu es maintenant un Fool. Si tu nous trahis, tu es mort. Yadda-yadda-yadda.}
{146}{}{Tu mens !}
{147}{}{Alors, qu'est-ce que ça fait d'être un Fool?}
{148}{}{J'aime ça.}
{149}{}{Merveilleux ! Maintenant, qu'est-ce que je fais ?}
{150}{}{Comment puis-je avoir une de ces armures ?}
{151}{}{T'as intérêt. Pas tout le monde est fait pour comprendre les nuances humoristiques des Fools.}
{152}{}{Oh, oui. Merci. Euh, ensuite ?}
{153}{}{Hmm, oui. Bonne question. J'imagine que nous pouvons préparer l'attaque contre les Crypts. Il nous faut ce générateur...}
{154}{}{Qu'est-ce que t'attends de moi ?}
{155}{}{Hé bien, vu que tu es le Fool le plus récent, tu es donc le plus sacrifiable. Je veux que tu ailles observer les positions ennemies et me faire ton rapport.}
{156}{}{D'accord.}
{157}{}{Bien. Devons-nous attaquer ?}
{158}{}{Oui !}
{159}{}{Non !}
{160}{}{Alors, pourquoi me déranger ? Va faire ton boulot et reviens-moi avec de vraies informations !}
{161}{}{Excellent ! Fools ! On part en guerre !}
{162}{}{Tu es un Fool en période de probation secrète. Tu n'auras droit à une armure qu'à la fin de ta période de probation.}
{163}{}{[Terminé]}
{164}{}{[Plus]}
{165}{}{Sales Crypts ! On va vous enterrer !}
{166}{}{Meurs enflure !}
{167}{}{Qui t'a dit que tu pouvais quitter ton cercueil ? Returne-y !}
{168}{}{Euh, rien.}
{169}{}{Tu mens ! Au boulot avant que je ne te fasse un nouveau trou !}
{170}{}{Je ne pense pas etre prêt.}
{171}{}{Euh, ouais. Salut.}
{172}{}{Seuls les Fools subsistent ! Moi, Reine Baka, règne maintenant sur Scrapheap.}
{173}{}{Tu vas peut-être pouvoir devenir un Fool, mais retiens bien ces mots: Si tu nous trahis, tu vas mourir avec une grimace, pas un rire.}
{174}{}{Et non, tu vas pas porter la tenue d'un Fool. Tu vas porter la tenue d'un traitre. Une tenue très serrée.}
{175}{}{Oui, tu pourrais être le prochain bouffon dans la cour des fous. Bienvenue chez les Fools. Si tu nous trahis, tu es mort.}
{176}{}{Et sans le générateur électrique, aucune raison de vivre dans ce taudis. Le générateur procure la chaleur, la lumière et de drôles d'expériences capillaires.}
{177}{}{Va surveiller nos ennemis et rapporte-moi des informations utiles]}
{178}{}{Dieux de la chance, dieux du destin... Je m'en fous tant que je peux rire la dernière. On ne peut pas rejoindre la mort, alors on en rit.}
