{100}{}{Tu vois Dumar, un Acolyte des Enfants de la Cathédrale.}
{101}{}{Salutations voyageur. Nous avons entendu des contes sur celui qui traverse le désert. Comment pourrions-nous t'être utiles aujourd'hui ?}
{102}{}{Uh ? Arrooo ?}
{103}{}{Le désert est un endroit difficile. J'ai été gravement blessé. Peux-tu m'aider avec ça ?}
{104}{}{Je veux que toi et tes semblables soient massacrés !}
{105}{}{Raconte-moi une histoire.}
{106}{}{Hein ? Je ne t'entends pas. Tu peux parler plus fort, s'il te plaît ?}
{107}{}{Qui puis-je consulter pour devenir membre de cet établissement ?}
{108}{}{Je souhaite comprendre la sagesse sur laquelle toi et tes Disciples avez basé cet ensemble de croyances.}
{109}{}{Je suis désolé, mais je suis un peu trop occupé en ce moment pour raconter l'histoire complète des Enfants de la Cathédrale. Ils me font nettoyer les bancs. Va parler à Laura si tu avez besoin d'informations.}
{110}{}{Je suis désolé, mais tes mots sont bien trop au-dessus de moi pour que je comprenne ce que tu as dit. Peut-être que nos Disciples les plus sages, comme Laura, seront capables de t'aider mieux que moi.}
{111}{}{Je suis vraiment désolé d'entendre parler de votre maladie. Hélas, je ne suis qu'un acolyte et je ne peux pas t'aider à te soigner. Seuls les membres à part entière ont droit à une formation dans les arts de la guérison.}
{112}{}{Ah, mon enfant, il semble que toi et moi parlons à des niveaux différents. Peut-être que si tu parles à Laura, elle pourra t'aider mieux que moi. Paix à toi, mon enfant.}
{113}{}{S'il te plaît, va parler à Laura. Elle peut t'aider mieux que moi.}
{114}{}{Nous sommes vraiment un peuple pacifique. S'il te plaît, ne verse pas de sang dans ce lieu saint.}
{115}{}{Il était une fois un petit voyageur qui faisait le tour du monde. Il s'approcha d'une jeune femme nommée Laura et lui demanda de lui raconter une histoire. Fin.}
{116}{}{Dumar te supplie de cesser tes attaques vicieuses.}
