{100}{}{Tu ne peux pas déterminer si tu es empoisonné ou irradié.}
{101}{}{Tu es irradié et empoisonné, mais tu ne sais pas dans quelle mesure.}
{102}{}{Tu es irradié, mais tu ne sais pas à quel point.}
{103}{}{Tu es empoisonné, mais pas sûr de l'étendu.}
{104}{}{Diagnostic : }
{105}{}{très peu}
{106}{}{très légèrement}
{107}{}{légèrement}
{108}{}{modérément}
{109}{}{très}
{110}{}{extrêmement}
{111}{}{dangereusement}
{112}{}{fatalement}
{113}{}{ irradié}
{114}{}{.}
{115}{}{ and }
{116}{}{Niveau d'irradiation : }
{117}{}{ rads.}
{118}{}{ Tu es empoisonné au niveau }
{119}{}{Tu n'es plus empoisonné ou irradié.}
{200}{}{}
