{100}{}{Voici un Chevalier.}
{101}{}{Je me demande à quoi ressemblaient les vieux turbomoteurs.}
{102}{}{Ce serait super si on avait une voiture qui marche.}
{103}{}{Tu savais que l'homme est allé sur la lune ? Enfin, à ce qu'il paraît.}
{104}{}{Je ne trouve pas le fichier dont j'ai besoin.}
{105}{}{Un jour, je serai Paladin.}
{106}{}{Talus est un excellent guerrier. Je n'aimerais pas devoir me mesurer à lui.}
{107}{}{Thomas est le meilleur combattant de la Confrérie. Je parie qu'il battrait Rhombus.}
{108}{}{J'aimerais mettre la main sur ces pillards et leur montrer le sort que méritent les voleurs.}
{109}{}{C'est ça... Quoi ? Oh. Je peux pas parler maintenant, je m'excuse.}
{110}{}{Je me demande... Pardon ? Oh, tu m'as fait perdre le fil de mes pensées.}
{111}{}{J'aime travailler sur de nouveaux prototypes.}
{112}{}{Quand les stocks s'épuisent, ça devient parfois difficile d'arriver à faire avec ce qu'on a.}
{113}{}{Je ne comprends pas pourquoi mon dernier prototype n'a pas fonctionné.}
{114}{}{Je peux pas parler maintenant, je m'excuse.}
{115}{}{Vree est là-bas.}
{116}{}{Bon, où j'ai mis ce fichier...}
{117}{}{Où est ce schéma ?}
{118}{}{D'après l'ordinateur ça devrait marcher ; j'ai dû faire une erreur, mais laquelle ?}
