{100}{}{Voici un conducteur de caravane.}
{101}{}{La journée sera longue !}
{102}{}{Je n'ai vraiment pas envie de travailler aujourd'hui.}
{103}{}{J'espère qu'on ne va pas être pillés... ou pire.}
{104}{}{On n'a plus besoin de gardes... Je pense.}
{105}{}{Impossible, on est au complet.}
{106}{}{Pour du boulot, tu devrais aller voir au Grand Marché.}
{107}{}{J'espère qu'on arrivera à tout vendre.}
{108}{}{Vivement qu'on ait terminé.}
{109}{}{Allez, faut tracer la route.}
{110}{}{Prêt pour la baston.}
{111}{}{On met les voiles !}
{112}{}{Chaude journée, non ?}
{113}{}{Bon sang que j'ai soif !}
{114}{}{On est quel jour ?}
{115}{}{Dès que j'ai terminé, je vais au Faucon !}
{116}{}{Désolé mais on revient juste d'une tournée.}
{117}{}{Pour du boulot, tu devrais aller voir au Grand Marché.}
{118}{}{C'est le jour de la paie !}
{119}{}{Je vais directement chez Bob !}
{120}{}{Il faut que je rembourse le prêt aujourd'hui !}
{121}{}{J'en peux plus.}
{122}{}{Quel long voyage !}
{123}{}{Bon, il est temps d'aller se pieuter.}
{124}{}{A demain, tout le monde.}
{125}{}{Eh ben, quelle nuit !}
{126}{}{C'est plus de mon âge...}
{200}{}{Voici Mat.}
{201}{}{A demain, les gars. Faites gaffe aux morpions...}
{202}{}{Eh ben, quel drôle de rêve.}
{203}{}{Oui ? Je peux être utile à quelque chose ?}
{204}{}{Hein ?}
{205}{}{Où sommes-nous ?}
{206}{}{Pourrais-tu me dire où trouver une puce d'eau ?}
{207}{}{Qu'est-ce que font tous ces charriots ici ?}
{208}{}{Oh ! Pardon. J'ai cru que tu étais quelqu'un d'autre. Salut.}
{209}{}{Ouais. Tu peux crever.}
{210}{}{Trop longtemps dans le désert, hein ? C'est dommage.}
{211}{}{On est au Centre. C'est la ville commerçante du désert. C'est la plus grande ville que je connaisse. On peut y trouver tout ce qu'on cherche. Si tu cherches du travail, c'est là que t'en trouveras. Au Centre, tu trouveras toujours quelqu'un pour te proposer quelque chose, réglo ou non.}
{212}{}{Pourrais-tu me dire où trouver une puce d'eau ?}
{213}{}{Qu'est-ce que tous ces chariots font ici ?}
{214}{}{Du commerce ? Quel genre de commerce ?}
{215}{}{Où faut-il que j'aille pour trouver du travail ?}
{216}{}{Au revoir.}
{217}{}{Une puce d'eau ? Ouah. Alors là, tu me poses une colle. J'en ai jamais entendu parler. Tu devrais certainement passer au grand magasin en ville. Ils pourront peut-être t'aider.}
{218}{}{Qu'est-ce que tous ces chariots font ici ?}
{219}{}{Merci. Au revoir.}
{220}{}{Ce sont les caravanes. On transporte des marchandises à peu près partout dans le désert. Dépôtville, la Confrérie, les Sables Ombragés et plein d'autres endroits encore. Nécropolis et le Rayon sont les seuls endroits où l'on ne met pas les pieds. C'est moi qui conduis ce groupe et on lève le camp dans pas très longtemps. Le groupe de l'autre côté de la rue vient d'arriver.}
{221}{}{On dirait que c'est la même caravane que j'ai déjà vue, non ?}
{222}{}{Qu'est-ce que tu vends ?}
{223}{}{Où sommes-nous ?}
{224}{}{Où faut-il que j'aille pour trouver du travail ?}
{225}{}{Merci. Au revoir.}
{226}{}{Hmm... Pas mal de choses. Des choses dont les gens ont besoin pour vivre, comme la nourriture, l'eau, beaucoup d'eau... L'eau, c'est certainement ce qui manque le plus dans le désert.}
{227}{}{Pourrais-tu me dire où trouver une puce d'eau ?}
{228}{}{Où faut-il que j'aille pour trouver du travail ?}
{229}{}{Merci. Au revoir.}
{230}{}{Au Centre, il suffit de demander pour trouver. Ou bien, consulte les offres d'emploi. On trouve des tableaux d'affichage un peu partout au Centre. Ce n'est pas le travail qui manque, crois-moi.}
{231}{}{Où sommes-nous ?}
{232}{}{Pourrais-tu me dire où trouver une puce d'eau ?}
{233}{}{Qu'est-ce que tous ces chariots font ici ?}
{234}{}{Merci. Au revoir.}
{235}{}{[Rires] Oui. On peut le dire. Au bout d'un moment, ils se ressemblent tous. Mais crois-moi, c'est pas les mêmes.}
{236}{}{Si tu continues à te payer ma tête, je te bute !!}
{237}{}{Où faut-il que j'aille pour trouver du travail ?}
{238}{}{Au revoir.}
{300}{}{Voici Luke.}
{301}{}{Ce sont les caravanes. On transporte des marchandises à peu près partout dans le désert. Dépôtville, la Confrérie, les Sables Ombragés et plein d'autres endroits encore. On vient d'arriver. C'était un long voyage. Le Groupe de l'autre côté de la rue est sur le départ.}
{400}{}{Voici John.}
{401}{}{Qu'est-ce que tu fais ici à cette heure ?}
{402}{}{Imbécile. Fous le camp.}
{403}{}{Une puce d'eau ? Je n'en ai jamais entendu parler.}
{404}{}{Ce sont les caravanes que je garde. Les marchands transportent des marchandises à peu près partout dans le désert. Dépôtville, la Confrérie, les Sables Ombragés et plein d'autres endroits.}
{405}{}{Eh ben... Pas mal de choses. Des choses dont les gens ont besoin pour vivre, comme la nourriture, l'eau, beaucoup d'eau... L'eau, c'est certainement ce qui manque le plus dans le désert.}
{406}{}{Au Centre, il suffit de demander pour trouver. Ou bien, consulte les offres d'emploi. On trouve des tableaux d'affichage un peu partout au Centre.}
{407}{}{Je travaille comme garde pour les Marchands qui possèdent les marchandises dans ces chariots. Un boulot dangereux, mais c'est bien payé. Pas plus tard que la nuit dernière, un de mes collègues a été tué pendant sa garde.}
{408}{}{Qu'est-ce que c'est les Caravanes ?}
{409}{}{Ahhhh.[sarcastique] Quelle triste histoire. Et si tu le rejoignais ton copain ?}
{410}{}{Ciao.}
{501}{}{Tu vois un garde de la Caravane.}
{502}{}{Voici un conducteur de caravane.}
{503}{}{Voici un conducteur de caravane.}
{504}{}{Tu vois un marchand de la Caravane.}
