{100}{}{Voici l'un des gardes de Hightower.}
{101}{}{Tu ferais mieux de déguerpir. Daren Hightower n'aime pas les visites.}
{102}{}{Ta présence n'est pas la bienvenue.}
{103}{}{Va-t'en !}
{104}{}{Tu n'as rien à faire ici.}
{105}{}{Tire-toi ou tu vas le regretter.}
{106}{}{T'as dû te tromper d'adresse. T'as rien à faire ici.}
{107}{}{Nom d'un... Regarde ça !}
{108}{}{Tu as fait une grave erreur en te pointant ici !}
{109}{}{Qu'est-ce que tu fous ici. Prépare-toi à mourir !}
{110}{}{Hmmm, ça sent bon !}
{111}{}{C'est de la brahmine que je sens ?}
{112}{}{Je me rincerais bien encore un peu le gosier !}
{113}{}{Y'a rien à bouffer dans le frigo ?}
{114}{}{Quand est-ce qu'on bouffe ?}
{115}{}{J'ai faim.}
{116}{}{Ca y est ? C'est prêt ?}
{117}{}{Je vais tomber dans les vapes !}
