{100}{}{Tu vois : Richie.}
{101}{}{Tu n'es pas censé faire ça. Je vais devoir t'arrêter !}
{102}{}{Tu n'es pas censé être ici. Tu réalises que je suis censé te tuer ?}
{103}{}{Ton service est terminé. Je suis le remplaçant.}
{104}{}{Inspecteur du coffre-fort du Centre. Je suis ici pour inspecter le coffre-fort. Ecartez-vous.}
{105}{}{Gamin, bats-toi. Mets fin au cycle de la violence maintenant !}
{106}{}{Qui t'a dit ça ? Monsieur, si tu m'attaques, ce sera la plus grosse erreur de ta vie !}
{107}{}{Salut, petit ! Qu'est-ce qu'il y a dans le coffre-fort en acier ?}
{108}{}{Trop tard, punk. Tu es mort.}
{109}{}{Uh... yeah... runk...}
{110}{}{Je ne suis pas censé te parler ! Fiche le camp !}
{111}{}{C'est l'heure ! C'est chaud ici ! Ennuyeux aussi ! Si je n'avais pas besoin de ce travail pour nourrir ma famille, j'enverrais Lorenzo se faire voir. On se voit demain.}
{112}{}{Je ne suis pas censé quitter cet endroit et tu n'es pas censé être ici. Sors !}
{113}{}{Vous, les fonctionnaires du Centre, vous me rendez malade ! Inspecter le coffre-fort de mes patrons ! C'est quoi la suite, des impôts plus élevés ? Est-ce qu'un homme ne peut plus gagner sa vie honnêtement sans que vous, les bureaucrates, essayiez de tout contrôler ? Un de ces jours, nous allons prendre position. Oui, un de ces jours, l'homme du peuple vous donnera un coup de genou dans les couilles comme vous le méritez, bande de gros bonnets. Un de ces jours, nous vous aurons vraiment bien... J'ai hâte... Au fait, ce n'est pas personnel. Je sais que tu fais juste ton travail. Je vais vous laisser tranquille pendant que vous faites votre inspection. Au revoir.}
{114}{}{Ne me donne pas cette merde ! Sors d'ici maintenant ou je vais devoir te tirer dessus !}
{115}{}{Ah ouais. Et bien personne ne bouscule Richie Glowsteader et ne s'en sort avec ça !}
{116}{}{Oh, juste environ 10 000 capsules. J'espère que tu ne pensais pas à le voler. Je devrais te tuer. J'ai presque tué quelqu'un une fois, alors tu n'as pas envie de me chercher !}
{117}{}{Mec, tu es stupide. Oh, désolé, je ne voulais pas t'offenser. Maintenant, essayons encore une fois. "Oui" signifie que je te fais sauter la tête. "Non" signifie que tu sors tes fesses d'ici. Qu'est-ce que ça va être ?}
{118}{}{Ah... yes... }
{119}{}{Uh... no...}
{120}{}{Runk ! Runk !}
{121}{}{Mec, je ne peux pas le faire ! Ce serait comme tirer sur un animal stupide. Sors juste d'ici, ok ?}
{122}{}{C'est bien. Maintenant, allez-y. Je suis sûr que tu trouveras quelqu'un pour te nourrir...}
{123}{}{Peut-être qu'un runk signifie 'oui' et deux runks signifient 'non'. Ok, "runk" signifie que je te tue. "Runk, runk" signifie que tu pars. D'accord ?}
{124}{}{Runk}
{125}{}{Runk, runk.}
{126}{}{Runk, runk, runk !}
{127}{}{Trois runks. Merde, ça ne marche pas. Peut-être que je vais juste t'ignorer et que tu vas t'éloigner...}
