{100}{}{Ves: a Billy.}
{101}{}{Hola.}
{102}{}{Hola, ¿qué haces?}
{103}{}{¿Puedo coger un brahmin?}
{104}{}{Hola. Eh, adiós.}
{105}{}{¡Arg!}
{106}{}{Ta.}
{107}{}{¿Por qué quieres un brahmin? ¿Tienes una caravana? Bueno, no importa. Yo solo cuido de ellos. Dan es su propietario y, además, no te los venderá.}
{108}{}{¿Por qué?}
{109}{}{Solo bromeaba.}
{110}{}{Por lo de las caravanas desaparecidas. A él no le sobra ninguno, las caravanas los necesitan casi todos. Los otros, se venden por comida. Bueno, será mejor que pare de hablar; Dan se enfadará si me ve hablando con una extraña.}
{111}{}{Oh, vale.}
{112}{}{Nada... Bueno, me encargo de los brahmines.}
{113}{}{¿Para qué sirve la lanza? ¿Son peligrosos?}
{114}{}{¿Qué es un brahmin?}
{115}{}{"¿Qué es un brahmin?" Debes estar bromeando. Los brahmines son la principal fuente de alimentos y de transporte de por aquí. Tiran de las caravanas. Dan dice que es un trabajo muy importante, pero es mentira.}
{116}{}{Oh, ¡ya lo sabía!}
{117}{}{Dan tiene razón. Estás haciendo un gran trabajo.}
{118}{}{Sí, eso parece. Que te diviertas.}
{119}{}{Oye, eres uno de esos yonquis, ¿no?}
{120}{}{¿En serio? ¿Eso crees? Oh, muchas gracias.}
{121}{}{Tú no eres de por aquí, ¿no? Solo te daré un consejo amistoso: ¡Que no te cojan robando!}
{122}{}{Claro, gracias.}
{123}{}{No se me ocurriría robar. Robar está mal.}
{124}{}{Sí. Creo que empiezo a estar de acuerdo contigo. Este trabajo no es tan malo en el fondo. Me hace sentir bien por alguna razón. Bueno, debo irme antes de que me meta en líos.}
{125}{}{Por favor, no me hagas daño ni a mí, ni a mis brahmines.}
{126}{}{¡No me hagas daño!}
{127}{}{¡Déjalo!}
{128}{}{Por favor, déjame tranquilo.}
{129}{}{Me estás dando miedo.}
{130}{}{Oye, ¿qué intentas hacer? No tengo nada que te interese.}
{131}{}{¡Para eso!}
{132}{}{¿Peligrosos? No mucho. Aunque no lo parezca, son alucinantes. Se tiran pedos y eructan mucho. No sé por qué.}
{133}{}{¿Para qué sirve la lanza entonces?}
{134}{}{Vale, gracias.}
{135}{}{Oh, pueden ser muy cabezotas cuando les pides que hagan algo. Entonces, los golpeo suavemente para que se muevan... pero no quiero acercarme demasiado porque a veces dan patadas.}
{136}{}{Por favor, no me hables. Dan me va a gritar otra vez. Se cabrea... quiero decir... se enfadada cuando no presto atención a lo que estoy haciendo.}
{137}{}{Solo intenta ayudarte. Trabaja duro y seguro que será más amable.}
{138}{}{Aquí tienes, chico, toma 50 chapas y sal de este agujero.}
{139}{}{Vale.}
{140}{}{¡Aaaaaarg!}
{141}{}{¿Rhu?}
{142}{}{Oh, no. Ya tengo bastantes problemas.}
{143}{}{¡YA trabajo duro!}
{144}{}{Lo siento, no quería decir eso. Él solo intenta ayudarte. }
{145}{}{Seguro, ¡tío vago!}
{146}{}{Vale.}
{147}{}{Sí, puede que tengas razón. Ahora parece excelente, pero me gustaría que no me gritara tanto.}
{148}{}{Sí, claro.}
{149}{}{¡Viejo cretino!}
{150}{}{¡Vieja arpía!}
{151}{}{¡Guau! Puedo vivir de esto toda mi vida. ¡Muchísimas gracias, señor!}
{152}{}{¡Guau! ¡Puedo vivir de esto el resto de mi vida! ¡Muchas gracias, señora!}
{153}{}{¡Guau! Gracias. ¿Pero?... ¡Estás intentando meterme en líos de nuevo!}
{154}{}{Por favor no me hables. Dan está como una cabra.}
{155}{}{No te preocupes. He hablado con él; intentará ser más agradable.}
{156}{}{¡Y tiene sus razones! ¡Eres un niño terrible!}
{157}{}{Bah.}
{158}{}{¡Hola!}
{159}{}{Esas niñas de ahí parecen tontas.}
{160}{}{Hola otra vez.}
{161}{}{Los brahmines son geniales.}
{162}{}{Dan me llevará al Halcón si hago un buen trabajo.}
{163}{}{Dan me llevará en una caravana algún día.}
{164}{}{Cuando sea mayor seré aventurero.}
{165}{}{¿De verdad? Vale. Espero que no le hicieras daño. En el fondo no es tan malo. Lo único es que grita mucho.}
{166}{}{Hola de nuevo.}
{167}{}{¿Qué quieres ahora?}
{168}{}{¿Puedo coger un brahmin?}
{169}{}{Solo pasaba para ver cómo iban las cosas. Adiós.}
{170}{}{¡Arg!}
{171}{}{Ta.}
{172}{}{Será mejor que regrese al trabajo.}
{173}{}{Esas niñas de ahí parecen tontas.}
{174}{}{Hola otra vez.}
{175}{}{Cuando sea mayor seré aventurero.}
{176}{}{Claro que los brahmines cag... uh, hacen mucha cacota.}
{177}{}{Ahora no puedo hablar.}
{178}{}{No quiero meterme en líos.}
