{100}{}{Gracias.}
{101}{}{Adiós.}
{102}{}{Hola.}
{103}{}{Ganas }
{104}{}{ puntos de experiencia.}
{105}{}{¡Oh oh!}
{106}{}{¡Clic!}
{107}{}{¡Uy!}
{108}{}{¡Ouch!}
{109}{}{Nos vemos.}
{110}{}{Tómatelo con calma.}
{111}{}{Ha sido divertido.}
{112}{}{Aquí están.}
{113}{}{¿Algo más?}
{114}{}{Sí.}
{115}{}{No.}
{116}{}{Ganas }
{117}{}{ puntos de habilidad en Armas Pequeñas.}
{118}{}{ puntos de habilidad en Armas Grandes.}
{119}{}{ puntos de habilidad en Armas de Energía.}
{120}{}{ puntos de habilidad en Combate Desarmado.}
{121}{}{ puntos de habilidad en Armas de Melé.}
{122}{}{ puntos de habilidad en Armas Arrojadizas.}
{123}{}{ puntos de habilidad en Primeros Auxilios.}
{124}{}{ puntos de habilidad en Médico.}
{125}{}{ puntos de habilidad en Sigilo.}
{126}{}{ puntos de habilidad en Robar.}
{127}{}{ puntos de habilidad en Ganzúa.}
{128}{}{ puntos de habilidad en Trampas.}
{129}{}{ puntos de habilidad en Ciencia.}
{130}{}{ puntos de habilidad en Reparar.}
{131}{}{ puntos de habilidad en Conversación.}
{132}{}{ puntos de habilidad en Trueque.}
{133}{}{ puntos de habilidad en Jugar.}
{134}{}{ puntos de habilidad en Supervivencia.}
{135}{}{Ganas 1 punto de habilidad en Armas Pequeñas.}
{136}{}{Ganas 1 punto de habilidad en Armas Grandes.}
{137}{}{Ganas 1 punto de habilidad en Armas de Energía.}
{138}{}{Ganas 1 punto de habilidad en Combate Desarmado.}
{139}{}{Ganas 1 punto de habilidad en Armas de Melé.}
{140}{}{Ganas 1 punto de habilidad en Armas Arrojadizas.}
{141}{}{Ganas 1 punto de habilidad en Primeros Auxilios.}
{142}{}{Ganas 1 punto de habilidad en Médico.}
{143}{}{Ganas 1 punto de habilidad en Sigilo.}
{144}{}{Ganas 1 punto de habilidad en Robar.}
{145}{}{Ganas 1 punto de habilidad en Ganzúa.}
{146}{}{Ganas 1 punto de habilidad en Trampas.}
{147}{}{Ganas 1 punto de habilidad en Ciencia.}
{148}{}{Ganas 1 punto de habilidad en Reparar.}
{149}{}{Ganas 1 punto de habilidad en Conversación.}
{150}{}{Ganas 1 punto de habilidad en Trueque.}
{151}{}{Ganas 1 punto de habilidad en Jugar.}
{152}{}{Ganas 1 punto de habilidad en Supervivencia.}
{153}{}{Tu Fuerza ha incrementado en }
{154}{}{Tu Percepción ha incrementado en }
{155}{}{Tu Resistencia ha incrementado en }
{156}{}{Tu Carisma ha incrementado en}
{157}{}{Tu Inteligencia ha incrementado en }
{158}{}{Tu Agilidad ha incrementado en }
{159}{}{Tu Suerte ha incrementado en }
{160}{}{ puntos.}
{161}{}{Tu Fuerza ha aumentado 1 punto.}
{162}{}{Tu Percepción ha aumentado 1 punto.}
{163}{}{Tu Resistencia ha aumentado 1 punto.}
{164}{}{Tu Carisma ha aumentado 1 punto.}
{165}{}{Tu Inteligencia ha aumentado 1 punto.}
{166}{}{Tu Agilidad ha aumentado 1 punto.}
{167}{}{Tu Suerte ha aumentado 1 punto.}
{168}{}{Gracias por tu ayuda.}
{169}{}{Gracias por nada.}
{170}{}{Fallas al intentar ponerte una armadura humana; la armadura queda destruida.}
{171}{}{Creo que el Maestro desea hablar contigo.}
{172}{}{¡Pagarás por tu BLASFEMIA!}
{173}{}{Este robot parece estar fuera de servicio. Posiblemente se deba a la falta de energía.}
{174}{}{No ves nada especial en este robot.}
{175}{}{Este Navaja se niega a hablar contigo.}
{176}{}{La maleta está sellada y no puede abrirse.}
{177}{}{Por favor, debemos darnos prisa. No hay tiempo para hablar.}
{178}{}{Solo Morfeo tiene la llave de esta puerta. Debo irme ahora para hacerle saber a Nicole lo que ocurre aquí.}
{179}{}{Por favor, tengo que irme de aquí antes de que descubran quién soy.}
{180}{}{No puedes robar nada y piensas que quizás te han pillado.}
{181}{}{Los miembros de la Hermandad te han pillado robando.}
{182}{}{Ves: un Supermutante invasor.}
{183}{}{}
{184}{}{}
{185}{}{}
{186}{}{Escuchas el altavoz: "¡Atención! Se ha detectado a un intruso".}
{187}{}{La sustancia pegajosa ha interrumpido la transmisión de tu jugada maestra.}
{188}{}{Armadura de Metal.}
{189}{}{Armadura de Cuero.}
{190}{}{Hazte a un lado, por favor.}
{191}{}{Tycho es ahora de nivel }
{192}{}{Ian es ahora de nivel }
{193}{}{Katja es ahora de nivel }
{194}{}{Fren mover! [Usted ceño fruncido y el sello de sus pies]}
{195}{}{Ir, ir, no hacer falta migo.}
{196}{}{¿Nosotros ser migos?}
{197}{}{}
{198}{}{ Lleva puesto: }
{199}{}{ Lleva puesto: }
{200}{}{Estás viendo un emisor de campo muy dañado.}
{201}{}{El emisor está demasiado dañado para utilizarse.}
{202}{}{El emisor está demasiado dañado para repararse.}
{203}{}{Te das cuenta de que el campo está demasiado dañado para funcionar.}
{204}{}{Armadura de Energía.}
{205}{}{Armadura de Combate.}
{206}{}{Chupa de Cuero.}
{207}{}{Túnica.}
{208}{}{Armadura de Energía (R).}
{209}{}{Armadura de la Hermandad}
{210}{}{Armadura Tesla.}
{211}{}{No puedes robarle a esta criatura.}
{212}{}{Te miras durante un rato. ¿Te gusta lo que ves?}
{214}{}{El veneno ha abandonado tu sistema.}
{215}{}{¡Gracias, le daré buen uso en combate!}
{216}{}{ Camina al estar cerca.}
{217}{}{ Correr siempre.}
{218}{}{Debes de tener mucho tiempo para estar viéndote de esta forma.}
{219}{}{El nivel de violencia es }
{220}{}{Ninguna.}
{221}{}{Mínimo.}
{222}{}{Normal.}
{223}{}{Máximo.}
{224}{}{ Nivel máximo recomendado para personajes con Masacre.}
{225}{}{Buen intento, pero eso no funcionará.}
{291}{}{¡Tycho ha subido un nivel!}
{292}{}{¡Ian ha subido un nivel!}
{293}{}{¡Katja ha subido un nivel!}
{294}{}{Ahora eres de nivel }
{295}{}{. }
{296}{}{ (max).}
{300}{}{Vale.}
{301}{}{Ups, lo siento.}
{302}{}{Oh, perdona.}
{400}{}{La explosión debilita en gran medida este campo de energía. Ahora debería ser inofensivo pasar a través de él.}
{401}{}{CONTACTA CON SDUIBEK SI VES ESTE MENSAJE}
{402}{}{Variables del mod EndGame reseteadas. Por favor, intenta entrar de nuevo al Refugio 13.}
{403}{}{Has muerto. El Refugio está condenado.}
{404}{}{Tu título: }
{405}{}{Moradora del Refugio.}
{406}{}{Vástago del Refugio.}
{407}{}{Veterana del Refugio.}
{408}{}{Élite del Refugio.}
{409}{}{Nómada.}
{410}{}{Nómada del Desierto.}
{411}{}{Nómada del Yermo.}
{412}{}{Élite Nómada.}
{413}{}{Viajera.}
{414}{}{Viajera del Desierto.}
{415}{}{Viajera del Yermo.}
{416}{}{Viajero de élite.}
{417}{}{Heroína del Refugio.}
{418}{}{Heroína Errante.}
{419}{}{Heroína Viajera.}
{420}{}{Heroína del Desierto.}
{421}{}{Heroína del Yermo.}
{422}{}{Heroína de las Tierras Resplandecientes.}
{423}{}{Parangón.}
{424}{}{Leyenda Viva.}
{425}{}{Mito del Yermo.}
{426}{}{Resucitado ejemplar.}
{427}{}{Viajero ejemplar.}
{428}{}{Parangón del Yermo.}
{429}{}{Parangón de élite.}
{430}{}{Parangón legendario.}
{431}{}{Parangón supremo.}
{432}{}{Comandante Viajero.}
{433}{}{Pip-Boy muestra: "FixtOS v}
{434}{}{0.9.0 }
{435}{}{activo}
{436}{}{. La simulación comenzó en FixtOS v}
{437}{}{. Actualizado desde FixtOS v}
{438}{}{0.}
{439}{}{.}
{440}{}{alfa}
{441}{}{beta}
{442}{}{"}
{443}{}{. La simulación comenzó en FixtOS v0.5.3 o más.}
{444}{}{}
{445}{}{}
{446}{}{}
{447}{}{}
{448}{}{}
{449}{}{}
{450}{}{}
{500}{}{La puerta se burla de ti al resistir, desafiante, la explosión, recibiendo solo algunas abolladuras.}
{501}{}{A la puerta le preocupa su habilidad para recibir más daño mientras cruje y se retuerce debido a la explosión.}
{502}{}{La puerta gime en agonía mientras sale volando de sus engranajes, cayendo al suelo y provocando un gran estruendo.}
{503}{}{Ganas }
{504}{}{ puntos de experiencia por utilizar explosivos con éxito.}
{505}{}{La explosión no termina de destruir la puerta. Necesitaras una más.}
{506}{}{Mmm, No funciona al parecer.}
{533}{}{Comandante del Yermo.}
{534}{}{Comandante de élite.}
{535}{}{Comandante legendario.}
{536}{}{Comandante supremo.}
{537}{}{Viajero ejemplar.}
{538}{}{Modelo ejemplar del Yermo.}
{539}{}{Modelo ejemplar de élite.}
{540}{}{El Legendario Modelo.}
{541}{}{Supremo Ejemplar.}
{542}{}{Nómada mítico.}
{543}{}{Viajero mítico.}
{544}{}{Élite mítico.}
{545}{}{Parangón mítico.}
{546}{}{Comandante mítico.}
{547}{}{Mítico Ejemplar.}
{548}{}{Héroe mítico.}
{549}{}{Supremo Tirón.}
{550}{}{Ves: }
{551}{}{, el }
{552}{}{, el }
{553}{}{, un }
{554}{}{, un }
{601}{}{No deberías estar aquí, Iniciada.}
{602}{}{¿Qué estás haciendo aquí?}
{603}{}{Por favor, vete. No deberías estar aquí.}
{604}{}{Ey, no Iniciados.}
{605}{}{Lo siento, no puedo hablar con nadie. Ya sabes como es.}
{606}{}{Esta no es la biblioteca, chico. Si quieres investigar, por favor, ve a la biblioteca.}
{607}{}{Esta no es la biblioteca, chica. Si quieres investigar, por favor, ve a la biblioteca.}
{700}{}{¡Ganas 10000 puntos de experiencia!}
{701}{}{Ganas 10000 puntos de experiencia por destruir los Tanques!}
{702}{}{Ganas 10000 puntos de experiencia por destruir al Maestro!}
{800}{}{¿Por qué les hablas a las ratas?}
{900}{}{En el Pip-Boy se lee: "AGUA DEL REFUGIO - }
{901}{}{}
{902}{}{ DÍAS."}
{903}{}{ DÍAS."}
{1000}{}{Colocas los explosivos a tus pies.}
{1001}{}{Recibes una pequeña cantidad de radiación.}
{1002}{}{Recibes una moderada cantidad de radiación.}
{1003}{}{Recibes una gran cantidad de radiación.}
{1004}{}{Has sido levemente irradiado.}
{1005}{}{Has sido moderadamente irradiado.}
{1006}{}{Has sido fuertemente irradiado.}
{1007}{}{¡Has sido irradiado!}
{1008}{}{Has recibido una leve cantidad de radiación.}
{1009}{}{Has recibido una pequeña cantidad de radiación.}
{1010}{}{Has recibido una moderada cantidad de radiación.}
{1011}{}{Has recibido una gran cantidad de radiación.}
{1153}{}{Tu Fuerza se ha reducido en }
{1154}{}{Tu Percepción se ha reducido en }
{1155}{}{Tu Resistencia se ha reducido en }
{1156}{}{Tu Carisma se ha reducido en }
{1157}{}{Tu Inteligencia se ha reducido en }
{1158}{}{Tu Agilidad se ha reducido en }
{1159}{}{Tu Suerte se ha reducido en }
{1160}{}{ puntos.}
{1161}{}{ puntos.}
{1170}{}{Tu intento de empuñar un arma humana ha fallado; el arma es destruida.}
{1171}{}{Sus grandes manos son demasiado torpes para empuñar el arma humana, y cae a sus pies.}
{1180}{}{Has matado a mucha gente inocente. ¡Ahora eres un Berserker! Por lo general no es algo muy bueno por lo que ser conocido, y claramente eres una muy mala persona.}
{1181}{}{Ya no eres un Berserker.}
