{100}{}{¡Para!}
{101}{}{¡Muere, humano!}
{102}{}{A la muerte.}
{103}{}{¡Pagarás por tus pecados!}
{104}{}{¡Acabaré contigo!}
{105}{}{¡Unidad para siempre!}
{106}{}{¡Por el Maestro!}
{107}{}{Se supone que no puedes ir armado en esta zona, hermanito. Explícate.}
{108}{}{Se supone que no puedes ir armada en esta zona, hermanita. Explícate.}
{109}{}{Hngg.}
{110}{}{Está bien, trabajo aquí.}
{111}{}{Está bien, tengo un pase.}
{112}{}{Tengo permiso del Teniente para llevar armas.}
{113}{}{¡¿Qué clase de traición es ésta?!}
{114}{}{Entonces muéstrame tu pase.}
{115}{}{Me lo dejé en el otro traje.}
{116}{}{Está justo aquí, enganchado al cañón de la pistola.}
{117}{}{Date prisa con tus tareas pero recuerda que te estoy vigilando.}
{118}{}{Sí, hermanito. ¿Qué puedo hacer por ti?}
{119}{}{Sí, hermanita. ¿Qué puedo hacer por ti?}
{120}{}{¡Unm!}
{121}{}{Hmm, ¿dónde está el Maestro?}
{122}{}{Alabada sea la Unidad, hermano.}
{123}{}{No voy a ser yo quien te conduzca a la Unidad. ¡Vete!}
{124}{}{¡Obviamente eres una hereje! ¡Paga por tus pecados!}
{125}{}{Aquí significa aquí. ¿Por qué lo preguntas?}
{126}{}{Oh, oh, por nada.}
{127}{}{¡De la patada que le voy a dar, lo voy a mandar bien lejos!}
{128}{}{¿Qué pregunta? Dije "Viva el Maestro, adiós".}
{129}{}{¡Me estás ofendiendo! ¡Muere!}
{130}{}{Alabada sea la Unidad.}
{131}{}{Parece como si no te creyeras lo que estás diciendo. ¿Es eso cierto? ¿O es que te has alejado del camino de la rectitud?}
{132}{}{Te crees que el temblor de mi voz se debe al miedo, cuando solo tengo un catarro.}
{133}{}{De hecho, creo que tu raza está maldita. Déjame que te lo demuestre con la ayuda de algunos amigos...}
{134}{}{Cuando te conviertas en uno de los nuestros, no temerás esos detalles. Fuera de aquí.}
{135}{}{¿Qué quieres esta vez? Tengo poco tiempo para hablar contigo.}
{136}{}{¡Labbo!}
{137}{}{Te queda muy poco tiempo... ¡Muere!}
{138}{}{Nada, lo siento.}
{139}{}{Alabada sea la Unidad, hermano.}
{140}{}{¡Obviamente eres un intrusa!}
{141}{}{Fuera de mi vista.}
{142}{}{No tengo tiempo para ti. Deja de molestarme.}
{200}{}{Estás viendo a un Sargento Supermutante.}
{201}{}{Eh, esto parece una bomba nuclear. ¿Qué hace aquí?}
{202}{}{Este arma es el último recurso del Maestro. Si vamos perdiendo la batalla, entonces los liquidaremos con esto. Pero dudo mucho que ocurra. ¡Incluso nuestro Maestro no quiere volver a utilizar el poder de la bomba atómica!}
{203}{}{Vale, gracias.}
{204}{}{¿Funciona?}
{205}{}{De nada. Ahora, cállate. Necesito concentrarme para vigilar este dispositivo.}
{206}{}{Oh, sí que lo es. Lo mantenemos en perfectas condiciones para encenderla en cuanto recibamos la orden. ¡La Unidad nunca será vencida!}
{207}{}{Ah, gracias.}
{208}{}{¿No te preocupa que alguien robe tus trajes o se cuele aquí para explosionarlo?}
{209}{}{No. Estamos aquí para protegerlo de intrusos. Nadie puede tener acceso al dispositivo sin que nos demos cuenta. Además, la llave del armamento nuclear necesaria para armar el dispositivo, no está aquí.}
{210}{}{Oh, eso parece sensato. Gracias.}
{211}{}{Bueno, por mi tranquilidad de pensamiento, ¿puedes decirme dónde está la llave?}
{212}{}{Oh, claro, no hay problema. El Lugarteniente tiene la llave. Está en la Base Militar, así que no está por aquí. Así, la bomba nuclear está bastante apartada y, si explota, no le hará daño a nuestro amado Maestro.}
{213}{}{Gracias por tu tiempo.}
{214}{}{(El mutante grande te mira un momento con las cejas levantadas.) Creo que estás haciendo demasiadas preguntas.}
