{100}{}{Ofrecemos la curación del cuerpo para sanar el espíritu. ¿Puedo ayudarte?}
{101}{}{Sí, ayúdame.}
{102}{}{¿Quién eres?}
{103}{}{¿Qué le pasó a la gente que estaba aquí antes?}
{104}{}{Ehh...}
{105}{}{Está bien, niña mía. Te examinaremos ahora.}
{106}{}{Benditos sean los bondadosos. No te pasa nada hijo mío. Corre, vete a jugar.}
{107}{}{Te has curado. Ten más cuidado en el futuro.}
{108}{}{Tienes lesiones.}
{109}{}{Parece que te han envenenado.}
{110}{}{Mmm, lesiones por exposición a la radiación. No podemos curarlas.}
{111}{}{Necesitamos una donación de 5 chapas }
{112}{}{ antes de poder curarte. ¿Te parece razonable?}
{113}{}{Sí.}
{114}{}{No.}
{115}{}{¡Pero no tengo esas chapas!}
{116}{}{¿Aceptarás }
{117}{}{ chapas?}
{118}{}{Los Niños no regatean. Entonces, ¿aceptarás nuestro precio ahora?}
{119}{}{Sí. Por supuesto que lo haré.}
{120}{}{¡Eso es así!}
{121}{}{Gracias, hijo mío. Rezaremos por tu curación.}
{122}{}{Gracias, hija mía. Rezaremos por tu curación.}
{123}{}{Eso es. Que la paz y la bendición de los Niños estén contigo.}
{124}{}{No tienes suficientes chapas. Si das todo lo que puedas te sanaremos. ¿Te parece bien?}
{125}{}{Sí.}
{126}{}{No.}
{127}{}{Si das todo lo que puedas, te sanaremos. ¿Te parece bien?}
{128}{}{Sí.}
{129}{}{No.}
{130}{}{Tienes más que suficiente para hacer la donación. Necesitas estudiar matemáticas, niña mía.}
{131}{}{Somos los Niños de la Catedral. Vivimos y trabajamos entre aquellos desgraciados que viven en el yermo. Si alguna vez vas al Cementerio de LA, párate en la Catedral.}
{132}{}{Gracias.}
{133}{}{¿Qué haces?}
{134}{}{Somos mensajeros de paz. Sanamos el cuerpo para purificar el espíritu. Solo pedimos una pequeña donación para nuestros materiales de curación.}
{135}{}{A mí me parece una buena idea.}
{136}{}{No me parece bien.}
{137}{}{No te hemos preguntado. Seguro que te has cansado de escuchar nuestras creencias. Si necesitas algo más, estaremos aquí.}
{138}{}{Es nuestra idea más sagrada. Nos esforzamos en establecer una paz absoluta en el yermo. Todas las criaturas serán una.}
{139}{}{Gracias. Adiós.}
{140}{}{Ellos nos donaron esta casa para que extendiésemos nuestras creencias y llevásemos a cabo nuestro deber como curanderos.}
{141}{}{¿Y Doc Mórbid no está preocupado por eso?}
{142}{}{Aquello fue un gran detalle por su parte. Gracias.}
{143}{}{Sienta lo que sienta ese corazón pagano, eso no es asunto de los Niños. Estamos aquí para cumplir nuestro deber, y así se hará.}
{144}{}{Uh, sí, gracias. Adiós.}
{145}{}{¿Por qué haces eso? ¡No te haremos daño!}
{146}{}{No necesitas nuestra ayuda.}
