{100}{}{No ves ningún panel de control en este emisor.}
{101}{}{Desactivas temporalmente el campo de fuerza, con el consiguiente daño para el emisor.}
{102}{}{Destruyes completamente el emisor de campo de fuerza y el campo de fuerza desaparece.}
{103}{}{Desactivas temporalmente el emisor de campo de fuerza.}
{104}{}{No puedes hacer nada con el emisor de campo de fuerza.}
{105}{}{Activas el emisor de campo de fuerza.}
{150}{}{Tu intento de recablear el emisor de campo falla.}
{151}{}{Apagas el emisor de campo.}
{200}{}{Estás viendo un emisor de campo muy dañado.}
{201}{}{El emisor está demasiado dañado para utilizarse.}
{202}{}{El emisor está demasiado dañado para repararse.}
{203}{}{Te das cuenta de que el campo está demasiado dañado para funcionar.}
{204}{}{Un explosivo bien colocado podría desbaratar por completo el emisor.}
{205}{}{No ves ninguna forma de unir el explosivo al emisor. Tendrás que colocarlo cerca del emisor.}
