{100}{}{Ves a un conductor de caravanas.}
{101}{}{¡Hoy va a ser un día largo!}
{102}{}{En realidad no quiero trabajar hoy.}
{103}{}{Espero que no nos asalten... o algo peor.}
{104}{}{Lo siento, no necesitamos más guardias, creo.}
{105}{}{Lo siento, estamos al completo.}
{106}{}{Deberías mirar en el Mercado de Mercaderes si buscas un trabajo.}
{107}{}{Espero que vendamos todo.}
{108}{}{No puedo esperar a que acabemos.}
{109}{}{Tomemos la carretera.}
{110}{}{Estoy listo para liquidar al que sea.}
{111}{}{¡Nos vamos de aquí!}
{112}{}{Hoy sí que fue un día caluroso.}
{113}{}{Oye, tengo sed.}
{114}{}{¿Qué día es hoy?}
{115}{}{¡Me marcho al Halcón en cuanto esté listo!}
{116}{}{Lo siento, acabamos de volver de una ruta.}
{117}{}{Deberías mirar en el Mercado de Mercaderes si buscas un trabajo.}
{118}{}{¡Hoy es día de pago!}
{119}{}{¡Me dirijo al chiringuito de Bob!}
{120}{}{¡Tengo que devolver el préstamo hoy!}
{121}{}{Estoy tan cansado.}
{122}{}{¡Menudo viajecito!}
{123}{}{Ya ha llegado la noche, supongo.}
{124}{}{Os veo mañana, amigos.}
{125}{}{Jo, colega, vaya noche.}
{126}{}{Me estoy haciendo viejo.}
{200}{}{Ves: a Mat.}
{201}{}{Os veré mañana, chicos. No dejéis que el perro os muerda...}
{202}{}{Ha sido un sueño extraño.}
{203}{}{¿Sí? ¿En qué puedo ayudarte?}
{204}{}{¿Uh?}
{205}{}{¿Qué lugar es éste?}
{206}{}{¿Podrías decirme dónde puedo encontrar un Chip de Agua?}
{207}{}{¿Qué hacen esos carros ahí?}
{208}{}{Oh. Perdóname. Creía que eras otra persona. Adiós.}
{209}{}{Sí. Podrías morir.}
{210}{}{Demasiado tiempo en el desierto, ¿eh? Qué lástima.}
{211}{}{Esto es el Eje. Es el centro comercial del desierto. Es la ciudad más grande que conozco, aquí puedes encontrar todo lo que quieras. Y si estás buscando trabajo, éste es el lugar idóneo. Es como si todo el mundo aquí quisiera contratarte para algo, sea legal o no.}
{212}{}{¿Podrías decirme dónde puedo encontrar un Chip de Agua?}
{213}{}{¿Qué hacen aquí todos estos carros?}
{214}{}{¿Comercio? ¿Qué es lo que comercias?}
{215}{}{¿Dónde puedo encontrar trabajo?}
{216}{}{Adiós.}
{217}{}{¿Un Chip de Agua? Guau. No tengo ni idea. Nunca he oído hablar de eso. Quizás debas preguntar en el almacén general del centro; allí puede que te ayuden.}
{218}{}{¿Qué hacen aquí todos estos carros?}
{219}{}{Gracias. Adiós.}
{220}{}{Son caravanas. Llevamos productos a prácticamente todos los rincones del desierto. A Ciudad Vertedero, a la Hermandad, a Arenas Sombrías y a muchos otros lugares. Necrópolis y el Ardor son los únicos dos sitios a los que no vamos. Dirijo a este grupo y ya partimos. El grupo de enfrente acaba de llegar.}
{221}{}{Es la misma caravana que he visto antes...}
{222}{}{¿Qué es lo que comercias?}
{223}{}{¿Qué lugar es éste?}
{224}{}{¿Dónde puedo encontrar trabajo?}
{225}{}{Gracias. Adiós.}
{226}{}{Umm... mucho material. Materias primas que la gente necesita. Comida, agua, mucha agua. El agua es probablemente el producto más apreciado en el desierto.}
{227}{}{¿Podrías decirme dónde puedo encontrar un Chip de Agua?}
{228}{}{¿Dónde puedo encontrar trabajo?}
{229}{}{Gracias. Adiós.}
{230}{}{Puedes preguntarle a cualquiera aquí en el Eje. O puedes mirar en un boletín de ofertas de empleo. Hay unos cuantos en el Eje. Una cosa está clara, hay más trabajo que gente.}
{231}{}{¿Qué lugar es éste?}
{232}{}{¿Podrías decirme dónde puedo encontrar un Chip de Agua?}
{233}{}{¿Qué hacen aquí todos estos carros?}
{234}{}{Gracias. Adiós.}
{235}{}{¡Ja, ja! Sí, supongo que tienes razón. Cuando pasa el tiempo todo parece igual. Pero créeme, no todo es igual.}
{236}{}{¡¡¡Morirás por reírte de mí!!!}
{237}{}{¿Dónde puedo encontrar trabajo?}
{238}{}{Adiós.}
{300}{}{Ves: a Luke.}
{301}{}{Son caravanas. Llevamos productos a prácticamente todos los rincones del desierto. A Ciudad Vertedero, a la Hermandad, a Arenas Sombrías y a muchos otros lugares. Acabamos de llegar y ha sido un duro viaje. El grupo de enfrente se está preparando para partir.}
{400}{}{Ves: a John.}
{401}{}{¿Qué haces aquí a estas horas?}
{402}{}{Eres idiota. Vete de aquí.}
{403}{}{¿Un Chip de Agua? No sé de qué me hablas.}
{404}{}{Son las caravanas que estoy vigilando. Llevan productos a prácticamente todos los rincones del desierto. A Ciudad Vertedero, a la Hermandad, a Arenas Sombrías y a muchos otros lugares.}
{405}{}{Umm... mucho material. Materias primas que la gente necesita. Comida, agua, mucha agua. El agua es probablemente el producto más apreciado en el desierto.}
{406}{}{Puedes preguntarle a cualquiera aquí en el Eje. O puedes mirar en un boletín de ofertas de empleo. Hay unos cuantos en el Eje.}
{407}{}{Soy un guardia de seguridad contratado por los mercaderes dueños de las cosas que hay en los carros. Es un trabajo peligroso, pero se paga bien. La otra noche asesinaron a uno de mis colaboradores mientras vigilaba las caravanas.}
{408}{}{¿Qué son las caravanas?}
{409}{}{Ahhhh. (Con un tono sarcástico) Vaya historia más triste. ¿Te gustaría acompañar a tu amigo?}
{410}{}{Adiós.}
{501}{}{Estás viendo a un guardia de las caravanas.}
{502}{}{Ves a un conductor de caravanas.}
{503}{}{Ves a un conductor de caravanas.}
{504}{}{Estás viendo a un mercader de caravanas.}
