{100}{}{Estás viendo a un Oficial de Policía.}
{101}{}{¡Saludos! Deberías tener cui... uh, quiero decir, vigila... (mira de forma extraña a los otros oficiales y apunta en tu dirección con la cabeza).}
{102}{}{Hola, forastero... ¡Espera! ¡Te conozco! ¡Te buscan por robo! ¡No te muevas!}
{103}{}{Vale, me voy.}
{104}{}{¡Vas a probar mi plomo!}
{105}{}{¡Kor Rok!}
{106}{}{(Poner las manos en el aire y entregarse)}
{107}{}{Ten cuidado, éste no es un lugar seguro.}
{108}{}{Vigila tus chapas, }
{109}{}{señor.}
{110}{}{señora.}
{111}{}{No deberías estar aquí, no es seguro.}
{112}{}{La Ciudad Antigua ha degenerado.}
{113}{}{Este lugar apesta.}
{114}{}{Debería acabar con toda esta zona.}
{115}{}{Estoy seguro de que ese maldito Gremio de Ladrones está por aquí.}
{116}{}{Pobre Harold, ha tenido una vida dura.}
{117}{}{No te metas en líos.}
{118}{}{Eh. Te conozco. Nada de peleas, ¿vale?}
{119}{}{¡Ni pienses en empezar otra pelea!}
{120}{}{Si te cogemos peleando de nuevo, ¡te la vas a cargar!}
{121}{}{¿Te has enterado? Los Comerciantes de Ultramar han sido eliminados.}
{122}{}{Los Mercaderes de Agua ya son historia. Es una bendición.}
{123}{}{Alguien ha liquidado a los de la Caravana Carmesí.}
{124}{}{¡¿Te has enterado?! ¡Los Clandestinos por fin han sido eliminados!}
{125}{}{¡Decker ha muerto!}
{126}{}{Esta ciudad sería más segura con Decker fuera del mapa.}
