{100}{}{¿Crees que eso te salvará de Baka?}
{101}{}{No es un partido para nosotros!}
{102}{}{Si fuera tan feo, me suicidaría.}
{103}{}{Usted Criptas no tienen una oportunidad.}
{104}{}{¿Te gusta el dolor?}
{105}{}{Voy a disfrutar con esto. }
{106}{}{Usted morirá escoria!}
{107}{}{Es tiempo de pagar las deudas.}
{108}{}{¿Estás listo para un poco de dolor?}
{109}{}{La única cosa más estúpido de lo que es Rayze.}
{110}{}{Supongo que la placenta puede vivir un poco de tiempo.}
{111}{}{Las Criptas será enterrado una vez más!}
{112}{}{Pierda, escoria!}
{113}{}{¿Quién dijo que podría salir de sus tumbas? Retorno!}
{114}{}{Tu humilde caminos, será erradicada de la faz de la tierra!}
{115}{}{Sólo los Tontos tienen el verdadero conocimiento de la regla Chatarra.}
{116}{}{Begone intestino limo de tres patas de pollo!}
{117}{}{¿Qué te pasó? ¿Tu madre te dejó caer de cabeza al nacer?}
{118}{}{}
{119}{}{}
{120}{}{}
{200}{}{Locos, corred mientras podáis.}
{201}{}{Hey, Rayze, la caza de temporada que acaba de abrir, y los Tontos están en la lista de los animales mudos.}
{202}{}{Eh, colegas. Dejadme que me cargue al Loco.}
{203}{}{Las Criptas va a enterrar a usted!}
{204}{}{Los tontos no tienes una razón para vivir.}
{205}{}{El Tonto perecerá.}
{206}{}{Mira quien fue golpeado con el feo palo.}
{207}{}{¡Te vamos a enterrar, Loco!}
{208}{}{¡Voy a patear unos cuantos culos! ¡Estoy preparadooooo!}
{209}{}{¡Los Enterradores mandan! ¡Y los Locos la maman!}
{210}{}{¡Traemos muerte!}
{211}{}{No se preocupe, que va a ser rápido y doloroso!}
{212}{}{PÚRPURA BABUINOS!}
{213}{}{El Brahmán tiene más sentido que un Tonto.}
{214}{}{Los Tontos son tan débiles, incluso Lex puede vencer a todos ellos.}
{215}{}{Jaja! Más tontos a matar!!}
{216}{}{La única cosa que los Tontos de la regla es de una lápida.}
{217}{}{Es cuestión de tiempo. He estado esperando por esto.}
{218}{}{Incluso Lenny tiene mejor objetivo que usted.}
{219}{}{Comer plomo tontos.}
{220}{}{Voy a montar su cabeza en un pico.}
{300}{}{Hey! El generador está roto. Vamos a salir de este basurero.}
{400}{}{Con el generador roto, no hay motivo para que las bandas se pelean por Chatarra. Su trabajo aquí está hecho, pero su misión para encontrar a la purificación de agua chip continúa.}
{402}{}{Con las pandillas y el derrotado, sin perspectivas de futuro es un refugio seguro, una vez más.}
