{100}{}{Ver Lenny.}
{101}{}{Usted ve un perdedor que huele a un Brahmán.}
{102}{}{[más]}
{103}{}{[Hecho]}
{104}{}{Herido a uno de mis amigos! Vamos a hacer que usted paga por eso! Get 'em, chicas!}
{105}{}{Oh, hola.}
{106}{}{¿Qué estás haciendo aquí?}
{107}{}{¿Cuáles son estos animales?}
{108}{}{¿Cómo es que estos animales apestar tanto?}
{109}{}{Que hacer? Yo no había notado. Supongo que me he estado dando vueltas por mucho tiempo, no me molesta. Ellos son mis amigos.}
{110}{}{Estos son Brahmán. Ellos son mis amigos. Puedo dormir en la pluma con ellos para que no se asustan en la noche. Este lugar puede ser un poco de miedo, si usted sabe a qué me refiero.}
{111}{}{No sé a qué te refieres. ¿Por qué es este lugar da miedo?}
{112}{}{Puedo comprar uno?}
{113}{}{NO! No! Yo no soy un esclavista, como algunas de estas personas. ¿Cómo podría usted vender tus amigos!?}
{114}{}{No me refiero a que, son sólo animales.}
{115}{}{Yo no haría eso, yo sólo era una prueba.}
{116}{}{Fácil, puedo hacer más dinero de esa forma.}
{117}{}{Oh, entiendo. No te das cuenta de lo importante de los Brahmanes son para mí. Eso está bien. Creo que la gente no me entiende.}
{118}{}{Uh, adiós.}
{119}{}{Eres malo. Te odio.}
{120}{}{Lo que sea.}
{121}{}{Oh. Oh, lo siento. Hey, estás un poco agradable. Me gusta usted. Debo advertir acerca de Engañar a los chicos. No me gusta. No les gusta a nadie.}
{122}{}{Gracias por la información.}
{123}{}{La gente mala. Que luchar por las cosas. Cosas que no entiendo. Los peores son los Tontos. Se burla de mí. No me gusta. [oler] no me gustan.}
{124}{}{Oh, es usted de nuevo.}
{125}{}{Dime lo que sabes acerca de los Necios.}
{126}{}{Dime qué sabes acerca de las Criptas.}
{127}{}{Quiero saber sobre el generador de energía.}
{128}{}{Nos vemos.}
{129}{}{No me gustan los Tontos, siempre están recogiendo en mí. Ellos viven en el garaje del norte. Luchan contra las Criptas, pero todos perdemos.}
{130}{}{Gracias.}
{131}{}{Las Criptas son realmente significa. Ellos sostienen que el 'lectricity y si estamos mal, ellos lo toman lejos de nosotros. Odian a los Tontos, peor que cualquier otra. Peor que odian a mis amigos.}
{132}{}{¿Cuál es la 'lectricity?}
{133}{}{El gen de la'rator? Oh, yo no sé acerca de eso.}
{134}{}{Se alimenta de las luces. Hace que todas las cosas ir. No sé, pero si no la tenemos, no es bueno.}
{135}{}{No voy a hablar con usted.}
{136}{}{Voy a pasar tiempo con mis amigos. Yo paso mucho tiempo con ellos. Son bonitos. Que no me trates mal. No se como algunas personas. [Lenny entrecierra los ojos sus ojos.] Odio a algunas personas. Yo odio a los Tontos.}
{137}{}{Me das miedo.}
{138}{}{Que estaba muy bien, pero no has contestado a mi pregunta.}
{139}{}{Oh, lo siento. Lex dice que asustar a él, también. No me refiero a que. Y yo nunca asustar a mi amigo.}
{140}{}{¿Cuáles son tus amigos?}
{141}{}{Que es Lex?}
{142}{}{Oh, puedo ver el Brahmán y asegúrese de que no les pasa nada.}
{143}{}{Ahora, eso no fue tan difícil, ¿a que no? ¿Cuáles son tus amigos?}
{144}{}{Lex es agradable. Lex trata a mis amigos como en familia. Aproximadamente una vez al mes, que incluso lleva a uno de mis amigos a casa para la cena. [Lenny sonrisas.] Entonces él les permite jugar con un montón de cielo Brahmán. ¿No es eso bueno?}
{145}{}{Sí, Lenny, es muy agradable. Ahora háblame de tus amigos.}
{146}{}{Lenny, creo que usted necesita saber algo. Lex se come a sus amigos.}
{147}{}{No, mentira! Eres un mentiroso! Lex nunca haría eso! Usted apestoso mentiroso! Voy a hacerte daño por decir eso delante de mis amigos.}
