{100}{}{Este ordenador contiene una gran cantidad de información relativa a la época anterior a la Gran Guerra.}
{101}{}{Usas el sistema didáctico del ordenador del Refugio.}
{102}{}{Pasas 1 hora consultando el sistema didáctico del ordenador del Refugio pero no descubres nada interesante. Ahora el mundo exterior es tu maestro.}
{103}{}{Pasas 6 horas buscando cualquier tipo de información que pueda resultar importante. Sientes haber ganado un gran conocimiento que te ayudará en tus viajes fuera del Refugio.}
{104}{}{Pasas 6 horas en la red interna sin hacer nada importante.}
{105}{}{You fiddle with the computer a bit, but it will take some scientific skill to actually get anything useful out of it.}
{106}{}{Pasas }
{107}{}{ horas consultando el sistema didáctico del ordenador del Refugio pero no descubres nada interesante. Ahora el mundo exterior es tu maestro.}
{108}{}{ horas en la red interna sin hacer nada importante. Ha sido divertido pero te deja con un sentimiento de vacío.}
{109}{}{ horas en la red interna buscando pornografía y vídeos de gatos.}
