{100}{}{Esto es una cabeza nuclear activa.}
{101}{}{Unos cables conectan el ordenador de acceso a la cabeza nuclear que está detrás de él.}
{102}{}{Has activado la cabeza. Un temporizador que muestra 4:00 minutos ha comenzado la cuenta atrás.}
{103}{}{Has desactivado la cabeza nuclear.}
{104}{}{¡BUUUUUUUUM! [¡Has hecho estallar la bomba!]}
{105}{}{No funciona al parecer.}
{106}{}{La cuenta atrás continúa... puede que debas cortar ese cable rojo.}
{107}{}{Puede que también debas usar la llave.}
{108}{}{Esto es una cabeza nuclear. Está controlada por el ordenador conectado por los cables.}
{109}{}{No hay nada en esta cabeza nuclear que necesite una reparación.}
{110}{}{No hay nada en esta cabeza nuclear que necesite el uso de una ganzúa.}
{111}{}{Esto es una trampa grande que no puede ser montada o desmontada desde aquí.}
