{100}{}{Ves a un campesino.}
{101}{}{Gracias por deshacerse de las bandas, pero sin el generador, vamos a tener una peor vida.}
{102}{}{Tengo frío.}
{103}{}{Quiero algunas luces.}
{104}{}{Debemos agradecer a usted, creo.}
{105}{}{Si usted no matar a todas las bandas, van a tomar su venganza sobre nosotros!}
{106}{}{Usted comenzó este baño de sangre, termine.}
{107}{}{Me gustaría ayudar, pero tengo este mal de la rodilla.}
{108}{}{Todo esto es tu culpa.}
{109}{}{La violencia no deja nada.}
{110}{}{Pensé que eras un buen tipo.}
{111}{}{Sólo otra Cripta. Supongo que se me haría daño ahora.}
{112}{}{No voy a causar problemas.}
{113}{}{Por favor, déjame tranquilo.}
{114}{}{He oído que se unió a los Tontos.}
{115}{}{Es un Tonto! Uy, no lo quise decir de esa manera.}
{116}{}{No me causa ningún problema.}
{117}{}{Por favor, déjame tranquilo.}
{118}{}{Me comprometo a reírse de sus chistes.}
{119}{}{Tengo hambre.}
{120}{}{Donde tienen toda la buena gente ido?}
{121}{}{Es Phil sigue teniendo problemas con el perro?}
{122}{}{Sin perspectivas de futuro va a soplar en el viento del desierto, si esas bandas tienen su manera.}
{123}{}{Hace frío por la noche, sin que los calentadores.}
{124}{}{Los Brahmanes seguro que no se pudrió durante el verano.}
{125}{}{La electricidad, la electricidad.}
{126}{}{Hola.}
{127}{}{[Hecho]}
