{100}{}{Ves: a Cindy. Está llorando.}
{101}{}{Ves: a Lisa. Está llorando.}
{102}{}{Ves: a Sandy. Está llorando.}
{103}{}{Ves: a Mary. Está llorando.}
{104}{}{Ves: a Stacy. Está llorando.}
{105}{}{Ves: a Susan. Está llorando.}
{106}{}{Ves: a Cindy.}
{107}{}{Ves: a Lisa.}
{108}{}{Ves: a Sandy.}
{109}{}{Ves: a Mary.}
{110}{}{Ves: a Stacy.}
{111}{}{Ves: a Susan.}
{112}{}{Hola, }
{113}{}{. ¿Ya has encontrado el Chip de Agua?}
{114}{}{No, aún no.}
{115}{}{Lo encontraré. ¿Cómo te va?}
{116}{}{¡Ahh!}
{117}{}{Oh... no me entiendes. Supongo que después de todo no nos quedan muchas esperanzas. Perdóname si lloro.}
{118}{}{¡Ug!}
{119}{}{Por favor, encuéntralo antes de que mi bebé muera de sed.}
{120}{}{[Hecho]}
{121}{}{¡Tienes que encontrarlo! ¡No dejes que nos muramos de sed!}
{122}{}{[Hecho]}
{123}{}{Sigue intentándolo. Confío en ti. Sé que harás todo lo posible para salvarnos.}
{124}{}{[Hecho]}
{125}{}{Lamento lo que está ocurriendo. Alguien ha estado robando agua y ahora todos estamos al límite.}
{126}{}{¿Quién podría hacer algo así?}
{127}{}{¿Qué pasó?}
{128}{}{Algunos han sido acusados y empieza a haber peleas, pero nadie sabe lo que pasa realmente.}
{129}{}{De acuerdo. Gracias.}
{130}{}{Algunos dijeron que les habían robado el agua. No se les dio más agua, pero algunos amigos la compartieron con ellos. Después de eso la gente se volvió paranoica y empezó a guardar el agua. Unos días después alguien dejó inconsciente al guardia en la zona de racionamiento del suministro y robó agua.}
{131}{}{¡Eso es terrible! ¿Qué puedo hacer?}
{132}{}{Quizás puedas frenar a quien está haciendo eso.}
{133}{}{Echaré un vistazo.}
{134}{}{Adiós.}
