{101}{}{Estás viendo extrañas criaturas flotantes...}
{102}{}{¡De pronto un grupo de mantis mutadas te ataca!}
{103}{}{¡De pronto un grupo de mantis mutadas te ataca!}
{104}{}{¡Estás viendo cómo los saqueadores atacan a un grupo de campesinos!}
{105}{}{¡Un grupo de ratas se acerca rápidamente!}
{106}{}{Estás viendo a unas personas pescando.}
{107}{}{Cerca de ti, ves un cadáver asqueroso parcialmente devorado. Acabas de perder el apetito.}
{200}{}{Tropiezas con unos charcos de agua.}
{201}{}{Muerto de sed, bebes un poco de agua... no sabe nada bien.}
{202}{}{El agua parece muy radioactiva y sucia.}
{203}{}{Ahhh...}
{204}{}{Arrgg...}
{205}{}{¡Puaj!}
{1000}{}{Ganas }
{1001}{}{ puntos de experiencia por utilizar tu habilidad de Supervivencia con éxito.}
{1002}{}{Encounter: "}
{1003}{}{"}
{1004}{}{. ¿Quieres parar al encuentro?}
{1005}{}{Sí.}
{1006}{}{No.}
{1007}{}{}
{1008}{}{}
{1009}{}{}
{1010}{}{Ustedes son emboscados por una sed de sangre cazador y su goon squad!}
