{100}{}{Tal y como están las cosas, no pueden haber ido muy lejos. Deben tener una guarida por aquí cerca.}
{101}{}{Parece que han viajado hasta aquí desde un lugar cercano.}
{102}{}{Por lo visto, venían de un lugar muy al norte de aquí.}
{103}{}{Aparentemente, solo estaban merodeando por el yermo.}
{104}{}{Has llegado en plena batalla entre escorpiones rad y ratas topo.}
{105}{}{¡¡¡EMBOSCADA!!!}
{106}{}{¡Has tropezado con una gran manada de escorpiones rad!}
{107}{}{Has tropezado con una manada de escorpiones rad.}
{108}{}{Has tropezado con una familia de ratas topo.}
{109}{}{Has evitado un gravísimo caso de deshidratación al buscar agua. La búsqueda te lleva una hora más.}
{110}{}{Has evitado un gravísimo caso de deshidratación al buscar agua. La búsqueda te lleva }
{111}{}{ horas.}
{112}{}{Consigues evitar la deshidratación gracias a tus reservas de líquidos, vaciando }
{113}{}{ puntos de salud.}
{114}{}{Tus reservas de agua se acaban, }
{115}{}{ horas no consigues encontrar nada de agua. Te has deshidratado, y pierdes }
{116}{}{ petaca de agua}
{117}{}{ petacas de agua}
{118}{}{tu petaca}
{119}{}{ petaca.}
{120}{}{Buscas agua por el alto desierto durante }
{121}{}{ horas, pero no encuentras bastante para satisfacer tu sed. Sufres 1 punto de daño de salud.}
{122}{}{Buscas agua por el alto desierto durante }
{123}{}{ horas, pero no encuentras bastante para satisfacer tu sed. Sufres }
{124}{}{ petacas.}
{125}{}{Consigues evitar la deshidratación gracias a tus reservas de agua, vaciando }
{126}{}{Te has topado con unos escorpiones rad que cazan ratas topo.}
{127}{}{Se acercan humanoides flacos con aspecto hostil y piel verdusca.}
{128}{}{El suelo está cubierto de trastos y de rocas. Te preguntas si puede quedar algo de valor...}
{129}{}{¡Un escorpión rad te ha tendido una emboscada!}
{130}{}{Aquí ves un cadáver medio devorado.}
{131}{}{¡¡¡ESTAMPIDA!!!}
{132}{}{¡Te has tropezado con una gran manada de escorpiones rad!}
{133}{}{¡Unos saqueadores te tienden una emboscada!}
{134}{}{¡Una manada de escorpiones rad peligrosos surge del desierto!}
{135}{}{Encuentras un grupo de centinelas patrullando.}
{136}{}{Te cruzas con un mercader con varios guardias.}
{137}{}{Ves a un campesino cuidando de varios brahmines.}
{138}{}{ Llenas }
{139}{}{Escorpiones rad cazan ratas topo junto a las ruinas de una ciudad.}
{140}{}{ Nuka-Colas}
{141}{}{ Nuka-Cola}
{142}{}{ cerveza}
{143}{}{¡¡¡Saqueadores!!!}
{144}{}{Has tropezado con un gran grupo de ratas topo.}
{145}{}{Te encuentras con un grupo de escorpiones rad salvajes.}
{146}{}{Te encuentras con unos campesinos que están siendo atacados.}
{147}{}{Consigues evitar la deshidratación por haber buscado agua. La búsqueda  te lleva 1 hora.}
{148}{}{ punto de salud.}
{149}{}{ cervezas}
{150}{}{ botella de alcohol}
{151}{}{ botellas de alcohol}
{152}{}{Al recurrir al alcohol, tu }
{153}{}{Fuerza se reduce}
{154}{}{Resistencia se reduce}
{155}{}{Fuerza y Resistencia se reducen}
{156}{}{ en 1 punto.}
{157}{}{ en 2 puntos.}
{158}{}{ en 1 punto cada una.}
{159}{}{tus petacas}
{160}{}{ con agua potable.}
{161}{}{Tus reservas de líquidos se acaban, }
{162}{}{y en tu búsqueda  de }
{163}{}{pero consigues evitar la deshidratación al haber estado buscando agua. La búsqueda  te lleva }
{164}{}{1 hora.}
{165}{}{Ganas }
{166}{}{ puntos de experiencia por utilizar tu habilidad de Supervivencia con éxito.}
{167}{}{}
{168}{}{}
{169}{}{Tropiezas con una familia de escorpiones rad.}
{170}{}{Te cruzas con un mercader que viaja con unos guardias.}
{171}{}{Encuentras un viajero muerto.}
{172}{}{Te encuentras objetos tirados por el suelo.}
{173}{}{Divisas los restos de una caravana atacada por saqueadores.}
{174}{}{Te cruzas con los restos de un mercader y sus guardias.}
{175}{}{Te encuentras con un viajero.}
{176}{}{Has tropezado con un pequeño grupo de construcciones derruidas y abandonadas.}
{187}{}{}
{188}{}{}
{189}{}{}
{190}{}{}
{191}{}{}
{192}{}{}
{193}{}{}
{194}{}{}
{195}{}{}
{196}{}{¡Escorpiones rad, acercándose!}
{197}{}{¡Uh-oh... un grupo de saqueadores!}
{198}{}{A lo lejos ves a un saqueador solitario.}
{199}{}{Has dado con los restos de un campo de batalla. El suelo está cubierto de cuerpos.}
{200}{}{¡Escorpiones rad, acercándose!}
{201}{}{}
{202}{}{}
{203}{}{}
{204}{}{}
{205}{}{}
{206}{}{}
{207}{}{}
{208}{}{}
{209}{}{}
{210}{}{}
{211}{}{}
{212}{}{}
{213}{}{}
{214}{}{}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}
{220}{}{}
{221}{}{}
{222}{}{}
{223}{}{Divisas una manada de coyotes salvajes merodeando.}
{224}{}{Ves a varios individuos explorando.}
{225}{}{Te encuentras con un grupo comerciantes y guardias.}
{226}{}{Asistes a una pequeña guerra... ¡hombres contra mutantes!}
{227}{}{¡Una horda de escorpiones rad se acerca de aquí!}
{228}{}{}
{229}{}{}
{230}{}{}
{231}{}{}
{232}{}{}
{233}{}{}
{234}{}{}
{235}{}{}
{236}{}{}
{237}{}{}
{238}{}{}
{239}{}{}
{240}{}{}
{241}{}{}
{242}{}{}
{243}{}{}
{244}{}{}
{245}{}{}
{246}{}{}
{247}{}{}
{248}{}{}
{249}{}{}
{250}{}{Se te acercan varios hombres con Armaduras de Energía.}
{251}{}{Ves un grupo de mercaderes y guardias.}
{252}{}{Asistes a una horrible batalla entre varios saqueadores del desierto y un grupo de hombres con Armaduras de Energía.}
{253}{}{Ves varios mutantes explorando una zona hostil.}
{254}{}{Divisas unas criaturas extrañas...}
{255}{}{Encuentras algunos objetos.}
{256}{}{¡Una patrulla de Supermutantes está pasando cerca!}
{257}{}{Divisas las ruinas de una aldea.}
{258}{}{}
{259}{}{}
{260}{}{}
{261}{}{}
{262}{}{}
{263}{}{}
{264}{}{}
{265}{}{}
{266}{}{}
{267}{}{}
{268}{}{}
{269}{}{}
{270}{}{}
{271}{}{}
{272}{}{}
{273}{}{}
{274}{}{}
{275}{}{}
{276}{}{}
{277}{}{}
{278}{}{}
{279}{}{Divisas chatarra diseminada sobre la arena.}
{280}{}{Tropiezas con un grupo de Supermutantes guerreros.}
{281}{}{Tropiezas con una manada de criaturas rarísimas.}
{282}{}{Tropiezas con una manada de escorpiones rad hambrientos.}
{283}{}{Sientes náuseas y te parece que el aire quema. ¡Una criatura mutante se te acerca de repente!}
{284}{}{Has tropezado con unas extraña criaturas mutantes.}
{285}{}{Has encontrado algo que parece salido de una vieja película de ciencia ficción.}
{286}{}{¡¡La Garra Mortal!!}
{287}{}{Tropiezas con una manada migratoria de escorpiones rad. Parecen estar huyendo de...}
{288}{}{Te encuentras una criatura mutada del desierto.}
{289}{}{}
{290}{}{}
{291}{}{}
{292}{}{}
{293}{}{}
{294}{}{}
{295}{}{}
{296}{}{}
{297}{}{}
{298}{}{}
{299}{}{A cierta distancia ves varios escorpiones rad.}
{300}{}{Te cruzas con un campesino harapiento.}
{301}{}{Encuentras una rata topo.}
{302}{}{Una Garra Mortal parece pensar que eres su almuerzo.}
{303}{}{Tropiezas con una manada migratoria de escorpiones rad.}
{304}{}{}
{305}{}{Te encuentras con lo que queda de los guardias hostiles del mercader Duc.}
{306}{}{Muy cerca de aquí patrulla una unidad de mutantes. ¡Acompañada por algunas criaturas extrañas!}
{307}{}{Una pequeña partida de guerra de Supermutantes te tiende una emboscada.}
{308}{}{¡Parece que has caído en plena guerra de bandas!}
{309}{}{¡Un grupo de bandidos hostiles aparece!}
{310}{}{¡Ataque de un pequeño grupo de saqueadores!}
{311}{}{¡Ataque de un pequeño grupo de bandidos!}
{312}{}{¡Las ratas te atacan repentinamente!}
{313}{}{¡De pronto un grupo de mantis mutadas te ataca!}
{314}{}{¡Eh! En serio, están ahí fuera.}
{315}{}{A lo lejos ves un camión volcado.}
{316}{}{Encuentras algunos coches desvencijados en medio del desierto.}
{317}{}{Divisas una cabina de policía al noreste.}
{318}{}{Te cruzas con una manada salvaje de brahmines. Sientes que algo no encaja...}
