{100}{}{Ves una cámara de seguridad que parece activa.}
{101}{}{Te das cuenta de que hay armas ocultas siguiendo tus movimientos.}
{102}{}{¡Abren fuego desde una tronera oculta! ¡Consigues evitar los impactos retorciéndote y esquivando!}
{103}{}{¡Abren fuego desde una tronera oculta! Intentas evadir los disparos mientras te retuerces, pero las balas te rozan.}
{104}{}{Sufres }
{105}{}{ de daño.}
{106}{}{¡Abren fuego desde una tronera oculta! Te sorprende, tropiezas y caes. Solo sufres daños leves.}
{107}{}{Sufres }
{108}{}{ de daño.}
{109}{}{¡Abren fuego desde una tronera oculta! ¡Te han dado!}
{110}{}{Sufres }
{111}{}{ de daño.}
