{100}{}{Esa destreza no tiene efecto aquí.}
{101}{}{Encuentras un tosco dispositivo explosivo conectado al baúl.}
{102}{}{¡Activas una trampa explosiva!}
{103}{}{Desactivas la trampa.}
{104}{}{No desactivaste la trampa.}
{105}{}{¡Activas accidentalmente el explosivo!}
{106}{}{Activas accidentalmente el explosivo, fuiste lo bastante inteligente como para encontrarlo, pero no lo suficiente como para dejarlo en paz.}
{107}{}{¡Uf!}
{108}{}{¡Aaagh!}
{109}{}{Ves: el baúl de Set.}
