{100}{}{Este ordenador purifica el agua del Refugio.}
{101}{}{El ordenador del agua no sirve para nada sin el chip que controla la purificación y este chip no se puede reparar. Necesitarás un repuesto.}
{102}{}{Jugueteas con el ordenador, pero en realidad no descubres nada más.}
{103}{}{Hay un montón de luces intermitentes en esta cosa.}
{104}{}{Con el chip de recambio, parece que el ordenador funciona bien.}
