{100}{}{Estás viendo a un perro. Parece que te está siguiendo.}
{101}{}{Estás viendo a un perro.}
{102}{}{¡Guau!}
{103}{}{¡Grrr!}
{104}{}{Parece que te has hecho amiga de este perro.}
{105}{}{Ganas 200 puntos de experiencia por hacerte amiga del perro.}
{106}{}{Ganas 335 puntos de experiencia por derrotar al perro y dejar que Phil vuelva a su casa.}
{107}{}{Ven aquí, chico.}
{108}{}{Ruff. Ruff.}
{109}{}{Por alguna razón le gustas al perro.}
{110}{}{Ves: a Albóndiga.}
{111}{}{¡Arf! ¡Arf! ¡Arf! ¡Arf! ¡Arf! ¡Arf! ¡Arf! ¡Arf! ¡Arf!}
{112}{}{[Snif. Snif.] ¡Grrrr! ¡Grrrr!}
{113}{}{[Snif. Snif.] ¡Guau!}
{114}{}{Ganas 100 puntos de experiencia por ayudar a Phil a solucionar su enigma canino.}
{115}{}{Parece que el perro cree que eres su dueña.}
{116}{}{Ganas 100 puntos de experiencia por ayudar a Phil a solucionar su enigma canino.}
{117}{}{¡Guau! ¡Guau! ¡Guau!}
{118}{}{No, nada. Adiós.}
{119}{}{Dogmeat, sit! Good boy. I'll be back soon.}
{120}{}{¡Vámonos!}
{121}{}{¡¡¡Cachorrito!!!}
{122}{}{¿Guau?}
{123}{}{¿Arf?}
{124}{}{¡Guau! ¡Guau! ¡Guau!}
{300}{}{¡¡Perrito!! ¿perrito ser amigo?}
{301}{}{¡perrito! ¡Quedar! ¡no mover!}
{302}{}{Muévete, amigito. Buen chico.}
{303}{}{}
{304}{}{¡Buen perrito!}
