{100}{}{Estás viendo un extraño disco de algún tipo.}
{101}{}{Pip-Boy 2000 muestra: "Descargando datos... Abortando, los datos ya existen."}
{102}{}{Pip-Boy 2000 muestra: "Descargando datos... ... ... completado. ¡Que tenga un buen día!".}
{103}{}{Este objeto es muy antiguo y parece tener una extraña insignia. Imaginas que debe ser lo que la Hermandad del Acero te envió a recuperar.}
{104}{}{Ves: Disco Antiguo de la Hermandad.}
{125}{}{Estás viendo un disco extraño procedente de la Base Militar.}
{126}{}{You see: Vault Locations Holodisk.}
{127}{}{Este holodisco en particular parece estar en excelentes condiciones. En la brillante etiqueta se lee: "Ubicación de Refugios v34.129".}
