{100}{}{Tù ves Baka.}
{101}{}{Estás viendo a una mujer.}
{102}{}{Criptas no deberìan estar aquì, ¿deberìan los chicos? (los otros tontos sacuden sus cabezas) Creo que deberìas irte. }
{103}{}{Cometí un error al unirme a las criptas. Quiero estar de tu lado. }
{104}{}{Vine con un mensaje de Phrax. }
{105}{}{Eso haré, gracias.}
{106}{}{¿Entonces deberíamos usar el abrigo de un traidor? ¿Uno que entregaría el suyo? Ningún perro es tan bajo como tú.}
{107}{}{Siento como si tu abrigo se volviera a poner, pero tus palabras me influyen.}
{108}{}{¿Phrax no es lo suficientemente valiente como para pronunciar este mensaje con su propia voz? Él no es hombre, de eso lo sé. Y envía a este chico a decir sus palabras. Bueno, entonces, diles y listo.}
{109}{}{Muere.}
{110}{}{Dijo que abandones la ciudad y que no te matarán.}
{111}{}{Dijo que tengas un buen dìa. }
{112}{}{Jajaja! Me gusta un hombre con sentido del humor. Puedes vivir. Perdòn, solo bromeaba. }
{113}{}{No creo que entiendas completamente las ramificaciones de lo que acabas de decir. Espero que los aprendas antes de que tus huesos se sequen en el sol del desierto. Lamentablemente, no creo que tengas mucho tiempo.}
{114}{}{¿Qué tenemos aquí? Escuchamos que alguien nuevo estaba en la ciudad. Este debes ser tú; todos los demás se ven tan familiares. Por favor permítame presentarme. Soy Baka, Reina de los locos. }
{115}{}{¿Por què se llaman los Tontos?}
{116}{}{Oigo que hay desacuerdos entre usted y las Criptas.}
{117}{}{Te ves como un tonto de mí.}
{118}{}{Después de la Guerra, sólo los Tontos se quedan. Si yo era lo suficientemente valiente, me hubiera llevado a mi propia vida años atrás. En su lugar, yo complacer a cualquier dioses de azar están a la izquierda.}
{119}{}{Comprensible. Clasifico de acuerdo con ella. Me puedo unir?}
{120}{}{Podríamos utilizar la otra mano. Déjenme pensar sobre esto. [Ella pone su mano a su mentón, y los desfiles alrededor de la habitación dramáticamente.]}
{121}{}{Tenga cuidado con las palabras que usted elija. No todos son tan indulgente como soy. Yo juego a la parte, o la parte que me toca, pero siempre hay espacio para otro cadáver para amenizar el drama.}
{122}{}{Yo no estaba seguro, era de que una amenaza?}
{123}{}{Voy a tratar de comportarse.}
{124}{}{Que era, ahora está entre las últimas palabras que jamás hayas escuchado.}
{125}{}{Bueno, a ver que hacen.}
{126}{}{¿Qué quieres ahora?}
{127}{}{Quiero unirme a su banda.}
{128}{}{¿Por qué desea que el generador de energía?}
{129}{}{No sé si debo confiar en ti. Demostrar su valía.}
{130}{}{Este pollo entra en un bar...}
{131}{}{Yo soy el mejor luchador de todo.}
{132}{}{Usted podría utilizar un buen hombre de por aquí.}
{133}{}{(Minutos pasan como termine su broma. Con una sonrisa nerviosa, reunirse con sus ojos. Ella se ríe.) Me gusta usted. Ha probado usted a entender la Broma. Ahora eres un Tonto. Nos engañará y morir.}
{134}{}{Eso ya lo veremos.}
{135}{}{Skippy? Su turno.}
{136}{}{Sólo hay una cosa que separa el Cementerio de el páramo: el hedor de brahmán estiércol. Pero sin que la mierda, no habría generador de energía.}
{137}{}{¿Por qué no puedes controlarlo?}
{138}{}{¡Gracias!}
{139}{}{Porque las Criptas hacer! Que superan en número a nosotros, por el momento, pero si fueron a unirse con nosotros, podríamos tomar de ellos.}
{140}{}{Seguro. Me voy a incorporar.}
{141}{}{No, gracias.}
{142}{}{Eres un Tonto... es broma. ¿Crees que dejaría que te unes que fácilmente?}
{143}{}{Sí.}
{144}{}{Eh, no!}
{145}{}{Oh, está bien. Usted está en. Ahora eres un Tonto. Nos engañará y morir. Bla-bla-bla.}
{146}{}{Miente!}
{147}{}{Bien, ¿qué se siente al ser un Tonto?}
{148}{}{Me gusta.}
{149}{}{Genial!!! ¿Y ahora qué hago?}
{150}{}{¿Cómo puedo obtener algunos de que el fresco de la armadura?}
{151}{}{Sería mejor. No muchos pueden profundizar el humor profundidades de la plena Fooldom.}
{152}{}{Uh, sí. Gracias. Uh, ¿qué es lo siguiente?}
{153}{}{Hmm, sí. Buena pregunta. Bueno, supongo que debemos planear nuestro ataque en las Criptas. Tenemos que lograr el control del generador de energía, o todo está perdido.}
{154}{}{¿Qué quieres que haga?}
{155}{}{Bueno, ya que usted es el miembro más reciente de los Necios, y por lo tanto el más prescindible, quiero que scout el enemigo y el informe.}
{156}{}{Vale.}
{157}{}{Así, en caso de ataque?}
{158}{}{¡Sí!}
{159}{}{¡No!}
{160}{}{Entonces ¿por qué me molesta? Hacer su trabajo y el informe de nuevo tan pronto como sea posible!}
{161}{}{Excelente! Tontos! Vamos a la batalla!}
{162}{}{Eres un Tonto en doble secreto de la libertad condicional. Usted no consigue Engañar a la armadura hasta que pase la libertad condicional.}
{163}{}{[Hecho]}
{164}{}{[Más]}
{165}{}{Las Criptas será enterrado una vez más!}
{166}{}{Perecer, escoria!}
{167}{}{¿Quién dijo que podría salir de sus tumbas? Retorno!}
{168}{}{Oh, nada.}
{169}{}{Miente! Llegar al trabajo antes de abrir una lata de whup-culo en usted!}
{170}{}{No creo que estoy listo.}
{171}{}{Oh, sí. Adiós.}
{172}{}{Dioses de la fortuna, los dioses de la suerte. No me importa mientras yo sea el último en reír. Nosotros no puede unirse a la muerte así que se ríen de él.}
{173}{}{Usted será como si un Tonto, pero escucha bien y marca mis palabras: si a traicionar como lo haría con sus antiguos compañeros, a continuación, vas a morir - con una mueca de dolor, no una risa.}
{174}{}{Y no, no deberán vestir el manto de un Tonto. Va a llevar el manto de un traidor, y mi garrot será su compañero.}
{175}{}{Sí, usted puede ser el próximo bufón en el Tonto del tribunal. Bienvenido a los Tontos. Nos engañará y morir.}
{176}{}{Y sin que el generador de energía, no hay ninguna razón para estar en este dunghole. El generador proporciona luz, calor e incluso algunos espeluznantes experiencias.}
{177}{}{Ir a recoger algunas de inteligencia o algo, y traer de vuelta la noticia de que el enemigo. (Agita su mano en un gesto desdeñoso)}
{178}{}{Sólo los Necios se quedan! Ahora bien, yo, la Reina Baka, regla de la Chatarra.}
