{100}{}{Estás viendo a un hombre. Te mira intensa y rápidamente a los ojos y luego aparta la vista.}
{101}{}{Estás viendo a Greg.}
{102}{}{¿Qué? ¿Por qué estás hablando conmigo? Averiguarán que sabes demasiado.}
{103}{}{Eh, detrás de ti. No hables tan alto, están ahí fuera.}
{104}{}{Vale, pero calla, vendrán a por los dos si no dejas de gritar.}
{105}{}{¿Quién eres?}
{106}{}{¿Por qué estás tan nervioso?}
{107}{}{Creo que deberían aumentar tus dosis de medicamentos.}
{108}{}{No importa.}
{109}{}{Soy... Greg... pero no se lo cuentes a nadie o vendrán a buscarme.}
{110}{}{¿Nervioso?, no estoy nervioso. Solo soy prudente. Todos dicen que soy un paranoico, pero soy el único que estará aquí cuando vengan a cogernos.}
{111}{}{¿Cuándo vengan a cogeros? ¿Quién va a venir a cogeros?}
{112}{}{Realmente estás paranoico. Hablaré contigo luego.}
{113}{}{Well, they are... You know, don't you? The disease was just the start. Now they're going to come and take us all. But you are just like all the rest. You won't believe me, and you'll be doomed. You mark my words: I'LL STILL BE HERE, and ALL OF THIS, INCLUDING YOU, WILL BE TAKEN. TAKEN! (He grasps his head and curls up, into a ball, squealing and thrashing about)}
{114}{}{Medication... Oh, so you're one of them, trying to get me to take my medication again... Well, you won't get me to. I WON'T TAKE IT! NO, I WON'T. THE VOICES. NO, I WON'T! YOU CAN'T MAKE ME. (He closes his eyes shut and clutches his head frantically, talking with the voices that only he can hear)}
{115}{}{¡NO PUEDES OBLIGARME!}
{116}{}{¡NADA DE LO QUE HAGAS ME AYUDARÁ!}
{117}{}{¡TODO ESTÁ PERDIDO!}
{118}{}{¡SE ACERCAN, Y NO PUEDES DETENERLOS!}
{119}{}{¡OS COGERÁN A TODOS!}
