{100}{}{Estás viendo al jefe de las caravanas.}
{101}{}{Bien, aquí está. Aquí está tu paga de }
{102}{}{ chapas. (Saca una bolsa vieja y raída y te da las chapas) Aquí tienes, otras }
{103}{}{ chapas más si vuelves con nosotros al Eje. Descansaremos un poco aquí, pero no te vayas muy lejos o la caravana partirá sin ti.}
{104}{}{Aaa... vale.}
{105}{}{¿Cuánto tiempo falta para que la caravana salga?}
{106}{}{¿Qué puedes contarme de Ciudad Vertedero?}
{107}{}{¿Qué puedes contarme del Cementerio de LA?}
{108}{}{¿Qué puedes contarme de la Hermandad del Acero?}
{109}{}{No sé si entenderás esto, pero salimos en dos horas o en cuanto estés lista.}
{110}{}{Um...}
{111}{}{¿Eh?}
{112}{}{Vale.}
{113}{}{Tía, actualmente solo contratamos a imbéciles.}
{114}{}{Normalmente salimos dos horas después de la llegada. No hay nada aquí que no hayamos visto antes, así que si quieres que salgamos más pronto, avísame cuando quieras.}
{115}{}{Creo que me daré una vuelta antes de que salgamos. Te veré luego.}
{116}{}{Vale. Volvamos al Eje. Yo tampoco tengo nada que ver aquí.}
{117}{}{¿Qué puedes contarme de Ciudad Vertedero?}
{118}{}{¿Qué puedes contarme del Cementerio de LA?}
{119}{}{¿Qué puedes contarme de la Hermandad del Acero?}
{120}{}{Bien, en realidad se parece un poco al Eje. También tiene sus problemas: Bandas ladrones, ya sabes... lo típico. Total, es mi ciudad ideal. [Risas]}
{121}{}{¿Cuánto tiempo falta para que la caravana salga?}
{122}{}{Creo que me daré una vuelta antes de que salgamos. Te veré luego.}
{123}{}{Esta parte del Cementerio de LA se llama Adytum. El Cementerio de LA está prácticamente gobernado por bandas. Una zona dura. Cuidado con lo que haces aquí. Adytum está gobernado por los Reguladores. Intentan mantener este lugar al margen de las batallas callejeras. No son demasiado amigos de los extraños, por lo que si no has hablado aún con ellos, te aconsejo que lo hagas antes de que empieces a merodear por ahí.}
{124}{}{Vacío }
{125}{}{¿Cuánto tiempo falta para que la caravana salga?}
{126}{}{Creo que me daré una vuelta antes de que salgamos. Te veré luego.}
{127}{}{No puedo contarte mucho de ellos. La Hermandad es muy prudente con sus cosas. Hay mucha gente que los critica, pero según tengo entendido son buena gente. Un poco fanáticos, quizás, pero tíos majos.}
{128}{}{¿Cuánto tiempo falta para que la caravana salga?}
{129}{}{Creo que me daré una vuelta antes de que salgamos. Te veré luego.}
{130}{}{¿Estás lista para partir?}
{131}{}{¡Vamos!}
{132}{}{No. Aún estoy echando un vistazo.}
{133}{}{Sí. Podemos irnos.}
{134}{}{Esta parte del Cementerio de LA se llama Adytum. El Cementerio de LA está prácticamente gobernado por bandas. Una zona dura. Vigila lo que haces allí.}
{135}{}{¿Cuánto tiempo falta para que la caravana salga?}
{136}{}{Creo que me daré una vuelta antes de que salgamos. Te veré luego.}
{137}{}{Vale. Lo has conseguido. Aquí tienes tus }
{138}{}{ chapas. Si quieres más trabajo, ve y habla de nuevo con el jefe. Me encantaría volver a trabajar contigo. Hablaré en tu favor ante el jefe. Tranquila.}
{139}{}{Adiós.}
{140}{}{Nos vemos.}
{141}{}{Eh, ¿qué tal?}
{142}{}{Si quieres más trabajo, ve y habla con el jefe.}
{143}{}{¿Te ocurre algo?}
{144}{}{¡Eres un asquerosa psicópata!}
{145}{}{¡No trabajo contigo!}
{146}{}{200}
{147}{}{400}
{148}{}{600}
{149}{}{¿Qué puedes contarme sobre Necrópolis?}
{150}{}{¡Un lugar horrible, tía!}
{151}{}{La caravana ha salido.}
{200}{}{Hmmmpf...}
{201}{}{Mmm... me encantaría saber leer.}
{300}{}{¿Por qué no te encargas de tus asuntos?}
{400}{}{No me pagan para hablar.}
{501}{}{Care to tell me why you abandoned the fucking caravan?! I can't believe it! Lucky for you, they finished without yer sorry ass. Get out! I ain't paying you anything!}
{502}{}{I can't believe it! We've lost the whole fucking caravan! I ain't paying you a single god-damn cap. Get the hell out of my face.}
{504}{}{You've got some nerve. Get out of here, and try to think up a credible story for the boss about why you abandoned the fucking caravan! Maybe then you'll get yer money, but I doubt it.}
{505}{}{I can't believe it! We've lost the whole fucking caravan! I ain't paying you a single god-damn cap. Get the hell out of my face.}
{506}{}{¿Hay algún trabajo que pueda hacer?}
{507}{}{¡Yo querer trabajo!}
{508}{}{Necesitamos músculo para descargar las caravanas. Te pagaré }
{509}{}{ chapas.}
{510}{}{¡Uh!}
{511}{}{Nop.}
{512}{}{Estoy en ello.}
{513}{}{No me gusta.}
{520}{}{Pasas una hora descargando la caravana.}
{521}{}{Ayudas a terminar de descargar la caravana y te dan }
{522}{}{ chapas.}
{600}{}{Well, here we are. I can't pay you the normal rate, since we lost some of the caravan. Gotta cover our losses, y'know. Here's your payment of }
{601}{}{ chapas. (Saca una bolsa vieja y raída y te da las chapas) Aquí tienes, otras }
{602}{}{If you want more work, just go talk to the boss. I'd be okay working with you again. Take it easy!}
{603}{}{ chapas. (Saca una bolsa vieja y raída y te da las chapas) }
{604}{}{Vale, lo has hecho. No puedo pagarte nada porque hemos perdido toda la caravana. Tenemos que cubrir las pérdidas, ya sabes. Me gustaría que fuese de otra forma pero esas son las reglas.}
{605}{}{Vale, lo has hecho. No puedo pagarte nada porque todos los brahmines han muerto. Nos has costado mucho dinero, colega. Sin brahmines no hay caravana, y sin esta no hay dinero. Espero que no te vuelvan a dejar trabajar con nosotros.}
