{100}{}{Ves a un Miembro de los Niños de la Catedral.}
{101}{}{¡El Maestro perdonará tus pecados! ¡Únete a nosotros y sé libre! ¡Reza al Maestro y a su misericordia!}
{102}{}{¡Hola alma errante! Las enseñanzas del Maestro me han hecho vivir por primera vez. ¿Puedo compartir mi fantástica historia contigo?}
{103}{}{¿Dónde puedo encontrar al Maestro?}
{104}{}{Adelante.}
{105}{}{¿Quién está al mando aquí?}
{106}{}{¿Las enseñanzas del Maestro? ¿Son mejores que el zumo de escorpión rad?}
{107}{}{¿Termina en muerte? ¡Si no, puedo cambiarlo!}
{108}{}{¡Me gusta la historia!}
{109}{}{¡El Maestro mira hacia arriba! ¡El Maestro se sienta debajo! ¡Observa el crecimiento de la Paz y la Unidad!}
{110}{}{Érase una vez un hombre tan lleno de ira que casi murió. Pero ahora... ¡Reza al Maestro! ¡Adora la Llama Sagrada! ¡Alaba el viñedo de la vida! ¡Síííí!}
{111}{}{Tú estás al mando, amiga mía, pero el Maestro es tu guía. ¡Alaba al Maestro! ¡Alaba a la Llama Sagrada que ilumina tu camino!}
{112}{}{¡Las enseñanzas del Maestro son mucho mejores que cualquier bebida e incluso que el sexo! ¡Ohhhh! ¡Él transciende al vicio y a la virtud! ¡Ahhhh! ¡El Maestro es tanto padre como amante para todos nosotros!}
{113}{}{¡No habrá muerte mientras el Maestro esté aquí para protegernos!}
{114}{}{¡Pero debo alabar al Maestro! ¡Adiós, amiga! ¡Luego te cuento la historia!}
{115}{}{¡Pero debo alabar al Maestro! ¡Adiós, amiga! ¡Luego te cuento la historia!}
