{100}{}{Nos dirigimos de vuelta al Eje.}
{101}{}{¿Vas a volver con nosotros?}
{102}{}{Estoy lista para partir.}
{103}{}{Espero que me queden suficientes balas.}
{104}{}{¡Me encanta este trabajo!}
{105}{}{¡Vámonos!}
{106}{}{¡Pongámonos en marcha!}
{107}{}{¡Los hemos matado a todos!}
{108}{}{¡Eso fue fácil!}
{109}{}{¡No hables, mueve el culo!}
{110}{}{¿Estás lista para partir?}
{111}{}{No me pagan para hablar.}
{112}{}{¡Un lugar horrible, tía!}
{113}{}{No me pagan para hablar.}
{114}{}{Metete en tus asuntos, ¿quieres?}
{115}{}{Metete en tus asuntos, ¿quieres?}
{200}{}{Let's do this!}
{201}{}{Hope I have enough bullets...}
{202}{}{Aim for the eyes!}
{203}{}{¡Protege la caravana!}
{204}{}{Stay sharp, everyone.}
