{100}{}{Abres la puerta.}
{101}{}{¡Rompes la ganzúa!}
{102}{}{No puedes abrir esta cerradura.}
{103}{}{No has podido forzar la cerradura.}
{104}{}{La puerta está cerrada con llave.}
{105}{}{La puerta está abierta.}
{106}{}{La puerta está cerrada pero sin llave.}
{107}{}{La puerta está cerrada con llave.}
{108}{}{La puerta chirría mucho.}
{109}{}{La puerta ya está abierta.}
{110}{}{Es bastante difícil que fuerces esta puerta.}
{200}{}{No hay ninguna cerradura que forzar en esta puerta.}
{201}{}{Te das cuenta de que hay algunas irregularidades en la pared.}
