{100}{}{Eres incapaz de determinar si estás envenenada o irradiada.}
{101}{}{Estás irradiada y envenenada, pero no sabes en qué medida.}
{102}{}{Estás irradiada, pero no sabes en qué medida.}
{103}{}{Estás envenenada, pero no sabes en qué medida.}
{104}{}{Estás }
{105}{}{mínimamente}
{106}{}{ligeramente}
{107}{}{levemente}
{108}{}{moderadamente}
{109}{}{muy}
{110}{}{extremadamente}
{111}{}{peligrosamente}
{112}{}{mortalmente}
{113}{}{ irradiada}
{114}{}{.}
{115}{}{ y }
{116}{}{Nivel de radiación: }
{117}{}{ rads.}
{118}{}{ Estás envenenada a un nivel }
{119}{}{No estás irradiada o envenenada.}
{200}{}{}
