{100}{}{Estás viendo un necrófago zombi.}
{101}{}{Ves: Zombi.}
{102}{}{Ugh.}
{103}{}{Ceeereebrooos}
{104}{}{Buuuu...}
{105}{}{Uuhnnng...}
{106}{}{¡Grrr!}
{107}{}{Uungh.}
{108}{}{Mmmuuh...}
{109}{}{¡Arrrr!}
{110}{}{¡Grrrrr!}
{111}{}{*gruñe*}
{112}{}{*gorgotea*}
{113}{}{Mmmmmmm.}
{114}{}{*gruñe*}
{200}{}{Examinas al lamentable ser, pero no consigues imaginar qué es lo que ha hecho que esté como está.}
{201}{}{Parece haber sido humano o por lo menos haber descendido de ellos. Imaginas que el deterioro del cuerpo se debe al ácido o a las radiaciones.}
{202}{}{El cuerpo del humanoide parece estar altamente irradiado, pero aún funciona. Aun habiendo sido humano en el pasado, ha degenerado a un estilo de vida más animal.}
{203}{}{El cuerpo del humanoide parece estar muy irradiado y gran parte de la musculatura y el cerebro están deteriorados. Sin embargo, los indicadores genéticos te hacen pensar que desciende, como tú, de aquellos que llegaron a los Refugios.}
{204}{}{Este triste ser parece estar altamente irradiado. No puedes determinar si se ha vuelto loco por estar enjaulado, o simplemente por haber perdido mucho tejido cerebral debido a la radiación.}
{205}{}{El cuerpo de este humanoide parece estar altamente irradiado, sea como sea ha mantenido suficiente materia cerebral y funciones motoras como para hablar claramente.}
