{100}{}{Comando, aquí la Casa de Guardia. Todo claro. Corto.}
{101}{}{¡Muerte para ti!}
{102}{}{¡Intruso!}
{103}{}{¡Hu-ma-na!}
{104}{}{Alto. Ésta es una zona prohibida. No deberías estar aquí.}
{105}{}{Será mejor que te rindas.}
{106}{}{Para. Voy a ver al Teniente. Ven en son de paz o muere.}
{107}{}{¡Luggi!}
{108}{}{¡Muere, escoria!}
{109}{}{Vengo a hablar con tu Maestro.}
{110}{}{Soy una mutante especial en una misión encomendada por tu Maestro. Déjame pasar o afronta las consecuencias.}
{111}{}{Estoy con los de la Catedral. Dalo por seguro.}
{112}{}{¡Muere!}
{113}{}{Hazlo a tu manera.}
{114}{}{Bueno. En realidad, la muerte es así.}
{115}{}{Bueno. Ven conmigo, miserable mosquito.}
{116}{}{Bien. Vámonos.}
{117}{}{¿Graciosilla? ¡No te va a parecer tan gracioso cuando te empapele!}
{118}{}{No te creo.}
{119}{}{Creo que no.}
{120}{}{No. Tú, humana. Muere.}
{121}{}{Si mientes, te mato.}
{122}{}{Oh, vale. Lárgate de aquí.}
{123}{}{Uh, bueno. Imagino que sí. Quizás sea mejor que veas al Teniente.}
{124}{}{Mataste a mi hermano. ¡Me vengaré!}
{125}{}{¡Muerte para ti!}
{126}{}{¡Asesino!}
{127}{}{¡Asesina!}
