{100}{}{A Junktown guard.}
{101}{}{Esto es Ciudad Vertedero. Es un lugar agradable en el que vivir mientras estés en el bando correcto.}
{102}{}{Vigila a Gizmo y a sus seguidores.}
{103}{}{Me cae bien mi jefe.}
{104}{}{Será mejor que apartes eso. Ciudad Vertedero es una ciudad amistosa, y queremos que siga siendo así.}
{105}{}{¿Apartar eso?}
{106}{}{No me digas lo que tengo que hacer, perdedor.}
{107}{}{Me parece bien. Por cierto, ¿cuál es la ley local sobre armas?}
{108}{}{Uh oh.}
{109}{}{Tu arma, idiota. Killian no te quitará las armas, pero será mejor que las mantengas enfundadas.}
{110}{}{Oh, lo siento.}
{111}{}{¡De ninguna manera! ¡No voy a dejar las armas por nadie!}
{112}{}{You'd better behave, since it's the law, and I enforce the law. Put your weapon away, don't draw it unless in self-defense, and you won't have a problem with us guards.}
{113}{}{[Más]}
{114}{}{Disobey the law, and we will return you to the lawless wasteland - dead or alive.}
{115}{}{Claro, si te pones así.}
{116}{}{¡Trágate tus leyes!}
{117}{}{Bueno, uh, yo estoy de acuerdo. Pero será mejor que tengas cuidado.}
{118}{}{Fine, then. Heh.}
{119}{}{Está bien que hayas preguntado. No se pueden desenfundar las armas si no es en defensa propia. Si empiezas una pelea, será culpa tuya. Otra cosa distinta es que vayas por ahí armada. No saques ni un cuchillo ni una pistola sin un motivo real. Que tengas un buen día.}
{120}{}{Thanks - you, too.}
{121}{}{Eh tú, ¡nada de armas! Y no me importa si tu madre te golpeó cuando eras pequeño.}
{122}{}{Dorf!}
{123}{}{You earn 150 experience for killing the guard.}
