{100}{}{Ves: a Heather, de los Exploradores de los Seguidores.}
{101}{}{¿Qué estás haciendo aquí?}
{102}{}{¡Chungo!}
{103}{}{Aa-dióós.}
{104}{}{Tan sólo estoy echando un vistazo.}
{105}{}{¡Vengo a matarte!}
{106}{}{Solo tengo curiosidad de lo que pasa por aquí.}
{107}{}{¿De verdad? ¿Y qué es lo que estás buscando?}
{108}{}{Creo que ya la he encontrado.}
{109}{}{Busco a un espía.}
{110}{}{Nada, realmente. Solo estoy observando.}
{111}{}{Información.}
{112}{}{Gracias, pero ya estoy pillada. Creo que es hora de que te vayas.}
{113}{}{Sí, el espía. He oído hablar de ese molesto parásito. Espero que podamos atraparlo.}
{114}{}{Sigo escuchando que es una espía.}
{115}{}{¿Has escuchado algo acerca del espía?}
{116}{}{¡Eres la espía!}
{117}{}{Buena suerte. Perdón por haberte molestado.}
{118}{}{Apuesto a que fue el fanfarrón de Neil el que lo dijo. Tendré que tener una charla con él más tarde.}
{119}{}{¿Crees qué Neil es el espía?}
{120}{}{¿Entonces quién crees que es el espía?}
{121}{}{Parece que estás a la defensiva. ¿Alguna razón para ello??}
{122}{}{Estoy seguro de ello. Solo necesito una prueba.}
{123}{}{Te encontraré esa prueba.}
{124}{}{Parece una persona agradable. No me lo creo.}
{125}{}{¿Por qué crees que es él?}
{126}{}{Gracias. No sabes cuánto significa esto para mí. En cuanto tengas la prueba, mátalo.}
{127}{}{¿Qué te falta para creerlo? Tiene acceso a los Niños. Trabaja durante la noche cuando los demás duermen. Debe de ser él.}
{128}{}{Vale, lo comprobaré.}
{129}{}{Olvídalo. ¡Creo que intentas confundirme!}
{130}{}{Siento de verdad que pienses así. No puedo tener a alguien que piense que soy una espía. Te eliminaré del servicio.}
{131}{}{Tiene acceso a los Niños durante la noche. Nunca nadie lo ve cuando está de servicio. Debe ser él.}
{132}{}{Vale, lo comprobaré.}
{133}{}{Olvídalo. ¡Creo que intentas confundirme!}
{134}{}{No estoy seguro de quién puede ser. Creo que deber de ser un guardia o una erudita. Siguen colándose en la Catedral de los Niños por la noche.}
{135}{}{¿Se te ocurre alguna otra información que puedas darme?}
{136}{}{Pero he oído que solo los exploradores hacen incursiones a la Catedral}
{137}{}{Vale. Gracias por tu ayuda.}
{138}{}{La verdad es que no. Es solo que pienso que debe de ser un hombre y probablemente guardia o erudito.}
{139}{}{Vale. Gracias por tu ayuda.}
{140}{}{Cierto. Nosotros, los exploradores hacemos muchas incursiones a los Niños, y a un gran precio últimamente. Este espía no está costando mucho.}
{141}{}{Pareces realmente desgarrada por esto. Buscaré al espía y lo mataré.}
{142}{}{¿Podría el espía ser un explorador?}
{143}{}{Gracias por tu ayuda.}
{144}{}{¿Por qué lo haría uno de nosotros?}
{145}{}{Si empiezas a matar exploradores, pararás las incursiones.}
{146}{}{No lo sé. ¿Por qué lo harías tú?}
{147}{}{No lo sé. Solo me lo preguntaba.}
{148}{}{Parece una buena idea. He notado que a Peter no suele ser atacado durante las incursiones. Creo que puede ser él.}
{149}{}{Vale, lo comprobaré.}
{150}{}{Olvídalo. ¡Creo que intentas confundirme!}
{151}{}{¿Crees que soy yo?}
{152}{}{Lo siento. Es que estoy algo estresado.}
{153}{}{¡Sí! ¡Y ahora morirás!}
{154}{}{Entonces pregúntatelo en otro sitio. Debo volver al trabajo.}
{155}{}{Creo que él cree que yo soy la espía. Pero no lo soy.}
{156}{}{Quizás él esté en lo cierto.}
{157}{}{¿Por qué lo piensa?}
{158}{}{Porque soy la nueva exploradora. Solo he estado aquí durante un año y los problemas empezaron hace cinco meses.}
{159}{}{Creo que Neil está en lo cierto.}
{160}{}{Creo que Neil puede ser el espía. Iré a comprobarlo.}
{161}{}{Entonces busca en otro lado. No hay lugar para ti aquí.}
{162}{}{Si necesitas información, busca a Nicole. Cree que lo sabe todo.}
{163}{}{Puedo ser persuadida para decirte qué es lo que pasa. Por un precio.}
{164}{}{¿Cuánto?}
{165}{}{¿Venderías secretos?}
{166}{}{Olvídalo. No tengo nada de dinero.}
{167}{}{300 chapas y la información es tuya.}
{168}{}{Claro.}
{169}{}{Ni hablar.}
{170}{}{Habrá una incursión al sur del fuerte de los Niños. Ahora ve.}
{171}{}{¿Intentas tenderme una trampa? ¡Te lo mostraré!}
{172}{}{Siento que lo veas así. Pero, que tengas un buen día.}
{173}{}{Tengo que sobrevivir de alguna forma. Ahora dime, ¿la quieres o no?}
{174}{}{Claro.}
{175}{}{Ni hablar.}
{176}{}{Nada. Ahora vete.}
{177}{}{Déjame. Estoy intentando descansar.}
