{100}{}{¿Qué quieres?}
{101}{}{Déjame en paz.}
{102}{}{¿Qué?}
{103}{}{No te metas en mis asuntos.}
{104}{}{Ey.}
{105}{}{¡Arrrr!}
{106}{}{¡Grrrrr!}
{107}{}{Uungh.}
{108}{}{Uhh.}
{109}{}{Oye, ¿has oído que Set ha sido derrotado?}
{110}{}{Set está muerto. Set está muerto. Set está muerto...}
{111}{}{Hay agua suficiente para satisfacer a todo el mundo. Set se encarga de eso.}
{112}{}{He oído que los mutantes han sido expulsados de la ciudad.}
{113}{}{Desde que los mutantes se han ido, todo marcha mejor.}
{114}{}{Hola.}
{200}{}{Examinas al lamentable ser, pero no consigues imaginar qué es lo que ha hecho que esté como está.}
{201}{}{Parece haber sido humano o por lo menos haber descendido de ellos. Imaginas que el deterioro del cuerpo se debe al ácido o a las radiaciones.}
{202}{}{El cuerpo del humanoide parece estar altamente irradiado, pero aún funciona. Aun habiendo sido humano en el pasado, ha degenerado a un estilo de vida más animal.}
{203}{}{Al parecer el cuerpo del humanoide está muy dañado, y gran parte de los músculos y de la masa cerebral parece estar deteriorada. Sin embargo, los indicadores genéticos te hacen pensar que procede, como tú, de aquellos que se instalaron en los Refugios.}
