{100}{}{¿Crees que eso te salvará de Baka?}
{101}{}{You're no match for us!}
{102}{}{Si fuera tan feo, me suicidaría.}
{103}{}{You Crypts don't have a chance.}
{104}{}{Do you like pain?}
{105}{}{I'm going to enjoy this.}
{106}{}{You shall die scum!}
{107}{}{It's pay back time.}
{108}{}{Are you ready for some pain?}
{109}{}{The only thing stupider than you is Rayze.}
{110}{}{I guess afterbirth can live a little while.}
{111}{}{The Crypts shall be buried once more!}
{112}{}{Perish scum!}
{113}{}{Who said you could come out of your graves? Return!}
{114}{}{Thy lowly ways shall be eradicated from the earth!}
{115}{}{Only Fools have true knowledge to rule Scrapheap.}
{116}{}{Begone gut slime of a three legged chicken!}
{117}{}{What happened to you? Your mama drop you on your head at birth?}
{118}{}{}
{119}{}{}
{120}{}{}
{200}{}{Locos, corred mientras podáis.}
{201}{}{Hey, Rayze, hunting season just openned, and Fools are on the list of dumb animals.}
{202}{}{Eh, colegas. Dejadme que me cargue al Loco.}
{203}{}{The Crypts will bury you!}
{204}{}{Fools got no reason to live.}
{205}{}{The Foolish shall perish.}
{206}{}{Look who got hit with the ugly stick.}
{207}{}{¡Te vamos a enterrar, Loco!}
{208}{}{¡Voy a patear unos cuantos culos! ¡Estoy preparadooooo!}
{209}{}{¡Los Enterradores mandan! ¡Y los Locos la maman!}
{210}{}{¡Traemos muerte!}
{211}{}{Don't worry, it'll be quick and painful!}
{212}{}{PURPLE BABOONS!}
{213}{}{The Brahmin have more sense than a Fool.}
{214}{}{The Fools are so weak, even Lex can beat them all up.}
{215}{}{Haha! More fools to kill!!}
{216}{}{The only thing you Fools will rule is a tombstone.}
{217}{}{It's about time. I've been waiting for this.}
{218}{}{Even Lenny has better aim than you.}
{219}{}{Eat lead fools.}
{220}{}{I'll mount your head on a spike.}
{300}{}{Hey! The generator is broken. Let's leave this dump.}
{400}{}{With the generator broken, there is little reason for the gangs to fight over Scrapheap. Your job here is done, but your mission to find the water purification chip continues.}
{402}{}{With the gangs defeated, Scrapheap is a safe haven once again.}
