{100}{}{Ves: a Kalnor, un guardia de Ciudad Vertedero.}
{101}{}{Será mejor que tengas cuidado con lo que haces aquí.}
{102}{}{No es una buena ciudad para meterse en líos.}
{103}{}{Compórtate y no tendremos que enfadarnos.}
{104}{}{Tienes razón.}
{105}{}{Sigue trabajando así de bien.}
{106}{}{Bonito día, ¿verdad?}
{107}{}{Esto es Ciudad Vertedero. Es un lugar agradable en el que vivir mientras estés en el bando correcto.}
{108}{}{Vigila a Gizmo y a sus seguidores.}
{109}{}{Me cae bien mi jefe.}
{110}{}{Será mejor que apartes eso. Ciudad Vertedero es una ciudad amistosa, y queremos que siga siendo así.}
{111}{}{¿Apartar eso?}
{112}{}{No me digas lo que tengo que hacer, perdedor.}
{113}{}{Me parece bien. Por cierto, ¿cuál es la ley local sobre armas?}
{114}{}{Uh, oh.}
{115}{}{Tu arma, idiota. Killian no te quitará tus armas pero será mejor que las mantengas enfundadas.}
{116}{}{Oh, lo siento.}
{117}{}{¡De ninguna manera! ¡No voy a dejar las armas por nadie!}
{118}{}{Será mejor que te comportes porque ésta es la ley y soy yo quien la impone. Aparta tu arma. No la desenfundes a no ser que sea en defensa propia y no tendrás problemas con nosotros, los guardias. Desobedece la ley y te devolveremos al yermo, donde no hay ley... muerta o viva.}
{119}{}{Claro, si te pones así.}
{120}{}{¡Trágate tus leyes!}
{121}{}{Bueno, uh, yo estoy de acuerdo. Pero será mejor que tengas cuidado.}
{122}{}{Está bien que hayas preguntado. No se pueden desenfundar las armas si no es en defensa propia. Si empiezas una pelea, será culpa tuya. Otra cosa distinta es que vayas por ahí armada. No saques ni un cuchillo ni una pistola sin un motivo real. Que tengas un buen día.}
{123}{}{Hey you, no weapons! And I don't care if your mama dropped you on your head as a kid. No weapons.}
{124}{}{¡Eh! ¡Tú! ¿Qué haces curioseando?}
{125}{}{Nada.}
{126}{}{No estoy curioseando. Solo me gusta caminar con precaución.}
{127}{}{Uhhh.}
{128}{}{Hagas lo que hagas, no lo hagas en esta ciudad.}
{129}{}{¡Eh! ¡En esta ciudad no queremos tías misteriosas! ¡Lárgate de aquí antes de que te echemos!}
{130}{}{Bueno, uh, vale. Lo que sea. Pero no hagas nada ilegal.}
{131}{}{Gracias, adiós.}
{132}{}{Naturalmente. Tendré mucho cuidado, señor.}
{133}{}{Naturalmente. Tendré mucho cuidado, señora.}
{134}{}{Será mejor que tengas cuidado porque te estaremos vigilando.}
{135}{}{Bienvenida a Ciudad Vertedero. ¿Qué puedo hacer por ti?}
{136}{}{Nada, gracias.}
{137}{}{¿Qué estás haciendo aquí? ¿Qué es este lugar?}
{138}{}{¿Dónde puedo conseguir algunos suministros?}
{139}{}{¡Gua-gua!}
{140}{}{No sé nada de eso. Mejor que hables con Killian. Está al norte. Por ese camino arriba, ¿vale?}
{141}{}{Yo soy guardia y vigilo a los extraños como tú. Y este lugar se llama Ciudad Vertedero. ¡Eh, no te rías! Da la casualidad de que a mí me gusta ese nombre. Nosotros nos dedicamos a comerciar. A veces hacemos negocios con esos bastardos creídos del Eje. Eh, tú no serás del Eje, ¿verdad?}
{142}{}{¿Qué si soy del Eje? ¡Claro que sí!}
{143}{}{¿Yo? No, yo no soy del Eje.}
{144}{}{Entonces tendrás que conocer la mayoría de las normas. Que tengas un buen día. Y perdona por lo de bastardos, ¿vale?}
{145}{}{¡Sí! Eh, no hay problema. Adiós.}
{146}{}{Esto me va a causar graves problemas mentales. Nos vemos.}
{147}{}{Mmm. Vale. No es nuestro papel hacer preguntas. Que tengas un buen día y no te metas en problemas.}
{148}{}{Oh, mierda. El lugar para eso es la tienda de Darkwater. Killian lo dirige. Está un poco hacia el norte. Killian tiene los mejores suministros de la ciudad.}
{149}{}{Gracias. Adiós.}
{150}{}{¿Quieres enseñarme dónde guardas TUS suministros?}
{152}{}{Uh, no. Lo siento, señora. Tengo trabajo que hacer aquí.}
{153}{}{Que tengas un buen día.}
{154}{}{No te metas en líos.}
{155}{}{Jolín, espero que mi reemplazo llegue pronto. Parece como si llevase toda la vida de guardia.}
{156}{}{Lo siento, las puertas están cerradas durante la noche. Vuelve por la mañana.}
{157}{}{Eh, ¡necesito entrar!}
{158}{}{No hay problema. Te veré por la mañana.}
{159}{}{Siento molestarle, señor, pero me gustaría entrar en su ciudad. Ya verá como no les causo ningún problema.}
{160}{}{¡Hunh-huh!}
{161}{}{Vuelve... el... día...}
{162}{}{Lo siento, las normas son las normas. No se admiten extraños durante la noche.}
{163}{}{Bueno, no debería hacer esto, pero pareces buena persona. Pasa, pero no causes problemas.}
{164}{}{¡Eh! ¡Eres tú! Vamos entra.}
{165}{}{¡Qué bien verte de nuevo!}
{166}{}{Eh, será mejor que gires a la derecha y te largues de aquí.}
{167}{}{Continúa.}
