{100}{}{El cajón parece estar cerrado.}
{101}{}{Consigues forzar la cerradura con éxito.}
{102}{}{Esta cerradura sobrepasa tus habilidades con la ganzúa.}
{103}{}{No consigues forzar la cerradura.}
{104}{}{La taquilla ya está abierta.}
{105}{}{¡Rompes tus ganzúas en la cerradura!}
{106}{}{Abres la cerradura con destreza.}
{107}{}{La taquilla está bajo llave.}
{108}{}{Rompes tu ganzúa.}
{109}{}{Abres la taquilla.}
{110}{}{No puedes abrir la cerradura.}
{111}{}{La explosión destruye completamente la cerradura.}
{112}{}{¡La explosión ha destruido el recipiente!}
