{100}{}{¿Qué quieres?}
{101}{}{Oye, ¿vas a comerte esta rata muerta?}
{102}{}{¿Qué?}
{103}{}{¿Has visto a mi perro Elvis? Está por aquí en alguna parte.}
{104}{}{Ey.}
{105}{}{¡Arrrr!}
{106}{}{¡Grrrrr!}
{107}{}{¡Voy a comerme tus huesos!}
{108}{}{¡Muerte! ¡Muerte! ¡Muerte!}
{109}{}{Oye, ¿has oído que Set ha sido derrotado?}
{110}{}{Set ha muerto. Set ha muerto. Set ha muerto.}
{111}{}{Hay agua suficiente para satisfacer a todo el mundo. Set se encarga de eso.}
{112}{}{He oído que los mutantes se han ido de la ciudad.}
{113}{}{Desde que los mutantes se han ido, todo marcha mejor.}
{114}{}{Hola.}
