{100}{}{Paladín}
{101}{}{Buenos días, Iniciada.}
{102}{}{Si necesitas algo, deberías hablar con Vree.}
{103}{}{Vree está justo allí, si necesitas hablar con alguien.}
{104}{}{Tengo que encontrar tiempo entre patrulla y patrulla y entrenarme para seguir con mis estudios. Creo que estoy falto de práctica.}
{105}{}{Tengo que mantener mi cuerpo y mi mente en las mejores condiciones, Iniciada.}
{106}{}{Nosotros los escribas diseñamos todo el equipo, armas y suministros. Es bastante emocionante.}
{107}{}{Ser Paladín no es solo luchar, hijo.}
{108}{}{Hija mía, ser un Paladín no es solo luchar.}
