{100}{}{Ves a un campesino.}
{101}{}{Ves: a Phil.}
{102}{}{¡Yo no soy mi perro!}
{103}{}{¡Maldita sea, acaba con esa bestia!}
{104}{}{Si yo fuera tú no confiaría en esa bestia. A esa cosa le gusta matar.}
{105}{}{Señor,}
{106}{}{Señora,}
{107}{}{ me haría muy feliz si se deshiciera de ese maldito perro.}
{108}{}{¿Por qué?}
{109}{}{No, solo me ocupo de asuntos importantes.}
{110}{}{¿De dónde viene?}
{111}{}{Hnng.}
{112}{}{Quizás puedas hablarle hasta que muera.}
{113}{}{No nos deja entrar en nuestra propia casa, por eso.}
{114}{}{Eso es todo, gracias.}
{115}{}{¿No es vuestro perro?}
{116}{}{Era el animal de compañía de un viajero. Cuando murió, este maldito chucho instaló su culo peludo en nuestra entrada y ya no se mueve de ahí. Lleva ahí días y días.}
{117}{}{Oh. Gracias.}
{118}{}{¿Quién era ese viajero?}
{119}{}{¿Cómo era el viajero?}
{120}{}{No lo sé. Un tío que venía del este, o eso dijo por lo menos. Como si fuera tan fácil atravesar las tierras de la muerte del este. Tuvo algunos problemas con Gizmo, cuando intentó meterse en sus negocios.}
{121}{}{Así que Gizmo mandó un par de matones para que le dieran una paliza, lo tiraron desde el tejado del casino. El viajero se rompió el maldito cuello y murió. El perro se volvió loco.}
{122}{}{¿Cómo era el viajero?}
{123}{}{Oh, era un tío alto, de pelo oscuro con entradas canosas. Vestía todo de negro, (menuda idea para vivir en el desierto) y llevaba una escopeta.}
{124}{}{Tenía un acento bastante gracioso. El perro lo acompañaba continuamente, lo seguía a todas partes.}
{125}{}{Gracias por la charla.}
{126}{}{Odio a ese perro.}
{127}{}{Gracias por tu ayuda.}
{128}{}{Wow, okay. See you around I guess. Asshole.}
