{100}{}{Estás viendo a un borracho.}
{101}{}{Estás viendo a un cliente.}
{102}{}{Ves a una chica muy guapa.}
{103}{}{Estás viendo a un hombre de aspecto extraño.}
{104}{}{Estás viendo a un jugador.}
{105}{}{Ves a una mujer que parece muy ocupada.}
{106}{}{Estás viendo a una mujer.}
{107}{}{Estás viendo a un hombre.}
{108}{}{Estás viendo a un jugador muy triste.}
{109}{}{Estás viendo a un mercenario.}
{110}{}{Déjame ahogar lash penas.}
{111}{}{Sí, querishísimo amiga.}
{112}{}{¿Po'qué estásh... hip... 'onde eshtoy?}
{113}{}{¿Quién eres?}
{114}{}{¿Te conozco?}
{115}{}{No me siento muy bien.}
{116}{}{La bebida me pone, digo te pone.}
{117}{}{¿Quiénes sois vosotros dos?}
{118}{}{¡Señorita, quédese quieta!}
{119}{}{¡Chica, quédate quieta!}
{120}{}{¡A por el caballo!}
{121}{}{Estás acabando con la elegancia de este lugar.}
{122}{}{Vete, ¡gafe!}
{123}{}{No me desconcentres.}
{124}{}{¡Voy a ganar esta partida!}
{125}{}{¿No sabes hacer esto?}
{126}{}{¿Has visto eso? ¡Es imposible!}
{127}{}{Creo que están bromeando.}
{128}{}{Ahora hay posibilidades.}
{129}{}{Gano seguro.}
{130}{}{¿Qué? ¿Cómo he podido perder?}
{131}{}{Esta mesa está gafada.}
{132}{}{Estoy ocupado.}
{133}{}{¿No ves que estoy intentando jugar?}
{134}{}{Apuesta o calla.}
{135}{}{Déjanos solos o llamaré a los guardias.}
{136}{}{Cuidado, soy amiga íntima del Ayudante Fry.}
{137}{}{¿Te importa?}
{138}{}{¡Odio a las mironas!}
{139}{}{No me gustan los grupos.}
{140}{}{Estoy demasiado cansada para otra.}
{141}{}{Estás soñando, colega, ¡lárgate!}
{142}{}{¡Vete de aquí! }
{143}{}{¿Qué diablos crees que estás haciendo?}
{144}{}{¡Cuidado con tus modales!}
{145}{}{¡Llamaré a la policía!}
{146}{}{¡Ni lo sueñes!}
{147}{}{¡Vete!}
{148}{}{¡Lárgate!}
{149}{}{¿Qué es lo que miras?}
{150}{}{¿Te importa?}
{151}{}{¡Vete de nuestra habitación!}
{152}{}{¡Vete!}
{153}{}{¿Formas parte de la orgía?}
{154}{}{¡Fuera de aquí, pervertido!}
{155}{}{¿Cuál es tu problema?}
{156}{}{Vete antes de que me enfade.}
{157}{}{Búscate a otra.}
{158}{}{Ésta es mía.}
{159}{}{¡Mierda!}
{160}{}{¿Estás de broma?}
{161}{}{Tendría que haber ganado yo.}
{162}{}{¡Por los pelos!}
{163}{}{He perdido por los pelos.}
{164}{}{¿Cuáles son las reglas?}
{165}{}{Antes era bueno en esto.}
{166}{}{Gracias por nada.}
{167}{}{¡No me lo creo!}
{168}{}{Lo he hecho a propósito.}
{169}{}{Hagan sus apuestas.}
{170}{}{Quite sus manos de ahí, señor.}
{171}{}{¡Ganador!}
{172}{}{Lo siento, amigos, puede que la próxima.}
{173}{}{¡Otro ganador!}
{174}{}{¡Manos fuera!}
{175}{}{Le toca, señor.}
{176}{}{Lo siento, es una apuesta inválida.}
{177}{}{Eso es.}
{178}{}{¿Alguien más?}
