{100}{}{Se trata de alguna clase de disquete de aspecto extraño. Quizás se puede utilizar con tu Pip-Boy 2000.}
{101}{}{Pip-Boy 2000 muestra: "Descargando datos... Abortando, los datos ya existen."}
{102}{}{Pip-Boy 2000 muestra: "Descargando datos... ... ... completado. ¡Que tenga un buen día!".}
{103}{}{Este disco está en mal estado. No tiene una etiqueta apropiada pero la palabra "anulasion" está grabada a rayones en un lado.}
{104}{}{Ves: Disco de Anulación de Seguridad.}
{105}{}{Usuario: "admin". Contraseña: "muerte". Protocolo de anulación de seguridad: Gamma Ómicron Delta.}
{106}{}{**BEGIN-DISK**}
{107}{}{**END-DISK**}
{108}{}{[Continuar]}
{109}{}{Pip-Boy 2000 muestra: "Usuario: "admin". Contraseña: "muerte". Protocolo de anulación de seguridad: Gamma Ómicron Delta."}
