{100}{}{Usas el ordenador de la puerta pero éste no acepta tu código de acceso.}
{101}{}{Utilizas el ordenador de la puerta. Un altavoz se pone en marcha.}
{102}{}{Perdona, pero no podemos dejarte volver ahora. Uh, problemas técnicos. Inténtalo más tarde.}
{103}{}{Estás viendo el ordenador de la puerta de entrada del Refugio 13.}
{104}{}{Te estamos agradecidos por habernos salvado pero ya no te podemos dejar entrar.}
{105}{}{Lo sentimos, pero no puedes volver. Te deseamos lo mejor.}
{106}{}{El Supervisor ha hablado, debes marcharte.}
{107}{}{Mira, muchos de nosotros estamos indignados con la decisión del Supervisor, pero debemos acatarla.}
{108}{}{Debes seguir tu vida en el mundo exterior. Buena suerte amiga.}
{109}{}{Eres un peligro para el futuro de este Refugio. Debes marcharte de inmediato.}
{110}{}{No eres bienvenida aquí. Márchate.}
{111}{}{No permitiremos a asesinas en el Refugio. ¡Lárgate!}
{112}{}{Tememos en lo que te has convertido y en lo que podrías hacernos... márchate.}
{113}{}{Después de lo que le hiciste al Supervisor, ¿pensabas que te dejaríamos volver?}
{114}{}{¡¿Cómo has podido traicionarnos de esta manera?!}
{115}{}{Lárgate, lunática.}
{116}{}{El ordenador explota en una espectacular lluvia de chispas y cables, cortocircuitando todo los mecanismos.}
{117}{}{Estás viendo el ordenador destruido de la puerta de entrada al Refugio 13.}
{118}{}{Es un desastre absoluto y es imposible de reparar.}
{119}{}{ La puerta no se volverá a cerrar nunca más.}
{120}{}{ La puerta no se volverá a abrir nunca más.}
{121}{}{¡Mi cara! ¡Qué has hecho!}
{122}{}{¡Mi cara! ¡Qué has hecho!}
{123}{}{El ordenador está inutilizado.}
{124}{}{Con la puerta sellada para siempre y sin un Chip de Agua de repuesto, los habitantes del Refugio 13 pronto descubrirán que su Refugio se ha convertido en una tumba.}
{125}{}{> ¿Comando?}
{126}{}{Estás viendo al médico del Refugio 13.}
{127}{}{Estás viendo al médico del Refugio 13.}
{128}{}{Modify configuration parameters.}
{129}{}{Nada, no importa.}
{130}{}{Welcome to your SimTek 5000 interactive customization! Vault-Tec is committed to providing a pleasant integration into the outside world. Remember, incorrect settings may cause unstable anomalies! (Warranty void after 2077)}
{131}{}{Vault 13 door entry computer can't be accessed during combat.}
{132}{}{I understand.  [Execute "SPOILERS.EXE"]}
{133}{}{Opens!}
{134}{}{Do shut.}
{135}{}{Miembro del Coro}
{136}{}{A-diós.}
{137}{}{Boosh.  [Execute "SPOILERS.EXE"]}
{138}{}{Recalibrate Vault 13 water-level monitoring systems.}
{139}{}{View or modify simulation-terminating parameters.}
{140}{}{Supermutantes}
{141}{}{Classify situational combat options.}
{142}{}{Recalculate cross-wasteland encounter statistics.}
{143}{}{[Items, Inventory, Bartering]}
{144}{}{Necesito algunas cosas.}
{145}{}{[Social sexy times]}
{146}{}{Hmm... Actually, let's go back.}
{147}{}{¡YO QUERER!}
{148}{}{Thanks, I'm all set.  [Exit system]}
{149}{}{[salir del sistema]}
{150}{}{Okay, I'm done here.  [Go to main menu]}
{151}{}{Replay historical data feed.}
{152}{}{Calculating... System monitors indicate that Vault 13 water reserves are currently dropping at a steady rate. Estimated days left until total depletion: }
{153}{}{.  Enter new value to recalibrate system.  (Default database value: 150)}
{154}{}{> ¿Comando?}
{155}{}{[30]}
{156}{}{[60]}
{157}{}{[90]}
{158}{}{[120]}
{159}{}{[150]}
{160}{}{[MÁS]}
{161}{}{[ATRÁS]}
{162}{}{[180]}
{163}{}{[210]}
{164}{}{[240]}
{165}{}{[270]}
{166}{}{[300]}
{167}{}{[330]}
{168}{}{[365]}
{169}{}{[730]}
{170}{}{[volver al menú principal]}
{171}{}{[125]}
{172}{}{[135]}
{173}{}{[140]}
{174}{}{[145]}
{175}{}{Align calibration with Overseer's estimates. [120 - 150]}
{176}{}{Or-seer nums! [120 - 150]}
{177}{}{[999]}
{178}{}{[64000]}
{179}{}{[130]}
{180}{}{Priority of Vault 13 waterchip-replacement subroutines.}
{181}{}{How to stop mutant invasions}
{182}{}{Reevaluate relative priority of Vault 13 survival vectors.}
{183}{}{[Endgame Condition: Can play after being dipped?]}
{184}{}{If the Wasteland will be as rough as it sounds, maybe I should take a moment to reflect on any personal neuroses that may affect my survival out there.}
{185}{}{Me strong is many smart. Maybe has crazies. Want big challenge! [Optional gameplay restrictions]}
{186}{}{If all other threats to the Vault are eliminated, our emergency wastewater redistribution protocol can negate the need for a Water Chip.  Protocol is currently: }
{187}{}{. Toggle protocol status?  (Default status: Enabled)}
{188}{}{DISABLED}
{189}{}{ENABLED}
{190}{}{Looks good; let's back up.  [Go to previous menu]}
{191}{}{Maestro}
{192}{}{Tanques}
{193}{}{Estás viendo al Maestro de los Supermutantes.}
{194}{}{Estás viendo al Maestro de los Supermutantes.}
{195}{}{To stop invasions of towns, you currently need to eliminate: }
{196}{}{ Change requirement for cessation?  (Default requirement: The Master)}
{197}{}{Checking... By default, this simulation will terminate if sensors indicate Vault 13 Survivability has dropped to zero. Current setting: }
{198}{}{Fijar la base en estado de alerta.}
{199}{}{No.}
{200}{}{Me done! Where other?  [Go to previous menu]}
{201}{}{Sí.}
{202}{}{!}
{203}{}{Raciones}
{204}{}{Habilidades}
{205}{}{Party members}
{206}{}{[Custom playstyles]}
{207}{}{[Misc]}
{208}{}{Thank you for trusting Vault-Tec and SimTek 5000 with your customization needs! Please state a command.}
{209}{}{Simulation terminates when Survivability reaches zero.}
{210}{}{Simulation can continue if the source was foreign.}
{211}{}{Simulation can continue if the source was organic.}
{212}{}{Simulation continues regardless of Survivability rating.}
{213}{}{Can the player keep playing after/if they've become a Super Mutant? Current seting: }
{214}{}{ (Default: No.)}
{215}{}{[SPECIAL]}
{216}{}{Adytum}
{217}{}{Necrópolis.}
{218}{}{Eje}
{219}{}{Nopnop.}
{220}{}{La Hermandad del Acero.}
{221}{}{Ciudad Vertedero.}
{222}{}{De Arenas Sombrías.}
{223}{}{Del Refugio 13.}
{224}{}{Vale, ¿de qué operación quieres hablar?}
{225}{}{You are viewing number of days until invasion of }
{226}{}{Actualmente tienes }
{227}{}{. Select new value below to modify.  (Default value: }
{228}{}{)}
{229}{}{Instant (0 days)}
{230}{}{1/4 of default.}
{231}{}{1/2 of default.}
{232}{}{Élite del Refugio.}
{233}{}{¡Es culpa mía!}
{234}{}{¡Es culpa mía!}
{235}{}{¡Es culpa mía!}
{236}{}{Disabled. (this location will not be invaded)}
{237}{}{Caes al suelo.}
{238}{}{Does player receive dadiation-on-hit from critters?}
{239}{}{Specifics of Childkiller status}
{240}{}{Ambient light and Flares}
{241}{}{}
{242}{}{}
{243}{}{}
{244}{}{}
{245}{}{}
{246}{}{}
{247}{}{Hardcore: No loading saves. Must complete in 1 session.}
{248}{}{Codependent Loser: If a hireling leaves or dies, game over.}
{249}{}{Lone Wolf: If you get party members, game over}
{250}{}{Pacifist: If player lands any hit in combat, game over.}
{251}{}{Killswitch: If combat mode is ever activated, game over.}
{252}{}{I Like It Hard: difficulty_level of Hard only.}
{253}{}{I Like It Rough: combat_difficulty of Rough only.}
{254}{}{Specify if any of the following characteristics apply to you, and sensors will adapt accordingly.}
{255}{}{I'm Special: If your stats are ever raised, game over.}
{256}{}{ This playstyle is currently: }
{257}{}{. Toggle status?}
{258}{}{Weapon Drop Mod is currently: }
{259}{}{hexes from corpse. Your command?}
{260}{}{, with weapons dropping }
{261}{}{¡Ve hacia él!}
{262}{}{1    Sí, desactívalo.}
{263}{}{Enable it, with a drop distance of 0 hexes from corpse.}
{264}{}{Enable it, with a drop distance of 0-1 hexes from corpse.}
{265}{}{Enable it, with a drop distance of 0-2 hexes from corpse.}
{266}{}{Enable it, with a drop distance of 1 hex from corpse.}
{267}{}{Enable it, with a drop distance of 1-2 hexes from corpse.}
{268}{}{Enable it, with a drop distance of 2 hexes from corpse.}
{269}{}{No creatures will irradiate the player upon landing an attack. Which type do you wish to toggle?}
{270}{}{Inteligencia}
{271}{}{, }
{272}{}{will have a chance to irradiate the player when landing hits, based on Combat Difficulty and player's stats. Which type do you wish to toggle?}
{273}{}{Rata Contaminada}
{274}{}{unos flotantes}
{275}{}{Centauros:}
{276}{}{Ves: a un necrófago resplandeciente.}
{277}{}{Ves: a un necrófago resplandeciente.}
{278}{}{Glowing Ghouls and Irradiated Rats only, with a max of 1 rad per hit (2077 field manual defaults)}
{279}{}{Only glowing ghouls and irradiated rats will have a chance to irradiate the player when landing hits, with 1/6 chance of 1 rad per hit. Which type do you wish to toggle?}
{280}{}{Number of times can upgrade Plasma Rifle and Power Armor?}
{281}{}{Items received at start of game}
{282}{}{Srta. Stapleton}
{283}{}{Killian}
{284}{}{Misil Explosivo}
{285}{}{Armadura}
{286}{}{Holodisk}
{287}{}{Swap knockback/no-knockback on Sledgehammers}
{288}{}{Settings for specific traders/merchants}
{289}{}{Military Base red forcefields - who do they damage?}
{290}{}{6  Arenas Sombrías,  Base Militar}
{291}{}{Can hired NPCs level up at all?}
{292}{}{How many player levels per NPC levelup?}
{293}{}{Is levelup tracking relative or absolute?}
{294}{}{After joining the player's team, can Ian/Tycho/Katja gain levels? (Currently they }
{295}{}{Puedo.}
{296}{}{cannot.)}
{297}{}{ Vanilla default: hired NPCs did not gain levels.}
{298}{}{[1]}
{299}{}{[2]}
{300}{}{[3]}
{301}{}{[4]}
{302}{}{[5]}
{303}{}{[6]}
{304}{}{[7]}
{305}{}{[8]}
{306}{}{How many player levels does it take to trigger a hireling levelup?. (Currently it takes }
{307}{}{ player level for an NPC to gain one level.)  NPC Mod default: 4.}
{308}{}{ player levels for an NPC to gain one level.)  NPC Mod default: 4.}
{309}{}{When hirelings join your team, should they immediately levelup to be what they would if you'd gotten them at level 1?  (Currently they }
{310}{}{do.)  NPC Mod default: Do not.}
{311}{}{do not.)  NPC Mod default: Do not.}
{312}{}{}
{313}{}{}
{314}{}{}
{315}{}{}
{316}{}{}
{317}{}{}
{318}{}{Number of Turbo Plasma Rifle upgrades allowed?}
{319}{}{Number of Power Armor upgrades allowed?}
{320}{}{Player will be able to upgrade this many Plasma Rifles: }
{321}{}{Player will be able to upgrade this many Power Armors: }
{322}{}{. Select a new value if desired.  (Vanilla default: 1)}
{323}{}{To switch between standard and no-knockback version of sledgehammer items, choose an option below.}
{324}{}{Remove knockback from all Super Sledges in player's inventory.}
{325}{}{Remove knockback from all regular Sledgehammers in player's inventory.}
{326}{}{Add knockback to all Super Sledges in player's inventory.}
{327}{}{Add knockback to all regular Sledgehammers in player's inventory.}
{328}{}{una Unidad de Procesamiento de Aire}
{329}{}{}
{330}{}{}
{331}{}{}
{332}{}{}
{333}{}{}
{334}{}{}
{335}{}{}
{336}{}{}
{337}{}{}
{338}{}{}
{339}{}{}
{340}{}{}
{341}{}{}
{342}{}{}
{343}{}{}
{344}{}{}
{345}{}{}
{346}{}{}
{347}{}{}
{348}{}{}
{349}{}{}
{350}{}{}
{351}{}{}
{352}{}{}
{353}{}{}
{354}{}{}
{355}{}{}
{356}{}{}
{357}{}{}
{358}{}{}
{359}{}{}
{360}{}{}
{361}{}{}
{362}{}{}
{363}{}{}
{364}{}{}
{365}{}{}
{366}{}{}
{367}{}{}
{368}{}{}
{369}{}{}
{370}{}{}
{371}{}{}
{372}{}{}
{373}{}{}
{374}{}{}
{375}{}{}
{376}{}{}
{377}{}{}
{378}{}{}
{379}{}{}
{380}{}{}
{381}{}{}
{382}{}{}
{383}{}{}
{384}{}{}
{385}{}{}
{386}{}{}
{387}{}{}
{388}{}{}
{389}{}{}
{390}{}{}
{391}{}{}
{392}{}{}
{393}{}{}
{394}{}{}
{395}{}{}
{396}{}{}
{397}{}{}
{398}{}{}
{399}{}{}
{400}{}{}
{401}{}{}
{402}{}{}
{403}{}{}
{404}{}{}
{405}{}{}
{1000}{}{Has hackeado al ordenador.}
{1001}{}{Ummm... me pregunto que cambiará esta opción}
