{100}{}{Voici Butch.}
{101}{}{Parle-moi de toi.}
{102}{}{T'as entendu des rumeurs intéressantes ?}
{103}{}{Qu'est-ce qu'il y a aux alentours, à part le Centre ?}
{104}{}{Qu'est-ce qu'on trouve au Centre ?}
{105}{}{Merci, ça ira.}
{106}{BUTCH01}{What do you want?}
{107}{}{Te poser quelques questions.}
{108}{}{Rien, merci.}
{109}{BUTCH02}{Le temps, c'est de l'argent. Le bavardage, du gaspillage. T'es ici pour le boulot ou pour autre chose ?}
{110}{}{Oui.}
{111}{}{Quel boulot ?}
{112}{}{T'es là pour l'argent ou pour aut'chose ?}
{113}{BUTCH03}{Bon sang, enfin quelqu'un qui a des tripes ! Marché conclu. Adresse-toi à mon second, Rutger. Il va te mettre au parfum.}
{114}{}{Minute ! D'abord quelques questions sur ce boulot !}
{115}{}{Ok, merci.}
{116}{BUTCH04}{Ah, va pas tout gâcher ! Parle. Et vite !}
{117}{}{Combien ça paie ?}
{118}{}{Euh... ça consiste en quoi, ce boulot ?}
{119}{}{Ah, si tu le prends comme ça, je m'en vais parler à Rutger.}
{120}{BUTCH05}{Hmm...Rutger va s'en occuper. Il règle tous les trucs pratiques pour les Marchands du Lointain. Maintenant, remue-toi, j'ai pas que ça à faire !}
{121}{}{Encore une question, d'accord ?}
{122}{}{Ok, merci.}
{123}{BUTCH06}{Une seule.}
{124}{}{ [Il paraît tendu.]}
{125}{}{Euh... ça consiste en quoi, ce boulot ?}
{126}{}{Y'a une date limite pour ce boulot ?}
{127}{}{Euh, combien ça paie déjà ?}
{128}{}{Es-tu aussi idiot que t'en as l'air ?}
{129}{}{T'as l'air nerveux. Quelque chose qui va pas ?}
{130}{BUTCH07}{Qu'est-ce qui... enfin, t'acceptes un boulot sans savoir ? Bon dieu, tu dois être aux abois. Ca me va !}
{131}{}{Dis-moi juste de quoi il s'agit, d'accord ?}
{132}{}{Ben, toi aussi, t'as l'air plutôt aux abois. On est à égalité.}
{133}{BUTCH08}{Eh bien, on a des caravanes qu'ont disparu récemment. Ce qu'a bien pu leur arriver, personne est fichu de le savoir.}
{134}{}{Bon, qu'est-ce que t'attends de moi ?}
{135}{}{Je parie que tu les as même pas cherchées.}
{136}{BUTCH09}{C'est simple. Trouver et venir me dire qui est le coupable. Ou t'en débarrasser. L'un ou l'autre, je m'en fous. Tant que le boulot est fait !}
{137}{}{Des indices, des soupçons ?}
{138}{}{Je m'en débarrasserai.}
{139}{}{Ca m'a l'air glauque... Je préfère m'en aller.}
{140}{BUTCH10}{Bah. Rien de sensationnel.}
{141}{}{Allez. Il doit bien y avoir un ou deux trucs intéressants.}
{142}{butch11}{Ecoute, je vais pas m'éterniser en bavardages.}
{143}{butch12}{Ben, y'a peut-être... quelque chose... mais je me fie jamais aux racontars.}
{144}{}{Moi, si. De quoi s'agit-il ?}
{145}{}{Ok, merci.}
{146}{BUTCH13}{Tu... tu tiens vraiment à le savoir ? Ben, on dit que ce serait le Griffemort, mais... mais moi, j'en sais pas plus.}
{147}{}{On dirait que ça t'angoisse.}
{148}{}{Merci. Je peux te poser quelques questions ?}
{149}{}{Comment je peux en savoir plus sur le Griffemort ?}
{150}{butch13a}{Comment tu... Va voir Beth, elle en sait plus long sur toutes ces conneries.}
{151}{}{Ouais, t'as l'air de trembler dans ta culotte.}
{152}{}{Je vais jeter un œil.}
{153}{}{J'ai besoin d'en savoir plus.}
{154}{BUTCH14}{Ecoute, j'ai pas peur. Je suis... prudent. Qui le serait pas, avec le Griffemort. Va voir Beth, elle t'expliquera.}
{155}{}{T'as l'air de trembler dans ta culotte.}
{156}{}{P-p-pardon. Je vais jeter un œil.}
{157}{}{J'ai besoin d'en savoir plus.}
{158}{BUTCH15}{J'en ai marre de tes insultes... face de rat ! Ne remets pas les pieds ici ! Rutger, éjecte-moi cette punaise !}
{159}{BUTCH16}{Marché conclu. Maintenant, tire-toi, et reviens me voir quand t'as du neuf.}
{160}{BUTCH17}{Fais vite.}
{161}{BUTCH18}{Mais bon dieu, pourquoi je perds mon temps avec toi ! Casse-toi !}
{162}{butch19}{Uh... what did you say?}
{163}{}{Je laissais entendre que t'as trop la frousse pour chercher toi-même.}
{164}{}{Rien. Alors, qu'est-ce que t'attends de moi ?}
{165}{BUTCH20}{Tu sais, tu me reviens pas. Mais peu importe. Tu veux le boulot, oui ou merde ?}
{166}{}{Bien sûr.}
{167}{}{Non, merci.}
{168}{BUTCH19}{Uh... what did you say?}
{169}{}{T'as parfaitement entendu.}
{170}{}{Rien. Alors, qu'est-ce que t'attends de moi ?}
{171}{BUTCH22}{Ouais, hier ! Grouille-toi !}
{172}{BUTCH23}{Hmm. Pourquoi donc que ça t'intéresse ?}
{173}{}{Simple curiosité.}
{174}{}{Comme ça.}
{175}{}{T'occupe. J'ai encore des questions.}
{176}{BUTCH24}{Eh bien, ça fait à peu près cinq ans que je dirige les Marchands du Lointain. Avant, j'étais au Sanctuaire. Avant ça, près du Rayon.}
{177}{}{Et avec ça ?}
{178}{}{Bien, merci.}
{179}{BUTCH25}{Not really.}
{180}{BUTCH26}{Ah, j'aime pas bien m'étendre sur ma vie privée.}
{181}{}{Oh, allez, s'il te plaît !}
{182}{}{Bon, d'accord.}
{183}{BUTCH27}{Quoi, mais est-ce que j'ai l'air de... d'un de ces touristes ?! Merde alors !}
{184}{}{Non, d'un mec génial.}
{185}{}{Je veux juste connaître quelques endroits.}
{186}{BUTCH28}{Merci. Encore autre chose ?}
{187}{BUTCH29}{Ben, t'as la Vieille Ville et les Hauteurs, mais y'a juste des baraques. Au centre-ville, on trouve tous les magasins qu'on veut.}
{188}{}{Quel genre de magasins ?}
{189}{}{Merci.}
{190}{BUTCH30}{Ah, y'a de tout. Va donc voir par toi-même !}
{191}{}{Bien, merci quand même.}
{192}{}{Merci.}
{193}{BUTCH19}{Uh... what did you say?}
{194}{}{T'es sourd ou quoi ?}
{195}{}{Rien. Mais, je voudrais te poser encore quelques questions.}
{196}{BUTCH32}{Eh bien, t'as le Faucon Maltais, et là, on mange bien, tu peux me croire. Quoi d'autre... le Grand Bazar, l'Armurerie... et, bien sûr, A l'Iguane Rôti, chez Bob.}
{197}{}{Merci.}
{198}{}{Et avec ça ?}
{199}{BUTCH33}{Y'a l'hôpital des Enfants de la Cathédrale, à l'Ouest du centre-ville. Et puis, bien sûr, les Marchands d'Eau au Sud, et la Caravane Ecarlate à l'Ouest.}
{200}{}{Merci.}
{201}{BUTCH34}{Voyons voir, t'as Dépôtville au Nord, et la Confrérie de l'Acier au Nord-Ouest. Et, bien sûr, le Cimetière au Sud.}
{202}{}{Et avec ça ?}
{203}{}{Merci.}
{204}{BUTCH35}{Euh, Nécropolis, à l'Est. Mais, euh... J'irais pas traîner mes guêtres par là pour tout l'or du monde, si tu veux mon avis. Ces Goules, t'as pas le temps de les voir qu'ils t'ont déjà bouffé la tête.}
{205}{}{Ca m'a l'air réjouissant.}
{206}{BUTCH35a}{Pouah. Parle pour toi ! Si ça te plaît, t'as le Rayon, plus au Sud. C'est un puits radioactif.}
{207}{}{C'est peut-être bon pour mon bronzage.}
{208}{BUTCH36}{Oh, encore deux ou trois endroits. Va donc voir toi-même !}
{209}{}{Bien, merci quand même.}
{210}{}{Merci.}
{211}{BUTCH37}{Alors, qu'est-ce que t'apportes ?}
{212}{}{Eh bien, j'ai trouvé qui fait disparaître les caravanes.}
{213}{}{Eh bien, c'est pas le Griffemort qui a pris les caravanes.}
{214}{}{Rien pour l'instant. Salut.}
{215}{BUTCH38}{Vraiment ? Qui ?}
{216}{}{Ces espèces de grands mutants.}
{217}{}{Des rats ! Des GROS rats avec des GRANDES dents...}
{218}{BUTCH39}{Que... qu'est-ce que cherchent les mutants avec nos caravanes ?}
{219}{}{Je sais pas, mais on dirait qu'ils capturent les humains.}
{220}{}{Rien de sûr. Mais c'est les mutants, pas le Griffemort.}
{221}{BUTCH40}{Quoi, est-ce que j'ai l'air d'une mauviette ? As-tu seulement vu le Griffemort ?}
{222}{}{J'étais là, je l'ai vu, je l'ai tué.}
{223}{}{Je te le dis, c'est pas le Griffemort.}
{224}{BUTCH41}{Tu... tu l'as tué ? Alors... euh, hmm... d'où viennent ces mutants ?}
{225}{}{Ils viennent du Nord-Ouest. Je pense qu'ils doivent avoir une sorte de base militaire là-bas.}
{226}{}{Ils travaillent pour le Maître. C'est pas des mutants ordinaires.}
{227}{BUTCH42}{Un avant-poste ? Hmm.... Faut que je parle au Comité. Ouais, c'est ça... ils sauront quoi faire. C'est bon. File, j'ai à faire... D'accord ?}
{228}{BUTCH43}{Le Maître ? Ah, certainement plus un mythe que le Griffemort. Tu... tu penses pas qu'il existe vraiment, si ?}
{229}{}{Je sais pas trop. Mais j'ai bien l'intention de le savoir.}
{230}{}{Ouais, je l'ai vu ! Et il vient pour te faire ta fête !}
{231}{BUTCH44}{Ouais, ok... Ouais, vas-y ! Euh, faut que je parle au Comité. Ils sauront quoi faire. Maintenant, file ! J'ai pas que ça à faire... D'accord ?}
{232}{BUTCH45}{Quoi ! Heu... j'ai pas peur ! Rutger ! J'ai des armes ! Rutger !}
{233}{BUTCH46}{D'accord, c'était pas le Griffemort. Mais qu'est-ce que les mutants fabriqueraient à la Vieille Ville avec nos caravanes ? A moins... peut-être une machination.}
{234}{}{Mais non, pauvre cloche ! Ces mutants sont grands et verts, et ils ont une armée dans les montagnes, vers le Nord.}
{235}{}{T'es vraiment borné ou quoi ? T'écoutes pas !}
{236}{BUTCH47}{Quoi ? Tire-toi ! Faut que j'en parle au Comité. Allez, tire-toi !}
{237}{BUTCH48}{Allez. Je suis sûr que tu peux faire mieux.}
{238}{}{Non, vraiment. Il s'agit bien de ces espèces de grands mutants verts.}
{239}{}{T'as raison.}
{240}{}{Oh, allons. Tu crois qu'une femme comme moi mentirait ?}
{241}{BUTCH49}{J'ai pas de temps à perdre. Tire-toi et reviens quand t'auras quelque chose d'intéressant à me dire !}
{242}{BUTCH50}{Alors, qu'est-ce que c'est ?}
{243}{}{En fait, c'est bien ces espèces de grands mutants...}
{244}{}{Des rats, je te dis ! Enormes, velus...}
{245}{BUTCH51}{Des rats ? Tu te fous de moi.}
{246}{}{Non, vraiment. Des GROS rats !}
{247}{}{C'est vrai. Je me foutais de toi.}
{248}{BUTCH52}{Bon... d'accord. Je vais en parler au Comité, mais ça m'étonnerait qu'ils me croient. C'est pourtant vrai, j'ai vu des rats rudement gros dans le coin...}
{249}{BUTCH53}{Comment le sais-tu ? T'as vu le Griffemort ?}
{250}{}{J'étais là, je l'ai vu, je l'ai tué.}
{251}{}{Fais-moi confiance. Je sais.}
{252}{BUTCH54}{Tu... tu l'as tué ?}
{253}{}{Oui.}
{254}{BUTCH54a}{Mais, mais alors qui vole mes caravanes ?}
{255}{}{Je sais pas encore, mais je trouverai.}
{256}{}{C'est Ralph.}
{257}{BUTCH55}{Uhh, do that. And come back and tell me... okay?}
{258}{BUTCH56}{Qui c'est encore, ce Ralph ?}
{259}{}{T'occupe. Je trouverai d'autres infos sur l'affaire des caravanes.}
{260}{}{Il vient voler ton âme !}
{261}{BUTCH57}{Ah ! Tu me fais tourner en bourrique, non ? Rutger, fous-moi ce parasite dehors ! Et ne reviens pas sans de vraies informations !}
{262}{BUTCH58}{Ouais. Comme si j'allais gober ça ! File jusqu'à ce que tu me trouves quelque chose d'intéressant !}
{263}{BUTCH59}{Eh bien, les nouvelles ?}
{264}{}{C'étaient les Mutants.}
{265}{}{Eh bien, c'est pas le Griffemort qui a pris les caravanes.}
{266}{BUTCH60}{La paix ! T'as eu ta récompense, maintenant, file !}
{267}{BUTCH61}{Ca va pas, pose ça !}
{268}{BUTCH62}{Je vois. Rutger va te faire avaler ton bulletin de naissance !}
{269}{BUTCH63}{Arrête ça immédiatement !}
{270}{BUTCH64}{Eh, qu'est-ce que tu fous là ! Dehors !}
{272}{butch65}{Oh... je vois, fous-moi le camp !}
{273}{BUTCH66}{Rutger va te transformer en chair à pâté... Amuse-toi bien ! RUTGER !}
{274}{BUTCH67}{Bon, t'es quelqu'un d'intelligent, non ? Le boulot, c'est ça : trouver qui vole mes caravanes. Tu réussis, du fric... beaucoup. Tu rates, des coups... beaucoup. Compris ? Maintenant, file !}
{275}{BUTCH67a}{Waouh, pauvre de toi ! J'ai pas de temps à perdre. Adresse-toi à Rutger.}
{276}{BUTCH68}{Adresse-toi à Rutger.}
{277}{BUTCH69}{Like I told you...}
{278}{BUTCH70a}{As I said...}
{279}{BUTCH71}{Je vais pas me répéter !}
{280}{BUTCH72}{Ecoute, je vais pas me répéter.}
{281}{BUTCH73}{C'est le proprio du Faucon Maltais, à l'Ouest. A ta place, je m'y frotterais pas, c'est pas un mec honnête, comme moi.}
{282}{BUTCH74}{Euh, non, non... On parle pas de ça.}
{283}{BUTCH75}{Ah, tu... non, faut pas aller là. C'est vraiment hors de prix et pas fameux.}
{284}{BUTCH76}{Quelle chienlit ! On pense qu'ils ont leur planque dans la Vieille Ville, mais aucune preuve.}
{285}{BUTCH77}{Oh, he's the sheriff. But if you see a crime, report to me. Justin doesn't rule the roost around here.}
{286}{BUTCH78}{Harold l'Ancien ? Qu'est-ce que tu veux à ce vieux mutant ? Il est à la Vieille Ville. Une fois là-bas, tu demandes.}
{287}{BUTCH79}{Le temps, c'est de l'argent. Le bavardage, du gaspillage. T'es ici pour le boulot ou pour autre chose ?}
{288}{BUTCH80}{Adresse-toi à Rutger. Il t'en dira plus.}
{289}{BUTCH81}{You can find them over on the northwest edge of Downtown. They controlled the hospital before the Children moved in. Talk about trading the strange for the weird.}
{290}{BUTCH82}{C'est le chef de la Caravane Ecarlate. A mon avis, un cinglé.}
{291}{BUTCH83}{Don't you know where your own feet are?}
{292}{BUTCH84}{Oh, ils ont la gâchette facile là-bas, dans le Nord-Ouest. Plutôt inquiétants. Mais faut reconnaître qu'ils fabriquent de la belle artillerie.}
{293}{BUTCH85}{Euh, Beth est la patronne de l'Armurerie. Elle connaît tous les racontars, si c'est ça qui t'intéresse.}
{294}{BUTCH86}{Rutger est mon assistant.}
{295}{BUTCH87}{It's south of the Merchant Market. The only source of water here and for a lot of the surrounding area. The Water Merchants own the damn thing.}
{296}{BUTCH88}{Three of my caravans have disappeared in the past month. At first I thought it was either the Water Merchants or the Crimson Caravan, but they've had disappearances too.}
{297}{BUTCH89}{C'est là où tout le monde fait du troc. En plein milieu de la ville.}
{298}{BUTCH90}{Uh, no I-I don't... Go talk to Beth, she knows more about that crap.}
{299}{BUTCH91}{The Glow is a radioactive pit way, way down south. Too much radiation for anyone to live there.}
{300}{BUTCH92}{Old Town's over on the east side. The skags hang out there.}
{301}{butch93}{It's over on the west side.}
{302}{BUTCH94}{Junktown? Yeah, I've been up north to that place a few times. Got some great booze.}
{303}{BUTCH95}{Dépôtville ? Vers le Nord. J'ai entendu dire qu'ils ont des ennuis... leur maire, Killian, qui s'est fait descendre...}
{304}{BUTCH96}{He's the mayor of Junktown, that's all I know.}
{305}{BUTCH97}{J'ai entendu dire qu'il est mort. Qu'est-ce que tu veux savoir de plus ?}
{306}{BUTCH98}{Oh, they're a bunch of gun freaks up to the northwest. Really weird. They do make a damn fine weapon, though.}
{307}{BUTCH99}{He leads the Brotherhood. It's about all I know.}
{308}{BUTCH100}{Well, it's a big ruined city to the south. The Children, the Followers and Adytum are there, along with all the gangs and stuff.}
{309}{BUTCH101}{Pourquoi ? Qu'est-ce qu'on t'a dit ? Il paraît qu'on l'a mise à sac. Mais qui ? Personne le sait. Oh, je suis pas inquiet. Le Centre est imprenable.}
{310}{BUTCH102}{Ah, c'est là que tout le monde va faire du commerce, dans le Cimetière. Le seul endroit assez civilisé pour ça.}
{311}{BUTCH103}{Last I heard, he's the mayor of Adytum.}
{312}{BUTCH104}{Ah, ils dirigent un vieil hôpital assez grand, au Sud du centre-ville. Une bande de culs-bénits cinglés, si tu veux mon avis.}
{313}{BUTCH105}{Il est à la tête des Enfants de la Cathédrale, là-bas au Cimetière de L.A.}
{314}{BUTCH105a}{Jain est la Grande Prêtresse des Enfants de la Cathédrale. Elle a installé l'hôpital dans le Centre.}
{315}{BUTCH106}{Euh, oui, je... j'ai entendu des histoires, c'est tout. Mais rien de vrai.}
{316}{BUTCH107}{Best prices on the best guns in town. Everyone says so, it's not just that I own it! Just trot out this door and make a right. You can't miss it.}
{317}{BUTCH108}{Now there's some good eating. Bob's has got the best charred iguana this side of the desert.}
{318}{BUTCH109}{Well, you... uh... you don't want to go there. The prices are really high and the quality's bad.}
{319}{BUTCH110}{What do you want with them wackos? Jeez, all that peace preaching and tree hugging. Makes me sick.}
{320}{BUTCH111}{Jamais entendu parler de ça.}
{321}{BUTCH112}{Euh, bah... j'préfère pas t'en parler. Non, vraiment.}
{322}{BUTCH113}{Jamais entendu parler de ça. C'est toi qu'invente ça, non ?}
{323}{BUTCH114}{Ah, aux dernières nouvelles, ça avait été saccagé. Par qui ? J'en sais rien.}
{324}{}{J'ai à faire. Va parler à Rutger. Il me dira ce que tu vaux.}
{325}{}{Je n'ai rien à te dire.}
{326}{}{Où est ma récompense ?}
{327}{}{C'était quoi déjà ma mission ?}
{328}{}{Fous le camp !}
{329}{}{Rien pour l'instant.}
{330}{}{Grr... !!}
{331}{}{Hors de ma vue... pauv' tâche !}
{332}{}{Loin au Nord-Ouest, il y a une base militaire fortifiée. C'est pas des mutants ordinaires. Ils sont énormes et lourdement armés. Ils obéissent à un barjot qui s'appelle le Maître. Ils sont organisés et c'est eux qui ont enlevé les caravanes et leurs employés.}
{333}{}{Loin au Nord-Ouest, il y a une base militaire fortifiée. C'est pas des mutants ordinaires. Ils sont énormes et lourdement armés.}
{334}{}{Loin au Nord-Ouest. Il y a une sorte de base militaire. Ils obéissent à un barjot qui s'appelle le Maître. Ils sont organisés et c'est eux qui ont enlevé les caravanes et leurs employés.}
{335}{}{Loin au Nord-Ouest. Il y a une sorte de base militaire.}
{336}{}{Ils viennent du Nord-Ouest. Ils obéissent à un barjot qui s'appelle le Maître. Ils sont organisés et c'est eux qui ont enlevé les caravanes et leurs employés.}
{337}{}{Ils viennent du Nord-Ouest. Je pense qu'ils doivent avoir une sorte de base militaire là-bas.}
{338}{}{Je sais pas encore, mais ils obéissent à un barjot qui s'appelle le Maître. Ils sont organisés et c'est eux qui ont enlevé les caravanes et leurs employés.}
{339}{}{Je sais pas encore, mais il y avait un gros mutant tout vert dans un grotte près de la ville, il radotait à propos d'une mission pour son "Maître".}
{340}{}{Je sais pas encore, mais j'ai trouvé cet étrange disque sur un gros mutant qui a parlé de son "Maître".}
{341}{}{Non, non, non, espèce d'andouille. Ces mutants-là sont grands et verts, et ils viennent d'une base militaire fortifiée au Nord-Ouest. C'est pas des mutants ordinaires. Ils sont énormes et lourdement armés. Ils travaillent pour un barjot qui s'appelle le Maître. Ils sont organisés et c'est eux qui ont enlevé les caravanes et leurs employés.}
{342}{}{Non, non, non, espèce d'andouille. Ces mutants-là sont grands et verts, et ils viennent d'une base militaire fortifiée au Nord-Ouest. C'est pas des mutants ordinaires. Ils sont énormes et lourdement armés.}
{343}{}{Non, non, non, espèce d'andouille. Ces mutants-là sont grands et verts, et ils viennent du Nord-Ouest. Ils ont une sorte de base militaire. Ils travaillent pour un barjot qui s'appelle Le Maître. Ils sont organisés et c'est eux qui ont enlevé les caravanes et leurs employés.}
{344}{}{Non, non, non, espèce d'andouille. Ces mutants-là sont grands et verts, et ils viennent du Nord-Ouest. Ils ont une sorte de base militaire.}
{345}{}{Non, non, non, espèce d'andouille. Ces mutants-là sont grands et verts, et ils viennent du Nord-Ouest. Ils travaillent pour un barjot qui s'appelle le Maître. Ils sont organisés et c'est eux qui ont enlevé les caravanes et leurs employés.}
{346}{}{Non, non, non, espèce d'andouille. Ces mutants-là sont grands et verts, et ils viennent du Nord-Ouest. Je pense qu'ils doivent avoir une sorte de base militaire là-bas.}
{347}{}{Non, non, non, espèce d'andouille. Ces mutants-là sont grands et verts, et ils travaillent pour un barjot qui s'appelle le Maître. Ils sont organisés et c'est eux qui ont enlevé les caravanes et leurs employés.}
{348}{}{Non, non, non, espèce d'andouille. Ces mutants-là sont grands et verts. Il y en avait un dans une grotte près de la ville, qui radotait à propos d'une mission pour son "Maître".}
{349}{}{Non, non, non, espèce d'andouille. Ces mutants-là sont grands et verts. J'ai trouvé cet étrange disque sur un gros mutant tout vert qui radotait à propos d'une mission pour son "Maître".}
{500}{BUTCH55a}{Uhh, do that. And come back and tell me... okay?}
{501}{butch63a}{Eh ! Ca suffit comme ça !}
{502}{BUTCH69a}{Like I told you...}
{503}{BUTCH70b}{As I said...}
{504}{BUTCH105b}{Je vois pas du tout de quoi tu parles.}
{980}{BUTCH111}{Jamais entendu parler de ça.}
{981}{BUTCH112}{Euh, bah... j'préfère pas t'en parler. Non, vraiment.}
{982}{BUTCH113}{Jamais entendu parler de ça. C'est toi qu'invente ça, non ?}
{1000}{}{Decker}
{1001}{}{Underground}
{1002}{}{Maltais|Faucon Maltais|Faucon}
{1003}{}{Voleurs|Voleur|Voleuse|Voleuses}
{1004}{}{Justin}
{1005}{}{Harold}
{1006}{}{Marchands|Marchand}
{1007}{}{Daren}
{1008}{}{Caravane écarlate}
{1009}{}{Demetre}
{1010}{}{Lointain}
{1011}{}{Butch}
{1012}{}{Beth}
{1013}{}{Rutger}
{1014}{}{Eau}
{1015}{}{Caravanes}
{1016}{}{Marché}
{1017}{}{Griffemort|Griffes|Griffe|Griffemorts}
{1018}{}{Rayon}
{1019}{}{Ville}
{1020}{}{Hauteurs}
{1021}{}{Dépôtville}
{1022}{}{Killian}
{1023}{}{Confrérie de l'Acier|Confrérie|Confrerie|Acier}
{1024}{}{Elder}
{1025}{}{Cimetière|Le Cimetière|Cimetière de L.A.|Los Angeles}
{1026}{}{Adytum}
{1027}{}{Jon}
{1028}{}{Cathedral}
{1029}{}{Morpheus}
{1030}{}{Jain}
{1031}{}{Maître}
{1032}{}{Weapon}
{1033}{}{Bob}
{1034}{}{Magasin|Général|Magasin Général}
{1035}{}{Followers}
{1036}{}{Harris}
{1037}{}{Maltais}
{1038}{}{Nightclub}
{1039}{}{Merchant}
{1040}{}{Hightower}
{1041}{}{Greene}
{1042}{}{Ecarlate}
{1043}{}{Romara}
{1044}{}{Marchands}
{1045}{}{Tower}
{1046}{}{Caravanes}
{1047}{}{Darkwater}
{1048}{}{Acier}
{1049}{}{Les Eventreurs|Eventreurs|Eventreur}
{1050}{}{Cimetière de L.A.}
{1051}{}{Zimmerman}
{1052}{}{Weapons}
{1053}{}{Magasin}
{1054}{}{guns}
{1055}{}{Chez Bob}
{1056}{}{A l'Iguane}
{1057}{}{Apocalypse}
{1058}{}{Death}
{1059}{}{Deathclaw}
{1060}{}{Zone rouge}
{1061}{}{Old Town}
{1062}{}{Vieille}
{1063}{}{Maxson}
{1064}{}{Bazar}
{1065}{}{Junk}
{1066}{}{Cimetière|Le Cimetière|Cimetière de L.A.|Los Angeles}
{1067}{}{L.A. Boneyard}
{1100}{BUTCH73}{C'est le proprio du Faucon Maltais, à l'Ouest. A ta place, je m'y frotterais pas, c'est pas un mec honnête, comme moi.}
{1101}{BUTCH74}{Euh, non, non... On parle pas de ça.}
{1102}{BUTCH75}{Ah, tu... non, faut pas aller là. C'est vraiment hors de prix et pas fameux.}
{1103}{BUTCH76}{Quelle chienlit ! On pense qu'ils ont leur planque dans la Vieille Ville, mais aucune preuve.}
{1104}{BUTCH77}{Oh, he's the sheriff. But if you see a crime, report to me. Justin doesn't rule the roost around here.}
{1105}{BUTCH78}{Harold l'Ancien ? Qu'est-ce que tu veux à ce vieux mutant ? Il est à la Vieille Ville. Une fois là-bas, tu demandes.}
{1106}{BUTCH79}{Le temps, c'est de l'argent. Le bavardage, du gaspillage. T'es ici pour le boulot ou pour autre chose ?}
{1107}{BUTCH80}{Adresse-toi à Rutger. Il t'en dira plus.}
{1108}{BUTCH81}{You can find them over on the northwest edge of Downtown. They controlled the hospital before the Children moved in. Talk about trading the strange for the weird.}
{1109}{BUTCH82}{C'est le chef de la Caravane Ecarlate. A mon avis, un cinglé.}
{1110}{BUTCH83}{Don't you know where your own feet are?}
{1111}{BUTCH84}{Oh, ils ont la gâchette facile là-bas, dans le Nord-Ouest. Plutôt inquiétants. Mais faut reconnaître qu'ils fabriquent de la belle artillerie.}
{1112}{BUTCH85}{Euh, Beth est la patronne de l'Armurerie. Elle connaît tous les racontars, si c'est ça qui t'intéresse.}
{1113}{BUTCH86}{Rutger est mon assistant.}
{1114}{BUTCH87}{It's south of the Merchant Market. The only source of water here and for a lot of the surrounding area. The Water Merchants own the damn thing.}
{1115}{BUTCH88}{Three of my caravans have disappeared in the past month. At first I thought it was either the Water Merchants or the Crimson Caravan, but they've had disappearances too.}
{1116}{BUTCH89}{C'est là où tout le monde fait du troc. En plein milieu de la ville.}
{1117}{BUTCH90}{Uh, no I-I don't... Go talk to Beth, she knows more about that crap.}
{1118}{BUTCH91}{The Glow is a radioactive pit way, way down south. Too much radiation for anyone to live there.}
{1119}{BUTCH92}{Old Town's over on the east side. The skags hang out there.}
{1120}{BUTCH93}{It's over on the west side.}
{1121}{BUTCH94}{Junktown? Yeah, I've been up north to that place a few times. Got some great booze.}
{1122}{BUTCH96}{He's the mayor of Junktown, that's all I know.}
{1123}{BUTCH98}{Oh, they're a bunch of gun freaks up to the northwest. Really weird. They do make a damn fine weapon, though.}
{1124}{BUTCH99}{He leads the Brotherhood. It's about all I know.}
{1125}{BUTCH100}{Well, it's a big ruined city to the south. The Children, the Followers and Adytum are there, along with all the gangs and stuff.}
{1126}{BUTCH102}{Ah, c'est là que tout le monde va faire du commerce, dans le Cimetière. Le seul endroit assez civilisé pour ça.}
{1127}{BUTCH103}{Last I heard, he's the mayor of Adytum.}
{1128}{BUTCH104}{Ah, ils dirigent un vieil hôpital assez grand, au Sud du centre-ville. Une bande de culs-bénits cinglés, si tu veux mon avis.}
{1129}{BUTCH105}{Il est à la tête des Enfants de la Cathédrale, là-bas au Cimetière de L.A.}
{1130}{BUTCH105a}{Jain est la Grande Prêtresse des Enfants de la Cathédrale. Elle a installé l'hôpital dans le Centre.}
{1131}{BUTCH106}{Euh, oui, je... j'ai entendu des histoires, c'est tout. Mais rien de vrai.}
{1132}{BUTCH107}{Best prices on the best guns in town. Everyone says so, it's not just that I own it! Just trot out this door and make a right. You can't miss it.}
{1133}{BUTCH108}{Now there's some good eating. Bob's has got the best charred iguana this side of the desert.}
{1134}{BUTCH109}{Well, you... uh... you don't want to go there. The prices are really high and the quality's bad.}
{1135}{BUTCH110}{What do you want with them wackos? Jeez, all that peace preaching and tree hugging. Makes me sick.}
{1136}{BUTCH84}{Oh, ils ont la gâchette facile là-bas, dans le Nord-Ouest. Plutôt inquiétants. Mais faut reconnaître qu'ils fabriquent de la belle artillerie.}
{1137}{BUTCH75}{Ah, tu... non, faut pas aller là. C'est vraiment hors de prix et pas fameux.}
{1138}{BUTCH75}{Ah, tu... non, faut pas aller là. C'est vraiment hors de prix et pas fameux.}
{1139}{BUTCH79}{Le temps, c'est de l'argent. Le bavardage, du gaspillage. T'es ici pour le boulot ou pour autre chose ?}
{1140}{BUTCH80}{Adresse-toi à Rutger. Il t'en dira plus.}
{1141}{BUTCH77}{Oh, he's the sheriff. But if you see a crime, report to me. Justin doesn't rule the roost around here.}
{1142}{BUTCH81}{You can find them over on the northwest edge of Downtown. They controlled the hospital before the Children moved in. Talk about trading the strange for the weird.}
{1143}{BUTCH82}{He's the boss of the Crimson Caravan. If you ask me he's nuts.}
{1144}{BUTCH83}{Don't you know where your own feet are?}
{1145}{BUTCH87}{It's south of the Merchant Market. The only source of water here and for a lot of the surrounding area. The Water Merchants own the damn thing.}
{1146}{BUTCH88}{Three of my caravans have disappeared in the past month. At first I thought it was either the Water Merchants or the Crimson Caravan, but they've had disappearances too.}
{1147}{BUTCH96}{He's the mayor of Junktown, that's all I know.}
{1148}{BUTCH98}{Oh, they're a bunch of gun freaks up to the northwest. Really weird. They do make a damn fine weapon, though.}
{1149}{BUTCH100}{Well, it's a big ruined city to the south. The Children, the Followers and Adytum are there, along with all the gangs and stuff.}
{1150}{BUTCH100}{Well, it's a big ruined city to the south. The Children, the Followers and Adytum are there, along with all the gangs and stuff.}
{1151}{BUTCH103}{Last I heard, he's the mayor of Adytum.}
{1152}{BUTCH107}{Best prices on the best guns in town. Everyone says so, it's not just that I own it! Just trot out this door and make a right. You can't miss it.}
{1153}{BUTCH107}{Best prices on the best guns in town. Everyone says so, it's not just that I own it! Just trot out this door and make a right. You can't miss it.}
{1154}{BUTCH107}{Best prices on the best guns in town. Everyone says so, it's not just that I own it! Just trot out this door and make a right. You can't miss it.}
{1155}{BUTCH108}{Now there's some good eating. Bob's has got the best charred iguana this side of the desert.}
{1156}{BUTCH108}{Now there's some good eating. Bob's has got the best charred iguana this side of the desert.}
{1157}{BUTCH110}{What do you want with them wackos? Jeez, all that peace preaching and tree hugging. Makes me sick.}
{1158}{BUTCH90}{Uh, no I-I don't... Go talk to Beth, she knows more about that crap.}
{1159}{BUTCH90}{Uh, no I-I don't... Go talk to Beth, she knows more about that crap.}
{1160}{BUTCH91}{The Glow is a radioactive pit way, way down south. Too much radiation for anyone to live there.}
{1161}{BUTCH92}{Old Town's over on the east side. The skags hang out there.}
{1162}{BUTCH92}{Old Town's over on the east side. The skags hang out there.}
{1163}{BUTCH99}{He leads the Brotherhood. It's about all I know.}
{1164}{BUTCH109}{Well, you... uh... you don't want to go there. The prices are really high and the quality's bad.}
{1165}{BUTCH94}{Junktown? Yeah, I've been up north to that place a few times. Got some great booze.}
{1166}{BUTCH100}{Well, it's a big ruined city to the south. The Children, the Followers and Adytum are there, along with all the gangs and stuff.}
{1167}{BUTCH100}{Well, it's a big ruined city to the south. The Children, the Followers and Adytum are there, along with all the gangs and stuff.}
