{100}{}{Tu vois le conducteur de la Caravane des Marchands du Lointain.}
{101}{}{Salut, si tu cherches à bosser sur une caravane, adresse-toi à Rutger. Il est là-bas.}
{102}{}{Faut que tu causes à Rutger.}
{103}{}{Alors tu t'es engagé, content de l'apprendre ! Comme tu le sais, on part tous les dix jours : le 8, le 18 et le 28 de chaque mois. Là maintenant, on met le cap sur la Confrérie, Dépôtville et le Cimetière de L.A.}
{104}{}{Alors, quel est le salaire ?}
{105}{}{Hmm.}
{106}{}{400 caps. Tu trouves peut-être ça léger, mais on part souvent et y'a pas vraiment de risques. Ca, c'est pour l'aller, et tu ramasses 800 si tu fais aussi le retour.}
{107}{}{Y'a un départ aujourd'hui. Ca t'intéresse ?}
{108}{}{On part en }
{109}{}{Vide}
{110}{}{}
{111}{}{. Ca t'intéresse ?}
{112}{}{Je vais quand même te donner du travail, même si... tant pis. Ca t'intéresse ?}
{113}{}{Bien sûr.}
{114}{}{Non.}
{115}{}{Peut-être.}
{116}{}{Ouais ouais.}
{117}{}{Gné ?}
{118}{}{Pas de problème. Fais-moi savoir si tu changes d'avis.}
{119}{}{Bon, tu te décides ?}
{120}{}{Reviens si tu cherches toujours un boulot. C'est le 8, le 18 et le 28. Salut.}
{121}{}{Nan, ça le fera pas si tu sais même pas distinguer ta droite de ta gauche. Désolé.}
{122}{}{Reviens quand tu te sentiras mieux.}
{123}{}{T'as pas l'air dans ton assiette mec. Tu devrais te remplir l'estomac... évite seulement d'aller chez Bob.}
{124}{}{Fous-moi le camp !}
{125}{}{Peux-tu laisser mes affaires tranquilles ? Pourquoi tu fais ça ?}
{126}{}{Parce que je suis un petit homme vert qui vient de l'espace Et je suis méchant !}
{127}{}{Je n'en avais pas l'intention mais je meurs de faim et j'ai des enfants à nourrir.}
{128}{}{Je vais te découper le coeur avec une cuillère !}
{129}{}{[Reddition]}
{130}{}{[Attaque]}
{131}{}{Ah, tu m'craches à la figure, hein ? J'crois qu'le seul moyen de d'enfoncer ça dans ton crâne épais, c'est de le séparer de ton cou.}
{132}{}{Bon, mais ça change rien. Faut quand même que tu te barres.}
{133}{}{Tu crois que j'vais gober ces salades ? Gardes !}
{134}{}{Peut-être qu'un petit séjour dans la citerne t'apprendrait les bonnes manières. Alors, tu viens gentiment ou faut qu'on emploie les grands moyens ?}
{135}{}{On se retrouvera en enfer !}
{136}{}{Oui. Pardon.}
{137}{}{Alors comme ça, on joue les gros bras, hein ? On cherche encore la castagne ?}
{138}{}{Si tu sors pas de là, j'appelle les flics !}
{139}{}{Gardes ! Police !}
{140}{}{Je crois que tu devrais partir...}
{141}{}{Désolé, mais je vais pas t'offrir de boulot.}
{142}{}{Je pourrais t'offrir un boulot, mais ça arrivera pas.}
{143}{}{Décampe.}
{144}{}{C'est mignon, mais je suis pas vraiment ton genre.}
{145}{}{Bon d'accord ! Ca paiera 400 caps. Quel trajet tu préfères ?}
{146}{}{Ca fait plaisir à entendre. Reviens en }
{147}{}{le 8}
{148}{}{le 18}
{149}{}{le 28}
{150}{}{}
{151}{}{}
{152}{}{Confrérie de l'Acier }
{153}{}{. Tu prendras la route. Comme d'habitude, ça paiera 400 caps.}
{154}{}{D'accord.}
{155}{}{Excuse-moi, je ne peux pas attendre.}
{156}{}{Je sais pas bien ce qui est arrivé, mais toute la caravane a disparu. C'est pas bizarre qu'une chose pareille se produise, et que tu sois le seul à en réchapper ? C'est pas banal tout ça. Alors c'est simple, j'peux plus t'embaucher, je suis sûr que tu comprends ça.}
{157}{}{Dépôtville}
{158}{}{L.A. Boneyard}
{159}{}{Hmm, pas tout de suite. Peut-être une autre fois.}
{160}{}{Bonne nouvelle, je vais réunir les effectifs.}
{161}{}{Génial.}
{162}{}{File d'ici. Bonne chance !}
{163}{}{Essaie d'éviter les problèmes, ne va pas les chercher.}
{164}{}{Fais attention là-bas, le Cimetière de L.A. est pas un lieu des plus sûr...}
{165}{}{C'est bien. Ces routes noires sont étranges, mais elles sont parfaites pour circuler.}
{166}{}{Pas de doute, il y a quelque chose de mauvais par là. Fais attention à qui tu parles quand t'y seras}
{167}{}{Bien, Dépôtville est pas une ville désagréable.}
{168}{}{Oh, et arrête-toi chez Killian et passe lui le bonjour de ma part. On en a vécu de sacrés moments dans les caravanes.}
{169}{}{Il paraît qu'il y a un médecin bizarre là bas. Il s'occupe des macchabées, à ce qu'on dit.}
{170}{}{Bon dieu, qu'est-ce qui t'a pris de quitter la caravane. Elle est revenue entière, mais c'est un sacré coup de pot.}
{171}{}{Puis-je avoir une autre chance ?}
{172}{}{Rien.}
{173}{}{Merde !}
{174}{}{Roo Rrr heu ?}
{175}{}{Grr...}
{176}{}{T'as encore merdé. J'crois pas que t'es fait pour ce genre de boulot.}
{177}{}{Pourquoi ?}
{178}{}{Tu ne devrais pas.}
{179}{}{Parce que sinon je vais te trouer la cervelle.}
{180}{}{J'avais mieux à faire que de traîner avec cette stupide caravane.}
{181}{}{Je ne savais pas que je n'avais pas le droit de partir. Tout était en ordre.}
{182}{}{Je vois... tu as pris des stimulants. Eh bien, mène ta vie comme tu l'entends.}
{183}{}{Ca me fait de la peine que tu le prennes comme ça.}
{184}{}{Etonnant que tu l'as pas fait avant. En attendant, ça fera de tort à personne si je te donne une seconde chance.}
{185}{}{T'as fait du bon boulot. Je peux t'en proposer un autre. Ca t'intéresse ?}
{186}{}{Bien sûr.}
{187}{}{Non.}
{188}{}{Peut-être.}
{189}{}{Eh... !}
{190}{}{Euh...}
{191}{}{T'as tout ce qu'il te faut ? On part aujourd'hui.}
{192}{}{Oui.}
{193}{}{Non !}
{194}{}{Ack!}
{195}{}{Sinon, je confierai ce travail à quelqu'un d'autre, ne t'inquiète pas. Tu n'as aucune obligation envers moi... tant que tu n'es pas engagé avec une caravane, d'accord ?}
{196}{}{La prochaine caravane part en }
{197}{}{le 8}
{198}{}{le 18}
{199}{}{le 28}
{200}{}{}
{201}{}{}
{202}{}{}
{203}{}{. Reviens par ici si le boulot t'intéresse. }
{204}{}{janvier }
{205}{}{février }
{206}{}{mars }
{207}{}{avril }
{208}{}{mai }
{209}{}{juin }
{210}{}{juillet }
{211}{}{août }
{212}{}{septembre }
{213}{}{octobre }
{214}{}{novembre }
{215}{}{décembre }
{216}{}{Confrérie de l'Acier, nous voilà ! Enfin... je ne t'accompagne pas, mais tu vois ce que je veux dire.}
{217}{}{Ok, va-t'en. Ces fanatiques de la Confrérie t'attendent.}
{218}{}{J'espère que tu aimes les montagnes ! Tu te diriges droit sur elles. Il devrait y avoir beaucoup d'action là-bas.}
{219}{}{Prépare-toi au départ, tu vas te diriger vers les montagnes ! Ca devrait bouger là-bas !}
{300}{}{Alors tu t'es engagé, content de l'apprendre ! Comme tu le sais, on part tous les dix jours : le 8, le 18 et le 28 de chaque mois. Là maintenant, on met le cap sur la Confrérie et Dépôtville. On met plus les pieds au Cimetière de L.A depuis ces histoires d'invasion de mutants.}
