{100}{}{You can't determine if you're poisoned or irradiated.}
{101}{}{You're irradiated and poisoned, but unsure of the extent.}
{102}{}{You're irradiated, but unsure of the extent.}
{103}{}{You're poisoned, but unsure of the extent.}
{104}{}{You are }
{105}{}{insignificantly}
{106}{}{slightly}
{107}{}{mildly}
{108}{}{moderately}
{109}{}{very}
{110}{}{extremely}
{111}{}{dangerously}
{112}{}{fatally}
{113}{}{ irradiated}
{114}{}{.}
{115}{}{ and }
{116}{}{Irradiation level: }
{117}{}{ rads.}
{118}{}{ You are poisoned at level }
{119}{}{You are free of poison and radiation.}
{200}{}{}
