{100}{}{You see a farmer.}
{101}{}{I need better soil.}
{102}{}{I'm not hiring.}
{103}{}{I don't need more water. Please leave.}
{104}{}{This soil is too hard.}
{105}{}{These stupid plants aren't going to survive.}
{106}{}{Why did I become a farmer?}
{107}{}{Those mutts better not be pissing on my crops.}
{108}{}{I hate dogs!}
{109}{}{I hate dogs! Uh, except yours.}
{110}{}{This isn't your home.}
{111}{}{What? Do you go around bothering everyone?}
{112}{}{What a day. I'm exhausted.}
{113}{}{I'll call the police.}
{114}{}{I'm tired. Please leave.}
