{100}{}{Voici Sally.}
{101}{}{Pourquoi tout le monde me parle de façon si étrange ??}
{102}{}{Le mutant t'ignore.}
{1000}{}{Puce d'eau|Puce eau|Puce|Eau|Controleur}
{1001}{}{Nécropolis}
{1002}{}{Set}
{1003}{}{Watershed}
{1004}{}{Hall}
{1005}{}{Lou}
{1006}{}{Goules}
{1007}{}{Normaux}
{1100}{}{Je ne sais pas.}
{1101}{}{C'est ici.}
{1102}{}{C'est un dégonflé. On devrait les éliminer lui et ses Goules.}
{1103}{}{C'est ici.}
{1104}{}{Je ne sais pas.}
{1105}{}{Lui, le chef de Harry.}
{1106}{}{Des poules mouillées.}
{1107}{}{Encore plus poules mouillées que les Goules.}
