{100}{}{Tu utilises l'ordinateur de la porte. L'ordinateur ne reconnaît pas ton code d'accès.}
{101}{}{Tu utilises l'ordinateur de la porte. Un haut-parleur crépite.}
{102}{}{Excuse-moi, mais nous ne pouvons pas te laisser entrer pour l'instant. Euh, des problèmes techniques. Réessaie plus tard.}
{103}{}{Voici l'ordinateur de la porte d'entrée de l'Abri 13.}
{104}{}{Nous te sommes redevables car tu nous as sauvé, mais nous ne pouvons te laisser entrer.}
{105}{}{Nous sommes désolés, mais tu ne peux pas rentrer. Bonne chance.}
{106}{}{Le Dirigeant a parlé; tu dois partir.}
{107}{}{Ecoute, nous sommes plusieurs à être outrés de la décision du Dirigeant, mais nous obéissons aux ordres.}
{108}{}{Tu dois faire ta vie dans le monde extérieur, maintenant. Bonne chance, l'ami.}
{109}{}{Tu es un danger pour le futur de cet Abri; tu dois partir immédiatement.}
{110}{}{Tu n'es pas le bienvenu ici, vas-t'en.}
{111}{}{Nous ne tolérons pas les meurtriers dans l'Abri. Dégage !}
{112}{}{Nous avons peur de ce que tu es devenu et de ce que tu pourrais nous faire. Vas-t'en.}
{113}{}{Après ce que tu as fait au Dirigeant, tu pensais qu'on allait te laisser rentrer tranquillement ?}
{114}{}{Comment as-tu pu nous trahir comme ça ?!}
{115}{}{Barre-toi, psychopathe.}
{116}{}{L'ordinateur explose dans une spectaculaire gerbe d'étincelles, court-circuitant toute le système.}
{117}{}{Tu vois l'ordinateur détruit de la porte d'entrée de l'Abri 13.}
{118}{}{C'est complètement foutu et impossible à réparer.}
{119}{}{Cette porte ne se refermera plus jamais.}
{120}{}{Cette porte ne s'ouvrira plus jamais.}
{121}{}{Direct dans la face !}
{122}{}{Oh-oh !}
{123}{}{L'ordinateur est inutilisable.}
{124}{}{Avec les portes scellées pour toujours et une puce d'eau défectueuse, les habitants de l'Abri 13 ne vont pas tarder à découvrir que cet Abri sera leur tombeau.}
{125}{}{> Command? }
{126}{}{Open the Vault 13 blast door.}
{127}{}{Close the Vault 13 blast door.}
{128}{}{Modify configuration parameters.}
{129}{}{Nothing, never mind.}
{130}{}{Welcome to your SimTek 5000 interactive customization! Vault-Tec is committed to providing a pleasant integration into the outside world. Remember, incorrect settings may cause unstable anomalies! (Warranty void after 2077)}
{131}{}{Vault 13 door entry computer can't be accessed during combat.}
{132}{}{I understand.  [Execute "SPOILERS.EXE"]}
{133}{}{Opens!}
{134}{}{Do shut.}
{135}{}{Changey?}
{136}{}{Buh-bye.}
{137}{}{Boosh.  [Execute "SPOILERS.EXE"]}
{138}{}{Recalibrate Vault 13 water-level monitoring systems.}
{139}{}{View or modify simulation-terminating parameters.}
{140}{}{[Super Mutant Invasions]}
{141}{}{Classify situational combat options.}
{142}{}{Recalculate cross-wasteland encounter statistics.}
{143}{}{[Items, Inventory, Bartering]}
{144}{}{[Levelup stuff]}
{145}{}{[Social sexy times]}
{146}{}{Hmm... Actually, let's go back.}
{147}{}{DO NOT WANT!}
{148}{}{Thanks, I'm all set.  [Exit system]}
{149}{}{This boring!  [Exit system]}
{150}{}{Okay, I'm done here.  [Go to main menu]}
{151}{}{Replay historical data feed.}
{152}{}{Calculating... System monitors indicate that Vault 13 water reserves are currently dropping at a steady rate. Estimated days left until total depletion: }
{153}{}{.  Enter new value to recalibrate system.  (Default database value: 150)}
{154}{}{Commande ?}
{155}{}{[30]}
{156}{}{[60]}
{157}{}{[90]}
{158}{}{[120]}
{159}{}{[150]}
{160}{}{[MORE]}
{161}{}{[BACK]}
{162}{}{[180]}
{163}{}{[210]}
{164}{}{[240]}
{165}{}{[270]}
{166}{}{[300]}
{167}{}{[330]}
{168}{}{[365]}
{169}{}{[730]}
{170}{}{Me like.  [Go to main menu]}
{171}{}{[125]}
{172}{}{[135]}
{173}{}{[140]}
{174}{}{[145]}
{175}{}{Align calibration with Overseer's estimates. [120 - 150]}
{176}{}{Or-seer nums! [120 - 150]}
{177}{}{[999]}
{178}{}{[64000]}
{179}{}{[130]}
{180}{}{Priority of Vault 13 waterchip-replacement subroutines.}
{181}{}{How to stop mutant invasions}
{182}{}{Reevaluate relative priority of Vault 13 survival vectors.}
{183}{}{[Endgame Condition: Can play after being dipped?]}
{184}{}{If the Wasteland will be as rough as it sounds, maybe I should take a moment to reflect on any personal neuroses that may affect my survival out there.}
{185}{}{Me strong is many smart. Maybe has crazies. Want big challenge! [Optional gameplay restrictions]}
{186}{}{If all other threats to the Vault are eliminated, our emergency wastewater redistribution protocol can negate the need for a Water Chip.  Protocol is currently: }
{187}{}{. Toggle protocol status?  (Default status: Enabled)}
{188}{}{DISABLED}
{189}{}{ENABLED}
{190}{}{Looks good; let's back up.  [Go to previous menu]}
{191}{}{The Master.}
{192}{}{The Vats.}
{193}{}{Either the Master or the Vats.}
{194}{}{Both the Master and the Vats.}
{195}{}{To stop invasions of towns, you currently need to eliminate: }
{196}{}{ Change requirement for cessation?  (Default requirement: The Master)}
{197}{}{Checking... By default, this simulation will terminate if sensors indicate Vault 13 Survivability has dropped to zero. Current setting: }
{198}{}{ State the desired status.}
{199}{}{Non.}
{200}{}{Me done! Where other?  [Go to previous menu]}
{201}{}{Oui.}
{202}{}{k!}
{203}{}{[Restorations]}
{204}{}{[Skills]}
{205}{}{Party members}
{206}{}{[Custom playstyles]}
{207}{}{[Misc]}
{208}{}{Thank you for trusting Vault-Tec and SimTek 5000 with your customization needs! Please state a command.}
{209}{}{Simulation terminates when Survivability reaches zero.}
{210}{}{Simulation can continue if the source was foreign.}
{211}{}{Simulation can continue if the source was organic.}
{212}{}{Simulation continues regardless of Survivability rating.}
{213}{}{Can the player keep playing after/if they've become a Super Mutant? Current seting: }
{214}{}{ (Default: No.)}
{215}{}{[SPECIAL]}
{216}{}{Adytum.}
{217}{}{Necropolis.}
{218}{}{The Hub.}
{219}{}{Nah-nah.}
{220}{}{The Brotherhood of Steel.}
{221}{}{Junktown.}
{222}{}{Shady Sands.}
{223}{}{Vault 13.}
{224}{}{For which location would you like to change the invasion time?}
{225}{}{You are viewing number of days until invasion of }
{226}{}{ Current value: }
{227}{}{. Select new value below to modify.  (Default value: }
{228}{}{)}
{229}{}{Instant (0 days)}
{230}{}{1/4 of default.}
{231}{}{1/2 of default.}
{232}{}{Default value.}
{233}{}{2x default.}
{234}{}{3x default.}
{235}{}{4x default.}
{236}{}{Disabled. (this location will not be invaded)}
{237}{}{Do weapons fall to the ground upon death?}
{238}{}{Does player receive dadiation-on-hit from critters?}
{239}{}{Specifics of Childkiller status}
{240}{}{Ambient light and Flares}
{241}{}{}
{242}{}{}
{243}{}{}
{244}{}{}
{245}{}{}
{246}{}{}
{247}{}{Hardcore: No loading saves. Must complete in 1 session.}
{248}{}{Codependent Loser: If a hireling leaves or dies, game over.}
{249}{}{Lone Wolf: If you get party members, game over}
{250}{}{Pacifist: If player lands any hit in combat, game over.}
{251}{}{Killswitch: If combat mode is ever activated, game over.}
{252}{}{I Like It Hard: difficulty_level of Hard only.}
{253}{}{I Like It Rough: combat_difficulty of Rough only.}
{254}{}{Specify if any of the following characteristics apply to you, and sensors will adapt accordingly.}
{255}{}{I'm Special: If your stats are ever raised, game over.}
{256}{}{ This playstyle is currently: }
{257}{}{. Toggle status?}
{258}{}{Weapon Drop Mod is currently: }
{259}{}{hexes from corpse. Your command?}
{260}{}{, with weapons dropping }
{261}{}{ to }
{262}{}{Disable it.}
{263}{}{Enable it, with a drop distance of 0 hexes from corpse.}
{264}{}{Enable it, with a drop distance of 0-1 hexes from corpse.}
{265}{}{Enable it, with a drop distance of 0-2 hexes from corpse.}
{266}{}{Enable it, with a drop distance of 1 hex from corpse.}
{267}{}{Enable it, with a drop distance of 1-2 hexes from corpse.}
{268}{}{Enable it, with a drop distance of 2 hexes from corpse.}
{269}{}{No creatures will irradiate the player upon landing an attack. Which type do you wish to toggle?}
{270}{}{Intel indicates: }
{271}{}{, }
{272}{}{will have a chance to irradiate the player when landing hits, based on Combat Difficulty and player's stats. Which type do you wish to toggle?}
{273}{}{Irradiated Rats}
{274}{}{Floaters}
{275}{}{Centaurs}
{276}{}{Glowing Ghouls}
{277}{}{Non-glowing Ghouls}
{278}{}{Glowing Ghouls and Irradiated Rats only, with a max of 1 rad per hit (2077 field manual defaults)}
{279}{}{Only glowing ghouls and irradiated rats will have a chance to irradiate the player when landing hits, with 1/6 chance of 1 rad per hit. Which type do you wish to toggle?}
{280}{}{Number of times can upgrade Plasma Rifle and Power Armor?}
{281}{}{Items received at start of game}
{282}{}{Mrs Stapleton}
{283}{}{Killian}
{284}{}{Explosives ruin lockers}
{285}{}{Armor}
{286}{}{Holodisks}
{287}{}{Swap knockback/no-knockback on Sledgehammers}
{288}{}{Settings for specific traders/merchants}
{289}{}{Military Base red forcefields - who do they damage?}
{290}{}{Mr Handy in Military Base}
{291}{}{Can hired NPCs level up at all?}
{292}{}{How many player levels per NPC levelup?}
{293}{}{Is levelup tracking relative or absolute?}
{294}{}{After joining the player's team, can Ian/Tycho/Katja gain levels? (Currently they }
{295}{}{can.)}
{296}{}{cannot.)}
{297}{}{ Vanilla default: hired NPCs did not gain levels.}
{298}{}{[1]}
{299}{}{[2]}
{300}{}{[3]}
{301}{}{[4]}
{302}{}{[5]}
{303}{}{[6]}
{304}{}{[7]}
{305}{}{[8]}
{306}{}{How many player levels does it take to trigger a hireling levelup?. (Currently it takes }
{307}{}{ player level for an NPC to gain one level.)  NPC Mod default: 4.}
{308}{}{ player levels for an NPC to gain one level.)  NPC Mod default: 4.}
{309}{}{When hirelings join your team, should they immediately levelup to be what they would if you'd gotten them at level 1?  (Currently they }
{310}{}{do.)  NPC Mod default: Do not.}
{311}{}{do not.)  NPC Mod default: Do not.}
{312}{}{}
{313}{}{}
{314}{}{}
{315}{}{}
{316}{}{}
{317}{}{}
{318}{}{Number of Turbo Plasma Rifle upgrades allowed?}
{319}{}{Number of Power Armor upgrades allowed?}
{320}{}{Player will be able to upgrade this many Plasma Rifles: }
{321}{}{Player will be able to upgrade this many Power Armors: }
{322}{}{. Select a new value if desired.  (Vanilla default: 1)}
{323}{}{To switch between standard and no-knockback version of sledgehammer items, choose an option below.}
{324}{}{Remove knockback from all Super Sledges in player's inventory.}
{325}{}{Remove knockback from all regular Sledgehammers in player's inventory.}
{326}{}{Add knockback to all Super Sledges in player's inventory.}
{327}{}{Add knockback to all regular Sledgehammers in player's inventory.}
{328}{}{Processing... Done!  }
{329}{}{}
{330}{}{}
{331}{}{}
{332}{}{}
{333}{}{}
{334}{}{}
{335}{}{}
{336}{}{}
{337}{}{}
{338}{}{}
{339}{}{}
{340}{}{}
{341}{}{}
{342}{}{}
{343}{}{}
{344}{}{}
{345}{}{}
{346}{}{}
{347}{}{}
{348}{}{}
{349}{}{}
{350}{}{}
{351}{}{}
{352}{}{}
{353}{}{}
{354}{}{}
{355}{}{}
{356}{}{}
{357}{}{}
{358}{}{}
{359}{}{}
{360}{}{}
{361}{}{}
{362}{}{}
{363}{}{}
{364}{}{}
{365}{}{}
{366}{}{}
{367}{}{}
{368}{}{}
{369}{}{}
{370}{}{}
{371}{}{}
{372}{}{}
{373}{}{}
{374}{}{}
{375}{}{}
{376}{}{}
{377}{}{}
{378}{}{}
{379}{}{}
{380}{}{}
{381}{}{}
{382}{}{}
{383}{}{}
{384}{}{}
{385}{}{}
{386}{}{}
{387}{}{}
{388}{}{}
{389}{}{}
{390}{}{}
{391}{}{}
{392}{}{}
{393}{}{}
{394}{}{}
{395}{}{}
{396}{}{}
{397}{}{}
{398}{}{}
{399}{}{}
{400}{}{}
{401}{}{}
{402}{}{}
{403}{}{}
{404}{}{}
{405}{}{}
{1000}{}{You notice blinking lights on the door computer.}
{1001}{}{Hmm... I wonder why those are blinking?}
