{100}{}{Estás viendo a un miembro de los Navajas.}
{101}{}{Hola.}
{102}{}{Hola.}
{103}{}{Que tengas un buen día.}
{104}{}{Tenemos un tiempo estupendo hoy.}
{105}{}{Me pregunto si lloverá.}
{106}{}{¿Has visto alguna vez como brilla la lluvia?}
{107}{}{Tengo que volver al trabajo.}
{108}{}{No vienen muchos forasteros por aquí.}
{109}{}{Tengo que irme.}
{110}{}{Nos vemos.}
{111}{}{Buenos días.}
{112}{}{Gracias por tu ayuda.}
{113}{}{No te olvidaremos.}
{114}{}{Es agradable tenerte de nuestro lado.}
{115}{}{Las cosas irán mejor ahora.}
