{100}{}{Ver Lex.}
{101}{}{Usted ve un perdedor.}
{102}{}{[Más]}
{103}{}{[Hecho]}
{104}{}{[Lex susurros.] Mejor tener cuidado. El Rock no siempre dice la verdad.}
{105}{}{¿Por qué dices eso?}
{106}{}{¿Por qué debería confiar en ti?}
{107}{}{El Rock es un miembro de las Criptas, una pandilla. Él trata de llegar a los extraños, como tú, en problemas. Si usted escucha a él, usted podría encontrarse muerto y enterrado.}
{108}{}{¿Quién eres?}
{109}{}{Gracias por la info. Que tengan un buen día.}
{110}{}{Estoy Lex. Chatarra es mi casa, y supongo que hablo en nombre de su pueblo.}
{111}{}{Nadie más que yo debería saber?}
{112}{}{Bueno, también están los Tontos. Se controla sin perspectivas de futuro, si las Criptas se habían ido. Las dos bandas se pelean por quién controla este lugar. En la actualidad, las Criptas están en la parte superior. Ahora que usted está aquí, las cosas podrían cambiar.}
{113}{}{¿Qué te lleva a decir eso?}
{114}{}{Si usted podría deshacerse de las pandillas, le estaría agradecido. No tenemos los números o la fuerza para ahuyentarlos, y pocas personas se preocupan por este lugar. Si lo que te interesa, entonces podríamos ser capaces de ayudarle.}
{115}{}{¿Qué quieres decir?}
{116}{}{He oído hablar de usted. Usted quiere encontrar la ciudad perdida de la Necrópolis. Un agradecido a la gente que puede proporcionar información sobre a dónde ir.}
{117}{}{Lo tendré en cuenta.}
{118}{}{Podemos pedir nada más.}
{119}{}{Adiós.}
{120}{}{Tengo algunas preguntas.}
{121}{}{¿Por qué no? Tengo los mejores intereses de mi pueblo en el corazón, y me gustaría ver que venir ningún daño.}
{122}{}{¿Qué quieres decir?}
{123}{}{Hay fuerzas en el trabajo aquí en el Cementerio que le gustaría usar, y si eso no es posible, a ver muertos y enterrados. Elige a tus amigos sabiamente, y a tus enemigos aún más la atención. Buen día.}
{124}{}{Sí, buen día.}
{125}{}{Agradecemos a usted para deshacerse de las Criptas y los Tontos. Sin el generador de corriente, mi gente tiene una mala vida. ¿Crees que podría solucionarlo?}
{126}{}{Por supuesto.}
{127}{}{Solucionar el problema usted mismo. Quiero mi recompensa.}
{128}{}{Gracias.}
{129}{}{Muy bien, usted se tiene. Te han echado de mi pueblo en una noche fría y, a continuación, nos abandonó a los lobos -, pero entiendo que tu búsqueda es más importante.}
{130}{}{La violencia ha iniciado puede conducir de vuelta a mi pueblo. Por favor, termine.}
{131}{}{Como cobardes, para sentar las tareas de muerte en los hombros de otros.}
{132}{}{Trabajando en ello.}
{133}{}{Si usted necesita ayuda, voy a ofrecer, pero no lo pido a mi gente. Que están demasiado cansados de la muerte y el dolor. Me uniré a usted, si eso es lo que deseas.}
{134}{}{Sí, que me siga, y atacar cuando lo hago.}
{135}{}{No. Sólo estoy haciendo un comentario social.}
{136}{}{Así como yo sospechaba, no le importa nada excepto sus propias necesidades. Únete a nuestros enemigos, llevar el miedo a mi pueblo, y traicionar a su propio fondo.}
{137}{}{Me voy a matar por decir eso.}
{138}{}{Es un plan. Yo soy de la infiltración de esta pandilla.}
{139}{}{Cierra el pico.}
{140}{}{Pensé que haría, usted gusano.}
{141}{}{Tal vez, pero las acciones hablan más fuerte que las palabras.}
{142}{}{Usted va a ver.}
{143}{}{¿Puedo ayudarte en algo?}
{144}{}{Cuéntame sobre el generador de energía.}
{145}{}{Háblame de las Criptas.}
{146}{}{Me dicen acerca de los Necios.}
{147}{}{Háblame de Chatarra.}
{148}{}{Nada más, gracias.}
{149}{}{Sin perspectivas de futuro es nuestro pueblo. Era nuestro hogar. Y será de nuevo, espero que.}
{150}{}{El poder generador suministra todos los electicity en la ciudad. Sin él, seguramente moriría. Es la cosa más importante en la ciudad. Quien controla los controles de Chatarra.}
{151}{}{Las Criptas son una pandilla de ejecución por Rayze. Él es un animal y tiene una de las armas más grandes que he visto nunca. Él permite a Lenny en vivo, porque él tiene cuidado de que el brahmán, que proporcionan el combustible para el generador. Las Criptas son en la gran casa.}
{152}{}{Baka conduce a los Tontos. Si tenía más hombres, ella seguramente ataque de las Criptas y tratar de tomar de nuevo el poder generador. Usted puede decirle a las Criptas de los Tontos por su armadura. Los tontos de desgaste de metal, Criptas de cuero.}
