{100}{}{Eres incapaz de determinar si estás envenenado o irradiado.}
{101}{}{Estás irradiado y envenenado, pero no sabes en qué medida.}
{102}{}{Estás irradiado, pero no sabes en qué medida.}
{103}{}{Estás envenenado, pero no sabes en qué medida.}
{104}{}{Estás }
{105}{}{mínimamente}
{106}{}{ligeramente}
{107}{}{levemente}
{108}{}{moderadamente}
{109}{}{muy}
{110}{}{extremadamente}
{111}{}{peligrosamente}
{112}{}{mortalmente}
{113}{}{ irradiado}
{114}{}{.}
{115}{}{ y }
{116}{}{Nivel de radiación: }
{117}{}{ rads.}
{118}{}{ Estás envenenado a un nivel }
{119}{}{No estás irradiado o envenenado.}
{200}{}{}
