{100}{}{¡Has enfurecido a Gary!}
{101}{}{Ves: a Gary.}
{102}{}{¡Eh! La ración de agua es solo para los necrófagos.}
{103}{}{¡Cállate!}
{104}{}{El mutante te ignora.}
{1000}{}{Agua}
{1001}{}{Necrópolis}
{1002}{}{Set}
{1003}{}{Almacén de Agua}
{1004}{}{Sala}
{1005}{}{Teni}
{1006}{}{Necrófagos}
{1007}{}{Normales}
{1008}{}{Chip}
{1100}{}{No tengo ni idea.}
{1101}{}{Estás encima de ella.}
{1102}{}{Es un imbécil. Nos cargaríamos a él y a sus necrófagos.}
{1103}{}{Es aquí.}
{1104}{}{No tengo ni idea.}
{1105}{}{Es el jefe de Harry.}
{1106}{}{Debiluchos.}
{1107}{}{Más débiles que los necrófagos.}
{1108}{}{No tengo ni idea.}
