{101}{}{No necesito tus servicios ahora. Quizás más tarde.}
{102}{}{¡Socorro! ¡Sálvame!}
{103}{}{¡Debes morir por lo que has hecho!}
{104}{}{¡Sálvame! ¡Por favor!}
{105}{}{¿Están todos muertos ya? ¡Quizás quede alguno más!}
{106}{}{Tu llegada fue muy oportuna, amiga mía. Déjame que te ofrezca una pequeña muestra de mi gratitud.}
{107}{}{Tu llegada fue muy oportuna, amiga mía. Déjame que te ofrezca una pequeña muestra de mi gratitud.}
