{100}{}{Un Junktown de la guardia.}
{101}{}{Esto es Ciudad Vertedero. Es un lugar agradable en el que vivir mientras estés en el bando correcto.}
{102}{}{Vigila a Gizmo y a sus seguidores.}
{103}{}{Me cae bien mi jefe.}
{104}{}{Será mejor que apartes eso. Ciudad Vertedero es una ciudad amistosa, y queremos que siga siendo así.}
{105}{}{¿Apartar eso?}
{106}{}{No me digas lo que tengo que hacer, perdedor.}
{107}{}{Me parece bien. Por cierto, ¿cuál es la ley local sobre armas?}
{108}{}{Oh, oh.}
{109}{}{Tu arma, idiota. Killian no te quitará las armas, pero será mejor que las mantengas enfundadas.}
{110}{}{Oh, lo siento.}
{111}{}{¡De ninguna manera! ¡No voy a dejar las armas por nadie!}
{112}{}{Que mejor se comportan, ya que es la ley, y yo de hacer cumplir la ley. Pon tu arma, no se dibujar a menos que sea en defensa propia, y usted no tendrá un problema con nosotros los guardias.}
{113}{}{[Más]}
{114}{}{Desobedecer la ley, y vamos a volver a los inicuos páramo - vivo o muerto.}
{115}{}{Claro, si te pones así.}
{116}{}{¡Trágate tus leyes!}
{117}{}{Bueno, uh, yo estoy de acuerdo. Pero será mejor que tengas cuidado.}
{118}{}{Bien, entonces. Heh.}
{119}{}{Está bien que hayas preguntado. No se pueden desenfundar las armas si no es en defensa propia. Si empiezas una pelea, será culpa tuya. Otra cosa distinta es que vayas por ahí armado. No saques ni un cuchillo ni una pistola sin un motivo real. Que tengas un buen día.}
{120}{}{Muchas gracias a vosotros también.}
{121}{}{Hey you, no weapons! And I don't care if your mama dropped you on your head as a kid. No weapons.}
{122}{}{Dorf!}
{123}{}{Usted gana 150 experiencia por matar a la guardia.}
