{100}{}{Ves a un granjero.}
{101}{}{Necesito una tierra mejor.}
{102}{}{No necesito a nadie.}
{103}{}{No necesito más agua; vete, por favor.}
{104}{}{Esta tierra es dura.}
{105}{}{Estas estúpidas plantas no van a aguantar.}
{106}{}{¿Por qué me hice granjero?}
{107}{}{Estos perros no deberían mear en mis cultivos.}
{108}{}{¡Odio los perros!}
{109}{}{¡Odio los perros! Excepto a ti.}
{110}{}{Ésta no es tu casa.}
{111}{}{¿Qué? ¿Te dedicas a molestar a la gente?}
{112}{}{Vaya día. Estoy muerto.}
{113}{}{Llamaré a la policía.}
{114}{}{Estoy cansado. Vete.}
