{100}{}{Estás viendo una mesa de dados. Jugar cuesta 40 chapas.}
{101}{}{Obtienes un 7. ¡Ganas!}
{102}{}{Obtienes dos unos. Pierdes.}
{103}{}{Sacas }
{104}{}{. ¡Ganas!}
{105}{}{Sacas }
{106}{}{. Pierdes.}
{107}{}{Sacas }
{108}{}{ antes de conseguir la puntuación. Pierdes.}
{109}{}{Consigues la puntuación. Ganas.}
{110}{}{Sacas }
{111}{}{. Es tu puntuación. Tiras de nuevo.}
{112}{}{Ganas 70 puntos de experiencia por asesinar al crupier.}
