{100}{}{Estás viendo a uno de los Guardias de Hightower.}
{101}{}{Yo que tú me iba. Daren Hightower no recibe visitas.}
{102}{}{No queremos tu compañía.}
{103}{}{¡Vete!}
{104}{}{¡No puedes estar aquí!}
{105}{}{Vete o te arrepentirás.}
{106}{}{En esta casa no admitimos a gente como tú.}
{107}{}{¿Qué?... ¡Cogedlos!}
{108}{}{¡Cometiste un grave error viniendo!}
{109}{}{¿Qué haces aquí? Voy a acabar contigo.}
{110}{}{Mmmm, parece apetitoso.}
{111}{}{¿Huele a brahmin o soy yo?}
{112}{}{¡Inyéctamelo!}
{113}{}{¿Hay algo en la nevera?}
{114}{}{¿Cuánto falta?}
{115}{}{Tengo hambre.}
{116}{}{¿Está lista?}
{117}{}{¡Voy a pasar!}
