{100}{}{Estás viendo a un fuerte cazador de recompensas con un cartelito que dice "Soy Christopher y estás muerto".}
{101}{}{¿Qué quieres?}
{102}{}{Un buñuelo.}
{103}{}{¿Qué estás haciendo aquí?}
{104}{}{Sólo estaba mirando.}
{105}{}{Nada.}
{106}{}{Aquí no nos gustan los listillos. Largo.}
{107}{}{Ese chiste no fue gracioso ni la primera vez que lo contaste. Estás a punto de descubrir porqué soy uno de los cazarecompensas más temidos del yermo. Y ni siquiera cobro por serlo.}
{108}{}{No es asunto tuyo.}
{109}{}{Bueno, vete por ahí a curiosear.}
{110}{}{¿Sabes que hay una recompensa de }
{111}{}{(Te mira de arriba a abajo detenidamente, como considerando algo. Parece que ya ha hecho una decisión) Dime, ¿con que frecuencia visitas El Eje o Ciudad Vertedero?}
{112}{}{A menudo, ¿por qué preguntas?}
{113}{}{Bueno, verás... el trabajo me quita mucho tiempo y no suelo tener la oportunidad de pasar por allí. Y como fumador incurable que soy, siempre hago en falta un viejo encendedor Zippo. Se dice, que muchos de esos objetos de la preguerra podrían encontrarse en tiendas de por allí. Si me consigues un Zippo, compartiré contigo información de los asentamientos vecinos. ¡Creo que podría ser de ayuda!}
{114}{}{Es una pena. Creo que he cometido un error contigo. Lárgate de aquí.}
{115}{}{Por qué no, te conseguiré uno.}
{116}{}{Vale.}
{117}{}{Ey, tengo uno justo aquí. La verdad es que no lo necesito y te lo podría dar a cambio de la información.}
{118}{}{¡Gracias! [coge el encendedor] Bueno, ¿qué es lo que quieres oír, exactamente?}
{119}{}{Aquí tienes el encendedor. Hora de darme algo de información}
{120}{}{No más preguntas, gracias.}
{121}{}{[Más]}
{122}{}{¿Qué más quieres saber?}
{123}{}{Necesito información.}
{124}{}{Eeehhh... ¿queé?}
{125}{}{¿Vas en serio? Quítate de mi vista.}
{126}{}{Le voy a hacer un favor al mundo poniéndote una bala en el cráneo.}
{200}{}{ chapas por tu pellejo dada tu afición a matar niños? ¡Ha llegado la hora de cobrar!}
