{100}{}{Ves a un campesino.}
{101}{}{Oh, sí, un hombre grande huyendo de un perro asustado. Phil, seguro que lo conseguiste. Seguro que lo hiciste.}
{102}{}{What are you doing, Phil? You're checking the tread on those shoes, aren't you?}
{103}{}{Tío, parece que ese perro tiene hambre. Phil, seguro que quiere comerte vivo.}
{104}{}{Eso es pasarse un poco con un animal indefenso, ¿no te parece?}
{105}{}{Seguro que es muy agradable eso que tienes ahí.}
{106}{}{Estoy seguro de que Phil te agradecería que te deshicieras de su perro.}
{107}{}{Gracias por ocuparte del perro.}
{108}{}{Ves: a Lenore.}
