{100}{}{You see a scared, angry peasant.}
{101}{}{Ves: a Phil.}
{102}{}{¡Yo no soy mi perro!}
{103}{}{Damn right, kill that beast!}
{104}{}{I wouldn't trust that monster, if I were you. That thing is a genuine killer.}
{105}{}{Señor,}
{106}{}{Señora,}
{107}{}{ me haría muy feliz si se deshiciera de ese maldito perro.}
{108}{}{¿Por qué?}
{109}{}{No, solo me ocupo de asuntos importantes.}
{110}{}{¿De dónde viene?}
{111}{}{Hnnng.}
{112}{}{Oh geez. Maybe you can talk it to death?}
{113}{}{No nos deja entrar en nuestra propia casa, por eso.}
{114}{}{Got it, thanks.}
{115}{}{¿No es vuestro perro?}
{116}{}{It was the "pet" of a traveler. When the traveler died, this stupid dog just plopped its furry ass down on my doorstep and wouldn't leave. It's been there for days.}
{117}{}{Oh. Thanks!}
{118}{}{¿Quién era ese viajero?}
{119}{}{¿Cómo era el viajero?}
{120}{}{No lo sé. Un tío que venía del este, o eso dijo por lo menos. Como si fuera tan fácil atravesar las tierras de la muerte del este. Tuvo algunos problemas con Gizmo, cuando intentó meterse en sus negocios.}
{121}{}{Así que Gizmo mandó un par de matones para que le dieran una paliza, lo tiraron desde el tejado del casino. El viajero se rompió el maldito cuello y murió. El perro se volvió loco.}
{122}{}{¿Cómo era el viajero?}
{123}{}{Oh, the guy was tall, dark-haired with a little graying around the edges. He was dressed all in black leather, like that's a good idea in the desert; and carried a shotgun.}
{124}{}{He had some funny accent. The dog was his constant companion; followed him everywhere.}
{125}{}{Appreciate the info!}
{126}{}{I really hate this stupid dog.}
{127}{}{Thanks for your help, stranger.}
{128}{}{Wow, está bien. Ver todo supongo. Culo.}
