{100}{}{Ver Phrax de las Criptas.}
{101}{}{Que la nevera no es de su propiedad. Yo recomiendo no tocarlo.}
{102}{}{¿Por qué no?}
{103}{}{Usted va a hacer?}
{104}{}{No, yo voy a hacer que mis compañeros de Criptas y vamos a hacer que usted se sienta dolor.}
{105}{}{Oh.}
{106}{}{Pertenece a las Criptas. No es la suya.}
{107}{}{Yo sólo quiero una bebida.}
{108}{}{Oh, ok.}
{109}{}{No hay ninguna bebidas en la nevera. Mantener lejos de ella.}
{110}{}{Usted no debería estar jugando con cosas que no es la suya. Y que sin duda no es la suya. Tonto mover.}
{111}{}{Puede ser una Cripta, pero esta sala no es para usted. No me meto con nada.}
{112}{}{Viniste al lugar equivocado en el momento equivocado.}
{113}{}{Esta sala no es para usted. No toque nada, o te la voy a contestar a mí.}
{114}{}{[HECHO]}
{115}{}{[MÁS]}
{116}{}{Phil tiene más valor que cualquier Tonto!}
{117}{}{PUPLE BABBOONS!}
{118}{}{El Brahmán tiene más sentido que un Tonto.}
{119}{}{Los Tontos son tan débiles, incluso Lex puede vencer a todos ellos.}
