{100}{}{Ver Rayze de las Criptas.}
{101}{}{Eres un Tonto para venir aquí.}
{102}{}{¿Por qué te molesta de mí?}
{103}{}{Rock me envió.}
{104}{}{Nada, solo pasaba por aquí.}
{105}{}{Me dicen acerca de los Necios.}
{106}{}{Cuéntame sobre el generador de energía.}
{107}{}{Oh, sí. ¿Por qué es eso?}
{108}{}{Él dijo que yo podría conseguir un vaso de agua fría o de agua.}
{109}{}{Roca dijo que las Criptas fueron en busca de los miembros.}
{110}{}{Ha-Ha! Buen intento. Me deja solo.}
{111}{}{Podría ser. Parece que tienes algo de talento. Usted piensa que usted podría ser una Cripta?}
{112}{}{Sí.}
{113}{}{No.}
{114}{}{Bien, entonces. Vamos a tratar de usted. Vamos a enviar a usted un poco de la misión. Ir a explorar los Tontos con el norte, y me informe.}
{115}{}{Vale.}
{116}{}{Creo que no.}
{117}{}{A continuación, los niños pequeños deben ir antes de que se obtenga una nalgada.}
{118}{}{Nosotros no como extraños en nuestra ciudad. Si usted desea permanecer, por unirse a nosotros. Si no, usted podría lamentar que se alojen en Chatarra.}
{119}{}{¿Cómo puedo unirme a ustedes?}
{120}{}{Me pregunte y le digo que sí. Jurar un juramento cuando se inscribe. Si usted romper ese juramento, puedo enviar algunos de mis chicos a romper.}
{121}{}{Ok, voy a unir.}
{122}{}{Creo que no quiero jugar.}
{123}{}{Usted no es bienvenido aquí. Dejar antes de ser enterrada.}
{124}{}{Son los Tontos listos para nuestro ataque?}
{125}{}{Sí.}
{126}{}{No.}
{127}{}{Necesito explorar algunos más.}
{128}{}{No importa. Nada va a detener de sentir el frío de la muerte! Morir ahora!}
{129}{}{Excelente. Vamos a cogerles desprevenidos. Morir ahora!}
{130}{}{Date prisa. Deseo que la sangre de los Necios.}
{131}{}{Ellos son mis enemigos. Van a morir. Ahora, ¿por qué te molesta de mí?}
{132}{}{Rock me envió.}
{133}{}{Nada, solo pasaba por aquí.}
{134}{}{Cuéntame sobre el generador de energía.}
{135}{}{Usted no debe hacer preguntas sobre cosas que no sabes acerca de. El generador es el nuestro, y lo seguirá siendo nuestra. Mientras la tenemos, estamos en control. Que hacer demasiadas preguntas.}
{136}{}{[Hecho]}
{137}{}{[más]}
{138}{}{Jaja! Más tontos a matar!!}
{139}{}{La única cosa que los Tontos de la regla es de una lápida.}
{140}{}{Los excrementos de Brahmán huele mejor que usted.}
{141}{}{Incluso Lenny tiene mejor objetivo que usted.}
{142}{}{Usted debe no me ha mentido. Yo sé mejor. Vaya, scout de los Necios y de retorno. No me tientan.}
{143}{}{No puede ser de confianza. Que es una vergüenza. Usted va a morir. Esto es un placer.}
{144}{}{Hemos estado esta ciudad ahora!}
{145}{}{Ahora no es el momento de las preguntas. Ahora es el momento de luchar!}
