{100}{}{Ver el Rock.}
{101}{}{Estás viendo a un hombre.}
{102}{}{Usted puede ser que desee pensar acerca de poner la pistola de distancia, hijo. Las Criptas no me gusta cuando la gente de flash de hardware de esa manera.}
{103}{}{Ay, de verdad. Voy a ir a hablar con ellos sobre esto. ¿Dónde están?}
{104}{}{Oh, ok. Where can I get a drink?}
{105}{}{Que son las Criptas?}
{106}{}{Ver como se podría utilizar una bebida fría.}
{107}{}{[Hecho]}
{108}{}{Sí, ir al gran edificio, en el interior de la ciudad, y dile a em 'Rock ha enviado a vosotros.}
{109}{}{Vale.}
{110}{}{Las Criptas? Ellos son el más grande, más malo de la tripulación de alrededor. No se metan con ellos, si quieres dejar sin perspectivas de futuro en una sola pieza.}
{111}{}{¿Dónde están?}
{112}{}{Están en el edificio grande justo dentro de la puerta. Estás buscando algún trabajo estable? En algún lugar de usar esa arma de la suya?}
{113}{}{No.}
{114}{}{Sí, estoy seguro.}
{115}{}{Entonces le sugiero que girar a la derecha alrededor de la espalda y salir. Cementerio no es un lugar para aquellos que no con las Criptas. Si usted quiere ir, puede - pero es su vida.}
{116}{}{Vale.}
{117}{}{Gran. Dígales Rock enviado, en la gran casa.}
{118}{}{Vale.}
{119}{}{Me alegra saber que usted está en el lado bueno de Chatarra. Bienvenido a la pandilla.}
{120}{}{Gracias.}
{121}{}{Has cometido un error. Un terrible, terrible error.}
{122}{}{Welcome to Scrapheap, son. Don't be a fool, and you will do ok.}
{123}{}{Gracias, ¿qué es este lugar?}
{124}{}{¿Quién está al mando aquí?}
{125}{}{Chatarra es la axila del desierto. No hay mejor lugar para criar a los hijos, en mi opinión. [Risas] Este lugar hace Junktown mira como la vida de la ciudad de los antiguos.}
{126}{}{Gracias.}
{127}{}{Bueno, hay una comuna, dirigido por Lex. Pero el poder real está siempre detrás del trono. En este caso, la gente no meterse con el son de las Criptas.}
{128}{}{Gracias.}
{129}{}{Bueno, seguro que no pedir un montón de preguntas. Creo que sólo debería mover a lo largo de ahora.}
{130}{}{Vale.}
{131}{}{[Hecho]}
{132}{}{Las Criptas va a enterrar a usted!}
{133}{}{Los tontos no tienes una razón para vivir.}
{134}{}{El Tonto perecerá.}
{135}{}{Mira quien fue golpeado con el feo palo.}
