{100}{}{Escriba}
{101}{}{Investigar es una de mis aficiones. Me siento como si estuviera resolviendo un misterio.}
{102}{}{Ser un escriba es lo mejor. Estudias antiguas tecnologías e intentas desarrollar otras nuevas.}
{103}{}{Se podrían mejorar estos terminales. Quizás deberíamos poner la pantalla aquí.}
{104}{}{Lo siento, estoy justo en medio de un posible descubrimiento. No puedo hablar ahora.}
{105}{}{Eh, Iniciado. Deberías intentar ser un escriba si no lo has decidido todavía.}
{106}{}{Nosotros los escribas diseñamos todo el equipo, armas y suministros. Es bastante emocionante.}
{107}{}{No me molestes, por favor. Estoy intentando terminar mi investigación.}
{108}{}{Aquella de allí es Vree. Ella también es escriba.}
