{100}{}{Estás viendo un muro macizo.}
{101}{}{En esta parte del muro hay algo raro.}
{102}{}{Ves una puerta deslizante.}
{103}{}{La puerta está cerrada con llave.}
{104}{}{Activas la trampa de la puerta.}
{105}{}{ detecta una trampa en esta puerta.}
{106}{}{Detectas una trampa en esta puerta.}
{107}{}{Eso no hace nada.}
{108}{}{La puerta ya está desbloqueada.}
{109}{}{Rompes tus ganzúas con esta cerradura que se te resiste.}
{110}{}{No consigues forzar esta cerradura.}
{111}{}{Fuerzas la cerradura de la puerta.}
{112}{}{Es demasiado difícil forzar esta cerradura ahora.}
{113}{}{Te fijas en una trampa altamente explosiva en esta puerta cerrada.}
{114}{}{Te fijas en una trampa altamente explosiva en esta puerta.}
{115}{}{Te fijas en una trampa en esta puerta cerrada.}
{116}{}{Te fijas en una trampa en esta puerta.}
{117}{}{No ves nada especial en esta puerta cerrada.}
{118}{}{No ves nada especial en esta puerta.}
