{100}{}{Ver Skippy.}
{101}{}{Usted ve un ganger.}
{102}{}{Él es tirar lo que parece una exótica cuchillo en el aire.}
{103}{}{[más]}
{104}{}{[Hecho]}
{105}{}{[Lanzando un juego de cuchillas cerca de su cara] cuidado, no se quien. Puedes hacerte daño, y entonces tendría que reír.}
{106}{}{Usted lo mira, esas cosas se ven bien.}
{107}{}{Dar estas cosas a mí antes de lastimar a alguien!}
{108}{}{What are you tossing around, anyway?}
{109}{}{Ellos son agudos, de hecho son más nítida que la de su ingenio.}
{110}{}{Se que me reto?}
{111}{}{Ouch, pero supongo que me lo merecía.}
{112}{}{Me? Desafío? Oh, el mismo pensamiento me hace reír. No, nosotros los Tontos de no participar en el código de duello. No es nuestro estilo. Permítanos mostrarle cómo tratamos a los forasteros.}
{113}{}{De hecho, lo hizo. ¿Qué puedo hacer por usted?}
{114}{}{¿Qué son esas cosas?}
{115}{}{Lo que son es mío, lo que no se es tuyo. Más allá de eso, estas fresas son una reliquia de mi pobre difunto padre. Usted puede decir que él tiene un poco atrapados en ellos antes de morir! [Skippy ríe].}
{116}{}{Eres tonto. Puedo tomar prestado de ellos?}
{117}{}{Bueno, ya que le preguntó muy bien - bien. [Él de manos a los cortadores.] Ahora, vete, porque tengo que buscar un nuevo juguete para pasar el tiempo.}
{118}{}{Yo creo que no, al menos no de la manija-en primer lugar. Llorarás de la sangre, o, al menos, lloro de la risa y el dolor cuando he terminado con usted.}
{119}{}{No nos gusta su clase aquí. Dejar o vas a estar en la final.}
{120}{}{Bueno, si no es la última Tonto. Un buen sentido del humor, al menos. Tal vez algunas habilidades de motricidad fina. Vamos a ver. Jugar bonito.}
{121}{}{Eres un afortunado, mi amigo. Este día es el día que le permitirá vivir. A menos que, por supuesto, usted me molestan demasiado. A continuación, voy a tener que usar mi mejor cadáver chistes.}
{122}{}{Nunca robar a un Tonto, tonto.}
{123}{}{Ya has conseguido el cortadores de Skippy. Dejar de fumar mientras está por delante.}
{124}{}{Te las arreglas para robar las fresas, mientras que él no está mirando.}
{125}{}{Usted nos insultan, y nuestra Reina de honor. Algunos insultos sólo puede ser pagado en sangre.}
{126}{}{Usted morirá escoria!}
{127}{}{Es que su cara, o que su cuello vomitar?}
{128}{}{Que la madre tenía que atar un filete de carne a su alrededor para que el perro juegue con usted}
{129}{}{La única cosa más estúpido de lo que es Rayze.}
{130}{}{Supongo que la placenta puede vivir un poco de tiempo.}
