{100}{}{Estás viendo a Terry.}
{101}{}{La ración de agua se da por la noche... Oye, ¡tú no eres un necrófago!}
{102}{}{Eso no importa ahora. Lo que importa es dónde se encuentra el jefe.}
{103}{}{No, no lo soy.}
{104}{}{Nah.}
{105}{}{Te llevaré ante él. Ven, deja que te eche una mano.}
{106}{}{Será mejor que te lleve a Harry, él sabrá qué hacer contigo.}
{107}{}{¡Oye, basta de charla! Perturbas mi concentración.}
{108}{}{¿Qué hora de la noche es?}
{109}{}{El mutante te ignora.}
{1000}{}{Chip}
{1001}{}{Necrópolis}
{1002}{}{Set}
{1003}{}{Almacén de Agua}
{1004}{}{Sala}
{1005}{}{Teni}
{1006}{}{Necrófagos}
{1007}{}{Normales}
{1100}{}{No tengo ni idea.}
{1101}{}{T´a pisándola.}
{1102}{}{Es un impresentable. Nos mantenemos alejados de él y de sus necrófagos.}
{1103}{}{Es aquí.}
{1104}{}{No tengo ni idea.}
{1105}{}{Es el jefe de Harry.}
{1106}{}{Debiluchos.}
{1107}{}{Más débiles que los necrófagos.}
