{100}{}{Du ser: Abel.}
{101}{}{Du ser en stor mutant.}
{102}{}{Du borde inte vara här.}
{103}{}{Hng.}
{104}{}{Självfallet inte. Jag är här för att döda dig!}
{105}{}{Varför säger du så?}
{106}{}{Jasså? Din mamma!}
{107}{}{Pik!}
{108}{}{Jag ska spöa skiten ur 'ej om du säger det där igen!}
{109}{}{Pik! Pik!}
{110}{}{Åh, nu ska du få vad du förtjänar!}
{111}{}{Du människa. Jag mutant. Mutant döda människa.}
{112}{}{Hur kan du göra det? Kraftfältet, då?}
{113}{}{Abel ta hand om det! Sen Abel spöa skiten ur dig!}
{114}{}{Barn är inte tillåtna här. Det här mutantställe. Försvinn.}
{115}{}{Hng!}
{116}{}{Jag måste igenom detta kraftfält. Vänligen sänk det.}
{117}{}{Nej.}
{118}{}{Du igen. Abel spöa skiten ur dig!}
{970}{}{Jag Abel.}
{971}{}{Jag Abel.}
{972}{}{Jag Abel.}
{973}{}{Jag Abel.}
{974}{}{Jag Abel.}
{975}{}{Jag Abel.}
{976}{}{Jag Abel.}
{977}{}{Jag Abel.}
{978}{}{Jag Abel.}
{979}{}{Jag Abel.}
{980}{}{Hng.}
{981}{}{Varför du säga så?}
{982}{}{Pik!}
{983}{}{Ung... va?}
{984}{}{Hmm?}
{985}{}{Vad du sa?}
{986}{}{Va, hmm?}
{987}{}{Eh... jag inte veta.}
{988}{}{Jag inte veta.}
{989}{}{Vad det där?}
{990}{}{}
{991}{}{}
{992}{}{}
{993}{}{}
{994}{}{}
{995}{}{}
{996}{}{}
{997}{}{}
{998}{}{}
{999}{}{}
