{100}{}{Du ser en invånare i Adytum.}
{101}{}{Ser ut som regn... som alltid.}
{102}{}{Förlåt, måste springa. Har jobb att göra.}
{103}{}{Vi får inte många främlingar här.}
{104}{}{Måste fortsätta arbeta.}
{105}{}{Om jag var du skulle jag gå tillbaka till Hubben.}
{106}{}{Goddag... om det är vad man kan kalla det.}
{107}{}{Ja, ja... sak samma.}
{108}{}{Ingen tid att snacka.}
{109}{}{Kan inte prata just nu.}
{110}{}{Hoppas att regnet int' stråla' som igår.}
{111}{}{Ser ut som att vi kommer ha dåligt med mat igen.}
{112}{}{Jag hoppas att karavanerna passerar förbi snart.}
{113}{}{Nu har vi en chans att klara det.}
{114}{}{Adytum ska bli den stad vi önskar.}
{115}{}{Tack för din hjälp.}
{116}{}{Tack för att du gjorde dig av med Reglerarna.}
{117}{}{Tack för vår frihet.}
{118}{}{Det är bra att Reglerarna är nu borta.}
{119}{}{Välkommen till det nya Adytum.}
