{100}{}{Du ser en äldre kvinna.}
{101}{}{Du ser: Agatha.}
{102}{}{Denna kvinna är rynkig och grå, men har ändå en pigg gångstil och en upplyftande personlighet.}
{103}{}{Du är en elak människa. Jag kommer inte ha något med dig att göra.}
{104}{}{Det är hemskt när en av våra unga är hotade. Att förlora Tandi skulle vara hemskt.}
{105}{}{Hnng.}
{106}{}{Okej.}
{107}{}{Varför?}
{108}{}{Vad menar du?}
{109}{}{Jag vet att du kommer göra ditt bästa, min kära. Hitta Tandi, hjälp henne att fly från de där bestarna och för henne tillbaka till Aradesh. Du kommer att hjälpa vårt samhälle och bygga upp god karma också.}
{110}{}{Aradesh älskar sin dotter väldigt mycket. Det är hans kärlek som gör honom till en pelare i vårt samhälle. Utan den kärlek skulle han vara förlorad och Shady Sands skulle säkerligen följa därefter...}
{111}{}{Jag ska göra mitt bästa. Hej då.}
{112}{}{Jag skulle behöva lite hjälp.}
{113}{}{Hmmm. Vi får se.}
{114}{}{Jag känner att hon är fängslad. Hon var måltavla för hat. Det hatet är mycket starkt i sydost. Jag är säker på att du kommer att hitta henne där. Lycka till.}
{115}{}{Tack.}
{116}{}{Har du inte hört? Tandi är försvunnen. Jag känner att hon blev kidnappad. Aradesh är väldigt förkrossad. Detta är hemskt...}
{117}{}{Jag hörde att du har räddat Tandi. Det var rätt sak att göra. Din karma är stark. Jag har stora förhoppningar för din framtid.}
{118}{}{Jag är ledsen att höra om Tandi. Hon var en så smart ung kvinna. Hon skulle ha gjort något bra med sitt liv.}
{119}{}{Hallå där. Du måste vara främlingen som alla pratar om. *suck* Hur kan jag hjälpa dig?}
{120}{}{Hngh.}
{121}{}{Vem är du?}
{122}{}{Du ser väldigt trött ut. Är det något som är fel?}
{123}{}{Varför ser du så trött ut?}
{124}{}{Prata inte med mig, gamla kvinna.}
{125}{}{Du behöver mer hjälp än jag kan ge dig, mitt barn. Må Dharma vara med dig.}
{126}{}{Mitt namn är Agatha. Jag är Shady Sands historieberättare. Det är mitt jobb att bevara historien så att vi kan minnas och aldrig glömma.}
{127}{}{Berätta en historia för mig.}
{128}{}{Okej, hursom.}
{129}{}{Det är bra att inte glömma.}
{130}{}{Jag är ledsen, mitt barn, men jag är trött just nu. Jag behöver min vila. Kom tillbaka senare, är du snäll.}
{131}{}{Så sant. (Hon stirrar på dig en stund) Det är bra för de unga att minnas, men det är mycket svårt att agera inom historiens flöde. Ibland bestäms den kurs vi tar av händelser för länge sedan. Må Dharma vara med dig. Jag måste vila en liten stund. Kom tillbaka när jag är starkare, så kan vi talas vid igen.}
{132}{}{Tack för att du frågar. Jag är bara gammal, det är allt. Jag kan inte sova på nätterna. Jag sluter mina ögon... (Hon pausar), men jag får ingen ro. Snälla, det är bara mina gamla trötta ben...}
{133}{}{Jag är ledsen, jag är väldigt trött. Kan du komma tillbaka senare?}
{134}{}{Hedå.}
{135}{}{Okej.}
{136}{}{Varför är du så trött?}
{137}{}{Jag sover inte så bra om nätterna, mitt barn. Det måste vara min ålder.}
{138}{}{God dag, mitt barn. Du ser ut att må bra. Du påminner mig om mitt egna barn.}
{139}{}{Hng.}
{140}{}{Jag vill höra en historia, i så fall.}
{141}{}{Jag är glad att du mår bättre.}
{142}{}{Tack. Hej då.}
{143}{}{Du påminner mig definitivt om mitt barn. När hon bara var några månader gammal, faktiskt.}
{144}{}{Tack så mycket. Dharma sa alltid att bonden som planterar artighet kommer att gå i frid när säsongen är över.}
{145}{}{Snälla, berätta en historia för mig.}
{146}{}{Den här Dharma-killen låter som en idiot.}
{147}{}{Du förolämpar dina äldre. Du borde veta bättre.}
