{100}{}{Du ser en Supermutant. Han vaktar dörren till luftslussen.}
{101}{}{Du ser en vaktande Supermutant.}
{102}{}{Jeremiah, du får passera.}
{103}{}{Gå vidare.}
{104}{}{Rör dig snabbare, budbärare.}
{105}{}{Normaler får inte bära vapen här! Stanna och identifiera dig!}
{106}{}{Grrr!}
{107}{}{Eh, förlåt. Jag ska lägga undan det.}
{108}{}{Jag är bara på genomresa. Inget behov av identiteter här.}
{109}{}{Dö! Dö! Dö! Jag har alltid velat säga det.}
{110}{}{Jag ska inte tilltalas på det sättet. Du kommer att bli straffad.}
{111}{}{Halt! Vad är ditt ärende här, "barn".}
{112}{}{Hng!}
{113}{}{Jag, eh, håller på med grejer.}
{114}{}{Jag är i ett viktigt ärende. Du har ingen rätt att stoppa och fråga ut mig.}
{115}{}{Prata inte med mig, storponken.}
{116}{}{Ditt svar lugnar inte mina nerver. Tala snabbt och tydligt, annars antar jag att ni är här i oanständigt syfte. Jag försäkrar dig att du inte kommer att gilla det...}
{117}{}{Eh, nej, verkligen, ärligt talat. Jag håller på med grejer.}
{118}{}{Jag kommer med ett meddelande till vår ledare.}
{119}{}{Jag anar osanningen bakom dina ord. Du kommer inte att släppas in. Det lovar jag dig...}
{120}{}{Du kan passera, men nästa gång, följ rätt procedur...}
{121}{}{Okej, tack. Vi ses.}
{122}{}{Och vad är det?}
{123}{}{Välsignelse till dig, broder.}
{124}{}{En sann anhängare av Mästaren skulle ha den kunskapen. Du är en inkräktare!}
{125}{}{Gå vidare. Jag har inte tid med dina frågor.}
{126}{}{Du irriterar mig.}
{127}{}{Jag har jobb att göra. Har du det?}
{128}{}{Du begår ett misstag genom att komma hit. Förklara dig eller dö...}
{129}{}{Nuggie!}
{130}{}{Jag har ingenting att säga.}
{131}{}{Jag är här för att skydda mänskligheten från sådana som du.}
{132}{}{Åh, håll tyst!}
{133}{}{Du ska inte försöka lura mig genom att spela dum. Jag är trött på det här...}
{134}{}{Vad är det för en dåraktig trångsynthet? Vi är "mänskligheten". Vi är precis lika mänskliga som du är.}
{135}{}{Vad är det för skit?}
{136}{}{Det finns ingen möjlighet att du är mänsklig.}
{137}{}{Mitt namn är Kyle. Jag föddes av en mor och en far, precis som du. Mästaren övervakade bara min återfödelse. Dessa muskler, denna hud, denna styrka gör mig inte mindre mänsklig än dig. Jag gillar inte allt som Enigheten står för, men det är den bästa chans till fred som vi har.}
{138}{}{Inte på min vakt, är det inte. Jag är här för att sätta stopp för dig och din sort.}
{139}{}{Du må vara mänsklig, men det gör inte din Enighet rätt. Jag antar att vi kommer att vara fiender.}
{140}{}{Det är synd att du beter dig så här, men du kommer inte att fortsätta...}
{141}{}{Det kommer att bli en sann skam att se ditt huvud på en påle.}
{142}{}{Inkräktare!}
{143}{}{Jag inte prata med dig.}
{200}{}{Du tjänar }
{201}{}{ erfarenhet för att ha bluffat dig förbi vakterna.}
