{100}{}{Du ser en medlem av Anhängarna.}
{101}{}{Du ser: Broder Alan, från Anhängarna.}
{102}{}{Hej, hälsningar och god dag till dig, mannen. Hur är läget?}
{103}{}{Hejsan. Vad kan jag göra för dig?}
{104}{}{Hej.}
{105}{}{Hej, hälsningar och god dag till dig, fröken. Hur är läget?}
{106}{}{Owoowngh!}
{107}{}{Hej.}
{108}{}{Jag har träffat några av Anhängarna. Vad gör ni egentligen?}
{109}{}{Jag försöker hitta en spion inom era led, men jag har inte mycket tur. Kan jag få ställa några frågor?}
{110}{}{Jag studerar mest filosofi och sånt. Jag menar, om vi ska skapa fred så behöver vi en bra grund för det, eller hur?}
{111}{}{Ett värdigt ändamål.}
{112}{}{Den enda filosofi du behöver är en stor pistol!}
{113}{}{Hmm. Okej, då. Jag antar att jag får prata med dig senare.}
{114}{}{Whoa! Jag tror inte att jag kan hjälpa dig.}
{115}{}{Hör du, det är just den sortens attityd som orsakar alla dessa problem. Ta det bara lugnt, okej?}
{116}{}{Heh. Jag skojade bara.}
{117}{}{Låt mig ge dig lite frid... evig frid.}
{118}{}{Eh, visst, varsågod.}
{119}{}{Vad mer vill du veta?}
{120}{}{Har du haft någon kontakt med Katedralens Barn?}
{121}{}{Lämnar du någonsin biblioteket?}
{122}{}{Känner du till någon som regelbundet går ut?}
{123}{}{Inte en chans. Jag har hört att de alla är missfoster. Jag skulle inte vilja prata med dem.}
{124}{}{Nej, varför skulle jag det? Jag gillar bara att läsa. Och det är bara spanare som får gå någonstans.}
{125}{}{Bara spanarna och vakterna. Vakterna går och patrullerar lite då och då. Jag ville bli vakt, men... tja, jag fick stryk i ett slagsmål, så jag kunde inte följa med. Spanarna, de går mycket längre, ibland hela vägen till Katedralen, tror jag.}
{126}{}{Inga fler frågor, tack.}
{127}{}{[Mer]}
