{100}{}{Du ser..: Alex, Regleraren som står nattvakt.}
{101}{}{Kom in, }
{102}{}{Ledsen, jag kan inte släppa in dig. Kom tillbaka imorgon bitti.}
{103}{}{Halt! Vem är det som går där?}
{104}{}{Jag är bara en resenär. Jag skulle vilja komma in.}
{105}{}{Det angår inte dig.}
{106}{}{Ehm, förlåt. Jag ska gå härifrån.}
{107}{}{Inga främlingar är tillåtna inom Adytums murar, på order av borgmästaren.}
{108}{}{Jag behöver bara någonstans att sova för natten.}
{109}{}{Jag är ledsen, men jag kan inte släppa in dig. Vänd dig om och gå, annars måste jag skjuta.}
{110}{}{Det är min plikt och ära att vara nattvakt i Adytum, så det är min ensak. Vänd dig om och gå, annars måste jag ta det på allvar.}
{111}{}{Get out of my face, John Law.}
{112}{}{Försök att komma tillbaka på morgonen.}
{113}{}{Åh, det var det. Nu är det dags att ta av handskarna!}
{114}{}{Nghgh.}
