{100}{}{Du ser en hund. Han verkar följa efter dig.}
{101}{}{Du ser en hund.}
{102}{}{Voff!}
{103}{}{Grrr!}
{104}{}{Det verkar som om den här hunden har blivit en vän till dig.}
{105}{}{Du får 200 erfarenhetspoäng för att du blivit vän med hunden.}
{106}{}{Du får 335 erfarenhetspoäng när du besegrar hunden och släppt in Phil i hans hus igen.}
{107}{}{Kom hit, pojken.}
{108}{}{Voff. Voff.}
{109}{}{Av någon anledning gillar den här hunden dig.}
{110}{}{You see: Dogmeat.}
{111}{}{Arf! Arf Arf! Arf! Arf! Arf! Arf! Arf! Arf!}
{112}{}{[Sniff. Sniff.] Grrrr! Morr!}
{113}{}{[Sniff. Sniff] Voff!}
{114}{}{Du tjänar 100 EXP för att du hjälpte Phil att lösa sin hundkonundrum.}
{115}{}{Hunden verkar tro att du är hans ägare.}
{116}{}{Du tjänar 100 EXP för att du hjälpte Phil att lösa sin hundkonundrum.}
{117}{}{Voff-voff! Voff!}
{118}{}{Kom igen, Dogmeat. Duktig pojke.}
{119}{}{Dogmeat, sitt! Duktig pojke. Jag är snart tillbaka.}
{120}{}{Kom igen, Dogmeat!}
{121}{}{Valp!!!}
{122}{}{Voff?}
{123}{}{Arf?}
{124}{}{Voff-voff! Voff!}
{300}{}{Vovven!! vovven vara ven?}
{301}{}{Vovven stanna! flytta inte.}
{302}{}{Flytta på dig, Dogmeat. Duktig pojke.}
{303}{}{}
{304}{}{Duktig vovve.}
