{100}{}{Du ser: Mitch, från All-N-One-butiken.}
{101}{}{Hur kan jag hjälpa dig i dag?}
{102}{}{Jag skulle vilja köpa något.}
{103}{}{Jag skulle vilja sälja något.}
{104}{}{Ingenting. Tack.}
{105}{}{Runk.}
{106}{}{Bra. Här är vad jag har.}
{107}{}{Bra, letar alltid efter nya saker.}
{108}{}{Tyvärr, jag förstår dig inte. Kom tillbaka när du får mer hjärna.}
{109}{}{Tack. Kom tillbaka snart igen.}
{110}{}{Du ser: Jake, vapenhandlaren.}
