{100}{}{Du ser en ökenplundrare. Att döma av hur de andra ser på henne måste hon ha någon viktig eller auktoritär ställning.}
{101}{}{Jag är Alya av Khans. Hur kan jag hjälpa dig idag?}
{102}{}{Jag söker en kvinna som heter Tandi. Har du sett henne?}
{103}{}{Vad sägs om en liten kyss?}
{104}{}{Varför har ert rövarband attackerat Shady Sands?}
{105}{}{Nej, tack.}
{106}{}{Hooroo!}
{107}{}{Om hon är en av de där kvinnorna från Shady Sands kanske du ska titta där. Gå nu, jag måste slipa klart mina knivar.}
{108}{}{Kyss det här!}
{109}{}{Vi attackerar inte dem från Shady Sands. Vi kommer från samma plats som de. Det är bara rätt att de delar med oss!}
{110}{}{Men ni skadar deras boskap och skrämmer dem.}
{111}{}{Det tycker jag är rättvist.}
{112}{}{Eh, ja. Jag tror att jag ska gå nu.}
{113}{}{Du låter lika mesig som de. Om de hade svältproblem är det deras eget fel att de inte planerade i förväg. Se det vi gör som handel med tjänster.}
{114}{}{En handel med talanger?!? Hur kan detta vara en handel med talanger? Du ger dem ingenting.}
{115}{}{Visst, och kycklingar har tre ben.}
{116}{}{Eh, ja. Jag tror att jag ska gå nu.}
{117}{}{Jag är ledsen, men jag kan inte förstå dig. Jag slipar mina knivar och vill inte bli störd.}
{118}{}{Vi ger dem det viktigaste som finns: Vi ger deras trista liv spänning.}
{119}{}{Jag tror inte att de vill ha din typ av spänning.}
{120}{}{Jag tror att jag kommer att göra deras liv tråkiga igen. Jag börjar med dig!}
{121}{}{Eh, ja. Jag tror att jag ska gå nu.}
{122}{}{Jag frågade inte. Men eftersom du uppenbarligen inte har något begrepp om vad som är roligt tror jag att jag kommer att avsluta din existens.}
{123}{}{Att håna mig bådar inte gott för dig. Jag föreslår att du lämnar min närvaro.}
{124}{}{Det är helt klart rättvist. Nu ska du försvinna ur mitt ansikte.}
{125}{}{Jag är just nu upptagen med att förbereda vår nästa räd.}
{200}{}{Du förstår: Alya, en av Garls rådgivare.}
