{100}{}{Du förstår: Amber, en lärare bland Anhängarna.}
{101}{}{Det är nu jag vilar. Kom tillbaka under kvällen.}
{102}{}{Välkommen ädla resenärer. Har du kommit hit för att studera?}
{103}{}{Nej, jag kom egentligen hit bara för att döda saker.}
{104}{}{Det beror på vad du vill lära mig.}
{105}{}{Ja, jag är villig att lära mig.}
{106}{}{Jag är verkligen ledsen att höra det. Anhängarna tror på fred till varje pris. Av den anledningen har jag avstått från våld. God kväll.}
{107}{}{Jag är skicklig i många språk och konstarter. Kanske vill du lära dig en av dem?}
{108}{}{Jag är ledsen, men jag behöver veta saker som hjälper mig att överleva.}
{109}{}{Jag har ingen tid för den typen av saker. Jag drar.}
{110}{}{Jag kanske kan lyssna på en sång eller två.}
{111}{}{Kan du lära mig något annat?}
{112}{}{Ah, här har vi en livets elev. I ett fall som detta kan jag lära dig lite örtmedicin, men det tar ett tag att träna för att få ett litet resultat.}
{113}{}{Visst, lär mig bara.}
{114}{}{Snälla, lär mig vad du kan.}
{115}{}{Ledsen, jag har verkligen inte tid med växter. Hej då.}
{116}{}{Du behöver inte vara oförskämd. Be om ursäkt nu, annars kommer jag inte att lära dig.}
{117}{}{Jag är ledsen. Kan du vara snäll och lära mig?}
{118}{}{Glöm det.}
{119}{}{Det är bättre nu. Vi kommer att påbörja dina studier.}
{120}{}{Du är en duktig elev. Må dina prövningar vara lätta. Gå i frid.}
{121}{}{Som du vill. Må framtiden mjuka upp ditt hjärta och vidga ditt sinne.}
{122}{}{Nåväl, jag ska lära dig hur man överlever.}
{123}{}{Du är en duktig elev. Må dina prövningar vara lätta. Gå i frid.}
{124}{}{Du övertygar mig inte. Jag tror att du försöker använda mina gåvor för att skada. God kväll.}
{125}{}{En konststuderande är en sällsynt sak i den här världen. Kanske finns det hopp för dig ännu. Varje sång är lång i tiden. Vilken skulle du vilja höra?}
{126}{}{I Skuggans Kölvatten.}
{127}{}{Balladen om Aires.}
{128}{}{Till minne av Artemis.}
{129}{}{Resandet av Gryningens Vagn.}
{130}{}{Ett häpnadsväckande arbete. Jag ska ge dig en publik.}
{131}{}{Jag måste vila. Denna undervisning tär mycket på mig. Lycka till.}
{132}{}{Ett häpnadsväckande arbete. Jag ska ge dig en publik.}
{133}{}{Jag måste vila. Denna undervisning tär mycket på mig. Lycka till.}
{134}{}{Ett häpnadsväckande arbete. Jag ska ge dig en publik.}
{135}{}{Jag måste vila. Denna undervisning tär mycket på mig. Lycka till.}
{136}{}{Ett häpnadsväckande arbete. Jag ska ge dig en publik.}
{137}{}{Jag måste vila. Denna undervisning tär mycket på mig. Lycka till.}
{138}{}{Jag är rädd att jag har uttröttat mig själv alldeles för mycket. Jag ber om ursäkt för det.}
{139}{}{Fred och Skönhet är allt jag kan lära ut. Jag är ledsen att det inte tilltalar dig. Ha en bra dag.}
{140}{}{Jag kan lära dig de gamla bardernas och minstrarnas sätt.}
{141}{}{Det vore en ära att få höra en sång.}
{142}{}{Kanske en annan gång. Tack så mycket.}
{143}{}{Jag hoppades kunna lära mig något som kan hjälpa mig mer.}
{144}{}{Du har inget behov av mina talanger. Du har lärt fredliga människor krigets vägar. Jag sörjer för dem nu.}
