{100}{}{Du ser: Andrew, fängelsevakten.}
{101}{}{Okej, du kan gå nu.}
{102}{}{Hallå! Du! Stopp!}
{103}{}{Kan jag hjälpa dig?}
{104}{}{Vem är du?}
{105}{}{Vad är det du gör?}
{106}{}{Nej tack.}
{107}{}{Jag heter Andrew. Mitt jobb är att vakta fängelset.}
{108}{}{Jag vaktar fängelset. Jag ser till att missdådare inte tar sig in eller ut.}
{109}{}{Varför skulle du hindra folk från att komma in i fängelset?}
{110}{}{Åh.}
{111}{}{Ha en bra dag. Och håll dig borta från trubbel.}
{112}{}{Någon kanske lämnar något för att hjälpa en fånge att fly. Eller så kan någon bli inlåst och fast tills vi får tag på nycklarna.}
{113}{}{Eergh!}
{114}{}{Gå vidare, mannen.}
{115}{}{Gå vidare, fröken.}
{116}{}{Hallå! Lägg av!}
