{100}{}{Du ser: Aradesh.}
{101}{Ara_1g}{Var hälsad, vandrare. Bli inte förolämpad om människorna här verkar oförskämda. Som Dharma sa, 'Tuffa tider garvar det mänskliga skinnet.' Ditt ändamål i Shady Sands kan vara?}
{102}{Ara_1n}{Var hälsad. Ditt ändamål i Shady Sands kan vara?}
{103}{Ara_1b}{Vi gillar inte främlingar särskilt mycket. Ditt ändamål i Shady Sands?}
{104}{}{Jag är från en liten by västerut. Jag är bara ute och utforskar och vill er inget illa.}
{105}{}{Vad betyder det för dig?}
{106}{}{Mina skäl är mina att behålla.}
{107}{}{Jag är från ett Valv i väst. Mitt folk dör av törst och jag måste hitta ett vattenreningschip för att de ska överleva.}
{108}{}{Jag räddar ett helt folk från undergång!}
{109}{}{Shady Sands? Hoppsan, jag är vilse! Jag ska bara gå nu.}
{110}{}{Hunh?}
{111}{Ara_2}{Jag känner inte till någon by västerut.}
{112}{}{Har du varit i bergen väster om oss?}
{113}{}{Och?}
{114}{}{Menar du att du känner till varenda plats härifrån till havet?}
{115}{}{Jag är säker på att du har varit på många ställen, men du måste ha missat min lilla by.}
{116}{Ara_3}{Tyvärr har jag inte gjort det. Vilket väcker frågan: Hur gjorde du den där passagen?}
{117}{}{Det var ganska tufft, men jag klarade det.}
{118}{}{Vad betyder det för dig?}
{119}{}{Allt jag ville ha var lite varor och saker, men jag går gärna någon annanstans.}
{120}{}{Jag behöver inte svara dig.}
{121}{Ara_4}{Ja, hmmm, ja, ja, ja. Jag ska tro dig... för tillfället. Men vi litar inte lätt på folk, särskilt inte de som kan vara farliga. Du ska veta att Seth och jag kommer att hålla ett öga på dig.}
{122}{Ara_5}{Det är min stad, vandrare. Du måste svara på mina frågor eller ge dig av. Detta är inte en fråga om val.}
{123}{}{Jag behöver inte berätta något för dig.}
{124}{}{Jag menar verkligen inget illa.}
{125}{}{Oroa dig inte, jag ska gå.}
{126}{Ara_6}{Du är ganska oförskämd. Jag tycker att du ska gå. Kom inte tillbaka. Du kommer inte att vara välkommen.}
{127}{Ara_7}{Så får det bli, vandrare. Seth kommer att visa dig ut.}
{128}{Ara_8}{Du måste tro att jag är ganska lättlurad, vandrare. Du besteg bergen på egen hand?}
{129}{}{Det spelar ingen roll vad jag tycker. Det är sant, jag kommer från bergen.}
{130}{}{Nej, bara dum.}
{131}{Ara_9}{Som Dharma sa, 'Försiktighet är livet i oroliga tider.' Ditt ursprung är inte problemet. Det är din avsikt.}
{132}{}{Okej.}
{133}{Ara_9A}{Jag låter dig passera, men du ska veta det här: Seth och jag kommer att hålla ögonen på dig väldigt, väldigt noga. Fundera inte ens på att ta hit problem.}
{134}{Ara_10}{Och behålla dem kan du. Men det här är inte en stad med öppen gästfrihet. Om du vill ha det, gå till Skrotstan. Du kan gå in, men vet att vi har våra ögon på dig.}
{135}{Ara_11}{Ett Valv. Hur ska jag kunna lita på dig, vandrare, när du inte är ärlig mot mig?}
{136}{}{Nej, ärligt talat, jag kommer från ett Valv!}
{137}{}{Valvet är... namnet på min by.}
{138}{}{Du har rätt, jag ljög.}
{139}{Ara_12}{Hmmm, ja, ja, ja. Berätta då om detta valv.}
{140}{}{Valvet är faktiskt namnet på min stad. Vi kallar den det för att den ligger mellan två stora klippor.}
{141}{}{Det är en stor plats som är inbyggd i ett berg långt västerut. Mitt folk har varit där de senaste 80 åren.}
{142}{}{Varför vill du veta det?}
{143}{Ara_13}{Vandrare, jag ska tro dig... för tillfället. Du kan gå in i Shady Sands, men var medveten om att varje steg du tar kommer att bevakas.}
{144}{Ara_14}{Jag tänker inte bli ljugen för, vandrare.}
{145}{}{Jag behöver inte berätta något för dig.}
{146}{}{Jag menar verkligen inget illa.}
{147}{}{Oroa dig inte, jag ska gå.}
{148}{Ara_15}{Hmmm. Du kan gå in. Men håll dig borta från trubbel.}
{149}{}{Vad kan du berätta om de andra städerna häromkring?}
{150}{}{Vad är på gång häromkring?}
{151}{}{Tack. Hej då.}
{152}{Ara_17}{Var hälsad igen, unge vandrare. Jag hoppas att din vistelse här har varit trevlig.}
{153}{}{Det har varit jättebra. Får jag ställa några frågor?}
{154}{}{Det har det. Men jag måste gå.}
{155}{}{Om du gillar avlopp.}
{156}{}{Nähä.}
{157}{Ara_18n}{Var hälsad. Vad kan jag hjälpa dig med denna fina dag?}
{158}{Ara_18b}{Är det något du vill ha?}
{159}{}{Kan du berätta för mig om Shady Sands?}
{160}{}{Jag undrar om jag kan få ställa några frågor till dig?}
{161}{}{Inget, egentligen, jag skulle precis gå.}
{162}{}{Näe.}
{163}{Ara_19}{Javisst. Vad är det du vill veta?}
{164}{Ara_19b}{Ni får fråga, men skynda er. Det finns viktigare saker att göra med min tid.}
{165}{}{Vad kan du berätta om de andra städerna häromkring?}
{166}{}{Vad är på gång häromkring?}
{167}{}{Tack. Hej då.}
{168}{Ara_20g}{Ah. Lycklig resa, vandrare.}
{169}{Ara_20n}{Hej då.}
{170}{Ara_20b}{Det hoppas jag verkligen.}
{171}{Ara_21}{Dharma sa: 'En man och hans egensinniga tunga skiljs snart åt.' Kom tillbaka när du har lärt dig lite hyfs.}
{172}{Ara_22}{Det är alldeles tillräckligt, vandrare. Seth ska visa dig ut ur staden. Återvänd inte. Ditt välkomnande kommer inte att bli trevligt.}
{173}{Ara_23g}{Shady Sands är som en familj, en som håller sig för sig själv.}
{174}{Ara_23b}{Vi är ett mycket skyddande samhälle. Som Dharma sa: 'Många pinnar kan brytas. Ett knippe kan inte det.'}
{175}{}{Vad har ni för saker häromkring?}
{176}{}{Intressant. Finns det några andra städer här i närheten?}
{177}{}{Så gulligt. Tja, det är bäst att jag går.}
{178}{Ara_24}{Trädgårdarna ligger på södra sidan. Inhängningarna för Brahma ligger på norra sidan, men jag är rädd att lukten är ganska intensiv den här tiden på året.}
{179}{}{Nåt annat?}
{180}{Ara_24a}{Vi är små och självförsörjande så det finns inte så mycket mer att berätta.}
{181}{}{Thanks. Can I ask you a few more questions?}
{182}{}{Tack. Hej då.}
{183}{Ara_24b}{It is a small place. You have feet.}
{184}{}{Thanks. Can I ask you a few more questions?}
{185}{Ara_25b}{Dharma said, 'Heed not the call of the wolf when the fox is raiding the hen house.'}
{186}{Ara_25g}{Junktown lies south of here, though there is little in the way of visitation. From stories, I'm certain there are cities south of that.}
{187}{}{Thanks. I... Can I ask you a few more questions?}
{188}{Ara_26}{It is a quiet time, thankfully.}
{189}{}{Sounds... boring.}
{190}{}{Well, then, can I ask you a few more questions?}
{191}{}{Good. Hopefully it will stay that way for a while.}
{192}{Ara_27}{Yes. We like it that way.}
{193}{}{Vad kan du berätta om de andra städerna häromkring?}
{194}{}{Vad är på gång häromkring?}
{195}{}{Tack. Hej då.}
{196}{Ara_28}{Oh my yes. Great packs of radscorpions are killing our herds. We don't know where they're from, and no matter how many we kill, there's always more!}
{197}{}{Go on.}
{198}{Ara_28a}{And now the monsters are attacking my people! Razlo is trying to find a cure for their poison, but I'm not sure how it goes.}
{199}{}{Well, I'll help you get rid of these things!}
{200}{}{I can help you for a price.}
{201}{}{That's terrible. Can I ask you a few more questions?}
{202}{Ara_29}{Ummm, yes, yes, yes, yes, yes! Please talk to Razlo. He possesses far more information on these creatures than I.}
{203}{Ara_30}{As Dharma said, 'Those who tend their own flock, know the shepherd.'}
{204}{}{I know it's hard for you to trust, but I would like to help.}
{205}{}{Your choice. Can I ask you some more questions?}
{206}{Ara_30a}{Please hurry and rid us of those radscorpions!}
{207}{Ara_31}{Things are much more settled now. Razlo has been working on a cure for radscorpion poison, and with that, we should be able to fight what's left of them.}
{208}{}{It was nothing. Can I ask you some more questions?}
{209}{}{You don't need to worry anymore. I destroyed the nest.}
{210}{Ara_32}{You are truly a hero! Know that the people of Shady Sands are most grateful.}
{211}{}{Thanks. Can I ask you a few more questions, though?}
{212}{}{Thanks. Bye!}
{213}{Ara_33}{If you can understand me, please try to find my daughter.}
{214}{Ara_35}{Since you brought my Tandi back to me, things are quite fine. My eternal gratitude to you, wanderer.}
{215}{}{Vad kan du berätta om de andra städerna häromkring?}
{216}{}{Vad är på gång häromkring?}
{217}{}{Tack. Hej då.}
{218}{Ara_36}{Yes, yes. Umm. Have a good stay.}
{219}{Ara_37}{Ahh, wanderer. How goes the search for my daughter?}
{220}{}{Sorry, but I haven't found her. I will, though.}
{221}{}{I'm sorry, but she is dead.}
{222}{}{Öööh... Nada.}
{223}{}{Sorry, but I haven't found her. I will, though.}
{224}{}{Slow, but I am making some progress. Can I ask you a few more questions?}
{225}{}{Guunngggg!}
{226}{Ara_37a}{Thank you for trying. Please leave me to my grief.}
{227}{Ara_38}{May my thoughts be wings to your feet. Please hurry.}
{228}{Ara_39}{Thank goodness you came! I am in desperate need of assistance. My daughter, Tandi, is missing. I do not know what to do!}
{229}{}{Have you tried to save her?}
{230}{}{Ehhh?}
{231}{Ara_39a}{My people are not skilled in this. Already three patrols have gone out to look, but none returned. Will you help me?}
{232}{}{Okay. Who could have taken her?}
{233}{}{I'll do it... for a fee.}
{234}{}{I am sorry, but I have other things I have to do.}
{235}{Ara_40}{Seth and I believe one of the raider clans is responsible - retribution for our resistance to them. Take this spear. It was found where my daughter was last seen.}
{236}{}{Okay, I'll check it out.}
{237}{Ara_40A}{Please, talk to Seth. He knows much about these raiders. And God speed, wanderer.}
{238}{Ara_41}{Of course, I will reward you. Bring her and you will receive 500 in Hub script. Will you help me?}
{239}{}{Okay. Who could have taken her?}
{240}{}{Ah... no thanks. I got other stuff I gotta take care of.}
{241}{Ara_42}{As Dharma said, 'While you are out hunting the wolves, do not bring the lion to your den.' If you will not help, you must leave here.}
{242}{Ara_43}{I will be forever in your debt for your courage and bravery, wanderer. Here is your reward.}
{243}{}{Thanks. Can I ask you a few more questions, first?}
{244}{}{Tack.}
{245}{Ara_44}{Until we meet again, my friend. May the water you find in the desert not shine at you in the dark.}
{246}{Ara_45}{What are you doing? Put that back at once!}
{247}{Ara_46}{That is not yours. Please do not take it.}
{248}{Ara_47}{Stop that at once!}
{249}{Ara_48}{What are you doing here? I am resting, come back in the morning!}
{250}{Ara_49}{I am he. I lead this humble town of Shady Sands.}
{251}{Ara_49A}{Dharma was a great, religious man. You would do well to listen closely to his sayings.}
{252}{Ara_50}{She is my daughter. It is she that makes this hard life worth living.}
{253}{Ara_51}{Hmm, yes, yes. Razlo is our doctor. If it ails you, he can heal it. I would wager he is just a little north of here at this moment.}
{254}{Ara_52}{A fine young man, Seth. Captain of our guards. He is likely to be at the guardhouse.}
{255}{Ara_53}{A wonderful woman. She just celebrated her sixtieth birthday! She spends much time with Razlo, talking his ear off with her veritable treasure trove of stories.}
{256}{Ara_54}{Ummm, um, um. Very bad. There are two bands of raiders that we know of. They call themselves the Vipers and the Khans.}
{257}{Ara_55}{Be very careful with such as these. Raiders who are fanatically religious can be quite dangerous. No one here knows of their base.}
{258}{Ara_56}{Umm, yes, yes. The Khans are nastier than the Vipers, let me tell you. These barbarians attack from the southeast.}
{259}{Ara_57}{Mean creatures, they are. Be careful of their tail. Their poison can be lethal if not looked after.}
{260}{Ara_58}{Yes, yes. yes. It is a rumor of a monster created during the War.}
{261}{}{}
{262}{Ara_60}{Junktown is south of here. Their merchants occasionally come to trade, but not often.}
{263}{Ara_61}{The Vipers and Khans both use spears. We know this from their attacks.}
{264}{Ara_62}{You will find it at the front of town. Seth will likely be there.}
{265}{Ara_63}{No one knows for certain, but the packs seem to be coming from the northeast.}
{266}{Ara_64}{I don't know.}
{267}{Ara_65}{I can't really say I have heard of that.}
{268}{Ara_66}{Hm, no. No, I have not heard of that.}
{269}{Ara_67}{As I said...}
{270}{Ara_68}{Like I mentioned earlier...}
{271}{Ara_69}{Like I said...}
{272}{Ara_70}{As I had told you before...}
{273}{Ara_71}{I shall not repeat myself so often as to make myself sound stupid. Please listen next time.}
{274}{Ara_72}{I will not stand here like a sputtering candle simply because you cannot listen.}
{275}{Ara_73}{Go talk to Seth about that. He'll know more than I.}
{276}{}{}
{277}{}{I will not waste my time on treacherous outsiders.}
{278}{}{Aradesh is furious and refuses to talk to you any more.}
{980}{Ara_64}{I don't know.}
{981}{Ara_65}{I can't really say I have heard of that.}
{982}{Ara_66}{Hm, no. No, I have not heard of that.}
{1000}{}{Aradesh}
{1001}{}{Dharma}
{1002}{}{Tandi}
{1003}{}{Razlo}
{1004}{}{Rädare}
{1005}{}{Huggormarna}
{1006}{}{Khanor}
{1007}{}{Skorpionerna}
{1008}{}{Klo}
{1009}{}{Skrotstan}
{1010}{}{Spjut}
{1011}{}{Guard House}
{1012}{}{Håla}
{1013}{}{Skorpion}
{1014}{}{Vaktstuga}
{1015}{}{Seth}
{1016}{}{rad scorpion}
{1017}{}{Radskorpioner}
{1018}{}{Radskorpion}
{1019}{}{Skuggig}
{1020}{}{Sand}
{1021}{}{Knutpunkt}
{1100}{Ara_49}{I am he. I lead this humble town of Shady Sands.}
{1101}{Ara_49A}{Dharma was a great, religious man. You would do well to listen closely to his sayings.}
{1102}{Ara_50}{She is my daughter. It is she that makes this hard life worth living.}
{1103}{Ara_51}{Hmm, yes, yes. Razlo is our doctor. If it ails you, he can heal it. I would wager he is just a little north of here at this moment.}
{1104}{Ara_54}{Ummm, um, um. Very bad. There are two bands of raiders that we know of. They call themselves the Vipers and the Khans.}
{1105}{Ara_55}{Be very careful with such as these. Raiders who are fanatically religious can be quite dangerous. No one here knows of their base.}
{1106}{Ara_56}{Umm, yes, yes. The Khans are nastier than the Vipers, let me tell you. These barbarians attack from the southeast.}
{1107}{Ara_57}{Mean creatures, they are. Be careful of their tail. Their poison can be lethal if not looked after.}
{1108}{Ara_58}{Yes, yes. yes. It is a rumor of a monster created during the War.}
{1109}{Ara_60}{Junktown is south of here. Their merchants occasionally come to trade, but not often.}
{1110}{Ara_61}{The Vipers and Khans both use spears. We know this from their attacks.}
{1111}{Ara_62}{You will find it at the front of town. Seth will likely be there.}
{1112}{Ara_63}{No one knows for certain, but the packs seem to be coming from the northeast.}
{1113}{Ara_57}{Mean creatures, they are. Be careful of their tail. Their poison can be lethal if not looked after.}
{1114}{Ara_62}{You will find it at the front of town. Seth will likely be there.}
{1115}{Ara_52}{A fine young man, Seth. Captain of our guards. He is likely to be at the guardhouse.}
{1116}{Ara_57}{Mean creatures, they are. Be careful of their tail. Their poison can be lethal if not looked after.}
{1117}{Ara_57}{Mean creatures, they are. Be careful of their tail. Their poison can be lethal if not looked after.}
{1118}{Ara_57}{Mean creatures, they are. Be careful of their tail. Their poison can be lethal if not looked after.}
{1119}{Ara_23g}{Shady Sands är som en familj, en som håller sig för sig själv.}
{1120}{Ara_23g}{Shady Sands är som en familj, en som håller sig för sig själv.}
{1121}{Ara_73}{Go talk to Seth about that. He'll know more than I.}
