{100}{}{You have enraged Barry!}
{101}{}{Du ser: Barry.}
{102}{}{Hey! Only ghouls get a water ration.}
{103}{}{I'm gonna get you for waking me up!}
{104}{}{The mutant ignores you.}
{1000}{}{Kretskort}
{1001}{}{Nekropol}
{1002}{}{Set}
{1003}{}{Vattenskjul}
{1004}{}{Hall}
{1005}{}{Lou}
{1006}{}{Ghouls}
{1007}{}{Normaler}
{1100}{}{I dunno.}
{1101}{}{Yer standin' in it.}
{1102}{}{He's a wuss. We should just wipe him out, and his ghouls.}
{1103}{}{That's here.}
{1104}{}{I dunno.}
{1105}{}{Han Harrys chef.}
{1106}{}{Wimpy things.}
{1107}{}{Wimpier than ghouls.}
