{100}{}{Du ser en vakt.}
{101}{}{I work for the trader here. I make sure nobody messes with him.}
{102}{}{Har du några munkar?}
{103}{}{If you break it, you buy it!}
{104}{}{Shoplifters will be killed!}
{105}{}{Are you gonna buy something? Perhaps in this century?}
{106}{}{Can't fight radscorpions without this stuff.}
{107}{}{I work for the trader here. I make sure nobody messes with him.}
