{100}{}{You see a member of the Blades.}
{101}{}{Hej.}
{102}{}{Hej.}
{103}{}{Have a nice day.}
{104}{}{Nice weather we are having today.}
{105}{}{I wonder if it will rain.}
{106}{}{Have you ever seen the rain glow?}
{107}{}{Måste fortsätta arbeta.}
{108}{}{Vi får inte många främlingar här.}
{109}{}{Gotta go.}
{110}{}{See ya.}
{111}{}{Good day.}
{112}{}{Thanks for your help.}
{113}{}{We won't forget you.}
{114}{}{Nice to have you on our side.}
{115}{}{Things are going to be better now.}
