{100}{}{Detta är en dåligt reparerad spelautomat. Det kostar 10 kapsyler att spela.}
{101}{}{Du lägger 10 kapsyler i spelautomaten och drar i spaken.}
{102}{}{DING! DING! DING!}
{103}{}{Du får tre granater. Utmärkt! }
{104}{}{ kapsyler faller ner i facket och du rycker åt dig dem.}
{105}{}{Ding! Ding! Ding!}
{106}{}{Du får tre kulor. Vinnare! 15 kapsyler faller ner i brickan och du tar upp dem.}
{107}{}{Åhh nej! Du förlorar.}
{108}{}{Du har inte tillräckligt med pengar för att spela.}
