{100}{}{Du ser: Forskare Theslin, från Katedralens Barn.}
{101}{}{Du ser: Forskare Slater, från Katedralens Barn.}
{102}{}{Du ser: Forskare Aunanut, från Katedralens Barn.}
{103}{}{Du ser: Forskare Eikenkoff, från Katedralens Barn.}
{104}{}{Du ser: Forskare Spikavar, från Katedralens Barn.}
{105}{}{Du ser: Forskare Varalone, från Katedralens Barn.}
{106}{}{Du ser: Forskare Quinonos, från Katedralens Barn.}
{107}{}{Du ser: Forskare Ziegliff, från Katedralens Barn.}
{108}{}{Du ser: Forskare Jones, från Katedralens Barn.}
{109}{}{Du ser: Forskare Smithe, från Katedralens Barn.}
{110}{}{Någonstans här omkring finns Anhängarnas planer.}
{111}{}{I am certain that the Followers had a list of all their allies.}
{112}{}{Those fools should have known better than to mess with our god!}
{113}{}{Be gone, lest you end up like those foolish Followers.}
{114}{}{None shall hinder the cleansing of the wastelands.}
{115}{}{We offered them peace. They sought war.}
{116}{}{Where did that foolish ghoul come from?}
{117}{}{Somewhere there has to be a list of all the Followers.}
{118}{}{Unfortunately, we can only search this place during the day.}
{119}{}{We must be wary of the Nightkin, for they search during the darkened hours.}
{120}{}{May you live in interesting times!}
