{100}{}{Du ser ett Barn med en riktig attityd.}
{101}{}{Försvinn ur min åsyn, din jävel!}
{102}{}{Försvinn från mig!}
{103}{}{Vad i helvete vill du?}
{104}{}{Where might I meet this Master?}
{105}{}{För att ta reda på vad som händer häromkring.}
{106}{}{Who's in charge here?}
{107}{}{Hej, ta det lugnt! Låt oss ta en drink!}
{108}{}{För att lägga till dina öron till min samling.}
{109}{}{Jag inte vill till helvete! Dumma man!}
{110}{}{I helvete heller, din nolla.}
{111}{}{Ställer du alltid dumma frågor, din nolla?}
{112}{}{Det är fan inte du, skitstövel.}
{113}{}{Vad får dig att tro att jag vill dricka med dig, din spya!}
{114}{}{Försvinn innan jag dödar dig!}
{115}{}{[Färdig]}
