{100}{}{Du ser en Nattvarelse.}
{101}{}{Dö!}
{102}{}{Lämna mig eller dö!}
{103}{}{Jag gillar inte din ton. Om mitt meddelande inte når fram till Mästaren, ska jag se till att din död blir långsam och smärtsam.}
{104}{}{Jag ville bara ge dig en komplimang för den snygga puckeln på din rygg. Din andedräkt skulle behöva lite arbete, dock...}
{105}{}{Kan du hänvisa mig till mannen som är ansvarig?}
{106}{}{Du skulle behöva en drink mer än jag!}
{107}{}{Jag tänker inte gå!}
{108}{}{Okej. Jag gå.}
{109}{}{Det är oklokt att leka med Nattvarelser. Försvinn härifrån!}
{110}{}{Jag tror inte det.}
{111}{}{Jag ska njuta av att se dig dö!}
{112}{}{Lyssnar du inte? Det är oklokt att ignorera Nattvarelserna.}
{113}{}{Jag måste prata med dig. Det är brådskande!}
{114}{}{Ingen har någonsin anklagat mig för att vara klok!}
{115}{}{Jag vill bara tala med den ansvarige!}
{116}{}{Ska du vara tuff eller?}
{117}{}{Jag är ledsen! Ha en bra dag.}
{118}{}{Vill du veta vad som är oklokt? Det är oklokt att käfta emot, skitstövel!}
{119}{}{Gå upp på övervåningen. Andra av min sort kommer att bedöma värdet av ditt meddelande.}
{120}{}{Detta är din sista varning!}
{121}{}{Jo visst! Det är ingen stor sak...}
{122}{}{Jag måste verkligen tala med den ansvarige!}
{123}{}{Okej! Okej! Jag är ledsen! Ha en bra dag.}
{124}{}{Vet du vad ditt misstag är? Du ger varningar. Det gör jag inte. Dö!}
{125}{}{[Färdig]}
