{100}{}{Du ser: Initierade Ronald, från Katedralens barn.}
{101}{}{Du ser: Initierade Caroline, från Katedralens Barn.}
{102}{}{Du ser: Initierade Myles, från Katedralens Barn.}
{103}{}{Du ser: Initierade Alisha, från Katedralens Barn.}
{104}{}{Du ser: Initierade Thomas, från Katedralens Barn.}
{105}{}{Du ser: Initierade Gabriel, från Katedralens Barn.}
{106}{}{Du ser: Initierade Charlene, från Katedralens Barn.}
{107}{}{Du ser: Initierade Ekdar, från Katedralens Barn.}
{108}{}{Du ser: Initierade Hopper, från Katedralens Barn.}
{109}{}{Du ser: Initierade Radek, från Katedralens Barn.}
{110}{}{Dessa förlorare till Anhängare var lätta att döda.}
{111}{}{Nu när Anhängarna är ur vägen kan ombyggnaden börja.}
{112}{}{I slutet av denna sökning hoppas jag att bli en Skribent eller en Forskare.}
{113}{}{En dag ska jag bli en Forskare och gå ut och predika om Enigheten.}
{114}{}{Orfeo är en svår person att arbeta med.}
{115}{}{Jag är fortfarande rädd för Nattvarelserna.}
{116}{}{De Äldre sa att Nattvarelserna är våra allierade.}
{117}{}{Go away.}
{118}{}{Jag gillar inte din sort.}
{119}{}{Om du har problem med Set, så har du problem med mig.}
{120}{}{Frid vare med dig. Var snäll och prata med Laura.}
{121}{}{Laura lärde mig att vi alla är en och samma folk och att vi ska se det goda i dem. Hon är mycket klok.}
{122}{}{Laura är en klok och underbar person.}
{123}{}{Du ser en av akrolyterna från Katedralens Barn.}
