{100}{}{Du ser en hängiven medlem från Katedralens Barn.}
{101}{}{Vi erbjuder läkning av kroppen för att läka själen. Kan jag hjälpa dig?}
{102}{}{Ja. Hjälp mig.}
{103}{}{Vilka är ni?}
{104}{}{Uhn.}
{105}{}{Det är bra, mitt barn. Vi ska undersöka dig nu.}
{106}{}{Välsignade är de ödmjuka i sinnet. Det är inget fel på dig, mitt barn. Spring iväg och lek.}
{107}{}{Du har blivit helad. Var mer försiktig i framtiden.}
{108}{}{Du är skadad.}
{109}{}{Du är inte skadad. Det är bra.}
{110}{}{Jag ser att du är förgiftad.}
{111}{}{Hmm, lite strålningsförgiftning. Tyvärr kan vi inte bota det.}
{113}{}{Vi kräver en donation på }
{114}{}{ kapsyler innan vi kan läka dig. Är det acceptabelt?}
{115}{}{Ja.}
{116}{}{Nej.}
{117}{}{Men jag har inte så där mycket pengar!}
{118}{}{Kan du ta }
{119}{}{ kapsyler?}
{120}{}{Barnen förhandlar inte priser. Accepterar ni vårt pris?}
{121}{}{Ja, det är klart att jag gör.}
{122}{}{Nej, tack.}
{123}{}{Tack, min son. Låt oss be för ditt helande.}
{124}{}{Tack, min dotter. Låt oss be för ditt helande.}
{125}{}{Så där ja. Frid och välsignelser från Barnen följer med dig.}
{126}{}{Du har inte tillräckligt med pengar. Om du donerar allt du kan, kommer vi att läka dig. Är det här acceptabelt?}
{127}{}{Ja.}
{128}{}{Nej.}
{129}{}{Om du donerar allt du kan, kommer vi att läka dig. Är det här acceptabelt?}
{130}{}{Ja.}
{131}{}{Nej.}
{132}{}{Du har mer än tillräckligt för att göra en donation. Du behöver undervisning i matematik, mitt barn.}
{133}{}{Vi är Katedralens Barn. Vi lever och arbetar bland de olyckliga som lever i ödemarken. Om du någonsin kommer till L.A. Bengård, stanna till vid katedralen.}
{134}{}{Tack.}
{135}{}{What do you do?}
{136}{}{Vi är helare och fredens lärare. Vi läker kroppen för att läka anden. Allt vi ber om är en liten donation för att betala för våra helande förnödenheter.}
{137}{}{Jag tycker att det låter som en bra idé.}
{138}{}{Det låter som en massa skit, om du frågar mig.}
{139}{}{Vi har inte frågat dig. Jag kan se att du är trött på att lyssna på vår tro. Om du behöver något annat, kommer vi att vara här.}
{140}{}{Det är den heligaste av idéer. Vi arbetar för att uppnå slutlig fred i ödemarken. Alla varelser ska leva som en enda.}
{141}{}{Tack. God dag.}
{142}{}{Vi har inte tid att prata. Vi ska gå nu. Den här platsen är farlig för oss.}
{143}{}{Varför gör du detta? Vi kommer inte att göra er någon skada!}
{1000}{}{Katedral}
{1001}{}{Mutanter}
{1002}{}{Mästare}
{1003}{}{Bengård}
{1004}{}{Följare}
{1005}{}{Kretskort}
{1006}{}{Apokalyps}
{1007}{}{Nekropol}
{1008}{}{Set}
{1009}{}{Vattenskjul}
{1010}{}{Hall}
{1011}{}{The Boneyard}
{1012}{}{L.A. Boneyard}
{1100}{}{Det är vi.}
{1101}{}{They are people who got mutated from the nuclear fallout. But they are still good people.}
{1102}{}{Vi har alla våra mästare, eller hur?}
{1103}{}{L.A. Boneyard is a breeding ground of hatred. There are the Followers of the Apocalypse, the gangs: The Rippers, The Blades, and The Gun Runners, and a small settlement called Adytum. }
{1104}{}{De är människor som försöker förstöra den fred som Mästaren försöker skapa.}
{1105}{}{Jag har ingen aning om vad du pratar om.}
{1106}{}{De är människor som försöker förstöra den fred som Mästaren försöker skapa.}
{1107}{}{Det är här. De sorgliga resterna av en forntida värld.}
{1108}{}{Jag tror att han är en av ghulerna.}
{1109}{}{Det är där borta i nordost.}
{1110}{}{Jag vet ingenting om det.}
{1111}{}{L.A. Boneyard is a breeding ground of hatred. There are the Followers of the Apocalypse, the gangs: The Rippers, The Blades, and The Gun Runners, and a small settlement called Adytum. }
{1112}{}{L.A. Boneyard is a breeding ground of hatred. There are the Followers of the Apocalypse, the gangs: The Rippers, The Blades, and The Gun Runners, and a small settlement called Adytum. }
