{100}{}{Du ser ett litet barn.}
{101}{}{Hej!}
{102}{}{Hej.}
{103}{}{Where are your parents?}
{104}{}{Erf.}
{105}{}{I dunno. Around here somewhere.}
{106}{}{You're funny!}
{107}{}{Hey, are you gonna kill someone?}
{108}{}{Ja.}
{109}{}{Nej!}
{110}{}{Erf.}
{111}{}{I'm gonna tell my mommy!}
{112}{}{Then you shouldn't carry around a weapon like that.}
{200}{}{Sorry, mister.}
{201}{}{Sorry, ma'am.}
{300}{}{You see: Boy.}
{301}{}{You see: Girl.}
{980}{}{Vadå?}
{981}{}{I dunno. Ask mommy.}
{982}{}{Ask daddy.}
{1000}{}{Dödsklo}
{1001}{}{Rädare}
{1002}{}{Skrotstan}
{1003}{}{Brahmin}
{1004}{}{Kretskort}
{1005}{}{Köpmän}
{1006}{}{Khanor}
{1007}{}{Garl}
{1008}{}{Shady Sands}
{1009}{}{Knutpunkt}
{1010}{}{Tandi}
{1011}{}{Aradesh}
{1012}{}{Seth}
{1013}{}{Razlo}
{1014}{}{Police}
{1015}{}{Karavaner}
{1016}{}{Handlare}
{1017}{}{Children}
{1018}{}{Nekropol}
{1019}{}{Spot}
{1020}{}{Brödraskap}
{1021}{}{Bengård}
{1022}{}{Towers}
{1023}{}{Stad}
{1024}{}{Downtown}
{1025}{}{Höjder}
{1026}{}{The Boneyard}
{1027}{}{L.A. Boneyard}
{1100}{}{Wah! Nightmare monster!}
{1101}{}{Big meanies!}
{1102}{}{I dunno.}
{1103}{}{Big stinkies.}
{1104}{}{Ask mommy.}
{1105}{}{Funny sea songs.}
{1106}{}{Big meanies!}
{1107}{}{Bad man.}
{1108}{}{I'm not tellin' ya.}
{1109}{}{Big city.}
{1110}{}{I'm not tellin'.}
{1111}{}{Nope, not gonna tell ya.}
{1112}{}{Mommy doesn't want me to talk about him.}
{1113}{}{Daddy thinks he's funny.}
{1114}{}{Big peoples.}
{1115}{}{They have those stinkies that pull them.}
{1116}{}{Nice people. They give me candy.}
{1117}{}{They don't like to play hide and seek.}
{1118}{}{Scary place.}
{1119}{}{Yucky place.}
{1120}{}{Scary place.}
{1121}{}{Scary place.}
{1122}{}{Mommy won't let us play there.}
{1123}{}{Daddy keeps telling us to play there.}
{1124}{}{Big people area.}
{1125}{}{Big people area.}
{1126}{}{Scary place.}
{1127}{}{Scary place.}
