{100}{}{Du ser en tekniker från Katedralens Barn.}
{101}{}{Släpp era vapen och Nattvarelserna kommer att låta er leva.}
{102}{}{Nattvarelse, ta den här dåren till fånge. Vår mästare kommer att bli nöjd.}
{103}{}{Gå med oss, slåss inte mot oss.}
{104}{}{Du kommer att bli ett med Enigheten!}
{105}{}{Snälla, döda mig inte. Jag jobbar bara här.}
{106}{}{Du skulle väl inte döda en obeväpnad man? Eller hur?!}
{107}{}{Jag ger upp!}
{108}{}{Du har ingen rätt att vara här. Vad vill ni?}
{109}{}{Hne.}
{110}{}{Vem är du?}
{111}{}{Era sjuka svin! Jag är trött på era liv!}
{112}{}{Vad är det här för ställe?}
{113}{}{Du är nästan en Nattvarelse nu. Jag hoppas att doppningen inte skadar din intelligens ytterligare.}
{114}{}{Jag är en del av Enigheten. Jag är en ärofull tjänare till vår Mästare. Jag kommer att vara den som ser dig bli en del av Enigheten.}
{115}{}{Du kommer att få reda på det snart nog.}
{116}{}{Detta är födelseplatsen för den överlägsna rasen! Detta är livmodern från vilken Guds arméer kommer att slå till! Från de svagas kött kommer nästa människoras. De som överlever doppningen kommer att bli Guds soldater, och med deras händer ska vi forma Enigheten.}
{117}{}{Du är galen! Du är helt enkelt knäpp! Dö!}
{118}{}{Hur fungerar det?}
{119}{}{You will be bound in the holy restraints. We will lower you into a vat of the blood of god, the holiest of holies. The FEV will shape and change you. You will be strong. You will become a Nightkin if you are fortunate and worthy of the honor, else you will die the most painful death possible. Soon, I will be honored. I will become strong. Then I will fear no man.}
{120}{}{Du har varit med Nattvarelserna alldeles för länge. Adjö.}
{121}{}{Och varför berättar du det här för mig?}
{122}{}{Where did you get the FEV from?}
{123}{}{Du kommer bara att gå härifrån som en del av Enigheten, eller som en förlorad själ i helvetet! (Teknikern pausar ett ögonblick) Dessutom sitter jag här med ett gäng konverterade. Det kändes bra att få ur mig det här.}
{124}{}{Where did you get the FEV from?}
{125}{}{Du dödade Guds Högra Hand. Mästaren kommer att bli mycket upprörd. Nu har det blivit dags för oss att ansluta oss till den Heliga Flamman!}
{126}{}{Du dödade Mästaren. Enighetens död är ditt fel. Du har orsakat mänsklighetens död. Jag hoppas att du känner dig nöjd med dig själv.}
{127}{}{Hnnn.}
{128}{}{Faktum är att jag gör det.}
{129}{}{Du kommer att göra honom sällskap om en stund. Be till den gud som tog hans plats.}
{130}{}{Jag går för att ansluta mig till honom nu, i de Heliga Lågorna!}
