{100}{}{Du ser en mörkhyad man utsmyckad med ljusa halsdukar och prydnadssaker.}
{101}{}{Du ser: Chuck, zigenarspåmannen.}
{102}{}{Hej, främling. Kan jag stå till tjänst?}
{103}{}{Uugh!}
{104}{}{Jag ser mig bara omkring, tack.}
{105}{}{Jag lär känna folket i Adytum.}
{106}{}{Varför antar du att jag behöver något?}
{107}{}{Hmm. Oroa dig inte, min simple vän, du har stora saker framför dig.}
{108}{}{Och vad tycker du om vår stad?}
{109}{}{Den är okej.}
{110}{}{Tycker inte om det så mycket. Inte alltför vänlig.}
{111}{}{Du har gjort anmärkningsvärt bra ifrån dig, med tanke på de svåra omständigheterna.}
{112}{}{Jag heter Chuck. Välkommen till Adytum. Jag är dock rädd att de flesta här inte är så tillmötesgående mot främlingar.}
{113}{}{Ja, jag märkte det.}
{114}{}{Så, vad är ditt jobb, Chuck?}
{115}{}{Vi ses, Chuck.}
{116}{}{God resa, vandrare.}
{117}{}{We all need something, don't we? And you wouldn't have talked to me if you didn't want something, whether it be information, conversation, or perhaps guidance. I can tell that you've been through a lot. What do you need?}
{118}{}{Uh, I don't need anything, thanks.}
{119}{}{Now that you mention it, perhaps you can give me some advice.}
{120}{}{(Chuck pulls out a set of Tarot cards.) Let me consult the cards. (He shuffles the cards.)}
{121}{}{(Chuck pulls out a card with a picture of a man in a lab coat with a computer in one hand, and another card with a man in Power Armor.) The Hierophant and the Prince of Wands in the southeast... great wisdom and nobility await in a place to the southeast.}
{122}{}{(Chuck pulls out a card with a picture of a man with a vibro-knife and a flag.) The Prince of Swords in the northwest... you must face a powerful foe far to the northwest.}
{123}{}{(Chuck pulls out a card with a picture of a radio tower, and another card with a picture of a man in a suit with a scepter.) The Tower and the Emperor... great change awaits by the hands of a powerful leader. Whether that change is death, I cannot tell.}
{124}{}{(Chuck pulls out a card with a picture of a man dancing on a nuclear warhead.) The Fool. I cannot help you; you must make your own way in the world.}
{125}{}{[Mer]}
{126}{}{Hmm. Thanks for the advice.}
{127}{}{Do you actually believe this stuff?!}
{128}{}{It works for me. If you don't want to believe then it's not for you.}
{129}{}{No offense, but it sounds like a load of superstition.}
{130}{}{Well, I guess we each have our own beliefs.}
{131}{}{If that is how you feel, then I suppose we have nothing more to discuss.}
{132}{}{Indeed, we do. And your universe is shaped by your beliefs, while my universe is shaped by my thoughts. We may not share beliefs, but I wish you well in your universe.}
{133}{}{It is home.}
{134}{}{Uh, yeah. See you around.}
{135}{}{Things do seem a little quiet around here.}
{136}{}{I know what you mean. I've seen a lot of suffering.}
{137}{}{The Regulators make sure of that. The people of Adytum sometimes suffer because of their strict rules.}
{138}{}{I guess so. Well, see you around.}
{139}{}{Och du är okej med det här?}
{140}{}{Eftersom jag vill stanna här accepterar jag Reglerarna som en del av det som är Adytum. Men jag gör vad jag kan för att göra deras liv lättare.}
{141}{}{Du verkar inte hålla med om vad de gör.}
{142}{}{Finns det något annat du kan göra?}
{143}{}{Reglerarna skyddar sina egna intressen, och det måste jag respektera.}
{144}{}{Ja, ja, sak samma.}
{145}{}{Jag håller inte nödvändigtvis med om den uppfattningen, men jag kan förstå den.}
{146}{}{Det har varit trevligt att prata. Vi ses.}
{147}{}{Jag är bara en person, men jag kan hjälpa till på det sätt jag kan. Jag råder dig att kämpa för det du tror på, men framför allt, välj de strider som är värda att utkämpa och hitta de tillfällen då kompromiss och hopp kommer att vinna större segrar.}
{148}{}{Har du några andra råd?}
{149}{}{Människorna i Adytum har mycket att göra under en vanlig dag. De vill inte att deras arbete ska vara oavslutat i slutet av dagen.}
{150}{}{Ja, ja, hur som helst.}
{151}{}{Things do seem a little quiet around here.}
{152}{}{Tack. Det har varit svårt. Vi förlorar människor till Dödsklorna ibland, och vintrarna kan vara svåra, särskilt när handlare från Hubben inte kommer. Men vi överlever.}
{153}{}{Lycka till.}
{154}{}{Vad händer med Dödsklorna?}
{155}{}{De härjar i ett område nordost härifrån och kan ofta ta livet av människor som får i uppdrag att handla med Vapensmugglarna.}
{156}{}{Förhoppningsvis kommer du att hitta en lösning.}
{157}{}{Ja, ja. Sak samma.}
{158}{}{Kanske det. Jag tror att Adytum kommer att vara här. Istället för att gå till världen, måste världen komma till oss, som du har gjort.}
{159}{}{Hmm. Jag antar det.}
{160}{}{Jag är bonde. Jag tycker också om att arbeta lite med byggnaderna, restaurera dem och hålla dem intakta, och ibland ger jag råd.}
{161}{}{Vad för slags råd?}
{162}{}{Ja, tyvärr. Jag tror... att det är en slags smältdegel, att vi genom att överleva dessa svåra tider kommer att förlita oss på varandra och lära oss de färdigheter vi behöver för att överleva. Jag tror att mänskligheten så småningom kommer att bli bättre av det.}
{163}{}{Jag håller inte med. Jag har stött på många gäng och plundrare under mina resor. De har blivit småsinta mördare och tjuvar. Jag tror att vi alla riskerar det så småningom.}
{164}{}{Du kanske har rätt. De som överlever kommer säkert att vara starkare.}
{165}{}{De kommer så småningom att förgöra sig själva. Och de som blir kvar kommer att vara de som samarbetar för att överleva, som vi.}
{166}{}{Jag är glad att några av de utomstående, som du, känner så. Vi måste hitta sätt att arbeta tillsammans för att bygga upp något nytt. Det kommer inte att börja här, vi är för reglerade, men det måste börja någonstans.}
{167}{}{Hej, vad kan jag göra för dig?}
{168}{}{Kan jag hjälpa dig?}
{169}{}{Ja?}
{170}{}{Jag tittar bara förbi för att säga hej.}
{171}{}{Jag letar efter lite råd.}
{172}{}{Får jag fråga vad du gör här?}
{173}{}{Hejsan. Jag hoppas att du mår bra.}
