{100}{}{Du ser: Cindy.}
{101}{}{Hon gråter.}
{102}{}{Hej, }
{103}{}{. Har du hittat vattenchipet än?}
{104}{}{Inte än. Jag har inte haft mycket tur.}
{105}{}{Ingen tur än, men jag vet att jag kommer att hitta den. Förresten, hur är det med dig?}
{106}{}{Urug!}
{107}{}{Du förstår mig inte. Jag antar att vi inte har mycket hopp trots allt. Ursäkta mig medan jag gråter.}
{108}{}{Ugg!}
{109}{}{Snälla, hitta det innan vi dör av törst.}
{110}{}{Du måste hitta den! Låt oss inte dö så här!}
{111}{}{Keep trying. I believe in you. I know you will do everything you can to save us.}
{112}{}{Who do you think might be involved?}
{113}{}{I am afraid of what is happening. Someone has been stealing water and now everyone is on edge.}
{114}{}{Who would do such a thing?}
{115}{}{What happened?}
{116}{}{Some people have been accused and fights have broken out over it, but nobody really knows.}
{117}{}{Okay. Thanks.}
{118}{}{Some people reported that their water had been stolen. They weren't given more water, but some friends shared with them. After that, everybody got very paranoid and started guarding their water. A few days later, someone knocked out the guard in the ration supply area and stole water rations from the supply lockers.}
{119}{}{That's terrible! What can I do?}
{120}{}{Maybe you can stop whomever is doing this.}
{121}{}{I'll take a look around.}
{122}{}{You're the water thief?! How could you?}
{123}{}{Thank you so much for saving us all.}
{124}{}{You did a good job catching the thief. Please hurry and find the Water Chip.}
{125}{}{How could you betray us? Now everyone here will die! But you don't care, do you?}
{126}{}{I'm scared. I don't know what will happen to us all. Please, don't let us down.}
{127}{}{Don't worry, I'll do my best. You'll be all right.}
{128}{}{Ja, ja, sak samma.}
