{100}{}{Du ser: Savil, en av Anhängarnas vakter.}
{101}{}{Du ser: Nancy, en av Anhängarnas vakter.}
{102}{}{Du ser: Jelissa, en av Anhängarnas vakter.}
{103}{}{Du ser: Lynda, en av Anhängarnas vakter.}
{104}{}{Du ser: Jessica, en av Anhängarnas vakter.}
{105}{}{Du ser: Shannon, en av Anhängarnas vakter.}
{106}{}{Du ser: Mohandki, en av Anhängarnas vakter.}
{107}{}{Du ser: Percy, en av Anhängarnas vakter.}
{108}{}{Du ser: Henry, en av Anhängarnas vakter.}
{109}{}{Du ser: Herion, en av Anhängarnas vakter.}
{110}{}{Vem vandrar i Anhängarnas salar?}
{111}{}{Vadå?}
{112}{}{I am }
{113}{}{. Jag kommer i fred.}
{114}{}{I am }
{115}{}{. Din förgörare.}
{116}{}{Who are the Followers?}
{117}{}{Okej. Jag ser att du är lite långsam. Vem du?}
{118}{}{Jag }
{119}{}{. Du död.}
{120}{}{Jag }
{121}{}{. Jag häp.}
{122}{}{Jag döda!}
{123}{}{Jag }
{124}{}{. Jag gå.}
{125}{}{Vill du hjälpa till? Jag tror att du måste prata med Nicole eller Jake om du vill hjälpa oss. De har mer tid att ta hand om långsammare människor.}
{126}{}{Okej. Håll dig bara borta från trubbel här.}
{127}{}{Kom du för att göra slut på Barnens ondska?}
{128}{}{Ja. Jag vill utplåna de där avskummen.}
{129}{}{Nej. Jag dödar hellre er mesar.}
{130}{}{Vilka är dessa Barn?}
{131}{}{Varför skulle jag vilja döda barn?}
{132}{}{Utmärkt! Gå och prata med Nicole så kan hon berätta hur du kan hjälpa oss.}
{133}{}{Barnen är en ockult grupp som dyrkar någon mörk gud. Personligen tycker jag att det är något med dem som osar av ondska.}
{134}{}{Jag ska döda dem.}
{135}{}{Jag vet inte. De låter för starka för mig.}
{136}{}{Vad kan jag göra för att hjälpa till?}
{137}{}{Glöm det! Det finns inte en chans att jag kommer att hjälpa er.}
{138}{}{De är ett starkt gäng, men jag tror att du med dina kunskaper kan ta dig in och hjälpa oss att förgöra dem.}
{139}{}{Jag ska göra det då.}
{140}{}{Nej, jag tror inte att jag kommer att hjälpa till.}
{141}{}{Skyll dig själv. Om de tar över ödemarkerna, säg inte att vi inte varnade er.}
{142}{}{Om du pratar med Nicole kan hon berätta mer om vad som kan göras för att stoppa dem.}
{143}{}{Tack. Hej då.}
{144}{}{Inte barn. Vi skulle inte kunna tänka oss att skada dem. Nej. Det här är Katedralens Barn. En otäck grupp människor.}
{145}{}{In that case, sure - I'll waste them.}
{146}{}{Jag trodde att du pratade om barn. Jag trodde att du pratade om barn. Strunt samma. Jag tror inte att jag kan hjälpa till.}
{147}{}{Vad kan du berätta för mig om dessa Barn?}
{148}{}{Vi är Apokalypsens Anhängare. Vi försöker bringa fred till ödemarkerna.}
{149}{}{Låter som en bra idé. Lycka till med den.}
{150}{}{Hur planerar du att göra det?}
{151}{}{Det verkar högst osannolikt.}
{152}{}{Vi arbetar för att skapa tolerans för dem som lever i ödemarkerna, för de få olyckliga som har muterats av människans destruktiva natur.}
{153}{}{Lycka till med det.}
{154}{}{In all of history, we have never been able to become tolerant. Why do you think the War happened?}
{155}{}{That's just a bunch of bull.}
{156}{}{You are right in saying that we, as humans, have been close-minded. However, there is always hope.}
{157}{}{Good luck to you, then.}
{158}{}{I think you are right. Here, let me make you more open-minded with this.}
{159}{}{Be that as it may, your opinion was not requested. Goodbye.}
{160}{}{A cynic in our midsts. I am sure you have your reasons. Regardless, I am certain we can bring about some type of understanding.}
{161}{}{Good luck to you then. Goodbye.}
{162}{}{I've heard that the Children have been able to get some of our secrets. I wonder how that is happening?}
{163}{}{I believe that there is a spy somewhere around here.}
{164}{}{I know. I am selling your secrets to them.}
{165}{}{I am sure you are just imagining things. How can they know anything?}
{166}{}{Truly? I thought as much myself, but feared that I would never have been able to get much support on the theory.}
{167}{}{Do you have any clues as to whom it could be?}
{168}{}{I'm glad to know that. Thanks for your time.}
{169}{}{You are the double agent!!!}
{170}{}{Not really. The only thing I can think of is that the person would have to have access to some information and have access to the outside. You might want to look to the initiates or scouts.}
{171}{}{Thanks. Goodbye.}
{172}{}{Nicole will be pleased then, to know that I killed the agent.}
{173}{}{You must be right. Thank you for setting me straight.}
{174}{}{I think you are the double agent. Trying to trick me, I see. Well now you DIE!}
{175}{}{Great job on wasting that agent. Now we might have a chance against those Children.}
{176}{}{Good luck to you.}
{177}{}{I can help train you to become a more efficient fighter.}
{178}{}{Would you? That would be wonderful.}
{179}{}{There you go. Maybe that will help you, if you get into a fight.}
