{100}{}{Du ser en stor, välbeväpnad man.}
{101}{}{Du ser: Gabriel, ledare för Vapensmugglarna.}
{102}{}{Det är inte ofta vi får besök. Hur kan jag hjälpa dig?}
{103}{}{Varför får ni inte många besökare?}
{104}{}{Vad gör ni här?}
{105}{}{Det här stället är inte särskilt tillgängligt med ett näste av de där jävla Dödsklorna precis utanför vår fabrik.}
{106}{}{Ni verkar ganska välbeväpnade, varför går ni inte och utrotar dem?}
{107}{}{Vi har varit där och dödat några, men de verkar alltid komma tillbaka. Dessutom är vi maskinister, inte krigare.}
{108}{}{Vad skulle du ge mig om jag gick in och tog hand om dem åt dig?}
{109}{}{Vi tillverkar vapen och ammunition. Vi har hållit på med det här de senaste 30 åren. Men de senaste 10 har varit ett helvete.}
{110}{}{Why is that?}
{111}{}{Vi har tömt området kring vår fabrik på allt metallskrot som fanns kvar efter kriget. Nu måste vi förlita oss på att Adytum förser oss med råmaterial.}
{112}{}{Vad är det som är så dåligt med att Adytum förser er med material?}
{113}{}{Till en början var det bra. De försåg oss med råmaterial, vi tillverkade och sålde vapnen. Sedan, för tre år sedan, anlitade Zimmerman några legosoldater för att skydda Adytum från dödsklorna och enstaka slumpmässiga attacker från plundrare. Reglerarna är kallhjärtade jävlar och pressar oss på allt vi har. Vi tillverkar vapnen och de blir rika på det.}
{114}{}{Varför flyttar ni inte bara och börjar om nån annanstans?}
{115}{}{Det låter hemskt. Vad skulle du ge mig för att ta hand om dödsklorna?}
{116}{}{Vi skulle göra det om vi kunde, men det är ett stort åtagande att flytta med alla svarvar och verk. Det här är saker som inte bara kan plockas upp och lätt flyttas. Vi skulle kunna flytta, men dödsklorna gör det omöjligt.}
{117}{}{Ni verkar ganska välbeväpnade, varför går ni inte och utrotar dem?}
{118}{}{Om du kunde bli av med dödsklorna en gång för alla, skulle du kunna bestämma ditt pris.}
{119}{}{Jag vill ha vapen och ammunition, och massor av det.}
{120}{}{}
{121}{}{Om ni rensar ut det området kommer vi att åka, men vi kommer att lämna kvar mer vapen och ammunition än ni någonsin kan använda.}
{122}{}{Okej. Vi är överens.}
{123}{}{Jag måste fundera på det.}
{124}{}{Människor som skulle lösa alla era problem med Adytum.}
{125}{}{Om du rensar ut dödsklorna, allihop, så är vi överens.}
{126}{}{Okej. Jag ska göra det.}
{127}{}{Jag måste fundera på det.}
{128}{}{Hello again.}
{129}{}{Vad gör ni här?}
{130}{}{Hej då.}
{131}{}{}
{132}{}{Det har gått bra.}
{133}{}{Jag tror att jag har dödat alla dödsklor.}
{134}{}{Vi måste vara säkra. Vi har dödat över 20 de senaste två åren och de verkar alltid komma tillbaka. Vi kunde aldrig räkna ut hur. Vi väntar några dagar och om de fortfarande är borta så ska vi se vad vi kan göra för er.}
{135}{}{Okej, tack}
{136}{}{Säg till när du har tagit hand om dödsklorna.}
{137}{}{Ja, det gör jag. Vi ses kanske.}
{138}{}{Jag vet, berätta om det.}
{139}{}{Vi ses, kanske.}
{140}{}{Det är inte ofta vi får besök. Kan jag hjälpa dig?}
{141}{}{Varför får ni inte många besökare?}
{142}{}{Vad gör ni här?}
{143}{}{Det här stället är inte särskilt tillgängligt med ett näste av de där jävla Dödsklorna precis utanför vår fabrik.}
{144}{}{Jag har dödat alla Deathclaws. Till och med alla jävla ägg.}
{145}{}{Vi skulle göra det om vi kunde, men det är ett stort åtagande att flytta med alla svarvar och verk. Det här är saker som inte bara kan plockas upp och lätt flyttas. Vi skulle kunna flytta, men dödsklorna gör det omöjligt.}
{146}{}{Jag har dödat alla Deathclaws. Till och med alla jävla ägg.}
{147}{}{}
{148}{}{Jag vill ha vapen och ammunition, och massor av det.}
{149}{}{}
{150}{}{Ni behöver inte betala mig. Era tack är tillräckligt.}
{151}{}{Det blir bra - Bara vad du vill ha. Vi drar härifrån om en dag eller två, men vi lämnar kvar mer vapen och ammunition än du kan bära just nu. Kom bara tillbaka hit när du behöver dem.}
{152}{}{}
{153}{}{}
{154}{}{Tack.}
{155}{}{}
{156}{}{No problem.}
{157}{}{}
{158}{}{}
{159}{}{Skulle inte ni flytta?}
{160}{}{Jag är bara här för att hämta några saker. Vad har ni idag?}
{161}{}{Ingenting. Tack ändå.}
{162}{}{}
{163}{}{Jättebra. Vad har ni för något idag?}
{164}{}{Vi ses senare.}
{165}{}{}
{166}{}{Jag är bara här för att hämta några saker. Vad har ni idag?}
{167}{}{Ingenting. Tack ändå.}
{168}{}{Ledsen att jag inte kan prata med dig nu, jag är väldigt upptagen.}
{169}{}{Vapen! Jag gillar vapen!}
{170}{}{Jag har några vänner som verkligen kan behöva några av era vapen.}
{171}{}{Jag har några vänner som verkligen kan behöva några av era vapen.}
{172}{}{Hur går det, min vän?}
{173}{}{Hur går det, min vän?}
{174}{}{Du vad?! Har du dödat dem alla? Tacka gudarna! Nu kan vi flytta till en ny plats, där vi kan få våra egna material och inte behöver förlita oss på de där ormarna i Adytum. Säg vad du vill ha, så får du det, min vän.}
{175}{}{Du vad?! Har du dödat dem alla? Tacka gudarna! Nu kan vi flytta till en ny plats, där vi kan få våra egna material och inte behöver förlita oss på de där ormarna i Adytum. Säg vad du vill ha, så får du det, min vän.}
{176}{}{Låter bra. Det har varit ett nöje att göra affärer med dig, min vän.}
{177}{}{Låter bra. Det har varit ett nöje att göra affärer med dig, min vän.}
{178}{}{Du har det. Låt dina vänner veta att de får sina vapen.}
{179}{}{Du har det. Låt dina vänner veta att de får sina vapen.}
{180}{}{Tack min vän.}
{181}{}{Tack min vän.}
{182}{}{Ledsen att jag inte kan prata med dig, vän, men vi är upptagna med att packa för att flytta. Ta för dig av vad du behöver.}
{183}{}{Ledsen att jag inte kan prata med dig, vän, men vi är upptagna med att packa för att flytta. Ta för dig av vad du behöver.}
{184}{}{Det finns ingen anledning att flytta nu när dina vänner har gjort sig av med de förbannade Reglerarna.}
{185}{}{Det finns ingen anledning att flytta nu när dina vänner har gjort sig av med de förbannade Reglerarna.}
{186}{}{Välkommen, min vän. Vad kan jag hjälpa dig med?}
{187}{}{Välkommen, min vän. Vad kan jag hjälpa dig med?}
{188}{}{Du måste prata med Zack om att köpa saker.}
