{100}{}{It's a slot machine with a picture of a nuclear explosion on the side. Sweet! It costs 20 caps to play.}
{101}{}{You drop 20 caps into the slot machine and pull the greasy handle.}
{102}{}{DING! DING! DING!}
{103}{}{You get three nukes. Excellent! }
{104}{}{ kapsyler faller ner i facket och du rycker åt dig dem.}
{105}{}{Ding! Ding! Ding!}
{106}{}{You get three bombs. Winner! 30 caps drop into the tray and you snatch them up.}
{107}{}{Aww shucks! You lose.}
{108}{}{Du har inte tillräckligt med pengar för att spela.}
