{100}{}{You see a burly bounty hunter with a button that reads, "I'm Christopher and you're meat."}
{101}{}{Vad vill du?}
{102}{}{A doughnut.}
{103}{}{What are you doing here?}
{104}{}{Just looking around.}
{105}{}{Ingenting.}
{106}{}{We don't appreciate wise guys here. Buzz off.}
{107}{}{That joke wasn't even funny the first time. You're about to discover why I'm one of the most fearsome bounty hunters in the wasteland. And I won't even get paid for it.}
{108}{}{Det angår inte dig.}
{109}{}{Well, go poke around somewhere else.}
{110}{}{Did you know that there's a bounty of }
{111}{}{(He looks you over, carefully, considering something. It seems he's made a decision already.) Tell me, how often do you visit The Hub or Junktown?}
{112}{}{Often enough, why do you ask?}
{113}{}{Well, you see... business takes almost all of my time and I don't have an opportunity to get there. And as an incurable smoker I miss an old Zippo lighter very much. It's said, many of those pre-War items can be found in the shops there. If you get a Zippo for me, I'll share some information about the neighboring settlements. I think it could be of use!}
{114}{}{It's a pity. Looks like I made a mistake about you. Get out of here.}
{115}{}{Sure, why not? I'll get one for you.}
{116}{}{Okej.}
{117}{}{Hey, I have one right here. I don't really need it and can give it to you in exchange for the information.}
{118}{}{Thank you! (He takes the lighter.) So, what do you want to hear, exactly?}
{119}{}{Here is your lighter. Time to give me some information.}
{120}{}{Inga fler frågor, tack.}
{121}{}{[Mer]}
{122}{}{Vad mer vill du veta?}
{123}{}{Jag behöver lite information.}
{124}{}{Buuhhh.. Wuh?}
{125}{}{Are you serious? Get out of my sight.}
{126}{}{I'm going to do the world a favor by putting a bullet through your skull.}
{200}{}{ caps on your head for killing children? Time to collect!}
