{100}{}{Vi erbjuder läkning av kroppen för att läka själen. Kan jag hjälpa dig?}
{101}{}{Ja. Hjälp mig.}
{102}{}{Vilka är ni?}
{103}{}{What happened to the people who were here before you?}
{104}{}{Uhn...}
{105}{}{Det är bra, mitt barn. Vi ska undersöka dig nu.}
{106}{}{Blessed are the meek of mind. There is nothing wrong with you my child. Run along and play.}
{107}{}{Du har blivit helad. Var mer försiktig i framtiden.}
{108}{}{Du är skadad.}
{109}{}{I see you are poisoned.}
{110}{}{Hmm, lite strålningsförgiftning. Tyvärr kan vi inte bota det.}
{111}{}{Vi kräver en donation på }
{112}{}{ kapsyler innan vi kan läka dig. Är det acceptabelt?}
{113}{}{Ja.}
{114}{}{Nej.}
{115}{}{Men jag har inte så där mycket pengar!}
{116}{}{Kan du ta }
{117}{}{ caps instead?}
{118}{}{Barnen förhandlar inte priser. Accepterar ni vårt pris?}
{119}{}{Yes. Of course I will.}
{120}{}{You can bite me!}
{121}{}{Tack, min son. Låt oss be för ditt helande.}
{122}{}{Tack, min dotter. Låt oss be för ditt helande.}
{123}{}{There you go. Peace and blessings of the Children with you.}
{124}{}{Du har inte tillräckligt med pengar. Om du donerar allt du kan, kommer vi att läka dig. Är det här acceptabelt?}
{125}{}{Ja.}
{126}{}{Nej.}
{127}{}{Om du donerar allt du kan, kommer vi att läka dig. Är det här acceptabelt?}
{128}{}{Ja.}
{129}{}{Nej.}
{130}{}{Du har mer än tillräckligt för att göra en donation. Du behöver undervisning i matematik, mitt barn.}
{131}{}{Vi är Katedralens Barn. Vi lever och arbetar bland de olyckliga som lever i ödemarken. Om du någonsin kommer till L.A. Bengård, stanna till vid katedralen.}
{132}{}{Tack.}
{133}{}{What do you do?}
{134}{}{Vi är helare och fredens lärare. Vi läker kroppen för att läka anden. Allt vi ber om är en liten donation för att betala för våra helande förnödenheter.}
{135}{}{Jag tycker att det låter som en bra idé.}
{136}{}{Sounds like a load of crap to me.}
{137}{}{Vi har inte frågat dig. Jag kan se att du är trött på att lyssna på vår tro. Om du behöver något annat, kommer vi att vara här.}
{138}{}{Det är den heligaste av idéer. Vi arbetar för att uppnå slutlig fred i ödemarken. Alla varelser ska leva som en enda.}
{139}{}{Tack. God dag.}
{140}{}{They donated this house to us, in order that we might spread the word and perform our duty as healers.}
{141}{}{Isn't Doc Morbid upset about this?}
{142}{}{That was awfully kind of them. Thanks.}
{143}{}{Whatever that heathen soul feels is no concern of the Children. We are here to do our duty, and it shall be done.}
{144}{}{Uh, gee, thanks. Bye.}
{145}{}{Varför gör du detta? Vi kommer inte att göra er någon skada!}
{146}{}{You do not have any condition that needs assistance.}
