{100}{}{You have enraged Larry.}
{101}{}{You see: Larry.}
{102}{}{If you disturb the boss, he's gonna hit you.}
{103}{}{Humans are not allowed in Necropolis. You're coming with me.}
{104}{}{Men...}
{105}{}{Never!}
{106}{}{Hngh!!}
{107}{}{Die human!}
{108}{}{The mutant ignores you.}
{1000}{}{Vatten}
{1001}{}{Nekropol}
{1002}{}{Set}
{1003}{}{Vattenskjul}
{1004}{}{Hall}
{1005}{}{Lou}
{1006}{}{Ghouls}
{1007}{}{Normaler}
{1100}{}{I dunno.}
{1101}{}{Yer standin' in it.}
{1102}{}{He's a wus. We should just wipe out him and his ghouls.}
{1103}{}{That's here.}
{1104}{}{I dunno.}
{1105}{}{Han Harrys chef.}
{1106}{}{Wimpy things.}
{1107}{}{Wimpier than ghouls.}
