{100}{}{You see: Mrs. Stapleton, the librarian.}
{101}{}{Du ser en medelålders kvinna.}
{102}{}{Hej, välkommen till biblioteket. Jag tror inte att jag har sett dig här tidigare. Vad kan du tänkas söka i form av kunskap?}
{103}{}{Kul att se dig igen. Vad kan du vara ute efter idag?}
{104}{}{Vad har du i bokväg?}
{105}{}{Jag letar efter ett Vattenchip.}
{106}{}{Inget, men tack ändå.}
{107}{}{Tja, låt mig visa dig mitt urval.}
{108}{}{Tja, under mina studier har jag stött på några referenser till sådana saker. Jag har faktiskt i min ägo en holodisk som innehåller en viss mängd information som du kan finna användbar.}
{109}{}{En holodisk, vad är det?}
{110}{}{Kan jag få holodisken?}
{111}{}{A holodisk contains information on it, but it can only be read by a certain number of electronic devices. I see that you have a Pip-Boy 2000. You can use that to decode, review, and store the information that a holodisk contains.}
{112}{}{Låter jättebra! Kan jag få holodisken?}
{113}{}{Det är svårt att få tag på information nu för tiden. Disken kommer att kosta dig 750 kapsyler.}
{114}{}{Det låter bra. Här är pengarna.}
{115}{}{Det ser ut som en sliten holodisk om jag någonsin har sett en. Jag ger dig 500 för den.}
{116}{}{How about I take a blowtorch to this whole place instead! Huh lady?!}
{117}{}{Sorry, don't have the cash.}
{118}{}{I am sorry but I can only accept the full amount for the holodisk. Please return when you have that amount.}
{119}{}{I am sorry, but you will need to keep your pyromaniacal tendencies to yourself. Please leave.}
{120}{}{[Mrs Stapleton takes your money.]}
{121}{}{You are right, the disk has seen better days. Since that is the case, I will accept 500 instead of my original price. [Mrs Stapleton takes your money.]}
{122}{}{Normally, I do not give in to such methods, but to protect my collection from such a threat I will give you the disk. In exchange, I would ask that you never return here.}
{123}{}{As I may have explained, you will need to use this and then access the information through your Pip-Boy 2000. [Mrs. Stapleton hands you the holodisk]}
{124}{}{You will have to excuse me, but I have research to do.}
{125}{}{Ruk?}
{126}{}{I'm sorry, I don't understand you. Somewhere I have a holodisk on learning the English language, if you're interested.}
{127}{}{Farväl.}
{128}{}{Tack.}
{129}{}{Ug.}
{130}{}{Do you have a set of chemistry journals? Miles in Adytum said you might.}
{131}{}{Yes, I've heard from Miles and I have the ones he's looking for. They will cost you 750 caps.}
{132}{}{Here you are, sir. Say hello to Miles for me.}
{133}{}{I'm sorry, but you don't have enough money. Please return when you have the money.}
