{100}{}{You see a highly advanced Brotherhood computer.}
{101}{}{You are denied access to this terminal.}
{102}{}{The lesson finishes in six hours. You feel exhausted.}
{103}{}{You've already absorbed as much as you can.}
{200}{}{You see a computer. There are some pieces of something on it that might be human flesh.}
{201}{}{You fiddle with the computer for a while, but cannot get past the security system.}
{202}{}{You find an interesting data file on a secret base to the northwest, and download the coordinates into your Pip-Boy.}
{203}{}{Du tjänar }
{204}{}{ experience for hacking into the computer!}
{205}{}{You discover some new information about Mariposa Military Base which you didn't known yet.}
{206}{}{Du tjänar }
{207}{}{ experience for hacking into the computer!}
{208}{}{Du tjänar }
{209}{}{ experience for your detective work}
{210}{}{, but ultimately you don't find any new intel while searching this terminal.}
{211}{}{You've learned all you can from the system.}
{300}{}{This computer is functioning perfectly.}
