{0}{}{ST}
{1}{}{PE}
{2}{}{EN}
{3}{}{CH}
{4}{}{INT}
{5}{}{AG}
{6}{}{LK}
{7}{}{Hit Points}
{8}{}{Armor Class}
{9}{}{  Normal}
{10}{}{  Laser}
{11}{}{  Feuer}
{12}{}{  Plasma}
{13}{}{  Explosion}
{14}{}{[no item]}
{15}{}{Dmg:}
{16}{}{Rng:}
{17}{}{}
{18}{}{(not worn)}
{19}{}{Need more Action Points to access your inventory.}
{20}{}{Total lb:}
{21}{}{MOVE ITEMS}
{22}{}{ALL}
{23}{}{SET TIMER}
{24}{}{Unarmed Dmg:}
{25}{}{You cannot pick that up. You are at your maximum weight capacity.}
{26}{}{There is no space left for that item.}
{27}{}{Okay, that's a good trade.}
{28}{}{No, your offer is not good enough.}
{29}{}{You earn %d experience for successful use of your Steal skill!}
{30}{}{Total lb:}
