{100}{}{Du siehst einen Bewohner Adytums.}
{101}{}{Sieht nach Regen aus... wie immer.}
{102}{}{Sorry, muss los. Hab Arbeit zu erledigen.}
{103}{}{Es kommen nicht viele Außenseiter her.}
{104}{}{Muss zurück an die Arbeit.}
{105}{}{Ich würde zurück zum Hub gehen, wenn ich du wäre.}
{106}{}{Guten Tag... wenn man es so nennen kann.}
{107}{}{Jup... was auch immer.}
{108}{}{Keine Zeit zum Reden.}
{109}{}{Kann gerade nicht reden.}
{110}{}{Ich hoffe, der ist nicht wieder verstrahlt so wie gestern.}
{111}{}{Sieht aus als würde unsere Nahrung wieder knapp werden.}
{112}{}{Ich hoffe, dass die Karawanen bald wieder vorbeikommen.}
{113}{}{Jetzt haben wieder eine Chance, es zu schaffen.}
{114}{}{Adytum wird die Stadt werden, wie wir sie gern hätten.}
{115}{}{Danke für die Hilfe.}
{116}{}{Danke, dass du Regulatoren los geworden bist.}
{117}{}{Danke für unseren Frieden.}
{118}{}{Es ist gut, dass die Regulatoren weg sind.}
{119}{}{Willkommen im neuen Adytum.}
