{100}{}{Du siehst eine betagte Frau.}
{101}{}{Du siehst: Agatha.}
{102}{}{Diese Frau ist faltig und grau, hat aber einen spritzigen Schritt und eine strahlende Persönlichkeit.}
{103}{}{Du bist ein schlechter Mensch. Ich möchte nichts mit dir zu tun haben.}
{104}{}{Es ist eine schreckliche Sache, wenn unsere Jugend bedroht ist. Der Verlust von Tandi wäre eine schreckliche Sache.}
{105}{}{Hnng.}
{106}{}{OK.}
{107}{}{Warum?}
{108}{}{What do you mean?}
{109}{}{I know you will do your best, dearie. Find Tandi, help her escape those beasts and return her to Aradesh. You will do this community a favor and build good karma as well.}
{110}{}{Aradesh loves his daughter very much. It is that love that makes him the man that he is and a pillar of this community. Without that love he would be lost, and Shady Sands would surely follow...}
{111}{}{I will do my best. Goodbye.}
{112}{}{I could use some help.}
{113}{}{Hmmm. We'll see.}
{114}{}{I feel that she is imprisoned. She was the target of hatred. That hate is very strong to the southeast. I'm sure you will find her there. Good luck.}
{115}{}{Danke.}
{116}{}{You have not heard? Tandi is missing. I feel she was kidnapped. Aradesh is most distraught. This is a terrible thing...}
{117}{}{I hear that you have saved Tandi. That was the right thing to do. Your karma is strong. I have high hopes for your future.}
{118}{}{I'm very sorry to hear about Tandi. She was such a bright young woman. She would have done good with her life.}
{119}{}{Hello. You must be the stranger everyone is talking about. *sigh* How can I help you?}
{120}{}{Hngh.}
{121}{}{Wer bist du?}
{122}{}{You look very tired. Is there anything wrong?}
{123}{}{Why do you look so tired?}
{124}{}{Don't talk to me, old woman.}
{125}{}{You need more help than I can give you, child. May Dharma be with you.}
{126}{}{My name is Agatha. I am the storyteller of Shady Sands. It is my job to keep the history so that we may remember and never forget.}
{127}{}{Tell me a story.}
{128}{}{Okay, whatever.}
{129}{}{It is good not to forget.}
{130}{}{I'm sorry, child, I am tired right now. I need my rest. Please come back later.}
{131}{}{How very true. (She stares at you for a moment) It is good for the young to remember, but it is very hard to act within the flow of history. Sometimes, the very course we take is determined by events long ago. May Dharma be with you. I must rest for a little while. Come back again, when I am stronger, and we will speak again.}
{132}{}{Thank you for asking. I'm just old, that's all. I cannot sleep at night. I close my eyes... (She pauses), but I get no rest. Please, it is just my old tired bones...}
{133}{}{I'm sorry, I'm very tired. Could you please come back later?}
{134}{}{Baba.}
{135}{}{OK.}
{136}{}{Why are you so tired?}
{137}{}{I don't sleep well at night, my child. It must be my age.}
{138}{}{Good day, my child. You look well. You remind me of my own baby.}
{139}{}{Hng.}
{140}{}{I want a story, then.}
{141}{}{I'm glad you are feeling better.}
{142}{}{Vielen Dank. Auf Wiedersehen.}
{143}{}{You definitely remind me of my baby. When she was just a few months old, as a matter of fact.}
{144}{}{Thank you. Dharma always said that the farmer who plants politeness will walk easy when the season is over.}
{145}{}{Please tell me a story.}
{146}{}{This Dharma fellow sounds like an idiot.}
{147}{}{You insult your elders. You should know better.}
