{100}{}{You see: Heather, of the Followers' scouts.}
{101}{}{Was machst du hier?}
{102}{}{Dis!}
{103}{}{Go bye.}
{104}{}{Ich schau mich nur um.}
{105}{}{I am here to kill you!}
{106}{}{Just curious as to what is going on around here.}
{107}{}{Really? And what might you be looking for?}
{108}{}{I think I have already found her.}
{109}{}{I am looking for a spy.}
{110}{}{Nothing really. Just looking around.}
{111}{}{Just information.}
{112}{}{Thank you, but I am already spoken for. I think it is time for you to leave.}
{113}{}{Yes, the spy. I have heard of that bothersome pest. I really wish we could catch him.}
{114}{}{I kept hearing that it was a female spy.}
{115}{}{Have you heard anything about this spy?}
{116}{}{You are the spy!}
{117}{}{Good luck to you. Sorry I bothered you.}
{118}{}{I bet it was the braggart Neil that said as much. I'll need to have a talk with him later.}
{119}{}{You think that Neil is the spy?}
{120}{}{Then who do you think the spy is?}
{121}{}{You sound a bit defensive. Any reason why?}
{122}{}{I am almost sure of it. I just need some proof.}
{123}{}{I will get you proof.}
{124}{}{He seems like a nice person. I don't know.}
{125}{}{Why do you think it is him?}
{126}{}{Thank you. You don't know how much this means to me. Once you get proof, kill him.}
{127}{}{What is there not to know? He has access to the Children. He works during the night when most are asleep. It has to be him.}
{128}{}{Okay, I will check into it.}
{129}{}{Forget it. I think you are trying to divert me!}
{130}{}{I am truly sorry that you think that way. I cannot have someone think I am a spy. I will remove you from service.}
{131}{}{He has access to the Children during the night. No one ever sees him on duty. It must be him.}
{132}{}{Okay, I will check into it.}
{133}{}{Forget it. I think you are trying to divert me!}
{134}{}{I am not certain as to whom it is. I think it may either be a guard or a scholar. They keep sneaking into the Children's Cathedral at night.}
{135}{}{Any other leads that you can think of?}
{136}{}{But I've heard talk that only the scouts do raids on the Children.}
{137}{}{Okay. Thank you for your help.}
{138}{}{Not really. Just that I think it is a male and probably a scholar or guard.}
{139}{}{Okay. Thank you for your help.}
{140}{}{True. We scouts do many raids on the Children, and to much loss lately. This spy costs us dearly.}
{141}{}{You seem really torn up about this. I will look for the spy and kill him.}
{142}{}{Could the spy be a scout?}
{143}{}{Danke für die Hilfe.}
{144}{}{Why would one of us do that?}
{145}{}{If you kill off the scouts, then you stop the raids.}
{146}{}{I don't know. Why would you do that?}
{147}{}{Don't know. Just wondering.}
{148}{}{Sounds like a good thought. I've noticed Peter never gets attacked much in the raids. I think he may be the one.}
{149}{}{Okay, I will check into it.}
{150}{}{Forget it. I think you are trying to divert me!}
{151}{}{You think that it is me?}
{152}{}{I'm sorry. I'm just a bit jumpy.}
{153}{}{Yes! Now you will die!}
{154}{}{Then wonder somewhere else. I must get back to work.}
{155}{}{I think he thinks I am the spy, but I'm not.}
{156}{}{Maybe he is right.}
{157}{}{Why would he think that?}
{158}{}{Because I am the new scout. I've only been here for about a year and the trouble started about five months ago.}
{159}{}{I think Neil may be right.}
{160}{}{I think Neil might be the spy. I'll go check into it.}
{161}{}{Then look elsewhere. This is no place for you.}
{162}{}{If you need information, look to Nicole. She thinks she knows everything.}
{163}{}{I can be persuaded to tell you something that's going on, for a price.}
{164}{}{How much?}
{165}{}{You would sell secrets?}
{166}{}{Forget it. I have no money.}
{167}{}{Three hundred caps and the information is yours.}
{168}{}{Sicher.}
{169}{}{Niemals.}
{170}{}{There will be a raid on the south end of the Children's stronghold. Now go.}
{171}{}{Trying to cheat me? I'll show you!}
{172}{}{I'm sorry you feel that way. But, good day to you.}
{173}{}{I need to get by somehow. Now, do you want in or not?}
{174}{}{Sicher.}
{175}{}{Niemals.}
{176}{}{Nothing. Now leave.}
{177}{}{Leave me. I am trying to get some rest.}
