{100}{}{You see a drunk.}
{101}{}{You see a customer.}
{102}{}{You see a sleazy-looking woman.}
{103}{}{You see a strange-looking man.}
{104}{}{You see a gambler.}
{105}{}{You see a very pretty lady. She seems to be busy.}
{106}{}{Du siehst eine Frau.}
{107}{}{Du siehst einen Mann.}
{108}{}{You see a very upset gambler.}
{109}{}{You see a mercenary.}
{110}{}{Leave me to my sorrows.}
{111}{}{Yer my bestest friend.}
{112}{}{Why you're... *hic* where am I?}
{113}{}{Wer bist du?}
{114}{}{Do I know you?}
{115}{}{Mir ist ein bisschen übel.}
{116}{}{Drinks are on me... I mean, you.}
{117}{}{Why are there two of you?}
{118}{}{Stand still, laddie!}
{119}{}{Stand still, lassie!}
{120}{}{Beat it, skag!}
{121}{}{Yer droppin' the class of this joint.}
{122}{}{Get away, you'll jinx me!}
{123}{}{Don't break my concentration.}
{124}{}{I'll beat this damn game yet!}
{125}{}{You any good at this?}
{126}{}{Did you see that? That was impossible!}
{127}{}{I think they're cheating.}
{128}{}{Now those are good odds.}
{129}{}{It's a sure thing.}
{130}{}{What? How could I have lost?}
{131}{}{This table's jinxed!}
{132}{}{I'm busy.}
{133}{}{Can't you see I'm playing a game here?}
{134}{}{Bet it or beat it.}
{135}{}{Leave us alone or I'll call the guards.}
{136}{}{Watch it, I'm a close friend of Deputy Fry.}
{137}{}{Do you mind?}
{138}{}{No peep shows!}
{139}{}{I don't do groups.}
{140}{}{I'm too tired for another one.}
{141}{}{You're dreaming, pal. Beat it!}
{142}{}{Get the hell out!}
{143}{}{What the hell do you think you're doing?}
{144}{}{Mind your manners!}
{145}{}{I'll call the cops!}
{146}{}{Don't even think about it!}
{147}{}{Get out!}
{148}{}{Beat it!}
{149}{}{What are you staring at?}
{150}{}{Are you part of the combo?}
{151}{}{Get the hell out of our room!}
{152}{}{Get out!}
{153}{}{Are you part of the combo?}
{154}{}{Beat it, pervert!}
{155}{}{What's your problem?}
{156}{}{Beat it before I get angry.}
{157}{}{Get your own.}
{158}{}{She's mine.}
{159}{}{Damn!}
{160}{}{Are you cheating?}
{161}{}{That should have been mine.}
{162}{}{Almost!}
{163}{}{Just missed it.}
{164}{}{What're the rules again?}
{165}{}{I used to be good at this.}
{166}{}{Thanks for nothing.}
{167}{}{I don't believe it!}
{168}{}{I meant to do that, honest.}
{169}{}{Place your bets.}
{170}{}{Keep your hands away, sir.}
{171}{}{Winner!}
{172}{}{Sorry folks, maybe next time.}
{173}{}{Another winner!}
{174}{}{Hands off!}
{175}{}{Your turn, sir.}
{176}{}{Sorry, that's an invalid bet.}
{177}{}{That's it.}
{178}{}{Anyone else?}
{200}{}{Hey darlin', lookin' for a good time?}
{201}{}{What'ya lookin for, darlin'?}
{202}{}{Lookin' for some company?}
{203}{}{Hey there, cutie.}
{204}{}{You like what you see? I do.}
{205}{}{Show me what you got, sugar.}
{206}{}{I like it rough, if you're into that.}
{207}{}{No diseases; I'm clean!}
{208}{}{I do groups, for a little extra.}
{209}{}{I'll do anything for the right price...}
{210}{}{I've never been with a girl before...}
{211}{}{I'm your dream come true, sugar.}
{212}{}{If you've got the caps, i'm in.}
{213}{}{You like what you see? I do.}
{214}{}{Hey there, sweet pea.}
{215}{}{Hey darlin', lookin' for a good time?}
{216}{}{I like it rough, if you're into that.}
{217}{}{No diseases; I'm clean!}
{218}{}{I do groups, for a little extra.}
{219}{}{I'll do anything for the right price...}
{220}{}{How much does the fun cost?}
{221}{}{Twenty caps.}
{222}{}{Let's get down to business...}
{223}{}{No thanks, not interested.}
{224}{}{Thanks for the good time. I'll see you later.}
{225}{}{How much for some group action?}
{226}{}{A hundred caps.}
{227}{}{Alright. What'chya lookin for, darlin'?}
{228}{}{Alright, follow me...}
{229}{}{Thanks, stranger. (She pockets the caps and blows you a kiss)}
{230}{}{Lapdance.}
{231}{}{Striptease.}
{232}{}{Pritty lady. With me?}
{233}{}{Oh god... darlin' I gotta make a livin' but even I have standards.}
{234}{}{Have some fun with yourself, I'll just watch.}
{235}{}{ME WANT!}
{236}{}{The usual.}
{237}{}{Anything and everything! Surprise me...}
{238}{}{Hmph.}
{239}{}{Sorry darlin'. If you find yourself a new brain, come back and see me.}
{240}{}{Mmf. Oh-k, me go.}
{241}{}{Depends on what you're lookin' for, honey.}
{242}{}{Alright, everyone follow me...}
{243}{}{Cap?}
{244}{}{*sigh* Yes, you idiot. Bottle caps. Pay me 150 and I'll show you a good time. That should be enough for me to drown my shame at the Falcon and still make a profit.}
{245}{}{I don't care, let's just get this over with.}
{246}{}{Just sex.}
{247}{}{For you, }
{248}{}{For you, sugar? }
{249}{}{Okay, sounds good.}
{250}{}{On second thought, never mind.}
{251}{}{Suit yourself, sugar. You'll be back.}
{252}{}{I don't have that many caps.}
{253}{}{Then why the fuck are you even talking to me? Get out!}
{254}{}{[Continue]}
{255}{}{[Fertig]}
{256}{}{Thanks, sugar. Come back soon!}
{257}{}{Here go.}
{258}{}{Me no got monies...}
{259}{}{Hmph!}
{260}{}{I can't believe I'm even doing this...}
{261}{}{Get out of here. I'm gonna go throw up now.}
{262}{}{I need to get a new job.}
{263}{}{You again? Fuck off, I don't work with retards that can't pay.}
{264}{}{Urr...}
{265}{}{Buh?}
{300}{}{ caps.}
{301}{}{Upon further inspection, it's obvious that this is a prostitute with a customer. She motions for you to leave, immediately.}
{302}{}{Upon further inspection, it's obvious that this is a prostitute. She flashes you a fake smile.}
{400}{}{Well that was interesting.}
{401}{}{Wuff!}
{402}{}{We should get back to work now.}
{403}{}{Ugh, I feel dirty.}
{404}{}{Oh wow...}
{405}{}{Well... I guess I could make an exception. You better have a helluva lot of caps though.}
