{100}{}{This is a strange-looking diskette of some sort. Perhaps it can be used in your Pip-Boy 2000.}
{101}{}{Pip-Boy 2000 displays: "Downloading ... Aborting, data already exists!"}
{102}{}{Pip-Boy 2000 displays: "Downloading data ... ... ... Done. Have a nice day!"}
{103}{}{This disk is in bad shape. It has no proper label but has "overide" scratched onto the side.}
{104}{}{You see: Security Override Disk.}
{105}{}{Username: "admin". Password: "muerte". Security override protocol: Gamma Omicron Delta.}
{106}{}{**BEGIN-DISK**}
{107}{}{**ENDE-DISK**}
{108}{}{[Continue]}
{109}{}{Pip-Boy 2000 displays: 'Username: "admin". Password: "muerte". Security override: Gamma Omicron Delta.'}
