{100}{}{This is a strange-looking diskette of some sort. Perhaps it can be used in your Pip-Boy 2000.}
{101}{}{Pip-Boy 2000 displays: "Downloading ... Aborting, data already exists!"}
{102}{}{Pip-Boy 2000 displays: "Downloading data ... ... ... Done. Have a nice day!"}
{103}{}{You notice the disk has a faded and worn label that reads "Delta Experiments Log".}
{104}{}{You see: Delta Experiments Disk.}
{105}{}{The Military has deemed it necessary for us to research further in-depth the effects of wave technology upon living organisms. We have taken light and sound as the basis of our studies. By manipulating the amplitude of the light waves and magnifying the frequency, we have been able to get lasers which will cut through a few feet of steel. Unfortunately, the power to do such a task has not been fully developed. We have other scientists looking into this.}
{106}{}{**BEGIN-DISK**}
{107}{}{**ENDE-DISK**}
{108}{}{[Continue]}
