{100}{}{You have broken out of the jail. You're now definitely a fugitive in Junktown!}
{101}{}{The door looks solid, and has a stout lock. Still, locks can be picked, and doors can be destroyed.}
{102}{}{The door is locked.}
{103}{}{Du sperrst die Tür auf.}
{104}{}{Du verriegelst die Tür.}
{105}{}{You fail to unlock the door.}
{106}{}{Du konntest die Tür nicht abschließen.}
{107}{}{You earn 250 experience for busting out of jail!}
