{100}{}{You see a Knight.}
{101}{}{You see a Scribe.}
{102}{}{Was machst du hier?}
{103}{}{Wer bist du?}
{104}{}{Haven't I seen you before?}
{105}{}{This is my room, please leave.}
{106}{}{Please leave my room.}
{107}{}{This isn't your room.}
{108}{}{Initiate rooming is on the second level.}
{109}{}{Are you lost?}
{110}{}{I believe your quarters are on level two.}
{111}{}{I'd appreciate some privacy.}
{112}{}{Hi there, nice to see you.}
{113}{}{Hallo.}
{200}{}{Hey.}
{201}{}{Hallo.}
{202}{}{Good day.}
{203}{}{Ja?}
{204}{}{What?}
{205}{}{Whats up?}
{206}{}{Was willst du?}
{207}{}{You want something?}
{209}{}{Hau ab.}
{210}{}{Stop bothering me.}
{211}{}{Lass mich in Ruhe.}
{212}{}{You are annoying me.}
{213}{}{He ignores you.}
{214}{}{She ignores you.}
