{100}{}{You are nearly crushed by a large boulder in an avalanche.}
{101}{}{You escape with no damage.}
{102}{}{The displaced rock brings with it the remains of a long-dead traveler.}
{103}{}{Your leg is critically damaged by falling rocks.}
{104}{}{Some rock shards slice your face and hands, but you escape with minimal damage.}
{105}{}{Radscorpions!!}
{106}{}{A particularly sneaky radscorpion seems to be trying to ambush you.}
{107}{}{Out of nowhere, a radscorpion suddenly strikes!}
{108}{}{You have stumbled upon a family of mole rats.}
{109}{}{You are overtaken by a landslide.}
{110}{}{Amazingly, you escape with no damage.}
{111}{}{The displaced rock reveals a gold deposit!}
{112}{}{Your leg is critically damaged by falling rocks.}
{113}{}{Some rock shards slice your face and hands, but you escape with minimal damage.}
{114}{}{You are traveling through sheer cliffs and rugged terrain.}
{115}{}{ fortunately, your climbing skills are up to the task.}
{116}{}{You find a cave with a small spring and manage to get your first good night's sleep in a long time.}
{117}{}{You fall from a ledge, landing on several sharp stones.}
{118}{}{You fall from a cliffside to the rocky ground below.}
{119}{}{You stumble onto a large pack of radscorpions.}
{120}{}{You find several rats scavenging about here.}
{121}{}{You see a lone traveler in the distance.}
{122}{}{The ground ahead is littered with debris and bodies. It looks like an old battle zone.}
{123}{}{You lose your footing on the rocky terrain.}
{124}{}{You skillfully escape with no damage.}
{125}{}{You escape with no damage. The displaced rock reveals a gold deposit!}
{126}{}{Your leg is critically damaged by falling rocks.}
{127}{}{Some rock shards slice your face and hands, but you escape with minimal damage.}
{128}{}{You see a lone radscorpion, skittering about.}
{129}{}{Tremendous mole rats are nosing about here.}
{130}{}{You find several rats scavenging about here.}
{131}{}{Exhausted, you nearly fall over some rough terrain. They could really use a GECK out here!}
{132}{}{You slip on the uneven terrain and twist an ankle, painfully. It makes several unhealthy sounds.}
{133}{}{You fall over the rough terrain and scrape some flesh.}
{134}{}{You see several rats running toward you.}
{135}{}{You come across the bones of a long-dead traveler.}
{136}{}{You stumble onto a pack of hostile radscorpions.}
{137}{}{You see the camp of a traveling raider band. Looks like you've come to the wrong place at the wrong time.}
{138}{}{You sustain }
{139}{}{ points of damage and a crippled left leg.}
{140}{}{ points of damage and a crippled right leg.}
{141}{}{ Trefferpunkte.}
{142}{}{You refill your empty flask in the spring.}
{143}{}{You refill your empty flasks in the spring.}
{144}{}{ points of damage and a crippled left arm.}
{145}{}{ points of damage and a crippled right arm.}
{146}{}{ points of damage and two crippled limbs.}
{147}{}{Your pitiful attempt to escape the rocks is a colossal failure. All of your limbs are crushed and battered in a spectacular spray of blood. Amazingly, you survive.}
{148}{}{You fail to find any handholds during the fall, and land with a mighty crash, crushing both your legs like radroaches.}
